### ISSUE TITLE
Bitbucket Pull Requests

### ISSUE THREAD

**Issue by clounie** [ForkIssues/Tracker#1]
I saw you had Github now, which is awesome; would be great to have Bitbucket as well.

**Comment by DanPristupov** [comment]
Hi,

Thanks for the request. I'll investigate the BitBucket API and implement the support in one of the following updates.

**Comment by floq-design** [comment]
+1 for bitbucket integration

**Comment by clounie** [comment]
Would still be great to have. Bitbucket PR/ PR Approval / PR Merge are the only actions in my workflow that are outside of Fork, at this point.

**Comment by DanPristupov** [comment]
@clounie Ouch, this is number 1 issue and it's still open. Thank you for reminding me about it.

**Comment by mika76** [comment]
Another vote for bitbucket - I use it more than github - and know plenty of people who do, mostly because of free private repositories...

**Comment by DanPristupov** [comment]
I added the BitBucket integration in 1.0.70. At the time it supports login/password authentication only.
