### ISSUE TITLE
What means the yellow icon?

### ISSUE THREAD

**Issue by frameworker2019** [ForkIssues/Tracker#1000]
I have several files with a   yellow icon in front. It seems changes to  file access attributes will be interpreted. The file is stagable despite the right window remains empty in some cases.

**Comment by frameworker2019** [comment]
Okay, I see. To resolve the problem I had to change filemode = false inside .git/config.
Could it be, that in one of the previous versions filemode=false was the default?

**Comment by frameworker2019** [comment]
Bonmot: Is there a price for the 1000th issue? :-)

**Comment by DanPristupov** [comment]
The yellow icon shows a file modification (it can be both content change and the file mode change)
