### ISSUE TITLE
[bug] resolve conflict: inverted labels?

### ISSUE THREAD

**Issue by StefanoCecere** [ForkIssues/Tracker#1006]
i feel it very weird:

if i choose my "local" master change.. i'd expect the label not to be "choose theirs"

![Screenshot 2020-05-07 at 10 55 32](https://user-images.githubusercontent.com/640536/81275149-8cf77600-9051-11ea-842f-ca717c8bb2e4.png)

**Comment by DanPristupov** [comment]
You probably used rebase.

Anyway, I agree, the label can be improved.

**Comment by StefanoCecere** [comment]
I confirm, i was rebasing

**Comment by DanPristupov** [comment]
https://stackoverflow.com/a/25576672

I think we should get rid (when possible) of the confusing local/remote and ours/theirs terminology

**Comment by Wevah** [comment]
Seconded; selecting my local version during a rebase makes the label say "remote", which feels backwards.
