### ISSUE TITLE
Selecting very large files hangs Fork

### ISSUE THREAD

**Issue by clusty** [ForkIssues/Tracker#1007]
From time to time I select by mistake every large binary files (2+GB) that will are not ignored, but will never be committed either.
This causes fork to get stuck for long while.

Might consider bailing out on file processing when it's over a certain size...

**Comment by ibushong** [comment]
I have this issue too, namely with large `.sql` (text) dump files. I'm pretty sure I've seen it bail with a message about not being able to diff large files, but it seems like that detection isn't working properly

**Comment by austinarbor** [comment]
For me I don't even have to select the file. As long as the file appears in the unstaged file section, staging or operating on any file in that area causes the app to crash

**Comment by msklywenn** [comment]
We do have large files too and even commit them (with LFS). On Windows it's pretty much fine but on macOS it completely freezes the client and I always end up killing fork and merging from the command line :'( (well, not even merging, just selecting mine or theirs)
