### ISSUE TITLE
File is not ignored

### ISSUE THREAD

**Issue by Evstyunin** [ForkIssues/Tracker#1008]
I changed local .gitignore so that I could commit "local.properties" file, commited it and then I changed .gitignore back, so that this "local.properties" file is now ignored again. But now Fork tracks this file and shows changes despite it being listed in .gitignore. I made all changes to .gitignore locally and did not commit it.

**Comment by DanPristupov** [comment]
.gitignore only works with untracked files.

You need to remove the file on disk.

**Comment by Evstyunin** [comment]
So there is no way around it if I don't want to track changes to this file and let it be as it is on remote but also keep the local version?

**Comment by DanPristupov** [comment]
Starting from 1.0.94 Fork will also untrack the ignored files.
