### ISSUE TITLE
Add text labels to toolbar buttons

### ISSUE THREAD

**Issue by unikitty37** [ForkIssues/Tracker#1014]
The toolbar buttons are image-only, and finding out what a button does requires mousing over it and waiting for a tooltip to appear.

Standard OS X toolbars always used to have options for image-only, text-only, or image with a text label underneath it, but these seem to have gone out of fashion.

Please could we have the option for text labels in the toolbar?

**Comment by DanPristupov** [comment]
Fork -> Preferences -> Use old toolbar style
