### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by nathanpovo** [ForkIssues/Tracker#1015]
Around twice a week Fork is crashing randomly during a normal workload.

I get no error messages, the application just crashes and closes. I can then open the application again and resume as if nothing happened.

The log file does not seem to contain any information regarding the crash but I'm including the last part of the log file, just in case. Note that this is before I reponed the application.

    D 2020-05-15 09:00:35.449 Detected changed reference
    I 2020-05-15 09:00:35.562 Refresh 'MyRepoName' data. Updated.
    I 2020-05-15 09:00:35.562 RefreshAheadBehindInfo
    I 2020-05-15 09:00:48.428 Application Window Activated
    I 2020-05-15 09:00:48.428 RefreshRepositoryStatus
    I 2020-05-15 09:00:48.533 Refresh 'MyRepoName' status. Updated 4 files
    I 2020-05-15 09:00:48.533 RefreshRepositoryData
    D 2020-05-15 09:00:48.533 MyRepoName RefreshRepositoryDataGitCommand All
    D 2020-05-15 09:00:48.585 MyRepoName Repository data are equal. No Changes
    I 2020-05-15 09:01:17.552 Application Window Activated
    I 2020-05-15 09:01:17.552 RefreshRepositoryStatus
    I 2020-05-15 09:01:17.655 Refresh 'MyRepoName' status. Updated 5 files
    I 2020-05-15 09:01:17.655 RefreshRepositoryData
    D 2020-05-15 09:01:17.655 MyRepoName RefreshRepositoryDataGitCommand All
    D 2020-05-15 09:01:17.709 MyRepoName Repository data are equal. No Changes
    I 2020-05-15 09:01:20.510 # New Changed Files: 5
    I 2020-05-15 09:01:21.384 # New Changed Files: 5

Log immediately after I reopen the application:

    D 2020-05-15 09:11:07.029 Loading settings.
    I 2020-05-15 09:11:07.146 Importing repositories from old format
    I 2020-05-15 09:11:07.146 Importing repositories from old format
    I 2020-05-15 09:11:07.173 Start ipc server Fork_9016_Pipe_AskPass
    I 2020-05-15 09:11:07.173 Start ipc server Fork_9016_Pipe_Default
    D 2020-05-15 09:11:07.173 Waiting for next cross-process event '401'
    D 2020-05-15 09:11:07.173 Waiting for next cross-process event '401'
    I 2020-05-15 09:11:07.875 Fork 1.49.1.0 at C:\Users\nate9\AppData\Local\Fork\app-1.49.1\Fork.exe
    I 2020-05-15 09:11:07.875 Git Location: C:\Program Files\Git\bin\git.exe
    I 2020-05-15 09:11:07.875 Log target: AppData log file
    I 2020-05-15 09:11:08.025 Last update check: 14/05/2020 18:37:58. Next one: 15/05/2020 18:37:58
    I 2020-05-15 09:11:08.171 Restoring 3 sessions.
    I 2020-05-15 09:11:08.570 RefreshRepositoryData
    I 2020-05-15 09:11:08.579 Main: 462, Window: 1450, WindowLoaded: 295, UiReady: 408, Total: 2153

**Comment by DanPristupov** [comment]
Is that possible that you work in a fire walled environment?

**Comment by nathanpovo** [comment]
I am using the application on my home computer, which does not have any weird configurations.

What I do have is an unreachable remote; the remote of the repository is on a company gitweb (which it cannot access on this computer).
