### ISSUE TITLE
[Feature Request] Adjust sorting branches

### ISSUE THREAD

**Issue by noelforte** [ForkIssues/Tracker#1018]
I've noticed as I've used fork that branches with names such as "develop" or "master" get hoisted to the top. The rest of the branches fall into folders and then single branches based on name alphabetically. However if you're someone that doesn't organize your branches with this naming convention (like using "dev" instead of "develop") then your branches fall out of what might be an order where they're easy to find.

![Screen Shot 2020-05-18 at 1 31 17 AM](https://user-images.githubusercontent.com/2560683/82177642-23c0ff80-98a8-11ea-9544-7c27b18799ee.png)

I'd propose either allowing for the branches to be sorted by hand, sorted by a list of predefined options or maybe adding additional common keywords for branches that should be hoisted.

**Comment by DanPristupov** [comment]
Currently there are 3 options:

<img width="328" alt="Screenshot 2020-05-18 at 07 46 59" src="https://user-images.githubusercontent.com/618115/82178211-c21a8880-98db-11ea-8239-627a0b54afd6.png">

I think sorting by hand and the custom sort options are excessive.

**Comment by noelforte** [comment]
Agreed. I also noticed that "develop" gets bumped to the top too...is that a side behavior of "master and folders on top"? Would it be possible to add "dev" to that as well for those that use it?

**Comment by DanPristupov** [comment]
> is that a side behavior of "master and folders on top"? 

Yes.

>  Would it be possible to add "dev" to that as well for those that use it?

No, because 'dev' is not a commonly used branch name. The 'develop' branch though is the default branch in git-flow repositories.

**Comment by noelforte** [comment]
Makes sense, thanks for clarifying.
