### ISSUE TITLE
Add support to view change in external diff tool

### ISSUE THREAD

**Issue by sirnacnud** [ForkIssues/Tracker#102]
There is no support to view the changes to a file in an external diff tool. You can only use the "eyeball" button to view the changes to a file in the side-by-side view.

It would be nice for users to be able to open the change in an external diff tool, as the side-side view is limited (can't see whole file).

**Comment by DanPristupov** [comment]
I added support for external diff tools in Fork 1.0.62. Currently FileMerge, BeyondCompare, Kaleidoscope, KDiff3 and P4Merge are supported. I also implemented support for Araxis, but could not test it because can't get the trial license.

**Comment by sirnacnud** [comment]
Thank you for adding this. This was one of the big missing features, at least for me, when moving from SourceTree to Fork.
