### ISSUE TITLE
Show in Finder opens a bunch of Finder windows

### ISSUE THREAD

**Issue by mtschoen-unity** [ForkIssues/Tracker#1027]
I was looking at a rather big set of pending changes in folder view recently and clicked "Show in Finder" in the context menu on the root folder. This took a few seconds and then opened a _lot_ of Finder windows. It seems like it opened a window for each of the folders in the hierarchy of changes.

I did not have a multiple-selection.

**Comment by StefanoCecere** [comment]
i keep facing this quite annoying bug!

**Comment by dv336699** [comment]
Just came across this "issue". We are all used to `Show in finder` when selecting a directory and expecting one Finder window. However, Fork tries to be clever and open in finder all files that changed within that directory - _this is wrong_.

If you select 2 files from 2 different directories and request to Show in Finder, you will get 2 windows, which is cool, but I think that the behaviour should follow any other software, meaning if you select one or two directories, it should open that directory, not a finder window for each file within each directory.
![image](https://user-images.githubusercontent.com/930792/91051500-20ac7c80-e618-11ea-8037-0889e94c87be.png)

**Comment by dv336699** [comment]
@DanPristupov a year later and this is still an issue, any chance this can be fixed?

Many thanks

**Comment by DanPristupov** [comment]
@diego-vieira thank you for reminding me
