### ISSUE TITLE
"Discard" shortcut does not work with box appearing on mouse hover

### ISSUE THREAD

**Issue by hmemcpy** [ForkIssues/Tracker#103]
When I select a few lines in the diff window, and press Cmd+Shift+D, I get the Discard dialog for the selected lines, which is the expected result:
![image](https://user-images.githubusercontent.com/601206/30776334-fd56412a-a0ac-11e7-8129-f312f0e767fd.png)

However, if I just hover over a hunk, when I get the selection box:
![image](https://user-images.githubusercontent.com/601206/30776345-1dd59518-a0ad-11e7-98a1-6a869648d15d.png)

Pressing the Discard shortcut key tries to discard the entire file!

I would expect it to activate the **Discard changes...** button on the box.

**Comment by DanPristupov** [comment]
Hi,

This is a tricky question. Technically, there's no selection, so the shortcut should be applied to the whole file. Hovering mouse over an element doesn't make it selected.

I need to figure out how this behave is os x.

**Comment by clounie** [comment]
Agreed with @hmemcpy here...having the button and keyboard shortcut do different things given the same visual cue is pretty confusing. 

Maybe one answer could be letting the user select hunks? That way you maintain consistency with the standards you mentioned, Dan, but also provides the user a clearer pattern of behavior to cue off of.

**Comment by DanPristupov** [comment]
@clounie not sure about allowing users to select hunks. I don't want to complicate things so much. Then we will get requirements for obvious selection mechanics: move selection by up/down arrow keys, multiselection, selection with cmd etc.

Probably it should work like @hmemcpy advised and highlight or blink the active chunk after pressing the key, so user could clearly see what chunk is currently processed.
