### ISSUE TITLE
Copy folder name in commit dialog

### ISSUE THREAD

**Issue by DmitryZemlyuk** [ForkIssues/Tracker#1036]
STR:
1) macOS 10.15.2 (19C57)
2) Fork (1.0.93.6)  -> open commit dialog window

Hi =)
Could you please return possibility for copy folder name in commit dialog?(amazing feature)

Actual Result: 
I decide to commit some changes to my repo, and I want copy **folder name** with changed file. 
If I check "copy file name" on folder In actual Fork update(1.0.93.6) => and paste clipboard content to commit subject: changed **filename** will be inserted.
![actual](https://user-images.githubusercontent.com/9571965/83539665-fa3ae180-a4ff-11ea-9cdd-271655d3208c.jpg)

Expected Result:
I decide to commit some changes to my repo, and I want copy **folder name** with changed file. 
1) If I check "copy file name" on folder In actual Fork update => and paste clipboard content to commit subject: **folder name** will be inserted.
2)  If I check "copy file name" on changed file or any file In actual Fork update => and paste clipboard content to commit subject: **changed file or any file** will be inserted.

![expected](https://user-images.githubusercontent.com/9571965/83539658-f7d88780-a4ff-11ea-8153-249d708c3c05.png)

**Comment by DanPristupov** [comment]
Hi. Thank you for the bug report. We will fix this in the next update.
