### ISSUE TITLE
Crash on open if configured custom git instance is removed

### ISSUE THREAD

**Issue by juamms** [ForkIssues/Tracker#1038]
Hi there, 
I was testing a more recent version of git that I installed via homebrew, and after testing it I uninstalled it without first reverting the git instance in Fork. This lead to Fork repeatedly crashing with the following error:

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'launch path not accessible'`

The issue is easily fixed by reinstalling git from homebrew and reconfiguring Fork to use one of the available git instances, before uninstalling it again.

### Steps to reproduce:
* Install another git instance (for example, from homebrew);
* Open Fork's preferences and select the custom git instance;
* Quit Fork;
* Uninstall the previously installed git instance;
* Open Fork;

Let me know if you need anything more from me!
Cheers

**Comment by DanPristupov** [comment]
Fixed in Fork 2.27. Thank you for the bug report!
