### ISSUE TITLE
[Feature Request] Double-click staged/unstaged single file should open the file by default associated App 

### ISSUE THREAD

**Issue by xohozu** [ForkIssues/Tracker#104]
**Motivation**: 
Double-click is common action that user want to open the file, while clicking option check-box is switch the file state in general.

**Comment by clounie** [comment]
I'd be pretty surprised if a Git client opened the file on double click. It's a git client, not a code editor..

**Comment by DanPristupov** [comment]
I agree with @clounie.  While I assume that opening a file by double click could be useful, it's not a behaviour which users expect double clicking on a file in a git client.

Opening file in default app is very accessible in Fork, just right-click on a file and select "Open' in the context menu. Technically it's 2 clicks too ;).

I could add a shortcut to open selected file in default editor, but I don't remember any which is used in macOS.
