### ISSUE TITLE
When creating a branch and pasting text into the name field, turn the colon character into a safe character

### ISSUE THREAD

**Issue by dwcramer** [ForkIssues/Tracker#1040]
One of my favorite little touches about Fork is that when I use it to create a branch and paste the bug number and name from Jira, Fork replaces all the spaces with dashes. However, if the text I'm pasting in contains a colon `:` character, the paste fails. I would prefer if it accepted the paste and turned the colon into some safe character like an underscore or dash.

**Comment by DanPristupov** [comment]
We implemented that in 1.0.94
