### ISSUE TITLE
Strange file capitalization issue

### ISSUE THREAD

**Issue by matkatmusic** [ForkIssues/Tracker#1041]
I had a file in my repo named `alphaomega.h`
I deleted it from my repo and it moved into the recycle bin (OS X).  I did not empty the recycle bin.
I created 2 new files in my repo: `AlphaOmega.h` `AlphaOmega.cpp`.
I filled them in with the code I needed them to have, and committed them.
Fork showed that the `alphaomega.h` had its contents changed but the file name was not changed to have capitalized `A` and `O`
The file in the repository had the capitalized `a` and `o`.  but when I viewed the remote, the file name was entirely lowercase. 

I'm not sure if this is a `git` setting about storing capitalization in file names, or if this is because I didn't empty the recycle bin before creating the new header file with the same name, or if this is because I didn't make a commit for that file being deleted before creating the new files.  Either way, I expected the capitalized filename to appear in the repo history, and it didn't.  I had to edit the file name on the remote in order for it to show up in the git history, so that I could then pull the correctly-named file into the local project from the remote.

**Comment by 153957** [comment]
This is a git thing. You can rename the file via your Terminal using `git mv alphaomega.h AlphaOmega.h` ( https://stackoverflow.com/a/24979063/ ), and then changing the content of the file.
You need to inform git about the rename, since macOS and git are usually case-insensitive.

**Comment by cpyfferoen** [comment]
Everything you might want to know on Git and case sensitivity
https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreignoreCase
https://stackoverflow.com/a/8482021/4713489
https://docs.microsoft.com/en-us/azure/devops/repos/git/case-sensitivity?view=azure-devops

**Comment by DanPristupov** [comment]
I think we can close this.
