### ISSUE TITLE
Make unmerged branch deletion keyboard accessible

### ISSUE THREAD

**Issue by MattTreichelYeah** [ForkIssues/Tracker#1043]
![image](https://user-images.githubusercontent.com/6729569/84047580-735f8c00-a979-11ea-95fc-d9bca0d40b4f.png)

I can press "Delete" on a branch in the All Commits view and "Enter" to get past the subsequent window, but this next warning doesn't seem to be keyboard accessible. I can't tab to the button. I have to do this a lot to clean up local branches that have been squashed and merged on remote, so it's a bit awkward.

**Comment by MattTreichelYeah** [comment]
Seems this is better in some recent version 🤔

**Comment by DanPristupov** [comment]
Actually, we are going to remove that warning in the upcoming update :)
