### ISSUE TITLE
Image diff problems with external diff tool Beyond Compare 4

### ISSUE THREAD

**Issue by bilalyaylak** [ForkIssues/Tracker#1044]
When I try to check difference between two revisions of a png file with Beyond Compare, Fork sends those two files to BC4 without png extension. Therefore, BC4 doesn't consider them as image files. 

I tried using BC4 with Rider IDE. Rider keeps extensions of old and new versions of the file while sending them to BC4 application. It works without any problem.

Can Fork keep file extensions even if it changes names of the files while sending them to external diff tool?

**Comment by DanPristupov** [comment]
This must be fixed in 1.0.98.

Here's a similar issue: https://github.com/ForkIssues/Tracker/issues/1117
