### ISSUE TITLE
Diff panel scrollbar position maintained from file to file

### ISSUE THREAD

**Issue by ldipenti** [ForkIssues/Tracker#1045]
Hello Fork devs!

First off let me congratulate you again for an awesome software, it's a really useful tool.

I have an issue when using it to do big code reviews, I usually go commit by commit checking the changes being made on every file.
When I change from one file to another, I have to manually scroll to the top of the diff view panel every time because the scrollbar relative position is kept from the previous file view.
I think the ideal fix would be that Fork saves every file position within a single commit (only saving positions for the current commit maybe, to avoid big memory usage) but if that's not possible, I think it would be acceptable to just reset the scroll bar to the top on every file selection change, making the lives of the users browsing changes much easier.

Thanks!

**Comment by DanPristupov** [comment]
> I think the ideal fix would be that Fork saves every file position within a single commit

It should work like that, but it doesn't. I will check this.
