### ISSUE TITLE
[BUG] Remotes don't appear on left panel

### ISSUE THREAD

**Issue by FranciscoAmado** [ForkIssues/Tracker#105]
Heyo!

Remotes aren't appearing on the left panel although I've added them.

I've cloned a new repository (origin), added a new remote repository (fork of the origin) and it didn't add it to the left panel.

I've checked and the, as you can see in the image below, the remote options I've added are still there.
Also, I can't add any remote with the same name as the ones I've added previously.
Restarting the Fork.app didn't help.

![screen shot 2017-09-25 at 17 22 48](https://user-images.githubusercontent.com/6344795/30819872-1880c468-a218-11e7-9d90-94a5a1acb159.png)

Any idea on why this is happening / how can it be solved?

**Fork Version** 1.0.56.1

Thanks for Fork, It's awesome!

**Comment by DanPristupov** [comment]
Hi Francisco!

Could you try to fetch from these remotes. May be they are invisible, because they don't have children... I'm going to try to reproduce the problem.

**Comment by DanPristupov** [comment]
I've reproduced the bug. I made it in 1.0.56. Going to fix in next version.

**Comment by FranciscoAmado** [comment]
Fetching from the remotes did the trick! Thanks 👍🏻

**Comment by ElfSundae** [comment]
Same here. I just can not add a remote.

**Comment by DanPristupov** [comment]
Fixed the problem in Fork 1.0.57 which is available now as prerelease. More information here: #110

**Comment by FranciscoAmado** [comment]
Thanks for fixing it 👍🏻
