### ISSUE TITLE
Merge conflict: are labels mixed up?

### ISSUE THREAD

**Issue by homm** [ForkIssues/Tracker#1050]
When I have conflicts during pulling, I see the next buttons. I believe the choice on the right is remote and on the left is mine.

<img width="681" alt="Screenshot 2020-06-10 at 17 41 30" src="https://user-images.githubusercontent.com/128982/84282175-19f68900-ab42-11ea-9238-269fc98a208f.png">
<img width="678" alt="Screenshot 2020-06-10 at 17 41 43" src="https://user-images.githubusercontent.com/128982/84282188-1d8a1000-ab42-11ea-8927-b8b0a10142b0.png">

PS. I just realized that this is actually merging a stash on top of the pulled branch. So this makes sense from this point of view, but since actually I haven't stashed anything manually this is very confusing.

**Comment by DanPristupov** [comment]
Hi. Do you have the latest version?

**Comment by homm** [comment]
1.0.93.6

**Comment by DanPristupov** [comment]
1.0.94 is the latest one

**Comment by homm** [comment]
Right. It was in the develop channel. I see this is fixed. Thank you!
