### ISSUE TITLE
Bisect conflicts with Commit Amend

### ISSUE THREAD

**Issue by nsh-ableton** [ForkIssues/Tracker#1051]
If I have been bisecting, which I tend to do on the command line, it seems that I cannot then use Fork to perform a `HEAD` commit amend without first "cleaning up" the bisect (by doing a `git bisect --reset` to clean up all the tags that the bisect has left on the branch). Otherwise Fork seems to believe that it's in a sort of "bisect mode", and when I try to amend `HEAD`, the commit message is cleared from the editor.

**Comment by DanPristupov** [comment]
Thank you for the bug report. I reproduced the problem. The fix will be available in 1.0.95.

**Comment by nsh-ableton** [comment]
Awesome!
