### ISSUE TITLE
Bitbucket app password login issue

### ISSUE THREAD

**Issue by farrukhaskari1** [ForkIssues/Tracker#1053]
I downloaded fork 1.0.94 on Mac OS 10.15.5 
unfortunately Bitbucket app password login is broken. it fails to parse response JSON. 

It would be kind enough if you can look into this issue.

thanks, have a good day.

**Comment by lksoft** [comment]
I have also noticed that bitbucket doesn't seem to work anymore. Also previously it didn't seem to correctly see other workspaces that I am a part of in bitbucket (hopefully that is a related issue).

**Comment by DanPristupov** [comment]
I just tried and everything worked. Please notice that you must use username, not email.

**Comment by lksoft** [comment]
I was using the username. However I just remembered that I moved the last repos from my personal account to one of my workspaces. So I didn’t see any results. Would it be possible to get the repos from the workspaces added?

**Comment by DanPristupov** [comment]
@lksoft It's not clear whether you can login or not. If you can, this is an offtopic.

> Would it be possible to get the repos from the workspaces added?

Do you mean to show them in the clone dialog?

**Comment by lksoft** [comment]
Sorry, to clarify, I am able to login, I was mistaken because no repos showed up, but that was my fault (having moved them all and forgetting). 

As for the repos from workspaces, yes it would be very much useful to show the repos from my workspaces in the clone dialog. 

Sorry for being less than clear, that is annoying. 😜

**Comment by DanPristupov** [comment]
@lksoft there is a corresponding issue: https://github.com/ForkIssues/Tracker/issues/619

@askari01 Please try to use the username instead of email.

**Comment by farrukhaskari1** [comment]
I tried both username and email. it was a new account via gmail on bitbucket. 
What solved the issue was to activate 2FA, generate app specific password and try logging in with that. 

The issue is with parsing of JSON response as per error message with 2FA disabled.

**Comment by lksoft** [comment]
> @lksoft there is a corresponding issue: #619

Thanks Dan I hadn't seen that one. I commented over there with some API calls that might help
