### ISSUE TITLE
Wrong files count in stash menu

### ISSUE THREAD

**Issue by marcheimendinger** [ForkIssues/Tracker#1054]
UI issue only but if selecting both folders and files in unstaged changes, the Stash menu will also count the enclosing folders, not just files.

![Screenshot 2020-06-15 at 19 53 40](https://user-images.githubusercontent.com/43568598/84690649-1a789080-af43-11ea-9d45-252de8f5638f.png)

**Comment by Niels-NTG** [comment]
Another example of this bug: <img width="500" alt="Schermafbeelding 2020-08-19 om 10 25 34" src="https://user-images.githubusercontent.com/6061595/90612865-e94d6280-e208-11ea-8852-da86428e86c0.png">

Even if you reword this menu entry to something like "Stash X Items…" or "Stash X Nodes…", I don't think counting both files and folders is particularly useful information. It's only the amount of files that I care about in this situation.

**Comment by DanPristupov** [comment]
This was fixed a few months ago in 1.0.97
