### ISSUE TITLE
Replace spaces in new branch/tag names with hyphens

### ISSUE THREAD

**Issue by jessetan** [ForkIssues/Tracker#106]
Git does not allow spaces in branch names. Fork ignores spaces that are typed in the "new Branch" window, so `my new branch` becomes `mynewbranch`.
Can this be changed to automatically replace spaces with a hyphen (possible configurable), so this will become `my-new-branch`. This is SourceTree's behavior and seems more user-friendly and results in more readable branch names

**Comment by DanPristupov** [comment]
Great idea. It didn't come to my mind. Will add soon.

**Comment by DanPristupov** [comment]
I implemented this is Fork 1.0.57 which is available now as prerelease. More information here: #110
