### ISSUE TITLE
sshCommand support

### ISSUE THREAD

**Issue by uetchy** [ForkIssues/Tracker#1063]
I've been using `sshCommand` prop in gitconfig to determine which private key should be used in pushing/pulling my repository. This is useful when you have multiple set of ssh keys in your machine.

However, Fork seems not to respect this property when interacting with remote repositories.
It would be great if Fork handles `sshCommand` properly so that I don't have to define custom hostname in `~/.ssh/config`.

```bash
$ cat .git/config
...
[core]
        sshCommand = ssh -i /Users/uetchy/.ssh/id_ed25519 -oIdentitiesOnly=yes
...
```

## Refs

- https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresshCommand

**Comment by Stanzilla** [comment]
are you sure this is not because of https://github.com/ForkIssues/Tracker/issues/674?

**Comment by uetchy** [comment]
@Stanzilla I'm sure it's different from the issue around `[include]` since I don't have a single `[include]` directive in my local&global git-config.

**Comment by DanPristupov** [comment]
Starting from 1.57 Fork supports multiple SSH keys.

**Comment by DanPristupov** [comment]
I think we can close this. Please feel free to reopen if you still have a problem.
