### ISSUE TITLE
[Feature Request] star and filter remote folders

### ISSUE THREAD

**Issue by davecotter** [ForkIssues/Tracker#1066]
working at a very large company, our remote list is unwieldy.
<img width="172" alt="big list" src="https://user-images.githubusercontent.com/259854/85438869-44344780-b541-11ea-9200-1831ea6b7131.png">

i'd love to be able to star only the interesting remotes, then click a filter button to see ONLY starred remotes?
<img width="257" alt="star" src="https://user-images.githubusercontent.com/259854/85438992-57dfae00-b541-11ea-841b-a87befc939a7.png">

I'd also like any of MY remotes to be automatically starred.

**Comment by DanPristupov** [comment]
In Fork 2.6 you can filter and hide folders
