### ISSUE TITLE
「Feature Request」detached HEAD should show in left `Branches` area

### ISSUE THREAD

**Issue by ooopscc** [ForkIssues/Tracker#107]
When checkout to a commit without tag, you have a detached HEAD.
`git status` will show
```
HEAD detached from 1d9d44eef
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   a.c
        modified:   b.c

no changes added to commit (use "git add" and/or "git commit -a")
```
In SourceTree, the left `Branches` area has a HEAD "branch" flag, click it will lead you to the commit. But in Fork, I can not find that commit I have checked out, unless I scroll from the long long commit history.
![image](https://user-images.githubusercontent.com/1056803/30910533-bcc7ae50-a34a-11e7-96c8-8a803a864872.png)

**Comment by DanPristupov** [comment]
Sorry for the delay. I like the idea. I'll try to implement this in the next release.

**Comment by bwl21** [comment]
Yes please, this is a blocker for me to swith from sourcetree.

**Comment by DanPristupov** [comment]
@bwl21 sound like a good reason to increase priority of the task :). It's going to be done in 1.0.60.

**Comment by DanPristupov** [comment]
@ooopscc @bwl21 this feature is finally available in 1.0.60

**Comment by bwl21** [comment]
Very cool. Now we can see that we are on a detached head.
I am afraid I propose to do more:

Here is a situation in fork,

![screenshot_1046](https://user-images.githubusercontent.com/2022976/33492675-0d5ac626-d6be-11e7-8a8b-7ea718bc0efc.jpg)

* love the idea to visualize the stashes in the history tree. 
* I would also like to see the HEAD visualized in the history tree
* I would also like the "uncommitted changes" in the history tree

Here is what I expected (Sorry Atlassian, I shameless copy Sourcetree's beahavior). But this visualization is the coolest approach I have seen for this.

![screenshot_1045](https://user-images.githubusercontent.com/2022976/33492669-06e4857a-d6be-11e7-91bb-84e0647fefb1.jpg)

**Comment by bwl21** [comment]
is there any chance that you come closer to sourcetree's approach. In particular it is not always visible if there are uncommitted changes.

An earlier verssion (before 1.0.61) showed a number of uncommited changes on the "Changes" entry in the left pane. But with 1.0.61 even this seems to be gone.

**Comment by bwl21** [comment]
@DanPristupov why do you close this issue? is it fixes or wontfix.

**Comment by DanPristupov** [comment]
Depends on what you mean. Fork shows `HEAD` in the branch list on the sidebar in detached HEAD state, which was the original request.

**Comment by DanPristupov** [comment]
> I would also like to see the HEAD visualized in the history tree

It's probably excessive to show such a label all the time, but I can show it in `Detached HEAD` state.

> I would also like the "uncommitted changes" in the history tree

What's the point of this? It seems strange to show a fake revision which semi-duplicates the "Changes" view.

**Comment by bwl21** [comment]
Well it is how Sourcetree does it (which is where I came from). The way fork currently does it is also reasonable after one got used to it. 

Thanks for the explanation.

**Comment by DanPristupov** [comment]
Ok, going to keep that issue closed. Please let me know if I'm missing something and feel free to create a separate issue if you have some idea.
