### ISSUE TITLE
[FEATURE] Allow batch rename of branches

### ISSUE THREAD

**Issue by ziriax** [ForkIssues/Tracker#1070]
Currently deleting many branches is easy, just multi-select, and hit the delete key.

However, it might also be handy to rename multiple local branches at once. 

For example, in a feature-based workflow, you might want to keep completed local feature branches with full history around for a while, but move them out of the main `feat` folder in Fork that shows the feature branches you're currently working on.

This could be done by dragging a multi-selected list of branches into a branch folder, e.g. dragging `feat/GUI-712` into the `done` folder would rename the branch to `done/GUI-712`. Other means of renaming are of course possible.

**Comment by cpyfferoen** [comment]
Dragging branches like moving around files/folders is a neat idea, tho... this seems awfully niche. I think it points much more to a extremely unique workflow. Re-naming branches isn't even a "universal" feature (you can't rename a remote branch, you must create a new one, and delete the old ones). I don't think this feature would be worthwhile IMO.

**Comment by ziriax** [comment]
Thanks for the update. Closing then
