### ISSUE TITLE
Sort main Branch to Top of Sidebar

### ISSUE THREAD

**Issue by robmathers** [ForkIssues/Tracker#1071]
Given that GitHub is switching to use `main` as the default branch, can it get the same preferential sorting treatment that `master` and `develop` do? Where they sort to the top of the branch list in the sidebar.

**Comment by sciencebook** [comment]
This would be great!  We also have also switched "production" as our main branch for some repositories.  Not sure how many special branch names you want to add, but "main" would definitely be great.

**Comment by DanPristupov** [comment]
In 1.0.97 `main` is sorted with a higher priority (same as `master` and `develop`)
