### ISSUE TITLE
[BUG] Filter icons in branches is disappearing after click

### ISSUE THREAD

**Issue by Siregar** [ForkIssues/Tracker#1078]
## Versions:
**OS:** macOS Catalina 10.15.4
**Client:** Fork 1.0.95

## How to reproduce:
When I click the filter button next to my branch, everything is working as expected. If I click it again to remove the filter, the button is suddenly disappearing. When I move my cursor away from the branch list item and move it back, the filter icon is back.

![bug](https://user-images.githubusercontent.com/31287148/87007410-8789e980-c1c2-11ea-9b4d-eeaca231ff23.gif)

**Comment by DanPristupov** [comment]
Can you still reproduce this problem? It works properly for me on Catalina 10.15.7.

**Comment by DanPristupov** [comment]
Surprisingly, right after I closed this issue, I reproduced the problem :).

It will be fixed in Fork 2.6
