### ISSUE TITLE
[Bug] Unable to create a feature branch after uninstalling Sourcetree App.

### ISSUE THREAD

**Issue by goppinath** [ForkIssues/Tracker#1079]
Recently I tried the Sourcetree App and then uninstalled it immediately. After that Fork App is not letting to create a feature branch by clicking "Start Feature...", and throwing the following error.

```
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 158: _flags_fatal: command not found
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 1022: [: -ne: unary operator expected
flags:WARN /Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 739: /Applications/Sourcetree.app/Contents/Resources/bin/getopt: No such file or directory
flags:FATAL unable to parse provided options with getopt.
```

<img width="682" alt="Screenshot 2020-07-09 at 14 23 21" src="https://user-images.githubusercontent.com/4173985/87039828-08aba580-c1f0-11ea-8074-7f53f52f7085.png">

**Comment by DanPristupov** [comment]
Hi,

https://github.com/ForkIssues/Tracker/issues/541#issuecomment-466292419

**Comment by goppinath** [comment]
@DanPristupov Thanks a lot, buddy you have saved my day. I know that I should not install the Sourcetree in the future anymore.
