### ISSUE TITLE
Clipboard is automatically read on File > Clone…

### ISSUE THREAD

**Issue by wesleymccloy** [ForkIssues/Tracker#1081]
When using the `File > Clone…` menu item. Fork will automatically read your clipboard to populate the repository URL field.

This is a potential invasion of privacy while only offering a 1 second "optimization" that only occurs when cloning a new repo.

**Comment by DanPristupov** [comment]
> This is a potential invasion of privacy

Can you elaborate?

**Comment by wesleymccloy** [comment]
Reading a user's clipboard without them initiating the paste is a subversion of the expected clipboard behavior. 

Realistically, in macOS, an app can transparently breach the user's clipboard privacy without the user knowing. iOS 14 notifies users of this behavior so there is a trend towards avoiding non-user-initiated clipboard operations.
