### ISSUE TITLE
Fork push does not offer to set the upstream tracking branch in the push dialog

### ISSUE THREAD

**Issue by nickoto** [ForkIssues/Tracker#1083]
This is sometimes offered in the dialog but not always. It would be useful to have this in the dialog and have an option to default to pushing to a remote tracking branch of the same name by default.

**Comment by nickoto** [comment]
At least I remember in the past it would offer to create a new tracking branch if the current tracking branch was master... This is tripping me up often now :)

**Comment by DanPristupov** [comment]
The 'Create tracking reference' option is visible when the target local branch doesn't track any remote branch.

<img width="496" alt="Screen Shot 2020-07-20 at 19 00 27" src="https://user-images.githubusercontent.com/618115/87964960-485d7180-cabb-11ea-823f-4717fa9b5f26.png">

You can change tracking reference for an existing local branch in the context menu on the sidebar.

**Comment by nickoto** [comment]
Yes, I've found that now. It would be useful if I could create a new one if needed in this dialog as part of the workflow :)

That is, I can pick a branch to push to from the `To:` dropdown, but you can't create a new one there -- you can only pick an existing one.

**Comment by DanPristupov** [comment]
>  It would be useful if I could create a new one if needed in this dialog as part of the workflow :)
> That is, I can pick a branch to push to from the `To:` dropdown, but you can't create a new one there -- you can only pick an existing one.

We implemented the ability to push to a custom branch in Fork 2.1.

https://github.com/fork-dev/Tracker/issues/1185
