### ISSUE TITLE
diff output omits "\ No newline at end of file" and subsequent line

### ISSUE THREAD

**Issue by isao** [ForkIssues/Tracker#109]
Hi, 

I love Fork, thank you very much for your work.

One small issue, is Fork's diff shows the line 12 below is deleted:

![screen shot 2017-09-28 at 5 16 12 pm](https://user-images.githubusercontent.com/46951/30995764-12fe5928-a471-11e7-8cdf-0cba0d23966a.png)

...but there was actually a newline added. git version 2.14.2 diff shows:

    -}
    \ No newline at end of file
    +}

FYI, thx

**Comment by DanPristupov** [comment]
@isao I've reproduced the problem. Fixing it right now.

**Comment by isao** [comment]
Thanks Dan. I love Fork BTW :)

On Oct 10, 2017, at 8:14 AM, Dan <notifications@github.com> wrote:

@isao I've reproduced the problem. Fixing it right now.
