### ISSUE TITLE
"Start Git Flow <smth>" is cut in the end

### ISSUE THREAD

**Issue by kambala-decapitator** [ForkIssues/Tracker#1090]
v1.0.96

![Screenshot 2020-07-27 at 15 24 41](https://user-images.githubusercontent.com/1557784/88541638-c8388e00-d01d-11ea-8ac5-d154602b7bff.png)

"Finish Git Flow \<smth\>" is fine though.

**Comment by DanPristupov** [comment]
Thank you for reporting this issue.
It's fixed in 1.0.97.

**Comment by kambala-decapitator** [comment]
Great, thanks! I confirm that it's fixed.
