### ISSUE TITLE
Error when staging files that contains  ∕  in their file name

### ISSUE THREAD

**Issue by aymanbagabas** [ForkIssues/Tracker#1092]
When I try staging a block within a file that contains a '∕' in its file name, I get `error: new file dev/null depends on old contents`. Works fine if I stage the whole file but not a single block.

![image](https://user-images.githubusercontent.com/3187948/88967846-5c079580-d27c-11ea-8d5c-45caf9cef626.png)

**Comment by DanPristupov** [comment]
How can I create such a file?

**Comment by aymanbagabas** [comment]
> How can I create such a file?

`touch newfile∕file` Note that this '∕' is different from '/' which has a unicode value of `0x2215`.

**Comment by DanPristupov** [comment]
This issue must be fixed in 1.0.97
