### ISSUE TITLE
Network operations block, UI gets stuck

### ISSUE THREAD

**Issue by pkamppur** [ForkIssues/Tracker#1096]
I use git repos that are hosted in a private network. When I don't have VPN open (and thus there's no connection to the server), Fork sometimes becomes stuck while refreshing views. "Fetching remotes automatically" seems to make the issue worse.

This happens I'm not explicitly doing any git operations. Just switching to Fork from other apps Fork's UI gets stuck. Spinning beachball stays on screen for about 10-20 seconds. Sometimes longer. 

It takes some time for this condition to start manifesting. Immediately after launching Fork everything is ok for some time. So relaunching the app is one workaround.

I know this is probably a rare case and won't impact majority of people.

[Spindump.txt](https://github.com/ForkIssues/Tracker/files/5026679/Spindump.txt)

I'm using Fork version 1.0.96.1, on macOS Catalina 10.15.6.

**Comment by DanPristupov** [comment]
I made many improvements in the past, but forgot to report about them here. Does the problem still exist or we can close the issue?

**Comment by pkamppur** [comment]
Hi! Thanks for the update. Indeed, I have not seen this problem in a long time. So, thanks for the fixes! 👍
