### ISSUE TITLE
[Question] How to remove integration with GitHub?

### ISSUE THREAD

**Issue by Lonli-Lokli** [ForkIssues/Tracker#1097]
I've tried to integrate my GitHub account - entered the password, give permission on next page and was able to see Fork app in OAuth list of application on GitHub page, was able to see my repos but I was not able to fetch any of them (message permissions denied (public_api) appears). Assume that's due to https://github.com/jirsbek/SSH-keys-in-macOS-Sierra-keychain

I've decided to remove current Github integration - revoked access on GitHub , removed *Fork*github* entry in KeyChain access. Now I am getting Authentication required message when I select Github node on Clone window.

**Comment by DanPristupov** [comment]
Hi. Open repository manager (cmd+t), click on GitHub and log out.
