### ISSUE TITLE
Please keep OSX 10.11 as the minimum version supported

### ISSUE THREAD

**Issue by clankill3r** [ForkIssues/Tracker#1098]
Please keep OSX 10.11 as the minimum version supported.
I'm on 10.12.6 and I'm planning on staying on that version for years cause I don't like the direction apple is going.

I notice some apps like docker always ride with the apple train, and drop support for older OSX versions really quickly.
Please don't do that!

<3

**Comment by DanPristupov** [comment]
We will, until 10.11 or Apple start making problems.
