### ISSUE TITLE
log file `Fork.log` gets very big

### ISSUE THREAD

**Issue by n8gray** [ForkIssues/Tracker#1099]
I'm clearing stuff out to recover disk space and found that `~/Library/Logs/Fork.log` was 1.7GB.  Seems like there needs to be a limit or rotation strategy for that logfile.

**Comment by DanPristupov** [comment]
Hi. I improved the behavior in 1.0.97 and now Fork will log less.

> Seems like there needs to be a limit or rotation strategy for that logfile. 

Fork already creates the log file once per session (i.e. erases the old one after restart).

**Comment by n8gray** [comment]
Awesome, glad to hear it.

> Fork already creates the log file once per session (i.e. erases the old one after restart).

Fork is stable enough that I only restart it when there are updates, so that might not happen quite as often as you expect.  :)
