### ISSUE TITLE
"Check for updates" menu item is disabled

### ISSUE THREAD

**Issue by cdzombak** [ForkIssues/Tracker#11]
For the last several updates, I've had to download them from the website because the "Check for updates" menu item is disabled.

The following screenshot is from Fork 1.0.43:

<img width="225" alt="screen shot 2017-04-20 at 13 31 51" src="https://cloud.githubusercontent.com/assets/102904/25244263/f76906f8-25cd-11e7-87ee-13a434d6d594.png">

**Comment by DanPristupov** [comment]
Hi. Thank you for reporting the problem.
I've never seen this on the computers in my environment.

Some obvious reasons why updates can be disabled:
- Fork is not installed to the Applications folder.
- Fork doesn't check for updates on first ever run (this is not the case, probably).

I'm going to investigate the menu behavior in source code of the Sparkle project which I use to handle the updates.

**Comment by cdzombak** [comment]
Hm. Fork is definitely in my Applications folder, but I did just restart it and the menu item became enabled. Is there a chance there's a bug in the first-run code? Or is it on the first run _of each version_?

**Comment by DanPristupov** [comment]
It should be on the very first run of the application.

First I'm going to update Sparkle to the latest version (it looks like they made many improvements). Let's see if this help.

**Comment by cdzombak** [comment]
I think what's happening is the "Check for Updates" item is disabled on the first run of _every_ version. This only me because frequently you release a new version more frequently than I have a reason to restart the app 😉

**Comment by DanPristupov** [comment]
Hi Chris. Thank you for getting back to this.
Now I see why it was so tricky to reproduce :). It took almost half a year to notice that.

Actually it probably means that Fork will not update itself until restart after an update, which is clearly a bad thing. I'm going to test if it really behaves like you said. Thanks!

**Comment by cdzombak** [comment]
Thanks, Dan. This isn't urgent in my eyes, so feel free to work on other stuff :)
