### ISSUE TITLE
File tree pane line number gutter doesn't support numbers greater than 9999

### ISSUE THREAD

**Issue by olets** [ForkIssues/Tracker#1101]
The line number gutter in the file previewer in the "file tree" pane of the "all commits" view cannot show more than 4 digits. Here's a screenshot of a file with more than 9999 lines:

![image](https://user-images.githubusercontent.com/3282350/89570009-8d8bde00-d7f3-11ea-9cb6-78ea93a3fae2.png)

Compare to the gutter in the unstaged changes' view, the staged changes' view, and the "all commits" changes pane, which does not have the same limit

![image](https://user-images.githubusercontent.com/3282350/89571560-df356800-d7f5-11ea-96cc-8e8013186c5b.png)

**Comment by DanPristupov** [comment]
Fixed in 1.0.97
