### ISSUE TITLE
long local path preview display truncated strangely in add submodule prompt dialog

### ISSUE THREAD

**Issue by doneykoo** [ForkIssues/Tracker#1102]
**Repro:**
1. add submodule
2. in the prompt dialog, set repository url
3. set a long path, eg: `aaaaaaaaaaaa/bbbbbbbbbbbb/cccccccccccc/dddddddddddd/submodule_name`

**Result:**
- local path preview display truncated strangely

<img width="563" alt="Snipaste_2020-08-07_16-13-12-fork-add-submodule-issue" src="https://user-images.githubusercontent.com/1118771/89624537-f6915580-d8c8-11ea-9c04-47027667b8e6.png">

PS, also noticed the begining part of local path preview is `~/xxx_folder/`, which is a bit confusing, somewhat looks like MacOS user root folder.

**Comment by DanPristupov** [comment]
Thank you for bringing our attention to that. We improved the 'Add submodule' dialog layout in 1.0.97.
