### ISSUE TITLE
Golint Not Found

### ISSUE THREAD

**Issue by Tensho** [ForkIssues/Tracker#1103]
Hi

Thank you for your wonderful product 🙇 ❤️  I have one strange issue with [pre-commit](https://pre-commit.com/) and [golint](https://github.com/golang/lint) toolset. When I  make git commit and pre-commit hooks are run in terminal with stage Go files everything is OK:

<img width="881" alt="Screenshot 2020-08-07 at 16 36 52" src="https://user-images.githubusercontent.com/892721/89651201-3b6abb80-d8cc-11ea-8fc8-b5e884a8a79f.png">

But when I try to do the same within Fork `golint` binary can't be found for some reason:

<img width="2032" alt="Screenshot 2020-08-07 at 16 33 55" src="https://user-images.githubusercontent.com/892721/89651285-5f2e0180-d8cc-11ea-826a-62fe78d8e629.png">
 
Here are some terminal outputs to proof everything is installed as expected:

```
$ cat -n /Users/andrii.babichev/.cache/pre-commit/repoozn3k62n/hooks/golint.sh
     1	#!/usr/bin/env bash
     2
     3	set -e
     4
     5	# OSX GUI apps do not pick up environment variables the same way as Terminal apps and there are no easy solutions,
     6	# especially as Apple changes the GUI app behavior every release (see https://stackoverflow.com/q/135688/483528). As a
     7	# workaround to allow GitHub Desktop to work, add this (hopefully harmless) setting here.
     8	export PATH=$PATH:/usr/local/bin
     9
    10	exit_status=0
    11
    12	for file in "$@"; do
    13	    if ! golint -set_exit_status "$file"; then
    14	        exit_status=1
    15	    fi
    16	done
    17
    18	exit ${exit_status}%
$ which golint
/Users/andrii.babichev/go/bin/golint
$ echo $PATH | tr -s ":" "\n" | grep go
/Users/andrii.babichev/go/bin
$ golint --help  
Usage of golint:
	golint [flags] # runs on package in current directory
	golint [flags] [packages]
	golint [flags] [directories] # where a '/...' suffix includes all sub-directories
	golint [flags] [files] # all must belong to a single package
Flags:
  -min_confidence float
    	minimum confidence of a problem to print it (default 0.8)
  -set_exit_status
    	set exit status to 1 if any issues are found
```

Non-Go compiled binaries work as expected. What could be a reason for that divergence?

**Comment by DanPristupov** [comment]
In short: Fork can't find `golint` in `PATH`.


The hook points to the problem and proposes to add `/usr/local/bin` to `PATH` in order to find `golint` there:
```
     5	# OSX GUI apps do not pick up environment variables the same way as Terminal apps and there are no easy solutions,
     7	# workaround to allow GitHub Desktop to work, add this (hopefully harmless) setting here.
     8	export PATH=$PATH:/usr/local/bin
```

However you installed `golint` to `~/go/bin`
```
$ which golint
/Users/andrii.babichev/go/bin/golint
```

So, you can either:

1. Install `golint` to `/usr/local/bin`
2. Update hook to `export PATH=$PATH:~/go/bin`
3. Run Fork from CLI using `open -a Fork .`. In this way Fork will inherit PATH of the parent (terminal) process (https://github.com/ForkIssues/Tracker/issues/430#issuecomment-429013890).

P.S. While it's not directly related, I'd like to mention that this comment is absolutely wrong:

> 5	# OSX GUI apps do not pick up environment variables the same way as Terminal apps

OSX GUI processes do inherit ENV the same way as command line processes.

**Comment by Tensho** [comment]
@DanPristupov Thank you for the thorough description, indeed Go path for binaries is added to `PATH` in `~/.zshrc` and I totally forgot about this. 🙇
