### ISSUE TITLE
Allow to change the GitLab Service to a custom domain

### ISSUE THREAD

**Issue by diegozuber** [ForkIssues/Tracker#1106]
I would like to use the GitLab Service, but I'm using a self hosted GitLab. Would be great if you can enter an alternative URL instead of the default gitlab.com.

**Comment by amitjindal** [comment]
Hi, I would also like to do the same. We have custom gitlab. I have been using Tower till now and am considering using this but this is really a big limitation.
Any plans to add this?

**Comment by DanPristupov** [comment]
You can authenticate to use any git service. Any server which is supported by git is also supported by Fork.

**Comment by diegozuber** [comment]
@DanPristupov I was talking about this:

![Bildschirmfoto 2020-08-13 um 18 25 08 PM](https://user-images.githubusercontent.com/21689209/90160901-aa478900-dd92-11ea-96ff-64903bfbbcf4.png)

I thought I can connect my gitlab with this service and clone all available repositories on gitlab directly within fork. So that I don't need to clone it "manually" by entering the url. But I tested it right now with github and as I saw it is "just" to manage your ssh keys?

**Comment by DanPristupov** [comment]
The integration with the service just adds an easier way to clone and the ability to generate SSH key from Fork.

**Comment by amitjindal** [comment]
Actually it does a few more things in my opinion. In my hosted gitlab we have 100+ projects. Another older version we have over 300 repos. Having an integration shows easy access to them for checkout. Else I need to open the browser, often put in username/password, find the repo, copy the SSH path for clone, click on clone, paste (or maybe its picked up), then press a button to actually clone it.
Since you have gitlab.com integration I am assuming supporting self hosted might be easier.

**Comment by amitjindal** [comment]
Please see the attached screenshots of how its easy to clone these (screenshot of Tower). I do like the Fork experience much better.

![2020-08-13_22-36-04](https://user-images.githubusercontent.com/3275983/90165129-d88a9000-ddb5-11ea-965b-b8a0984afbf2.jpg)

![2020-08-13_22-36-20](https://user-images.githubusercontent.com/3275983/90165121-d4f70900-ddb5-11ea-8223-b25b74fa95db.jpg)

**Comment by faimin** [comment]
don't support custom domain Gitlab
![image](https://user-images.githubusercontent.com/8207436/92551029-a292db80-f28f-11ea-8a96-e20daaaffe30.png)

**Comment by m4p** [comment]
Consider this another vote for this feature.
