### ISSUE TITLE
Switching away from local changes in amend mode destroys updated text

### ISSUE THREAD

**Issue by robmathers** [ForkIssues/Tracker#1109]
There's a data loss bug when using the "Amend" mode on the commit screen.

To reproduce:
1. Open **Local Changes** screen
2. Click **Amend**
3. Update some text in the commit subject or description
4. Switch to the **All Commits** screen
5. Return to the **Local Changes** screen

Expected result: updated text remains
Actual result: text reverts to the original text of the commit being amended

**Comment by DanPristupov** [comment]
I think I've fixed this in 1.0.97. Could you confirm that it works as expected on your side please?

https://github.com/ForkIssues/Tracker/issues/548
