### ISSUE TITLE
Default value when editing remote

### ISSUE THREAD

**Issue by ElfSundae** [ForkIssues/Tracker#111]
Steps:

1. Open "edit remote" or "rename remote", the text field shows the default value
2. Input something, do not close this panel, and switch to another application
3. Reactive Fork, then the text field would show the default value again, lost my input...

**Comment by DanPristupov** [comment]
@ElfSundae cool, thanks. Will fix ASAP.

**Comment by ElfSundae** [comment]
Fixed in 1.0.57.2 #110 thanks.
