### ISSUE TITLE
Open and open with from history window open the highlighted commit, not the one clicked on

### ISSUE THREAD

**Issue by robertsinton** [ForkIssues/Tracker#1112]
To reproduce:

- Open history window and select a commit to highlight it.
- Right-click on that commit to open contextual menu, and choose Open the file in your editor.
- Return to the history window, right-click on a _different_ commit to the highlighted one, and choose to open it.

Outcome is that the same version of the file will be opened in your editor: the one that is highlighted, not the one you right-clicked on.

**Comment by DanPristupov** [comment]
Thank you for the bug report. The problem is fixed in 1.0.97
