### ISSUE TITLE
Checking out a commit while in detached HEAD state doesn't work.

### ISSUE THREAD

**Issue by jespertheend** [ForkIssues/Tracker#1113]
How to reproduce:
-While in your main branch, double click a commit from the list. (let's call this commit A)
-A pop up appears, click on 'checkout'
-Notice how on the left 'HEAD' is now bold, and all the commits above the one you double clicked are grey. Indicating that you have checked out the commit.
-Now double click another commit (commit B). The pop up appears again, click 'checkout' again.
-Notice how the checked out commit doesn't change. The same commits stay grey.
-Check out your main branch again.
-Double click commit B again, now it does work.

**Comment by DanPristupov** [comment]
I've reproduced the problem. We will fix it in the next (1.0.97) update.

**Comment by jespertheend** [comment]
Sweet, thanks!

**Comment by jespertheend** [comment]
It seems like the commit does actually get checked out properly, my files change and `git status` shows it is checked out at the commit that I double clicked. So I think it's just a visual issue in fork, restarting fork updates the UI with the correct commit.

**Comment by DanPristupov** [comment]
We released the 1.0.97 update with the fix on Friday (21/8/2020)

**Comment by jespertheend** [comment]
Nice, it seems to work. Thanks!
