### ISSUE TITLE
Custom commands - cherry pick specific file

### ISSUE THREAD

**Issue by lievendf** [ForkIssues/Tracker#1116]
Hi,

I'm trying to create a custom command to cherry pick changes from a specific file in a commit.
The following seems to work from command line but I can't get it to work as custom command: 
`git show $SHA -- $filepath | git apply -` (https://stackoverflow.com/a/29788254)

I figured I might need an alias in my .gitconfig and pass the parameters using $1 and $2
```
[alias]
    cherrypickfile = ! git show $1 -- $2 | git apply -
```
and create a custom command with parameters: `cherrypickfile $SHA $filepath`
But this seems to fail:
`error: can't open patch 'ae645119fcb62ab1a00427e57011be072253b191': No such file or directory`
Strangely though, the operation actually succeeds after a few moments and the change appears in unstaged changes.

What am I doing wrong?

**Comment by DanPristupov** [comment]
> I figured I might need an alias in my .gitconfig and pass the parameters using $1 and $2

This is smart 👍

I just tried to create such alias and it actually worked for me. It does show an error indeed, but it also cherry-picks the file.


<img width="421" alt="Screen Shot 2020-08-20 at 12 25 52" src="https://user-images.githubusercontent.com/618115/90759126-4bc56200-e2e0-11ea-8f3f-f0c7955b1141.png">

**Comment by Lonli-Lokli** [comment]
Is it possible to enhance somehow custom commands without creating aliases?

**Comment by DanPristupov** [comment]
We will introduce an ability to run bash scripts (including pipes, etc) very soon.

**Comment by DanPristupov** [comment]
In Fork 2.7 you can run bash commands as custom commands.
