### ISSUE TITLE
Temp file names break language detection with External Merge or Diff

### ISSUE THREAD

**Issue by flit** [ForkIssues/Tracker#1117]
When Fork writes the temporary files in order to invoke an external merge or diff tool, the filenames used prevent the external tool from detecting the language and using syntax colouring or other language support features.

**Details**

For external merge, Fork writes:
- `name.ext.~REMOTE`
- `name.ext.~LOCAL`

For external diffs, Fork uses random UUIDs for the file names.

In both cases, the file names used mask the extension used to detect the language. An example of a tool for which this file name format breaks syntax colouring is Apple's FileMerge.app.

**Solution**

An possible change for merges that would solve the problem is to use this file name format:
- `name~REMOTE.ext`
- `name~LOCAL.ext`

For diffs, one option is a format like `name~<UUID>.ext`. An improvement over the existing UUID-based unique names would be to use the git SHA-1 instead, e.g. `name~<SHA-1>.ext`.

**Comment by DanPristupov** [comment]
Hi.

Would you like to be a tester?

**Comment by kapcino** [comment]
I have this problem too. I use Mac version and make BC as external diff and merge tool.
If I remember correctly, it works well 3 moths ago.

I think for merge, maybe the correct path should be used since we need the edit the file and save the results.

**Comment by DanPristupov** [comment]
@kapcino do you want to be a tester? :)

**Comment by kapcino** [comment]
Yeah, tell me what to do.

**Comment by DanPristupov** [comment]
OK, here's the build which uses original file name and extension: https://cdn.fork.dev/prerelease/Fork-1.0.94.10.dmg

Could you try and tell if makes the diff/merge tool work properly?

**Comment by kapcino** [comment]
Still doesn't  work.
Old and new names in Beyond Compare are like: /private/var/folders/__/93q_61_j5zq4324cz5xrlpl40000gp/T/FF475C32-6417-440E-84DF-C595BE6A1B6D

**Comment by DanPristupov** [comment]
Ouch, sorry. I posted a wrong link.

Here's the correct one: https://cdn.fork.dev/prerelease/Fork-1.0.97.5.dmg

**Comment by kapcino** [comment]
The extension is correct, but the file is still temp file, not the actual one.

<img width="467" alt="fork-bc" src="https://user-images.githubusercontent.com/909314/91417099-dda21180-e882-11ea-932a-06df37f85623.png">

**Comment by DanPristupov** [comment]
Not sure what you mean.

There are 2 or 3 files for diff and merge correspondingly.
For diff: file from one commit and from the other commit.
For merge: two temp files and the actual one which is in the repository directory.

**Comment by kapcino** [comment]
Sorry, my problem, it works now, both for diff and merge.
Thanks.
