### ISSUE TITLE
Push multiple branches all at once

### ISSUE THREAD

**Issue by russianryebread** [ForkIssues/Tracker#1120]
<img width="649" alt="Screen Shot 2020-08-24 at 10 19 34 AM" src="https://user-images.githubusercontent.com/747085/91063669-e6c97f00-e5f3-11ea-82d6-8a2ae8ac348a.png">

One of the only features that I miss from SourceTree is the ability to push to multiple remotes all at once.  This is really helpful after a git flow operation, where you have two or three branches which changed, and can push them at once.

All in all, Fork is really great.  Thank you!

**Comment by DanPristupov** [comment]
You can select multiple branches on the sidebar and select 'Push' in the context menu.

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/Tracker/issues/724

**Comment by russianryebread** [comment]
Thanks for the prompt response!  I searched open issues, but failed to look at the closed ones, so I missed #724.  Thank you!
