### ISSUE TITLE
All avatars identical for users without github accounts

### ISSUE THREAD

**Issue by n8gray** [ForkIssues/Tracker#1125]
Fork Version 1.0.98.1

Very few of my coworkers have github accounts that use their work email. Now that Fork is pulling avatars from github, they all end up identical:

![Screen Shot 2020-09-04 at 2 14 45 PM](https://user-images.githubusercontent.com/82794/92285373-fe88e900-eeb8-11ea-8d98-863d94c9e045.png)

I'm surprised, since I thought the concept of these "random block" icons was to generate a stable icon that's unique to the given identity. Perhaps there's a bug in the way the avatars are being fetched?

On a related note, how are these avatars fetched? Are measures being taken to prevent leaking internal email accounts to Github?  Do they use hashes like Gravatar does?

**Comment by DanPristupov** [comment]
> Very few of my coworkers have github accounts that use their work email. Now that Fork is pulling avatars from github, they all end up identical:

You are right 👍. A very few commits in my repos have no GitHub account and I didn't notice that. Such avatars must fallback to old generated avatars.

> Are measures being taken to prevent leaking internal email accounts to Github? Do they use hashes like Gravatar does?

This is a very good point. The url is `https://avatars.githubusercontent.com/u/e?email=some@domain.com&s=64` and email is not hashed. I suppose we must provide an option to select (and may be disable) the avatar service.

As for now, I will revert this change.

**Comment by n8gray** [comment]
Thank you for the quick response. Apologies for raining on the parade. I think reverting the change was the right move for now. IT departments get weird about stuff like that.

A good solution for user avatars would probably have to be per-repo. Github avatars would be perfect for github projects, but private projects from an internal repo would need to use a different service.

**Comment by DanPristupov** [comment]
We released 1.0.99 with the following updates:
- Fork used GitHub avatars by default, but falls back to generated avatar, if user isn't registered on GitHub
- We introduced an option to disable external avatar services to prevent a possible email leaking
<img width="504" alt="Screen Shot 2020-10-26 at 18 00 06" src="https://user-images.githubusercontent.com/618115/97203480-2871d400-17b5-11eb-86ce-670023549663.png">

**Comment by n8gray** [comment]
It's good that we can disable the whole thing to prevent email leakage, but I think this should be a per-repo setting.  I'd love to use github avatars for github repos and disable it for work repos.
