### ISSUE TITLE
Is there any way to turn off file preview / diff on a file or file type?

### ISSUE THREAD

**Issue by iOSleep** [ForkIssues/Tracker#1128]
https://community.atlassian.com/t5/Sourcetree-questions/SourceTree-Is-there-any-way-to-turn-off-file-preview-diff-on-a/qaq-p/266006

**Comment by DanPristupov** [comment]
No, there's no way to turn file preview off. What is the use case for that?

**Comment by iOSleep** [comment]
the big package-lock.json cast too time

**Comment by zhubroid** [comment]
<img width="200" alt="Screenshot 2022-11-20 at 19 36 58" src="https://user-images.githubusercontent.com/48361880/202899854-52e522db-4b84-4615-b590-ac3f8698ecfd.png">

Just add a file pattern that you wish to ignore in the preview. Pattern *.* will ignore all files.

**Comment by MuhammedResulBilkil** [comment]
If you would like to hide one specific file preview, you need to write its path -> C:\Test\Test.json
