### ISSUE TITLE
Search not finding numbers 6 or more digits

### ISSUE THREAD

**Issue by fecundf** [ForkIssues/Tracker#1129]
I'm searching for error numbers in a busy commit log. If I put in 5 or fewer digits, I find commits, but 6 or more and the search results disappear. When the commit message contains the number 64234825, searching for 64234 finds them, searching for 42348 finds them, but searching for 642348 or 64234825 does NOT find them.

This is in Version 1.0.98.4 - I think it worked a few versions ago, before Search was redone.

<img width="209" alt="Screen Shot 2020-09-11 at 3 34 53 PM" src="https://user-images.githubusercontent.com/317592/92978529-e4b14e00-f444-11ea-8b9c-4d44a6d26f55.png">
<img width="231" alt="Screen Shot 2020-09-11 at 3 34 38 PM" src="https://user-images.githubusercontent.com/317592/92978532-e5e27b00-f444-11ea-9d0e-88e845068413.png">
<img width="228" alt="image" src="https://user-images.githubusercontent.com/317592/92978498-c9ded980-f444-11ea-8a25-fed96aeab4a9.png">

**Comment by fecundf** [comment]
Here's an update – still an issue in Fork version 2.2.1, with a little more info and a sort-of-workaround until this is fixed.

Still can't search for long numbers in commit messages using the "Search Commits" left-pane. However the same number in the top "find" bar will search the displayed commits. So if one can get all commits showing, then click on any commit, hit command-F to open that pane's Find input, and search from the top bar.

Here's an image showing the situation where the left bar won't find, while the top bar does, for the same numeric string.

<img width="739" alt="image" src="https://user-images.githubusercontent.com/317592/105873852-eb8ec680-5fc9-11eb-9813-8e878e0371b3.png">

**Comment by DanPristupov** [comment]
You pressed the 'Enter' key to search on the sidebar, right?

I mean, do other search queries work properly?

**Comment by fecundf** [comment]
Yes, I pressed enter. I also made sure the device was powered on.

**Comment by DanPristupov** [comment]
Do other search queries work? Can you search for `swan` for example?

**Comment by fecundf** [comment]
yes, searching for short words like "swan" works- same as the first post which shows working searches for "64234" and "42348"

 A more interesting question is, do six-or-more-character non-numeric searches work? The answer is yes. This bug happens when the search term is only numbers. Another example, the sidebar gives no results for `722952` but does find `/722952`

**Comment by DanPristupov** [comment]
This problem must be fixed in Fork 2.4

**Comment by fecundf** [comment]
Hi, thanks much! As it was I was just feeling bad about being terse-impolite on this issue and was logging in to apologize, and you already fixed it. I have the update and yes, the search is working with numbers now just as I had hoped.

**Comment by DanPristupov** [comment]
No problem at all. I knew I asked a strange question and wasn't surprised by a little sarcasm in response :).
