### ISSUE TITLE
Ability to be able to search for files from within the file tree view

### ISSUE THREAD

**Issue by brsanthu** [ForkIssues/Tracker#1130]
We have repo which contains close to 50000 files under various folders. Scrolling through to find the file we looking for can be a pain. If there was a way to filter file/files in that view would be awesome and would save so much time.

**Comment by brsanthu** [comment]
Looks like duplicate of https://github.com/ForkIssues/Tracker/issues/428 so closing.

**Comment by DanPristupov** [comment]
You can use: 
Cmd+P -> History -> /search for file/
or
Cmd+P -> Blame -> /search for file/
