### ISSUE TITLE
 [Feature request] Custom external editor

### ISSUE THREAD

**Issue by silver886** [ForkIssues/Tracker#1131]
I use Fork and other editors directly from the external storage because it reduces the time during to switch to a new or others' computer.

After some search, there are some related issue.
The first time Fork support external editors (#280) and the custom merge/diff tools support (#405), although the second one is still open, I saw it on Windows already, that's great!
Also, according to [release notes](https://git-fork.com/releasenoteswin), start from 1.39 there is a way to change git instance with environment variable.

I'm wondering if it is possible to add a custom external editor.
Current way of customizing git and merge/diff tools all look good to me.

**Comment by DanPristupov** [comment]
Do you use Mac or Windows?

> I'm wondering if it is possible to add a custom external editor.

You can create a custom command which will open the repo in the given editor.

**Comment by silver886** [comment]
Sorry for the missing information. 
I'm using both Mac and Windows, but seems Windows is easier to implement this feature.

> You can create a custom command which will open the repo in the given editor.

I thought this would appear when right click the commit instead of "Open in" menu.
Let me try it.

**Comment by DanPristupov** [comment]
Repository custom commands appear in the 'Open in' dropdown on the toolbar. Most likely, this is what you look for.
Commits custom commands appear in the commit context menu.

**Comment by silver886** [comment]
That's what I'm looking for!
Didn't expect the solution would be custom command.

Closing this issue.
