### ISSUE TITLE
[Feature Request] Keyboard shortcut for force option in push dialog

### ISSUE THREAD

**Issue by marvin-yorke** [ForkIssues/Tracker#1134]
When performing `reset` on a branch you're able to use keyboard shortcuts to select reset type (**s**oft/**m**ixed/**h**ard). I'd like to be able to use **f** key in push branch dialog window to select force push

**Comment by DanPristupov** [comment]
Such shortcut will be non-discoverable.

On the contrary, the dropdown in the reset dialog clearly shows the shortcuts.

**Comment by DanPristupov** [comment]
OK, we added `f` as a 'force' option shortcut in 2.0 (event though it's not discoverable 🙂)
