### ISSUE TITLE
Ampersand in branch name is not escaped when creating a pull request

### ISSUE THREAD

**Issue by tplester** [ForkIssues/Tracker#1138]
If you use Push and Create Pull Request on 'origin' on a branch which has an ampersand in the name with a repository on Azure, then the ampersand is not escaped and the pull request isn't created.
This also happens with Create Pull Request on 'origin'

Version Fork 1.0.98.4 Mac

**Comment by DanPristupov** [comment]
This must be fixed in Fork 2.1
