### ISSUE TITLE
[Feature Request] Add "skip hook" button when pre-commit hook fails

### ISSUE THREAD

**Issue by juraj-blahunka** [ForkIssues/Tracker#114]
It would be helpful if one could ignore commit hooks when making a commit (e.g. when merging master into feature branches), current UI doesn't seem to support `--no-verify` commit flag.

**Comment by DanPristupov** [comment]
Hi @juraj-blahunka.

I don't wan't to mess up the commit UI with an additional checkbox which is rarely used. I'm thinking of recognising when commit failed because of a hook and showing the "Commit without hook" button in the error window. Will that be ok?

**Comment by juraj-blahunka** [comment]
@DanPristupov Love the idea!

**Comment by DanPristupov** [comment]
@juraj-blahunka here's how I implemented this:
![2017-10-05 at 15 37](https://user-images.githubusercontent.com/618115/31231017-f69f6aa4-a9e5-11e7-908d-bceed0e39355.png)

The feature is available in 1.0.57.4 which can be downloaded here https://github.com/ForkIssues/Tracker/issues/110. Please let me know if everything makes sense.

**Comment by juraj-blahunka** [comment]
@DanPristupov It's perfect!

**Comment by DanPristupov** [comment]
This feature is available publicly in Fork 1.0.57.6 which I just released.
