### ISSUE TITLE
Search does not consider lost commits (reflog)

### ISSUE THREAD

**Issue by bgagnon** [ForkIssues/Tracker#1140]
When _View > Show Lost Commits (reflog)_ is active, I would expect commit search to include those lost commits in the results. It does not seem like it does that in the current version (1.0.98.4).

**Comment by DanPristupov** [comment]
Hi. The search only searches in the reachable commits. I doesn't (and probably will not) search in reflog and stash revisions.

**Comment by DanPristupov** [comment]
> I doesn't (and probably will not) search in reflog and stash revisions.

Well, it turned out I was wrong and as of Fork 2.34 context search also takes into account reflog commits.
