### ISSUE TITLE
`All Commits` view not sync with the selected search result commit.

### ISSUE THREAD

**Issue by yam-liu** [ForkIssues/Tracker#1144]
When I search some words, I get some commit results. But now the commits list is on the left side of the window, and when click on the commit, `All commits` history view not showing THE commit, so I can not get the related info about this commit. 
It's not convenient than before.

**Comment by DanPristupov** [comment]
Can you show a screenshot with an exampleplease? For me a click on the commit match always reveals it (if it's in the commit tree).

**Comment by yam-liu** [comment]
@DanPristupov 

I record a video, but I cannot provide the example repo, it's giant and private.

I notice the commit I wanna find is committed two years ago, dont know if this related.

[bug.mp4](https://cowtransfer.com/s/5819a163b7044e)  (expire after 7 days)

**Comment by DanPristupov** [comment]
Fork UI only shows the latest 50000 commits. Is it possible that the commit you click on is too far away?

You can change the limit in Terminal using the following command:

`defaults write com.danpristupov.fork maxCommitCount 150000`

**Comment by yam-liu** [comment]
@DanPristupov Maybe. will change the limit affect Fork performance？

**Comment by DanPristupov** [comment]
Yes, of course ;), that's why we have the limit in the first case.

However the performance degradation is not linear. Increasing the limit to 150K commits will slow down some operations by 20-30% may be.

**Comment by yam-liu** [comment]
@DanPristupov Thanks for providing the approach, I will adjust the count only when I want to get the related commits.
