### ISSUE TITLE
Annoying fork[...] ApplePersistence=NO console message

### ISSUE THREAD

**Issue by ssbarnea** [ForkIssues/Tracker#1146]
Apparently when called from command line fork also logs a confusing debug message, even if user did not request any verbosity. Also there is no option to silence this message.

$ fork open -C /Users/ssbarnea/c/os/zuul-jobs                                                                                   [13:53:27]
2020-10-01 13:53:41.830 fork[9646:6508452] ApplePersistence=NO

A launcher should not print anything unless requested.

**Comment by DanPristupov** [comment]
1.  <img width="373" alt="Screen Shot 2020-10-03 at 14 37 53" src="https://user-images.githubusercontent.com/618115/94991843-0904d400-0586-11eb-8eb4-c2808571f457.png">


2. Searching for `ApplePersistence` in the source code returns an empty result

**Comment by DanPristupov** [comment]
http://www.openradar.me/28409008

https://github.com/lionheart/openradar-mirror/issues/15902


Running `defaults delete NSGlobalDomain ApplePersistence` can be a workaround.

**Comment by ssbarnea** [comment]
@DanPristupov Thanks. Apparenty there is nothing we can do about it.
