### ISSUE TITLE
Request: Automatically expand branch folder when a new branch created

### ISSUE THREAD

**Issue by prin53** [ForkIssues/Tracker#1147]
Would be nice if the branch with folder inside will be automatically expanded, so users will be able to immediately see which branch they are on.

1. Create a new branch:
<img width="583" alt="Screenshot 2020-10-02 at 09 24 33" src="https://user-images.githubusercontent.com/4447833/94894065-463b6a00-0491-11eb-8d10-2503559bfac8.png">
2. The branch will be created, but its folder will be collapsed:
<img width="236" alt="Screenshot 2020-10-02 at 09 24 43" src="https://user-images.githubusercontent.com/4447833/94894077-4d627800-0491-11eb-920b-cd6c3e5d072f.png">
3. Users need to manually open the collapsed folder:
<img width="235" alt="Screenshot 2020-10-02 at 09 24 52" src="https://user-images.githubusercontent.com/4447833/94894079-4dfb0e80-0491-11eb-87c0-872f24e2a230.png">

**Comment by pt-paulrahme** [comment]
Looks similar to one I requested in August: https://github.com/fork-dev/Tracker/issues/1147

**Comment by DanPristupov** [comment]
I accidentally came across this old question. Since 2.15 Fork automatically reveals the active branch on the sidebar on checkout.
