### ISSUE TITLE
Repository Selection Width Issue

### ISSUE THREAD

**Issue by ApricumMedia** [ForkIssues/Tracker#115]
The list of repositories in *Fork 1.0.56.1 (Mac OS)* is rendered with a list on the left side, using about 90% of available width in the pane, with the "Add Repository" button on the upper right hand side. When selecting a repo from the list, the blue selection is slightly off on the right part where it overflows the list (gray lines).

![screen shot 2017-10-05 at 09 14 07](https://user-images.githubusercontent.com/7656669/31216053-6b0c16b4-a9b2-11e7-8b87-8b6750f01222.png)

**Comment by DanPristupov** [comment]
@ApricumMedia will fix in the next Fork release. Thank you.

**Comment by DanPristupov** [comment]
Fixed in 1.0.57. Thanks.
