### ISSUE TITLE
Clone remote repository do not show all accounts

### ISSUE THREAD

**Issue by SergioSuarezGil** [ForkIssues/Tracker#1150]
Clone remote repository do not show all accounts 
Fork Version 1.0.98.4
MacOS:  10.15.7 (19H2)

**I have 4 accounts:**
<img width="282" alt="Captura de pantalla 2020-10-06 a las 16 55 47" src="https://user-images.githubusercontent.com/3636232/95219005-2b505900-07f5-11eb-9bb9-aac136fd8d45.png">

**Here i can see only 3 (the last is missing):** 
<img width="520" alt="Captura de pantalla 2020-10-06 a las 17 01 08" src="https://user-images.githubusercontent.com/3636232/95219355-90a44a00-07f5-11eb-8763-8a79d9c87e1b.png">

<img width="610" alt="Captura de pantalla 2020-10-06 a las 16 59 30" src="https://user-images.githubusercontent.com/3636232/95219150-55098000-07f5-11eb-8b7e-36c2566d6e93.png">

**Comment by DanPristupov** [comment]
First of all, it should not be possible to create multiple accounts on the same service, because this feature is not implemented yet :). Looks like we introduced a bug there.

**Comment by SergioSuarezGil** [comment]
Okay! So then I take the opportunity to support the option of creating multiple accounts for the same service. In my case, I need 2 Github and Bitbucket accounts, because I use my laptop for my own projects in addition to the projects of the company I work for, thank you very much Dan & continue with your great work!

**Comment by robotink** [comment]
thats funny just today i tried creating a 2nd gitlab account, it worked fine but didnt work when cloning

I second the request, having a work + personal account on the same service would be great, thanks!

**Comment by joshbuhler** [comment]
Seeing the same thing here - I have two Github accounts added, but only one of them shows up in the dropdown menu of the clone window.

I was able to add the second Github account using the following steps:

1. In the Accounts window, click the + icon at the bottom-left
2. Double-click the GitHub icon
3. Proceed to login to Github

Having two Github accounts hasn't been a big deal for me until now. Previously, all of my personal stuff was on Github, with the work stuff on Gitlab. However, we'll be transitioning to Github soon, so I'll need to be able to manage the two Github accounts.

**Comment by SergioSuarezGil** [comment]
+1 to multiple accounts soon 😜

**Comment by DanPristupov** [comment]
The ability to have multiple accounts was introduced in Fork 2.5.

**Comment by SergioSuarezGil** [comment]
Nice, thanks!

**Comment by robotink** [comment]
thanks, you are awesome!
