### ISSUE TITLE
Staging, unstaging and discarding doesn't always refresh the view

### ISSUE THREAD

**Issue by siraic** [ForkIssues/Tracker#1152]
There quite a few different ways of staging / unstaging / discarding, and not all of them refresh the view. These are the methods that don't refresh the view:

- Stage file using button above file list.
- Stage file using cmd+s.
- Stage chunk/line using button above change.
- Unstage file using button above file list.
- Unstage file using drag & drop.
- Unstage file using context menu (both unstage and unstage all).
- Unstage file using cmd+shift+s.
- Unstage file using cmd+shift+option+s.
- Unstage chunk using button above change.
- Discard chunk/line using button above change.

I tried to be as precise as I could be in the description and research. Let me know if you need more information. Thanks for doing an excellent job building and maintaining my favourite git client.

**Comment by DanPristupov** [comment]
Could you check if the log file (`~/Library/Logs/Fork.log`) contains any errors?

**Comment by DanPristupov** [comment]
> These are the methods that don't refresh the view:
> Stage file using cmd+s.

Do you mean you press Cmd+S on a file and nothing happens?

What methods do refresh the view?

**Comment by siraic** [comment]
What I meant with 'don't refresh the view' was that the action is performed correctly, but I have to press cmd+r to see it reflected in the UI.

The log indeed contains errors:

```
ℹ️[RefreshRepositoryCommand.swift:190] refreshRepositoryStatus(_:_:_:_:_:_:_:_:_:) > Refresh 'testrepo' status. Updated (1 files).
ℹ️[RefreshRepositoryCommand.swift:190] refreshRepositoryStatus(_:_:_:_:_:_:_:_:_:) > Refresh 'testrepo' status. Updated (1 files).
⚠️[GitRequest.swift:206] execute(suppressErrorLogging:cancelationToken:) > Git error '--no-optional-locks status --porcelain --renames --untracked-files=all -z -- testfile.txt':
error: unknown option `renames'
```

I've updated my git-client from 2.17 to 2.28 and the issue is resolved. Thanks for the help, and sorry to bother you with it!

**Comment by DanPristupov** [comment]
No problem. I'm glad I could help.
