### ISSUE TITLE
Add remote name in the "View in GitHub" menu item

### ISSUE THREAD

**Issue by NicolasMassart** [ForkIssues/Tracker#1153]
When having a few remotes, it's not easy to see which "View in GitHub" matches the remote we want to view.
Following is just with two remotes, imagine when I have all my colleagues forks listed...
![image](https://user-images.githubusercontent.com/4677568/95485651-5623e400-0992-11eb-837e-e86ec6dbc64b.png)

Adding the remote name to have "View 'upstream' in GitHub" and "View 'origin' in GitHub" or "View 'myfriendfork' in GitHub" would help.

Maybe, because we already have the GitHub logo on the left, just "View 'remote name'" would be enough.

Thanks! Best Git GUI ever.

**Comment by DanPristupov** [comment]
Implemented in 2.1:

<img width="245" alt="Screen Shot 2020-12-08 at 13 13 11" src="https://user-images.githubusercontent.com/618115/101482507-20ca5100-3957-11eb-80c7-670c85d72fa3.png">
