### ISSUE TITLE
merge squash not working

### ISSUE THREAD

**Issue by noethig** [ForkIssues/Tracker#1155]
whenever I try to merge a branch into its parent in the following way

![grafik](https://user-images.githubusercontent.com/5759469/95872989-bee2d600-0d6f-11eb-9b32-8735ab3f2dd3.png)

I get the following error message:

    "fatal: You cannot combine --squash with --no-ff."

![grafik](https://user-images.githubusercontent.com/5759469/95872387-06b52d80-0d6f-11eb-91d5-bdb18e0b6a26.png)

git is not configured with merge-options, so I don't realy understand, where the option `--no-ff` is injected from. The command from gitfork yields

    $ git merge x --squash
    fatal: You cannot combine --squash with --no-ff.

When I execute the following command

    git merge --squash --ff target-branch

in gitbash, it works fine.

Is there a configuration I missed, which enforces `--no-ff`, or is this a bug?

**Comment by DanPristupov** [comment]
1. Please check the exact command in the activity manager (click on the status control on the toolbar). Update: it looks like this is what you showed.

2. Check the value of the `merge.ff` config value in command line:

`git config --show-origin merge.ff`

https://git-scm.com/docs/git-merge#Documentation/git-merge.txt-mergeff

**Comment by noethig** [comment]
Thank you very much for your fast help! :D the value was indeed set to `no`
after executing `git config --global merge.ff yes` everything works fine 👍

**Comment by noethig** [comment]
Thank you very much for your fast help! :D the value was indeed set to `no`.
After executing `git config --global merge.ff yes` everything works fine 👍
