### ISSUE TITLE
Gitmoji support

### ISSUE THREAD

**Issue by infotexture** [ForkIssues/Tracker#1157]
💡 What if [Fork](https://fork.dev) would render @carloscuesta’s [Gitmoji](https://gitmoji.carloscuesta.me) in history, so `:bug:` appears as 🐛and `:sparkles:` as ✨, etc. ?

Several projects have adopted this convention, and it’s pretty handy for recognizing at a glance what type of changes commits include. Kind of like [Conventional Commits](https://www.conventionalcommits.org), but more visual — and fun.

**Comment by DanPristupov** [comment]
There's a similar issues already https://github.com/ForkIssues/Tracker/issues/296

**Comment by infotexture** [comment]
@DanPristupov Sorry, missed that one. I see in #296 that related issue #940 was closed, so I'll close this too as a duplicate.

Given the multiple issues that have been created, and [sorting the open issues by number of comments](https://github.com/ForkIssues/Tracker/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-desc) suggests this is a popular request. 👀 💬🤞
