### ISSUE TITLE
Rebase with conflicts can't be resolved

### ISSUE THREAD

**Issue by lkster** [ForkIssues/Tracker#1159]
If I do a rebase which gets some conflicts I can't commit resolved files. GIT says that it can't commit changes without any message. The message is actually filled automatically by Fork without any possibility to fill / change it.

![obraz](https://user-images.githubusercontent.com/10232371/96164269-4882d700-0f1b-11eb-9005-c173d1e585ef.png)

**Comment by DanPristupov** [comment]
Did you start the rebase from Fork?

**Comment by lkster** [comment]
@DanPristupov Of course, I don't use console nor other git client at all

**Comment by DanPristupov** [comment]
What git instance does Fork use? If I remember correctly git changed the rebase format some time ago and this error can be caused by it.

**Comment by lkster** [comment]
2.27.0 Fork Instance. Also Fork's version is 1.0.98.4

**Comment by DanPristupov** [comment]
OK, it looks like we need to go deeper. Could you send the fork log file (it's located at `~/Library/Logs/Fork.log`) to support@fork.dev?

**Comment by lkster** [comment]
Sure, I've sent it

**Comment by DanPristupov** [comment]
The problem was caused by commit messages that start with `#` (which is a comment symbol in git).
