### ISSUE TITLE
Fork crushes when opening repository

### ISSUE THREAD

**Issue by KutnerUri** [ForkIssues/Tracker#1160]
I just migrated to a new Mac, and now fork is crushing whenever I try to open a project.
(i.e. clone project, open existing repository, and creating a new one)

Any ideas how I can fix it, reset the app setting etc?

**Comment by DanPristupov** [comment]
Did you switch Fork to a custom git instance which now became invalid?

You can change it in the application preferences: `Fork -> Preferences -> Git`

> I just migrated to a new Mac

What do you mean? How did you migrate?

**Comment by KutnerUri** [comment]
> You can change it in the application preferences: `Fork -> Preferences -> Git`

Ok I think this is the problem.
How do I reset this?
![Screen Shot 2020-10-18 at 17 02 54](https://user-images.githubusercontent.com/5400361/96369621-ccc79b00-1163-11eb-8ff4-8bfa74ed9aa1.png)


> > I just migrated to a new Mac
>
> What do you mean? How did you migrate?

using the mac migration assistant.

**Comment by DanPristupov** [comment]
> How do I reset this?

Try to reset all settings by running `defaults delete com.DanPristupov.Fork` in Terminal

**Comment by KutnerUri** [comment]
yesss it worked, thanks!
