### ISSUE TITLE
Feature request: add "Open Swift Package" action to "Open In" menu

### ISSUE THREAD

**Issue by doroshenko** [ForkIssues/Tracker#1161]
With Swift Package Manager, `Package.swift` file in the root of the git repo can serve the same role as traditional Xcode projects and workspaces. Double-clicking this file in Finder opens Xcode with the list of source files, resources and dependency packages. Traditional xcodeproj or xcworkspace files may not even be present anymore. 

It would be nice to have "Open Swift Package" action in Fork's "Open In" menu for convenience.

**Comment by SimplyDanny** [comment]
I'd love to see that too.

**Comment by SimplyDanny** [comment]
Works like a charm in 2.17. Thank you for implementing it, @DanPristupov!
