### ISSUE TITLE
[Feature] Undo with "git bundle"

### ISSUE THREAD

**Issue by svoop** [ForkIssues/Tracker#1166]
I'm not sure whether this is a good idea, therefore this is more a RFC than a feature request. 😄 

Sometimes, I'm doing "dangerous" stuff like a rebase with many collisions or just trying a new feature of Fork. It would be nice to have an "undo" button which is very difficult to implement if you actually want to undo every specific scenario.

Maybe there's a simpler solution with full backups.

* I'm currently `tar`ing the directory before trying anything funky, but this takes a long time on bigger repos even when no compression is used.
* There's `git bundle create {FILENAME} --all` which packs almost everything (e.g. no hooks) into a single file.

An "undo" feature might work as follows: You first create a backup which does something like `git bundle create .git/backups/{FILENAME} --all`. To restore a specific backup, you'd chose from the list of backups.

What do you think, useful, possible or troublesome, impossible?

**Comment by DanPristupov** [comment]
> Sometimes, I'm doing "dangerous" stuff like a rebase with many collisions or just trying a new feature of Fork.

Generally speaking, you can backup majority of things by creating a backup branch (that's what interactive rebase dialog proposes).

You can also backup the working directory changes using the new 'make snapshot' option inside the Stash dropdown on the toolbar.

Regarding the built-in undo feature. I'm not sure about the solution yet, but making whole backup is not an option (e.g the `Chromium` repo is 20 Gb).

I need some time to think about this.

**Comment by svoop** [comment]
> e.g the Chromium repo is 20 Gb

Fair point! 👍 I guess, this Issue can be closed then.

**Comment by DanPristupov** [comment]
Well, let's close it because there's a similar your issue already :) https://github.com/fork-dev/Tracker/issues/981
