### ISSUE TITLE
[Feature Request] Github avatars for people with email privacy enabled

### ISSUE THREAD

**Issue by stephenpope** [ForkIssues/Tracker#1168]
GitHub offers users the ability to keep their email address private and recommends using this option:
[help.github.com/articles/keeping-your-email-address-private](help.github.com/articles/keeping-your-email-address-private)
[help.github.com/articles/setting-your-email-in-git](help.github.com/articles/setting-your-email-in-git)

If you have the *Email Privacy* feature enabled in Github you will sign your commits with an email that looks like:

```[GITHUBUSERID]+[GITHUBUSERNAME]@users.noreply.github.com```

It would be great if `Fork` coukd notice if the commit email domain was `users.noreply.github.com` then it could parse out the username and then use that to retreive the correct avatar from the Github API (e.g `https://api.github.com/search/users?q=[GITHUBUSERNAME]`)

**Comment by DanPristupov** [comment]
Implemented in Fork 2.1

<img width="450" alt="Screen Shot 2020-12-08 at 13 14 56" src="https://user-images.githubusercontent.com/618115/101482692-5f600b80-3957-11eb-971e-d99177cff20f.png">
