### ISSUE TITLE
[BUG] "label" placeholder appears on Remote branches

### ISSUE THREAD

**Issue by FranciscoAmado** [ForkIssues/Tracker#117]
### Fork Version 1.0.57.5

A `Label` placeholder appears at the right of Remote branches.

![screen shot 2017-10-09 at 11 40 42](https://user-images.githubusercontent.com/6344795/31334692-3c751d04-ace7-11e7-8870-320e17e32e41.png)

Cheers 👍🏻

**Comment by DanPristupov** [comment]
Hi Francisco. Thank you very much for the quick report. Not sure how I could miss this...
I just fixed the bug and released the hotfix update (1.0.57.6).

**Comment by FranciscoAmado** [comment]
This is fixed on the new version 👍🏻 Thanks 😁
