### ISSUE TITLE
Deached Head not display in commit graph

### ISSUE THREAD

**Issue by pkernevez** [ForkIssues/Tracker#1171]
Hi,

When I'm in a detached head, the commit is not display in the graph.
I have this problem in 2 situations : 
1) When I checked-out a commit without having a branch and then start to work from this commit wihtout having a branch. The commits I create are never display in the graph. I can show them by creating a tag or a branch, but without them, nothing is displayed.
2) More problematique, during a rebase with conflics to solve, I don't see the 'new graph under construction', so I don't know which is the commit that is the source of the problem.
I only have the feedback : '3 of 10 commits'
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/338699/97861533-36b77700-1d04-11eb-8aba-fddb74bc2151.png">
If I do a `git log graph` I saw the HEAD and the already rebased commit:
<img alt="image" src="https://user-images.githubusercontent.com/338699/97861947-daa12280-1d04-11eb-8691-3abca5ad67e4.png">

**Comment by DanPristupov** [comment]
> When I'm in a detached head, the commit is not display in the graph.

In my case the HEAD is displayed.

Do you have enabled commit filter may be (Cmd+Shift+A)?

**Comment by DanPristupov** [comment]
The commits on your screenshot are grayed out. Are there any black commits or whole whole commit list is gray?

Can you show the graph until the first common parent of the branches? Otherwise it's difficult to say what's going on.

**Comment by pkernevez** [comment]
They are all grey in this repository (no always the case in other repositories).
What change the color of the commits ?

With a simple repository, it seems to be ok: I can checkout a commit (Detach Head) and do some commit on it. Every thing is fine.

On my repository:
I can checkout a commit, HEAD is well positionned in the graph (the commit Temp in bold).
<img width="132" alt="image" src="https://user-images.githubusercontent.com/338699/97872006-9a966b80-1d15-11eb-9ee3-823c19122644.png">

When I had a commit, the new commit (on top of Temp) is not displayed, the commit Temp is not any more bold (this is normal a it's supposed to bold the new missing commit) and the 'Head' in the left menu do not put focus on anything:
<img width="152" alt="image" src="https://user-images.githubusercontent.com/338699/97872170-ddf0da00-1d15-11eb-9256-040ed297d7c7.png">

Is there a way to activate logs ?

**Comment by DanPristupov** [comment]
> What change the color of the commits ?

The commits which belong to the active  branch are black.


Is there anything unusual in this repo? Is it located on a network disk? Does contain git worktrees?

We can find out what's going on if you contact me by email: support@fork.dev

**Comment by pkernevez** [comment]
They are all grey in this repository (no always the case in other repositories).
What change the color of the commits ?

With a simple repository, it seems to be ok: I can checkout a commit (Detach Head) and do some commit on it. Every thing is fine.

On my repository:
I can checkout a commit, HEAD is well positionned in the graph (the commit Temp in bold).
<img width="132" alt="image" src="https://user-images.githubusercontent.com/338699/97872006-9a966b80-1d15-11eb-9ee3-823c19122644.png">

When I had a commit, the new commit (on top of Temp) is not displayed, the commit Temp is not any more bold (this is normal a it's supposed to bold the new missing commit) and the 'Head' in the left menu do not put focus on anything:
<img width="152" alt="image" src="https://user-images.githubusercontent.com/338699/97872170-ddf0da00-1d15-11eb-9256-040ed297d7c7.png">

Is there a way to activate logs ?

**Comment by pkernevez** [comment]
Hi Dan,

I did several tests and I wasn't able to reproduce this beahviour in another context.
I think it's may related to the remote and local branch (my remote branch was far behind the local one, from which I create the detached head).
