### ISSUE TITLE
Custom command being triggered "randomly"

### ISSUE THREAD

**Issue by maksimovic** [ForkIssues/Tracker#1172]
I've set up a custom command to create a PR against the "upstream" master, but it's working too good 😅 

It sometimes gets triggered on creating a new branch, checking out remote branch, or pushing the changes. Not always, but just sometimes. Is there any more info that I can provide except the screenshot of the command's settings?

Edit: running Catalina 10.15.7 and Fork 1.0.99

<img width="831" alt="Screenshot 2020-11-03 at 12 29 59" src="https://user-images.githubusercontent.com/1126226/97980346-ea863880-1dd0-11eb-9e62-627409007d84.png">

**Comment by DanPristupov** [comment]
We checked the source code, but there's nothing suspicious.

> running Catalina 10.15.7 and Fork 1.0.99

I also use Catalina and I noticed that there's a problem with Safari that sometimes it opens url with a delay which can be rather long (~10 seconds?). Can this be the case?

**Comment by maksimovic** [comment]
No, because I don't get the browser to open the page. It's Fork that opens the "Are you sure you want to execute custom command" prompt out of nowhere, except that I didn't even want to do it.
