### ISSUE TITLE
[Feature Request] A new icon

### ISSUE THREAD

**Issue by DevilDimon** [ForkIssues/Tracker#1179]
The updated Apple Human Interface Guidelines for macOS (https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/) feature the new app icon shape (the squircle). It would be nice for Fork to follow suit and adopt the new visual style.

**Comment by daniel-white** [comment]
2.0 has this.

**Comment by sirnacnud** [comment]
Any chance the old icon could be published so people can use it if they want? MacOS allows you to change app icons. I'm still on Catalina and the squircle icon looks pretty out of place.

**Comment by DanPristupov** [comment]
@sirnacnud You can copy it from 1.0.99: https://cdn.fork.dev/mac/Fork-1.0.99.dmg
