### ISSUE TITLE
Icon for local branches

### ISSUE THREAD

**Issue by p16r** [ForkIssues/Tracker#1180]
Loving the separators between icon and name for remotes and tags. Could you add generic branch icons for local branches and make the active branch name bold just like most recent commit on that branch?

<img width="254" alt="Screenshot 2020-11-13 at 20 02 28" src="https://user-images.githubusercontent.com/29314504/99083184-2bf5bf80-25eb-11eb-8de2-fd9d2ab7d8cd.png">

**Comment by daniel-white** [comment]
It also is super hard to see the icons in dark mode

**Comment by DanPristupov** [comment]
> Could you add generic branch icons for local branches 

No. We intentionally want to local and remote branches visually different.

@daniel-white I'm releasing a hotfix in a few minutes

**Comment by p16r** [comment]
I understand. Right now it looks more like you forgot to add the icon than it looks like an intentional choice, given that each entry in the side bar, remotes, stashes, and tags have icons but local branches don't. Thanks for the clarification.
