### ISSUE TITLE
Distance between commits

### ISSUE THREAD

**Issue by spromicky** [ForkIssues/Tracker#1182]
In tree view vertical distance between commits become bigger. Can you pls return old distance or take an option to change it in preferences?

**Comment by DanPristupov** [comment]
No, we cant return the old distance.
We increased the row height to make Fork look consistent in macOS Big Sur.

`a spacious new design that makes navigation easier` :)

**Comment by DanPristupov** [comment]
We also will increase the row height on the sidebar soon. I don't like those changes myself, but since we live in the Apple world, we must behave like a citizen.

**Comment by spromicky** [comment]
😔

**Comment by dean0x7d** [comment]
Please do consider adding an option for line spacing. Too much padding can feel like wasted space, depending on the context, and I do feel like this is such a context. 

This also reminds me a bit too much of the old issue from SourceTree: https://jira.atlassian.com/browse/SRCTREE-5204 (Although it's not as drastic in Fork now.) That old issue is the one that got me to start using Fork in the first place (after holding out on an older version of SourceTree for a long time). 

But I am glad that I did switch to Fork. Fork is amazing, thank you so much for your great work! I'm just afraid of seeing history repeat itself. And I do hope that you'll consider making the line spacing optional.

**Comment by DanPristupov** [comment]
Fork is a native macOS application. We use same row height as in Finder. When it was 14px, we also used 14px. Now it's 16px and we also use 16px.

Here's a quote from Apple Human Interface Guidelines (https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/)

<img width="721" alt="Screen Shot 2020-11-16 at 11 13 17" src="https://user-images.githubusercontent.com/618115/99240501-da248380-27fc-11eb-8218-3a42abb378b1.png">

**Comment by dean0x7d** [comment]
I understand. And I really do appreciate your efforts to create a native application with a native look and feel -- it's pretty rare these days for cross-platform applications, that's commendable! However, I do see a couple of issues still:
1. It seems to me that the font size didn't increase as indicated by the macOS 11 style guide, which gives it the feeling of extra white space.
2. While it may fit in with macOS 11, it now looks strange on macOS 10.15 and lower. It no longer looks native on those versions.
3. The macOS 11 style guide suggests defaults and I do think it's wise to follow them. But I don't think that there's anything wrong with offering additional options. Especially with macOS 10 vs 11 differences.
