### ISSUE TITLE
"Initialize Git LFS" does not appear to have an effect

### ISSUE THREAD

**Issue by amoffatt** [ForkIssues/Tracker#1184]
Running this command on our repository does not seem to change anything

**Comment by DanPristupov** [comment]
It should run `git lfs install --local`
What is the expected behavior?

**Comment by amoffatt** [comment]
As fork provides an intuitive GUI for most git functions, I expected either a wizard to show up (perhaps allowing selection of file extensions), and a command to perform `git lfs migrate import`
(But I understand this isn't a priority feature)
