### ISSUE TITLE
Edit name for the new remote branch on push

### ISSUE THREAD

**Issue by homm** [ForkIssues/Tracker#1185]
For the instance, I have my own prefixes in branch names and don't want to expose them to the origin.

<img width="546" alt="Screenshot 2020-11-18 at 17 37 50" src="https://user-images.githubusercontent.com/128982/99544429-5a95e080-29c5-11eb-8424-5f2a40676be2.png">

**Comment by DanPristupov** [comment]
If Fork 2.1 we added an option to push to a custom remote branch (or refspec)

<img width="482" alt="Screen Shot 2020-12-08 at 09 49 47" src="https://user-images.githubusercontent.com/618115/101461094-b7d4e000-393a-11eb-91c6-97c1811049ab.png">

**Comment by homm** [comment]
Cool!
