### ISSUE TITLE
Create Universal app to natively support Apple Silicon

### ISSUE THREAD

**Issue by neilmorton** [ForkIssues/Tracker#1186]
Fork is running under Rosetta 2 on new Apple Silicon devices, but are you looking to port to a Universal app for full native support?

**Comment by infotexture** [comment]
[2.1 Release Notes](https://fork.dev/releasenotes):

> Native support for Apple Silicon (M1)

**Comment by neilmorton** [comment]
Native support for Apple Silicon (M1) (Universal app) was included in [Fork 2.1](https://fork.dev/releasenotes).

Thanks @infotexture for the heads up.

Closing this issue.
