### ISSUE TITLE
Statistics - Commits per day hour

### ISSUE THREAD

**Issue by MichalBryxi** [ForkIssues/Tracker#1189]
Clicking on `Repository -> Repository statistics ...` I can see the `Commits per day hour` graph. It's not obvious what time / timezone is it using? We have people working all around the globe and for one person _3pm_ means _11pm_ for other person. 

Will two commits with _the same_ timestamp, but from _two different timezones_ show in the graph as:

1. Two commits at **the same** time. Therefore both adjusted to my current timezone.
2. Two commits at **different** times. Therefore both representing time at creator's timezone.

**Comment by DanPristupov** [comment]
I think the time is UTC time adjusted to your local timezone.

So, the stats will change if you open them in different time zones.

Like: `git log --pretty=format:'%ct %s'`

**Comment by MichalBryxi** [comment]
Perfect. We tried to change timezone locally and the graph has changed. So that aligns with what you're saying. Thank you. Maybe this as an explanation would help prevent future questions. But my question here is answered (and documented for future generations :)).
