### ISSUE TITLE
Bad behavior while deactivate+hide and reactivate Fork on macOS

### ISSUE THREAD

**Issue by ferben** [ForkIssues/Tracker#1190]
**How to reproduce:**
Launch Fork and open any repo. Make any changes in repo, click to "Local changes".
Press Alt and click outside of Fork.app –> this means switch to another app + hide Fork.app (standard macOS behavior since classic MacOS 7).
Switch back to Fork.app by clicking to Fork icon (NOT by key shortcut).

**Current state/behavior:**
See changed/alternative buttons:
1. "Commit">"Commit and Push",
2. "Stage">"Stage All",
3. "Unstage">"Unstage All"

**Wanted state/behavior:**
Default buttons eg. Commit, Stage, Unstage not alternative.

Like: `applicationWillBecomeActive:()` should reset button state to default.

**Comment by DanPristupov** [comment]
This must be fixed in Fork 2.3

**Comment by ferben** [comment]
Verified.
