### ISSUE TITLE
Staging files with non-ASCII characters in filename fails

### ISSUE THREAD

**Issue by ole** [ForkIssues/Tracker#1192]
Fork 1.0.99.1
macOS 10.15.7

This issue is probably related to #955 and #938. I'm filing a new one because neither issue describes this problem exactly.

Problem: Fork cannot stage/unstage files that contain a non-ASCII character such as "ä" in the filename.

Steps to reproduce:

1. In Terminal:

```sh
mkdir testrepo
cd testrepo
git init
touch ä.txt
fork .
```

2. Fork shows the added file correctly, but clicking the Stage button has no effect (the spinner in the toolbar spins for a second, but nothing else happens).

<img width="1171" alt="Screen Shot 2020-11-24 at 19 22 36" src="https://user-images.githubusercontent.com/5010/100135885-8bc15580-2e8a-11eb-8f9d-845766eb92ec.png">

After adding the file in Terminal with `git add .`, Fork correctly moves the file to the Staged list.

**Comment by DanPristupov** [comment]
Can you show output of the `git status --untracked-files=all` command please?

**Comment by ole** [comment]
> Can you show output of the `git status --untracked-files=all` command please?

Sure, here you go:

```sh
$ git status --untracked-files=all
On branch main

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	ä.txt

nothing added to commit but untracked files present (use "git add" to track)
```

By the way, in case it's important, this is my git version in Terminal:

```
$ git --version
git version 2.29.2
hub version 2.14.2
```

**Comment by DanPristupov** [comment]
Strange. For me it's:

```
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   "\303\244.txt"
```

**Comment by ole** [comment]
Hm, interesting. So could this be a shell- or terminal-related issue? FWIW, I'm using iTerm2 and the Fish shell, so not exactly a standard setup. Would this affect Fork in any way?

**Comment by ole** [comment]
New information: the problem doesn’t happen with all non-ASCII characters. For example, Fork has no problems with a file named `ß.txt` (created via `touch ß.txt`).

I wonder if the issue is specific to _accented characters_ and other characters that have two different Unicode representations. For example, `ä` can be either U+00E4 (the actual character ä) or U+0061 U+0308 (the character a, followed by a diaresis composing sequence). Both are equivalent, but if Fork uses one representation and the file system or Git use the other, that might explain the issue.

Swift code to demonstrate:

```swift
let a1 = "\u{E4}" // ä
let a2 = "\u{61}\u{308}" // also ä
a1 == a2 // true
```

> ```
> 	new file:   "\303\244.txt"
> ```

I couldn’t find any reference what those escape sequences in the filename mean? Do you know? Are these hex or decimal digits? What's the encoding?

**Comment by DanPristupov** [comment]
> I couldn’t find any reference what those escape sequences in the filename mean? Do you know? Are these hex or decimal digits?

https://git-scm.com/docs/git-config#Documentation/git-config.txt-corequotePath

Can you try to run the following please? It should should how this parameter affects the output.

```
git status --porcelain --untracked-files=all
git -c core.quotepath=false status --porcelain --untracked-files=all
git -c core.quotepath=true status --porcelain --untracked-files=all
```

On my computer:

```
% git status --porcelain --untracked-files=all
?? "\303\244.txt"

% git -c core.quotepath=false status --porcelain --untracked-files=all
?? ä.txt

% git -c core.quotepath=true status --porcelain --untracked-files=all
?? "\303\244.txt"
```

**Comment by ole** [comment]
Sure.

```
$ git status --porcelain --untracked-files=all
?? ß.txt
?? ä.txt

$ git -c core.quotepath=false status --porcelain --untracked-files=all
?? ß.txt
?? ä.txt

$ git -c core.quotepath=true status --porcelain --untracked-files=all
?? "\303\237.txt"
?? "\303\244.txt"
```

Thanks for telling me about this option. It's true that I have `core.quotepath=false` in my global Git config. I don't remember when or why I added this, but it's there:

```
$ git config --global --list | grep quotepath
core.quotepath=false
```

When I change this setting to true, sure enough that changes the display of the filenames in `git status`. But the setting doesn't seem to be affecting Fork in any way.

FWIW, my Fork Preferences are configured to use Fork's own Git instance (2.27.0):

<img width="545" alt="Screen Shot 2020-12-01 at 16 08 04" src="https://user-images.githubusercontent.com/5010/100758137-764ead00-33ef-11eb-908e-c95c2d8e7939.png">

This is still on Fork 1.0.99.1. I'm going to update to 2.0.2 next and see if that changes anything.

**Comment by ole** [comment]
Fork 2.0.2 doesn't seem to hve changed anything, I'm still seeing the same issue.

**Comment by DanPristupov** [comment]
I made some improvements in 2.3. Staging and unstaging of `ä.txt` work on my computer now.

However, I guess, there will be no difference for you, but it's still worth checking.

It looks like the problem is that the arguments of NSTask are not encoded properly (https://developer.apple.com/documentation/foundation/process/1408983-arguments), but I couldn't find a way to change the encoding 🤷‍♂️.

**Comment by ole** [comment]
@DanPristupov Thanks for working on this. I tried with 2.3 but you're right, I'm not seeing any change.

**Comment by ole** [comment]
I don’t know what changed, but the problem has (mostly?) disappeared for me. I hadn’t tried it for a while because I switched to another Git client for my problematic repository (where I'm using filenames with accented characters a lot). But I tried this repo with Fork again and staging files with accented characters has been working fine for a few days now.

I don’t know if something in my configuration changed or if it was a particular Fork update that did it. I'm running v2.5.6 right now and I did an automatic update a few days ago, but the problem was fixed before that, so it wasn't the last update.

The problem doesn't seem to be 100% gone, either. When I repeat the steps from my initial post:

```
mkdir testrepo
cd testrepo
git init
touch ä.txt
fork .
```

This works fine now.

But my old `testrepo` folder that I created months ago when I filed this issue still shows the original issue. I can't explain it.

Anyway, my immediate problem seems to be fixed for now. @DanPristupov Do you want me to close this or would you rather keep it open?
