### ISSUE TITLE
commits history empty on macOS

### ISSUE THREAD

**Issue by xoyojank** [ForkIssues/Tracker#1194]
if I filtered the commits by one branch, the commits history begin empty
![企业微信20201126-153905](https://user-images.githubusercontent.com/2873643/100321865-52115b80-2ffe-11eb-94bd-360b990aa791.png)

**Comment by DanPristupov** [comment]
Fork has a limit for 50000 commits. Is that possible that this branch is too far away?

You can increase the limit using the following terminal command:
`defaults write com.danpristupov.fork maxCommitCount 150000`

**Comment by xoyojank** [comment]
it's worked! thank you very much. 
UE4's commits are too much, if I add the github respository to remotes

**Comment by hitzhangjie** [comment]
It should be `defaults write com.DanPristupov.Fork maxCommitCount <n>`.
