### ISSUE TITLE
[Issue] Merge dialog erroneously shows "manual resolution" warning sometimes

### ISSUE THREAD

**Issue by ghost** [ForkIssues/Tracker#1196]
v2.0.2
macOS Catalina 10.15.7

When merging branches that do not generate manual conflict resolutions, the warning in the merge dialog still appears sometimes. This issue has been around for a few versions now, perhaps since 1.0.98.

Step 1: Merge branches and get warning that the merge will require manual resolution
<img width="501" alt="image" src="https://user-images.githubusercontent.com/70993406/100656349-72039f00-33b1-11eb-9972-788490caf848.png">

Step 2: Branches merge with no conflicts
<img width="796" alt="image" src="https://user-images.githubusercontent.com/70993406/100656445-9f504d00-33b1-11eb-9188-d4ec90da786a.png">

Edit: I merged the branches again after an extra change was added on the source branch and the warning did not appear, even though the files changed in the new commit still did not conflict.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/70993406/100657079-990ea080-33b2-11eb-91a3-29fdba5d443a.png">

**Comment by maksimovic** [comment]
I get this in Fork sometimes, too. However, I've also noticed that Github sometimes reports that a PR has a conflict to be manually resolved, while the actual git merge happens without any conflicting files popping up.

I'm wondering if it could be related to git itself, but I'm not too familiar with its inner workings.

**Comment by DanPristupov** [comment]
We improved the conflict detection. It should not happen so often now.
