### ISSUE TITLE
[Issue] Branch push indicator disappears when stashing changes

### ISSUE THREAD

**Issue by ghost** [ForkIssues/Tracker#1197]
v2.0.2
macOS Catalina 10.15.7

When choosing to commit some files and stash the rest, the push indicator on the left side column disappears when the remaining files are stashed. This issue has been around for a few versions now, perhaps since 1.0.98.

Step 1: Make changes, roll some (not all) into local, unpushed commit
<img width="234" alt="image" src="https://user-images.githubusercontent.com/70993406/100657237-d7a45b00-33b2-11eb-8f62-209a06320afd.png">

Step 2: Stash the remaining changes, and observe the indicator disappearing. Note the new stash, and the commits in the list highlighted with blue dots indicating they are unpushed.
<img width="549" alt="image" src="https://user-images.githubusercontent.com/70993406/100657832-3ff33c80-33b3-11eb-9137-c7eeb819d55c.png">

**Comment by ghost** [comment]
Note: The stash itself can sometimes disappear from the commit list entirely in this scenario.

**Comment by ghost** [comment]
On the topic of this indicator, as of version 2.1.1 (same OS) the indicator seems quite pushed up against the branch name. Should this be raised as a separate issue?

<img width="241" alt="image" src="https://user-images.githubusercontent.com/70993406/101291297-93aacd80-386c-11eb-81b2-ce4d90bd291c.png">

**Comment by DanPristupov** [comment]
> When choosing to commit some files and stash the rest, the push indicator on the left side column disappears when the remaining files are stashed. 

Thank you for the bug report. I fixed this.

> This issue has been around for a few versions now, perhaps since 1.0.98.

According to blame, since February 2020 ;).

> the indicator seems quite pushed up against the branch name. 

I just checked, both labels are on the same baseline.
