### ISSUE TITLE
can not fetch repo list from GitLab

### ISSUE THREAD

**Issue by iugo** [ForkIssues/Tracker#1198]
GitLab token scopes have been selected all.

<img width="187" alt="截屏2020-12-01 下午4 54 45" src="https://user-images.githubusercontent.com/499364/100718123-ed873f80-33f5-11eb-9d03-f021bd22b2f2.png">

**Comment by DanPristupov** [comment]
Do you use gitlab.com or a private server?

**Comment by iugo** [comment]
> gitlab.com

gitlab.com

**Comment by DanPristupov** [comment]
I just tried to login GitLab and then opened the clone dialog. The list of repositories was loaded properly (it took a bit long though).

Can you check if the log file contains any errors: `~/Library/Logs/Fork.log`?

**Comment by iugo** [comment]
> I just tried to login GitLab and then opened the clone dialog. The list of repositories was loaded properly (it took a bit long though).
> 
> Can you check if the log file contains any errors: `~/Library/Logs/Fork.log`?

```
🔷> Fork Version: 2.1.2 Build: 2.1.2 PID: 580
🔷> XCGLogger Version: 7.0.1 - Level: Debug
🔷> XCGLogger writing log to: file:///Users/iugo/Library/Logs/Fork.log
🔷[AppDelegate.swift:112] applicationDidFinishLaunching(_:) > Application Update Channel: develop
🔷[AppDelegate.swift:113] applicationDidFinishLaunching(_:) > Git instance: system
🔷[RemoteServiceNotificationManager.swift:73] stop() > Stop checking GitHub notifications
🔷[RemoteServiceNotificationManager.swift:48] start() > Start checking GitHub notifications
🔷[RemoteServiceNotificationManager.swift:95] refresh(force:) > Refresh GitHub notifications...
🔷[GitServiceConnection.swift:55] restoreAuthenticationFromKeychain() > Restore gitlab.com API session: authenticated
◽️[CloneController.swift:307] repositoriesFetched(result:) > Fetching GitLab, page: 1. Received: 0 repos
◽️[CloneController.swift:311] repositoriesFetched(result:) > Fetching GitLab. Done.
◽️[CloneController.swift:307] repositoriesFetched(result:) > Fetching GitLab, page: 1. Received: 0 repos
◽️[CloneController.swift:311] repositoriesFetched(result:) > Fetching GitLab. Done.
```

**Comment by DanPristupov** [comment]
Does the problem still exist?

**Comment by iugo** [comment]
> Does the problem still exist?

Everything is working now, awesome.
