### ISSUE TITLE
Files added with --intent-to-add do not appear in Local Changes

### ISSUE THREAD

**Issue by benprisby** [ForkIssues/Tracker#1199]
This became apparent when using Qt Creator to add new files to Git (as I reported with https://bugreports.qt.io/browse/QTCREATORBUG-25019). Because `--intent-to-add` is used, the file(s) do not appear in Fork, which makes it possible to commit without including them (especially for larger commits), causing upstream issues. To fix this, I needed to go to the command line to manually stage the file to get it to appear within Fork.

There should likely be a notion in Fork via some UI indicator that a file is being "watched" by Git, but whose contents have not actually been staged.

**Comment by DanPristupov** [comment]
Hi. I will have a look at this.

**Comment by DanPristupov** [comment]
So, I made a build which does not ignore such files. Could you check if it works for you please?

https://cdn.fork.dev/prerelease/Fork-2.1.13.dmg

----

`--intent-to-add` is a strange option and I'm still not sure how it should be used properly. For example I couldn't find a way to discard such file without staging it:

```
$ ls > file.txt

$ git add --intent-to-add file.txt

$ git status
On branch 2.1.13
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory) # <-- git restore is proposed it discard the changed
	new file:   aa.txt

no changes added to commit (use "git add" and/or "git commit -a")

# try the restore command
$ git restore aa.txt 

# but it doesn't do anything
$git status
On branch 2.1.13
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	new file:   aa.txt

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by benprisby** [comment]
The 2.1.13 build worked great for me! I was able to see these files appear in the unstaged section of Local Changes, which is where I would expect them to be I suppose since their content is not actually staged. I agree with you; it does seem like a strange option, but I think this implementation is great so at least the files do not disappear from within Fork. Thanks!

**Comment by DanPristupov** [comment]
Thank you for the feedback 👍
I will make it part of the upcoming Fork 2.2 update then.
