### ISSUE TITLE
Show git console output after performing push/fetch.

### ISSUE THREAD

**Issue by DanPristupov** [ForkIssues/Tracker#12]

**Comment by jaredreich** [comment]
Note: *output* meaning console output

**Comment by DanPristupov** [comment]
@jaredreich thanks, I updated the title.

**Comment by jaredreich** [comment]
For reference, bitbucket does this when you push, then you can click "show output". There's also the style of Tower, where in the bottom left it displays each line of the console output, but if you can expand the "activity view" to a large window that contains past console output history.

**Comment by clounie** [comment]
The "Show Output" button is nice - clean by default, but commands + output there if you want them.

**Comment by DanPristupov** [comment]
Fork 1.0.67 has activity manager which shows git output for fetch/push/clone operations.

![2018-05-28 at 20 34](https://user-images.githubusercontent.com/618115/40626072-8c5c42b8-62b6-11e8-920b-f79008332278.png)

**Comment by ssbarnea** [comment]
I am afraid that this might not prove to be a good enough solution for those using git push hooks, where is high likely to need to see the output of the linting commands, in real time.
