### ISSUE TITLE
on mac fork application pops up unintentially

### ISSUE THREAD

**Issue by bwl21** [ForkIssues/Tracker#1200]
# Problem

When I have Fork running (which I always do) even in the background, it comes to front very often without intention. It appears to me that it happens whenever a file is crated or touched. This is really annoying.

**Comment by DanPristupov** [comment]
I guess the problem is in your environment. Try to remember when this started.

> It appears to me that it happens whenever a file is crated or touched.

Fork doesn't listen to file system. Do you have applications which do that?

**Comment by bwl21** [comment]
Ok, I will have a closer look to identify, when this happens. Maybe it was because I had Fork in the Finder toolbar

**Comment by bwl21** [comment]
Hi Dan, the issue is stil there, and I could not track it down. Nevertheless it is ok to close this issue. I will reopen it as soon as I find out more ...
