### ISSUE TITLE
Question: Using environment variables during pre-commit hook

### ISSUE THREAD

**Issue by cheziyi** [ForkIssues/Tracker#1201]
When my pre-commit hook requires an environment variable, in a terminal, I can perform `export MY_VAR=abc`
or have it in my `.bashrc`/`.zprofile`, before performing `git commit` to have my pre-commit hook use the variable.

In Fork, is there anyway to achieve this? I have `export MY_VAR=abc` in both `.bashrc`/`.zprofile`, and in both zsh and bash I am able to retrieve it, but in Fork it complains that it does not exist.

OS: macOS Big Sur v11.0.1
Fork: v2.0.2

**Comment by DanPristupov** [comment]
> In Fork, is there anyway to achieve this?

Run fork from CLI using `open -a Fork` command

You can find more details here: https://github.com/ForkIssues/Tracker/issues/430#issuecomment-429013890
