### ISSUE TITLE
Don't display "also delete remote branch" option when remote branch was already removed

### ISSUE THREAD

**Issue by seanparmelee** [ForkIssues/Tracker#1204]
A very minor, cosmetic feature request:

I'm often deleting local PR branches once the corresponding PR has been merged and I love that Fork shows a tiny warning icon over the branches that no longer have a remote tracking branch:

![image](https://user-images.githubusercontent.com/1933330/101061848-9187fc80-3556-11eb-8d7d-79b3834c1cc4.png)

but I was curious about the option for removing the remote branch that's displayed when deleting one of these local branches:

![image](https://user-images.githubusercontent.com/1933330/101062063-c85e1280-3556-11eb-9eaf-23d6a3f25f97.png)

if I select that option, a warning icon is displayed next to it, presumably because it's already been removed. Seems like this option could not be displayed at all instead?

**Comment by DanPristupov** [comment]
In Fork 2.1 this option is no longer enabled when you delete a branch with invalid remote tracking reference.

**Comment by seanparmelee** [comment]
Thanks @DanPristupov!
