### ISSUE TITLE
Toolbar resets to "Icon and Text" in version 2.1

### ISSUE THREAD

**Issue by pointum** [ForkIssues/Tracker#1207]
I had the toolbar set to "Icon Only" and the bug was the first thing I noticed. The option resets to "Icon and Text" on app relaunch or when I open new tabs.

See the video: https://www.youtube.com/watch?v=fs6xnIZWC9k
 
I've tried deleting toolbar settings from defaults with no effect.

**Comment by mikchmie** [comment]
Moreover the padding over the "Repository Status" view seems to shrink incorrectly, when the "Icon Only" option is selected (visible in the video above as well)

**Comment by pointum** [comment]
Thank you for the fix.
