### ISSUE TITLE
[Feature request] Option to hide individual remotes

### ISSUE THREAD

**Issue by flit** [ForkIssues/Tracker#1208]
The ability to hide all remotes is nice. But frequently I have remotes for a repo which are rarely used. Commits and branches from these remotes just get in the way unless I'm actively working with one of those remotes, but I can't hide all remotes because need to see commits from the remotes that _are_ used frequently.

A feature to hide individual remotes would solve this situation. A hide/show command should be available in the remote context menu. When a remote is hidden, the name in the sidebar should probably be grayed out.

**Comment by DanPristupov** [comment]
The ability to hide particular branches, folders or remotes was introduced in Fork 2.6
