### ISSUE TITLE
[Feature request] Option to hide individual branches

### ISSUE THREAD

**Issue by flit** [ForkIssues/Tracker#1209]
Similar to #1208, the ability to hide individual branches would be very helpful in making one's work in Fork a lot more streamlined.

The hide/show command should be present in the branch context menu. One should also be able to hide/show all the child branches of a "branch folder" (e.g., for a branch with slashes in the name) by opening a context menu on the folder.

Hiding of remotes (#1208) can be merged with this feature by simply treating a remote as a root branch folder.

When branches are hidden the name should be drawn grayed out. When all child branches in a branch folder (or remote) are hidden, the folder name (remote name) should be drawn grayed out.

**Comment by DanPristupov** [comment]
The ability to hide particular branches, folders or remotes was introduced in Fork 2.6
