### ISSUE TITLE
Hang and Crash subsequent launch on Window Resize on Big Sur.

### ISSUE THREAD

**Issue by kellyhuberty** [ForkIssues/Tracker#1210]
Here is a video of the repro steps (Going to add it, got some screenshots first need to compress the video). When you resize the window to an abnormal size the app will hang, and repeated attempts to launch will cause the app to hang. Force quitting and launching results in crashing. To resolve I ended up removing the `NSWindow Frame ForkWindow` key in `~/Library/Preferences/com.DanPristupov.Fork.plist`. (If I relaunch it enough macOS sees something when awal and puts up that crash dialog and actually removes that item in the plist for me.) 

Thank you for taking a look. Love the app. Use it daily.

![Screen Shot 2020-12-05 at 10 26 10 AM](https://user-images.githubusercontent.com/1676539/101254986-8367e680-36e4-11eb-9ad8-e95b05e71553.png)

![Screen Shot 2020-12-05 at 10 20 30 AM](https://user-images.githubusercontent.com/1676539/101253927-3552e300-36e4-11eb-9a3e-ee9173bc96f8.png)

**Comment by kellyhuberty** [comment]
Here's a zip containing a view of Reproducing the issue.

[Screen Recording 2020-12-05 at 10.15.56 AM.mp4.zip](https://github.com/fork-dev/Tracker/files/5648039/Screen.Recording.2020-12-05.at.10.15.56.AM.mp4.zip)

**Comment by DanPristupov** [comment]
Thank you very much for reporting this ❤️. I'm releasing a hotfix.
