### ISSUE TITLE
Ability to move History window (nice-to-have)

### ISSUE THREAD

**Issue by dkadrios** [ForkIssues/Tracker#1211]
It's not possible to drag the child window around when viewing the history of a file.  In order to view both Fork and say a code editor, side-by-side, one needs to premeditatedly move the main Fork window aside before opening the history.  It sure would be handy if you could drag it after the fact.

If popup windows are not being kept in a separate Electron process and therefore appear within the main window, making it hard to implement moving them, then perhaps allowing the main window to be moved when children are shown would suffice?

**Comment by DanPristupov** [comment]
We made the history window non-modal in Fork 2.27.
