### ISSUE TITLE
"Open in" toolbar icon is missing in "selector"

### ISSUE THREAD

**Issue by herrherrmann** [ForkIssues/Tracker#1212]
I wanted to customize my toolbar today and noticed that the "Open In" command doesn’t show any icon in the "selector" anymore (see below). However, once it’s moved to the toolbar (which is a bit finicky), the icon shows up and the button is working. ✌️ 

![Screenshot 2020-12-07 at 10 15 38](https://user-images.githubusercontent.com/6429568/101332196-441ccf80-3875-11eb-9281-0ed87421faef.png)

**Environment:**
- Fork versions 2.1.2 and 2.2.1
- macOS 10.15.7

**Comment by axiac** [comment]
It works as expected in Fork 2.1.1 under macOS 10.13

**Comment by DanPristupov** [comment]
The problem existed in Big Sur.

We fixed it in Fork 2.3
