### ISSUE TITLE
List of branches with truncated text

### ISSUE THREAD

**Issue by rafsouzap** [ForkIssues/Tracker#1215]
I'm using Fork Version 2.1.2 (which is the latest version apparently) on macOS Big Sur 11.0.1, and my list of branches, stashes, etc is truncated regardless of column size.

See the screenshot I've attached below:

<img width="539" alt="Screen Shot 2020-12-07 at 14 54 41" src="https://user-images.githubusercontent.com/2496520/101386660-4181a080-389c-11eb-8ca7-9351827baf6b.png">

**Comment by DanPristupov** [comment]
Thank you for the bug report. We will fix this in the next update.

**Comment by DanPristupov** [comment]
Fixed in 2.2. Please check for updates

**Comment by rafsouzap** [comment]
Thanks @DanPristupov! All right! 👍🏻
