### ISSUE TITLE
gitflow not working

### ISSUE THREAD

**Issue by devployment** [ForkIssues/Tracker#1220]
I try to create a new hotfix

![image](https://user-images.githubusercontent.com/7137845/101894588-ad1e8300-3ba6-11eb-8a0c-600fce7ec0ad.png)

After that I get the following error

![image](https://user-images.githubusercontent.com/7137845/101894605-b576be00-3ba6-11eb-9625-4664e79bafe7.png)

```
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 158: _flags_fatal: command not found
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 1022: [: -ne: unary operator expected
flags:WARN /Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 739: /Applications/Sourcetree.app/Contents/Resources/bin/getopt: No such file or directory
flags:FATAL unable to parse provided options with getopt.
```

The weird thing is that I did not initialize gitflow within Fork. It was most likely initialized through GitKraken. 

Sourcetree was eventually installed quite some time ago on the machine as well. No idea what role `Sourcetree.app` plays here now. 

Any advice?

**Comment by DanPristupov** [comment]
Hi.

https://github.com/fork-dev/Tracker/issues?q=is%3Aissue+gitflow+is%3Aclosed

https://github.com/fork-dev/Tracker/issues/541#issuecomment-466292419

**Comment by devployment** [comment]
What did I search for?  Sorry, my bad.

**Comment by DanPristupov** [comment]
Actually, I think we must recognize this error and point the user to the solution. We will implement this in Fork 2.3

**Comment by DanPristupov** [comment]
Starting from the 2.3 update Fork will recognize this error and show a link to the solution.
