### ISSUE TITLE
[Feature request] Search for text inside files in the file tree

### ISSUE THREAD

**Issue by aslr** [ForkIssues/Tracker#1225]
I am paid customer of Fork and indeed is one of the best git GUI clients. However, I truly miss a way to search for specific methods / functions or any specific text in files in the file tree, especially when checking their history. Sometimes this is needed to check when a specific feature was removed and needs to be reimplemented again in the same or another project.

**Comment by DanPristupov** [comment]
Hi,

You can try to use the search by diff on the sidebar, but it will show matches in **all** commits.

<img width="261" alt="Screenshot 2020-12-15 at 09 06 54" src="https://user-images.githubusercontent.com/618115/102187902-e3187b80-3eb4-11eb-894c-5a1828dfbf9a.png">

**Comment by aslr** [comment]
Thanks, that's what I was looking for. 👍 Sometimes it is difficult to find these workflows, because of a lack of a detailed help file. Anyway, thanks. I will close this feature request.
