### ISSUE TITLE
Contextual menu item for resolve does nothing when squashing

### ISSUE THREAD

**Issue by tgunr** [ForkIssues/Tracker#1232]
V2.2.1 
Tried to resolve several files after merge by selecting them and using contextual menu for "Resolve using theirs". Nothing happens, had to select each one then use the resolve pane and click on "theirs" for each one, painful when you have dozens to resolve.

https://dsc.cloud/8e6a8d/1609161296.gif

**Comment by DanPristupov** [comment]
Please check if the log file contains any errors. It's located at `~/Library/Logs/Fork.log`.

**Comment by DanPristupov** [comment]
I reproduced the bug. The problem happens only on merge with the 'squash' option.

The fix will be available in the 2.3 update.
