### ISSUE TITLE
[Feature request] Configure page guide / break at page guide / line counter

### ISSUE THREAD

**Issue by mrclmh** [ForkIssues/Tracker#1233]
Hello,
first of all, thanks for this great git client!

My problem:
I have bad eyes and have a hard time seeing the page guide which I have set at column 72.
I have seen that you already made it more visible in https://github.com/fork-dev/Tracker/issues/632 but is seems this is unfortunately not visible enough for me.

I have three ideas for this:
1. Give an option the wrap the line while typing when reaching the page guide, so the current words starts in the next line.
2. Make the page guide configurable in its thickness.
3. Give an addition counter counting down so the counter is zero for the last character before the page guide and turning red and negative for characters beyond the page guide. (similar to the subject counter)

My favorite is the automatic line wrap but I would appreciate any solution for this problem.

**Comment by DanPristupov** [comment]
You can right click on commit description field and select `Wrap Paragraph at Ruler`. May be it can help with 1 and 3.

**Comment by mrclmh** [comment]
Nice. That solves the problem for me. So no new feature needed. I close this request.
