### ISSUE TITLE
Happy new year message appears on December 31

### ISSUE THREAD

**Issue by jespertheend** [ForkIssues/Tracker#1234]
I appreciate the message but it just wished me a happy 2020 hahah.
My local clock is set to December 31, 00:01. So it won't be a new year for 24 hours.
I'm on macOS.

**Comment by DanPristupov** [comment]
Yes, I made a mistake this year :(.

Thank you for reporting this bug. And Happy New Year 🎉

**Comment by kambala-decapitator** [comment]
Saw the message today, but it greeted me with 2019 :(

**Comment by kambala-decapitator** [comment]
just observed the same bug on another machine:

> it's 2020 somewhere...

> may 2019 bring you...
