### ISSUE TITLE
Happy New Year 🎉

### ISSUE THREAD

**Issue by DanPristupov** [ForkIssues/Tracker#1235]
Happy new year!

Thank you for all the feature requests and bug reports 🎁😊

<img src="https://user-images.githubusercontent.com/618115/103410427-71eeee80-4b6b-11eb-83f3-8191af617ae7.png" width="600"/>

**Comment by iolla-net** [comment]
A very Happy New Year to you too! 😀

**Comment by svoop** [comment]
@DanPristupov Happy New Year to both of you as well! 

Fork displayed animated new year's wishes in the status bar as well, cool! However... if I remember correctly, it wished best of luck for 2020. Oh no, don't wanna repeat that particular one. :wink:

**Comment by kellertuer** [comment]
Happy new year and thanks for this nice software.
