### ISSUE TITLE
Pasting branch name in search doesn't work (used to work)

### ISSUE THREAD

**Issue by palaniraja** [ForkIssues/Tracker#1238]
Pasting a branchname in search doesn't filter the branchlist. Now,  it requires additional keystore, like add remove a char works.

It used to work in the past, I think it is broken in recent (±2 revisions)

Note: Mac App

**Comment by DanPristupov** [comment]
Do you mean this search field?

![image](https://user-images.githubusercontent.com/618115/103642023-dd153800-4f52-11eb-952c-836b2e408176.png)

It works properly on our computers.

**Comment by palaniraja** [comment]
Yes. instead of typing, try to paste  "newtest" in the above example. it will not filter just one, unless you go back and edit the search term like add space and remove

**Comment by DanPristupov** [comment]
Thank you for the clarification. I reproduced the problem.

**Comment by DanPristupov** [comment]
This bug must be fixed in Fork 2.3

**Comment by palaniraja** [comment]
Thank you, working as expected now
