### ISSUE TITLE
Tab switching order is incorrect after drag and drop

### ISSUE THREAD

**Issue by Niels-NTG** [ForkIssues/Tracker#124]
It seems like since version 1.0.57.6 the behaviour of tab switching using ctrl+tab/ctrl+shift+tab has changed to something found in many IDEs. For me this doesn't really work with Fork. For my work I constantly switch between at least 4 different submodule repos. The order of the tabs have become part of my muscle memory and the the new behaviour messes with this. I would like to have a checkbox to turn this behaviour on/off, where the off state is the traditional left-right navigation.

**Comment by DanPristupov** [comment]
Hi. It looks like I reproduced the problem. It appears after a tab reorder. I'm not sure if this problem existed previously.

As a workaround you can restart Fork, which should fix the issue.

**Comment by Niels-NTG** [comment]
Ah yes. It does fix the issue indeed. Thanks.

**Comment by DanPristupov** [comment]
I'll keep this issue open not forget to fix the bug.

**Comment by DanPristupov** [comment]
This is going to be fixed in next update and already available in 1.0.59.4 prerelease (https://github.com/ForkIssues/Tracker/issues/152)
