### ISSUE TITLE
Padding is off in repository settings on macOS 11

### ISSUE THREAD

**Issue by jonstodle** [ForkIssues/Tracker#1240]
The bottom padding inside the _General_ tab in the repository settings seems to be missing, giving a bit a lopsided look

![Screen Shot 2021-01-06 at 14 34 12](https://user-images.githubusercontent.com/1719761/103774265-9562df00-502c-11eb-8231-549c61192161.png)

**Comment by DanPristupov** [comment]
Fixed in Fork 2.3
