### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by OysterD3** [ForkIssues/Tracker#1242]
When **Create a new tab** on Big Sur, the client will be not responding

**Comment by DanPristupov** [comment]
Does this happen every time you open a new tab?

**Comment by OysterD3** [comment]
Previously it happened every time, the issue gone now.

**Comment by rohitranjan1991** [comment]
Its happening for me also ... And yes it happens every time. The App freezes when i try to open a new tab.

Version:
Fork 2.2 is currently the newest version available.
(You are currently running version 2.2.1.)
