### ISSUE TITLE
Location of Fork GIT instance MacOS 10.15

### ISSUE THREAD

**Issue by frameworker2019** [ForkIssues/Tracker#1243]
Hi,

where"s the fork git instance is located in macOS 10.15?
Cannot find them below ~Library.

**Comment by DanPristupov** [comment]
`/Applications/Fork.app/Contents/Resources/git-instance`

Why?

**Comment by frameworker2019** [comment]
It's about global user information. The commits will be signed by my name and the hostname of my machine. I want to get rid the machine name. So I thought that information stands by default in gitconfig.

In the preference dialog, GIT tab, the second line above "avatar" info is empty. Is that the reason the machine name comes into play?

Fork 2.0.4

**Comment by DanPristupov** [comment]
> It's about global user information

The global user information is not related to the installation path.

You can see all config values by running the following command in terminal: `git config --list --show-origin`

> In the preference dialog, GIT tab, the second line above "avatar" info is empty. Is that the reason the machine name comes into play?

Yes, I guess.

https://git-scm.com/docs/git-commit#_commit_information

> ... the information is taken from the configuration items `user.name` and `user.email`, or, if not present, the environment variable EMAIL, or, `if that is not set, system user name and the hostname used`...
