### ISSUE TITLE
History empty

### ISSUE THREAD

**Issue by ties-s** [ForkIssues/Tracker#1245]
"Show history" shows empty panel for some files.

<img width="2048" alt="Screenshot 2021-01-08 om 17 42 44" src="https://user-images.githubusercontent.com/9462286/104041361-34c4d500-51d9-11eb-9ec9-d83bfbe202b1.png">

**Comment by DanPristupov** [comment]
Please check if the log file (`~/Library/Logs/Fork.log`) contains any errors

Does `git log -- /path/to/file` show any changes?
