### ISSUE TITLE
Fork constantly asks me to set up my git identity

### ISSUE THREAD

**Issue by mtschoen-unity** [ForkIssues/Tracker#1246]
This just started happening today; whenever I try to commit something, I see the following error message:
```
$ git commit --file=/var/folders/1p/4nbs872n4734svxpx96vyh0m0000gp/T/E553BA37-4CF6-41F2-8C7D-ECF723F15623


*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <>) not allowed

```

If I set up my identity under `Preferences... > Git` it will let me commit but then the next time I try I see the same error.

**Comment by DanPristupov** [comment]
> This just started happening today

Did you install anything today?

Open a command line and run: `git config --global user.email`. It will show your email. Then run it again in 30 minutes. If the email gets erased, try to remember what you used during this time period.

**Comment by schwa** [comment]
I'm about to file this as a new issue - but I notice that Fork isn't correctly picking up my email and user name from my git config. For logistical reasons I keep my git user configuration in its own file and import that into the main git config file via

```
[include]
path = user
```

And the user file contains the actual [user] email/name config.

git config user.name & git config user.email work perfectly. But fork seems to read the settings directly from the config file without including the user directory.

**Comment by mtschoen-unity** [comment]
It must have been an XCode update or something which messed up my global git config. It was also broken in command line. I've reset it from the command line and now things seem to be fine now.

One thing which was confusing to me: if I go to `Fork > Preferences > Git`, and enter my e-mail/name, it would work in Fork but then later on it would be reset back to blank. Is that UI supposed to update the git config or am I meant to fix this in command line if it happens?

**Comment by DanPristupov** [comment]
> if I go to `Fork > Preferences > Git` ...  Is that UI supposed to update the git config

Yes, this UI changes `git config --global user.name` and `git config --global user.email`. There must be some other application that erases them (IDE, another git client, or hook).

**Comment by mtschoen-unity** [comment]
Yeah no reinstalls or anything and after restarting my computer this morning the config is cleared out again. I'll have to investigate what's going on here, but it doesn't seem to be Fork.

**Comment by mtschoen-unity** [comment]
Ah! It was Atom! For some reason, switching to a file can end up causing some plugin (or something) to clear your git config. I'll be bringing this over to their issue tracker :)
