### ISSUE TITLE
"Merge Without Commit" option is missing on macOS

### ISSUE THREAD

**Issue by mcx808** [ForkIssues/Tracker#1247]
Fork 2.2 on macOS 11.1
Fork 1.57.1.0 on Windows 10 20H2

![Screenshot 2021-01-12 122911](https://user-images.githubusercontent.com/30801293/104314882-f7f72780-54d1-11eb-9a7b-04ebfdccef47.png)
<img width="526" alt="Screenshot 2021-01-12 at 12 31 16" src="https://user-images.githubusercontent.com/30801293/104315143-6805ad80-54d2-11eb-948c-fb4c1a1f881a.png">

The Merge Option: Don't commit is missing on macOS. I have tried to leave 'Always create a merge commit' unticked but the merge immediately stages and commits all files.

**Comment by Andrew-Au** [comment]
Related: sometimes I want to change the default commit message for a merge.  Fork for Mac doesn't provide a way to do this.

The workaround is to do a 'git merge --no-commit <source>' on the command line, and then 'resolve' the merge in Fork.  But it would be much better if I could just do a 'no-commit' merge directly in Fork.

**Comment by DanPristupov** [comment]
We added this option in 2.4

**Comment by mcx808** [comment]
Just updated to 2.4. I can confirm it works as expected.
