### ISSUE TITLE
Fork doesn't read user name/email from correct config file

### ISSUE THREAD

**Issue by schwa** [ForkIssues/Tracker#1248]
Fork isn't correctly picking up my email and user name from my git config. For logistical reasons I keep my git user configuration in its own file and import that into the main git config file via

```
[include]
path = user
```

And the user file contains the actual [user] email/name config.

git config user.name & git config user.email work perfectly. But fork seems to read the settings directly from the config file without including the user directory.

**Comment by DanPristupov** [comment]
I added to `.gitconfig` the following:

```
[include]
	path = /Users/dan/userconfig
```

Then created `userconfig`:

```
[user]
	name = Dan Pristupov
	email = test@test.com
```

Opened Fork, made a commit.

Everything seems to be correct:

<img width="251" alt="Screenshot 2021-01-18 at 15 23 19" src="https://user-images.githubusercontent.com/618115/104926956-1ad97e00-59a1-11eb-800d-c4c64ce1ef1e.png">

**Comment by schwa** [comment]
<img width="662" alt="Screen Shot 2021-01-18 at 12 58 53 PM" src="https://user-images.githubusercontent.com/20267/104962279-f5427980-598c-11eb-96ba-2bbede813124.png">

My gitconfig is in ~/.config/git/config and that loads ~/.config/git/user (which is symlinked to another file in ~/config/git/)

**Comment by schwa** [comment]
Commits work as expected however.

**Comment by DanPristupov** [comment]
This view shows (and allows to edit) **--global** user information.

> My gitconfig is in ~/.config/git/config and that loads ~/.config/git/user (which is symlinked to another file in ~/config/git/)

This is fine, but the location of the settings not considered as '--global' anymore. You can check that yourself by running 'git config --global user.name' in Terminal.

> But fork seems to read the settings directly from the config file without including the user directory.

No, Fork reads those settings from git.

**Comment by schwa** [comment]
Sure I understand. It's not a high priority bug - but it would be great if the prefs showed what was actually used when committing (although per repo configs would make that more complex). I get that everyone can potentially have a more complex configuration than typical users would but it would be nice if the UI was improved a little to accommodate more complex situations.

**Comment by Stanzilla** [comment]
I use a few `[includeIf "gitdir:~/projects/work/"]` in my config and it works fine on the terminal but not in Fork. When using SSH for authentication, I get the generic

```
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


In a case you entered incorrect password, please
update it in Keychain Access application.
```

error because it doesn't use the correct SSH key.

Related https://github.com/fork-dev/Tracker/issues/1063 https://github.com/fork-dev/Tracker/issues/674

Test Setup:

`.gitconfig`

```ini
[user]
	name = John Doe
	email = me@private.com
	signingkey = xxx

[includeIf "gitdir:~/projects/work/"]
	path = ~/.gitconfig-work

[includeIf "gitdir:~/projects/personal/"]
	path = ~/.gitconfig-personal
```

`.gitconfig-work`

```ini
[user]
	name = John Doe
	email = me@work.com
	signingkey = xxx

[core]
	sshCommand = "ssh -i ~/.ssh/id_rsa_work"

```

`.gitconfig-personal`

```ini
[user]
	name = John Doe
	email = me@private.com
	signingkey = xxx

[core]
	sshCommand = "ssh -i ~/.ssh/id_rsa_personal"

```

**Comment by DanPristupov** [comment]
Everything works for me again. At least for the author name.

`~/.gitconfig`

```ini
...
[includeIf "gitdir:~/Sources/samples/"]
	path = ~/userconfig
[includeIf "gitdir:~/Sources/git/"]
	path = ~/userconfiggit

```

`~/userconfig`

```ini
[user]
	name = Samples
	email = test@test.com
```

`~/userconfiggit`

```ini
[user]
	name = git
	email = test@test.com
```

When I commit in a repo in `~/Sources/samples/*` the author is "Samples", when I commit in a repo in `~/Sources/git/*` the author is git.

**Comment by DanPristupov** [comment]
@Stanzilla 

> error because it doesn't use the correct SSH key.

Why are you sure? It could be that Fork doesn't have access to the SSH passphrase in KeyChain Access.

**Comment by Stanzilla** [comment]
@DanPristupov okay that could also be the case, how do I test/fix that? Since it works from the terminal I'm not sure. Also could be the use of different sshCommands?

**Comment by persimmonsoft** [comment]
I also have this problem with git config include files as well, for the simple case of a straight include.
Fork version 2.4

~/.gitconfg
```
[user]
	name = Dave Smith
	email = dave@home.com
...
[include]
	path = ~/.gitconfig_local
```

~/.gitconfig_local
```
[user]
	name = Dave Smith (work)
	email = dave@work.com
```

In the terminal
```
> git config user.email
daves@work.com

> git config user.name
Dave Smith (work)
```

When I check Fork in the Preferences -> Git, I see:
Name as
Dave Smith
Email as
daves@home.com

I am not sure how my setup is different than yours Dan, but it definitely does not work for me.

**Comment by DanPristupov** [comment]
@persimmonsoft https://github.com/fork-dev/Tracker/issues/1248#issuecomment-763472922

> When I check Fork in the Preferences -> Git

This view shows `--global` values

> I am not sure how my setup is different than yours Dan, but it definitely does not work for me.

It must work if you try to commit.

**Comment by persimmonsoft** [comment]
Thanks for the explanation Dan.
I am surprised the git `--global` ignores the include in the config. I did not expect that.

I tried this
`git config --global --includes user.email`
and that produced the expected results of: dave@work.com
Hmm

**Comment by persimmonsoft** [comment]
Dan, I did verify your comment about committing.
I ended up with dave@work.com as the committer, so that is most of my concern.
Would it be possible to have the UI use the --includes to be consistent through?

Thanks

**Comment by Stanzilla** [comment]
It seems to work correctly now, apart from the Settings view. that will always ignore includes
