### ISSUE TITLE
Blame list is offset by half a line

### ISSUE THREAD

**Issue by jespertheend** [ForkIssues/Tracker#1251]
It's hard to tell wich line belongs to which commit.
My files always end with an empty new line, not sure if that's related.

![image](https://user-images.githubusercontent.com/2737650/105332588-13021f80-5bd5-11eb-9844-b182ac9e237e.png)

**Comment by DanPristupov** [comment]
Most likely the custom font size is related :)

**Comment by DanPristupov** [comment]
No, custom font size is handled properly.

Does this happen with any file?

**Comment by jespertheend** [comment]
Seems like it, I can't find any file where it doesn't happen.

This file doesn't end with a new line and it happens here as well:
![image](https://user-images.githubusercontent.com/2737650/105343802-62028180-5be2-11eb-8540-4a050f453df1.png)

**Comment by DanPristupov** [comment]
I see now. You are using Big Sur which adds offsets to the commit list.

**Comment by DanPristupov** [comment]
The issue must be fixed in Fork 2.3 which is just released.

**Comment by jespertheend** [comment]
It seems to crash now when I open the blame window 😔

**Comment by jespertheend** [comment]
Oh wait, it seems to be fixed 😄 
It crashed because I did blame on an unstaged 74MB lfs file, all text files do work perfectly.
