### ISSUE TITLE
"Stage" Button Should Be "Stage All" Button

### ISSUE THREAD

**Issue by bdkjones** [ForkIssues/Tracker#1252]
I'm a Mac developer moving to Fork from Tower. I'm well aware of the "who moved my cheese!?" phenomenon, but there is some friction in Fork's UX that I think is worth addressing. Please see the text in this screenshot:

![Screen Shot 2021-01-22 at 01 00 29](https://user-images.githubusercontent.com/926566/105470569-92800500-5c4e-11eb-9ba3-66d6add24c8f.png)

Thanks for the great app! I'm VERY happy to send Tower and their subscription nonsense directly to hell.

**Comment by DanPristupov** [comment]
> This should be "Stage All" ... that's what users want to do.

No, it should not. Changes are supposed to be reviewed before you stage them. That is the point of the stage area after all.

However, you can hold the `option` key to stage all:

![ezgif com-video-to-gif-4](https://user-images.githubusercontent.com/618115/105472851-b23e1a00-5c9c-11eb-8630-b779d7f567d1.gif)

**Comment by DanPristupov** [comment]
Regarding the second part:

> (`Stage All`) menu item should be removed <because> it belongs above the entire outline view

An item that affects the entire outline view is a common practice, I think. E.g. If Finder in the file context menu we can see 'Use Groups', 'Sort By',

**Comment by bdkjones** [comment]
The option key will work; thanks for that! I would still suggest that the button should default to "stage all", but maybe that's because all the other Git clients I've used have been that way. 

As for reviewing before staging: absolutely, if I didn't write the code. I'm a one-man team, so I can luxuriously stage everything at once because I know what's in it; I wrote it. Makes the Blame function fun, too.

**Comment by bdkjones** [comment]
Regarding the Finder's contextual menus: notice that you get different menuItems when you right-click empty space and when you right-click a file/folder. When you right-click a file/folder, the "Use Groups", "Sort By" and other items unrelated to the clicked row disappear.

**Comment by bdkjones** [comment]
Ah, the Option key trick has a drawback: the button is still not available until something in the list is selected. At that point, it's easier to just right-click something random and use the "stage all" menu item. That still feels backwards, but I gather the change isn't desired.

Maybe once the Option key goes down, you could enable the "Stage All" button even if no items are selected?

**Comment by DanPristupov** [comment]
Actually, I forgot that there is the 'Stage All' button on the small toolbar above the 'Stage' button

<img width="277" alt="Screenshot 2021-01-28 at 15 13 38" src="https://user-images.githubusercontent.com/618115/106150227-68ad6d80-617b-11eb-85b3-c74cb834e489.png">

**Comment by bdkjones** [comment]
Well, that solves this right up! Perfect.
