### ISSUE TITLE
[Feature] Show Finder tags in repo list

### ISSUE THREAD

**Issue by svoop** [ForkIssues/Tracker#1253]
This is very low prio, but would be useful nonetheless:

I'm having a lot of repos in the list, some of which share characteristics. Grouping is already very useful and I use it extensively to group by client/project. But some characteristics such as e.g. "deployment via GitLab CI" are spanning across these groups.

I tag the client/project folders accordingly in the finder, how about showing these finder tags in the repo list? Here's a mockup which shows the tag blob and – on mouse over – a tooltip with the tag name:

![tags](https://user-images.githubusercontent.com/7255/105470930-773ae700-5c9a-11eb-83f6-435f53b75ec7.jpg)

**Comment by svoop** [comment]
@DanPristupov Wow, thanks so much for adding the finder colors! The mileage of others may vary, but it makes my day so much easier navigating the repos and finally, these finder colors are useful for a change. Very cool!

**Comment by DanPristupov** [comment]
You are welcome and thank you very much for the feature request 👍

**Comment by svoop** [comment]
@DanPristupov Let me reopen this, not sure whether it's intentional though: When assigning more than one tag in Finder, only one (the one higher up in the tag list it appears) is shown in Fork. Would be cool to see all if that's not too complicated and therefore intentionally limited to one.

**Comment by svoop** [comment]
Even though multiple tags would be nice, one should work for most users, closing again.
