### ISSUE TITLE
Pressing Tab in Commit subject text field should move focus to Description field

### ISSUE THREAD

**Issue by ole** [ForkIssues/Tracker#1255]
Fork 2.2.1
macOS 11.1

When the keyboard focus is in the "Commit subject" text field and I press the Tab key, I expect the keyboard focus to move to the "Description" text field, but it doesn't.

(I know I can press Return to move to the Description field, but my muscle memory isn't wired like that. I always press Tab.)

**Comment by DanPristupov** [comment]
This looks like a bug in macOS. Try to restart the computer.

**Comment by ole** [comment]
@DanPristupov Thanks. You're right, I can't reproduce this at the moment. I'm still wondering if something Fork-specific is going on here because I have definitely seen this exact issue in Fork many times over weeks/months and I'm not aware of similar issues with other apps on my computer. But I'm gonna close this for now. Thanks again for the suggestion.
