### ISSUE TITLE
[feature request] show git command when use tool

### ISSUE THREAD

**Issue by tbm98** [ForkIssues/Tracker#1259]
I want to know in the behind of scene where tool use git tool to do.
if I can see it so I will learn more about git :D

**Comment by DanPristupov** [comment]
<img width="723" alt="Screenshot 2021-01-26 at 08 03 26" src="https://user-images.githubusercontent.com/618115/105811485-0272f000-5fad-11eb-9292-285050f0f59a.png">

**Comment by tbm98** [comment]
yes. Thank you :D
