### ISSUE TITLE
Toolbar resets to "Icon only" in version 2.3

### ISSUE THREAD

**Issue by thijskramer** [ForkIssues/Tracker#1260]
When I configure Fork to show both Icon and Text in the toolbar, and close and reopen fork, the text labels are gone and the 'Icon only' option is selected again.

This seems very similar to #1207, but just the other way around. 

I'm using MacOS Big Sur.

**Comment by DanPristupov** [comment]
Thank you very much for reporting this 👍.

I've already released a hotfix (Fork 2.3.2). Please check for updates (`File -> Check for updates...`)

**Comment by thijskramer** [comment]
Thanks for the hotfix! It works again!
