### ISSUE TITLE
[Feature] Show diff in .strings files

### ISSUE THREAD

**Issue by luvacu** [ForkIssues/Tracker#1264]
On iOS development we use `.strings` files with the translations/copies. It would be useful to be able to check the differences in those files in Fork when making a change. Currently this is how the diff is displayed:

![diff-strings-files](https://user-images.githubusercontent.com/1182855/106154353-cb086d00-617f-11eb-809f-7faf0b561cca.png)

**Comment by DanPristupov** [comment]
Try to add `*.strings       text` to the `.gitattributes` file in the root of your repository.
You can find more info there: https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes

**Comment by luvacu** [comment]
Thanks, it works in Fork! However, GitHub does not display the differences line-by-line in pull requests, but that's another issue. Thank you again @DanPristupov
