### ISSUE TITLE
Spaces missing in repository git action log

### ISSUE THREAD

**Issue by bartvanandel** [ForkIssues/Tracker#1266]
When clicking the title of the currently open repository, an action log is displayed (e.g. containing git fetches). Looks like some spaces have gone missing, the command should say `git stash save --message ...`, but looks like this instead:

![image](https://user-images.githubusercontent.com/1194804/106276305-b091ca80-6237-11eb-94a4-68c513efeaf8.png)

**Comment by DanPristupov** [comment]
I think it was fixed at some point.
