### ISSUE TITLE
How to open fork from terminal in mac?

### ISSUE THREAD

**Issue by SilkageNet** [ForkIssues/Tracker#1270]
How to open fork from terminal in mac?

**Comment by DanPristupov** [comment]
Open Fork preferences -> Intergration and install Fork CLI tools.
Then use the `fork` command in the terminal

**Comment by relikd** [comment]
@SilkageNet If it is just opening Fork you are concerned about (and not a specific repo), you can also use `open -a Fork`

**Comment by DanPristupov** [comment]
`open -a Fork .` to open the current directory.

**Comment by SilkageNet** [comment]
Thank you
