### ISSUE TITLE
assertion failed?

### ISSUE THREAD

**Issue by aholla** [ForkIssues/Tracker#1278]
Hi I'm getting this when trying to check out a repo from BitBucket

assertion failed [abi_info.kind == AbiKind::TranslatedCode]: emulated forward to an arm pc that isn't in translated code. arm_pc=0x1053484d8 abi_kind=6 emulation_interval=[0x1058bdc3c,0x1058bdc64) instruction_interval=[0x1058bdc2c, 0x1058bdc64) x86_rip=0x415cffb

I'm on a new MacMini M1

**Comment by DanPristupov** [comment]
Did you install XCode or Rosetta already?

Can you try this build, please: https://cdn.fork.dev/prerelease/Fork-2.3.11.dmg?

**Comment by aholla** [comment]
Yep, that seems to have fixed it! Thanks!
