### ISSUE TITLE
Checkout issue. (M1?)

### ISSUE THREAD

**Issue by aholla** [ForkIssues/Tracker#1279]
Another issue when checking out a new repo.

assertion failed [*ret_index + 2 == num_insts]: RET should be second last instruction in translation

On an Mac Mini M1. Build: 2.3.11

**Comment by DanPristupov** [comment]
> Another issue when checking out a new repo.

Do you mean clone?

**Comment by aholla** [comment]
Yes, sorry, cloning a new repo!

It worked the second time though :)

**Comment by DanPristupov** [comment]
We can probably close that.
