### ISSUE TITLE
[Feature] - Favorites Group & Reordering

### ISSUE THREAD

**Issue by bdkjones** [ForkIssues/Tracker#1281]
Two straightforward requests for the left-hand sidebar. Please see the screenshot.

Note: Fork is excellent; my comments aren't meant to imply otherwise.

<img width="1090" alt="Screen Shot 2021-02-11 at 19 17 54" src="https://user-images.githubusercontent.com/926566/107726769-a68fb300-6c9e-11eb-8848-2b8fd36214eb.png">

**Comment by DanPristupov** [comment]
The 'Repositories' section allows modifications. So you can create a `.favorites` folder and put the most important repos there.

I don't see much use in a separate favorites section because `Cmd+P` allows to quickly navigate to any repo without opening the new tab.

**Comment by bdkjones** [comment]
Is the 'Repositories' section not a disk listing? I see my local folder structure when I expand that section; if I move repos around in that section is it going to move them on disk?

I mean...I already have to memorize keyboard shortcuts for Xcode, Final Cut Pro, Sketch, Photoshop....if I were a keyboard-driven Git user, I'd just use the Terminal. I'll just stop asking for features, I guess. Thanks anyway.

**Comment by DanPristupov** [comment]
> Is the 'Repositories' section not a disk listing?

No. It imports the structure from the file system but is absolutely independent. You can reorganize it and rename the repos if needed.

**Comment by bdkjones** [comment]
Ah, good to know. Now if I could only put it at the top!
