### ISSUE TITLE
Stash tag disappear from the GUI when rebasing a branch

### ISSUE THREAD

**Issue by Mryb68** [ForkIssues/Tracker#1283]
I stashed some code on my branch. The stash tag was above my last commit, as usual. But then when I tried to rebase my branch on another branch, my stash disappeared from de GUI (fortunately I could still recover it with a 'git stash pop' ).

**Comment by DanPristupov** [comment]
Rebase recreates the commit tree and the old one (with stash) becomes invisible.

You can still see all stashes on the sidebar.
