### ISSUE TITLE
Merge in External Tool does not work on M1?

### ISSUE THREAD

**Issue by abra-code** [ForkIssues/Tracker#1284]
I have Fork 2.3.2 on a couple of machines. On my M1 Mac mini "Merge in External Tool" fails silently. I have "File Merge" selected. There is no error message shown. I also tried changing "External Diff Tool" in preferences to /usr/local/bin/bbdiff and it also fails silently. I am trying to resolve a conflict in a rather large Xcode project and internal Fork merge window is not good enough - I can't edit a large diff chunk

**Comment by DanPristupov** [comment]
Can you run File Merge manually?

Is Command Line Tools selected in XCode preference?

<img width="829" alt="Screenshot 2021-02-16 at 14 44 25" src="https://user-images.githubusercontent.com/618115/108070995-7876ee00-7065-11eb-9c06-0cc6a0d2db7b.png">

**Comment by abra-code** [comment]
FileMerge runs fine and the Locations in Xcode prefs are the same as in your screenshot.

**Comment by DanPristupov** [comment]
Could you check if there's any error or warning in `~/Library/Logs/Fork.log`?

**Comment by abra-code** [comment]
When I choose "External Diff" from contextual menu on some changed file, the log shows:
🔷[MergeTool.swift:135] diff(remote:local:) > Diff using 'custom(path: "/usr/local/bin/bbdiff", arguments: ["$LOCAL", "$REMOTE"])'.
◽️[MergeTool.swift:323] activeTool(merge:) > Looking for a merge tool: 'custom(path: "/usr/local/bin/bbdiff", arguments: ["$LOCAL", "$REMOTE"])'

No error but nothing happens

**Comment by abra-code** [comment]
The merge resolution started working again when using FileMerge as external tool after updating to v. 2.4.
"External Diff" from contextual menu still does nothing and silently fails
