### ISSUE TITLE
Tags are not deleted

### ISSUE THREAD

**Issue by antonm76** [ForkIssues/Tracker#1289]
It looks like Fork has an issue deleting tags on Bitbucket (not sure for other servers).
- I tried to delete a tag with `Delete tag from remote repositories` flag checked. Tag disappears but on next fetch appears again.
- Next I tried to delete it locally and unchecked `Fetch all tags` option on the Fetch dialog, but it again appears after fetch.
Maybe I do not understand it but it looks like an issue.

**Comment by DanPristupov** [comment]
1. Check output of the delete tag and fetch commands in Fork.

2. Is it possible that the tag is pushed by somebody else? For example, somebody in the team may have 'push all tags' option enabled.

**Comment by antonm76** [comment]
Hm, outputs look good and tags haven't reappeared this time so your latter assumption may be truth.

**Comment by DanPristupov** [comment]
It's very difficult to completely delete a tag in git if you work in a team. It's by design.
You need to delete the tag remotely. Then **everybody** must fetch --prune.
So, we ourselves only use tags for versioning.
