### ISSUE TITLE
Add keyboard shortcut for "Save Stash…"

### ISSUE THREAD

**Issue by herrherrmann** [ForkIssues/Tracker#129]
I'd love to access the Stash feature via a keyboard shortcut (`CMD+Shift+S`?) just like the other common actions (fetch, pull, push).

**Comment by DanPristupov** [comment]
Nice idea. `Cmd+Shift+S` is currently used by stage/unstage. So there are two ways:
- Find another shortcut for SaveStash.
- Stop using  `Cmd+Shift+S` for stage/unstage (we have `Enter` shortcut for them anyway) and use it for stash. This will take few months to migrate people nicely.

**Comment by DanPristupov** [comment]
Or, we can use `Cmd+Shift+S` for stash. But for people who used it for staging, show in stash window a hint like `Missing the Stage shortcut? Please use the Enter key instead.` Hopefully people won't be as mad as previously when I stole the 'Spacebar' shortcut ;).

P.S. Actually, I use stash a lot during my work day. I probably should improve it's usability.

**Comment by herrherrmann** [comment]
Oh, you're totally right! I'd also prefer to keep `CMD+Shift+S` for staging files/lines actually (because I wanna keep my left hand resting on the left side of the keyboard instead of "reaching over" to the enter key).
So maybe it should simply be another shortcut then for stashing, like `CMD+Shift+X`?

**Comment by DanPristupov** [comment]
Yes, after an hour of thinking I realized that I do use `Cmd+Shift+S`, my left hand is always on the `cmd+shift` combination.

`Cmd+Shift+X` is strange. It could be tricky to remember because`X` has no relations to stash.

Another ideas:

May be `Cmd+Shift+H`? It has a common letter at least.
Or: `Cmd+Shift+↓` for stash, and `Cmd+Shift+↑` for unstash last.

**Comment by clounie** [comment]
+1 for not changing `Cmd+Shift+S` - and for up/down arrows. That seems pretty intuitive.

**Comment by DanPristupov** [comment]
OK, here's the plan:
- Click on the stash icon on toolbar (or `Cmd+Shift+H`) will open the 'Create stash' dialog
- `Alt`-Click on the stash icon (or `Cmd+Alt+Shift+H`) will stash the changes without prompting

The stash icon will also contain a drop-down segment which will show a list of recent stashes.
- Click on an item will raise the 'Apply Stash' dialog
- `Alt`-Click on an item will apply the stash without prompting

![2017-10-15 at 11 55](https://user-images.githubusercontent.com/618115/31583659-d703c2f0-b19f-11e7-8f78-da7b8197756c.gif)

This is going to appear in the next release (as well as GPG support).

**Comment by herrherrmann** [comment]
Hey, awesome solution! That'll make it even faster than I hoped for so far. :)

**Comment by DanPristupov** [comment]
Just released Fork 1.0.58 with the stash improvements we discussed here.
