### ISSUE TITLE
No longer using user ssh config

### ISSUE THREAD

**Issue by flit** [ForkIssues/Tracker#1293]
Fork 2.4.2 appears to no longer use the user's `~/.ssh/config`.

I have a number of Host configurations in my config file that are required to get to some of the git servers I use. Previous versions of Fork were able to access the servers by using the user ssh config, but this no longer works in 2.4.2. The only workaround is to fetch and push from the command line.

**Comment by DanPristupov** [comment]
Hi. Open SSH Configuration (Fork -> SSH Configuration) and uncheck all SSH keys to make Fork use the default system configuration.

**Comment by flit** [comment]
Thanks! Adding a note in the SSH Configuration dialog would be helpful. (I did look there.)

It's also not clear to me what the best default behaviour is. I guess Ideally you could parse `~/.ssh/config`, and if it has configuration settings then default to using the system configuration.
