### ISSUE TITLE
Switching github account by ssh hostname does not work.

### ISSUE THREAD

**Issue by jakelizzI** [ForkIssues/Tracker#1294]
First of all, I'm not good at English. So, I'm sorry if I'm wrong.

I use to switch github account by ssh hostname.

For example,

```
~/.ssh/config

Host github_primary
    User git
    Port 22
    HostName github.com
    IdentityFile ~/.ssh/github_primary_id_rsa
    TCPKeepAlive yes
    IdentitiesOnly yes

Host github_secondary
    User git
    Port 22
    HostName github.com
    IdentityFile ~/.ssh/github_secondary_id_rsa
    TCPKeepAlive yes
    IdentitiesOnly yes
```

and git remote url is

- `github_primary:hoge/fuga`
- `github_secondary:piyo/piyo`

Version 2.3 worked, but 2.4 does not work.
The error is as follows.

```
ssh: Could not resolve hostname github_primary: nodename nor servname provided, or not known.
fatal: Could not read from remote repository.

etc...
```

Is this a bug?

What can I do?

Thanks.

**Comment by DanPristupov** [comment]
Open SSH Configuration (Fork -> SSH Configuration) and uncheck all SSH keys to make Fork use the default system configuration.

https://github.com/fork-dev/Tracker/issues/1293#issuecomment-785391965

**Comment by jakelizzI** [comment]
Oh! There is already same issue. Please excuse me.

So, I close this issue.

**Comment by DanPristupov** [comment]
No problem :)
