### ISSUE TITLE
[Feature Request] Clobber local tags on fetch

### ISSUE THREAD

**Issue by ashtonmeuser** [ForkIssues/Tracker#1295]
When working on a repo where tags are updated often, I am presented with `(would clobber existing tag)`. To fetch all remote branches and tags, I need to delete the conflicting tags locally and fetch again. It would be great to have a "Clobber Local Tags" option on fetch.

**Comment by DanPristupov** [comment]
When this error occurs, the error dialog has the option to force fetch.
<img width="682" alt="Screenshot 2021-02-25 at 22 23 15" src="https://user-images.githubusercontent.com/618115/109219614-1b431100-77b8-11eb-8814-b82a1a8a59ef.png">

**Comment by ashtonmeuser** [comment]
Can't believe I didn't notice that. Thanks for the speedy reply. Closing this issue.

**Comment by ashtonmeuser** [comment]
@DanPristupov I feel better about not seeing this option as it seems the button is missing entirely from my version. Using macOS 11.2.1, Fork 2.4.2, Git 2.27.0 (Fork instance).
<img width="755" alt="Screen Shot 2021-02-25 at 1 53 10 PM" src="https://user-images.githubusercontent.com/7253863/109230874-6f2f0500-777a-11eb-8247-e302a5af527e.png">

**Comment by DanPristupov** [comment]
Weird 🤔
Can you reproduce the problem and send the Fork log file (~/Library/Logs/Fork.log) to my email (support@fork.dev), please?

**Comment by DanPristupov** [comment]
This problem was caused by the fact that you used the 'fetch all remotes' option. In this way Fork cannot recognize which particular remote the problem belongs to and fetching all remotes with the `--force` flag is dangerous.

**Comment by ashtonmeuser** [comment]
Ah, you're right! Thanks for the insight. Closing.
