### ISSUE TITLE
Add Grammarly support

### ISSUE THREAD

**Issue by melo** [ForkIssues/Tracker#1296]
Hi,

I understand that Grammarly was made to work for the web context, but it would be useful to have it when writing commit descriptions.

https://www.grammarly.com

Not sure if Grammarly would be interested in this though :).

Thank you for your considerarion.

**Comment by DanPristupov** [comment]
> Not sure if Grammarly would be interested in this though :).

Looks like they don't:

https://support.grammarly.com/hc/en-us/articles/360046352591-Can-I-use-Grammarly-API-

> We do not offer a publicly available Grammarly API at this time.

**Comment by DanPristupov** [comment]
It looks like currently the API is not even planned.

https://twitter.com/Grammarly/status/1335967163702784002?s=20

> We currently do not have the Grammarly API on our active development roadmap
