### ISSUE TITLE
Branch renaming ignores case when comparing 

### ISSUE THREAD

**Issue by mrRedSun** [ForkIssues/Tracker#1297]
In MacOS app if I rename branch "DEV" to "dev" the app doesn't allow me to change the name so I have to rename branch to something else and then change the register. 

The app should allow to change the name of a brach if case changes

**Comment by DanPristupov** [comment]
> Branch renaming ignores case when comparing

Well, it works exactly the same way as git.

```
$ git branch -m test Test
fatal: A branch named 'Test' already exists.
```

**Comment by mrRedSun** [comment]
I didn't know that.
Nice to have kinda, but git is git. Sorry then, issue closed.
