### ISSUE TITLE
lack of "recent" in file menu

### ISSUE THREAD

**Issue by jbergstroem** [ForkIssues/Tracker#13]
This may be more a poll than anything else, but my brain is looking for "recent" in the File menu. I know "open quickly" gives me a representation; but seeing how most other apps have recent, my subconscious just sits there and does nothing.

Is anyone else feeling the same hurt?

**Comment by DanPristupov** [comment]
Hi.

I've never used the recent menu in other apps, but it should not be difficult to add one soon.

P.S. In Fork I prefer the quick open (Cmd+Shift+O) window which shows recent repos and also supports search.

**Comment by DanPristupov** [comment]
@jbergstroem hi. I added the 'Open Recent' file menu in Fork 1.0.52.

**Comment by jackxujh** [comment]
What about making this neat feature even more handy by defaulting to show Recent repositories upon Fork launch? It feels like a natural extension to the over all _smartness_ of Fork and Recent functionality. #413 (still open) is exactly talking about this.

**Comment by DanPristupov** [comment]
On launch Fork restores the previously open tabs (if you close the application using Cmd+Q), so showing any recent popup doesn't make much sense I suppose.

**Comment by jackxujh** [comment]
Actually I (and many users, I believe) use Command-W to close all windows of an app, then use Command-Q to quit. Besides, all apps have a default to Recent when they launch (if there is no projects opened from the last session), e.g. Xcode, Visual Studio, Adobe CC applications, etc.
