### ISSUE TITLE
Pressing enter when entering the tag name should create the tag

### ISSUE THREAD

**Issue by herrherrmann** [ForkIssues/Tracker#130]
Hello! Yet another small "I don't wanna touch my mouse/trackpad" issue: When I open the modal to create a new tag and enter the tag name I simply want to hit `enter` when I'm done to quickly create the tag (just like when I add a new branch!).

Thanks a lot. :*

**Comment by clounie** [comment]
I'd vote for Enter working in the tag name, but giving a normal newline when in the description.

Could do Shift+Enter for newlines in the description, but that'd probably just lead to frustration for most people, I would think.

**Comment by herrherrmann** [comment]
I think what's pretty established UX-wise (e.g. on social media platforms, chat applications and even here on GitHub) is to use `CMD+Enter` to submit something when you're in a multiline input field (and the regular `Enter` would add a new line).

**Comment by clounie** [comment]
fewf

**Comment by herrherrmann** [comment]
I don't really understand your point yet. My suggestion for the shortcuts would be as follows:
![shortcuts](https://user-images.githubusercontent.com/6429568/31521065-69395c42-afa8-11e7-82b7-b26fb6e42487.png)
I think this is an intuitive way to handle it and it's established in the same way in many other applications. Why would you prefer `Shift+Enter`?

**Comment by clounie** [comment]
Because I've never run into a single app that uses Cmd+Enter, while I've used plenty with `Shift+Enter` - makes no sense to break conventions.

Off the top the head:
1. Twitter
2. Slack - https://get.slack.help/hc/en-us/articles/201374536-Slack-keyboard-shortcuts#message-shortcuts
3. Github (Literally just try in Github when typing your response to this - it's `Shift+Enter`)
4. Fork (commit descriptions)

**Comment by clounie** [comment]
Ah, just read your comment wrong (as `Cmd+Enter` to put a newline in the text box, instead of submitting the dialog.)

Agreed @ `Cmd+Enter` - didn't realize that was a widespread shortcut, but that makes sense.

**Comment by DanPristupov** [comment]
I agree. The 'Create Tag' window submit has been bothered me for a long time :).

I really like the idea to handle both `Enter` and `Cmd+Enter`. Hopefully it won't be tricky to implement.

**Comment by DanPristupov** [comment]
Added support for Cmd+Enter in Fork 1.0.58.
