### ISSUE TITLE
Show merge conflict resolution in list

### ISSUE THREAD

**Issue by svoop** [ForkIssues/Tracker#1304]
This is best shown with a screenshot:

<img width="850" alt="Screen Shot 2021-03-04 at 20 27 39" src="https://user-images.githubusercontent.com/7255/110018958-2b16a400-7d28-11eb-8124-ab8e9c02a421.png">

(The first two conflicts have been resolved already, the remaining are still pending.)

For already resolved conflicts in the list (such as the one selected above), would it be possible to replace the :warning: with another symbol such as the green check mark maybe?

Thanks a bunch for this great Git client!

**Comment by svoop** [comment]
Mostly cosmetic, I'll close this for unimportance.

**Comment by DanPristupov** [comment]
The problem is that in git file remains 'unmerged' until it gets staged. So Fork can only check if file has no conflicts when you open it. I think there's no way to improve that behavior without affecting the performance.
