### ISSUE TITLE
Could not resolve hostname when defined in .ssh/config

### ISSUE THREAD

**Issue by g-amichnia** [ForkIssues/Tracker#1305]
I am using separate ssh identities for different projects. It recently stopped working, with following error:

```ssh: Could not resolve hostname github.com-other: nodename nor servname provided, or not known
fatal: Could not read from remote repository.```

Hostname should be resolved due to ssh configuration:

```ssh
# ~/.ssh/config

# Github other account
Host github.com-other
    HostName github.com
    AddKeysToAgent yes
    UseKeychain yes
    IdentityFile ~/.ssh/other_identity_rsa

# Private account
Host *
    AddKeysToAgent yes
    UseKeychain yes
    IdentityFile ~/.ssh/id_rsa
```

This setup was working flawlessly before, still works when using git from command line.

**Comment by DanPristupov** [comment]
Open SSH Configuration (Fork -> SSH Configuration) and uncheck all SSH keys to make Fork use the default system configuration.

**Comment by g-amichnia** [comment]
@DanPristupov great! It works perfectly. Thank you very much.
