### ISSUE TITLE
[Feature Request] Decide whether to 'Commit' or 'Commit and Push' at commit

### ISSUE THREAD

**Issue by gdman** [ForkIssues/Tracker#1307]
I use Fork with a lot of repositories, most of the the time I want to commit and push at the same time - so I make use of the 'Automatically push on commit' option in preferences. However, there are a few repositories where either I don't want to push automatically or they are local repositories that don't have a remote.

It would be great if I could make the decision to auto push or not at time of commit i.e. default to pushing automatically but have an opt out. Maybe a push checkbox that's checked by default (dare I say it, like Sourcetree, I feel a little dirty now) or perhaps have explicit 'Commit' and 'Commit and Push' buttons maybe as a button menu (defaulted based on the 'Automatically push on commit' option).

Another way to go might be to be able to set 'Automatically push on commit' at a repository level.

Thanks for all of your hard work on Fork, it's a really great product.

**Comment by DanPristupov** [comment]
> It would be great if I could make the decision to auto push or not at time of commit i.e. default to pushing automatically but have an opt out.

Hold `option/alt` key

**Comment by gdman** [comment]
Didn't even know that was a thing. Perfect, thanks!
