### ISSUE TITLE
Hostname is no longer support hyphen suffix?

### ISSUE THREAD

**Issue by jimmywkp** [ForkIssues/Tracker#1308]
Hi Forks!

I'm having multiple ssh keys for multiple clients and projects. I'm using the techniques here and still working if I use git cli: https://gist.github.com/jexchan/2351996

But after upgraded to Fork 2.4.2, I'm no longer making successful git request with following message:
```
ssh: Could not resolve hostname bitbucket.org-someuser: nodename nor servname provided, or not known
fatal: Could not read from remote repository.
```

OS: macOS Catalina 10.15.6
Git: 2.24.3 (Apple Git-128)
Fork: 2.4.2

**Comment by DanPristupov** [comment]
Open SSH Configuration (Fork -> SSH Configuration) and uncheck all SSH keys to make Fork use the default system configuration.

**Comment by jimmywkp** [comment]
Thanks! It's working again! I'm closing this issue now. It would be nice to have it working even checked SSH keys though.
