### ISSUE TITLE
Using multiple GitHub accounts suddenly not working (v2.4.2)

### ISSUE THREAD

**Issue by anadin** [ForkIssues/Tracker#1312]
I updated to 2.4.2 and have previously had two GitHub accounts working using config  setup as listed at the bottom of this issue https://github.com/fork-dev/Tracker/issues/766

Now Fork will not play nice with my work account. I found the Configure SSH Keys panel and my two GitHub keys were unticked. I ticked them (entered my passphrase  and see them in Keychain Access) I can use my repository fine from the command line.

I don't have much else to go on as on a Fetch/Pull/Push I just get the following in the log (xxx being my company name

```
ssh: connect to host xxx.github.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
```

Config file
```
Host github.com
	HostName github.com
	AddKeysToAgent yes
	UseKeychain yes
	IdentityFile ~/.ssh/GitHub2019MBP

Host xxx.github.com
	HostName github.com
	AddKeysToAgent yes
	UseKeychain yes
	IdentityFile ~/.ssh/GitHubXXX2019MBP
```

**Comment by DanPristupov** [comment]
Open SSH Configuration (Fork -> SSH Configuration) and uncheck all SSH keys to make Fork use the default system configuration.

**Comment by anadin** [comment]
Aha, that does work. Thanks, I feel that perhaps the SSH Configuration popup could do with that as an extra message. It's not obvious.

**Comment by JasieBasie** [comment]
Got exactly the same issue with 2.29.2 and with SSH keys unchecked. Tried resetting app, checking and un-checking the checkboxes. Nothing helps. SSH agent is running in terminal and connects fine.

**Comment by DanPristupov** [comment]
@JasieBasie try to switch Fork to you system git instance (Fork -> Preferences -> Git).

**Comment by JasieBasie** [comment]
@DanPristupov Tried this. Didn't help.


PS: I also see this "issue" when using not system git instance.
<img width="656" alt="Screenshot 2023-06-07 at 17 15 03" src="https://github.com/fork-dev/Tracker/assets/123300706/0b06c6c1-762d-4f29-97ee-797b007bf485">
