### ISSUE TITLE
Repositories not showing up in OS X 10.15.7

### ISSUE THREAD

**Issue by matkatmusic** [ForkIssues/Tracker#1313]
I'm trying to open this repository and Fork is saying that there is no repository.  The screenshot clearly shows the .git repo for it.

Also, when I 'rescan repositories' in my folder with all of my repositories, nothing shows up.

This is on a branch new 27" 2020 imac 3.8 GHz 8-Core Intel Core i7
<img width="490" alt="Screen Shot 2021-03-11 at 4 28 30 PM" src="https://user-images.githubusercontent.com/2929847/110873589-f1ddb700-8286-11eb-91fd-0941a546dc6d.png">

**Comment by matkatmusic** [comment]
Ok, the problem went away after I ran Xcode for the first time.

It might be nice to remind the user to run xcode first before trying to scan for repositories.  I am guessing that Fork needs the Xcode Command line Tools installed before it can do what it does.

**Comment by DanPristupov** [comment]
Hi,

Is that possible that you migrated to the new computer (i.e. imported settings from an old one) and Fork couldn't find the git instance you used on the old machine?

**Comment by matkatmusic** [comment]
Hi Dan. 

I did not migrate anything to this new computer.
My guess is that running Xcode for the first time installed the Xcode CommandLine Tools, which installs the default instance of Git that Fork is looking for.  But that is just a guess.

**Comment by pyby** [comment]
When a folder san for repositories does not find anything, I found that my `xcode-select -p`. command returns a path to an old Xcode version that I just deleted.

Even if Fork has in the preferences, in Git tab, the global user information was empty. The setting above displayed "Fork instance" but Fork does not use it, from my feedback.

To solve it (with UI, but can be done with command line too):
- Open Xcode and go to preferences / location. Command line tools was empty.
- I selected the new Xcode instance.
- Fork scanned my folder and found all Git repositories.
- Fork preferences, Git tab. the git version is again "Apple git" version.

Maybe, you should check that Xcode location for command line tool has a valid path.
