### ISSUE TITLE
[Issue] File names in Local Changes view possibly overly compressed

### ISSUE THREAD

**Issue by ghost** [ForkIssues/Tracker#1316]
v2.5.5
macOS Catalina 10.15.7

File names in the Local Changes view look to be a lot more compressed than normal. Unsure if this is a bug or implemented on purpose? It makes file names hard to read sometimes if they are long names.

<img width="386" alt="image" src="https://user-images.githubusercontent.com/70993406/111212104-142f5600-8634-11eb-8553-2e7a7e531a72.png">

**Comment by DanPristupov** [comment]
Weird, but I can not reproduce this. Does this happen in both `Tree` and `List` file list modes?

**Comment by DanPristupov** [comment]
Does the problem disappear when you resize the file list width?

**Comment by ghost** [comment]
Looks to only happen in list mode. Resizing the file list to be smaller in width than the text and then re-expanding it fixes the issue, but it reappears when restarting the application.

**Comment by StefanoCecere** [comment]
same problem, mac 2.5.0, bot list and tree
<img width="761" alt="Screenshot 2021-03-25 at 22 26 47" src="https://user-images.githubusercontent.com/640536/112546062-402ba380-8db9-11eb-8121-0d73f9cebc31.png">

<img width="760" alt="Screenshot 2021-03-25 at 22 26 33" src="https://user-images.githubusercontent.com/640536/112546051-3bff8600-8db9-11eb-87a6-8da361b90c1b.png">

**Comment by StefanoCecere** [comment]
ah ok. fixed by narrowing the panel and enlarging it again.
odd but now it's fixed :)

**Comment by ghost** [comment]
Closing this, does not seem to appear anymore. Currently running 2.14 but this was probably fixed ages ago.
