### ISSUE TITLE
Diff view error when uncheck ignore whitespaces

### ISSUE THREAD

**Issue by susan51531** [ForkIssues/Tracker#132]
I find a diff view error when I view [kibana repos](https://github.com/elastic/kibana/).
It's the diff of README.md file for the first two commits.

Default(uncheck ignore whitespace)
![image](https://user-images.githubusercontent.com/2595468/31537353-720cbae8-afc7-11e7-882b-86691caf465d.png)

Ignore whitespaces
![image](https://user-images.githubusercontent.com/2595468/31537385-919bf1c6-afc7-11e7-99a3-d9f65cb728d5.png)

**Comment by DanPristupov** [comment]
Hi!

Thank you for reporting this. I'll pull the Kibana and investigate what's going on.

**Comment by DanPristupov** [comment]
It turned out that this is the same problem as mentioned here https://github.com/ForkIssues/Tracker/issues/109.
The fix is going to be available in the next release. Thank you
