### ISSUE TITLE
Feature: Display Diff between two commits

### ISSUE THREAD

**Issue by d-koppenhagen** [ForkIssues/Tracker#1321]
When selecting multiple commits using the "Shift"-key, a message in the bottom area appears, that indicates, only diff between two commits can be shown.

It would be great if one can select commit ranges as displayed in the example image below and the bottom area will display the diff between all the selected commits.

![Bildschirmfoto 2021-03-23 um 07 42 45](https://user-images.githubusercontent.com/4279702/112104592-b1960700-8bab-11eb-993b-a905648ae2f2.png)

**Comment by DanPristupov** [comment]
> only diff between two commits can be shown.

This is enough.

> It would be great if one can select commit ranges

A range is defined by a **pair** of commits.

>  the bottom area will display the diff between all the selected commits.

You don't need the diff between all the selected commits. You are only interested in diff between the first and the last one.

So, just select the first and the last commits of a range.

**Comment by d-koppenhagen** [comment]
Ah I agree. I think my problem was just that I didn't know that I can select two commits by using "ctrl".
