### ISSUE TITLE
Fork continuously attempting to update git instance & never launches

### ISSUE THREAD

**Issue by safderiqbal** [ForkIssues/Tracker#1322]
![Screenshot 2021-03-23 112117](https://user-images.githubusercontent.com/1107375/112138927-0183c680-8bca-11eb-86c6-ea6f6d5e99ff.png)

Since updating to Fork 1.60 the application always prompts with this window to update the internal Git instance and never subsequently launches the full application.

**Comment by safderiqbal** [comment]
For context, this has been attempted several times and each time, when Fork is launched again, prompts with the window shown above,

**Comment by DanPristupov** [comment]
Hi. May be an antivirus doesn't allow to update the git instance.

Try to reinstall the application: https://fork.dev/update/win/ForkInstaller.exe

**Comment by safderiqbal** [comment]
Thank you. Reinstall worked.
