### ISSUE TITLE
Launch path is not executable '$sh'

### ISSUE THREAD

**Issue by markshep** [ForkIssues/Tracker#1323]
Someone on my team has added custom commands to our repos, however they're using Windows and I'm using a Mac and the commands fail for me with this error:

    Launch path is not executable '$sh'

Please can you define `$sh` on Mac to be `/bin/sh` so that these commands can work?

**Comment by DanPristupov** [comment]
We added `$sh` in Fork 2.6.

I consider this as a workaround though. I think we need to introduce a new custom command type, which allows to write bash scripts (including pipes). E.g. `git log $SHA | wc -l`

**Comment by markshep** [comment]
Thanks for that - I've got it working now with version 2.6.

**Comment by markshep** [comment]
I'm now getting the original error message again with Fork 2.28.1, so I guess you removed `$sh` and implemented something else instead.  Please can you tell me how to fix my custom commands, which are:

```json
[
  {
    "name": "Open on GitHub",
    "target": "revision",
    "action": {
      "type": "process",
      "path": "$sh",
      "args": "$path/Tools/github-url $sha open",
      "showOutput": false,
      "waitForExit": true
    }
  },
  {
    "name": "Copy GitHub URL",
    "target": "revision",
    "action": {
      "type": "process",
      "path": "$sh",
      "args": "$path/Tools/github-url $sha copy",
      "showOutput": false,
      "waitForExit": true
    }
  }
]
```

**Comment by DanPristupov** [comment]
Ah, that's a bug! I'm sorry, I made a typo.

Can you show what's inside `github-url` file?

**Comment by markshep** [comment]
Here's the `github-url` script:

```shell
#!/bin/sh

if [ $# = 0 ]; then
    echo "ERROR: missing SHA argument"
    exit 1
fi

sha=$1
shift

if [ $# -gt 0 ]; then
    command=$1
    shift
fi

if [ $# -gt 0 ]; then
    echo "ERROR: too many aguments"
    echo "USAGE: $0 sha [open|copy]"
    exit 1
fi

# This only works for SSH repos, not HTTPS repos.
origin=$(git remote get-url origin)
eval $(sed -E 's,^[^@]+@(.+):(.+)\.git$,host=\1; repo=\2,' <<< $origin)
url="https://$host/$repo/commit/$sha?ts=4"

if [ $(uname) = Darwin ]; then
    os=mac
else
    os=windows
fi

case $command in
    open)
        if [ $os = mac ]; then
            open $url
        else
            start $url
        fi
        ;;

    copy)
        if [ $os = mac ]; then
            /bin/echo -n $url | pbcopy
        else
            /bin/echo -n $url >/dev/clipboard
        fi
        ;;

    *)
        echo $url
        ;;
esac
```

**Comment by DanPristupov** [comment]
1. I made a build with the hotfix. You can download it here: https://cdn.fork.dev/mac/Fork-2.28.2.dmg.
2. I'll try to make the given `.sh` script work and will send an update here later.

**Comment by DanPristupov** [comment]
Regarding the script. It's written by a very smart person 👍.

Here is another way to run it using `.sh` custom commands. I think it's a slightly shorter:

`.fork/custom-commands.json`:
```
[
  {
    "name": "Copy GitHub URL",
    "target": "revision",
    "action": {
      "type": "sh",
      "script": "origin=$(git remote get-url origin)\neval $(sed -E 's,^[^@]+@(.+):(.+)\\.git$,host=\\1; repo=\\2,' <<< $origin)\n\nurl=\"https://$host/$repo/commit/$sha?ts=4\"\n\nif [ $(uname) = Darwin ]; then\n    /bin/echo -n $url | pbcopy\nelse\n    /bin/echo -n $url >/dev/clipboard\nfi",
      "showOutput": false,
      "waitForExit": false
    }
  },
  {
    "name": "Open on GitHub",
    "target": "revision",
    "action": {
      "type": "sh",
      "script": "origin=$(git remote get-url origin)\neval $(sed -E 's,^[^@]+@(.+):(.+)\\.git$,host=\\1; repo=\\2,' <<< $origin)\n\nurl=\"https://$host/$repo/commit/$sha?ts=4\"\n\nif [ $(uname) = Darwin ]; then\n    open $url\nelse\n    start $url\nfi",
      "showOutput": false,
      "waitForExit": false
    }
  }
]
```

Copy GitHub URL:

<img width="834" alt="Screenshot 2023-04-25 at 18 11 36" src="https://user-images.githubusercontent.com/618115/234338101-32ee62e7-2053-4652-93d9-30abc9d7212c.png">

```
origin=$(git remote get-url origin)
eval $(sed -E 's,^[^@]+@(.+):(.+)\.git$,host=\1; repo=\2,' <<< $origin)

url="https://$host/$repo/commit/$sha?ts=4"

if [ $(uname) = Darwin ]; then
    /bin/echo -n $url | pbcopy
else
    /bin/echo -n $url >/dev/clipboard
fi
```

Open on GitHub:

<img width="834" alt="Screenshot 2023-04-25 at 18 11 58" src="https://user-images.githubusercontent.com/618115/234338196-fa6d0041-5b50-4183-b886-e3c7f9fa0633.png">

```
origin=$(git remote get-url origin)
eval $(sed -E 's,^[^@]+@(.+):(.+)\.git$,host=\1; repo=\2,' <<< $origin)

url="https://$host/$repo/commit/$sha?ts=4"

if [ $(uname) = Darwin ]; then
    open $url
else
    start $url
fi
```

**Comment by DanPristupov** [comment]
And since we are here, I think we should add the ability to open (and copy) the commit url to Fork.

**Comment by markshep** [comment]
I can confirm that the 2.28.2 build with the hotfix works - thanks for your help!

**Comment by DanPristupov** [comment]
We are in the middle of a large custom commands refactoring, so some things may get broken.

That particular bug happened because we've been introducing new variables syntax (`${sha}` instead of `$sha`, etc), which will allow us to implement GUI custom commands and access particular controls by index using variables like `$3{sha}`, `$4{file:path}`.
