### ISSUE TITLE
ellipsizes always in the start 

### ISSUE THREAD

**Issue by sejalis** [ForkIssues/Tracker#1329]
Hello! First of all, I love your Git Client! :) 
After the last Update I'm having the issue of always having ellipsized file names (in the beginning) in my local changes (staged or unstaged). As far as I remember I had the unstaged/staged window very small before/while updating. 

![fork screen](https://user-images.githubusercontent.com/49563775/112541275-7ebe5f80-8db3-11eb-804a-76e52f326540.png)
<img width="265" alt="Bildschirmfoto 2021-03-25 um 21 47 32" src="https://user-images.githubusercontent.com/49563775/112541475-b75e3900-8db3-11eb-9b41-46dce46e2e3a.png">

**Comment by DanPristupov** [comment]
Hi. We fixed this in Fork 2.6
