### ISSUE TITLE
Add ability to create a patch file

### ISSUE THREAD

**Issue by sirnacnud** [ForkIssues/Tracker#133]
There is the ability to Apply a patch currently. It would also be nice if there was support to create a patch file from a commit or group of commits.

**Comment by DanPristupov** [comment]
Hi. Ability to create patches should not be difficult to implement, but I need to finish other tasks first. I added this request to my todo list.

**Comment by torre76** [comment]
+1 for this feature request.

Support for `git format-patch` would be very handful.

**Comment by DanPristupov** [comment]
Hi. I've added ability to create a patch in 1.0.67.

**Comment by evgeny-sureev** [comment]
And can you implement creating a patch from uncommited changes too?

**Comment by nebhale** [comment]
@evgeny-sureev This issue has been closed for three weeks and it's not reasonable to comment on it after that time.  You should open a new issue requesting the enhancement you seek.
