### ISSUE TITLE
"Stage All" button too small!

### ISSUE THREAD

**Issue by StefanoCecere** [ForkIssues/Tracker#1330]
i didn't really notice that those two arrows were the stage all button!

<img width="92" alt="Screenshot 2021-03-25 at 22 29 51" src="https://user-images.githubusercontent.com/640536/112546409-afa19300-8db9-11eb-91da-1e143de0c9de.png">

**Comment by DanPristupov** [comment]
You can hold Alt to have a bigger 'Stage All' button :).

Jokes aside, the button is small intentionally. 'Stage All' should not be easy accessible.

**Comment by StefanoCecere** [comment]
didn't know about the Alt.. perfect! thank you
