### ISSUE TITLE
 [Gitlab integration] Missing project list

### ISSUE THREAD

**Issue by eagle23** [ForkIssues/Tracker#1334]
In api gitlab it is possible to get not only your own projects, but also projects to which you have access.

List all projects
Get a list of all visible projects across GitLab for the authenticated user.
https://docs.gitlab.com/ee/api/projects.html#list-all-projects

List user projects
Get a list of visible projects owned by the given user.
https://docs.gitlab.com/ee/api/projects.html#list-user-projects

**Comment by DanPristupov** [comment]
Can you try if this version shows all the repos https://cdn.fork.dev/mac/Fork-2.6.1.dmg?

**Comment by eagle23** [comment]
Works perfectly!

**Comment by DanPristupov** [comment]
You are fast! Thank you :)

**Comment by yossizahn** [comment]
Hi @DanPristupov,
Is version 2.6.1 supposed to show all Gitlab projects I have access to? It doesn't yet work for me. (I have none of my own repos but I have access to a few projects in another org)
![image](https://user-images.githubusercontent.com/19174667/115373364-7ac80680-a1d4-11eb-8c74-aafba27ad0a9.png)

![image](https://user-images.githubusercontent.com/19174667/115373488-9b905c00-a1d4-11eb-8a45-697a999a2532.png)

The Github account does show all projects I have access to.

**Comment by yossizahn** [comment]
Listening in to the traffic using Charles shows that you are requesting: `/api/v4/projects?page=1&per_page=30&owned=true`.
That should probably be changed to `/api/v4/projects?page=1&per_page=30&membership=true`.

Thanks. Appreciate all your work making Fork the great app that it is!

**Comment by yossizahn** [comment]
BTW, this doesn't work for me on the Windows version too.

**Comment by DanPristupov** [comment]
@yossizahn you are probably right. Could you check if this version works as you expect? https://cdn.fork.dev/prerelease/Fork-2.6.8.dmg

**Comment by yossizahn** [comment]
Yes, it works great. Thanks.
