### ISSUE TITLE
how to program checkin hooks?

### ISSUE THREAD

**Issue by jimka2001** [ForkIssues/Tracker#1340]
Does fork have any way to implement check-in hooks?
I'm looking for some way to update copyright headers on checkin.
In my case it could be done with regex search and replace, but would need to have some bit of interaction
capability.

I'm not exactly sure how smart this feature would need to be.  I'm just interested to know what capabilities exist
in the tool already, including capabilities for me to program my own hooks?

**Comment by DanPristupov** [comment]
https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks
https://www.git-scm.com/docs/githooks#_pre_commit

**Comment by jimka2001** [comment]
Thanks for the links.  So the feature must be done with git itself, not with Fork if I understand correctly?  And there's no way to  hook into Fork's interaction?

**Comment by DanPristupov** [comment]
Yes, this is a feature of git.

Basically, a hook is an executable `.sh` script in the `.git/hooks` directory which will be run before/after the corresponding action. You can open `.git/hooks` in any of your repos and check the samples (just rename one in order to try).

**Comment by DanPristupov** [comment]
Since we are here, usually it's better to NOT slow down commit by long-running hooks. Instead, I'd recommend to add to the repository an executable `.sh` script which will do what you want, and run it when you need. But it's up to you, of course.

**Comment by jimka2001** [comment]
Thanks for the advice.  The problem is remembering to run it when I need, and deciding when I need it.   Ideally I'd like to prevent changes and checkins (by me or anyone else) with insufficient copyright notices.  

OK, I'll look further elsewhere.
