### ISSUE TITLE
Avatar showing question mark

### ISSUE THREAD

**Issue by wqfan** [ForkIssues/Tracker#1343]
Hello,

Fork is showing a question mark as my avatar. I'm curious about in which case it's a question mark and when it's name initial. 

The email address is not on Gravatar so I suppose Fork will use the GitHub profile avatar. If I visit `https://avatars.githubusercontent.com/u/e?email=<my_email_address>`  (not the public address of this GitHub account), I'm able to see the GitHub avatar. 

I'm wondering if you can help troubleshoot the issue here. And thanks for making this awesome Git client!

**Comment by DanPristupov** [comment]
I can see your avatar in this repo: https://github.com/wqfan/wqfan.github.io
<img width="169" alt="Screenshot 2021-04-07 at 21 38 34" src="https://user-images.githubusercontent.com/618115/113924053-9e10b000-97e9-11eb-9e37-2611ee7932d2.png">
> Fork is showing a question mark as my avatar. 

Can you show a screenshot of the question mark, please?

> The email address is not on Gravatar so I suppose Fork will use the GitHub profile avatar.

Correct

**Comment by wqfan** [comment]
That's right. It's working fine for emails associated with this GitHub account. However, it's showing like below when I'm using my work email which is associated with a different GitHub account.

<img width="162" alt="Screen Shot 2021-04-07 at 12 50 27 PM" src="https://user-images.githubusercontent.com/7760864/113925608-15215680-97a0-11eb-8081-6a6ee499f76b.png">

**Comment by DanPristupov** [comment]
Can you send it to support@fork.dev, so I could check what's going on, please?

**Comment by wqfan** [comment]
Sure. Sent the email. Thanks for the quick response!

**Comment by wqfan** [comment]
After some investigation with Dan, it turns out it's a problem with my network or GitHub CDN. The request `https://avatars.githubusercontent.com/u/e?email=<my_email_address>&s=64` returns a default avatar in which case Fork falls back to use name initials as the avatar. When on a different network, Fork displays the right avatar.

However, in my case, Fork doesn't fall back to initials correctly. Instead it shows question mark. It seems Fork has some problems in generating the initials when the last name is <= 2 characters:
![image](https://user-images.githubusercontent.com/7760864/116490516-72af3d00-a84c-11eb-810c-a074073073a4.png)

I tested this on two Intel based MacBook Pros and can reproduce it in both cases. One is on Fork 2.7 and the other is on 2.5.6. It doesn't seem to be a problem on Dan's Mac though.

**Comment by DanPristupov** [comment]
I'm just curious, is the problem still actual?

**Comment by wqfan** [comment]
It's not. I'm closing it. Thanks for following up on this!
