### ISSUE TITLE
Feature Suggestion: push force with lease

### ISSUE THREAD

**Issue by hcguersoy** [ForkIssues/Tracker#1344]
Currently, it is possible to force push a commit, e.g. after an amend. 
It would be nice to have an additional checkbox _force with lease_ using the option `--force-with-lease` to be a bit more on the safe side.

**Comment by DanPristupov** [comment]
<img width="505" alt="Screenshot 2021-04-08 at 13 25 21" src="https://user-images.githubusercontent.com/618115/114018761-e2459400-986d-11eb-9304-da2d664bcc9d.png">

<img width="898" alt="Screenshot 2021-04-08 at 13 26 10" src="https://user-images.githubusercontent.com/618115/114018862-00ab8f80-986e-11eb-9b72-1e73c62c4976.png">

https://github.com/fork-dev/Tracker/issues/526

**Comment by hcguersoy** [comment]
ok, sorry, I should check if same request already exists.
Closing :-)
