### ISSUE TITLE
On mac, file names incorrectly truncated in File Tree panel

### ISSUE THREAD

**Issue by dgolembomyob** [ForkIssues/Tracker#1345]
On a Mac, in the File Tree panel, the filenames are truncated in a very narrow column, regardless of how much space is available.  Shrinking the panel to the width of this invisible column causes Fork to crash.
![image](https://user-images.githubusercontent.com/42726260/114111153-9998e400-991c-11eb-8033-3cde5f1353f4.png)

**Comment by DanPristupov** [comment]
Hi. This is fixed in Fork 2.7
