### ISSUE TITLE
Must use exact 7-character form of short SHA-1 for search

### ISSUE THREAD

**Issue by mtschoen-unity** [ForkIssues/Tracker#1351]
I just tried searching in my repo with a short hash of only 6 characters, and didn't find it. I then tried the _full_ hash and it also didn't show up. I had to search for the specific 7-character string that I see in the SHA-1 column of fork.

I would expect that at least the full hash returns a valid result, and I would also like to be able to search for a "fragment" of the first few characters, without having to match the exact character length.

**Comment by DanPristupov** [comment]
I just checked, any number of characters work properly. 3, 6, 7 or full SHA. Fork may not highlight the match if the column, if it's not complete, but it will jump to the commit properly.

**Comment by DanPristupov** [comment]
<img width="500" alt="Screenshot 2021-04-13 at 19 26 07" src="https://user-images.githubusercontent.com/618115/114594935-1bc33880-9c8e-11eb-95e1-1684baa6c107.png">
<img width="500" alt="Screenshot 2021-04-13 at 19 26 47" src="https://user-images.githubusercontent.com/618115/114595002-32698f80-9c8e-11eb-8ab8-3b99648ae5be.png">

**Comment by mtschoen-unity** [comment]
Weird! I just tried again and it works 🤔 
I wonder if maybe the string I was pasting in had special characters or something. I'll close for now and re-open if I see it again.
