### ISSUE TITLE
Open In Finder opens parent folder, not folder with repo

### ISSUE THREAD

**Issue by matkatmusic** [ForkIssues/Tracker#1358]
Previous versions of Fork opened the folder that contained the `.git` repository. 
The latest version running on OS X Catalina opens the parent folder. 
I'm running Fork v2.6.1

Example:

My repository is stored inside this JUCE folder here: 
`/Volumes/Thunderbay/MyBook2/Programming/JUCE/.git`
`Open in Finder` opens `/Volumes/Thunderbay/MyBook2/Programming/` instead of the `JUCE` folder.

**Comment by DanPristupov** [comment]
I didn't touch that code for 2-3 years at least.

> The latest version running on OS X Catalina opens the parent folder.

I guess, you switched Finder to Column View. After some macOS update, It started opening the parent folder. The icons view still works properly.

**Comment by DanPristupov** [comment]
I just checked, `Reveal in Finder` called from XCode also opens parent folder, when Finder is in 'Column View' mode.

**Comment by matkatmusic** [comment]
Nice sleuthing.   Is this a bug that should be reported to Apple?

**Comment by DanPristupov** [comment]
It looks like a bug for me.

**Comment by matkatmusic** [comment]
Cool.  I reported it via their Feedback tool, linking to this Pull request as confirmation from another Apple user.
