### ISSUE TITLE
https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

### ISSUE THREAD

**Issue by bwl21** [ForkIssues/Tracker#1359]
What shall I do with this respect?

I got an email with:
You recently used a password to access the repository at bwl21/CT-API-Tools with git using git/2.27.0.

I have configured an SSH for Github.

**Comment by DanPristupov** [comment]
> You recently used a password to access the repository
> ...
> I have configured an SSH for Github.

Something is wrong here.

If you use SSH, you don't need to do anything.
If you use password, then you should log in to your GitHub account in Fork (Fork -> Accounts -> + -> GitHub).

**Comment by bwl21** [comment]
The issue is still there,I could not find the root cause. I will reopen it when I find a reason or a solutionl

**Comment by DanPristupov** [comment]
Check the url of the remote server.
