### ISSUE TITLE
Give option to commit without pushing

### ISSUE THREAD

**Issue by bdgeyter** [ForkIssues/Tracker#136]
Once there is a remote tracking branch, there seems to be no option to commit without pushing. This is handy in several scenarios. Maybe I'm missing something here?

**Comment by DanPristupov** [comment]
Fork doesn't push on commit by default. May be you've enabled the following option occasionally? 
![2017-10-17 at 17 20](https://user-images.githubusercontent.com/618115/31673529-ba17899e-b35f-11e7-9914-59fcb3c22bce.png)

Also, please read this: https://github.com/ForkIssues/Tracker/issues/77

**Comment by bdgeyter** [comment]
Clearly was missing my ability to find stuff in Settings and in the Issue tracker today 🙈 

Thanks for the quick help and the reference, Dan!
