### ISSUE TITLE
Bitbucket shows only a subset of repos to clone

### ISSUE THREAD

**Issue by kambala-decapitator** [ForkIssues/Tracker#1362]
My Bitbucket account is in multiple teams and I have access to tens of repos, but in the clone window I see only 10. Looks like it's the first page of response (or a bug in UI), as the repos I see are from one of the teams and in alphabetical order. I don't even see my personal repos!

v2.6.1 (I use `develop` update channel), Catalina

**Comment by DanPristupov** [comment]
I confirm the problem

**Comment by DanPristupov** [comment]
Can you check if the problem is fixed in this build, please? https://cdn.fork.dev/prerelease/Fork-2.6.9.dmg

**Comment by kambala-decapitator** [comment]
> Can you check if the problem is fixed in this build, please? https://cdn.fork.dev/prerelease/Fork-2.6.9.dmg

works fine! thanks!

**Comment by DanPristupov** [comment]
The fix will be a part of the 2.7 update (it's planned for tomorrow)
