### ISSUE TITLE
Offer to stash changes when creating a new branch

### ISSUE THREAD

**Issue by aceslick911** [ForkIssues/Tracker#1363]
I've done this at least 40 times - 
1. Go to create a new branch on a specific commit using the right click menu - not noticing that I have some uncommitted changes
```
error: Your local changes to the following files would be overwritten by checkout:
	package-lock.json
Please commit your changes or stash them before you switch branches.
Aborting
```
2. Come up with a good branch name, hit create branch
3. Error says I have uncommitted code. Git command is rejected and cancelled. I have to now remember what branch name I wanted and manually stash and create the new brnahc.

This is a known output when creating a branch through git; it would be helpful if git-fork could help avoid this small but frequently occurring gotcha

**Comment by DanPristupov** [comment]
> Error says I have uncommitted code. Git command is rejected and cancelled. **I have to now remember what branch name I wanted and manually stash and create the new branch.**

In Fork 2.7 the dialog will remember the branch name if an error happens.

**Comment by aceslick911** [comment]
Wow.. really? It’s already implemented waiting for a release? There’s no way you did that since I asked this question 12 hrs ago 😂😂

nice! Whatever the reason I’m excited for it!

**Comment by DanPristupov** [comment]
Tanya implemented it today after reading your issue :)

**Comment by DanPristupov** [comment]
You can try the new build here, if you don't want to wait for the automatic update: https://cdn.fork.dev/mac/Fork-2.7.dmg

**Comment by aceslick911** [comment]
Wow thats very impressive! Just tried it - I noticed i didn't get any prompt this time; fork simply stashed and un-stashed my changes I think! Marked as closed!

Is there any way to see which git commands fork has run?

**Comment by DanPristupov** [comment]
> Is there any way to see which git commands fork has run?

Yes, you can see the internal requests in the activity manager. Click on the left-bottom corner on the status control on the toolbar.
