### ISSUE TITLE
Pushing should remember last selected remote

### ISSUE THREAD

**Issue by cwensley** [ForkIssues/Tracker#1367]
When you have more than one remote configured, it is seemingly random on which remote gets selected when pushing a branch.  It would be preferable if this was configurable or at least just remember the last remote that was pushed to and use that.

**Comment by DanPristupov** [comment]
It's not random. The dialog selects the corresponding remote tracking branch.

**Comment by cwensley** [comment]
There _is_ no remote tracking branch.  I've created it locally and am trying to push it to GitHub.

**Comment by cwensley** [comment]
To be clear, this is my workflow:

1. Create a new branch with Fork
2. Commit some changes
3. Click Push.  I want it to always go to a specific remote.

**Comment by DanPristupov** [comment]
I forgot to mention that starting from 2.12 (24 September 2021) Fork remembers the last remote which was used for a local branch without remote tracking branch.

**Comment by cwensley** [comment]
Woo!  Thank you!

I thought so, I haven't had to select the remote for quite a while but I thought it was just randomly picking the right one now.  

Thanks for the follow up.
