### ISSUE TITLE
Bitbucket Server "Token is not valid" 

### ISSUE THREAD

**Issue by sejalis** [ForkIssues/Tracker#1369]
Hi there! 

I wanted to try out the new Bitbucket Server feature, but I'm already struggling with the login. 

It seems like you are using the following request when logging in:
`curl --location --request GET 'https://bitbucket.mycompanyname.country/rest/api/1.0/projects/' \
--header 'Authorization: Bearer PERS_TOKEN' \`

which unfortunately fails for me in Fork:
![fork bitbucket server login](https://user-images.githubusercontent.com/49563775/116523162-36c0ba00-a8d6-11eb-962e-837cf72895c3.png)

although succeeds with postman:
![postman](https://user-images.githubusercontent.com/49563775/116523151-332d3300-a8d6-11eb-9a98-689c103157a3.png)

We have a VPN connection within the company, might that be the issue for Fork?

Thanks in advance.
Cheers

**Comment by DanPristupov** [comment]
> We have a VPN connection within the company, might that be the issue for Fork?

Not sure. Check if the log file `~/Library/Logs/Fork.log` contains any error.

**Comment by sejalis** [comment]
looks like it: 

```
[GitServiceConnection.swift:88] > 130ms: GET https://bitbucket.XXXXX.XXX/rest/api/1.0/application-properties (200)
BitbucketServerLoginController.swift:74] > unknown("Token is not valid")
```


Just wondering, how come that I'm getting this error? 
According to the [Documentation](https://docs.atlassian.com/bitbucket-server/rest/7.7.1/bitbucket-rest.html)
![Bildschirmfoto 2021-04-30 um 15 09 02](https://user-images.githubusercontent.com/49563775/116699590-09533980-a9c6-11eb-8852-767d1b9758f3.png)

there is no token needed, so I guess thats not the call which is failing?

Could you please share which endpoint you are using for the login? I'd like to try it locally via Postman

**Comment by DanPristupov** [comment]
@sejalis it's `/rest/api/1.0/application-properties`. Fork uses it to retrieve the `X-AUSERNAME` header.

**Comment by davidkaya** [comment]
I have the exact same issue. Could the logging be improved so we are able to troubleshoot it better?

**Comment by DanPristupov** [comment]
@davidkaya It's difficult because I don't have an access to such server.

Do you see the `X-AUSERNAME` header if you run:

`curl "https://SERVERNAME/rest/api/1.0/application-properties" \
     -H 'Authorization: Bearer <TOKEN>'`?

**Comment by davidkaya** [comment]
Yep, I do:

```
...
< x-auserid: XXX
< x-ausername: XXX
...
```

**Comment by DanPristupov** [comment]
@davidkaya that's weird. Can you contact me by email, please? support@fork.dev

**Comment by sejalis** [comment]
sorry to get back so late to you. 😬 
Seems like you resolved the issue (or IT updated the server or ... ? ), login has worked today. 👏
