### ISSUE TITLE
Show diff context in All Commits > Changes tab

### ISSUE THREAD

**Issue by otto-md** [ForkIssues/Tracker#137]
If I look at the diff under Changes > diff viewer I see the context (marked in red below).
<img width="548" alt="screen shot 2017-10-19 at 15 22 02" src="https://user-images.githubusercontent.com/31409359/31772995-a3b34f16-b4e1-11e7-83da-321d39c7a9dd.png">

But if a look at the diff of a commit below All Commits it looks like this:
<img width="416" alt="screen shot 2017-10-19 at 15 23 08" src="https://user-images.githubusercontent.com/31409359/31773071-e17b229c-b4e1-11e7-8ccc-6c9683f3ba2b.png">

There is no context displayed (marked in red). Is there any specific reason for this?

**Comment by DanPristupov** [comment]
Hi. I already fixed this. The fix will be available in the next Fork update.

**Comment by otto-md** [comment]
Perfect. Thanks!
