### ISSUE TITLE
"Ignore whitespace" not working in "Changes" view

### ISSUE THREAD

**Issue by scheinercc** [ForkIssues/Tracker#1376]
### Steps
1. Select a commit which includes some changes to whitespace
2. Swtich to "Changes" (`opt + cmd + 2`, "Show Commit Changes")
3. Toggle "Ignore whitespace" on

### Expected
Any changes which only affect whitespace would be hidden from the view.

### Actual
No change between "Ignore whitespace" on or off

### System
macOS 11.3
Fork: Version 2.7 (also true for Version 2.6, maybe earlier)

### Screenshot
<img width="1423" alt="Screen Shot 2021-05-07 at 11 33 54 am" src="https://user-images.githubusercontent.com/817856/117386331-0e663a80-af2a-11eb-9028-6d90bd591913.png">

### Note
Same for "Show diff side-by-side (spacebar)" view - clicking the eye icon.

**Comment by DanPristupov** [comment]
Could you check how this feature works now? I made some improvements recently, but not sure if they affected your particular case.

**Comment by scheinercc** [comment]
I checked a few files and it seems to work pretty well now. The case above has been addressed. 
I found changes with single empty lines added or removed which is not covered by this filter, but maybe that is intentional?

**Comment by DanPristupov** [comment]
> I found changes with single empty lines added or removed which is not covered by this filter, but maybe that is intentional?

Not sure. Can you show an example?

Now Fork uses `git diff --ignore-all-space` flag (https://git-scm.com/docs/diff-options/2.9.5#Documentation/diff-options.txt---ignore-all-space), so I guess this is as much as we can do.

**Comment by scheinercc** [comment]
> I guess this is as much as we can do.

That's fine with me. Happy to close.

**Comment by scheinercc** [comment]
Hey @DanPristupov 

> Can you show an example?

here is a simple one, just in case you are curious:

![Screen Shot 2021-07-28 at 10 55 14 am](https://user-images.githubusercontent.com/817856/127246555-b0b64603-deb3-4458-9c1a-6031961c39bd.png)
