### ISSUE TITLE
Tapping left arrow when a branch commit is selected crashes the app

### ISSUE THREAD

**Issue by parrotbait** [ForkIssues/Tracker#1379]
Version: 2.7
Reproducible: 100%

I have a branch commit selected and when the tip commit is select and the left arrow is pressed (I did it by accident initially), the app crashes. It is 100% reproducible, though pressing left on some other commits doesn't crash.

Sent the crash to apple but also included the crash stack as an attachment.

Branch selected: 

![branch_crash](https://user-images.githubusercontent.com/2385924/117785401-75dafd80-b23c-11eb-958e-84293b5e659b.jpg)

[fork-crash.txt](https://github.com/fork-dev/Tracker/files/6457571/fork-crash.txt)

**Comment by DanPristupov** [comment]
Thank you, I will have a look.

**Comment by kambala-decapitator** [comment]
Seeing a similar crash but under different conditions, not sure if it's actually the same or not.

Open completely empty repo in Fork (I created it on Bitbucket and cloned) and press right or left arrow -> crash. No crash with up/down arrows.

Crash log: [crash.txt](https://github.com/fork-dev/Tracker/files/7719280/crash.txt)

![Screenshot 2021-12-15 at 15 24 15](https://user-images.githubusercontent.com/1557784/146186227-c03b8db6-2df3-45b4-b5ce-c4db4fedf8bb.png)
