### ISSUE TITLE
Commits History are cut off

### ISSUE THREAD

**Issue by susan51531** [ForkIssues/Tracker#138]
When open large repos likes [nodejs](https://github.com/nodejs/node), commits history cannot be scrolled to the first commit as if there is a limit on the visible commit lines.

**Comment by DanPristupov** [comment]
It's not that important to watch earlier commits, excepting the curiosity reason ('how did did this project start?'). Currently Fork has a limit for 25000 commits which is enough for 99.9% of cases.

I introduced the limit when a guy from Chromium project mentioned that Fork had used few gigabytes of RAM loading commit list of 10GB repository.

I'm going to implement a pagination one day, but it's a low-priority task.

**Comment by MisLink** [comment]
@DanPristupov 
Hi, I have the same issue and I found this one. I cloned this repo https://github.com/celery/celery and try to get the first commit (curiosity reason of course), but only 8819 commits show:
<img width="474" alt="图片" src="https://user-images.githubusercontent.com/8280169/76677090-38152180-6605-11ea-9103-3cbcf0169dd3.png">
Github says it has 11000+ commits currently.
The other big repo (I tried https://github.com/getsentry/sentry) shows 25000 commits just like you said.
Is it limited by other conditions?

---
env:
Fork 1.0.90 
MacOS 10.14.6

**Comment by mikebeaton** [comment]
Can I respectfully disagree that this is a low priority. I have the same issue with the qemu repo, and I wish to actively investigate an issue that arose around 00fcd100c3f47445f6a59d39e11601460880cfe4 and e3592bc9d841c397eeda87f0019fab94ff71004b. I can't use Fork to do that.

**Comment by DanPristupov** [comment]
@mikebeaton we are working on that

**Comment by DanPristupov** [comment]
You can change the limit by running `$ defaults write com.DanPristupov.fork maxCommitCount 150000` in Terminal.
