### ISSUE TITLE
Entry still present for removed remote

### ISSUE THREAD

**Issue by markshep** [ForkIssues/Tracker#1380]
With an instance of Fork running I removed a remote from the command line.  When returning to Fork all the branches under the removed remote disappeared, but the remote itself was still present in the list of remotes.  Please can you fix Fork so that it completely disappears?

**Comment by DanPristupov** [comment]
You can restart the application as a workaround.

**Comment by DanPristupov** [comment]
Probably it doesn't happen all the time. I couldn't reproduce it.
