### ISSUE TITLE
Crash when selecting an encrypted PDF in the list of changed files

### ISSUE THREAD

**Issue by noheger** [ForkIssues/Tracker#1386]
When the list of changed files contains an encrypted PDF, clicking on that file in the list causes Fork 2.7 to crash.

**Comment by DanPristupov** [comment]
How can I encrypt a PDF file?

**Comment by noheger** [comment]
For example in Preview.app. The Save dialog for PDFs provides an “Encrypt” option.

**Comment by DanPristupov** [comment]
OK, we don't have a time implementing custom preview for such file type, but will make Fork to not crash at least :).

**Comment by noheger** [comment]
I think making Fork not to crash with these files is more than sufficient :-)

**Comment by DanPristupov** [comment]
Could you check if the crash is fixed here, please?

https://cdn.fork.dev/prerelease/Fork-2.7.4.dmg

**Comment by noheger** [comment]
Yes, it no longer crashes with this version. It just shows a 0×0 px preview:

<img width="200" alt="encrypted-pdf" src="https://user-images.githubusercontent.com/42006266/119687461-864bc480-be47-11eb-8d12-27eba07af8e0.png">

**Comment by noheger** [comment]
Maybe you could show the file icon instead, just like with other files that cannot be previewed:

<img width="183" alt="heic" src="https://user-images.githubusercontent.com/42006266/119688321-2dc8f700-be48-11eb-9af0-f4292a9c5a32.png">
