### ISSUE TITLE
Can't change minor version in tag name

### ISSUE THREAD

**Issue by yauhenipakala** [ForkIssues/Tracker#1387]
<img width="526" alt="Screen Shot 2021-05-28 at 4 54 56 PM" src="https://user-images.githubusercontent.com/766193/119995021-da84af00-bfd5-11eb-93ee-5b36c0496077.png">

### Steps
- Put the cursor before or after minor version
- Try to remove number via backspace or delete buttons

### Expected
- Number will be remove

### Actual
- Nothing happens

### Workaround
- Put cursor before dot 0.8.|9 and use backspace

### Env:
OS: macOS Big Sur 11.2.3 (20D91)
Fork: 2.7

**Comment by DanPristupov** [comment]
Fixed in 2.46

**Comment by yauhenipakala** [comment]
Thanks, by the way, it works for me on 2.44.6
