### ISSUE TITLE
[feature request] workspace feature

### ISSUE THREAD

**Issue by RyuNen344** [ForkIssues/Tracker#1388]
Added workspace functionality similar to the mac version

**Comment by brightknight08** [comment]
any news or plans about this?

**Comment by JanPhill** [comment]
I love this functionality on the windows version and really miss it on mac as well!

**Comment by DanPristupov** [comment]
We implemented workspaces in Fork for mac 2.26. Please check for updates.

**Comment by RyuNen344** [comment]
@DanPristupov 
thank you very much!! It helps me so much, I love this feature!!!!
