### ISSUE TITLE
Cannot open git repos after updating into BigSur.

### ISSUE THREAD

**Issue by tangible-idea** [ForkIssues/Tracker#1389]
Cannot open git repos after updating into BigSur.
![image](https://user-images.githubusercontent.com/4496005/120062926-834b1100-c09f-11eb-9199-2a880f63d2e3.png)
![image](https://user-images.githubusercontent.com/4496005/120062942-9fe74900-c09f-11eb-81b8-33989b14143e.png)

**Comment by DanPristupov** [comment]
Most likely you switched Fork to a custom git instance which is not available on the new machine (brew?)

**Comment by tangible-idea** [comment]
Duplicated of : https://github.com/fork-dev/Tracker/issues/1390
