### ISSUE TITLE
Git status shows no changes but Fork shows a long list of modified files

### ISSUE THREAD

**Issue by valba8** [ForkIssues/Tracker#139]
After some changes and branches created by hand, now If I do a "git status" in my folder I get 

```
$ git status
On branch low_power
nothing to commit, working tree clean
```
but Forks shows a list of changes of 98 files where all the files are changed from the first line to the last:
![screen shot 2017-10-23 at 11 58 36](https://user-images.githubusercontent.com/6358242/31883364-f6a3e0c2-b7e9-11e7-9f5f-2d1f2f9557de.png)

The actual situation is the one showed by `git status`, I've no changes in this branch.

**Comment by DanPristupov** [comment]
Are you using the latest Fork version? I have fixed a similar case in 1.0.57.6 release.

Right now you can restart Fork and that will solve the problem. If you are able to reproduce this problem again, please tell me more details.

**Comment by valba8** [comment]
Yes, I'm using 1.0.57.6. I tried restarting the app but the issue keeps showing. If I discard the changes then the problem seems to be solved, but with this discard also are discarded any other changes in the files.  

Also, I found a list of steps to reproduce this issue (or something very similar):

1. I have two branches, `master` and `low_power`. Branch `low_power` is 2 commits ahead master. I made a checkout to both of them a discarded any "ghost" change in the files.
2. I'm in master branch in Fork.
3. I make a `git checkout low_power` and automatically in Fork the ghost list appears.

I think this is the first time I see this error, so I guess it has its roots in some action I made previously, but I don't think I did anything strange....

**Comment by DanPristupov** [comment]
Investigating the problem right now.

Could you please run `git status --porcelain --untracked-files=all` in terminal? Does it show any file?

**Comment by DanPristupov** [comment]
I see. You said that all files are changed from the first line to the last. Probably the end-of-line symbol has changed. Do you edit your files on both windows and unix?

**Comment by valba8** [comment]
@DanPristupov probably that is the problem, the repository is inside a windows vm and although I only edit the files in Windows, maybe something like that is happening. I tried to set autocrlf=true without success, maybe I have to change some old file with an incorrect end-of-line symbol or something.

I'll keep working with this repository and Fork and I'll comment any advance with this issue.

**Comment by DanPristupov** [comment]
I suppose this can be closed.
