### ISSUE TITLE
Update error...

### ISSUE THREAD

**Issue by tangible-idea** [ForkIssues/Tracker#1390]
![image](https://user-images.githubusercontent.com/4496005/120097492-af33c880-c16b-11eb-9e82-fe118edba20c.png)

**Comment by DanPristupov** [comment]
Can you download the file directly? https://cdn.fork.dev/mac/Fork-2.8.dmg

**Comment by tangible-idea** [comment]
> Can you download the file directly? https://cdn.fork.dev/mac/Fork-2.8.dmg
![image](https://user-images.githubusercontent.com/4496005/120098406-b90bfa80-c170-11eb-8503-b0fba74716a9.png)
Image not recognized.

It seems something wrong with my Fork like this error: https://github.com/fork-dev/Tracker/issues/1389
How can I delete all cache that Fork is using?
I have already tried removing Fork app and re-instaling from the website(https://git-fork.com/) several times.

**Comment by tangible-idea** [comment]
It was not a problem from Fork. This article was helpful to me: https://stackoverflow.com/a/52522566/6754906
