### ISSUE TITLE
The `git-lfs` binary doesn't include Apple Silicon slice

### ISSUE THREAD

**Issue by igor-makarov** [ForkIssues/Tracker#1391]
While trying to perform regular actions, such as pulling, Fork invokes `git-lfs`. It always uses the binary that's bundled with it, even when the Apple git is selected in Preferences.

The error is:
```
git-lfs filter-process: /Applications/Fork.app/Contents/Resources/git-instance/git-lfs/git-lfs: Bad CPU type in executable
```

I've also verified and this is the output of `file`:
```
$ file /Applications/Fork.app/Contents/Resources/git-instance/git-lfs/git-lfs
/Applications/Fork.app/Contents/Resources/git-instance/git-lfs/git-lfs: Mach-O 64-bit executable x86_64
```

Thanks, and keep up the good work!

**Comment by ferben** [comment]
Vote for git-lfs Apple Silicon native support. Thank you.

**Comment by tied** [comment]
I also run into this issue. Would be great if this could be fixed.

Kind Regards,
Tim

**Comment by DanPristupov** [comment]
I've made a build with the GitLFS 3.0.2 (universal binary, x86 + M1). Could you check if it works properly on your computers?

The build can be downloaded here: https://cdn.fork.dev/prerelease/Fork-2.15.12.dmg

If everything is OK, we will make it part of the Fork 2.16 update.

**Comment by igor-makarov** [comment]
Looks like it's working and supports Apple Silicon! 👍🏻

**Comment by tied** [comment]
Works for me as well 👍

**Comment by drlukas6** [comment]
Works! 👍

**Comment by domagojb** [comment]
Works for me as well. Thanks!
