### ISSUE TITLE
Extreme slowdown when switching to the app or after performing any action with a particular repo

### ISSUE THREAD

**Issue by Noleli** [ForkIssues/Tracker#1393]
Hi, I’m a huge fan of Fork, use it all the time.

I have one particular repo that is extremely slow any time I do anything or when I bring the app into focus. If what `Stopwatch` is outputting is ms, you can see it often takes over a minute, sometimes 90 seconds before it finishes refreshing.

```
 (
 )\ )                  )
(()/(         (     ( /(    Fork 2.7
 /(_))   (    )(    )\())   Git: internal
(_))_|   )\  (()\  ((_)\    Update Channel: stable
| |_    ((_)  ((_) | |(_)
| __|  / _ \ | '_| | / /       https://fork.dev
|_|    \___/ |_|   |_\_\

---

🔷[RefreshRepositoryCommand.swift:87] > RefreshRepository canceled
◽️[Stopwatch.swift:42] >  48810 GetRepositoryStatusGitCommand
🔷[RefreshRepositoryCommand.swift:87] > RefreshRepository canceled
◽️[Stopwatch.swift:42] >  94832 GetRepositoryStatusGitCommand
🔷[RefreshRepositoryCommand.swift:186] > Refresh 'xxxxxxx' status. Updated (5 files).
◽️[Stopwatch.swift:42] >  17588 RefreshRepositoryDataGitCommand
◽️[Stopwatch.swift:42] >  100437 GetRepositoryStatusGitCommand
🔷[RefreshRepositoryCommand.swift:186] > Refresh 'xxxxxxx' status. Updated (5 files).
◽️[Stopwatch.swift:42] >  27698 RefreshRepositoryDataGitCommand
◽️[Stopwatch.swift:42] >  78946 GetRepositoryStatusGitCommand
🔷[RefreshRepositoryCommand.swift:186] > Refresh 'xxxxxxx' status. Updated (5 files).
◽️[Stopwatch.swift:42] >  9966 RefreshRepositoryDataGitCommand
◽️[Stopwatch.swift:42] >  91129 GetRepositoryStatusGitCommand
🔷[RefreshRepositoryCommand.swift:186] > Refresh 'xxxxxxx' status. Updated (5 files).
◽️[Stopwatch.swift:42] >  20095 RefreshRepositoryDataGitCommand
```

Happy to provide any info that could help resolve the issue. Thanks!

**Comment by DanPristupov** [comment]
Hi.

What is the result of the following commands?

```
du -hs .
time git status --porcelain --untracked-files=all > /dev/null
time git for-each-ref > /dev/null
```

**Comment by Noleli** [comment]
Thanks, I just checked these. I’m afraid the issue is related to the repo being on a mounted smb share from a local virtual machine (the repo needs to live on a linux box for the build environment).

## From the virtual machine

```
$ du - hs
12G

$ time git status --porcelain --untracked-files=all > /dev/null
real	0m0.076s
user	0m0.056s
sys	0m0.020s

$ time git for-each-ref > /dev/null
real	0m0.419s
user	0m0.000s
sys	0m0.055s
```

## From the host Mac

```
$ du -hs .
 72G

$ time git status --porcelain --untracked-files=all > /dev/null
real	0m11.592s
user	0m0.135s
sys	0m0.761s

$ time git for-each-ref > /dev/null
real	0m2.017s
user	0m0.023s
sys	0m0.757s
```

I’m most confused by why `du` is reporting different sizes in the two environments. Aside from that, clearly running in the network share on the host Mac is a couple orders of magnitude slower than on the VM.

Unless you can think of a work-around, it seems to me that the only solution is for Fork to be able to connect via SSH to a remote machine and treat that SSH session as “local”. I suspect that’s a pretty niche use case. Thanks for your help!

**Comment by Noleli** [comment]
This turned into a duplicate of #929.
