### ISSUE TITLE
MacOS Cant rename branch when changing capitalization 

### ISSUE THREAD

**Issue by MichielHeusinkveld** [ForkIssues/Tracker#1394]
When trying to rename the branch from for example foo-42 to FOO-42 the rename button will not become active.
Work around: Add or remove a character rename it and then rename it again removing or adding the character and change the capitalization.

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/Tracker/issues/1297

**Comment by MichielHeusinkveld** [comment]
My bad, forgot to search closed issues.
