### ISSUE TITLE
Support of signed-off-by git commit -s Option

### ISSUE THREAD

**Issue by mapau** [ForkIssues/Tracker#1396]
Would be great if you can support the git commit -s option to set the signed-off-by line automatically.
https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s

**Comment by DanPristupov** [comment]
Repository -> Settings for this repository -> GPG
Repository -> Settings for this repository -> General: 'Add signed-off-by line'

**Comment by mapau** [comment]
Oh .. thanks .. didn't find it there.

**Comment by mike-lischke** [comment]
For those coming here to find this solution: the "Add Signed-off-by line" setting is now on the  Commit tab.
