### ISSUE TITLE
"show xxx branch commits only" not work in Mac

### ISSUE THREAD

**Issue by RobinWuu** [ForkIssues/Tracker#1399]
Hi, thank you for such useful tool firstly. 
After upgrade fork version, I found that when I click A branch’s filter("show xxx branch commits only") button, it not only show A branch’s commits, but also show other branch’s commits. In the past, it’s  the feature command+click do.  
But now, there is not difference between click branch filter button or command+click branch filter button.

**Comment by DanPristupov** [comment]
Can you show a screenshot with both sidebar filter and the commit list, please?

>  In the past, it’s the feature command+click do.

I think, it never worked this way.

> But now, there is not difference between click branch filter button or command+click branch filter button.

Some time ago Cmd+Click allowed to set filter on multiple branches at the same time. Now the filter button works as checkbox and Cmd is not needed. However, the filter logic hasn't changed for a long time.

**Comment by mcgitty** [comment]
@RobinWuu You don't need to press the Cmd key at all. Each branch's "V" filter icon is a toggle -- click once to select, click again to unselect. This way you can select any subset of branches.
