### ISSUE TITLE
Option to sort branches alphabetically

### ISSUE THREAD

**Issue by clounie** [ForkIssues/Tracker#14]
When your team starts getting a lot of branches (my situation currently), an option to sort them alphabetically in the left menu would be great.

**Comment by DanPristupov** [comment]
What menu are you talking about? The sidebar? Branches on the sidebar are sorted alphabetically (to be precise, in natural sort order). The only exception is the master branch which is always first.

P.S. I'm going to introduce quick filter for the sidebar items soon. It will make work with branches in projects like yours more handy.

**Comment by clounie** [comment]
^filter would be fantastic.

Oh, I see. master is first but everything else is natural sort order. I can see the reasoning for that...but maybe a "primary branch" or "pinned branches" system would be better? 

That way you have a section of frequently/currently used branches, and then below it the full tree with all branches in natural sort order.
