### ISSUE TITLE
[Feature Request] Commit and push changes to origin

### ISSUE THREAD

**Issue by pawelkondraciuk** [ForkIssues/Tracker#140]
I am a former SourceTree user but I love Fork much more. I miss "Push changes to origin" during committing changes.
![drawing](https://user-images.githubusercontent.com/7136191/31945515-b4bb4a4c-b8cf-11e7-8ac8-6d0cfb889513.png)

**Comment by DanPristupov** [comment]
Hi,

Press Alt or enable this option in preferences. More info here https://github.com/ForkIssues/Tracker/issues/77 and there https://github.com/ForkIssues/Tracker/issues/47

**Comment by pawelkondraciuk** [comment]
This is definitely hidden feature
