### ISSUE TITLE
Commit hash search is not working as expected

### ISSUE THREAD

**Issue by raymondctc** [ForkIssues/Tracker#1402]
Commits are not being shown in the search result, while it does exist (as highlighted on the right hand side)
<img width="755" alt="image" src="https://user-images.githubusercontent.com/13764117/122499212-159d5f80-d023-11eb-9b4a-4b6e117a2688.png">

Version 2.8

**Comment by DanPristupov** [comment]
Hi. You can use context search in the commit list  (Cmd+F) to search by SHA.

**Comment by raymondctc** [comment]
Thanks, closing
