### ISSUE TITLE
Cropped "close" icon in preview window (opened by spacebar)

### ISSUE THREAD

**Issue by zelenomodrypes** [ForkIssues/Tracker#1409]
<img width="440" alt="Screenshot 2021-06-28 at 12 57 34" src="https://user-images.githubusercontent.com/755065/123626044-ad176500-d810-11eb-8d6b-1f20ca63ce60.png">

Fork version: 2.9.3
macOS version: 11.3.1

**Comment by DanPristupov** [comment]
Fixed in 2.11
