### ISSUE TITLE
Sort order preference is not applied immediately

### ISSUE THREAD

**Issue by znek** [ForkIssues/Tracker#141]
Ideally, this shouldn't be a global preference but a view setting. Depending on what I have to do (reviewing vs. committing) I frequently need to toggle between sort orders (repo is large and we have several concurrent branchs).

Granted, restarting Fork and working on a large repository is very fast so this isn't a showstopper.

**Comment by DanPristupov** [comment]
@znek yes, confirm. I forgot to refresh the revision list after the preference change. Going to fix in the next update.
Thank you.

**Comment by DanPristupov** [comment]
This is fixed in the latest 1.0.58.3
