### ISSUE TITLE
No longer possible to fetch from private GitHub repository

### ISSUE THREAD

**Issue by brechtm** [ForkIssues/Tracker#1410]
After upgrading to 2.9.3, I can no longer fetch from a private repository on GitHub.

Dialog:
> **Git Error**
> An unexpected error occurred while performing the git request.
> Error Details:
> ```
> remote: Repository not found.
> fatal: repository 'https://github.com/*****/*****.git/' not found
> error: Could not fetch origin
> ```

Fork console:
```
🔷> Refresh '*****' status. Updated (14 files).
◽️> *****: askPasswdRequest
◽️> Url doesn't contain credentials
◽️> Asked for username for 'https://github.com'.
◽️> Checking if user logged into github.com...
◽️> Using https authentication for 'github.com'
◽️> Using oauth login
◽️> *****: askPasswdRequest
◽️> Url contains credentials
◽️> Url contains username only
◽️> Using https authentication for 'github.com'
⚠️> Git error 'fetch --prune --tags --all --verbose --progress':
remote: Repository not found.
fatal: repository 'https://github.com/*****/*****.git/' not found
error: Could not fetch origin

❌> gitUnknownError(output: "", error: "remote: Repository not found.\nfatal: repository \'https://github.com/*****/*****.git/\' not found\nerror: Could not fetch origin\n")
```

This is using Fork's git instance. After switching to the git instance provided by Homebrew (2.32.0), I can fetch (after allowing Fork access to the keychain).

Possibly related to #1397:
- `/usr/local/etc/gitconfig` sets `credential.helper = osxkeychain`. Removing it doesn't make a difference for the Fork git instance, but it does result in the same error when using the Homebrew git instance. 
- I do have my GitHub set up in Fork's Accounts, though it does not show this particular private repository in the list of repositories (it is owned by an organization - the organization is managed by my user account).
- _Configure SSH Keys_ crashes Fork

**Comment by DanPristupov** [comment]
> I do have my GitHub set up in Fork's Accounts, though it does not show this particular private repository in the list of repositories (it is owned by an organization - the organization is managed by my user account).


Does Fork have access to the organization here? https://github.com/settings/connections/applications/166b00df5e7ea4f78d4b

**Comment by brechtm** [comment]
> Does Fork have access to the organization here?

It does now, and that fixes the issue. Thanks!

Of course, it would be good if Fork could give this feedback to the user.

**Comment by DanPristupov** [comment]
> it would be good if Fork could give this feedback to the user.

As you see, GitHub doesn't give a clear message about the problem, so it's difficult to recognize that case

**Comment by brechtm** [comment]
I suppose you could check using the GitHub API, but that's quite some extra work...
