### ISSUE TITLE
Diff content search doesn't show the first match

### ISSUE THREAD

**Issue by xlebushkin89** [ForkIssues/Tracker#1411]
Hi, thank you for this awesome client!

## Description
There seems to be an issue with diff content search ("Search commits" in the left panel -> Diff Content). There are no results for some search strings.

Fork version 2.9.3, macOS.

## Steps to reproduce

1. Clone https://github.com/xlebushkin89/forktest2
2. Try to search for `SomethingThatINeedToFindReallyBad`, `ReallyBad`, `MoreMore` or `enum`

It's working for `public` though.

Thanks!

**Comment by DanPristupov** [comment]
Thank you for reporting this. I've reproduced the problem. It will be fixed in 2.10.

**Comment by DanPristupov** [comment]
Fork 2.10 is released.
