### ISSUE TITLE
Commits per weekday, start of week

### ISSUE THREAD

**Issue by qqilihq** [ForkIssues/Tracker#1412]
This is really a minor one, but I just spotted (Version 2.9.3, macOs 11.3.1 (20E241)) …:

![image](https://user-images.githubusercontent.com/2172260/124008007-3f1f9900-d9dc-11eb-8ff9-9441daf13753.png)

I've come to accept the weird opinion that weeks start on Sunday, but starting on Tuesday is still new to me 🙂 

(Or does this display depend on **current** day? Screenshot was taken on a Wednesday)

**Comment by DanPristupov** [comment]
Thank you for the bug report. The problem has been fixed in 2.10.

**Comment by qqilihq** [comment]
Thank you! :-)
