### ISSUE TITLE
Unstaged files view options feedback

### ISSUE THREAD

**Issue by titonobre** [ForkIssues/Tracker#1413]
Hi.

The view options on the unstaged files area seem to have a minor bug.

I call "view options" to the options on the dropdown under the button with four lines on the top right of the unstaged files area.

Despite the errors mentioned below, the behaviour of these options seems correct.

**Use Case 1**

To Reproduce:
1. Open Local Changes
2. Click on the view options
3. Click on the option "Show Ignored Files"

Expected:
- The option "Show Ignored Files" gets selected with a checkmark

Actual Result:
- The option "Hide Untracked Files" gets selected with a checkmark

**Use Case 2**

To Reproduce:
1. Open Local Changes
2. Click on the view options
3. Click on the option "Hide Untracked Files"

Expected:
- The option "Hide Untracked Files" gets selected with a checkmark

Actual Result:
- No option gets selected with a checkmark

My Environment
- OS: Mac OS
- Fork Version: 2.9.3

https://user-images.githubusercontent.com/7109082/124026800-08e91600-d9ea-11eb-80ec-17b9ef53700e.mov

**Comment by DanPristupov** [comment]
Fixed in 2.10. Thank you for reporting the problem.
