### ISSUE TITLE
push all tags checkbox 

### ISSUE THREAD

**Issue by mauroat22** [ForkIssues/Tracker#1417]
if user marks "push all tags" checkbox in the Push alert, and then "Cancel", then the  "push all tags" checkbox is marked with the previous value. so the only way to update the "push all tags" checkbox is by performing a Push. 

IMO It would be nice to mark/unmark this value without pushing.

**Comment by DanPristupov** [comment]
The dialog remembers the last performed action. It's absolutely logical, I think.
