### ISSUE TITLE
[Keyboard Shortcut] Discard Changes not working with CMD+Shift+D

### ISSUE THREAD

**Issue by brwolfgang** [ForkIssues/Tracker#1420]
Hello, I would like to report that as of version 2.9.3 on MacOS BigSur the keyboard shortcut for Discard Changes (CMD+Shift+D) is not working anymore, I can confirm that the shortcut "Delete" works ok, though.

**Comment by DanPristupov** [comment]
We didn't change them recently and Cmd+Shift+D still works for me.

Try to restart Fork or computer. Also try to close the other applications which may steal the key combination.

**Comment by brwolfgang** [comment]
Yeah I've spotted DEVONthink misbehaving.

For posterity sake: DEVONthink Sorter (the capture icon on menubar) silently steals this keyboard shortcut and it cannot be customized. As far as I know the only way to get CMD+Shift+D back is deactivating this by going to DEVONthink Preferences -> Sorter -> Appearance: none.
