### ISSUE TITLE
[bug] Find in local changes diff pane switches to all commits if search field already open

### ISSUE THREAD

**Issue by olets** [ForkIssues/Tracker#1428]
Expected: in the Local Changes diff pane, <kbd>cmd f</kbd> always focuses the search field as it does in the All Commits diff pane.

Actual: in the Local Changes diff pane, <kbd>cmd f</kbd> activates the All Commits view if the search field is already open

1. Introduce a local change
1. Select the Local Changes view
1. Focus the diff pane
2. <kbd>cmd f</kbd> 
2. <kbd>cmd f</kbd>

See that the All Commits view is now active

**Comment by olets** [comment]
Re: https://github.com/fork-dev/Tracker/issues/1427#issuecomment-904512663

2.11.5 changes the behavior. Now it's: <kbd>cmd f</kbd> from the Local Changes diff pane when the "find field" is visible opens and focuses the file pane "filter" field, and <kbd>cmd f</kbd> from the file pane when the "filter" field is open beeps.

1. Introduce a local change
2. Select the Local Changes view
3. Focus the diff pane
4. <kbd>cmd f</kbd> 
5. <kbd>cmd f</kbd>

See that the file pane's "filter" field is visible and focused.

6. <kbd>cmd f</kbd>

Hear a beep.

---

My expectation is that <kbd>cmd f</kbd> always works like #1427. If the diff pane is active you go to the "find" field, if the file pane is active you go to the "filter" field.

Or maybe it's useful to move from the "find" field to the "filter" field? I don't know.

This might all be in the scope of #1427, close this ticket if you want to!

**Comment by DanPristupov** [comment]
> Or maybe it's useful to move from the "find" field to the "filter" field? I don't know.

No, honestly, I don't think it's useful :).

I've improved the behavior to not jump to the 'All commit' view if you accidentally press `⌘f` twice, but I can't make it work as you'd originally expected (i.e. beep at the `5.` step) without spending much time. The search field within the text view is built-in and It's difficult to control the behavior in it.

**Comment by olets** [comment]
Cool! Yeah I expect no beep but if Apple wants a beep I guess we get a beep!
