### ISSUE TITLE
History browser view doesn't honor the "Show scroll bars" system preference setting

### ISSUE THREAD

**Issue by znek** [ForkIssues/Tracker#143]
<img width="800" alt="scrollbar_issue" src="https://user-images.githubusercontent.com/1011745/32046603-d90e656c-ba43-11e7-83ad-1645942e7417.png">

As can be seen here, the vertical scrollbar is not shown (indicated by the row selection, drawing its selection background up to the window border) despite the system preference demanding otherwise.

*NOTE*: The setting was active before Fork was running (and I never changed it while Fork was running)

**Comment by DanPristupov** [comment]
@znek I fixed that problem in 1.0.60.
