### ISSUE TITLE
[feature request] visually distinguish between tabs and spaces in diff viewer.

### ISSUE THREAD

**Issue by qdolan** [ForkIssues/Tracker#1430]
Many editors allow for tabs to be visualised using a pale '⇥' or '―' symbol for each tab. Such a symbol would be helpful in the diff viewer to determine what kind of white space has been used, particularly when there are whitespace only changes.

**Comment by DanPristupov** [comment]
<img width="401" alt="Screenshot 2021-07-30 at 08 45 28" src="https://user-images.githubusercontent.com/618115/127612244-7687e517-4225-4f96-8cfc-560e8beafa89.png">
<img width="172" alt="Screenshot 2021-07-30 at 08 45 55" src="https://user-images.githubusercontent.com/618115/127612291-78c30dd2-9bc7-4757-9e83-333c622fb40f.png">

**Comment by qdolan** [comment]
Carry on.. nothing to see here.

Thank you good sir.
