### ISSUE TITLE
Automatic fetching of remotes no longer seems to work

### ISSUE THREAD

**Issue by DanielSWolf** [ForkIssues/Tracker#1432]
In the past, Fork would automatically fetch the latest changes from remote repos. The commit graph it displayed was always up-to-date, even if I didn't explicitly fetch changes.

For some time now, this seems to be broken: I repeatedly missed changes pushed to the remote repo by colleagues because Fork wouldn't auto-fetch, even after several days.

The appropriate option is set: 
![image](https://user-images.githubusercontent.com/5963162/128301067-5735f7f2-0d8f-4792-8390-639aa1bf2506.png)

I'm using Fork 2.10 on macOS 10.15.7.

**Comment by DanPristupov** [comment]
1. Open the activity manager (the left-bottom button in the status control on the toolbar). Do you see fetch requests there?
<img width="700" alt="Screenshot 2021-08-05 at 09 35 45" src="https://user-images.githubusercontent.com/618115/128310544-43dc6f29-c5a2-408e-a308-3a20dc63419c.png">

2. Ensure that the automatic fetch is not disabled for the particular remote.
<img width="220" alt="Screenshot 2021-08-05 at 09 33 52" src="https://user-images.githubusercontent.com/618115/128310301-ff217435-2494-4f3d-809f-3931c206b739.png">

**Comment by DanielSWolf** [comment]
Right now, it's working again, without changing anything. Seems to be an occasional hiccup rather than a deterministic bug.

If I notice this behavior again, is there anything I can do to help you identify the cause?

**Comment by DanPristupov** [comment]
> If I notice this behavior again, is there anything I can do to help you identify the cause?

Check the log file at `~/Library/Logs/Fork.log`. It must have a message for each automatic fetch operation.
