### ISSUE TITLE
[feature request]: Hitting enter in search should scroll back to first search result

### ISSUE THREAD

**Issue by benwoodward** [ForkIssues/Tracker#1433]
Currently if your searched commit(s) is out of view, the only way to bring it back into view via the search bar is to clear the search input and then type/paste in your search again. It'd be great if you could just hit enter in the search bar to bring the first search result commit back to the top.

**Comment by DanPristupov** [comment]
Do you mean the context search (Cmd+F)?

> It'd be great if you could just hit enter in the search bar to bring the first search result commit back to the top.

I just checked, it works that way for me.
