### ISSUE TITLE
No author name in new Blame window (Mac version)

### ISSUE THREAD

**Issue by Viciousu** [ForkIssues/Tracker#1436]
Now author's name is not showing in blame window.
Is it intended?

![image](https://user-images.githubusercontent.com/4673120/128706960-76220d56-89b6-431c-ad93-896a459da6ac.png)

**Comment by DanPristupov** [comment]
Yes, we changed the layout, which I think is more informative. Now we show avatar + sha + commit message instead of author.

**Comment by Viciousu** [comment]
Maybe it's possible to show author's name in tooltip on mouseover?

Now you have to do right click -> Reveal in Fork to see the author, and then Blame window closes and should be reopened, that is really slows down the process.

**Comment by DanPristupov** [comment]
> Maybe it's possible to show author's name in tooltip on mouseover?

This is a good point.
