### ISSUE TITLE
[feature request]: file cherry pick / checkout

### ISSUE THREAD

**Issue by Andrew-Au** [ForkIssues/Tracker#1437]
Implement 'git checkout <commit> /path/to/file'

Suggested mechanism:
* select changeset
* in commit / changes / file tree view, right click on a file
* choose "checkout this file" from right click menu (_new option_)

Result: above 'git' command is executed.  File in working directory is updated to the specified version.

#####

It would also be really useful to be able to apply the _changes_ to a single file.  Currently, one can do this by cherry-picking (no commit), then deleting all the unwanted file changes.  It should be possible for fork to use diff to generate a patch for the single file and then apply the patch to the working directory.

Essentially: git diff <commit> -- /path/to/file | git apply

**Comment by DanPristupov** [comment]
> Implement 'git checkout /path/to/file'

It's in the file context menu and called 'Reset file to state at commit'

**Comment by Andrew-Au** [comment]
Maybe I didn't explain correctly, but I don't think this is the quite same operation as I am talking about.

I believe we are both thinking of 'git checkout [<tree-ish>] -- [<pathspec...>]'

However, as far as I can tell, the "reset file to" command only applies to a file shown in "changes" (but allows me to checkout either the that revision or the parent).

If I select an arbitrary commit, expand the file tree, and right click, I don't get the option to reset the particular file.  In other words, it looks to me that the ability to check out a file is restricted to a commit that changed the file (changes pane) rather than any commit (file tree pane).

**Comment by maliayas** [comment]
@Andrew-Au As a workaround, you can go to File Tree tab, right click your file and select "Save as...". Fork will then automatically offer to save that file in the same location. Using this trick you can overwrite existing file, thus it means a checkout.

__Cherry pick__ as mentioned in the title is however different. With that, you want to cherry-pick only the modifications you see in the diff, not the whole file. You can achieve that with a custom command:

- Type: File custom command
- Name: Cherry-pick Diff
- Code: `${git} show ${sha} -- ${file} | git apply`

You can even go further and define a revert command:

- Type: File custom command
- Name: Revert Diff
- Code: `${git} show ${sha} -- ${file} | git apply --reverse`

Now go to a commit's Changes tab and right click a file to use these custom commands.
