### ISSUE TITLE
[Feature] Toggle branch/tag labels between full and short (in commit list)

### ISSUE THREAD

**Issue by svoop** [ForkIssues/Tracker#1440]
Since branch/tag labels are rendered in front of the commit message, expressive branch names tend to push the commit message out of view:

<img width="677" alt="Screen Shot 2021-08-11 at 19 21 50" src="https://user-images.githubusercontent.com/7255/129077092-a8c03a68-d3f2-44b8-9fc4-1cab640b69a1.png">

In addition to these useful but long branch/tag labels, it would be totally awesome to have short branch/tag labels e.g. like so:

<img width="677" alt="Screen Shot 2021-08-11 at 19 21 50 altered" src="https://user-images.githubusercontent.com/7255/129079131-3e99a695-00b3-4f71-92cf-1d8901d258ab.png">

Clicking any label anywhere in the commit list would toggle between the short and long view. Optionally, to save extra space, identical short branch/tag labels would be rendered only once (e.g. when a merge commit refers to several local branches).

Such an addition might solve other feature requests as well such as #1365 and #637. Thanks for giving it a thought or two over a 🍺 (or two).

**Comment by DanPristupov** [comment]
> Optionally, to save extra space, identical short branch/tag labels would be rendered only once (e.g. when a merge commit refers to several local branches).

In the Windows version we collapse the remote tracking branch when both local and the remote branch are on the same commit.

Do you mean something like this?

<img width="400" alt="Screenshot 2021-08-11 at 20 16 42" src="https://user-images.githubusercontent.com/618115/129081903-983c6534-af62-4ec3-9a27-7833c33c3063.png">

**Comment by svoop** [comment]
This approach looks nice at first, but comes with two gotchas IMO:

* It saves some space, but probably not enough on smaller MacBook screens with expressive branch names in "folders". 
* It's somewhat confusing, even more so if you chose to rename your local tracking branch e.g. because the remote branch has a poorly chosen name you're not allowed to change.

Toggling between just showing there are branches/tags (short with no text) and the current, full branch/tag labels does away with this for good. Essentially, you toggle the focus between branches/tags and the commit message.

**Comment by svoop** [comment]
Cool, much better already. In fact, no need to go any further I guess:

![image](https://user-images.githubusercontent.com/7255/174557224-6a0628ff-6098-4a86-ac62-79627dd0d400.png)

Thanks so much for this addition!!

**Comment by DanPristupov** [comment]
Yes, it's a nice feature.

It takes some time to get used to the new mental model. Instead of thinking 'the corresponding remote branch is also here' we think 'it is up to date' (which is what we usually want to know) .
