### ISSUE TITLE
File list in combined mode doesn't show filenames with colon

### ISSUE THREAD

**Issue by erwinw** [ForkIssues/Tracker#1442]
There's an interesting issue in the changes view in the view mode 'combined list' only. Any files with a colon (`:`) in the name show, but the name is not visible:

![Listing of one file with a colon in the name staged, and one unstaged](https://user-images.githubusercontent.com/54856303/129172396-f7d3d002-de52-45ff-bae2-0225cf29d372.png)

(In this screenshot there's one file with a colon in the name staged (`w:q`) and one not staged (`:wq` - guess how I discovered this issue).

Related bonus issues:
- Trying to _stage_ or _unstage_ a file whose name _starts_ with a colon (like `:wq`) using the `stage` / `unstage` buttons triggers a `fatal: pathspec ':wq' did not match any files` error. This is the same error I encounter when running `git add ':wq'` on the command line; escaping the colon (`git add '\:wq'`) does work
- Staging/unstaging a file whose name _starts_ with a colon (like `:wq`) using drag-and-drop works - but the file does not show up in the list until I refresh the list (for example by hitting `⌘ + R`)

**Comment by DanPristupov** [comment]
I'm investigating.

**Comment by DanPristupov** [comment]
That's funny. I think I found the problem. Using URL parser for file paths is usually fine, but not always :).

Can you try if that build works properly? https://cdn.fork.dev/prerelease/Fork-2.10.13.dmg

**Comment by alfreedom** [comment]
Same problem using cookiecutter file name syntax:
Files with names like {{ XXX }} are not displayed in **View as combined list**

![image](https://user-images.githubusercontent.com/6258387/129927554-88ec9cb0-0e8b-4578-8a58-dce20b7100f6.png)

In **View as list** works well

![image](https://user-images.githubusercontent.com/6258387/129927680-46959e12-7cf7-4290-bc86-f3d928426eff.png)

**Comment by DanPristupov** [comment]
Fixed in 2.11
