### ISSUE TITLE
In Fork 1.38 you can see tag messages in tooltips:

### ISSUE THREAD

**Issue by NickPenney** [ForkIssues/Tracker#1447]
I am using fork 2.10 for OSX and this does not appear to be functioning properly.
---
In Fork 1.38 you can see tag messages in tooltips:

<img width="220" alt="Screenshot 2019-08-16 at 17 11 14" src="https://user-images.githubusercontent.com/618115/63177743-dc6fbf00-c048-11e9-94e6-f171a7cd5b3d.png">

_Originally posted by @DanPristupov in https://github.com/fork-dev/TrackerWin/issues/270#issuecomment-522044075_

**Comment by DanPristupov** [comment]
<img width="350" alt="Screenshot 2021-08-19 at 16 12 34" src="https://user-images.githubusercontent.com/618115/130083920-1fb260d2-27be-457c-8db3-fdfe7ebc6dec.png">

**Comment by NickPenney** [comment]
Ah ok, thank you!
