### ISSUE TITLE
Multiple Bitbucket Accounts - Access Token expiry

### ISSUE THREAD

**Issue by JoGoFo-** [ForkIssues/Tracker#1448]
Since adding a second Bitbucket account, Fork does not seem to be properly refreshing access tokens. I can successfully remove and re-add accounts, but after a period of time they both start receiving an error on any remote operation (e.g. Fetch). When I go back to Accounts I'm presented with the following error next to Status:

```Bitbucket error: Access token expired. Use your refresh token to obtain a new access token.```

Both accounts are setup via OAuth. Having removed one of the accounts, it seems to be functioning correctly again (will monitor). Seems to be an issue with supporting two oauth accounts simultaneously?

MacOS 11.4 (Silicon)
Fork 2.10

**Edit**
I seem to be having the same issue again several hours later with only a single Bitbucket account setup. Setup with OAuth via Google. Maybe this is a Bitbucket issue?

**Comment by DanPristupov** [comment]
Thank you for reporting that.

> Maybe this is a Bitbucket issue?

Not sure yet, I will investigate.

**Comment by DanPristupov** [comment]
I'd like to notice that I haven't changed that code since the initial implementation.

Did you try to restart the computer. It may happen that KeyChain access got globally blocked, which happens sometimes.

**Comment by firetrap** [comment]
I'm having the same issue. It started to happen with a fresh MacOS install.
Fork for MacOS - Version 2.11.3.

Maybe bitbucket changed something in theirs Oauth??!

PS: I've only a single account

**Comment by DanPristupov** [comment]
@firetrap Does the problem occur after computer restart?

Do you see `fork:https://bitbucket.org.username.accesstoken` entry in KeyChain Access?

**Comment by firetrap** [comment]
> @firetrap Does the problem occur after computer restart?
> 
> Do you see `fork:https://bitbucket.org.username.accesstoken` entry in KeyChain Access?

No i don't think it's related with restart. My 2 coins are: keychain problem on my side or breaking changes in oAuth method by bitbucket. I'm gone do some more research and give you feedback.

**Comment by firetrap** [comment]
I've checked the keychain and everything seems fine. The entry is present in keychain and it's accessible by fork app.
![Screenshot 2021-09-01 at 22 38 17](https://user-images.githubusercontent.com/655828/131748789-715f6330-0bad-43b9-85be-5a0d7e0526b6.png)

I'm running MacOs Big Sur 11.5.2 (20G95). 
By the way this only happens after the token expires. Maybe something changed with the refreshToken?
Right now i'm trying with AppPassword to see if it happens

**Comment by firetrap** [comment]
I can confirm this is not happening with AppPassword auth.

**Comment by DanPristupov** [comment]
@firetrap would you be interested in trying a debug build with additional logging, which will help to find out why the problem occurs for you?

**Comment by firetrap** [comment]
> @firetrap would you be interested in trying a debug build with additional logging, which will help to find out why the problem occurs for you?

Yes, i can do in the weekend ;). Just to clarify i've developing background so i can help you with that. Send me a build with verbose logs ative and i will send you the logs.

**Comment by DanPristupov** [comment]
I think I've reproduced the problem. Can you try if it's solved in that build, please? https://cdn.fork.dev/prerelease/Fork-2.11.16.dmg

**Comment by firetrap** [comment]
> I think I've reproduced the problem. Can you try if it's solved in that build, please? https://cdn.fork.dev/prerelease/Fork-2.11.16.dmg

Can i update from the older version or you need a clean install?

**Comment by DanPristupov** [comment]
You can run it right from the dmg file.

**Comment by firetrap** [comment]
Done, the problem only happens a few hours after logging in, so tomorrow i will tell you something.

**Comment by firetrap** [comment]
Tested and everything went well. I think the issue is solved in that last release.
