### ISSUE TITLE
Relative dates (i.e. in history view)

### ISSUE THREAD

**Issue by znek** [ForkIssues/Tracker#145]
It would be nice to have (optional) relative date display (even better: custom formatting) for dates in the history browser, i.e.:

<img width="325" alt="relative_dates_example" src="https://user-images.githubusercontent.com/1011745/32047461-48082a78-ba46-11e7-87a0-885da2d40310.png">

Left: *Fork*
Right: *SourceTree*

**Comment by DanPristupov** [comment]
Hi. Yes, I agree. Going to improve this.
