### ISSUE TITLE
Application crashes after opening and click on a gray area somewhere in the window after update to 2.11

### ISSUE THREAD

**Issue by miracuruzrh** [ForkIssues/Tracker#1451]
Hi

I have updated "Git Fork" on my macOS from v2.10 to v2.11.
v2.10 was stable.
v2.11 crashes as soon as I click on a grey area on the window where is no text.
The affected area is only when I'm on "All commits" in the right section where all the commits are visible.
And when there is no text. Just below the first commit.
See marked in red the area on the screenshot. 

No other areas are affectes as far as I checked.

I have also attached a crash report which macOS has generated.

[Fork_Crashlog.txt](https://github.com/fork-dev/Tracker/files/7071335/Fork_Crashlog.txt)

![image](https://user-images.githubusercontent.com/44341190/131229105-d52c7252-35a9-47cd-8aab-77414d122266.png)

**Comment by DanPristupov** [comment]
Hi!

I didn't believe first, but you are absolutely right 👍. It's almost night here in Europe, so I will release the hotfix in the morning.

Thank you very much for reporting that.

**Comment by miracuruzrh** [comment]
Hi Dan

Many thanks for looking into this.
No hurry. It's also almost midnight in Switzerland here. And it's weekend :-)

**Comment by DanPristupov** [comment]
I've just released the 2.11.1 hotfix.

Once again, thank you very much for the bug report.

**Comment by miracuruzrh** [comment]
Thank you for the update and have a good day.
