### ISSUE TITLE
Creating GitHub Enterprise account opens GitLab Server dialog

### ISSUE THREAD

**Issue by Kozoft** [ForkIssues/Tracker#1456]
After pressing Log In button with GitHub Enterprise selected in Add Account dialog (Accounts menu item) new account dialog opens with GitLab Server settings for the new account instead of GitHub Enterprise.

<img width="903" alt="Screenshot 2021-08-31 at 13 12 53" src="https://user-images.githubusercontent.com/30182230/131485050-21fbe812-7f52-4656-82cb-dd3f282fc624.png">

**Comment by DanPristupov** [comment]
May be I'm missing something, but on your screenshot the `GitHub Enterprise` dialog is opened.

**Comment by Kozoft** [comment]
Right, but Server field displays GitLab icon and after clicking Sign In button the Fork presents error 404 with .../api/v3/user status message which I believe is GitLab-related. Cannot add GitHub Enterprise account this way.
<img width="897" alt="Screenshot 2021-08-31 at 15 11 52" src="https://user-images.githubusercontent.com/30182230/131500362-403e52a4-328b-44df-8221-b7ed578e6ed0.png">

**Comment by DanPristupov** [comment]
> Server field displays GitLab icon

It's just an icon.

> after clicking Sign In button the Fork presents error 404 with .../api/v3/user status message which I believe is GitLab-related. 

The GitHub [documentation](https://docs.github.com/en/enterprise-server@3.1/rest/guides/getting-started-with-the-rest-api) says it's correct:
> Use `https://[hostname]/api/v3` to access the API for **GitHub Enterprise Server**.


> Cannot add GitHub Enterprise account this way.

I guess, the problem is that there are two `//` in the path. Try to remove the trailing slash in the url

**Comment by Kozoft** [comment]
Oh, right. GitHub Enterprise Server is really works this way, my bad. I'm trying to add GH Enterprise Cloud account which hosts on GitHub.com and should be added as regular GH account apparently. Sorry for bothering you.

**Comment by DanPristupov** [comment]
We will fix the incorrect icon in the next update :)
