### ISSUE TITLE
Default button in Pull dialog is now labeled "Submit" instead of "Pull"

### ISSUE THREAD

**Issue by noheger** [ForkIssues/Tracker#1462]
In version 2.11.2 the title of the default button in the Pull dialog has been renamed from "Pull" to "Submit", whereas the default button of similar dialogs (Fetch, Push, Merge, Apply Stash) still shows the actual name of the action that will be performed (Fetch, Push, etc.).

I find the "Submit" button title quite irritating, and would ask to change it back to "Pull".

<img width="589" alt="Pull Dialog" src="https://user-images.githubusercontent.com/42006266/132022500-b27d6da2-9b6f-4cdd-b7c6-4fc330b6eec2.png">

<img width="612" alt="Push Dialog" src="https://user-images.githubusercontent.com/42006266/132022542-a89c2518-b9b9-4c01-aef5-03841ac73917.png">

<img width="583" alt="Fetch Dialog" src="https://user-images.githubusercontent.com/42006266/132022573-e43dbb9a-07c5-4812-9e43-3a90e3869c0c.png">

**Comment by DanPristupov** [comment]
Hi. Thank you for the bug report.

**Comment by DanPristupov** [comment]
Fixed in 2.12
