### ISSUE TITLE
Changes count not reseting

### ISSUE THREAD

**Issue by aonez** [ForkIssues/Tracker#147]
Reported [via Twitter](https://twitter.com/aonez/status/922764630568718337).

The counter increments correctly, but It does not drop when a commit is done. Can't see any log relating to this issue.

- On a machine I got this issue and after updating and rolling back it's no more present.
- On my primary machine I've created a test repository and now I have no counter at all:

![screen shot 2017-10-26 at 12 46 49](https://user-images.githubusercontent.com/480163/32049053-d847e696-ba4b-11e7-864f-bf0c1134020a.png)

Reproduced in OS X 10.11.6 and macOS 10.13. From 1.0.57.6 to 1.0.58.2.

**Comment by DanPristupov** [comment]
A lot of people have reported this issue, but I still can't reproduce it. I'll continue investigating the problem.

Please share if you find more details.

**Comment by clounie** [comment]
I don't have a hard repro (yet), but from my experience it generally happens when I'm using the `git` CLI + using Fork at the same time.

**Comment by aonez** [comment]
@clounie in my case I only work with git CLI when Fork fails on a rebase or something involving too much changes. Usually I only use Fork, and the count fails to reset.

**Comment by bwl21** [comment]
I did a git gc on the command line, maybe this might help. Anyhow the changes counter is not really reliable. I even would prefer if the uncommitted changes would be visible the commit history (see my comment on #107)

**Comment by DanPristupov** [comment]
I'm finally back from the holidays and investigating this bug now.

@bwl21 I recently added additional logging related to this problem. You can really help me to fix it if you send me the log file which is located at `~/Library/Caches/Fork/fork.log` to support@git-fork.com. Thank you in advance.

**Comment by bwl21** [comment]
As a pity, the issue is still there in 1.0.65.1

**Comment by aonez** [comment]
> send me the log file which is located at ~/Library/Caches/Fork/fork.log to support@git-fork.com.

You still need those? I can send you mine too.

**Comment by aonez** [comment]
I can't even reproduce this with 1.0.71.2. So for my part you can close this. Hopping to see the day when we can support this project 💰

**Comment by bwl21** [comment]
as a pity I still have the issue in 1.0.72.1. In the following screenshot you see, there is a chage, but
in the "changes"
 
![screenshot_1271](https://user-images.githubusercontent.com/2022976/49338864-5b8ea580-f628-11e8-959a-132e8deb900a.jpg)

**Comment by aonez** [comment]
@bwl21 what OS do you use? Also, the repository is local/remote and on what hosting if the later?

**Comment by aonez** [comment]
By the way the buttons on your screenshot look funny.

![screen shot 2018-12-02 at 11 52 51](https://user-images.githubusercontent.com/480163/49338883-d6f05700-f628-11e8-8734-2eaf3fc0df86.png)

Do you use the old toolbar style or it is imposed for using an old OS?

**Comment by bwl21** [comment]
I am on el capitan. repository is hosted github.

**Comment by aonez** [comment]
@DanPristupov I was also working on an old Mac Mini with Mac OS X 10.11 El Capitan when reported this one. Now I can't reproduce but my minimum OS is 10.13. Will try to reproduce on a VM.

**Comment by bwl21** [comment]
> Do you use the old toolbar style or it is imposed for using an old OS?

i did not change the toolbar setting up to now, so it is the old style

**Comment by bwl21** [comment]
> Forgot this line of the first report. So the OS should no be the reason.

I tried with https://github.com/bwl21/react-jspdf-example. It still happens that the Counter is not updated.

![screenshot_1272](https://user-images.githubusercontent.com/2022976/49341003-a1a73180-f647-11e8-8082-8d14898be94f.jpg)

**Comment by bwl21** [comment]
sure. can it be installed in parallel?

**Comment by aonez** [comment]
If I can reproduce this again (not the case now) I'll for sure use the build with additional logging.

**Comment by DanPristupov** [comment]
OK, I'm investigating this problem right now.

> sure. can it be installed in parallel?

Yes, it won't require installation, you can run it right from the DMG file.

@aonez @aonez thank you! Please contact me by email (support@forkapp.io) so I could send you the build.
