### ISSUE TITLE
Use main repository name in submodule tabs

### ISSUE THREAD

**Issue by micka-fdz** [ForkIssues/Tracker#1474]
I think we should use custom name of main repository in submodule tabs instead of its folder name (like "Main repository > Submodule") ? It's sometimes hard to find your way around when several git repositories use the same folder name (like "www" in web projects).

**Comment by micka-fdz** [comment]
Hi @DanPristupov and @TanyaPristupova. Any news here? Still an issue...

**Comment by micka-fdz** [comment]
Hi @DanPristupov @TanyaPristupova, I would like to ask you once again for this improvement which I miss on a daily basis… Thanks in advance for your reply.

**Comment by DanPristupov** [comment]
Hi. Thank you for reminding!

The fix will be part of 2.33 update.

If you don't want to wait (you already waited too long), I made a special build for you: https://cdn.fork.dev/prerelease/Fork-2.32.1.dmg

**Comment by micka-fdz** [comment]
Thanks @DanPristupov for this news and this prerelease!

**Comment by micka-fdz** [comment]
Hi @DanPristupov, do you plan to add this feature to Windows version?

**Comment by DanPristupov** [comment]
Ah, yes!

Once again, thank you for reminding :)

**Comment by micka-fdz** [comment]
No problem @DanPristupov! I can now close this issue about Mac version.

**Comment by DanPristupov** [comment]
OK, I just checked, on Windows it's a bit more complicated. We'll definitely fix that, but not *right now*.

Please feel free to bump this issue in the future.

**Comment by micka-fdz** [comment]
Do you want me to open issue on [TrackerWin](https://github.com/fork-dev/TrackerWin/) repo?

**Comment by DanPristupov** [comment]
Yes, please 👍

**Comment by micka-fdz** [comment]
Done ✅
