### ISSUE TITLE
Unable to use Homebrew installed GPGTools on Apple Silicon Macs

### ISSUE THREAD

**Issue by tonyarnold** [ForkIssues/Tracker#1476]
Could you consider letting us select the GPG tools we want to use? 

Later versions of Homebrew are installed into `/opt/homebrew`, not `/usr/local` (all M1 Macs would have their Homebrew installations in the new location). 

Unfortunately, it seems like Fork might be hardcoded to only look in `/usr/local`?

_Originally posted by @tonyarnold in https://github.com/fork-dev/Tracker/issues/378#issuecomment-886322362_

**Comment by svoop** [comment]
Another possible approach: Shell out as the current user and fetch the location with `which gpg`. (The same would be possible for `git` as well.) This reduces the amount of preferences, however, I'd prefer an explicit and unrestricted filesystem chooser.

For now, there's a simple enough workaround for those with more recent Homebrew installs:

```
sudo ln -s /opt/homebrew/bin/gpg /usr/local/bin
```

**Comment by ssbarnea** [comment]
On M1 homebrew link would be `/opt/homebrew/bin/git` and Fork is unable to detect git on this location. Homebrew adopted this mothan an year ago but Fork was not updated.

**Comment by matheusamazonas** [comment]
Any updates on this? It seems like simply fetching gpg's path using `which` would be feasible.

**Comment by remcom** [comment]
@DanPristupov Any updates for this issue. Got my new MBP today and running into the same issue. Let me know what i can do to further debug this

**Comment by DanPristupov** [comment]
To be honest, I don't know how to solve that issue properly.

Where should Fork copy the cli-tool? Actually, should it copy it somewhere at all or it's a wrong approach? Shouldn't we just add fork-cli to `PATH` (`export PATH=$PATH:/Applications/Fork.app/Contents/Resources/`)?

**Comment by ssbarnea** [comment]
Lets look at what other popular apps are doing:
```
ls -la /opt/homebrew/bin/code
lrwxr-xr-x  1 ssbarnea  admin  68 Apr 13  2022 /opt/homebrew/bin/code -> /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code

ls -la /usr/local/bin/code
lrwxr-xr-x  1 ssbarnea  admin  68 Jul 27  2018 /usr/local/bin/code -> /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code

$ ls -la /usr/local/bin/bcomp
lrwxr-xr-x  1 ssbarnea  wheel  53 Mar 16  2022 /usr/local/bin/bcomp -> /Applications/Beyond Compare.app/Contents/MacOS/bcomp

$ ls -la /usr/local/bin/prlctl
lrwxr-xr-x  1 root  wheel  68 May 12  2022 /usr/local/bin/prlctl -> /Applications/Parallels Desktop.app/Contents/MacOS/parallels_wrapper
```

**Comment by DanPristupov** [comment]
Ouch, I just realized that I wrote to the wrong issue... I was looking for one about adding fork-cli-tool. Sorry for the off-topic

@ssbarnea thank you for the info! It's very helpful.

Anyway, since I'm here, I will have a look at the original issue with GPGTools and try to fix it.

**Comment by svoop** [comment]
@ssbarnea 

> On M1 homebrew link would be `/opt/homebrew/bin/git` and Fork is unable to detect git on this location. Homebrew adopted this mothan an year ago but Fork was not updated.

Which is why I'd suggest discovering the git binary with `which` as the current user. Homebrew adds itself into the PATH and if an advanced user changes the order there or removes it again (e.g. because you only need libs), then `which`ing would reflect this wish automatically.

**Comment by aonez** [comment]
I'm having this issue as well. Any workaround that does not involve installing `gnupg` and `pinentry-mac`?

Here the #258 workaround of manually installing GPG Tools does not fix the issue.

```sh
aone@aONe-Pro ~ % which gpg
/usr/local/bin/gpg
aone@aONe-Pro ~ % which gpg2
/usr/local/MacGPG2/bin/gpg2
```

<img width="538" alt="Screenshot 2023-03-25 at 12 48 35" src="https://user-images.githubusercontent.com/480163/227715716-6cfc29d0-284a-4358-94ac-b82975643545.png">

**Comment by DanPristupov** [comment]
@aonez just for a case someone else encounter the same problem. Try https://cdn.fork.dev/mac/Fork-2.27.1.dmg.
