### ISSUE TITLE
[Bug] Sorting commits by date is broken

### ISSUE THREAD

**Issue by devemlight** [ForkIssues/Tracker#1478]
Version 2.12

Sorting by date broke after the update.

![image](https://user-images.githubusercontent.com/45560785/134697544-e74f565b-d5f9-439f-bbbf-80b925a1e908.png)

**Comment by DanPristupov** [comment]
We didn't change the behavior in 2.12.

Most likely of one the commits on the screenshot was amended and the date you see is the original commit date.

Fork 2.11: https://cdn.fork.dev/mac/Fork-2.11.3.dmg

**Comment by devemlight** [comment]
Yeah, that's right.

It looks like these commits have been rebased and it displays their original date.

Thanks.
