### ISSUE TITLE
Support Kaleidoscope 3

### ISSUE THREAD

**Issue by infotexture** [ForkIssues/Tracker#1486]
A new version of [Kaleidoscope.app](https://kaleidoscope.app/) has been released, but Fork doesn't seem to recognize the new version. 🤔 

In Fork’s **Preferences**, the **Integration** tab allows you to select external diff & merge tools, but the **Kaleidoscope** entry in both dropdowns is dimmed, even though `/Applications/Kaleidoscope.app` exists. 

— Perhaps the bundle ID has changed, and maybe Fork is using that to find the installed apps?

Also, Kaleidoscope 3 has new [changeset support](https://kaleidoscope.app/#dev-changeset), but there doesn't seem to be any way to invoke that from the Fork UI, only right-click on individual files and **External Diff**.

💡 Would be great to be able to select commits in the timeline and call Kaleidoscope’s changeset view with all of the files that were modified in the commit or branch.

A custom command such as `git difftool $sha..$sha^1` can be used as a workaround, but this seems to open an extra dialog in Fork that says the custom command completed. Would be nice to just open the changeset in Kaleidoscope without the extra confirmation.

**Comment by DanPristupov** [comment]
Can you try if that version works? https://cdn.fork.dev/prerelease/Fork-2.12.10.dmg


> — Perhaps the bundle ID has changed, and maybe Fork is using that to find the installed apps?

Right, that seems to be correct.

> A custom command ... seems to open an extra dialog in Fork that says the custom command completed. Would be nice to just open the changeset in Kaleidoscope without the extra confirmation.

You can uncheck the 'show output' checkbox.

**Comment by infotexture** [comment]
> Can you try if that version works? https://cdn.fork.dev/prerelease/Fork-2.12.10.dmg

Yes, I now see both **Kaleidoscope2** and **Kaleidoscope3** entries in the list, and selecting **Kaleidoscope3** works as expected.

> > — Perhaps the bundle ID has changed, and maybe Fork is using that to find the installed apps?
> 
> Right, that seems to be correct.

[LittleSnitch](https://www.obdev.at/products/littlesnitch/) seems to confirm this theory:

> Previously, the program had the identifier "com.blackpixel.kaleidoscope", but
now it's "app.kaleidoscope.v3". 

Unchecking the **Show Output** checkbox in the Edit Action dialog prevents the extra confirmation from appearing. 
Sorry I missed that earlier.

**Comment by DanPristupov** [comment]
> selecting Kaleidoscope3 works as expected.

You can keep using that build. When the new version comes out it will be updated automatically without a problem.
