### ISSUE TITLE
Configure SSH Keys crashes app

### ISSUE THREAD

**Issue by jehanf** [ForkIssues/Tracker#1487]
The simple fact of going to Fork => "Configure SSH Keys..." makes Fork crash.

Here is a part of the report that is given to me : 
```Process:               Fork [36591]
Path:                  /Applications/Fork.app/Contents/MacOS/Fork
Identifier:            com.DanPristupov.Fork
Version:               2.12 (2.12)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Fork [36591]
User ID:               501

Date/Time:             2021-10-12 14:52:55.234 +0200
OS Version:            macOS 11.6 (20G165)
Report Version:        12
Bridge OS Version:     5.5 (18P4759a)
Anonymous UUID:        B6E7D9F3-7BD9-7023-FA96-3CCF2482D17D

Sleep/Wake UUID:       3E9468DE-DDAF-4817-A478-6FFB493D9F22

Time Awake Since Boot: 100000 seconds
Time Since Wake:       3900 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [36591]

Application Specific Information:
Performing @selector(showConfigureSshKeysSheet:) from sender NSMenuItem 0x600001e15e30
```

**Comment by DanPristupov** [comment]
Hi,

May be Fork crashes on parsing one of the public keys in the `~/.ssh` directory.

Does the log file `~/Library/Logs/Fork.log` contain any warnings or errors?

I will try to fix that in the next update, but you can check if you that directory has some non-open-SSH keys (or converted keys from some other formats).

**Comment by jehanf** [comment]
Hi,

No warnings or errors in the Fork.log file (I also tried to make the app crash to see if something would appear, but no).

What is it you call `non-open-SSH keys` ? All I can say at the moment is that all keys in there have been generated by OSX's native ssh-keygen.

**Comment by DanPristupov** [comment]
I've made a build with additional logging. Can you reproduce the problem in it and send the log file to support@fork.dev, please?

The log is located at ~/Library/Logs/Fork.log

You can redact the private info if needed.

https://cdn.fork.dev/prerelease/Fork-2.12.11.dmg

**Comment by jehanf** [comment]
@DanPristupov this build does not crash, it works perfectly fine.
