### ISSUE TITLE
Fork not detecting installed k3diff

### ISSUE THREAD

**Issue by ovisirius** [ForkIssues/Tracker#1489]
Fork (v 2.12) is not detecting kdiff3 as a merge or diff tool. It is installed in /Applications.
The kdiff3 version is this one: https://download.kde.org/stable/kdiff3/?C=M;O=D

**Comment by DanPristupov** [comment]
Hi. I'm glad to hear that KDiff is alive again :). We will have a look why the new version doesn't work.
