### ISSUE TITLE
git path as a symlink

### ISSUE THREAD

**Issue by ElfSundae** [ForkIssues/Tracker#149]
![image](https://user-images.githubusercontent.com/526008/32168138-5d04fda2-bd39-11e7-85ad-5b3d6a2de261.png)

I install git client using Homebrew, and I want Fork use it `/usr/local/bin/git` which is a symlink to "../Cellar/git/**{version}**/bin/git", but Fork use the real path, I need to update git path in Fork every time I upgrade git client.

**Comment by james-rabbit** [comment]
Agreed this would be nice. Duplicate of https://github.com/ForkIssues/Tracker/issues/116

**Comment by ElfSundae** [comment]
OK, close this
