### ISSUE TITLE
Unable to login to Bitbucket server when username contains '@'

### ISSUE THREAD

**Issue by speelplaats** [ForkIssues/Tracker#1492]
When trying to create an entry to a bitbucket server, it fails with notFound(url: https://bitbucket.dev.XXX/rest/api/1.0/users/XXX.XXX%2540XXX.XXX)
Our login ids are email addresses, and Bitbucket sends this back url encoded in the initial request:
x-ausername: XXX.XXX%40XXX.XXX
Fork then tries to use it, url encoding it again (%40 becomes %2540):
https://bitbucket.dev.XXX/rest/api/1.0/users/XXX.XXX%2540XXX.XXX

So it seems that the received name is not url decoded before it is being used, causing the @ symbol to be double url encoded

**Comment by DanPristupov** [comment]
Sorry for the delay. I will investigate that this week.

**Comment by DanPristupov** [comment]
> So it seems that the received name is not url decoded before it is being used, causing the @ symbol to be double url encoded

Weird, but decoding percents is not enough. You can see that on the profile page. `https://bitbucket.dev.xxx/users/super@email.com` is also wrong.

It seems that `@` character must also be replaced with `_`, i.e. `https://bitbucket.dev.xxx/users/super_email.com`. At least that's how it works at the instance I have. How does the url of your profile page look like?

I don't want to check what will happen when there are two usernames: `super@email.com` and `super_email.com` :).

**Comment by DanPristupov** [comment]
> I don't want to check what will happen when there are two usernames: `super@email.com` and `super_email.com` :).

OK, my curiosity won and I tried to create the collision. It seems that both 'user@domain.com' and 'user_domain.com' will be mapped to the same `https://bitbucket.dev.xxx/users/user_domain.com` page which always shows profile of 'user@domain.com'.

**Comment by speelplaats** [comment]
My url does indeed substitute the @ with a _ in the final url, and trying it in the rest/api/1.0/users url also works (%40 does indeed not work).
