### ISSUE TITLE
[Feature Request] Change to desired branch on double click 

### ISSUE THREAD

**Issue by jankowskib** [ForkIssues/Tracker#1497]
Hello, firstly thanks for a great git client! To be honest there is just one annoyance that keeps me from telling this is the best git client. When I double click on a branch label, I am not checkouted to the branch I clicked but to the first from the left. To change to desired branch I have to right click -> branch -> checkout. It'd be great If I could just double click on a label and switch branch/tag etc
![image](https://user-images.githubusercontent.com/1850243/140510731-eb329c11-9027-4d20-8845-e739df30a676.png)

**Comment by jankowskib** [comment]
Thank you so much for implementing this feature. Works great!

**Comment by DanPristupov** [comment]
Thank you very much for reporting it :).
