### ISSUE TITLE
fork for Mac v2.13 SSH viewer missing 'ssh-rsa' token

### ISSUE THREAD

**Issue by matkatmusic** [ForkIssues/Tracker#1502]
The windows version of Fork shows this: 
<img width="339" alt="Screen Shot 2021-11-11 at 1 05 05 AM" src="https://user-images.githubusercontent.com/2929847/141269630-329d02e8-e23a-4147-8550-228df2fb97e8.png">

The mac version of Fork does not. 
<img width="342" alt="Screen Shot 2021-11-11 at 1 05 21 AM" src="https://user-images.githubusercontent.com/2929847/141269658-2126bf77-2faa-43dd-b0d0-3e23533a0a98.png">

When uploading a key to BitBucket, BitBucket expects the `ssh-rsa` token at the top. 
Copying the key directly from Fork for Mac will result in BitBucket stating that an invalid key has been entered.

Copying the key from Fork for Windows does not have this issue. 

It's easy enough to insert `ssh-rsa` into the bitbucket text editor.  But for new users of SSH keys, forgetting this token can waste lots of time trying to figure out what is wrong with the key.

**Comment by mpalosuo** [comment]
The issue is still there in v2.14 - and also happens when copying ssh key to GitLab. Missing `ssh-rsa` results in GitLab stating it's an invalid key.
