### ISSUE TITLE
Improve hide icon on branches (low hanging fruit)

### ISSUE THREAD

**Issue by svoop** [ForkIssues/Tracker#1505]
I find the eye symbol in the branches sidebar quite confusing:

<img width="354" alt="Screenshot 2021-11-12 at 13 43 34" src="https://user-images.githubusercontent.com/7255/141469278-888b4bf5-44c4-4c1c-8845-c7e58460031d.png">

Currently, the eye symbol is used to signal whether commits for this branch are hidden (eye symbol highlighted in blue):

<img width="34" alt="Screenshot 2021-11-12 at 13 47 31" src="https://user-images.githubusercontent.com/7255/141469710-1a41cbed-818a-413c-a85a-da13d8338023.png">

IMO, an open eye is no match for "hide" and doesn't correspond to e.g. bitmap editors using similar symbols for layer visibility.

How about just using the opposite symbol which – at least for me – is much more self-explanatory:

<img width="40" alt="Screenshot 2021-11-12 at 13 47 47" src="https://user-images.githubusercontent.com/7255/141469906-06da4aab-bc1b-4ff4-9935-33d5ed256ed8.png">

This way, when commits for this branch are hidden (aka: not to be seen), the above symbol is highlighted.

What do you think?

**Comment by svoop** [comment]
@DanPristupov Any opinion on this one? I still find it very confusing, but maybe I'm misunderstanding this feature.

**Comment by DanPristupov** [comment]
Sorry for not answering in time.

> IMO, an open eye is no match for "hide" and doesn't correspond to e.g. bitmap editors using similar symbols for layer visibility.

We made it look like in Photoshop where open eye used to mean "hide layer". I'm not sure if it's the same in the new versions, though.

![](https://i.stack.imgur.com/J0V4T.gif)

What bitmap editors did you mean? Can you show some screenshots?

**Comment by svoop** [comment]
I understand the current implementation as follows:

* open eye symbol in black: commits for this branch are shown
* open eye symbol highlighted in blue: commits for this branch are hidden

All of the below is based on this understanding. If I'm wrong, then all of the below is just meaningless noise. :smile:

---

> We made it look like in Photoshop where open eye used to mean "hide layer"

Actually, the [open eye means "show layer" in Photoshop](https://photoshopcafe.com/tutorials/layers/intro.htm):

> visibility: If the eye is showing that layer is visible. Click on the eye and the layer will still be there but invisible until you click on the eye again.

The presence (aka: highlight) of the eye symbol therefore has the opposite meaning of that in Fork.

Consequently, to make the way Fork highlights semantically work, the eye has to be struck through.

However, to make it 100% clear, a combination of highlighting and toggling the symbol might be best:

<table>
<tr><td><img width="34" alt="141469710-1a41cbed-818a-413c-a85a-da13d8338023" src="https://user-images.githubusercontent.com/7255/148684021-7f47fe08-c182-4003-b6ef-3050de94bbb8.png">
</td><td>commits for this branch are **shown**</td></tr>
<tr><td><img width="40" alt="141469906-06da4aab-bc1b-4ff4-9935-33d5ed256ed8" src="https://user-images.githubusercontent.com/7255/148684031-0dd55095-80a2-4067-b428-1534b4914d29.png"></td><td>commits for this branch are **hidden**</td></tr>
</table>

**Comment by svoop** [comment]
Thanks a bunch for implementing this, @DanPristupov !!
