### ISSUE TITLE
[Feature Request] Add preference to only "folder-ize" branch names when sensible

### ISSUE THREAD

**Issue by benspaulding** [ForkIssues/Tracker#1508]
When a branch name has a `/` (slash) in it the UI treats it like a folder. I have used Fork for *years* (maybe even *all* the years) and this has always been the right thing to do.

But a team I work with now organizes their branches differently than the `git-flow`-ish ways of `feature/DEV-123-add-whizbang`. They use `DEV-123/add-whizbang`. It makes a lot of sense for their workflow, but in Fork this means that there is virtually always only a single `DEV-123/` branch, but I always have to open it and it takes up a lot of room in the sidebar.

<img width="370" alt="Example of single-item 'folders' in Fork sidebar." src="https://user-images.githubusercontent.com/21705/142053666-b624ddcc-f752-4967-b5f3-82ede563dd93.png">

Would it be possible to have a preference to not "folder-ize" branch names when there is only single branch with that name?

Then these:
```
▾ Branches
    ✓ main
  ▸ dev-123
  ▸ dev-234
  ▸ dev-345
  ▸ dev-456
  ▸ wip
```
```
▾ Branches
    ✓ main
  ▾ dev-123
      add-whizbang
  ▾ dev-234
      remove-whatsit
  ▾ dev-345
      refactor-spam
  ▾ dev-456
      add-nifty-tests
  ▾ wip
      some-thing
      another-thing
```

Could just be this:
```
▾ Branches
    ✓ main
      dev-123/add-whizbang
      dev-234/remove-whatsit
      dev-345/refactor-spam
      dev-456/add-nifty-tests
  ▾ wip
      some-thing
      another-thing
```

*Thanks for all your work on Fork!*

**Comment by DanPristupov** [comment]
> When a branch name has a `/` (slash) in it the UI treats it like a folder.

Not (only) UI, but the file system!

Please read my explanation here:
https://github.com/fork-dev/TrackerWin/issues/1169#issuecomment-840569023

**Comment by benspaulding** [comment]
Haha, I combed open and closed issues to be sure this was not already asked, but still I missed it!

Thanks for the response and the explanation. But I don't see how that precludes implementing something like this — the Fork UI _exists_ to give us a nicer interface than the file system. 😁

Please close this ticket (or not!) as you see fit. Thanks!
