### ISSUE TITLE
Problems in the local changes when aborting an edit interactive rebase

### ISSUE THREAD

**Issue by hico17** [ForkIssues/Tracker#1510]
Every time I try to do an `edit interactive rebase` (right-click on commit -> interactive rebase -> edit) and I abort the rebase, the app shows me in the staged files changes that **are not true**. It should show me a clear view (like the one I see before starting the rebase) but instead, it shows me files with changes, probably from old commits (?).

The problem is that these files **are not really changed**, it just shows them on staged files. If I try to check on other Git Clients, there are no changes on these files.
Another problem is that If you try to discard these invented changes, the app let you do that, but this way it actually changes the files (indeed checking on other Git Clients now I see files with changes).

The only two ways I've found to solve this problem are:
1. Avoid aborting when rebasing
2. If you have to abort the rebase, do it. Then discard the changes on files it shows you in staged files (actually doing this instead it applies some changes...) and then change the branch in order to let the app ask you if you want to discard your changes and then click on discard.

**Comment by DanPristupov** [comment]
Can you write steps to reproduce that?
Is it possible that the changes you see are caused by the enabled 'Amend' mode?

**Comment by hico17** [comment]
Ok, it's for the "amend" mode! Sorry, I haven't seen it!
