### ISSUE TITLE
missing macos menubar?

### ISSUE THREAD

**Issue by ehagerty** [ForkIssues/Tracker#1516]
Forgive me if I'm being an idiot, but the product website suggests that there is a menubar icon for Fork on macos, but I'm a bit lost as to how I'm supposed to enable it?  Thanks so much for any pointers.
<img width="1152" alt="Screenshot 2021-11-25 at 15 43 13" src="https://user-images.githubusercontent.com/982973/144069345-1bb13f5c-1d8a-40b0-87ba-db402f433333.png">

**Comment by DanPristupov** [comment]
Hi.

Fork -> Accounts -> + -> GitHub. Then the notification icon will appear automatically.

**Comment by ehagerty** [comment]
@DanPristupov thank you so much, i'm sorry for being a thicko!
