### ISSUE TITLE
Adding remote via clipboard does not trim whitespace from URL

### ISSUE THREAD

**Issue by rhys-vdw** [ForkIssues/Tracker#1518]
Repro:

1. Copy remote URL including leading whitespace and trailing newline
2. Add new remote, prepopulating from clipboard
3. New remote adds successfully but is not shown in UI (presumably due to error)
4. Fetching remote via CLI results in an error due to invalid URL (e.g. `Invalid protocol ' https'`)

**Comment by DanPristupov** [comment]
Thank for for reporting that. It's been a long time ago, but we finally improved the behavior in Fork 2.28 :)
