### ISSUE TITLE
Highlighted (found) words remain visible on another view

### ISSUE THREAD

**Issue by MatkovIvan** [ForkIssues/Tracker#1524]
Hi there 👋 

It's just a minor visual bug: highlighted (found) words remain visible on another view (see attached screenshots).

Reproduction steps:
1. In "All Commits" view, select some changes (commit/file)
2. Try to find something in diff
3. Switch to "Local Changes" view

| All Commits | Local Changes |
| --- | --- |
| <img width="378" alt="Screenshot 2021-12-09 at 10 56 52" src="https://user-images.githubusercontent.com/1836384/145357843-cc2a36b0-e7c3-403f-b191-955bd85673c7.png"> | <img width="378" alt="Screenshot 2021-12-09 at 10 57 00" src="https://user-images.githubusercontent.com/1836384/145357854-67a7ecc6-94ad-4c24-903f-e67357a3495a.png"> |

Version: 2.11.3

PS Thanks for great git client!

**Comment by DanPristupov** [comment]
I couldn't find a solution for that :(. The inline search in the text control seems to not be customizable in any way.

https://github.com/fork-dev/Tracker/issues/821

**Comment by MatkovIvan** [comment]
Okay... Thanks for your answer.
Closing it as duplicate than.
