### ISSUE TITLE
"Fork" needs to be updated warning.

### ISSUE THREAD

**Issue by jespertheend** [ForkIssues/Tracker#1527]
Upon committing my first commit right after upgrading to macOS Monterey I got a pop up that said something like `"Fork" needs to be updated, please contact the developer`. However, subsequent commits do not give me this warning.
Not sure what is going on here.

**Comment by jespertheend** [comment]
I got another similar pop up, though not from Fork this time, but the message looked the same would apply here as well.
This time I clicked the learn more button and got sent to https://www.python.org/doc/sunset-python-2/

**Comment by DanPristupov** [comment]
I didn't receive any other reports about that problem. It would be great to see a screenshot at least.

**Comment by jespertheend** [comment]
Unfortunately it only happened once :(
I'm not sure exactly what I was doing, but I have a pre-commit hook setup so it could very well be that python2 was being used in there somewhere.

**Comment by jklausa** [comment]
I've run into it too, and in my case guess by @jespertheend was correct — it was due to a pre-commit hook I have that's using python2 (`git-format-stage` in my case; it worked fine when I just changed the requested `env` to `python3`).

**Comment by DanPristupov** [comment]
Well, sometimes macOS warnings are weird and misleading :).

**Comment by jespertheend** [comment]
I'm pretty sure the same was the case for me then. I've seen similar notifications for vscode as well.
