### ISSUE TITLE
Add force-with-lease to push options

### ISSUE THREAD

**Issue by Vloeck** [ForkIssues/Tracker#1531]
`git push --force-with-lease` is a "safer" way to force push, is it possible to add this to the push dialog?

**Comment by DanPristupov** [comment]
It's always `--force-with-lease`

**Comment by Vloeck** [comment]
Is it possible to show this in the UI?

**Comment by DanPristupov** [comment]
You can see that in the tooltip:

<img width="300" alt="Screenshot 2021-12-16 at 13 59 24" src="https://user-images.githubusercontent.com/618115/146376481-7cc410c7-7a0b-4bfa-8102-28c17c41a696.png">

And in the command output:
<img width="551" alt="Screenshot 2021-12-16 at 13 59 01" src="https://user-images.githubusercontent.com/618115/146376429-bfc9a464-f4bc-4506-9547-a70a5c13cc3b.png">

**Comment by Vloeck** [comment]
I have never actually waited for tool tips, but now it makes sense.
