### ISSUE TITLE
Subject allows pasting of multiline text, but only displays last line

### ISSUE THREAD

**Issue by mitchcohen** [ForkIssues/Tracker#1535]
Let's say I copy this text from a Jira web browser window:
>ABCD-1234
>Add Some Crazy New Feature

and paste this into the Subject field, the Subject field only displays:
>Add Some Crazy New Feature

It isn't apparent, but the first line _is_ in the field, but one has to arrow-key around to see it.

My suggestion for a fix is to replace any pasted newline characters with a space.  Expanding the Subject field to hold multiple lines is an option (just not a good one in my opinion).  Truncating to just the first line might be valid too.

**Comment by DanPristupov** [comment]
This was fixed at some point.
<img width="239" alt="Screenshot 2024-02-15 at 10 41 00" src="https://github.com/fork-dev/Tracker/assets/618115/3824871a-9439-4360-b3be-b4b6892392f0">
