### ISSUE TITLE
UI rendering artifact

### ISSUE THREAD

**Issue by yauhenipakala** [ForkIssues/Tracker#1538]
<img width="275" alt="Screen Shot 2022-01-05 at 1 59 59 PM" src="https://user-images.githubusercontent.com/766193/148209136-274e0c74-111f-49c2-96f4-4d4655a05adb.png">

Steps:
- open Fork in Fullscreen
- click "local changes"
- click "all commits"
- try again or in a different sequence

Actual:
- "line" artifact

Fork 2.12
macOS 12.1 (21C52)

**Comment by yauhenipakala** [comment]
<img width="264" alt="Screen Shot 2022-01-05 at 2 22 46 PM" src="https://user-images.githubusercontent.com/766193/148209902-a4f29585-00cb-4fb5-9c8e-e6566a17f7ea.png">

Steps:
- open Fork in Fullscreen
- try to discard local changes
- displays OS confirmation dialog
- Fork UI has an overlay as on screenshot

**Comment by DanPristupov** [comment]
Looks like a bug in macOS.
BTW, I can't reproduce the issue with the line on `macOS 12.1 (21C52)`. Did you try to restart the computer?

**Comment by yauhenipakala** [comment]
Thanks, restart was helpful 🙃
