### ISSUE TITLE
Credentials not fetched from keychain for usernames with symbols

### ISSUE THREAD

**Issue by jespertheend** [ForkIssues/Tracker#154]
Today I had an issue while trying to pull commits from a repository with lfs support.
Fork kept giving me the username and password dialogs, for every file it had to fetch. And since there were a lot of lfs files, it took way too long to actually finish. So I ended up force quitting fork (since there was no way to abort) and using `git pull` on the command line.

Not sure if this is actually what was going on, all I know for sure is that the username/password dialog kept appearing, I'm assuming it was doing it for each lfs file since the lfs server log showed a different /objects/<hash> every time I entered my username and password.

**Comment by DanPristupov** [comment]
@jespertheend what Fork version are you using?
Did you check "Remember credentials in KeyChain" checkbox?

**Comment by jespertheend** [comment]
@DanPristupov I'm using fork 1.0.58.3
I did try checking the "Remember in Keychain" checkbox, but even then a new dialog pops up with the checkbox unchecked.
When I open Keychain Access I do see my entry with username, password and domain stored in keychain. So storing the credentials isn't the issue.

**Comment by DanPristupov** [comment]
@jespertheend Fork uses keychain entries which looks like `Fork.%host%.https` (more information here https://github.com/ForkIssues/Tracker/issues/142).

Some people facing same issue while others don't. It would be great if you could you send your Fork log file (~/Library/Caches/Fork/fork.log) to support@git-fork.com? It will help me to investigate the problem. Thank you in advance.

**Comment by jespertheend** [comment]
@DanPristupov I figured it out, it was because I had a questionmark in my username. I noticed how the keychain entry from fork was outdated and just some random user name I typed to test if it was working. So I suppose if a username contains a question mark it doesn't get stored in keychain.

Do you still need my log file?

**Comment by DanPristupov** [comment]
@jespertheend so, did you resolve the problem? Does Fork remember the password now?

**Comment by jespertheend** [comment]
Yes, it's now properly adding the username and password to the keychain.
It's not an issue for me, but I'm not sure if not being able to have a question mark in your username counts as a bug.

**Comment by DanPristupov** [comment]
@jespertheend glad to hear you managed to make it work.

Regarding the question mark. Yes, I do consider this as a bug and going to fix it in the next release. If it's possible, please could you send me your username privately to support@git-fork.com, so I could ensure that I understand the problem properly.

P.S. I will rename the issue title correspondingly.

**Comment by DanPristupov** [comment]
@jespertheend I fixed the bug in 1.0.59.3 (https://github.com/ForkIssues/Tracker/issues/152).

**Comment by jespertheend** [comment]
@DanPristupov Hmm, this doesn't seem to be fixed for me. In fact, usernames without symbols are now not working anymore either. When I open Keychain Access and right click the fork entry, and then click the 'show password' checkbox, it switches back off immediately and I am unable to see the stored password, so I feel like the entry is corrupt or something.

The weird thing is though, at some point during the lfs pull, I only kept getting dialogs for entering my username. No password dialogs, so it does seem to remember them.

The git log shows this a bunch of times:
```
🔅[main] [AskPassController.swift:17] windowDidLoad() > AskPassRequest:
/Applications/Fork.app/Contents/Resources/fork_askpasswd
Username for 'https://example.com:8080': 
🔅[main] [AskPassController.swift:17] windowDidLoad() > AskPassRequest:
/Applications/Fork.app/Contents/Resources/fork_askpasswd
Password for 'https://example.com:8080': 
🔅[main] [ShowAskPassSheetCommand.swift:54] loadKeychainCredentials(_:askPassProcessId:) > Asked for username for 'https://example.com:8080'.
📢[main] [KeychainManager.swift:73] getUsernames(host:authenticationType:) > Asking available usernames for 'Fork.example.com.https'
🔅[main] [ShowAskPassSheetCommand.swift:80] loadKeychainCredentials(_:askPassProcessId:) > Found 0 accounts for example.com.
🔅[main] [ShowAskPassSheetCommand.swift:88] loadKeychainCredentials(_:askPassProcessId:) > Could not found account for 'example.com'.
🔅[main] [AskPassController.swift:17] windowDidLoad() > AskPassRequest:
/Applications/Fork.app/Contents/Resources/fork_askpasswd
Username for 'https://example.com:8080': 
🔅[main] [AskPassController.swift:17] windowDidLoad() > AskPassRequest:
/Applications/Fork.app/Contents/Resources/fork_askpasswd
Password for 'https://example.com:8080': 
🔅[main] [ShowAskPassSheetCommand.swift:54] loadKeychainCredentials(_:askPassProcessId:) > Asked for username for 'https://example.com:8080'.
📢[main] [KeychainManager.swift:73] getUsernames(host:authenticationType:) > Asking available usernames for 'Fork.example.com.https'
🔅[main] [ShowAskPassSheetCommand.swift:80] loadKeychainCredentials(_:askPassProcessId:) > Found 0 accounts for example.com.
🔅[main] [ShowAskPassSheetCommand.swift:88] loadKeychainCredentials(_:askPassProcessId:) > Could not found account for 'example.com'.
🔅[main] [AskPassController.swift:17] windowDidLoad() > AskPassRequest:
/Applications/Fork.app/Contents/Resources/fork_askpasswd
Username for 'https://example.com:8080': 
🔅[main] [AskPassController.swift:17] windowDidLoad() > AskPassRequest:
/Applications/Fork.app/Contents/Resources/fork_askpasswd
Password for 'https://example.com:8080': 
```

Let me know if you need any more info.

**Comment by DanPristupov** [comment]
@jespertheend sorry for the delay, it took some time to understand what causes the problem and how to handle it. I made a lot of changes to the existing code and all url cases should work properly now.
The updated build is here: https://git-fork.com/update/files/Fork-1.0.59.4.dmg. it's going to be the release version.

**Comment by jespertheend** [comment]
@DanPristupov Thank you very much! That does indeed seem to be working.
