### ISSUE TITLE
No version of git accepted as valid

### ISSUE THREAD

**Issue by iconara** [ForkIssues/Tracker#1542]
I've had Fork installed on my Mac for a while, but haven't used it. Now I decided to give it another try, launched it, but it wouldn't accept any repository as valid. When I look in the preferences it doesn't seem to find any git, and when I try to point it to my various versions of git I have on my machine (Homebrew, the one bundled with Fork, the one in /Developer) none of them are accepted as valid.

The first version I tried was v2.11.3 and then I upgraded to v2.15.1. I'm using macOS 11.6.1, but I probably had 11.5.x when I installed Fork.

Here's the git preferences panel, as you can see it doesn't show any version of git:

<img width="551" alt="fork1" src="https://user-images.githubusercontent.com/73330/149816762-a3f0ec40-1aad-4836-ab39-4b2e5e1f8040.png">

And here's what happens when I navigate to the version installed by Homebrew (git 2.34.1), the same happens for any other version I try:

<img width="796" alt="fork2" src="https://user-images.githubusercontent.com/73330/149816806-36ff5ffe-1cad-4870-823b-1b311efcd411.png">

**Comment by DanPristupov** [comment]
Hi!

Try to erase the settings by running `defaults delete com.DanPristupov.Fork` in terminal.

**Comment by iconara** [comment]
Thank you for the fast reply! Unfortunately that did not fix the issue. Is there any way to completely wipe the installation and start from scratch? I've tried trashing the app and `~/Library/Application Support/Fork` (I should have said this in my initial report), but it didn't work.

**Comment by DanPristupov** [comment]
> Is there any way to completely wipe the installation and start from scratch?

`defaults delete com.DanPristupov.Fork` and also remove `~/Library/Application Support/com.danpristupov.fork`.

Check the log file `~/Library/Logs/Fork.log`. It must contain details about the problem.

**Comment by iconara** [comment]
Aha! I found the problem. Fork does not work if `~/.gitconfig` is a symlink.

I found this message in the logs:

```
⚠️[GitRequest.swift:704] > Shell error /usr/local/bin/git 'version':
fatal: unable to access '/Users/theo/.gitconfig': Operation not permitted
```

and I realised my `~/.gitconfig` is a symlink. I changed it to a hard link and now Fork works!

Why is my `~/.gitconfig` a symlink? I keep my dotfiles in another location so I can version control them (which is inconvenient when they are in my home directory).

**Comment by DanPristupov** [comment]
> Aha! I found the problem. Fork does not work if `~/.gitconfig` is a symlink.
> fatal: unable to access '/Users/theo/.gitconfig': Operation not permitted

It's not Fork. Fork doesn't work with configs manually. That message comes from git, which is weird.

Does `git version` work properly in CLI??

**Comment by iconara** [comment]
I might have found the root cause, finally: Fork did not have permissions to the Documents folder in System Preferences. 

I've had this setup for years, and I haven't noticed any problems with it when using git tools before. I use `git` on the command line almost daily, and I've used a couple of different git UIs from time to time.

I changed it back to a symlink to try again. Fork stops working, but `git` works fine:

```
$ ln -fs /Users/theo/Documents/dotfiles/git/gitconfig /Users/theo/.gitconfig
$ ls -al ~ | grep .gitconfig
lrwxr-xr-x    1 theo  staff       44 Jan 18 09:53 .gitconfig -> /Users/theo/Documents/dotfiles/git/gitconfig
$ git config user.name
Theo
```

To debug I tried making `~/.gitconfig` a symlink to a file on my desktop instead. When I opened Fork it asked for permissions to use the Desktop folder, which I gave. Fork worked as expected. That made me think that at some point Fork might have asked for permissions and I had declined.

I checked Security & Privacy in System Preferences, and I saw that Documents was unchecked in the Files and Folders settings for Fork. After checking Documents and restarting Fork things now work.

What I don't understand at this point is how Fork was able to read repositories in `~/Documents/Code/…` when I made `~/.gitconfig` a hard link, but _not_ read `~/Documents/dotfiles/git/gitconfig` through a symlink. If I had declined Fork access to the Documents folder it should not have been able to read those repositories when I moved `~/.gitconfig`, right?

**Comment by DanPristupov** [comment]
> What I don't understand at this point is how Fork was able to read repositories in `~/Documents/Code/…` when I made `~/.gitconfig` a hard link, but _not_ read `~/Documents/dotfiles/git/gitconfig` through a symlink. If I had declined Fork access to the Documents folder it should not have been able to read those repositories when I moved `~/.gitconfig`, right?

Yes, that seems to be right and TBH, I don't have the answer.
