### ISSUE TITLE
Question: License and moving to new machine - deactivate?

### ISSUE THREAD

**Issue by hcguersoy** [ForkIssues/Tracker#1545]
Hello, I'm moving to new hardware and my question is if I've to 'deactivate' the license on my old system:

![Fork License dactivate](https://user-images.githubusercontent.com/778536/150320155-6a75a771-90de-43e8-9d47-5cfc62663ae8.png)

Or deactivates this button the whole license key?

**Comment by DanPristupov** [comment]
It will deactivate Fork license on that particular machine.

If you don't have an access to the old system, I can do do that for you on request (support@fork.dev).

**Comment by hcguersoy** [comment]
@DanPristupov Thank you for your fast answer. I've few days access to the machine so I can deactivate it myself but I just wanted to go safe.
