### ISSUE TITLE
Re-merge message is gone

### ISSUE THREAD

**Issue by ElfSundae** [ForkIssues/Tracker#155]
1. Merge branch, the commit message shows "Message branch ... into ... # Conflicts ..."
2. Abort merge
3. Merge the same branch, the default commit message is disappeared. Is this normal?

**Comment by ElfSundae** [comment]
Sorry I made a mistake.

**Comment by DanPristupov** [comment]
I already started investigating the problem and glad that everything is OK :).

FYI, Fork loads merge conflict message from `MERGE_MSG` file which is created by git in `.git` directory when merge conflict happens.

**Comment by ElfSundae** [comment]
@DanPristupov  Thanks.
I just encountered once. After `git merge --abort` everything is OK now.
