### ISSUE TITLE
Squash or rebase and merge a branch in fewer steps (like GitHub)

### ISSUE THREAD

**Issue by samsonjs** [ForkIssues/Tracker#1556]
When accepting a pull-request on GitHub you can choose to create a merge commit, squash all the commits and reword, or rebase all the commits and reword. It would be nice to have an easier way to do this in Fork. It's already possible to do the same thing manually of course.

Doing it in one or two steps would be awesome. It could be part of the interactive rebase UI, like a button that changes all the commits to squash and brings up the message editor or something along those lines.

**Comment by DanPristupov** [comment]
<img width="500" alt="Screenshot 2022-02-04 at 9 00 17" src="https://user-images.githubusercontent.com/618115/152492929-c775671f-48ad-4eb2-be7a-bbb1fccb56c6.png">

Merge dialog has the squash option.

**Comment by samsonjs** [comment]
That's exactly what I'm after! I rarely use the rebase option so I'm fine doing that one manually. Thanks for pointing me in the right direction.
