### ISSUE TITLE
[Feature Request] Show progressbar / spinner for long operations

### ISSUE THREAD

**Issue by Meligy** [ForkIssues/Tracker#156]
Can we have some indicator that an operation is still in progress when doing a long operation?

Like remote operations (pull / fetch / push).

I love how this app improves upon common patterns in Git Extensions. I found it when looking for an alternative that works better on Mac. Git Extensions brings up a modal dialog showing the command it runs, and a progress bar. It gives the option to close the dialog automatically when done.

Super cool tool though BTW, way ahead of pretty much everything I saw. Great work!

**Comment by DanPristupov** [comment]
Hi. Fork shows progress for long operations in the status bar

![2017-11-09 at 11 30](https://user-images.githubusercontent.com/618115/32600987-8abe5468-c541-11e7-9787-ee6469683417.gif)

**Comment by Meligy** [comment]
Interesting. I haven't noticed it until you pointed it out!

Sorry for the noise.
