### ISSUE TITLE
Not installing command line tools

### ISSUE THREAD

**Issue by pablobm** [ForkIssues/Tracker#1562]
I just got a new MacBook Pro running Monterey. Doing initial setup, one of the first tools I have installed is Fork. However, when I go to the Integration config and press "Install Command Line Tools", the button gives no feedback at all (apart from looking "pressed" when I click) and the tools are not installed.

**Comment by DanPristupov** [comment]
I think it's related to https://github.com/fork-dev/Tracker/issues/999

**Comment by pablobm** [comment]
Indeed. Closing this one in favour of that one. I did try this morning again and it worked, and I had installed Homebrew in the meantime, so that ticket explains the problem well. Thank you!
