### ISSUE TITLE
[Feature Request] Fast-forward all branches

### ISSUE THREAD

**Issue by igor-makarov** [ForkIssues/Tracker#1563]
As a user who collaborates on features with several other teammates, I often have multiple branches that need fast-forwarding.

The "fast-forward" context menu item is great, and I would like an option to "Fast-Forward All Branches" that will apply the same logic to all the branches that are trivial to FF.

My suggestion is to add this in two places:
* The "**Repository**" menu.
* In the context menu for the "**Branches**" root item in the sidebar (where there's also "New Branch" item)

Thank you for all the work!

**Comment by DanPristupov** [comment]
In Fork 2.19 you can select and fast-forward multiple branches.

<img width="299" alt="Screenshot 2022-08-17 at 11 35 05" src="https://user-images.githubusercontent.com/618115/185086235-646c016b-9ec1-4b3d-823f-b5d5763e4bbe.png">

**Comment by igor-makarov** [comment]
Awesome! Thank you!
