### ISSUE TITLE
[BUG] Stable Update Channel doesn't work

### ISSUE THREAD

**Issue by gentique** [ForkIssues/Tracker#1564]
Automatic update or even manually checking doesn't seem to trigger a new update, even though it has been more than a month since the last release.
<img width="258" alt="Screenshot 2022-02-18 at 12 17 47 AM" src="https://user-images.githubusercontent.com/15278390/154588000-234f4da9-46b8-40f7-adbd-b298187f22b8.png">

**Comment by DanPristupov** [comment]
Yes, I forgot to publish 2.15 to stable. Just released it.
