### ISSUE TITLE
Feature Request: Fork does not (yet) support zdiff3 merge.conflictstyle

### ISSUE THREAD

**Issue by ffloimair** [ForkIssues/Tracker#1566]
git 2.35 introduced the new merge.conflictstyle setting zdiff3 (see [blog](https://github.blog/2022-01-24-highlights-from-git-2-35/#:~:text=If%20you%E2%80%99ve%20ever%20dealt%20with%20a%20merge%20conflict))

When this is configured as default in .gitconfig then staging changes in Fork causes the following error message in a new popup window:

```
Git Error
An unexpected error occured while performing the git request
Error Details:
fatal: unknown style 'zdiff3' given for 'merge.conflictstyle'
```

It would be great to see this new merge.conflictstyle setting implemented in Fork as well.

**Comment by DanPristupov** [comment]
> `fatal: unknown style 'zdiff3' given for 'merge.conflictstyle'`

Internal Fork git (2.33.1) tells you that that option is not supported. Which means, that you must switch Fork to your system git.

**Comment by ffloimair** [comment]
Thanks for the hint. I had this set to system git at one point, but somehow it switched back to Fork's internal git at another point.
That's why I thought that it's Fork itself that does not support this.
When set to system git it works as expected.
