### ISSUE TITLE
[Bug] - Can't open external diff tool (BBEdit)

### ISSUE THREAD

**Issue by brownjoel** [ForkIssues/Tracker#1569]
Running Fork 2.16 on macOS 12.2.1.

I'm trying to set up BBEdit as my preferred diff tool.  I've set it up correctly in the preferences, and it attempts to run the following line:
`$ /usr/local/bin/bbdiff "/var/folders/nm/37199m6n6d53gbngzvptj0d40000gn/T/fork/b485088/path/to/file" "/var/folders/nm/37199m6n6d53gbngzvptj0d40000gn/T/fork/b485088~/path/to/filepas"`

This sequence works copy-pasting into the Terminal, but in Fork nothing happens.

Alternatively, BBEdit could be added as a default option for macOS.

**Comment by scheffle** [comment]
I'd like to see support for BBEdit as well.
I just had a look why it does not work with the current "Custom" command and the console prints out the following interesting bit:
`Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for responsible={<TCCDProcess: identifier=com.DanPristupov.Fork, pid=76726, auid=501, euid=501, responsible_path=/Applications/Fork.app/Contents/MacOS/Fork, binary_path=/Applications/Fork.app/Contents/MacOS/Fork>}, accessing={<TCCDProcess: identifier=com.barebones.cmd-line-tools.bbdiff, pid=76883, auid=501, euid=501, binary_path=/Applications/BBEdit.app/Contents/Helpers/bbdiff>}, requesting={<TCCDProcess: identifier=com.apple.appleeventsd, pid=893, auid=55, euid=55, binary_path=/System/Library/CoreServices/appleeventsd>},`
From my understanding the issue would be solved if Fork would add the "com.apple.security.automation.apple-events" hardened runtime entitlement.
