### ISSUE TITLE
Slowdown when staging extremely long lines

### ISSUE THREAD

**Issue by james-rabbit** [ForkIssues/Tracker#157]
I have a very long line of text, if I wrap it then it goes for hundreds of lines.
Having text like that is a bad idea in general, so I'm removing it from the repo.
However while staging the removal (selecting the line removal and staging it), Fork became unresponsive for a long time.

**Comment by DanPristupov** [comment]
Hi. It can be either Fork's own slowdown or the native Apple text control's one.
I'll investigate why this happens. BTW, how long (approximately) did the staging take?

**Comment by james-rabbit** [comment]
It was some time longer than 30 seconds, I ended up quitting the app and using the command line git to stage the line. Thanks!

**Comment by ElfSundae** [comment]
@DanPristupov you may try some compressed web-frontend assets, like [this](https://github.com/laravel/laravel/blob/master/public/js/app.js)

Fork is often frozen when I click a compressed js/css in Changes list.

An example:

```sh
git init test
cd test
wget https://raw.githubusercontent.com/laravel/laravel/master/public/js/app.js
git add .
git commit -am "init"

fold -w5 app.js > tmp
mv tmp app.js

fork status
```

**Comment by DanPristupov** [comment]
@ElfSundae Today I was fixing this problem and your example helped me a lot. Thank you.

BTW, I managed to make Laravel's app.js to be loaded in about 100ms :).

**Comment by DanPristupov** [comment]
@ElfSundae just released Fork 1.0.60 with the fix. It should handle both huge and as minified files properly.

**Comment by ElfSundae** [comment]
@DanPristupov Much better now 👍 

A little files in my project now hang about 3~5s, and my commented example still makes Fork to be unresponsive, maybe you could increase the limitation (line/column number I guess)?

![image](https://user-images.githubusercontent.com/526008/33494366-006e7e0e-d6fe-11e7-926d-c0d8986e1a14.png)

**Comment by james-rabbit** [comment]
Thanks, this seems to work much better now.
