### ISSUE TITLE
[Feature Request] Keep prefix when creating a new branch

### ISSUE THREAD

**Issue by adrien-de-tocqueville** [ForkIssues/Tracker#1574]
For example i am on branch `2021.2/graphics/hd/bugfix` and i press ctrl+shift+b to branch off
A popup appears to enter the new branch name, if `2021.2/graphics/hd/` could be prefilled in the text box that would save some typing

**Comment by DanPristupov** [comment]
I like the idea, but I'm not sure if we should use the active branch. Often we create a new branch while being on 'master' and that approach won't work.

May be a better solution could be to remember the last folder used in the create branch dialog?

**Comment by adrien-de-tocqueville** [comment]
actually i just realised that there is autocompletion of the folder if you press tab while typing, so that's pretty much the same
