### ISSUE TITLE
Add support for --signoff

### ISSUE THREAD

**Issue by infotexture** [ForkIssues/Tracker#158]
Many open source projects require contributors to “sign off” each commit with 

    git commit --signoff

to indicate that the committer has the right to submit the changes and agrees to the terms of the  [Developer Certificate of Origin](https://developercertificate.org). (For details, see <https://git-scm.com/docs/git-commit#git-commit--s>.)

To support these workflows, it would be helpful if Fork would add a signoff option to the repository settings view alongside the GPG signing options or add a **Sign off** checkbox to the commit dialog.

_(If an option is added to the commit dialog, it should remember its state per repo, or mirror the state of the option in the repository settings. This approach would help to remind users at commit time whether signoff is enabled for the current repository without having to check the repository settings.)_

**Comment by DanPristupov** [comment]
Hi.

Thank you for the great explanation and for providing the links to details.

It looks like it should not be difficult to add such an option to the repository settings view as you suggested. I added this to my todo list.

I may ask some questions if something is not clear during the implementation.

**Comment by DanPristupov** [comment]
I implemented `--signoff` in Fork 1.0.61. The option is available in repository settings.

**Comment by infotexture** [comment]
🎉 Thanks! Looking forward to using Fork with my open source projects that require signoff.
