### ISSUE TITLE
Support for Github Flow / Gitlab Flow / Simplified Git Flow

### ISSUE THREAD

**Issue by yisyang** [ForkIssues/Tracker#1586]
# Issue / Feature-Request: Simplified Git Flow

## Overview

For a lot of CI/CD projects nowadays, having a develop branch no longer makes sense.

For example - if you're working with Flux, you'd probably want GitOps configs for each env (/cluster/dev, /cluster/stage, /cluster/prod) in their own subdirs on the same main/master branch, instead of /cluster/dev on develop branch, /cluster/stage on staging branch, etc.

Trouble is, at the moment, it doesn't seem like Fork supports simplified Git Flow where there is only 1 single main/master branch.
There seems to be no issues setting up the branches to be equivalent, but in practice starting a feature would fail.

## Issue when master branch == develop branch

Button grayed out when develop branch is empty.
<img width="528" alt="gitflow-1" src="https://user-images.githubusercontent.com/5167456/161872013-f6b50b69-494e-4e58-8e39-17210abc0938.png">

Button works when both branches are filled out.
<img width="525" alt="gitflow-2" src="https://user-images.githubusercontent.com/5167456/161872016-e026fa88-c04e-43b5-932f-050b06f8910e.png">

Starting a feature.
<img width="547" alt="gitflow-3" src="https://user-images.githubusercontent.com/5167456/161872017-2cef66d4-b0b1-47d4-b47e-026f549ebf5c.png">

Fail.
<img width="700" alt="gitflow-4" src="https://user-images.githubusercontent.com/5167456/161872018-15d7a443-4fa9-40d1-92b5-5c425c0bcd2e.png">

## (Not related to Fork) git-flow CLI

Trying the git-flow CLI directly also fails:

```
$ git flow init
Which branch should be used for bringing forth production releases?
   - main
Branch name for production releases: [main] 
Branch name for "next release" development: [develop] main
Fatal: Production and integration branches should differ.
```

## Additional Ref
More on Github Flow / Gitlab Flow: https://docs.gitlab.com/ee/topics/gitlab_flow.html

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/1432

**Comment by DanPristupov** [comment]
> There seems to be no issues setting up the branches to be equivalent, but in practice starting a feature would fail.

You should address that to GitFlow AVH project (https://github.com/petervanderdoes/gitflow-avh). Fork just wraps it.

Regarding 'Support for Github Flow / Gitlab Flow'. You don't need any support for them. Just create a branch.

**Comment by yisyang** [comment]
@DanPristupov 
It doesn't even look very difficult to update the gitflow-avh scripts to allow the functionality. Sadly gitflow-avh looks like it's not been maintained for 3 years - loads of unmerged pull requests. So I think it's best to just rely on your Lean Branching model.

👍 The Lean Branching model is **almost exactly** what I'm asking for. Just a different set of terminology.

It's great, just several things I'd hope to see in the future to make it more similar to GitX Flow:
- Checkbox (remembered) for "Finish/merge" to delete "feature" branch on merge.
- Checkbox (remembered) for "Finish/merge" to delete "origin/feature" branch on merge.
- Allow configuring a default branch prefix (e.g. feature/)

Before Fork, I've used several other GUI Git tools, the most recent being SmartGit, and it definitely supported the simplified GitX Flow without issues. It was my favorite in terms of features, but its licensing model is awful.

**Comment by DanPristupov** [comment]
> * Checkbox (remembered) for "Finish/merge" to delete "feature" branch on merge.
> * Checkbox (remembered) for "Finish/merge" to delete "origin/feature" branch on merge.

Lack of these checkboxes is a feature (i.e. it is intentional behavior). The use *must* be able to test the changes after merge and possible roll them back before push if merge was incorrect.

> Allow configuring a default branch prefix (e.g. feature/)

Just type it by hands. Fork will suggest the available prefixes with autocomplete.
