### ISSUE TITLE
Update server returning wrong version

### ISSUE THREAD

**Issue by shengslogar** [ForkIssues/Tracker#1588]
I manually updated Fork but wasn't able to get that through the "Check For Updates" menu item. Seems like an error on your end?

![CleanShot 2022-04-18 at 11 26 21@2x](https://user-images.githubusercontent.com/4350009/163847560-6cc6ccab-0aa7-4840-afdf-3bb3c7715c0c.png)

**Comment by DanPristupov** [comment]
I think at the time you switched Fork to the stable update channel and couldn't see the latest update.
