### ISSUE TITLE
Repository Name or Path Not Shown in UI

### ISSUE THREAD

**Issue by c-alpha** [ForkIssues/Tracker#1589]
<img width="1792" alt="Screenshot 2022-04-19 at 16 03 39" src="https://user-images.githubusercontent.com/2213269/164024411-a2a68a56-624d-4826-9801-2b65d862535e.png">

AS shown in the screenshot above, the checked out branch name is shown multiple times, but the name or path of the repository is not shown at all in the UI. As I'm working with many repositories, this can sometimes be a head-scratcher ("What am I lookign at here again?").

It would seem to me that there are two locations where showing repository identifying information could be useful (as shown in blue in the screenshot above):

1. The repository name (e.g. "myrepo.git") as the headline of the "LCD display" (or whatever it's called) in the toolbar.
2. The path of the working copy (e.g. "~/projects/myrepo") as the title of the tab.

**Comment by DanPristupov** [comment]
- Is your repo located in the 'master' directory on disk? If so, open RepoManager (Cmd+T) and rename it to something else.
- Or have you renamed your repository to 'master' in Fork? Then again, open Repo Manager and rename it.

**Comment by c-alpha** [comment]
Thanks for your swift answer! I have indeed checked out the master branch into a directory named "master". This is a pattern I use often to be able to build & run different branches ("myrepo/main", "myrepo/branch1", etc.).

I have renamed the repo in Fork using the RepoManager as you suggest. Now I get the Fork name displayed in the tab header, and as the headline in the "LCD display". This is fine as an immediate solution.

I still think that seeing "myrepo.git" in the "LCD display", and the (relative) path in the tab header could be more expressive though. Plus it would save me from having to manually rename the repositories in Fork every time I create a new directory for the next branch. 😉 

Many thanks, and looking forward to your thoughts. 👋

**Comment by DanPristupov** [comment]
> I still think that seeing "myrepo.git" in the "LCD display"

I don't understand. What is "myrepo.git"? This the first time I hear about the `.git` extension, I think.

> and the (relative) path

Relative path, relatively to what?

**Comment by c-alpha** [comment]
Apologies for not having been clear enough.

> > I still think that seeing "myrepo.git" in the "LCD display"
> 
> I don't understand. What is "myrepo.git"? This the first time I hear about the `.git` extension, I think.

I meant to mean the repository part in the remote speciification, such as for example:

```
▶ git remote -v
origin	https://git.savannah.gnu.org/git/emacs.git (fetch)
origin	https://git.savannah.gnu.org/git/emacs.git (push)
```

I thought that seeing "emacs.git" (or just "emacs") up there would help remind me of what I had checked out?

> > and the (relative) path
> 
> Relative path, relatively to what?

Relative to the default source folder I can set in the preferences (General tab, first thing at the top), and that can be scanned for repositories.

For repositories outside that folder, you could truncate the left part of the path as space in the UI permits, focussing on the end of the directory path. The truncation could be indicated by an ellipsis of three dots.
Example: `.../long/path/to/myrepo`
