### ISSUE TITLE
Update to git 2.36 to support the built in fsmonitor--daemon

### ISSUE THREAD

**Issue by Cyberbeni** [ForkIssues/Tracker#1591]
Starting with 2.36, people have the option to use the built in fsmonitor to speed up stuff like `git status`. I tested it in the command line and in one specific repo `git status` went from 600ms to 50ms.

https://git-scm.com/docs/git-config#Documentation/git-config.txt-corefsmonitor

**Comment by DanPristupov** [comment]
I spent a lot of time in the past trying to implement my own file system watcher, but there were a lot of problems to solve (submodules, etc).

I'll looking forward to try it out.

> I tested it in the command line and in one specific repo `git status` went from 600ms to 50ms.

That's amazing!

**Comment by DanPristupov** [comment]
I tried `fsmonitor--daemon` in the Chromium repo. The git status went down from 5000ms to 1000ms, which is pretty impressive.

Though I couldn't make it work using the default commands. Running `git fsmonitor--daemon run` doesn't make `git status` faster. However `git config --local core.fsmonitor true` seems to be working and does make impact on `git status`. I couldn't find what's wrong yet.

Anyway, in the next update we will bundle `git 2.36.1` with Fork, so enabling the FS daemon using the git config will be possible. You can try the prebuild and ensure that everything works properly in your environment: https://cdn.fork.dev/prerelease/Fork-2.18.10.dmg.

**Comment by Cyberbeni** [comment]
There is a bug with 2.36.1 and submodules (if fsmonitor is turned on), it will be fixed probably in the next release: https://www.spinics.net/lists/git/msg440170.html

**Comment by DanPristupov** [comment]
Ah, that was you! I've read that topic but couldn't understand why the author name is so familiar to me :).
