### ISSUE TITLE
Fast forward on current active branch leads to freeze/hang

### ISSUE THREAD

**Issue by ferben** [ForkIssues/Tracker#1592]
User is able to select fast forward action from context menu on the current active branch.

But if user do fast forward on current active branch Fork.app freeze/hang.

**Comment by DanPristupov** [comment]
Does the problem persist after the computer reboot?

**Comment by ferben** [comment]
Yes. I've seen this issue at first time in version 2.0.
It is strange, because if you have inctive tracked branch fast forward works, fast forward cause freeze only on active branch.

I don't have perfect git knowledge, fast forward on active branch can git mark as impossible operation. 

I send crashlog to Apple when I must force quit Fork.app.

**Comment by ferben** [comment]
I have two observation:
1) Freeze happen when you fast forward in current branch more commits 50-70 or more.
2) In my case repo working with git-lfs.

ps aux | grep Fork:
ferben@iMac ~ % ps aux | grep Fork        
ferben           60658   0.0  0.2 35285172  41660   ??  S     2:06PM   0:00.50 /Applications/Fork.app/Contents/Resources/git-instance/bin/git merge --ff-only refs/remotes/origin/[branchname]
ferben           60556   0.0  1.2 35441736 310524   ??  S     2:05PM   0:05.79 /Applications/Fork.app/Contents/MacOS/Fork
ferben           60900   0.0  0.0 34236680  11704   ??  S     2:14PM   0:00.03 /Applications/Fork.app/Contents/Resources/fork_askpasswd Password for "https://[company name]@dev.azure.com"

[Spindump.txt](https://github.com/fork-dev/Tracker/files/8590694/Spindump.txt)
[Sample of Fork.txt](https://github.com/fork-dev/Tracker/files/8590695/Sample.of.Fork.txt)

**Comment by DanPristupov** [comment]
I will have a look next week. Please don't hesitate to remind me if I forget :)

**Comment by DanPristupov** [comment]
> ferben 60900 0.0 0.0 34236680 11704 ?? S 2:14PM 0:00.03 /Applications/Fork.app/Contents/Resources/fork_askpasswd Password for "https://[company name]@dev.azure.com"

I guess, your server prompts something unusual and waits for the response. Some confirmation, may be?

**Comment by ferben** [comment]
How can I help you to reveal the issue?
Can I see this in log or can do something else (connect to fork process with debugger etc.)?

**Comment by DanPristupov** [comment]
Can you try to run the following command in command line?

`git merge --ff-only <remote_tracking_branch>`.

This is the command which hangs in Fork.
