### ISSUE TITLE
GitLabl Server cannot parse JSON in server response

### ISSUE THREAD

**Issue by RbBtSn0w** [ForkIssues/Tracker#1594]
Services-> Accounts

our custom GitLab server.

when I log in using the Personal Access token of GitLab Server.

return message: cannot parse JSON in the server response.

**Comment by DanPristupov** [comment]
I'm sorry, I missed your question. Have you solved the problem? If not, could you check if the log file has any errors? The log is located at `~/Library/Logs/Fork.log`

**Comment by LyhjeHylje** [comment]
I have this same error but with github (enterprise)
My log says:
◽️[GitServiceConnection.swift:88] > 183ms: GET https://github.xxx.fi/yyy/api/v3/user (406)
⚠️[GitServiceConnection.swift:91] > Http error: https://github.xxx.fi/yyy/api/v3/user 406
❌[GitHubEnterpriseLoginController.swift:88] > jsonParseError

This worked some years back when I set up intel-based macbook. Now I have m1 and get this. Everything else same except the mac-model and the account token which is of course newly generated by github.

**Comment by DanPristupov** [comment]
@LyhjeHylje 406 error code means `Not Acceptable`. Is it possible that API is disabled in your GitHub Enterprise configuration?

**Comment by LyhjeHylje** [comment]
> @LyhjeHylje 406 error code means `Not Acceptable`. Is it possible that API is disabled in your GitHub Enterprise configuration?

In my case the problem seemed to be invalid url; I removed the closing slash and it worked.

**Comment by RbBtSn0w** [comment]
> 


◽️[GitServiceConnection.swift:88] > 597ms: GET http://gitlab.MYGITSERVER.com/api/v4/user (200)
❌[GitServiceConnection.swift:30] > Cannot parse json in the server response content
❌[GitLabLoginController.swift:99] > jsonParseError

**Comment by RbBtSn0w** [comment]
> I'm sorry, I missed your question. Have you solved the problem? If not, could you check if the log file has any errors? The log is located at `~/Library/Logs/Fork.log`

Thanks for your reply, I was checking this log by ~/Library/Logs/Fork.log

Look same error message by FORK UI alter.

◽️[GitServiceConnection.swift:88] > 597ms: GET http://gitlab.mygitserver.com/api/v4/user (200)
❌[GitServiceConnection.swift:30] > Cannot parse json in the server response content
❌[GitLabLoginController.swift:99] > jsonParseError

**Comment by DanPristupov** [comment]
@RbBtSn0w can you contact me by email (support@fork.dev), so I could help you to investigate that?

**Comment by RbBtSn0w** [comment]
> @RbBtSn0w can you contact me by email ([support@fork.dev](mailto:support@fork.dev)), so I could help you to investigate that?

sure

**Comment by RbBtSn0w** [comment]
> @RbBtSn0w can you contact me by email ([support@fork.dev](mailto:support@fork.dev)), so I could help you to investigate that?

nobody replies to the email.

**Comment by RbBtSn0w** [comment]
The reason is my API only supports v3.
FORK app default use v4, so access is failed.

**Comment by RayanSaeed** [comment]
```
🔷> XCGLogger writing log to: file:///Users/rayansaeed/Library/Logs/Fork.log
🔷[AppDelegate.swift:391] > 
 ________      ,-----.     .-------.     .--.   .--.
|        |   .'  .-,  '.   |  _ _   \    |  | _/  /
|   .----'  / ,-.|  \ _ \  | ( ' )  |    | (`' ) /     Fork 2.49.1
|  _|____  ;  \  '_ /  | : |(_ o _) /    |(_ ()_)      Git: internal
|_( )_   | |  _`,/ \ _/  | | (_,_).' __  | (_,_)   __  Update Channel: develop
(_ o._)__| : (  '\_/ \   ; |  |\ \  |  | |  |\ \  |  |
|(_,_)      \ `"/  \  ) /  |  | \ `'   / |  | \ `'   /    https://fork.dev
|   |        '. \_/``".'   |  |  \    /  |  |  \    /
'---'          '-----'     ''-'   `'-'   `--'   `'-'
🔷[WindowManager.swift:266] > Restore workspace 'Work' with 0 windows and  tabs
◽️[RestServiceConnection.swift:88] > 1007ms: GET https://gitlab.********.com/api/v4/user (200)
❌[RestServiceConnection.swift:30] > Cannot parse json in the server response content
❌[GitLabLoginController.swift:100] > jsonParseError
```

I am facing the same issue, how do I know if mine is also an error because of API version difference or not?
Would really appreciate your help on this @DanPristupov 


EDIT:

Here is the server response using the same personal access token and api v4.
`https://gitlab.********.com/api/v4/user?private_token=************************`

```
{
  "id": 246,
  "username": "Saeed",
  "name": "Rayan Saeed",
  "state": "active",
  "avatar_url": "https://gitlab.********.com/uploads/-/system/user/avatar/246/avatar.png",
  "web_url": "https://gitlab.********.com/Saeed",
  "created_at": "2024-12-17T10:23:10.950Z",
  "bio": "",
  "location": "",
  "public_email": "",
  "skype": "",
  "linkedin": "",
  "twitter": "",
  "website_url": "",
  "organization": "********",
  "job_title": "Senior iOS Engineer",
  "pronouns": "",
  "bot": false,
  "work_information": "Senior iOS Engineer at ********",
  "followers": 0,
  "following": 0,
  "local_time": "10:32 AM",
  "last_sign_in_at": "2024-12-17T10:24:07.859Z",
  "confirmed_at": "2024-12-17T10:23:10.788Z",
  "last_activity_on": "2024-12-18",
  "email": "rsaeed@********.com",
  "theme_id": 1,
  "color_scheme_id": 1,
  "projects_limit": 0,
  "current_sign_in_at": "2024-12-17T10:24:07.859Z",
  "identities": [],
  "can_create_group": true,
  "can_create_project": false,
  "two_factor_enabled": false,
  "external": false,
  "private_profile": false,
  "commit_email": "rsaeed@********.com",
  "shared_runners_minutes_limit": null,
  "extra_shared_runners_minutes_limit": null
}
```

**Comment by DanPristupov** [comment]
@RayanSaeed

> Cannot parse json in the server response content

This means that the server response is not a valid JSON (probably a web-page).

Try to run in CLI: `curl "https://git.***********.com/api/v4/user" -H 'Private-Token: ***********'`. Does it work?

**Comment by RayanSaeed** [comment]
Interesting 🤔 
You are right. It is indeed a web-page and not valid JSON.

```
<html>
  <head>  <title>302 Found</title>  </head>
  <body>
    <center>  <h1>302 Found</h1>  </center>
    <hr> 
    <center>  cloudflare  </center>
  </body>
</html>
```

**Comment by RayanSaeed** [comment]
What could be the reason for this? Any idea? 

It works fine if I make a request via the browser and pass the token as a URL parameter 
But doesn't work when passed in header. 🤔 

EDIT:

I think I know what the issue is.. I think it's because my company has setup a SSO which is what the curl request is being redirected to. 🤔 

So is it safe to say I won't be able to use Fork with the company GitLab account? 😢

**Comment by DanPristupov** [comment]
I'd recommend to ask an administrator in your company and send them the failing CURL request.

**Comment by RayanSaeed** [comment]
Got it. Thanks a bunch Dan!
