### ISSUE TITLE
Side by Side diff use same setting is confused

### ISSUE THREAD

**Issue by adison** [ForkIssues/Tracker#1603]
I am checking Fork features to promote to colleagues and find lots unknown features.
And I found the side by side diff, aka press space to give an independent window to show code diff need some improvement.
1. While I pressed space bar, it gives me a 15 lines diff, just as what I see on Fork main window, and that confused me..
2. After secs, I found the setting at top right corner and click to full file mode, take a screenshot, press space bar to back main GUI. I found the file diff changes too.. 

So, I would suggest to give a separated setting for Side by Side diff, like default diff lines increased to 50 or set to full file.

![image](https://user-images.githubusercontent.com/2823871/168724689-a91199f9-85d2-41e8-ba2a-ac3c5753437b.png)

**Comment by DanPristupov** [comment]
The 'number of visible lines' is a global setting. That works fine for the majority of the users.

**Comment by adison** [comment]
For me, calling the separate diff window implies I need more space to watch something, it might be to read many diff in same file, or need more lines/full file to track logic.
In later condition, a separate setting can help me from change setting every time.
I thinks this feature deserve a rethink.
