### ISSUE TITLE
[Feature] Cherry picking by drag and drop

### ISSUE THREAD

**Issue by svoop** [ForkIssues/Tracker#1604]
Maybe a more intuitive or natural way to cherry pick:

Select one or multiple commits from the commit list and drag-n-drop them onto a branch.

**Comment by DanPristupov** [comment]
> Select one or multiple commits from the commit list and drag-n-drop them onto a branch.

Do you mean on a branch on sidebar?

What if that branch is not active?
Isn't the right-click context menu just easier?

**Comment by svoop** [comment]
> Isn't the right-click context menu just easier?

If the branch has to be active, yes. Thanks for the reply!
