### ISSUE TITLE
[feature] Bulk delete local branches with missing remote branch

### ISSUE THREAD

**Issue by BretFisher** [ForkIssues/Tracker#1605]
With GitHubs "Automatically delete head branches" enabled in many projects I work on, I find myself doing lots of cleanup of local branches that Fork correctly throws the warning logo on, but (I think) the only way to remove those is to r-click each, click delete, then confirm on prompt.

It would be a "toil saver" if I had a prune branches option that would remove all local branches, in one go, that Fork identified as having (now) missing remote branches.

**Comment by DanPristupov** [comment]
You can multi select local branches with the 'warning' icon on the sidebar (hold Cmd for multiselection) and remove at once.

**Comment by BretFisher** [comment]
Oh, sweet, that's a good time saver. Thanks.
