### ISSUE TITLE
[Feature Request] Export/Import custom commands

### ISSUE THREAD

**Issue by JohannesDeml** [ForkIssues/Tracker#1608]
As suggested in https://github.com/fork-dev/Tracker/issues/123#issuecomment-417679857, it would be great to have a possibility to export and import the custom commands to make sharing them in the team easier.

**Comment by DanPristupov** [comment]
Fork allows to share repository custom commands with the other repository users.

Repository -> Settings for this repository -> Custom Commands. Notice the local/shared switch.

<img width="650" alt="Screenshot 2022-05-29 at 13 50 04" src="https://user-images.githubusercontent.com/618115/170864237-9a315a0c-16a9-4444-84b7-668eb3f44edd.png">

**Comment by JohannesDeml** [comment]
Ah, very nice! Thanks a lot, I somehow missed this setting completely!
