### ISSUE TITLE
[feature request] repo tabs: don't require shift to scroll horizontally with scroll wheel

### ISSUE THREAD

**Issue by olets** [ForkIssues/Tracker#1609]
Currently to scroll the repositories tabs with a scroll wheel (for example with a mouse) I have to hold the shift key.

Shift+scroll wheel is a standard way to scroll horizontally. The current behavior is good.

A desktop UI pattern I like is to not require the shift key when _only_ horizontal scrolling is possible.

I don't know how widespread this is. Compare for example VS Code, where scrolling scrolls tabs horizontally and shift scrolling scrolls horizontally and changes the active tab.

**Comment by DanPristupov** [comment]
Do you mean Fork for macOS? It uses the default macOS which work the same in Finder, XCode and also Fork. The tabs are normally scrollable by mouse wheel (shift is not required).

**Comment by olets** [comment]
Yes Fork for macOS.

Testing tabs in Finder windows now I see the same behavior, where shift is required. (I don't make heavy use of Finder tabs so hadn't noticed before.) Guess this would require deviating from macOS defaults.

Strange, wonder if it's my mouse.
