### ISSUE TITLE
GPG signing using SSH key

### ISSUE THREAD

**Issue by scottaw66** [ForkIssues/Tracker#1612]
Please allow Fork to sign commits with SSH keys (which git supports as of 2.34).

<img width="1192" alt="Screen Shot 2022-05-26 at 6 35 26 PM" src="https://user-images.githubusercontent.com/7348442/170611402-12adca88-1409-41b4-a00a-fabd7214e453.png">

**Comment by DanPristupov** [comment]
You can switch Fork to your system git instance, if you need.

**Comment by scottaw66** [comment]
Wow, that's beautiful. I'm sorry I didn't understand that! Works like a charm!!

**Comment by DanPristupov** [comment]
We should probably add a friendly UI for SSH commit signing and checking the sign.

**Comment by DanPristupov** [comment]
BTW, how do you validate the commits? Do you maintain your own `allowedSignersFile` file and gather the committers public SSH keys manually?

**Comment by scottaw66** [comment]
Great question. I’ve only used this on solo projects.
