### ISSUE TITLE
Fetch is not working

### ISSUE THREAD

**Issue by bellmcp** [ForkIssues/Tracker#1615]
Hello Fork team,

I enjoy using your app on Windows, everything works fine. but recently I just switched to macOS. I found something weird with the app.

I cannot fetch and view the git tree. Even if the status log shows "Everything is up to date" and branch details are correctly fetched from the server.

<img width="1262" alt="Screen Shot 2022-06-06 at 3 08 33 PM" src="https://user-images.githubusercontent.com/32966560/172125529-464af55c-9443-42e4-a2a2-7a9d8555b1a7.png">

<img width="1375" alt="Screen Shot 2022-06-06 at 3 08 29 PM" src="https://user-images.githubusercontent.com/32966560/172125103-ec53dc06-2703-4efe-9651-22842c82a6dc.png">

I don't know why I can see the Repository statistics correctly fetched here.
<img width="1262" alt="Screen Shot 2022-06-06 at 3 08 43 PM" src="https://user-images.githubusercontent.com/32966560/172125654-c78177d5-a682-43f7-9b87-3f7a1e7478bc.png">

My project is on self-hosted GitLab, So, I tried logging in to GitLab Server, Creating SSH keys, and Switching through the git instance. But it doesn't seem to help solve the problem.

By the way, I tried opening the same project with [Sourcetree](https://www.sourcetreeapp.com/), But It works.

Looking forward to the solutions, I hope to use Fork as the main git tool again.

Thank you in advance.

**Comment by bellmcp** [comment]
Update: If I manually clicked the fetch button it always show `unknown error`
<img width="1262" alt="Screen Shot 2022-06-06 at 3 46 41 PM" src="https://user-images.githubusercontent.com/32966560/172128129-30641ff4-faa9-4853-a06f-c86768e118d3.png">

**Comment by DanPristupov** [comment]
Hi. Could you check if the log file has any errors? `~/Library/Logs/Fork.log`

**Comment by bellmcp** [comment]
Hi, I think this causes the problem.

```❌[RefreshRepositoryCommand.swift:229] > cannotParse(error: "Cannot parse author in \'username~..ืfirstname.lastname@mydomain.com\'")```

```❌[ErrorWindowController.swift:25] > cannotParse(error: "Cannot parse author in \'username~..ืfirstname.lastname@mydomain.com\'")```

There is one guy in my team, whose email starts with a Thai vowel `ื` [(U+0E37)](https://unicode-table.com/en/0E37/)

Could you help handle this weird case? lol

Thank you again for your support.

Note: I am using Fork 2.18.1

**Comment by DanPristupov** [comment]
> email starts with a Thai vowel `ื` [(U+0E37)](https://unicode-table.com/en/0E37/)

Somehow that symbol modifies the previous one `.`. I don't know how to handle that.

> Could you help handle this weird case? lol

No, not quickly. I will have a look what we can do with it, though.

**Comment by bellmcp** [comment]
Hope it gets fixed soon, Thanks a lot for your help.

**Comment by DanPristupov** [comment]
Most likely this was fixed in 2.38
