### ISSUE TITLE
[Feature] Using Fork over an SSH connection

### ISSUE THREAD

**Issue by whomwah** [ForkIssues/Tracker#1619]
Hi, just wondering if anything like this kind of functionality is in the pipeline (or maybe it exists and I've not found it). Basically I am currently working on a project where the codebase lives on a remote server. In VSCode for example I can use their remote explorer to edit and update the code. I'd like to be able to do the same sort of thing for version control using Fork rather than the git integration that VSCode supports?

**Comment by flit** [comment]
That's what git remotes are for. Fork doesn't need to do anything; it's already supported by git.

**Comment by whomwah** [comment]
Fair point staring right at me!

**Comment by whomwah** [comment]
Although worth noting whilst this will work for some things it's not the same as having as I described in VSCode. Any file changes on the remote repo are not instantly reflected in Fork. You would still need to pull in those changes.
