### ISSUE TITLE
Support for KDiff3 and DiffMerge

### ISSUE THREAD

**Issue by bishtawi** [ForkIssues/Tracker#162]
Hi,
Great piece of software! Similar to #4, I would like to request support for the merge tools [KDiff3](http://kdiff3.sourceforge.net/) and [DiffMerge](http://www.sourcegear.com/diffmerge/)
Thanks!

**Comment by dogoku** [comment]
Yes this

**Comment by DanPristupov** [comment]
Added support for KDiff3 in Fork 1.0.62

**Comment by opotapov-sygic** [comment]
Also voting for DiffMerge here :)

**Comment by DanPristupov** [comment]
@opotapov-sygic just added DiffMerge in 1.0.63.

**Comment by opotapov-sygic** [comment]
Thanks a lot!
