### ISSUE TITLE
[Feature]  List of commit - copy to Clipboard

### ISSUE THREAD

**Issue by pinochico** [ForkIssues/Tracker#1622]
Simetimes I need copy list of selected commits and send to client as info about deploy.

Yes, now I can select a more then one commits in view, but I can't copy to Clipboard

**Comment by DanPristupov** [comment]
<img width="313" alt="Screenshot 2022-06-16 at 8 56 00" src="https://user-images.githubusercontent.com/618115/174010407-eafdcde0-ca81-4cd2-bdc5-79c3c7e6710d.png">

**Comment by DanPristupov** [comment]
You can also hold ⌥

https://user-images.githubusercontent.com/618115/174010909-1277181a-4e12-458e-882d-e4fb286784db.mov

**Comment by pinochico** [comment]
yes,

copy Commit SHA == result:

cdc9309cfd6b0420a8ad59ff577dc688a61ee604
151e04d361941c46850ca3383d0d67d37d89b56f
34f4ae2c22c50fd5cf4082d18a4dd1eca954c55d
0443c15b59b148e77b6756591eb312198d54229d
0c67f3eac7f09779c621fe4a0f627311c9e2a41c
f7ecbd3205fd756f739d518f7fca5581d4c2fea2
c47eea7b38ccf2139e98b96cc8ec2ed1d91dec22
2ccd131be3beb94df96fe4d8a4c1f9060fb80523
2c53de0b78f6d9b5ba46bd11cbf004c06b31ecd9
4229d88b1b13173b490e8bedcd49e1debb185dab
a0d51de3d528bb8ef36ca58fadde90037102c1d3
98c54c1a0678338e2fa098caffe2a34b9157eeeb
2c6761976bad5c941fcd98041dd8631fae4a8fa4
001e24a5352c73a0c58ef1abae5c0c4cb7118333
1076de2253f044eda9ce3bf6b614f936c69a7274
1a3d04059ebe5f4a41fc6470c0f21dfe176effbe
16de820452474615b9b7b0d1e63e208e76620303
d583c574de90547016f6f07dea36db25b37ffd1e
54b367c020affbab684f3af132be047cd11f9c66
0bba0d87ddaf278f8ddf75383df91afcc0277beb
cbfe82de53b2b34ad217b14c22b65ff9d5578553
5137a371262475f4e283ec173b9f4eed5e154c93
bf44d48b250a684f38e11f9253c592a9f71ce249
8dd9fdc0f7a737d39160935552ad0d37528d5347
e5378d7c296b3b254e3e6dfcdad553f271d8bcd6
a10c4b9373ec5443417c6825c8fec2d112e5237b
b62b1f65968c785c8c799fe6852e3c88ca5ae55f
109ad7c94cb8c82a9e9a82e4fe16fe899ba0b741
0b342d4081ce8684b4a73d9d4e5aa149438addbc
ff84a67b42992aca55e62c3a221c199d0e0f5e32
2ac41fe15f34b4c28a0edf912557049da610549c
8ebd28d588347d53504dac3210b424a94eb2aaa2

I need this result:

Instalace češtiny pro n3tCookieConsent RC 0.0.6
Instalace n3tDebug 4.1.0
#23816 - Instalace n3tCookieConsent rc06
Smazani check24347.php a přidání do gitignore
#24712 - Přidání podmínky pro base price a sales price
#24712 - Přidání elementu pro štítky, úprava featured
Smazání CF Last version
Uprava gitignore
#25052 - změna počtu dní
#25052 - informační email o nedoběhnutí předchozího importu
#25052 - tvorba kontroly error products
24912 - přidán log o finálním stavu importu
#16634 - instalace com_geolocator
#16634 - chyba opc_captchy - oprava
Úpravy casrouselu, překlady
#16634 - úpravy captchy
#16634 - Upgrade VM core funkcí na novější verze
#16634 - #17283 - Oprava chování Recaptcha - přidání reset
#16634 - Hack - zakázání odeslání SPAMU - Kontaktní formulář prodejce
#16634 - Hack - zakázání odeslání SPAMU - Kontaktní formulář prodejce
#16634 - aktualizace opc_captcha
Nezagitovaná úprava mod_virtuemart_product_extended - šablona carousel
#17348 - nasazení fixe pro customfields od Maxe
Revert "#17348 - nasazení fixe pro customfields od Maxe"  
#17348 - nasazení fixe pro customfields od Maxe
#24526 - rozšíření podmínky discontinued
#23298 - Hlídací pes - úprava šířky select boxu
#23298 - přidání hodnotu z nastavení db
#23735 - úprava cesty owl js a css souborů

**Comment by pinochico** [comment]
aha. I see now :)

you can close this
