### ISSUE TITLE
Status field in tool bar collapsed on MacOS 13 beta

### ISSUE THREAD

**Issue by idrougge** [ForkIssues/Tracker#1624]
The status field is collapsed to a single overlapping line on MacOS beta. I don't know if this should be reported in Apple's feedback assistant or here.

![image](https://user-images.githubusercontent.com/17124673/174619016-4f7d0889-f158-4260-9d03-967c46d02044.png)

**Comment by DanPristupov** [comment]
Previously people from A told me to not worry about that. So, let's wait for an update first.

**Comment by DanPristupov** [comment]
This issue is fixed when I build Fork with XCode 14 beta, so we just have to wait for it to be released.

**Comment by seia-soto** [comment]
So, this will be fixed with macOS Ventura release?
