### ISSUE TITLE
Not showing the green tag after checking out a remote branch

### ISSUE THREAD

**Issue by saminmel** [ForkIssues/Tracker#1627]
Version 2.19.2
After checking out a remote branch, the green tag for remote branch is not showing
![image](https://user-images.githubusercontent.com/5424363/175183715-6c0815e9-2144-42b8-958e-d20bbb29d7a6.png)

**Comment by saminmel** [comment]
Oh I just realise that the icon sitting before the branch name tag is indicating which commit the remote branch is at. 
So is it intentional in the new version that the green tag is removed for remote branch when local and remote branch are at the same commit?
![image](https://user-images.githubusercontent.com/5424363/175187037-2b26402a-0bd6-49ce-a76a-e88ba6f072fc.png)

**Comment by DanPristupov** [comment]
> So is it intentional in the new version that the green tag is removed for remote branch when local and remote branch are at the same commit?

Yes, it is. The feature can be disabled in preferences, if you don't like it.
