### ISSUE TITLE
GitHub SSO/SAML fails to authorize

### ISSUE THREAD

**Issue by kieranparsons** [ForkIssues/Tracker#1628]
When using OAUTH to GitHub and selecting normal organizations, everything seems fine. But, if I select an organization that enforces SAML/SSO then it doesn't work (just get rolling cursor).

**Comment by DanPristupov** [comment]
> if I select an organization

Where?

**Comment by DanPristupov** [comment]
Can the following be useful?

> ### About OAuth Apps, GitHub Apps, and SAML SSO
> 
> You must have an active SAML session each time you authorize an OAuth App or GitHub App to access an organization that uses or enforces SAML SSO. You can create an active SAML session by navigating to https://github.com/orgs/ORGANIZATION-NAME/sso in your browser.
> 
> After an enterprise or organization owner enables or enforces SAML SSO for an organization, and after you authenticate via SAML for the first time, you must reauthorize any OAuth Apps or GitHub Apps that you previously authorized to access the organization.
> 
> To see the OAuth Apps you've authorized, visit your [OAuth Apps page](https://github.com/settings/applications). To see the GitHub Apps you've authorized, visit your [GitHub Apps page](https://github.com/settings/apps/authorizations).

https://docs.github.com/en/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/about-authentication-with-saml-single-sign-on#about-oauth-apps-github-apps-and-saml-sso

**Comment by kieranparsons** [comment]
I was already signed in to an active SAML session, so this doesn't help unfortunately.

See screenshot below. The top and bottom orgs are not SAML. The middle one is. When I click the Grant button I get the rolling cursor forever.
<img width="519" alt="Screen Shot 2022-06-24 at 3 06 47 PM" src="https://user-images.githubusercontent.com/54148619/175649614-6f49602e-5928-4560-8619-8e788da430ef.png">
