### ISSUE TITLE
Pull cannot specify branch in new version of Fork

### ISSUE THREAD

**Issue by youyou015** [ForkIssues/Tracker#1629]
OS: Mac
Version: 2.19.2

Click Pull button will pop up dialog to select remote and branch, but select branch not take effect on final git command, git command actually always like this: `git pull --rebase=false origin --prune --verbose`. This will make it pull all branch and will take very long time when my repo is very big.
The older version didn't have this issue.
Thanks.

**Comment by DanPristupov** [comment]
I couldn't reproduce what you said. The selected branch is taken into the git command.

- Pull does NOT specify branch when the active branch is selected. This is the equivalent to `git pull` command which fetches all branches.

- When you change a branch, the dialog will specify the branch. The command will become `git pull $remote $remoteBranch`, which fetches only the active branch.
