### ISSUE TITLE
Search in file changes or diffs

### ISSUE THREAD

**Issue by pwxn** [ForkIssues/Tracker#163]
Feature request: search for a string in the file changes of all commits instead of just the commit message. 

Possibly a dropdown arrow on the search icon where a search type could be chosen.

Apologies if there is already an issue or this is on the roadmap already, but I was checking out Fork and thinking of switching from sourcetree, but this is a feature it has that I often use.

**Comment by p3l6** [comment]
This was added in Fork (Mac) 1.0.92. 
Thanks!
