### ISSUE TITLE
Git flow - finish release does not show correct value

### ISSUE THREAD

**Issue by xdarka** [ForkIssues/Tracker#1630]
Hello,

When I want to finish my release branch but there are multiple ones pending, it does not display the correct value (cfr. attached files). In addition, if I do not change the value in the popup, it finish the value previously selected. 

I was a bit confused at the begining because I though I finish the wrong one 😅

I'm working with submodules but it seems to be not related.

Regard,

MacOS: 12.4
Fork: 2.19.2

Selecting :

![Screenshot 2022-06-27 at 11 34 20](https://user-images.githubusercontent.com/30314009/175909586-07d04623-48a0-4bdf-91a9-71a89bdfa68b.png)

Popup message with wrong display:

![Screenshot 2022-06-27 at 11 34 33](https://user-images.githubusercontent.com/30314009/175909581-75e7f4b9-aeed-4cfd-b089-942593f14531.png)

**Comment by DanPristupov** [comment]
I think gitflow doesn't allow multiple release branches.

P.S. I'd recommend to NOT use gitflow and manage your branches manually. It's not that hard :).

**Comment by xdarka** [comment]
Sorry for the late 🙃

I was not aware about that but thank you for the reply

**Comment by DanPristupov** [comment]
Check 'Lean branching' in Fork as an alternative. It may fit your workflow.
