### ISSUE TITLE
interesting commit-list

### ISSUE THREAD

**Issue by ppuschmann** [ForkIssues/Tracker#1634]
Hi,

opening a freshly cloned repository left me at a first a bit lost, but then I found out I had to scroll downwards a lot...

What did I do?

1. in my CLI: `git clone git@github.com:cortexproject/cortex.git`
2. open repository in `fork`
3. scroll a lot for actual commits to `master`

Fork: 2.19.2

Maybe this is no real problem but intended behaviour? 

![SCR-20220630-nfh](https://user-images.githubusercontent.com/3431761/176708706-4efec2d1-86f9-4244-bfbb-1709b6aa9a4f.png)

![SCR-20220630-ned](https://user-images.githubusercontent.com/3431761/176708563-4375b50c-371d-4313-877e-b155f9f06175.png)

**Comment by DanPristupov** [comment]
Sorry for the delay. I missed your question.

The repository has two trees. In other words, there are two independent repository stored in one. Usually it's made to store source code and the website in the same repo.

For example React (http://github.com/facebook/react) used to have source and jekyll-based website histories separated in the same repo.

**Comment by DanPristupov** [comment]
You can create a new root using `git checkout --orphan newbranch` command. It's rarely needed in daily life and Fork doesn't have a UI for it.

https://shannoncrabill.com/blog/git-orphan-branches/
