### ISSUE TITLE
Repository Statistics not rendering

### ISSUE THREAD

**Issue by Manduro** [ForkIssues/Tracker#1637]
In the top menu on macOS, I go to Repository > Repository Statistics... and the following shows up:
![Screenshot 2022-07-07 at 13 55 07](https://user-images.githubusercontent.com/2545042/177767709-4d59106b-6b1c-4f91-bac2-caf5d84f2d9e.png)

I'm on version 2.19.2, Git instance is the 2.36.1 Fork instance.

**Comment by DanPristupov** [comment]
Hi,

We'll fix that in the next update.
