### ISSUE TITLE
Some shortcuts are broken since latest update 2.19 & 2.19.1 on macOS

### ISSUE THREAD

**Issue by igoooor** [ForkIssues/Tracker#1638]
Hi,

I use these shortcuts frequently:
`⌘` + `1` - to open "Local Changes"
`⌘` + `2` - to open "All Commits"
`⌘` + `shift` + `D` - to "Discard Changes..."

Since the latest update (2.19 & 2.19.1) these won't work.
Only the "Discard Changes..." shortcut works when I enable Caps Lock, but that's kind of annoying ^^

**Comment by DanPristupov** [comment]
That's weird. Do you use any non-default keyboard settings?

**Comment by igoooor** [comment]
I don't think so, I have standard a mac keyboard (french layout though, it's "Azerty"). But it used to work fine before the update.

**Comment by igoooor** [comment]
oh and when I try to use the shortcut to "Discard Changes..." (`⌘` + `shift` + `D`) it opens the "External Diff" which is bound to the shortcut (`⌘` + `D`) (and that shortcut still works, it also open the "External Diff")

**Comment by DanPristupov** [comment]
Do you use a non-English keyboard layout?

**Comment by DanPristupov** [comment]
Could you check if the problem is fixed here? https://cdn.fork.dev/mac/Fork-2.19.2.dmg

**Comment by igoooor** [comment]
It's fixed in the 2.19.2 thank you :)
