### ISSUE TITLE
Large file preview causes app to freeze

### ISSUE THREAD

**Issue by DougSisk** [ForkIssues/Tracker#164]
We push our compiled JavaScript to Git and often Fork will automatically select this single line compiled file. It tries to preview it, which causes the app to completely freeze up. I have a 2014 15" MBP with quad core 2.8 GHz i7, so hardware definitely isn't the issue.

I'm not sure of a sensible way of handling this situation, but any ideas to remedy would be appreciated. I love Fork, but this issue is quite major for me and forces me to use another app for projects that have large compiled files.

**Comment by DanPristupov** [comment]
Hi Doug. Thank you for describing the problem in details. I'm considering this as a top-priority task for this week. Going to fix it in the next update.

**Comment by DanPristupov** [comment]
@DougSisk I just released Fork 1.0.60 which contains improvements for this case. Could you please check it?

**Comment by DougSisk** [comment]
Works great! Thank you!
