### ISSUE TITLE
[Feature Request] Show when commits have descriptions in main list

### ISSUE THREAD

**Issue by ghost** [ForkIssues/Tracker#1640]
It would be nice if commits had an indicator of some sort in the main commit list to help identify at a glance if commits have more information than just their subject (in repositories where commit descriptions are not often used.) This would be helpful when users don't generally tend to have the commit details view open all the time. 

GitLab has something like this already when viewing commits on the web, as in this image. The three dots button opens and closes the description.

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/70993406/178379572-d426b2c3-c760-489d-892a-ea0eacf5d35f.png">

(Apologies if this FR already exists, perhaps with a different name. I could not find anything before I created this.)

**Comment by DanPristupov** [comment]
While I'd like to have that feature myself, I don't know a way to request that info from git. I think it's not possible without requesting full message for each commit, which would dramatically impact the overall performance.

**Comment by ghost** [comment]
Oh well, thanks for replying anyway :)
