### ISSUE TITLE
"Create Pull Request" computes incorrect PR url

### ISSUE THREAD

**Issue by finestructure** [ForkIssues/Tracker#1641]
"Create Pull Request" has recently started generating PR URLs that lead to 404s in Github. For example:

https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server.gi/compare/doc%2Darchives%2Dbased%2Ddoc%2Durl?expand=1

Looking at the URL, you'll notice a partial `.git` suffix: `...-Server.gi/...`. If I remove the `.gi` fragment, the URL works fine.

I believe this started happening because I renamed my upstream to `_🐙_` in order for it to stand out.

I wonder if there's perhaps some string handling going on that doesn't take into account that `🐙` is multi-byte, leading to an incorrect string offset?

Note that the PR is correctly created, it's just the URL that Fork is generating to open in the browser that's wrong.

**Comment by DanPristupov** [comment]
Hi!

> I wonder if there's perhaps some string handling going on that doesn't take into account that `🐙` is multi-byte, leading to an incorrect string offset?

You are absolutely right.

Could you check it that build works properly? https://cdn.fork.dev/prerelease/Fork-2.19.10.dmg

**Comment by finestructure** [comment]
It does! Thanks a lot for the quick fix ❤️
