### ISSUE TITLE
[Feature Request] reverse from commit diff file list, hunk based like sourcetree.

### ISSUE THREAD

**Issue by yam-liu** [ForkIssues/Tracker#1642]
When I need revert specific diff from commit, I can use sourcetree to revert some hunk (or whole file in "..." button). 
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/1056803/178915928-1b88ea75-c33b-4327-ac5c-1f6a655939ce.png">

**Comment by DanPristupov** [comment]
I think this is a duplicate of https://github.com/fork-dev/Tracker/issues/1280
