### ISSUE TITLE
per-repository commit template gone after update

### ISSUE THREAD

**Issue by kambala-decapitator** [ForkIssues/Tracker#1652]
I have different commit templates configured in repos which had been working for a long time. Yesterday I upgraded from v2.17 to 2.20.1 through develop channel and all my templates are gone.

**Comment by DanPristupov** [comment]
Thank you for reporting that. I'm investigating the problem.

**Comment by DanPristupov** [comment]
I'm releasing the hotfix.

**Comment by DanPristupov** [comment]
I've just published the `2.20.2` hotfix.

Please check for updates (Fork -> Check for updates).

**Comment by kambala-decapitator** [comment]
the functionality is restored. thanks a lot!

**Comment by DanPristupov** [comment]
Thank you very much for reporting the problem in the first place 👍
