### ISSUE TITLE
graph disappear 

### ISSUE THREAD

**Issue by Gu3** [ForkIssues/Tracker#1654]
Hi ! 
For one of my project the graph is gone :/  Tested with git Kraken : all good. 
Mac + Version 2.20
Thanks ! 

![image](https://user-images.githubusercontent.com/5227741/179786353-8ecabccf-1b6d-4920-817e-4b46b07b3c0b.png)

**Comment by DanPristupov** [comment]
Check if the log file has any warnings or errors: %localappdata%\fork\logs\fork.log

I guess, it can be the same issue: https://github.com/fork-dev/TrackerWin/issues/1544#issuecomment-1134752037

It looks like git has introduced some bug with binary compatibility which happens on a very few machines.

Regarding the solution: try to switch Fork to your system git instance.
