### ISSUE TITLE
Noticeable slowdown with huge folder in gitignore when using shortcuts

### ISSUE THREAD

**Issue by homm** [ForkIssues/Tracker#1655]
I have a folder (6,76 GB on disk) with 103 615 items in my working git repo, it added in `.gitignore`.

Fork UI freeze for a two seconds when I switch views by keyboard shortcuts. For example, by pressing ⌘1, ⌘2, ⌘T, ⌘+shift+[. The same actions done through the main menu, or UI, doesn't lead to noticeable slowdown, only shortcuts.

Deleting this folder or closing the repo normalizes performance.

**Comment by DanPristupov** [comment]
Not sure if the issue still exists, but we couldn't reproduce it today.

**Comment by homm** [comment]
luckily I'm working on the same project right now and after a while, I'll say if this bug is still present )

**Comment by homm** [comment]
I don't experience any slowdown for now. Thanks
