### ISSUE TITLE
"temporary branch" is not showing up

### ISSUE THREAD

**Issue by haifengkao** [ForkIssues/Tracker#1657]
I am following the tutorial here. 
https://simplabs.com/blog/2021/05/26/keeping-a-clean-git-history/

But I can't get "backup current state with temporary branch" to work. 
<img width="1360" alt="截圖 2022-07-22 下午6 37 06" src="https://user-images.githubusercontent.com/4080524/180422400-35cb5b29-6382-4481-a624-26926fb9b882.png">

The temporary branch doesn't show up at all

<img width="1086" alt="截圖 2022-07-22 下午6 37 16" src="https://user-images.githubusercontent.com/4080524/180422138-66373504-834d-4757-a3cd-1a25698dd030.png">

What am I missing?

**Comment by DanPristupov** [comment]
That's weird. Is there any warning or error in the log file `~/Library/Logs/Fork.log` may be?

**Comment by haifengkao** [comment]
<img width="884" alt="截圖 2022-07-22 下午7 23 03" src="https://user-images.githubusercontent.com/4080524/180429353-9a62c0ca-e92b-478e-9b00-d4063b2c94d9.png">

@DanPristupov  A space in the backup branch name?

**Comment by DanPristupov** [comment]
Yes, we must remove spaces.
We'll fix that in the next update.

If it's urgent, I can make you a private build tomorrow.

**Comment by haifengkao** [comment]
That's OK. I am just starting to  learn Fork.
