### ISSUE TITLE
Cannot add a new tag that begins with "@"

### ISSUE THREAD

**Issue by james246** [ForkIssues/Tracker#1665]
**Expected Behavior**

Able to add a new tag with any characters in the name

**Current Behaviour**

Unable to add a new tag if the name begins with a `@` character. All other characters appear to work as intended.

Steps to Reproduce

1. Right click any commit
2. Click `New Tag...`
3. Enter `@` as the first character in the `Tag name` field. The character will not be entered into the field. On MacOS the system "boop" sound effect is heard, as an audible indication the action is not permitted.

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/Tracker/issues/1236
