### ISSUE TITLE
HTTPS is not available as a login protocol for Github Enterprise

### ISSUE THREAD

**Issue by diosmiodio** [ForkIssues/Tracker#1667]
Hi!

I've been loving Fork for personal use, and I'm now trying to use it with my git enterprise account. Seems I can't setup a clean machine since it wont allow me to login using the HTTPS protocol (which is required for our company).

When providing my access token, I receive a `cannot parse JSON in server response` error. I can get around it by authenticating in other ways, but thought you all should know this is an issue. Thanks so much for making such an awesome git GUI! ☺️

Best,
Dio

**Comment by DanPristupov** [comment]
What error do you see in the fork log? The log is located at `~/Library/Logs/Fork.log`

https://github.com/fork-dev/Tracker/issues/1594#issuecomment-1126714818
