### ISSUE TITLE
Cannot navigate to commit parent

### ISSUE THREAD

**Issue by macness-pavelh** [ForkIssues/Tracker#1669]
Sometimes clicking on the parent SHA in the commit detail panel does not work and UI does not navigate to the parent commit. The issue then does not recover until I restart the app.

I cannot reproduce step by step - but if I keep the app running for a while, it always ends up in that bad state.

Using Fork for Mac, Version 2.20.2

**Comment by DanPristupov** [comment]
Do you still experience this issue?

How large is your repository? Fork loads 50000 commits but default, is it possible that this commit is out of the range?

**Comment by macness-pavelh** [comment]
Hey, I did not see it for a while. But I'm not using that feature so heavily. Our repo defo does not have 50k commits.
