### ISSUE TITLE
Delete branch command succeeds, but then displays error message

### ISSUE THREAD

**Issue by masonmark** [ForkIssues/Tracker#167]
Often (but not always) when I delete a branch, and leave the "Delete remote branch:..." checkbox checked, everything seems to work, but Fork displays an error dialog in a sheet, showing the result. (See screenshot.)

![image](https://user-images.githubusercontent.com/122212/33172463-9592ec34-d093-11e7-922e-8506973a1e22.png)

Fork 1.0.59.5, but it has been happening for the last few versions.

**Comment by ole** [comment]
I'm seeing this too.

**Comment by DanPristupov** [comment]
It looks like the warning was cut and the message became misleading.

Quick googling got me the following: https://stackoverflow.com/questions/17903739/warning-message-deleted-branch-skin-was. I suppose I can ignore this warning and don't bother user at all.

**Comment by domagojb** [comment]
I found how to reproduce this. 

This happens when you delete a local branch whose tracking (origin) branch had been deleted and check the "Delete remote branch" checkbox.

**Comment by DanPristupov** [comment]
I fixed few problems there and also improved the error messages to be more clear. The changes will be available in the next update.
