### ISSUE TITLE
Cmd-S keyboard shortcut to Stage files no longer works

### ISSUE THREAD

**Issue by Jaaap** [ForkIssues/Tracker#1674]
⌘-S (Command-S) no longer stages a file in Version 2.21 for macOS.

**Comment by DanPristupov** [comment]
Do you hear a beep sound when you press ⌘S?

**Comment by Jaaap** [comment]
Yeah it makes a beep sound like it's a non-existing key combo

**Comment by DanPristupov** [comment]
That's weird.
Does the Enter key work as a replacement?
Are you sure you press Cmd+S and not Cmd+Shift+S?
Does ⌘S work in the opened file context menu in Fork?
<img width="250" alt="Screenshot 2022-08-22 at 15 17 03" src="https://user-images.githubusercontent.com/618115/185930387-e20a77bf-b742-434d-9301-c87046f721e8.png">

**Comment by Jaaap** [comment]
Enter key works yes.
I press Cmd-S.
Cmd-S does not work in the context menu either.
<img width="222" alt="image" src="https://user-images.githubusercontent.com/243016/185934669-e275047f-6e48-4811-a6b9-122a3f236db6.png">

**Comment by gkopff** [comment]
@DanPristupov Did the keyboard short-cut change from `CMD-Shift-S` to just `CMD-S` recently?  My muscle memory has me doing `CMD-Shift-S` for staging and `CMD-Shift-D` for discarding.

**Comment by DanPristupov** [comment]
@gkopff It means, you are a very old user:). Yes, initially it was `Cmd+Shift+S`. I couldn't find a reason why we'd chosen it instead of `Cmd+S`, but probably that was a mistake. When I realized that in July 2017, I added `Cmd+S` and made sure the UI mentions `Cmd+S` only. I also kept `Cmd+Shift+S` as a fallback. Now, 5 years later, we removed `Cmd+Shift+S`.

**Comment by gkopff** [comment]
@DanPristupov well, I hope it doesn't take me 5 years to _unlearn_ it. ;-)

(❤️ fork and couldn't live without it!)

**Comment by craigotis** [comment]
Hah, my muscle memory brought me here also - I didn't see the removal of `Cmd+Shift+S` in the release notes, so thought I was going crazy.

**Comment by sebleclerc** [comment]
Same here 🙋‍♂️ For sure I'll have to un-learn my muscle memory 😅
