### ISSUE TITLE
Fork is slow these days...

### ISSUE THREAD

**Issue by mtschoen-unity** [ForkIssues/Tracker#1676]
Hi there!

This is a difficult one to diagnose, but I have noticed pretty much every action in Fork taking a lot longer than it used to. I don't think it's about network latency, because things like creating branches, viewing changes, etc. which are just local are also taking multiple seconds, when I recall them being more or less instant. I work on a variety of repo sizes, and even on really small repos things seem to be slow. I can't say exactly when this started happening, but I just updated, and it is the case in at least the last two versions. Maybe it's a MacOS update? I don't think the whole computer has gotten slower, but I was reading about another speculative execution vulnerability which may have been patched and affected things somehow.

How should I go about diagnosing the issue? Are the logs detailed enough to tell me what operations are taking the longest amount of time? Has anyone else experienced this issue?

Edit: I don't think it's git itself, either. CLI equivalents to the slow Fork actions seem to happen instantly, or at least a lot faster than they do in Fork.

**Comment by DanPristupov** [comment]
> How should I go about diagnosing the issue?

Did you try to restart the computer?

> Are the logs detailed enough to tell me what operations are taking the longest amount of time?

Fork must log requests which take longer than expected. Can you send the log (~/Library/Logs/Fork.log) to support@fork.dev?

**Comment by mtschoen-unity** [comment]
Yeah I've done a restart and tried to clean out caches and things like that.

I'll do another restart when I'm done with work and try to capture a clean log of slow requests. From a brief skim there's nothing out of the ordinary there, but I'll send it over either way.

**Comment by mtschoen-unity** [comment]
I've sent over a log capturing some slow actions. It looks like maybe `git status` is the slow thing? I see things like `◽️[Stopwatch.swift:42] >  6083 RefreshRepositoryDataGitCommand` in the log. Should I read that to mean "RefreshRepositoryDataGitCommand took 6.083 seconds"?

**Comment by mtschoen-unity** [comment]
Welp. After switching to my Windows machine for a bit and coming back to the mac... Fork is fast again. I think there may have been some XCode/OS updates in between that fixed the issue. If it comes back I'll re-open this.
