### ISSUE TITLE
Fork is creating a backup/<branch>-<time> branch every time I do a rebase.

### ISSUE THREAD

**Issue by gkopff** [ForkIssues/Tracker#1679]
The problem:

I rebase *a lot*, and Fork has started creating backup branches for me.  I can't find an option to turn this off.  They're a huge distraction as they make commits that are obsolete stick around.  (If I wanted to find those commits, I'd check the reflog).

The solution:

Have an option to disable this feature.

Version:

Fork 2.21

**Comment by DanPristupov** [comment]
> Have an option to disable this feature.

Check the left-bottom corner of the IR dialog.

**Comment by gkopff** [comment]
I see it! Thanks!
