### ISSUE TITLE
[Feature request] Add "Copy Filename" to file context menu

### ISSUE THREAD

**Issue by ElfSundae** [ForkIssues/Tracker#168]
![image](https://user-images.githubusercontent.com/526008/33233748-e5363c32-d255-11e7-8de1-484a21f31381.png)

Could you please add a "Copy Filename" item in this context menu?
Thank you. ❤️

**Comment by DanPristupov** [comment]
I'll add a 'Copy filename' alternative action which will appear when user presses the `option` key (same as other alternative menu actions).

**Comment by ElfSundae** [comment]
I am very glad to hear this, thanks. 
And in my opinion, for "Copy Filename", a standalone menu action would be better than an alternative one. Both OK, you decide : )

**Comment by DanPristupov** [comment]
A added an alternative (⌥) menu item to all menus in 1.0.60.

Regarding a separate item. I'd rather not add another item to context menu. Otherwise it can end up like a mess in the revision menu (https://github.com/ForkIssues/Tracker/issues/113).

**Comment by ElfSundae** [comment]
Done 🎉
