### ISSUE TITLE
[Feature request] Add "Open in <custom app"

### ISSUE THREAD

**Issue by iosdevben** [ForkIssues/Tracker#1680]
I frequently use the Open In Terminal command so I can quickly get to the root of the repository, then I type `code .` to open my repo in Visual Studio Code.

It occurred to me that this could be streamlined if Fork allowed you to specify a preference for another app to open the repo. 

Please consider my idea.

I also less frequently use the Open In Finder command, which is also very useful.

**Comment by DanPristupov** [comment]
> I frequently use the Open In Terminal command so I can quickly get to the root of the repository, then I type code . to open my repo in Visual Studio Code.

The Open-in dropdown must already have the 'Open in VSCode' item, if you use the default distribution.

> It occurred to me that this could be streamlined if Fork allowed you to specify a preference for another app to open the repo.

Fork -> Preferences -> Custom Commands -> + -> Create Repository Custom Command

**Comment by iosdevben** [comment]
Hi Dan,
Thanks for the quick reply!

>The Open-in dropdown must already have the 'Open in VSCode' item, if you use the default distribution.

I can see the following options when I try to open a single file from a commit log, as shown in the following screenshot. Is that what you are referring to?
![image](https://user-images.githubusercontent.com/824608/187776300-2a2579bf-aed2-4202-aed8-6006c34b1dde.png)

I'll try a custom repository command.

**Comment by iosdevben** [comment]
Custom command works well:

![image](https://user-images.githubusercontent.com/824608/187779136-c7d0839e-c74e-4800-b1d0-48c75f23ab15.png)


I've also added a keyboard shortcut via System Preferences:

![image](https://user-images.githubusercontent.com/824608/187779004-163c8fe6-bfbd-42c3-8572-7ab358d518cb.png)
