### ISSUE TITLE
Disappearing "Unstage" button 

### ISSUE THREAD

**Issue by alustig3** [ForkIssues/Tracker#1681]
When hovering over a hunk, an "Unstage" button will appear. When I go to click the button, it will disappear after I cross a certain horizontal position. A workaround is to to make the window narrower so that the horizontal threshold is never crossed. Video attached:

https://user-images.githubusercontent.com/8128628/187792421-cc972d2a-eed5-4471-b01c-b3fd4b2bee7f.mp4

Restarting Fork seemed to fix it. I am unable to replicate the problem at the moment

**Comment by DanPristupov** [comment]
Thank you for reporting that. I didn't know such a problem exists. I will take an attention now.
