### ISSUE TITLE
Rebase is hidden in commit context menu when filter is enabled

### ISSUE THREAD

**Issue by TommasoAmici** [ForkIssues/Tracker#1683]
I've noticed recently that sometimes the Rebase option is hidden in the main panel where git log is.

If I click on the sidebar where all branches are the option is still available though.

See screenshots below

<img width="781" alt="image" src="https://user-images.githubusercontent.com/424525/188854113-54196588-2e0d-4300-9e07-c1591cbb0708.png">

<img width="735" alt="image" src="https://user-images.githubusercontent.com/424525/188854607-46c227ad-1f05-47f3-a4f4-92a00f1608aa.png">

**Comment by DanPristupov** [comment]
That's weird. The rebase and merge context menu options disappear only when there's no active branch (i.e. when repo is in `detached HEAD`), however on your screenshot I see that there IS an active branch.

Do the menu items appear if you restart Fork?

**Comment by DanPristupov** [comment]
Fork also hides rebase and merge for branches which are already merged into the active branch. Again, on your screenshot, origin/master is not reachable, but there can be a bug.

Do you have an enabled filter may be? If so, try to disable it.

**Comment by TommasoAmici** [comment]
> Do you have an enabled filter may be? If so, try to disable it.

Yeah, that's it. I cleared all filters and now I see the option to rebase again. This is a big repo with more than 1000 branches so the filters are very convenient

**Comment by DanPristupov** [comment]
Then, I guess,  it's a bug which we have to fix :).

Could you confirm that the problem gets back when you enable the filter, please?

**Comment by TommasoAmici** [comment]
Yes, toggling the filters on removes rebase, toggling them off makes it reappear. See video attached


https://user-images.githubusercontent.com/424525/188872705-8614a307-c9c8-4af1-a69e-702896524840.mp4

**Comment by DanPristupov** [comment]
Fixed in 2.22

**Comment by TommasoAmici** [comment]
Indeed, thanks for the quick fix!
