### ISSUE TITLE
Repository Status in toolbar overlaps text in Icon and Text mode

### ISSUE THREAD

**Issue by kavon** [ForkIssues/Tracker#1689]
I appreciate that the toolbar supports showing both the icon and text. But when that mode is enabled while viewing a repository, the status bar at the top shows the repository name overlapping with the branch name:

<img width="517" alt="Screenshot 2022-09-13 at 9 07 14 PM" src="https://user-images.githubusercontent.com/188095/190057784-93f2ee51-f450-4e1b-b656-3a4cc6a346f2.png">

when setting it to Icon only, its working OK:

<img width="517" alt="Screenshot 2022-09-13 at 9 07 24 PM" src="https://user-images.githubusercontent.com/188095/190057825-ca222cf4-8f40-490f-aa7c-480eea0a053b.png">

seems to happen regardless of having increased contrast or other system-wide accessibility settings. I'm on macOS 13.0 beta using Fork 2.21.

**Comment by seia-soto** [comment]
I can confirm this on macOS 13.0 (22A5342f) using Fork 2.21 too.

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/Tracker/issues/1624
