### ISSUE TITLE
Dark theme: scrollbars invisible

### ISSUE THREAD

**Issue by rothkj1022** [ForkIssues/Tracker#169]
Scrollbars are not visible using the dark theme.

<img width="545" alt="screen shot 2017-11-28 at 9 14 27 am" src="https://user-images.githubusercontent.com/1591839/33327269-b1a91c18-d41c-11e7-9ecd-7233616d81a9.png">

**Comment by DanPristupov** [comment]
@rothkj1022 Hi. Thank you. Will fix in the next Fork update.

**Comment by DanPristupov** [comment]
@rothkj1022 this is fixed in 1.0.60. Please check for updates.

**Comment by rothkj1022** [comment]
Works great! Thanks a lot!
