### ISSUE TITLE
Copyright year display bug

### ISSUE THREAD

**Issue by marune-jp** [ForkIssues/Tracker#1690]
The year is displayed wrongly when the system is in japanese with era names turned on.
(0004 comes from this year, Reiwa 4)

<img width="229" alt="スクリーンショット 0004-09-14 22 03 33" src="https://user-images.githubusercontent.com/49405880/190161686-cbcc3c81-48bc-4027-9bf3-82cd7a15b50f.png">

**Comment by marune-jp** [comment]
BTW I did not say it because it seemed obvious because I am used to it (as a developer in Japan), but this comes from a wrong usage of the date/time formatter APIs provided by Apple.

FYI correct display would be something like `Reiwa 4`, `R4`, `令和４年`, or just `2022`.

**Comment by marune-jp** [comment]
Maybe try setting the calendar to Gregorian calendar `dateFormatter.calendar = Calendar(identifier: Calendar.Identifier.gregorian)`
or just omit your `.dateFormat` for the default one (or create one from a template)

**Comment by DanPristupov** [comment]
Hi, it's been a long time since you reported this minor bug, but we finally fixed it in Fork 2.30 :)

**Comment by marune-jp** [comment]
nice :)R5/06/26 15:32、Dan ***@***.***>のメール:﻿
Hi, it's been a long time since you reported this minor bug, but we finally fixed it in Fork 2.30 :)
