### ISSUE TITLE
Switching to Fork window when history is shown is very slow

### ISSUE THREAD

**Issue by mcdreamer** [ForkIssues/Tracker#1691]
Fork version 2.21. macOS 12.5.1.

- Show the history for a file
- Switch to another app
- Switch back to Fork

It can take several seconds for the Fork window to appear depending on the size of the history. The slowdown appears to scale up quite quickly with history size. This should be instantaneous.

Note, this delay can also be observed when initially showing the history as well.

**Comment by DanPristupov** [comment]
Could you send me the log file (~/Library/Logs/Fork.log) to support@fork.dev, please?

**Comment by mcdreamer** [comment]
Hi Dan,

As the log contains lots of information about our repository I'd rather not send this over as is. Are there any particular lines from the log which you'd be interested to know about?

**Comment by DanPristupov** [comment]
You can find-and-replace the repo and branch names. Not sure about the particular lines, it would be better to see the whole file.

If you restart Fork and just reproduce the problem, the file should be pretty small.

**Comment by mcdreamer** [comment]
I've just sent a small anonymised log file to your support email address.

**Comment by DanPristupov** [comment]
Is this issue still actual?

**Comment by mcdreamer** [comment]
Hi Dan,

Apologies for the delay. I've just tried this in 2.39.1 and can no longer reproduce the issue.
