### ISSUE TITLE
Refreshing the working copy is very slow

### ISSUE THREAD

**Issue by mcdreamer** [ForkIssues/Tracker#1692]
Fork 2.21. macOS 12.5.1.

When switching back to Fork from another app to observe changes to my working copy, Fork will show a progress spinner in the title bar for several seconds before animating the modified files into view. This occurs regardless of the number of files modified or the number of changes to these files. Even a single file with a single change exhibits this behaviour.

For reference, git on the command line shows these changes instantly. As Fork markets itself as a fast client I would expect at least this level of performance, if not higher, from the app.

**Comment by DanPristupov** [comment]
How large is your repository?
What is the output of `time git status --porcelain --untracked-files=all > /dev/null`

**Comment by mcdreamer** [comment]
The repository is 1.7GB (with 253MB in the .git directory).
The output of that command is: 0.25s user 1.82s system 154% cpu 1.335 total.

**Comment by DanPristupov** [comment]
> 0.25s user 1.82s system 154% cpu **1.335** total.

1.335 seconds is quite much.

1. Try to run `git gc` in the command line
2. Consider to use git fsmonitor-daemon (`git config --local core.fsmonitor true`)

https://git-scm.com/docs/git-fsmonitor--daemon/en
https://github.blog/2022-06-29-improve-git-monorepo-performance-with-a-file-system-monitor/

**Comment by mcdreamer** [comment]
`git gc` doesn't seem to have made much difference unfortunately. I will try the fsmonitor.

How large does a repository need to become before you would expect performance issues to start appearing in Fork? What range of repository sizes do you normally test with?

**Comment by DanPristupov** [comment]
Git doesn't work well with large binary files. So, repos > 1GB start being slow because to get the list of changed file `git status` must compare every byte in the project. That's why `GitLFS` has been created.

> What range of repository sizes do you normally test with?

Some notable ones:

- The Swift repo (500 mb) is very fast
- The VSCode repo (600 mb) is very fast
- The Chromium repo (> 20 Gb) is slower, but it's slow because of 'third_party' components (png files, in some of them, AFAIK).

**Comment by mcdreamer** [comment]
Thanks for the information. This repo uses GitLFS so hopefully binaries files won't be playing too much of a part here. Without the fsmonitor enabled, a git status on the command line takes around 0.15 seconds to execute which is why I hoped for, say, a sub-one second response from Fork.

I had a quick play with the Swift repo and, as you said, the performance with this is good.

As for the porcelain command above, does this suggest that artefacts from in-tree builds could be causing performance issues (even though they are .gitignored)?

**Comment by DanPristupov** [comment]
> As for the porcelain command above, does this suggest that artefacts from in-tree builds could be causing performance issues (even though they are .gitignored)?

I'm not 100% sure (i.e. I don't have a documented proof), but I think so.

Here is an .sh script which will help to find the problem place:

```
#!/bin/sh

for d in */ ; do
    echo "$d:"
    $(time git status --porcelain --untracked-files=all  -- $d)
done

exit 0
```

[status.sh.zip](https://github.com/fork-dev/Tracker/files/9582385/status.sh.zip)

**Comment by mcdreamer** [comment]
Thanks for this script. The directories with untracked and ignored build artefacts seem to be the ones adding the most to the time as suspected. I will use this information to consider whether we need to take a different approach here. Many thanks for your help.
