### ISSUE TITLE
 is it possible to have 'hide untracked files' activated by default ?

### ISSUE THREAD

**Issue by parmentelat** [ForkIssues/Tracker#1695]
I'd really like this feature, and could not spot it if it's already there 

it could be done either globally i.e. for all repos (good enough) or on a per repo basis

thanks for this amazing tool :)

**Comment by DanPristupov** [comment]
Hi,

That's a duplicate, I think (https://github.com/fork-dev/Tracker/issues/471)

**Comment by parmentelat** [comment]
indeed, closing then
