### ISSUE TITLE
Minor visual issue in macOS Ventura

### ISSUE THREAD

**Issue by izantech** [ForkIssues/Tracker#1698]
In macOS Ventura the branch name overlaps the repository name:
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/1703659/190899661-31cde66d-da00-4c81-af5c-22b224308a14.png">

**Comment by DanPristupov** [comment]
We'll fix that when Apple releases stable XCode for MacOS 13.
https://github.com/fork-dev/Tracker/issues/1624

**Comment by 2Grey** [comment]
@IzanRodrigo, as temporary solution you can fix it with:
View -> Customize Toolbar... -> Icon Only

https://imgur.com/gallery/5Wcx5U6

**Comment by izantech** [comment]
@2Grey It works, thank you!

**Comment by stone-zeng** [comment]
> @IzanRodrigo, as temporary solution you can fix it with: View -> Customize Toolbar... -> Icon Only

I found that in v2.23 `View > Customize Toolbar…` became gray so I can't edit it now.

**Comment by DanPristupov** [comment]
@stone-zeng yes, but toolbar must always be in the 'Icon only' mode.

**Comment by TheGlorySaint** [comment]
For me this Issue is with 2.23.1 fixed and displays now correctly.

**Comment by 2Grey** [comment]
@TheGlorySaint, I do not agree with you, there isn't default view with Icons and Title now, and you can't enable it.

**Comment by slatlasdev** [comment]
I am not experiencing the overlap issue mentioned above, but I want to be able to get the Icon & Text view back, as I prefer having the button labels there.

In other system apps in Ventura, like `Mail.app`, you can right click on the toolbar and choose Icon & Text, Icon Only or Text Only, or you can also use `View > Customize Toolbar...` as mentioned above.

However Fork doesn't do anything when you right click the toolbar, and the `View > Customize Toolbar...` option is greyed out.

I am running 2.23.1

**Comment by DanPristupov** [comment]
We couldn't make 'Icon and Text' work on macOS Ventura. There were some breaking changes in the macOS SDK which conflict with our large status toolbar control.
