### ISSUE TITLE
Character Limit too bright in dark theme

### ISSUE THREAD

**Issue by danez** [ForkIssues/Tracker#170]
When using the dark theme the character limit indicator in the commit box is to white in my opinion and should be actually darker than the border of the box.
![bildschirmfoto 2017-11-29 um 16 07 10](https://user-images.githubusercontent.com/231804/33381916-9a5f858e-d51f-11e7-853f-0295c6285c09.png)

**Comment by DanPristupov** [comment]
@danez yes, absolutely agree. Just fixed that in 1.0.60. Thank you

**Comment by danez** [comment]
Thank you, perfect now.

Thanks for the amazing tool.
