### ISSUE TITLE
"Edit Remote" does not change push URL

### ISSUE THREAD

**Issue by colececil** [ForkIssues/Tracker#1700]
When I use the "Edit Remote" feature to change the URL of the remote, it only changes the fetch URL - it leaves the push URL as is. I don't see anywhere in Fork to view or edit the push URL, so I'd assume it would change both of them.

I discovered this because I had accidentally configured my remote using HTTPS instead of SSH at some point before switching to Fork. I was getting authentication popups in Fork, at which time I realized the issue and changed the remote to use SSH. Then it was working fine for pulling, but I got the authentication popup again when I tried to push. Upon checking the repo's `.git/config` file, I saw that `url` was set to SSH, but `pushurl` was still set to HTTPS.

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/505#issuecomment-544137786
