### ISSUE TITLE
UI often hangs at "writing objects 100%" while pushing commits

### ISSUE THREAD

**Issue by richvreeland** [ForkIssues/Tracker#1706]
i've noticed that when pushing larger commits with lots of binary files, the UI often hangs when it reaches "writing objects 100%".

however going to the repo by some other method (ie. via github.com) shows that the commit has been successfully pushed. If i quit Fork and reopen it, it shows that the commit has not been pushed. But doing a pull always resolves the issue.

v2.22, Apple M1 Max Macbook Pro

**Comment by pauldrummond** [comment]
I'm having the same problems with v2.22.1 on Mac OS. Push gets stuck at 100% and the changes aren't seen on the repo.

**Comment by DanPristupov** [comment]
Does the problem occur all the time? Did you try to push from the command line (`git push`)?

**Comment by pauldrummond** [comment]
Yes, it happens every time. Same thing if I use the command line.

**Comment by pauldrummond** [comment]
I updated to the latest Git using Brew and told Fork to use this. Still the same result.

**Comment by pauldrummond** [comment]
I found the problem. The repository had been set up using HTTPS instead of SSH, so was failing on large file transfers. Changing to SSH fixed it.
