### ISSUE TITLE
pre-push hooks with rspec

### ISSUE THREAD

**Issue by dminchev** [ForkIssues/Tracker#1707]
My repository is using pre-push hooking running RSpec tests.
```
#!/bin/sh

echo "Running RSpec"
bundle exec rspec spec
spec=$?

if [ "$spec" = 0 ]
then
  echo >&2 "Tests are green, pushing..."
  exit 0
else
  echo >&2 "Cannot push, tests are failing. Use --no-verify to force push."
  exit 1
fi
```

If I push from command line the tests are executed and push is completed. However if try to push using the app the following error is received:

```
Pushing to xxxx.com:xxx/xxx.git
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.3.22) required by your /Users/xxx/projects/app-name/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.3.22`
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	from /usr/bin/bundle:23:in `<main>'
Cannot push, tests are failing. Use --no-verify to force push.
error: failed to push some refs to 'xxxx.com:xxx/xxx.git'
```

I'm not sure how the Fork App is working and from where the push process (and pre-hook) is triggered. All my RSpec dependencies are installed in the project app dir and accessible from there, they are not system wide.

**Comment by DanPristupov** [comment]
Try to run fork from CLI using `open -a Fork` command.
You can find more info here https://github.com/ForkIssues/Tracker/issues/430#issuecomment-429013890

**Comment by dminchev** [comment]
@DanPristupov thank you for the fast feedback, this resolved my issue 🙌
