### ISSUE TITLE
Tabs no longer show repo name when opened from terminal

### ISSUE THREAD

**Issue by gimbo** [ForkIssues/Tracker#1708]
I frequently launch Fork in some repo from my terminal, by typing `fork .` in the repo directory. Previously this would create a tab in Fork with the repo name in it, but now they're being created with the name `.` which is less useful.

Screenshot showing old (happened to still be open) vs new:

![Screenshot 2022-09-22 at 13 02 36](https://user-images.githubusercontent.com/133770/191741548-8749bd2d-5b60-4769-9d3f-c76569e3f0ae.png)

Both of these tabs were opened via `fork .`, but the left hand one was opened on an earlier version of Fork (I assume!).

**Comment by kbakk** [comment]
Had the same issue with 2.22. Downloaded 2.21 (https://cdn.fork.dev/mac/Fork-2.21.dmg) and the names are back.

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/Tracker/issues/1703

**Comment by gimbo** [comment]
Thank you @DanPristupov - I looked for existing issues but searched vs "tab" I think so missed this.

👍🏻

**Comment by gimbo** [comment]
(Thought I closed this with that comment yesterday; let's try again...)
