### ISSUE TITLE
UI/UX: "Resolve using..." options are looking totally same, impossible to differentiate / choose right one.

### ISSUE THREAD

**Issue by burakkurkcu** [ForkIssues/Tracker#1709]
Hello there,

I don't know if there is a hint elsewhere to differentiate  that I am not aware of but, currently it is impossible to know these 2 options are referring to what actually. It can even be same, maybe 2 duplicate options, I don't know. Example below:

<img width="512" alt="Confusing-UI" src="https://user-images.githubusercontent.com/5931039/191940598-72150cc7-132b-4933-b535-00e3df981e18.png">

"Resolve using mine", "Resolve using theirs" was much clearer and better option imo, like in SourceTree.  

Attached below the repo folder at this state, I zipped whole folder as it is to maybe help to reproduce:
[ExampleRepo-Resolve using option problem-stable-diffusion-tensorflow.zip](https://github.com/fork-dev/Tracker/files/9632868/ExampleRepo-Resolve.using.option.problem-stable-diffusion-tensorflow.zip)

**Comment by DanPristupov** [comment]
At some point we fixed this, but I don't remember when.

<img width="531" alt="Screenshot 2023-06-08 at 14 09 37" src="https://github.com/fork-dev/Tracker/assets/618115/c24b5b36-446c-43f4-ae97-d88738d27706">
