### ISSUE TITLE
Starred&Filter only appear in the first opened tab

### ISSUE THREAD

**Issue by susan51531** [ForkIssues/Tracker#171]
Starred&Filter is only appear in the first opended after app is started. It's not visible in new tabs or the first tab reopend.
![image](https://user-images.githubusercontent.com/2595468/33466103-ce08f0a6-d686-11e7-8a82-b0c0c28630d1.png)

Version: v1.0.59.6
Steps:
1. restart fork
2. open a repository
3. If there are starred or filterred branch Starred&Filter is visible.
    Otherwise if you star a new branch Starred&Filter will appear.
4. open new tab or close the current tab, things in steps will not working

**Comment by DanPristupov** [comment]
Hey. Not sure I understand the problem.

Stars and filters are remembered for each repository separately. The starred section is visible only when a repository has starred branches or tags. I hide empty group intentionally to not disturb users who do not use stars.
So:
- If repository has at least one star, the section will be visible.
- On the first run or if/when you cancel all stars, the section will disappear.

Do I miss something?

**Comment by susan51531** [comment]
In the above case, i have a kibana repository with 4 star. As you see, the section is visible.
1: if i close it then reopen it, the section will disappear.
2: If i open the same repository in a new tab, the section is not visible in the seconed tab. But it is still visible in the first tab. And any new tab this section is invisible, and start icon not working.

On my computer, this section is only working in the tab opened with app. For any tab opened manually, the star icon not working, stared branches not visible.

**Comment by DanPristupov** [comment]
What you described is definitely a strange behaviour. I will investigate.

Thank you.

**Comment by susan51531** [comment]
fixed in version 1.0.67.2
