### ISSUE TITLE
Visual toolbar glitch on macOS 13.0b9 Ventura

### ISSUE THREAD

**Issue by finestructure** [ForkIssues/Tracker#1712]
Just a heads up incase you're not aware: the "Icon & Text" toolbar setting is slightly messed up on Ventura:

<img width="517" alt="CleanShot 2022-09-28 at 10 25 03@2x" src="https://user-images.githubusercontent.com/65520/192729061-280d4c98-669b-4040-a497-fbcc7f54ed34.png">

<img width="484" alt="CleanShot 2022-09-28 at 10 24 48@2x" src="https://user-images.githubusercontent.com/65520/192729085-e36a2659-0ae0-4575-9f97-6da922a73173.png">

Looks like there's a change in how title bar height is computed/reported or something.

I have no idea why I was using "Icon & Text" to begin with 😅

**Comment by DanPristupov** [comment]
Hi!
https://github.com/fork-dev/Tracker/issues/1624

**Comment by finestructure** [comment]
Oh sorry! I did a quick search for "toolbar" in the issues list and missed the dupe :)
