### ISSUE TITLE
Stashes not visible

### ISSUE THREAD

**Issue by LavTeamProject** [ForkIssues/Tracker#1713]
Version 2.22.1
macOS Monterey 12.6
Apple M1

How to fix?

<img width="553" alt="Screenshot_2022-09-28 в 12 54 48" src="https://user-images.githubusercontent.com/41138925/192750315-7f038390-cfb7-490f-9f37-55fac72ff204.png">

**Comment by DanPristupov** [comment]
> How to fix?

Click on the stashes icon.

<img width="210" alt="Screenshot 2022-09-28 at 13 30 50" src="https://user-images.githubusercontent.com/618115/192757007-c1253e47-aafa-4f33-bb08-425a384e5f89.png">

**Comment by LavTeamProject** [comment]
@DanPristupov 
magic)
Thank you!

**Comment by pyby** [comment]
Ho, 2.23.1 on Mac reverted this change.
Thanks for the release notes, I saw it.

After adopted this UX change, I liked it. I hope you'll have time to rethink about it.
A project with many branches, lot of tags, the stash list is accessible after lot of scroll, if tags and branches are expanded :)

Moving staches to the top sidebar sounds a good idea. 💙
