### ISSUE TITLE
Feature Request: Squash Selected Commits

### ISSUE THREAD

**Issue by Molin-L** [ForkIssues/Tracker#1714]
I really like a feature in Jetbrains IDEs. I can select multi-commits and squash them. It's really good feature and easy to implement.

**Comment by DanPristupov** [comment]
<img width="323" alt="Screenshot 2022-09-29 at 10 04 11" src="https://user-images.githubusercontent.com/618115/192962735-f95b0435-4134-4283-91c8-c47a3e200703.png">

**Comment by grigorye** [comment]
I feel like this is probably the same: https://github.com/fork-dev/Tracker/issues/1693
