### ISSUE TITLE
Reveal Line in Xcode

### ISSUE THREAD

**Issue by shinichy** [ForkIssues/Tracker#1719]
Hi, I'd like to use Xcode for "Reveal Line in ..." context menu below. But I see only "Visual Studio Code", not Xcode. How do I use "Reveal Line" action for Xcode?

<img width="530" alt="Screen Shot 2022-10-12 at 8 45 36 PM" src="https://user-images.githubusercontent.com/900172/195335095-e68b8618-2cd4-495d-a899-bf0ebb43a63b.png">

**Comment by DanPristupov** [comment]
I couldn't find a way to open a particular line in XCode.

**Comment by shinichy** [comment]
You're right. I though `xed` command does the job, but it doesn't work...

**Comment by 2Grey** [comment]
I checked `xed` with following syntax and it's work:

`xed -l 54 ./ProjectName/Classes/AppDelegate.swift`

Where is _54_ is a line number.

**Note:** But it stuck for a few seconds (and sometime just returns a error).

But it works well for opened project.

**Comment by 2Grey** [comment]
Release notes of Xcode 15 (Beta 15):

_The xed tool has been rewritten for performance and reliability. Invoke it from the command line to edit an existing or new file in Xcode, optionally opening to a given line number, and waiting for the file to close. (105476406)_

Now it works much faster.

```
$(which xed) -l 33 %path_to_file%
```

**Comment by DanPristupov** [comment]
We released Fork 2.44 with this feature.
