### ISSUE TITLE
When hitting enter in commit mode leave cursor where it was

### ISSUE THREAD

**Issue by mergesort** [ForkIssues/Tracker#172]
Let's say I have 3 files unstaged.

```
A.swift
B.c
C.cpp
D.js
E.ts
```

Before when I selected `D.js` and hit enter, the currently selected file cursor would move to `C.cpp` and I would be able to continue reading where I left off. This is really convenient when you are looking at dozens of files between commits.

The new behavior appears to be that it would move the currently selected file cursor to `A.swift`, meaning I have to scroll down and find where I left off last time.

This didn't change in the last version, but a while back and has made it more difficult to use Fork. I would like to see this behavior reverted back to the way it was for usability purposes. If you need any more information about the behavior I'm experiencing, I'm more than happy to provide more information.

Thank you very much!

**Comment by DanPristupov** [comment]
Is this still true? If so, what version do you use? 

Here's how it works in 1.0.60:
![2017-12-14 at 13 52](https://user-images.githubusercontent.com/618115/33993250-09b94e6c-e0d6-11e7-8f08-647dcb63b39e.gif)

I tested tree and list view modes, and both work properly.

**Comment by mergesort** [comment]
Hey @DanPristupov, thanks for following up! I noticed that it was fixed in 1.0.60, so I'll close this issue.
