### ISSUE TITLE
[Feature Request] - Support `--force` & `force-with-lease` in push dialog

### ISSUE THREAD

**Issue by spadger** [ForkIssues/Tracker#1724]
Hi

When pushing my code, sometimes I want to force-push, but only if it won't lose other peoples' commits

In the CLI, I can run `git push --force-with-lease`, but in the push dialog today, I only get a checkbox to force-commit.  A dropdown would be handy to select the aggressiveness of the push

**Comment by DanPristupov** [comment]
Hi. It's always `--force-with-lease`
<img width="500" alt="Screenshot 2022-10-17 at 13 26 30" src="https://user-images.githubusercontent.com/618115/196165509-a07f2f32-fa85-4c9f-8f2d-33c182f857d9.png">

**Comment by spadger** [comment]
Nice; thanks!

**Comment by rzwitserloot** [comment]
Was about to post this exact feature request, awesome that it is already there and has been there since forever / a long time already. Nice. Fork impresses as always :)
