### ISSUE TITLE
Blame and Timeline View crashes the app (MacOS Intel/M1)

### ISSUE THREAD

**Issue by dzianis-dashkevich-epam** [ForkIssues/Tracker#1727]
Hi!
Thank you for the great product!

I faced the following issue:

Steps to reproduce:
- Right-click on any file and choose Blame/Timeline...
- Fork App crashes

I tried it on:
- MacOS 12.6 (21G115) Intel Core i7
- MacOS 12.5 (21G72) M1

The reproducibility rate is 100%

Fork Version 2.23

**Comment by DanPristupov** [comment]
Thank you for reporting that.

1. ~~Can you send the log `~/Library/Logs/Fork.log` to support@fork.dev, please?~~ I've reproduced the problem 👍
2. ~~It's not clear from the bug report, Is that a new problem in 2.23?~~ It is.

**Comment by DanPristupov** [comment]
I'm sorry for the inconvenience.

I've already fixed the problem, but will release the hotfix update only Tomorrow.
If you really need blame, you can download the previous Fork version `2.22` here: https://cdn.fork.dev/mac/Fork-2.22.dmg

Thank you very much for the bug report ❤️

**Comment by DanPristupov** [comment]
I just released `2.23.1` hotfix

**Comment by dzianis-dashkevich-epam** [comment]
Hi @DanPristupov 
Amazing! Thank you for your rapid response!
It is working now, I really appreciate your hard work. And thank you again for such a great product!
