### ISSUE TITLE
Cannot set remote url type back from SSH to HTML

### ISSUE THREAD

**Issue by gerkov77** [ForkIssues/Tracker#1728]
Hi! I accidentally set my remote repo url to be SSH at "edit origin", and cannot set it back to HTML. Clicking on the down arrow is not doing anything. Thus I cannot fetch my repo anymore.
 
Otherwise thanks for the great app!

**Comment by gerkov77** [comment]
my mistake, SSH or HTML label depends on the url

**Comment by DanPristupov** [comment]
I guess you meant HTTPS :).
Anyway, I'm glad you figured it out.

**Comment by gerkov77** [comment]
Yes, sorry it was very late ;P. My problem connecting was actually that I am supposed use HTTP connection instead of HTTPS, and Fork does not support that. We should probably move our repo elsewhere with HTTPS domain.
