### ISSUE TITLE
"Fork 2.21 is currently the newest version available"

### ISSUE THREAD

**Issue by KnifeFed** [ForkIssues/Tracker#1729]
I can't get the app to update itself any longer as it thinks the latest version is 2.21, so I have to update manually.

<img width="260" alt="frontend-desktop-node18 (Fork) - 2022-10-23 at 19 58 04@2x" src="https://user-images.githubusercontent.com/85502276/197408007-3f0a2132-cd0f-40de-ba3a-65be4b402cf5.png">

Is this an issue with my installation or is it global? 
MacUpdater also thinks the latest version is 2.21 but [Latest](https://github.com/mangerlahn/Latest) has always found the correct version.

**Comment by DanPristupov** [comment]
You switched fork to the stable update channel.

**Comment by KnifeFed** [comment]
I'm not sure what you mean. I'm on stable, yes. Isn't that default? Isn't e.g. 2.22 stable?

**Comment by DanPristupov** [comment]
> Isn't that default?

No

> Isn't e.g. 2.22 stable?

No

**Comment by KnifeFed** [comment]
Oh, I checked https://git-fork.com/releasenotes and it doesn't mention anything about develop versions, nor does it denote 2.21 as being stable, so I assumed those were the release notes for the stable versions.

**Comment by KnifeFed** [comment]
And so the stable releases being "delayed 1 week" is outdated information, or?

<img width="443" src="https://user-images.githubusercontent.com/85502276/197414233-e521ad03-d74e-40a2-9902-2cfd0d5c35b5.png">

**Comment by DanPristupov** [comment]
> And so the stable releases being "delayed 1 week" is outdated information, or?

Sometimes it's longer
