### ISSUE TITLE
Commit graph broken with "Date Order"

### ISSUE THREAD

**Issue by Turbo87** [ForkIssues/Tracker#173]
This is similar to https://jira.atlassian.com/browse/SRCTREE-3041

Steps to reproduce:

- Clone https://github.com/Turbo87/sourcetree-bug-test
- Disable "Sort commits in topological order"
- View commit graph

Expected graph (from `gitk`):

![image](https://user-images.githubusercontent.com/141300/33765520-7785e3ae-dc19-11e7-94d0-04c4762bc7a7.png)

Actual graph:

<img width="1240" alt="bildschirmfoto 2017-12-08 um 13 12 49" src="https://user-images.githubusercontent.com/141300/33765531-8a3d4a32-dc19-11e7-9c0d-a08bdcb01416.png">

**Comment by DanPristupov** [comment]
@Turbo87 thank you for the good description. It seems that I fixed it. The fix will be available in Fork 1.0.61 update next week.
![2017-12-08 at 17 17](https://user-images.githubusercontent.com/618115/33774477-ac221ee4-dc3b-11e7-8682-afdb77a0f183.png)

**Comment by Turbo87** [comment]
AWESOME!! ❤️ 

I opened https://jira.atlassian.com/browse/SRCTREE-3041 with that reproduction 2.5 years ago and they still haven't fixed it 😭

**Comment by DanPristupov** [comment]
This should be fixed in 1.0.61.
