### ISSUE TITLE
MacOS Ventura navigation bar UI bug v2.22

### ISSUE THREAD

**Issue by bence-t0th** [ForkIssues/Tracker#1731]
<img width="484" alt="Screenshot 2022-10-25 at 15 13 30" src="https://user-images.githubusercontent.com/48957481/197782575-35f70325-47d4-4c8c-ae60-9b8ef9f745df.png">
macOS Ventura navigation bar UI bug

**Comment by DanPristupov** [comment]
Check for updates (Fork -> Check for updates).

**Comment by 2Grey** [comment]
Duplicate #1698

**Comment by geberl** [comment]
Had the same issue in 2.21, can confirm that updating to 2.23.1 fixes it
