### ISSUE TITLE
BUG: Collision of branch name and commit message

### ISSUE THREAD

**Issue by matkatmusic** [ForkIssues/Tracker#1733]
latest version of Fork, Mac OS

<img width="58" alt="Screen Shot 2022-10-25 at 2 06 47 PM" src="https://user-images.githubusercontent.com/2929847/197882179-92f8dc6e-0788-4bba-a4a1-ded8fbf31417.png">
<img width="63" alt="Screen Shot 2022-10-25 at 2 06 56 PM" src="https://user-images.githubusercontent.com/2929847/197882183-30a01a61-3398-4333-8e72-32e44a726f4d.png">
<img width="57" alt="Screen Shot 2022-10-25 at 2 06 59 PM" src="https://user-images.githubusercontent.com/2929847/197882184-2cdbc384-82d5-41ee-8705-2b8f30e29c75.png">

**Comment by Permusoft** [comment]
Mine too

<img width="314" alt="Screenshot 2022-10-26 at 7 47 08 PM" src="https://user-images.githubusercontent.com/1248287/198171903-76acf410-e008-490a-9ded-c3d72ecbb45b.png">

**Comment by 2Grey** [comment]
@Permusoft 
#1698
