### ISSUE TITLE
Label for toolbar items disappeared on macOS

### ISSUE THREAD

**Issue by acanda** [ForkIssues/Tracker#1735]
After updating to version 2.23.1 on macOs, the labels for the toolbar items (Fetch, Pull, Push, etc.) are not visible anymore and I can't find a way to enable them again. I think there used to be a context menu to enable icon and label, but right clicking on the toolbar does not bring it up (anymore).

**Comment by DanPristupov** [comment]
We had to disable that because the status control doesn't work on macOS Ventura in text & icons mode.

**Comment by acanda** [comment]
Bummer! I liked the labels. But if there is nothing you can do, then feel free to close this issue.

**Comment by ethanbeyer** [comment]
Do you believe this is something that will be possible in upcoming versions on MacOS?

**Comment by DanPristupov** [comment]
@ethanbeyer 
From what I see in the layout debugger, that won't be easy. AppKit in Ventura automatically applies height constraints to all toolbar items when in 'icons and text' mode.

**Comment by ethanbeyer** [comment]
Ah, so the old behavior of the Text being below the Icon _does_ get very difficult! Can Text go beside the Icons?

**Comment by ethanbeyer** [comment]
Here's how it looks in a Finder window when the toolbar is set to Icon & Text; not sure if this uses the same underlying libraries or not, though.

![Screenshot 2022-11-02 at 1 17 04 PM](https://user-images.githubusercontent.com/6864684/199557391-b20e1fa3-3d16-4ff8-b36d-c86f6e85447d.png)

**Comment by DanPristupov** [comment]
The toolbar text in AppKit is not controllable at all :(.

Here's a screenshot from the other topic:
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/1703659/190899661-31cde66d-da00-4c81-af5c-22b224308a14.png">

**Comment by DanPristupov** [comment]
@ethanbeyer Finder uses `isNavigational` toolbar item, which automatically makes the corresponding toolbar item left-aligned.

https://developer.apple.com/documentation/appkit/nstoolbaritem/3622481-isnavigational

> When you set this property to true, the system can position navigation items outside of the normal list of items in the toolbar. For example, the back and forward buttons in Finder windows are navigational, and the system positions them at the leading edge of the window’s title area.

**Comment by ethanbeyer** [comment]
Well that stinks. Thanks a lot, Apple!

I can't speak for other users but I would be OK losing the Repo name in the status box (since it's in the sidebar) in lieu of allowing text & icons again. I know that's probably not what you want to do, though.

**Comment by gabors** [comment]
Bummer indeed
This is the only thing I dislike about this awesome app.

**Comment by DanPristupov** [comment]
🎂

<img width="1295" alt="Screenshot 2023-04-07 at 11 31 40" src="https://user-images.githubusercontent.com/618115/230586196-3eebfeb0-0f56-422c-9387-1ec1269535d0.png">

**Comment by ethanbeyer** [comment]
siiiiick!

**Comment by DanPristupov** [comment]
We just released Fork 2.28, which has toolbar labels on macOS 13.

I couldn't get the original toolbar items work as we wish, so we implemented them manually and made them look exactly the same.

**Comment by gabors** [comment]
@DanPristupov Nice job!
Now brace for the requests to hide the toolbar button labels. :)

**Comment by username0x0a** [comment]
@gabors Well, count me in! 😄 I'd love to get `Icons Only` back. I know it's messy between pre-Big Sur up to Ventura when it comes to toolbar configuration, `AppKit` still carries around a lot of legacy relics & supporting everything is a PITA, yet still it's doable… 🤓

**Comment by gabors** [comment]
@DanPristupov I noticed one thing that can be also improved. You can only click the icon but not the label below, which is not how Mac apps behave.
Also the Fetch label is misaligned.

<img width="328" alt="image" src="https://user-images.githubusercontent.com/3587589/232872109-e331579e-8542-4515-9f25-af03ae30c3ff.png">

**Comment by DanPristupov** [comment]
I believe labels on macOS toolbars are not clickable. I just checked in Finder.

**Comment by gabors** [comment]
@DanPristupov you right about Finder. Yet in Mail they are clickable.
Would be nice to have a larger click area for clumsy developers :)
