### ISSUE TITLE
Can't select stage in full screen

### ISSUE THREAD

**Issue by hrvoje0099** [ForkIssues/Tracker#1736]
The best way to describe this to you is to watch video. When I open Fork in full screen (3440x1440) I can't select "stage", but in half screen can i.e. its okay.

https://user-images.githubusercontent.com/24483776/199028785-55954fa8-e573-4d69-832a-b7b7c3451e0d.mp4

**Comment by highflyingaction** [comment]
I have this issue as well.  What's weird is if the diffed lines are selected, the stage button is available no matter what width the window is.

**Comment by DanPristupov** [comment]
Fixed in 2.25.
