### ISSUE TITLE
After updating mac OS Ventura, SSH doesn't work anymore

### ISSUE THREAD

**Issue by steen4space** [ForkIssues/Tracker#1737]
![image](https://user-images.githubusercontent.com/20059342/199214184-4928c794-97a4-4691-9f18-37e7c93bb1b5.png)
After updating mac OS Ventura, Fork doesn't work anymore

**Comment by DanPristupov** [comment]
I may assume your server is very old and Ventura has a newer version of OpenSSH (> 8.2) which deprecated `RSA/SHA1` keys. A solution could be:

1. Update your server
2. Allow rsa-keys in the `~/.ssh/config`
```
Host ssh.dev.azure.com
    User git
    PubkeyAcceptedAlgorithms +ssh-rsa
    HostkeyAlgorithms +ssh-rsa
```
https://stackoverflow.com/a/70434510

3. Generate a new ED25519 key:
```
$ ssh-keygen -t rsa -b 4096
```

**Comment by lacastorine** [comment]
Same issue. Adding 
```
PubkeyAcceptedAlgorithms +ssh-rsa
HostkeyAlgorithms +ssh-rsa
```
helped to fix error while accessing directly from terminal, but fork still throws same error. 

---
Edit:

Deselecting all keys in the 'SSH Configuration' dialog helped - Fork is overriding the default system SSH settings... Is it possible to configure somehow?
