### ISSUE TITLE
Extraneous entry in 2.23 release notes

### ISSUE THREAD

**Issue by lobsterkatie** [ForkIssues/Tracker#1739]
Pretty sure the first entry is copy pasta, especially given the second entry:

![image](https://user-images.githubusercontent.com/14812505/199823897-4753547e-f50d-4cb3-a44b-e94775ca6d18.png)

**Comment by DanPristupov** [comment]
Yes, thank you. Not sure how that could happen :).

**Comment by lobsterkatie** [comment]
Copy, paste, forget to change? (Happens to the best of us. Just had someone catch me in the same thing in a PR an hour ago! 🙂 )
