### ISSUE TITLE
Interactive rebase: Add keyboard shortcuts

### ISSUE THREAD

**Issue by Turbo87** [ForkIssues/Tracker#174]
I've been using https://github.com/sjurba/rebase-editor for interactive rebases so far and it works quite well. What I'm missing when doing it via Fork is keyboard shortcuts.

for example when a row is selected:

- <kbd>d</kbd> would set the action to "drop", <kbd>f</kbd> to "fixup", etc.
- <kbd>Ctrl</kbd> + <kbd>↓</kbd> would move the row downwards

**Comment by DanPristupov** [comment]
@Turbo87 I'm really not sure about adding **one-key** shortcuts. They are nice in vim, but having them in macOS app seems to be confusing. Is there any other OS X application which uses a similar approach?

**Comment by Turbo87** [comment]
> Is there any other OS X application which uses a similar approach?

good question, I can't think of one right now, but I'm not proposing to do this for the whole app, just when a row of that model is focused

but I'd also be okay with making it e.g. <kbd>Ctrl</kbd> + <kbd>d</kbd> for "drop"

I guess it all depends on what the users intuition is when hitting any keys within that dialog. The two intuitive things that I could image would be:

- searching for a commit message starting with the character that were typed
- modifying the current row in any way (which is what I'm proposing here)

**Comment by tflo** [comment]
> They are nice in vim, but having them in macOS app seems to be confusing. Is there any other OS X application which uses a similar approach?

[GitUp](https://github.com/git-up/GitUp) is making good use of single-key shortcuts:

![screen shot 2017-12-10 at 02 00 32-pty-fs8](https://user-images.githubusercontent.com/1410282/33801025-f4efa7f0-dd4d-11e7-84b4-2b188004d40d.png)


[Reeder](http://reederapp.com/mac/) is also using single-key shortcuts for many things:

![screen shot 2017-12-10 at 01 46 35-pty-fs8](https://user-images.githubusercontent.com/1410282/33800966-c8df8ce4-dd4c-11e7-89d2-fc4aa423394c.png)

Besides that, video and audio editing software often uses single-key shortcuts, for example [Audacity](http://www.audacityteam.org), [MPEG Streamclip](http://www.squared5.com/svideo/mpeg-streamclip-mac.html) and similar programs:

![screen shot 2017-12-10 at 02 09 37-pty-fs8](https://user-images.githubusercontent.com/1410282/33801069-54353490-dd4f-11e7-891c-deeb53e9052e.png)
![screen shot 2017-12-10 at 02 09 59-pty-fs8](https://user-images.githubusercontent.com/1410282/33801070-5453ec78-dd4f-11e7-95f5-c1c4ea2beee0.png)


So, it is not so uncommon.

– Tom

**Comment by DanPristupov** [comment]
I added such shortcuts in 1.0.64.
![2018-02-22 at 09 49](https://user-images.githubusercontent.com/618115/36528524-b5311408-17b5-11e8-8a22-2975bc446889.png)

Thank you

**Comment by Turbo87** [comment]
awesome, thanks :)

**Comment by Turbo87** [comment]
unrelated question: why do you use the "done" label instead of closing the issues?

**Comment by DanPristupov** [comment]
I close issues when they are finished and feedback is good (i.e. when they don't need my attention anymore).

The "Done" label exists mostly for myself. It's like 'Release Candidate' mark for issues. It means that the issue has been resolved recently and I need to review it a bit later again. Usually, after a new release I go through old items and close them, and then mark new ones as 'done'.

**Comment by Turbo87** [comment]
One thing I noticed when using it was that <kbd>Enter</kbd> did not trigger the "Rebase" button, so you still need to switch over to the mouse/touchpad to start the rebase.

**Comment by DanPristupov** [comment]
@Turbo87 also noticed that issue.
Just to remind myself: the`reword` dialog should also handle <kbd>⌘</kbd> + <kbd>Enter</kbd>.

**Comment by DanPristupov** [comment]
I got reported that *sometimes* shortcut handling is too aggressive and does not allow to type `p/r/s/f/d` letters in the reword popup. But I could reproduce that problem only once (I tried about 10 times).

**Comment by gaggle** [comment]
I've had the issue of not being able to use keys used by shortcuts anywhere in the app after using interactive rebase, but I've not been able to reproduce it now for some time. The problem manifested itself globally, e.g. I couldn't type letter "P" into the commit or Create Branch dialog boxes.

Restarting the app would solve the issue.

I still check after each rebase but haven't had a repro so... *\*shrug*\*

**Comment by petterikamppuririchie** [comment]
Hi!

I just today started to see keyboard entry problems. Happened in reword popup, but also happened in commit text field.

No problems until today, don't know why they started today.

**Comment by DanPristupov** [comment]
I just released Fork 1.0.65.

@Turbo87 <kbd>Enter</kbd> now submits rebase.
@petterikamppuririchie I think I fixed the keyboard problem. Please let me know if it appears again.

**Comment by petterikamppuririchie** [comment]
Thanks! Will report if I run into it again.
