### ISSUE TITLE
Stuck loading on Mac after fresh install

### ISSUE THREAD

**Issue by obasille** [ForkIssues/Tracker#1741]
Hi there,
I'm usually using Fork on Windows and it's great!
Today I installed it on a Mac. I've downloaded the latest from the web.
Upon starting it asked me to download an update and I accepted.
It also asked me for my name and email, which I gave.
Then the GUI showed up but the cursor stayed with the loading/waiting animation (the rotating rainbow disc). There was also a window saying something like "Ready to update, yes, no". But the GUI wasn't responding, I couldn't click on anything, even the menus.
I waited for a while with no change so I killed the app and restarted it. Got stuck with the loading cursor again. So I've deleted the app and re "installed" it (copied the files in "Applications"). Same. It seems to be keeping my setting somewhere though because it didn't asked for my name after re-installing (but I didn't find what file to delete to remove the settings).
Please help :)

**Comment by DanPristupov** [comment]
You can reset settings by running `defaults delete com.DanPristupov.Fork` in command line.

**Comment by obasille** [comment]
Thanks @DanPristupov !
Just did that. This time I skipped downloading the update. Still stuck.
So tried again, and accepted the download without clicking on "Finish" for the User information window. Then accepted to update. It restarted. Still stuck but at least I'm running the latest version now.
Going to restart my machine.

**Comment by obasille** [comment]
Well, restarting the machine solved my issue... sorry for the trouble!
