### ISSUE TITLE
Git error when deleting/applying stash

### ISSUE THREAD

**Issue by Stannieman** [ForkIssues/Tracker#1743]
When I try to delete or apply a stash I git a Git error.
Managing the same stashes via terminal works fine.
<img width="833" alt="image" src="https://user-images.githubusercontent.com/1538156/200601850-0407cf5e-5a50-4516-99c8-d60574903384.png">

This may not be very helpful on its own, so is there a log I can attach somewhere?

Update: It seems Fork tries to run `git stash drop stash@{0}` but it should be `git stash drop 0`

**Comment by DanPristupov** [comment]
> It seems Fork tries to run `git stash drop stash@{0}` but it should be `git stash drop 0`

Since when?

Stash docs says: 
>  A reference of the form `stash@{<revision>}`. When no <stash> is given, the latest stash is assumed (that is, `stash@{0}`).
> ...
> This option is only valid for apply, branch, `drop`, pop, show commands.

https://www.git-scm.com/docs/git-stash#Documentation/git-stash.txt-ltstashgt

> This may not be very helpful on its own, so is there a log I can attach somewhere?

The log is located at `~/Library/Logs/Fork.log`, however It's very possible that the stash command returns an empty output in your case.

What git instance do you use?

**Comment by DanPristupov** [comment]
Do other git operations (like commit or checkout) work properly? I assume, stash drop/apply are not the only one which fail.

**Comment by Stannieman** [comment]
Since when?
Don't know, at least a few weeks. I daily drove Windows until a few weeks ago so no idea before that. Windows version has no problem btw.

Instance: both built in (2.36.1) and system installed Apple git (2.37.1), but system one does does print `error: 'stash@{0}' is not a stash reference`.

Other operations work fine.

I wonder if it's something on my machine because I see nobody else complaining about this.

**Comment by Stannieman** [comment]
Also no luck with git from homebrew.
It is an M1 machine but that should not affect CLI interface IMO.

**Comment by DanPristupov** [comment]
> I wonder if it's something on my machine because I see nobody else complaining about this.

Yes, that code in Fork has been unmodified since 2016.

> `error: 'stash@{0}' is not a stash reference`

It might be possible that the repo is corrupted.

1. Can you reproduce the problem in some other repo?
2. Try to run `git fsck --full` in the command line (https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery). Do you see any errors?

P.S. M1 machines should work fine too.

**Comment by Stannieman** [comment]
1. Other repos work fine 😅 sorry to bother you...
2. No errors, only a bunch of dangling stuff

I will re-clone the problematic repo and if that doen't work check if some script is messing with it or if it is even corrupt on origin (I am new to this project and they have some scripts to set up the project for you environment, maybe it is doing something nasty).

Thanks for the quick response and again sorry to take your time!

**Comment by Stannieman** [comment]
FYI clean clone without running scripts is broken too so I think it is bad on the server.

**Comment by DanPristupov** [comment]
> FYI clean clone without running scripts is broken too so I think it is bad on the server.

So, you are saying there is a repository which doesn't work with stashes, even if you clone a new repo? There must be some mistake. Stashes are purely local, so server/origin should not affect them.

**Comment by DanPristupov** [comment]
Here's what I've found: https://stackoverflow.com/questions/22076944/git-stash-reporting-is-not-a-stash-reference

**Comment by DanPristupov** [comment]
Do you see all your stashes if you run `git stash list` in the command line?

**Comment by Stannieman** [comment]
Yes I see all stashes. I also found that my colleagues have the same issue with this specific repo. Everybody just thought it was their machine and nobody ever asked anyone else about it 😅

I know stashes are local, but maybe something is broken on remote and this corruption gets cloned as well.

**Comment by DanPristupov** [comment]
Check, if your repo has a 'stash' file (or folder) in the root?

**Comment by Stannieman** [comment]
No such file. Only in .git/refs but I think that is normal if you have at least 1 stash

**Comment by DanPristupov** [comment]
> Only in .git/refs but I think that is normal if you have at least 1 stash

Yes, that's normal. That's the files which contains stashes. It's a text file, you can open it if you are curious :)

OK, is there a remote branch `stash` may be? There must be some object which conflicts with the 'stash' name. It could be a file, a branch or a tag.

**Comment by Stannieman** [comment]
![image](https://user-images.githubusercontent.com/1538156/200804994-02fb45c6-047f-4d58-8c9a-59a593773b5d.png)

FFS 🙄

**Comment by DanPristupov** [comment]
Bingo! :)

Now there is another tricky moment to get rid of that tag. Deleting a tag in git is difficult.

1. Delete the tag on the server or in Fork with enabled `Delete tag from remote repositories` option.
<img width="350" alt="Screenshot 2022-11-09 at 11 59 32" src="https://user-images.githubusercontent.com/618115/200812874-14bfd015-7004-4d38-8502-ae932d540944.png">

2. Ensure **none** of the team members have `Push all tags` enabled in the push dialog, otherwise that tag will be pushed back.
<img width="350" alt="Screenshot 2022-11-09 at 12 00 14" src="https://user-images.githubusercontent.com/618115/200812993-082d2764-86fc-4249-8869-debdb74cd4b8.png">

**Comment by Stannieman** [comment]
Yep I will discuss with the rest of the team! Thanks a lot for looking into it even though it is no Fork bug! ❤️

**Comment by DanPristupov** [comment]
Well, I think Fork should use full reference path (like `git stash drop refs/stash@{0}`) to avoid the ambiguity. We'll improve that in the next update.
