### ISSUE TITLE
Can't create Merge Request to self-hosted gitlab. Does the feature exist?

### ISSUE THREAD

**Issue by jacattrongnlh** [ForkIssues/Tracker#1746]
This issue says they can create Pull request to Gitlab https://github.com/fork-dev/Tracker/issues/914 but I do not see it in the app. I can only create Pull Request to Github, I can't create Merge request to Gitlab.

I'm using self-hosted Gitlab.

**Comment by DanPristupov** [comment]
Did you log in to your GitLab account in Fork (Fork -> Accounts -> + -> GitLab EE)?

**Comment by jacattrongnlh** [comment]
I've logged in the account using Personal Access Token (with sufficient scopes), I find Gitlab Server, not Gitlab EE. I still don't find the option to create Merge request to Gitlab.

**Comment by jacattrongnlh** [comment]
I got it. I have to delete github from the list of remotes to see that option in Right click on branch > Create Pull request on 'origin'.
