### ISSUE TITLE
Quick Launch: Open recent repo in new tab by default

### ISSUE THREAD

**Issue by svoop** [ForkIssues/Tracker#1750]
I'm falling into this trap half a dozen times a day, maybe happens to others as well. 😄 

The quick launcher on `⌘P` is great for quickly opening repos. However, it opens the repo replacing the current tab. This might be the desired behavior every once in a while, but usually, it's not... at least not for me.

Would it be possible to open in a new tab instead by default?

In case you did want to replace the current tab, it's easy enough to close the old tab *after* the new one is opened. The other way round is more cumbersome, because you have to hit `⌘T` *before* `⌘P` to create a new tab first... and in real life, at least I forget to do so all the time.

Thanks for considering this simple "fix"!

**Comment by DanPristupov** [comment]
> Would it be possible to open in a new tab instead by default?

Starting Fork 2.25, the Quick Launch opens repos in new tabs by default 👍

**Comment by svoop** [comment]
@DanPristupov Awesome, thanks so much!
