### ISSUE TITLE
[Feature Request] list commits in submodule changes "diff" view

### ISSUE THREAD

**Issue by brechtm** [ForkIssues/Tracker#1751]
The "diff" view for a submodule currently shows only the descriptions for the old and new commits. It would be very convenient if all commits in-between could also be shown. Alternatively (or additionally), a _View Changes_ button could be added (next to the _Open Submodule_ button) that would open the submodule and select the old and new commits so that the net diff is displayed.

**Comment by brechtm** [comment]
Oops. This kind of duplicates #980

**Comment by DanPristupov** [comment]
> The "diff" view for a submodule currently shows only the descriptions for the old and new commits. It would be very convenient if all commits in-between could also be shown.

This is a good idea.

Technically, showing the commit list should not be difficult. Though finding the right design will need a time.

- We should keep the old/new commit badges, but make them smaller so there is a room for the scrollable commit list area.
- 'Open submodule' and 'Update submodule' buttons must be moved somewhere, but I don't know where.
- Probably the commits in the list shouldn't be selectable, but double click must open commit details in a separate window.
- If submodule has a dirty working directory, a virtual 'Local Changes' item must appear in the commit list.

**Comment by DanPristupov** [comment]
Here is an early version:

<img width="962" alt="Screenshot 2024-01-09 at 18 28 36" src="https://github.com/fork-dev/Tracker/assets/618115/2b3c65b2-3152-4738-9ae5-ff9f255168e6">
