### ISSUE TITLE
message of displayed "stash save" command must be enclosed in quotes

### ISSUE THREAD

**Issue by kambala-decapitator** [ForkIssues/Tracker#1752]
Here `crash SDK-885` is stash name (`--message` param in CLI), but git command in the log doesn't enclose the name in quotes leading to incorrect command. Correct is: `git stash save -m 'crash SDK-885'` (or double quotes).

![Screenshot 2022-11-28 at 18 43 49](https://user-images.githubusercontent.com/1557784/204321648-1e676b04-4f2f-4161-991e-472af35da533.png)

Tested in 2.23.1 and 2.24.

**Comment by DanPristupov** [comment]
Quotes is a problem of a command line which must parse the user input. It not really related to the actual process interaction.

Internally (In unix) `args` is not a string, but an array of strings (https://linux.die.net/man/3/execvpe).

**Comment by kambala-decapitator** [comment]
but I thought the point of the displayed string that starts with `$ ` is to show to a user the CLI equivalent of an action? If not, which purpose does it serve?

**Comment by DanPristupov** [comment]
The purpose it to show what commands have been run internally. More like a log.

Most likely no one copies requests and runs them in a terminal :)

**Comment by kambala-decapitator** [comment]
all clear now, thank you for the clarification!

**Comment by DanPristupov** [comment]
Of course, we can check each argument and wrap with quotes the ones with whitespace, but then we need to start thinking about escaping other characters too. Like quotes `'"` -> `\'\"` and unicode emojis `🦔` -> `<0001f994>`.

`git stash -m '🦔test'''test"""'` is still an invalid command :).

We might also take into account that the default MacOS terminal, iTerm2 and say kitty, have different syntaxes.

It's not worth the time, I think.
