### ISSUE TITLE
It is possible to hide the notifications icon from the menu bar (MacOS)

### ISSUE THREAD

**Issue by ShlomoCode** [ForkIssues/Tracker#1756]
In MacOS, FORK adds an icon to the menu bar, which opens a menu like this:
![CleanShot 2022-12-06 at 01 19 36](https://user-images.githubusercontent.com/78599753/205764498-deecfad7-ec6f-4645-841b-211b25cc8c88.png)
I use many programs through the menu bar, and on the other hand, I don't use this notification feature of fork at all. Therefore, please make it possible to cancel this icon, so that I can gain more space in the menu bar without using expensive external software such as Bartender.
Thanks!

**Comment by DanPristupov** [comment]
Fork -> Accounts -> GitHub

**Comment by designorant** [comment]
Quite a challenge to find this option fyi!

**Comment by juliand665** [comment]
I also just spent a while looking for this! I feel like the accounts should at least be linked to from the settings, if not part of them itself.

**Comment by shashank-shekhar** [comment]
This should be an opt-int feature.
