### ISSUE TITLE
gitUnknownError in commit detail

### ISSUE THREAD

**Issue by radek-altof** [ForkIssues/Tracker#1757]
When viewing any commit, I get the following **gitUnknownError** message in the commit detail pane:
`gitUnknownError(output: "", error: "fatal: unrecognized argument: --diff-merges=1\n")`

I first noticed this happening yesterday when I opened Fork.
Otherwise, all git operations (fetch, push, pull, merge, rebase, stash ...) are working fine for me.

Running on macOS Monterey 12.5.1, git version 2.27.0.

<img width="581" alt="Screenshot 2022-12-06 at 13 57 12" src="https://user-images.githubusercontent.com/34248370/205918856-9b9261e5-18a2-48a3-b325-14140e7fe48b.png">

**Comment by DanPristupov** [comment]
> git version 2.27.0.

Upgrade git or switch Fork to the internal git.

**Comment by radek-altof** [comment]
Switched to internal git and it works, thank you 🙂
