### ISSUE TITLE
Add an option to remove all branches where the tracked branch is removed

### ISSUE THREAD

**Issue by janpieterz** [ForkIssues/Tracker#1759]
It would be nice to have some easy option to remove all branches where the tracked branch is removed. 
This often happens when a pull request is merged on GitHub, GitLab etc, and means I'm often doing some manual cleanup task.

<img width="247" alt="image" src="https://user-images.githubusercontent.com/383634/206398524-f09dce4b-5659-42c1-8b7f-d3e1af7e5190.png">

**Comment by DanPristupov** [comment]
You select them all holding Cmd and delete at once.

P.S. A related issue: https://github.com/fork-dev/Tracker/issues/1141

**Comment by janpieterz** [comment]
Yea, that works of course, but with a ton of branches it's one of those maintenance tasks. Will close in favor of #1141, I had checked but somehow didn't find that.
