### ISSUE TITLE
Can't install Command Line Tools

### ISSUE THREAD

**Issue by jv-k** [ForkIssues/Tracker#1761]
Version: `2.24`
MacOS: `12.6.0`

```
🔷> Installing cli tool...
❌> Can't install cli tool. Error Dictionary: '["NSAppleScriptErrorNumber": -2147450879]'
```

`brew` is installed, and `/usr/local/bin` already exists

**Comment by DanPristupov** [comment]
I found this: https://developer.apple.com/forums/thread/675364

>  The error code you’ve got, -2147450879, translates to 0x80008001, or badComponentInstance. AppleScript is tied to the Open Script Architecture (OSA) which uses Component Manager to find the script engine to run your script. For some reason it’s not able to do that.
> 
> Here’s a quick test: Use System Preferences > Users & Groups to create a new admin user and see if your script works there.

**Comment by jv-k** [comment]
Fantastic, that worked for me! I created the account, and installed the CLI in there, and switched back to my main account, and the CLI was already installed. Thanks for this 👍🏻
