### ISSUE TITLE
"fatal: unknown value for --diff-merges:1 \n" on file changed

### ISSUE THREAD

**Issue by TK-Nathaphop** [ForkIssues/Tracker#1762]
I'm not sure that why I got this error message on Fork and it occurs on every repositories.
I've tried to search in Google and Github issues already but still not found anything.
And I tried many ways to solve this problem e.g. restart, update Git and Fork, reinstall Git and Fork already. But it still occurred.

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/1493167/206873296-17174a36-60c2-4b6a-8e90-d706ed4dbc49.png">

Also I've checked with another Git GUI (SourceTree) and found that it can displayed normally without any error.
If there is created issues or closed issues already, apologize for duplicated this issue.

**Another information**
OS: macOS Big Sur 11.6
Fork version: 2.24
Git version: git version 2.30.1

P.S. This is my first issue. So, if there are any mistake, please feel free to give a suggestion or advice.

**Comment by DanPristupov** [comment]
> git version 2.30.1

Please update git or switch Fork to the internal git instance

>  This is my first issue. So, if there are any mistake, please feel free to give a suggestion or advice.

Everything is fine 👍

**Comment by TK-Nathaphop** [comment]
Thx! I just found that I've another git instances on setting.

<img width="547" alt="image" src="https://user-images.githubusercontent.com/1493167/206873755-1f3914a2-2377-49fb-888e-2021a0f0b654.png">

After changing to another instance (either fork instance or local git), it can work properly!
But I've never changed this setting by myself before and not sure why my Mac changed it.

Anyway, thanks! 👍🏻
