### ISSUE TITLE
[Feature request] Keyboard shortcut for "Also delete remote branch"

### ISSUE THREAD

**Issue by skanaar** [ForkIssues/Tracker#1764]
When I choose **Delete branch** a confirmation dialog opens with a checkbox for **Also delete remote branch origin/BRANCH_NAME**.

I would like a keyboard shortcut for checking that checkbox.

The keyboard shortcuts for _soft / mixed / hard_ in the **Reset BRANCH_NAME to here** dialog is a good example of what I am looking for.

🍰 Thank you for a great piece of software!

**Comment by DanPristupov** [comment]
It's difficult to make such a shortcut discoverable. I think it's better to leave that option without shortcut to make the user think before enabling it. It's still an error-prone option, after all.
