### ISSUE TITLE
Commit short hash (SHA-1) is 7 character problem

### ISSUE THREAD

**Issue by ramazanogunc** [ForkIssues/Tracker#1765]
Hello
When we run the git command below, where we can see the short commit hash, the value is 8 characters. 
`git rev-parse --short HEAD`
The commit hashes displayed in the fork application are 7 characters. I looked but I couldn't see a setting to make it 8 characters
Screenshoot:
<img width="224" alt="Screenshot 2022-12-13 at 16 09 40" src="https://user-images.githubusercontent.com/46759371/207326633-256765a5-a43b-454a-9f5e-128ba1de1b8f.png">

**Comment by DanPristupov** [comment]
> When we run the git command below, where we can see the short commit hash, the value is 8 characters. 
`git rev-parse --short HEAD`

It can be longer. For example for my repo it returns 9 characters, even though `core.abbrev` (https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreabbrev) is not modified.

> The commit hashes displayed in the fork application are 7 characters. I looked but I couldn't see a setting to make it 8 characters

The abbreviation length in Fork is hard-coded and can't be changed.

**Comment by ramazanogunc** [comment]
Thanks for reply
I understand. If you see fit, may you update the length to 8 characters? 🙂

İf not possible we can close the issue. 

Thanks
