### ISSUE TITLE
some tag missing

### ISSUE THREAD

**Issue by rickytan** [ForkIssues/Tracker#1766]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/1250207/207527536-cad37afa-2eec-4c0a-ab70-ba743fe2172e.png">
but acutely it has another tag `0.1.24`

```shell
❯ git tag --contains=02840cb869eb1f0b346930f4ff31cb8ea6bcea7c | cat
0.1.24
0.1.24.20221214.rc.1
```

**Comment by DanPristupov** [comment]
Can you show output of the following git command, please?

```
git for-each-ref refs/tags/0.1.24 --format="%(refname):%(objecttype):%(*objecttype):%(objectname):%(*objectname)"
```

**Comment by rickytan** [comment]
Sure
```bash
❯ git for-each-ref refs/tags/0.1.24 --format="%(refname):%(objecttype):%(*objecttype):%(objectname):%(*objectname)"
refs/tags/0.1.24:tag:tag:b41110add66387e6a2ccbce27bb860278af2fba9:a47ce1d0104d640874d495a0269eecc89e7e0074
```

**Comment by rickytan** [comment]
Specailly, SourceTree gives the right result:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/1250207/226914430-6067bf80-7cad-45de-959c-810a5379fb1d.png">

**Comment by DanPristupov** [comment]
Well, `git for-each-ref` returns only one tag which starts with `0.1.24`.

I can investigate the problem if you can find steps to reproduce it.

**Comment by rickytan** [comment]
You may try make a tag named `0.1.24.xxx` , then make a tag named `0.1.24`

**Comment by DanPristupov** [comment]
Ouch, I'm sorry.  I made a mistake in the request. It must have been `git for-each-ref 'refs/tags/0.1.24*' --format="%(refname):%(objecttype):%(*objecttype):%(objectname):%(*objectname)"`


> You may try make a tag named `0.1.24.xxx` , then make a tag named `0.1.24`

```
$ git tag 0.1.24.xxx

$ git tag 0.1.24

$ git for-each-ref refs/tags/0.1.24 # <-- wrong
8ea17c95e8759b34931f9609f34c114143f16ea5 commit	refs/tags/0.1.24

$ git for-each-ref refs/tags/0.1.24* # <-- looks like `*` must be quoted
zsh: no matches found: refs/tags/0.1.24*

$ git for-each-ref 'refs/tags/0.1.24*' <-- that's the right one
8ea17c95e8759b34931f9609f34c114143f16ea5 commit	refs/tags/0.1.24
8ea17c95e8759b34931f9609f34c114143f16ea5 commit	refs/tags/0.1.24.xxx
```

**Comment by n8gray** [comment]
I have a similar problem, but much more severe. In one of my repos at work *none* of the tags appear in Fork. 

```shell
[n8gray]% git tag -l | wc -l                        
     478
```

<img width="354" alt="Screenshot 2023-04-30 at 1 57 29 PM" src="https://user-images.githubusercontent.com/82794/235375872-e175a2ba-dfc8-48d1-9ac9-388237a7d225.png">

This is a huge problem for me, since one of our very common workflows involves checking out the code corresponding to a specific release tag. Any idea what could be going wrong?

I've looked at the tag names and they seem totally reasonable, tried piping them through `cat -v` to see if there were any strange unprintable characters, but didn't find anything.

**Comment by DanPristupov** [comment]
@n8gray 

1. Check `View -> Hide Tags`
2. Check if the log file has any errors. The log is located at `~/Library/Logs/Fork.log`

**Comment by n8gray** [comment]
Thanks @DanPristupov, it was the `View > Hide Tags` switch. I guess I turned it on a long time back to stop the tags from cluttering the timeline, but I didn't expect that would also hide them in the dedicated Tags area of the sidebar. I guess I'd consider it an improvement if they still displayed there, or at least there was a label saying `[hidden]` or something to nudge people like me in the right direction.
