### ISSUE TITLE
Horizontal black line artefact on macOS fullscreen mode

### ISSUE THREAD

**Issue by frameworker2019** [ForkIssues/Tracker#1769]
Hello,

minor visual issue when operating Fork in fullscreen mode on my Mac, Monterey 12.6.2

![image](https://user-images.githubusercontent.com/55428040/208713729-06f35473-2cf8-40bf-83c7-1b15dd73425d.png)

This happens when the mouse  hovers the local change line.

Fork version: 2.21

**Comment by DanPristupov** [comment]
Looks like a macOS glitch. Try to reboot the computer.

**Comment by frameworker2019** [comment]
No, it's permanent, that's why update the mac to the latest version fix today. It's not critical for me, so it's documented now for the ones who have the same issue.
I thought it's regarding a drawing issue of the bar line.
