### ISSUE TITLE
Hide HEAD branches by default

### ISSUE THREAD

**Issue by Turbo87** [ForkIssues/Tracker#177]
The HEAD "branches" (`HEAD`, `origin/HEAD`, ...) are usually just adding noise to the history graph unless they are in detached HEAD mode. I would like to propose to hide the HEAD branches if there is at least one other branch pointing at the same commit.

**Comment by DanPristupov** [comment]
@Turbo87 thank you for reminding me. I used to hide `origin/HEAD`, but if it's visible again it's probably a bug. Will have a look.

Actually `[remote]/head` is the only `HEAD` branch which can appear, right?

Please note that there is an exception when repo is in detached head state, which is a feature (more info here https://github.com/ForkIssues/Tracker/issues/107).

**Comment by Turbo87** [comment]
yeah, I saw #107 and that absolutely makes sense to me. I'm actually seeing `upstream/HEAD` right now, not sure about `origin/HEAD`, but IMHO the name of the remote shouldn't make a difference.

**Comment by Turbo87** [comment]
note that I'm using `git clone --origin=upstream` by default which is probably be the reason I'm seeing `upstream/HEAD`

**Comment by DanPristupov** [comment]
This should be done in 1.0.61
