### ISSUE TITLE
Button text improvement request (this will literally take seconds to implement!)

### ISSUE THREAD

**Issue by brandonzylstra** [ForkIssues/Tracker#1770]
It is conventional (at least on macOS) to use an ellipsis (`...`) when a button or menu item takes you to a new dialog rather than having an immediate effect.   This is an important indication to the user of whether to expect

- their code (or document, in many other apps) to be immediately changed, OR
- to be given an opportunity to make changes in a new dialog.

Whenever a button (or menu item) is a verb, it is otherwise unclear whether clicking the button will _**begin**_ the action or whether it will _**complete**_ the action of the verb. 

In the context of Fork, the button which says "Resolve" is ambiguous (at least to anyone who has not already used it).
<img width="154" alt="image" src="https://user-images.githubusercontent.com/9854/208778497-c99138d0-2548-423e-8cf3-317dcbd46779.png">

I looked at it and thought that _it would most logically open a dialog box_ (rather than immediately mark the conflict resolved), and yet the text on the button _implicitly claimed to take an immediate action_, by virtue of its lack of an ellipsis.  I didn't know whether to trust the text actually written on the button, or to trust my intuition of what would make the most sense, so I had to spend time hunting for information online (which was less available than expected), eventually finding a video which showed someone using the feature.

It would be very helpful if you could follow this standard macOS convention, adding `...` to this button and any other button or menu item which begins an action but gives the user an opportunity to avoid completing it.

Thanks for the awesome app!

**Comment by DanPristupov** [comment]
> It is conventional (at least on macOS) to use an ellipsis (`...`) when a button or menu item takes you to a new dialog rather than having an immediate effect. This is an important indication to the user of whether to expect

Yes, I agree.

> In the context of Fork, the button which says "Resolve" ... would most logically open a dialog box

Why should it 'logically' open a dialog box? If it would, there would be ellipsis, as you said.

> It would be very helpful if you could follow this standard macOS convention, adding ... to this button

It looks like you assumed what this button does and based on this assumption, propose changes.
But it does not open a dialog! it just switches layout to the 'Local Changes' view where you can resolve the conflict.
