### ISSUE TITLE
[BUG] Search overlay persists from All commits to Local Changes

### ISSUE THREAD

**Issue by gentique** [ForkIssues/Tracker#1772]
Step 1:
Search for something in the Changes window on All Commits
<img width="2416" alt="Screen Shot 2022-12-22 at 3 13 27 PM" src="https://user-images.githubusercontent.com/15278390/209153068-49be63cd-158f-44ca-9706-a1c864754d19.png">
Step 2:
After search has highlighted a result, go to Local Changes
<img width="2416" alt="Screen Shot 2022-12-22 at 3 13 32 PM" src="https://user-images.githubusercontent.com/15278390/209153072-6401252f-7d1d-4bbd-a9e5-6522306cbf55.png">

**Comment by DanPristupov** [comment]
I couldn't find a solution for that. The inline search in the NSTextView control seems to be non-customizable.

https://github.com/fork-dev/Tracker/issues/821
https://github.com/fork-dev/Tracker/issues/1524

**Comment by brechtm** [comment]
It's pretty annoying to have to go back to the previous view to clear the search and then, again, go to the other view. Perhaps the search could simply be cleared when switching from _Local Changes_ to _All Commits_ and vice versa?

Though it may be useful to keep the search state for when you get back to the view where you were performing a search, so perhaps store the state on leaving the view and restore it when returning. That will require much more work than just clearing the search, so I would propose to just clear the view for now.
