### ISSUE TITLE
[feature request] Add ability to collapse/expand file folders

### ISSUE THREAD

**Issue by jv-k** [ForkIssues/Tracker#1776]
Add the feature to collapse/expand staged or unstaged folders, as you can do with SourceTree, for example.

![Screenshot 2022-12-29 at 18 27 37](https://user-images.githubusercontent.com/5808914/209994283-cec68c0d-561c-4916-9885-3a7a5b558320.png)

Thank you for a great app!

**Comment by DanPristupov** [comment]
Sorry for the delay.
I think on Mac you can expand/collapse nested folders by holding `alt/option` key when you click on the triangle. Works everywhere: in Finder, XCode and also in Fork.

**Comment by jv-k** [comment]
Didn't know that, thanks! 

Originally I was suggesting a feature to expand *all* folders in the tree view, your tip (as useful as it is) only does one parent folder at a time.

**Comment by DanPristupov** [comment]
Yes, that's true. There is no parent root item which would allow to collapse even the top level folders.

**Comment by jv-k** [comment]
I think this is totally possible, but I can understand if it's not a priority. Thanks
