### ISSUE TITLE
Fetch, Pull, Push, etc labels hidden in MacOs Ventura

### ISSUE THREAD

**Issue by chris-chrono** [ForkIssues/Tracker#1777]
This is for Fork 2.24, activated.

![image](https://user-images.githubusercontent.com/119885759/210013875-bfddfc80-2a4d-41a8-b2f3-58c2d01eca7e.png)

**Comment by DanPristupov** [comment]
We can't fix that.

https://github.com/fork-dev/Tracker/issues/1774
https://github.com/fork-dev/Tracker/issues/1735

**Comment by cmjsae** [comment]
Understood, @DanPristupov - thank you

**Comment by DanPristupov** [comment]
We added labels back on macOS 13 in Fork 2.28. Please check for updates.

**Comment by larryNexus** [comment]
I don't seem to have access to this update. My machine is saying that I'm on the latest, at 2.27.1. Is 2.28 released?

**Comment by DanPristupov** [comment]
@larryNexus you switched Fork to the stable update channel (check preferences).

**Comment by larryNexus** [comment]
@DanPristupov Thanks, forgot that was an option!
