### ISSUE TITLE
Diff view broken with "fatal: unknown value for --diff-merges: 1\n"

### ISSUE THREAD

**Issue by atsnisov** [ForkIssues/Tracker#1778]
The diff view is broken e.g. when clicking on a commit or a stash. The full error message is
```
gitUnknownError(output: "", error: "fatal: unknown value for --diff-merges: 1\n")
```

Version 2.24.1

<img width="554" alt="image" src="https://user-images.githubusercontent.com/2471452/210252523-6161ed5a-e364-4711-a6b6-bc1c5adc457a.png">

What could cause this? This started happening to me sometime during December 2022.

**Comment by DanPristupov** [comment]
Update git or switch for to the internal git instance.

**Comment by atsnisov** [comment]
It worked. I was running git version 2.30.0 and now changed to 2.36.1. Required restart of Fork.

Thanks for such a fast reply! 🚀
