### ISSUE TITLE
BUG - 'Stage' button no longer appears in git diff

### ISSUE THREAD

**Issue by clounie** [ForkIssues/Tracker#1779]
See recording below.
* Fork 2.24.1
* macOS 12.6.1 Monterey

**Expected:** the Stage/Discard buttons to be highlighted wherever I am in that box.

**Workaround:** is that click+drag produces a box with those buttons.

https://user-images.githubusercontent.com/11947182/210436512-ae2f630c-345c-4bcc-bb19-85b73948611d.mov

**Comment by DanPristupov** [comment]
Thank you for the bug report.
Do you have a large monitor?

**Comment by clounie** [comment]
Yes - 4k.

It does look like it works properly on laptop. But not when plugged into monitor.

**Comment by DanPristupov** [comment]
The problem must be fixed in Fork 2.25.
