### ISSUE TITLE
[BUG] Whole file is commited although there were unstaged changes

### ISSUE THREAD

**Issue by SaqibJDev** [ForkIssues/Tracker#1780]
I have a file with some staged and unstaged changes. When I commit, I would expect only the staged changes to be added to my commit. But lately, the whole file gets committed along with the unstaged changes.
Version 2.24

**Comment by DanPristupov** [comment]
Check hooks.

**Comment by SaqibJDev** [comment]
Thanks for the quick answer. Seems that was the issue.
