### ISSUE TITLE
Change remote in "Pull" dialog resets branch selection

### ISSUE THREAD

**Issue by vitalyster** [ForkIssues/Tracker#1784]
Broken recently, works before, still works in Windows version

https://user-images.githubusercontent.com/1052407/211192678-5c6acbd0-e9f9-4f8a-9847-81c285f8379a.mov

**Comment by DanPristupov** [comment]
> Broken recently

Most likely it hasn't.


The logic after changing the remote is the same in both Windows and Mac versions:

- select upstream of the active local branch
- otherwise select remote branch with the same name as the active branch
- otherwise select nothing

**Comment by vitalyster** [comment]
I'm not sure what is wrong with my setup? I'm using the same repository with two remotes on Windows and Mac. Windows version display "origin/master" in branch combobox and it is changed to "github/master" after switch.
![image](https://user-images.githubusercontent.com/1052407/211193736-59f2f1f5-0e9d-43d7-9ace-c50e5ca7a1d6.png)
![image](https://user-images.githubusercontent.com/1052407/211193786-dbb565bb-81fa-4993-ba7f-0fb750bca30e.png)

**Comment by vitalyster** [comment]
I did a fresh clone from "origin", added "github" remote and seeing the same issue in "Pull" dialog after that

**Comment by DanPristupov** [comment]
You are right! I've reproduced the problem.

👍

I'm going to have a look later.

**Comment by vitalyster** [comment]
Fixed in 2.25.1 👍

**Comment by DanPristupov** [comment]
Thank you for noticing that difference in the first case 👍
