### ISSUE TITLE
"Reset branch to Here..." removes untracked files 

### ISSUE THREAD

**Issue by vitalyster** [ForkIssues/Tracker#1785]
If I do `git reset --hard` from CLI it does not touch untracked files, while Fork deletes them if I select "Hard: discard all local changes" reset type

**Comment by DanPristupov** [comment]
> Fork deletes them if I select "Hard: discard all local changes" reset type

No, it doesn't.


https://user-images.githubusercontent.com/618115/211193096-03f62c56-ae3b-4824-983d-bd3da3cec990.mov

**Comment by vitalyster** [comment]
OK, sorry, works for me now too, maybe fixed recently

**Comment by DanPristupov** [comment]
What could have happened, is that you had some non-english keyboard layout, pressed `H` and `enter`. There is a bug that in that case the selection change is not handled and reset remains `--mixed`.

https://github.com/fork-dev/Tracker/issues/1782

**Comment by DanPristupov** [comment]
Even though the description is not accurate, I think you was right and I was wrong. There is a bug with handling keyboard shortcuts in non-English layout and we'll fix it in 2.25.

Thank you for the bug report 👍
