### ISSUE TITLE
Easier interactive rebase rewording with unstaged changes

### ISSUE THREAD

**Issue by JonasPardon** [ForkIssues/Tracker#1786]
My scenario:

I am working on a feature and have a lot of changes. I commit related changes in separate commits to make the code review bearable. I've made 2 commits and have some more changes that I have to commit later.

I just noticed a typo in my last commit message and want to reword it. I go to said commit and do `Interactive rebase > reword message`. It fails because I have unstaged changes, and it tells me to either commit or stash them. 

Would it be possible in such a scenario to do the following?
- Automatically stash any unstaged changes
- Let the user reword the message
- Automatically apply the auto stash en remove the stash

For me, this would improve UX greatly because this is what I have to manually do every time I encounter this scenario and it's kind of a pain in the ass.

Thanks for creating Fork, easily my most used tool in the last five years!

**Comment by DanPristupov** [comment]
Hi.

It's probably related to https://github.com/fork-dev/Tracker/issues/1268

**Comment by JonasPardon** [comment]
> Hi.
> 
> It's probably related to #1268

It is, thanks! Closing this one.

**Comment by DanPristupov** [comment]
Could you copy your original message to that topic, please?

**Comment by JonasPardon** [comment]
> Could you copy your original message to that topic, please?

Done!
