### ISSUE TITLE
DIFF not showing Markdown differences

### ISSUE THREAD

**Issue by nazar** [ForkIssues/Tracker#1788]
Greetings,

Fork version: Version 2.24.2

I just noticed that Fork doesn't show differences in `.md` text files. I'm sure that differences were previously displayed.

![Screenshot 2023-01-17 at 13 53 49](https://user-images.githubusercontent.com/6967/212916899-eb3fed14-8cc0-409c-b88e-3b1fe0989633.png)

Please LMK if there is any further information I can provide to debug this 🙏

**Comment by nazar** [comment]
Sorry for opening this prematurely. Using `git` cli shows that the `git` executable also identifies this file as a binary so it seems Fork is reflecting what the executable is reporting. Looks like I corrupted the file somehow 🤷

**Comment by DanPristupov** [comment]
Check the `.gitattributes` file in the repository root.
