### ISSUE TITLE
Commits order in tree

### ISSUE THREAD

**Issue by Aleksandr-ru** [ForkIssues/Tracker#1790]
Hey! I'm trying to use fork and it looks great, but one thing makes it very hard. 
What is the idea of ordering commits in a tree? Why older commits is upper than newer ones?

Check the screenshot, why selected commit is later than older commits?

![image](https://user-images.githubusercontent.com/15122148/213658386-9b5618de-9a89-4b85-b4eb-7c7e07d7859c.png)

And the following problem, there is unable to see recent activity in repo. 
Check the screenshot, I have large repo and yesterdays changes is palced many many screens down after 2+ year aged commits. Why so?

![image](https://user-images.githubusercontent.com/15122148/213659830-f6f47001-ba2a-4098-8c0a-238ec2b6b602.png)

Please explain the idea of so strange ordering and may be there is a way to display commits ordered by date?

**Comment by DanPristupov** [comment]
> Check the screenshot, why selected commit is later than older commits?

Because topological sorting is more compact. You can switch the commit order in preferences: `Fork -> Preferences -> Sort commit`

> Check the screenshot, I have large repo and yesterdays changes is palced many many screens down after 2+ year aged commits. Why so?

Most likely because someone committed to those branches recently and the topo-sort in git grouped such commits.

**Comment by Aleksandr-ru** [comment]
Thanks! Now it works as expected!)
