### ISSUE TITLE
Latest release notes?

### ISSUE THREAD

**Issue by finestructure** [ForkIssues/Tracker#1791]
Are the latest release notes available somewhere? https://fork.dev/releasenotes is showing 2.20 from 15 Jul 2022 whereas the app is on 2.25.2 right now. I'd love to catch up on what's new :)

**Comment by DanPristupov** [comment]
Yes, we are doing website maintenance during this weekend. We'll fix the release notes today. There are some other minor issues too.

**Comment by finestructure** [comment]
Ah, that's great to hear. Thanks for the quick reply and for making such a great app!

**Comment by DanPristupov** [comment]
And yes, thank you very much for noticing that ❤️.
