### ISSUE TITLE
Add ability to hide branch from UI commit history

### ISSUE THREAD

**Issue by ssbarnea** [ForkIssues/Tracker#1792]
Anyone using `gh-pages` branch to publish github pages, will struggle to use Fork with their repository because the special `gh-pages` branch which is detached will always display on to of their normal repository history, even if they never pulled the branch from the remote.

We need an option to hide such maintenance branch from the UI, so you can confu

![](https://sbarnea.com/ss/fork-gh-pages-branch.png)

**Comment by DanPristupov** [comment]
<img width="526" alt="Screenshot 2023-01-23 at 9 34 40" src="https://user-images.githubusercontent.com/618115/213995893-e3596409-fa2e-4fea-8211-c4d2de77d2bb.png">

**Comment by isaac-weisberg** [comment]
> we beed to be able

His nose is stuffy

![downeyjr](https://github.com/fork-dev/Tracker/assets/36449887/68bd83aa-27eb-495b-a117-bda45b4170fe)
