### ISSUE TITLE
Repository manager window window could show remote URL(s) together with name

### ISSUE THREAD

**Issue by kervich** [ForkIssues/Tracker#1794]
Currently only remote name is shown in repository manager window. Adding remote URL side by side would make the screen much more informative.

**Comment by DanPristupov** [comment]
Where can we add it? Here's an example:
<img width="1099" alt="Screenshot 2023-01-24 at 12 07 46" src="https://user-images.githubusercontent.com/618115/214276272-18f27abb-47a1-4b24-b30f-1058c1b3b072.png">

**Comment by proactive-solutions** [comment]
How about mouse hover event?

**Comment by DanPristupov** [comment]
<img width="503" alt="Screenshot 2023-02-25 at 15 40 48" src="https://user-images.githubusercontent.com/618115/221362905-f587a4fa-56fb-4a49-8acc-6f5db929da1f.png">
