### ISSUE TITLE
Git LFS says everything is up to date....

### ISSUE THREAD

**Issue by aholla** [ForkIssues/Tracker#1795]
When I do a Git LFS Pull, it says everything is upto date but it is not.

I have lots of audio files that are only reading around 133 bytes. I can see these files on Bitbucket and they are around 15Mb for example.

How can I fix this?

**Comment by aholla** [comment]
Just to add to this, I installed SourceTree and when I opened the repo, it detected LFS and said something was missing and if I wanted to fix it. I tapped fix it and then it sorted everything out. Pulled the LFS files correctly.

Im not sure what has gone wrong, I would prefer to use Fork but will continue to use SourceTree for now.

**Comment by DanPristupov** [comment]
Did you initialize Git LFS (Repository -> LFS -> Initialize)? It's difficult to say now, but it looks like you didn't.

**Comment by aholla** [comment]
Yes, I did. It actually happened on two different repos.

**Comment by DanPristupov** [comment]
OK, what are the steps to reproduce the problem?

1. Clone a repo with LFS
2. Repository -> LFS -> Initialize
3. Repository -> LFS -> Pull
4. Check the files, none of them contain the expected data.

Is that right?
