### ISSUE TITLE
[Feature Request] Image diff option to display pixel differences 

### ISSUE THREAD

**Issue by misprintt** [ForkIssues/Tracker#1796]
The existing image diff options are great, however they don't work very well for comparing subtle differences (e.g. different versions of the same screenshot)

Image comparison tools typically offer a pixel diff map option that highlights which pixels are different between the two images.

Please consider adding this :)

**Comment by DanPristupov** [comment]
> Image comparison tools typically offer a pixel diff map option that highlights which pixels are different between the two images.

Can you show a few screenshots?

**Comment by misprintt** [comment]
This example (from https://github.com/yahoo/blink-diff) - shows how it can highlight changes that aren't immediately obvious

![image](https://user-images.githubusercontent.com/525045/216848114-498a0579-d061-4d9e-89b2-547af6f9e86b.png)


Some example libraries that offer this:
- https://imagemagick.org/script/compare.php
- https://github.com/yahoo/blink-diff
- https://github.com/mapbox/pixelmatch
- https://github.com/uber-archive/image-diff

**Comment by ZevEisenberg** [comment]
Kaleidoscope also does this really well. It has a slider to fade in the diff overlay, so you can get a sense of what parts of the underlying images are different.

**Comment by DanPristupov** [comment]
@ZevEisenberg 

Fork has onion skin too.
https://github.com/fork-dev/Tracker/assets/618115/cc228376-fee0-42d7-ac15-5fa70ec3849e

Or do you mean onion skin + diff highlighting?

**Comment by ZevEisenberg** [comment]
Exactly - sometimes, the diff is too subtle to see in onion skin by itself, so onion skin that fades in the 1-bit diff on top of either the "before" or "after" image would be useful.

Also, the ability to pinch-to-zoom in that view would be useful so you can see individual pixels in a large image.

**Comment by shane-exygy** [comment]
This doesn't appear to exist despite being marked completed in 2024.

It would be really nice to have.  GitHub Desktop offers it when you're creating PRs, but not the review web tool.

**Comment by ZevEisenberg** [comment]
You can click this little checkerboard button at the upper right of the image diff view to enable pixel-level diffing. Perhaps not the most discoverable, but definitely useful! (It would be more useful if you could zoom in on the images!)

<img width="185" alt="Image" src="https://github.com/user-attachments/assets/a1eb895d-2d23-41f8-a665-dd5489e1d3c4" />

**Comment by shane-exygy** [comment]
Thank you!  That is promising but I don't see that.  

To be clear I'm on /pull/#####/files and select an image and the upper right looks like the following which is a little different than yours.  Can you more directly point me at what page you're on in your screenshot?

<img width="457" alt="Image" src="https://github.com/user-attachments/assets/210446c1-7275-4866-9ba0-becc945dea6a" />

**Comment by ZevEisenberg** [comment]
I'm in the [Fork app](https://fork.dev), for which this repo is the bug tracker. Your screenshot is from the GitHub website.

**Comment by shane-exygy** [comment]
Ah sorry, I lost my context on the way to finding this.  Apologies and now I know about Fork!
