### ISSUE TITLE
A git pull just overwrote a local commit.

### ISSUE THREAD

**Issue by gsp100677** [ForkIssues/Tracker#1798]
I just pulled a remote branch into my local one, and it seems to have overwritten a local commit (losing me tons of work). I did not force, and it doesn't look like there's any option to accidentally force pull in Fork anyway.

I had two local branches tracking the same remote branch. Made changes in local-branch-a, then pushed them to remote-branch. Then checked out local-branch-b and pulled remote-branch (with rebase instead of merge selected, but not stash and reapply local changes).

At no point did I force anything.

**Comment by DanPristupov** [comment]
Check request and output of the pull command (click on the status control on the toolbar).

**Comment by DanPristupov** [comment]
Enable Reflog (View -> Show Lost Commits) to find the missed commit.

**Comment by gsp100677** [comment]
These are very useful suggestions - thanks! 


I didn't see them till today, so unfortunately in the case of the status control in toolbar, I can no longer see the pull command output because multiple auto-fetches seem to have pushed the pull out of the history (it appears to keep the last 30 commands).

However, eEnabling reflog allowed me to find it quickly and recover my changes - thanks, you saved me almost a day's worth of work!
