### ISSUE TITLE
"Merge in fork" is broken for .pbxproj .. it doesn't show the conflicts to be fixed

### ISSUE THREAD

**Issue by SoufianHossam** [ForkIssues/Tracker#1799]
When trying to fix a conflict in `project.pbxproj` file the merger does not show you what is going on in this file.

![Screenshot 2023-01-29 at 8 34 54 AM](https://user-images.githubusercontent.com/29013948/215309603-624c300e-d997-4ae7-897a-bd522ba4837d.png)

![Screenshot 2023-01-29 at 8 35 04 AM](https://user-images.githubusercontent.com/29013948/215309624-414ce65d-2627-4382-8cd4-4b0c78a0c3ec.png)

**Comment by DanPristupov** [comment]
Git couldn't recognize the file content as text.
Try to add `*.pbxproj text` to the `.gitattributes` file. (https://www.git-scm.com/docs/gitattributes)
