### ISSUE TITLE
[Suggestion]: UI

### ISSUE THREAD

**Issue by xulsup** [ForkIssues/Tracker#1800]
1. Put the `File Tree` Tab to the Left. I think this will be better. And give the file history a bigger view.
<img width="878" alt="图片" src="https://user-images.githubusercontent.com/17876392/216245542-6357e483-fdaa-4a9b-a32c-717716fbffdb.png">

**Comment by DanPristupov** [comment]
The File Tree tab displays file tree **of the selected commit** and logically belongs to the commit details section.
