### ISSUE TITLE
Show all User IDs in the GPG keys list

### ISSUE THREAD

**Issue by DominikPalo** [ForkIssues/Tracker#1801]
I'd like to point out the issue I'm having with the Fork client on macOS. I use a GPG key containing multiple User IDs (emails). But as you can see on the attached screenshots, the GPG keys list in Fork shows only the last User ID. It is a bit confusing for me because I use multiple GPG keys - some of them just with a single User ID. It would be much better to show all User IDs/emails inside the <> bracket for a particular GPG key (similar to how GitHub works - see that last screenshot) or show the main email address assigned to the Key (email from the "Key" tab). Displaying only the latest email doesn't really make sense, as it can change anytime (sometimes I'm adding/removing user IDs from my GPG key)

![image](https://user-images.githubusercontent.com/1623257/216269773-2587bef2-c363-4b66-a736-810235a8e292.png)
<img width="904" alt="image" src="https://user-images.githubusercontent.com/1623257/216270655-b16f15fa-b621-4862-bbbb-55ab7f6b9ddd.png">
![image](https://user-images.githubusercontent.com/1623257/216269895-feef22b9-2491-4399-b45c-9ab7d0203982.png)
![image](https://user-images.githubusercontent.com/1623257/216269990-7da728da-463b-4b7b-bc88-4c1cf15cb485.png)

**Comment by DanPristupov** [comment]
Hi.

I'm not a very big expert in gpg signing and trying to figure out your issue.

> It would be much better to show all User IDs/emails inside the <> bracket for a particular GPG key

So, is the proposal to remove the identity name and list all identity emails in the dropdown item title?

Instead of:
`09976F5F Dominik Paľo <dominik@palo.sk>`

Make it:
`09976F5F <dominik@palo.sk>, <dominik@slido.com>, <dominik@cisco.com>`

**Comment by DominikPalo** [comment]
@DanPristupov I'd probably include the full name from the key signature and list all email addresses from user IDs. So in my case, it would be:
`09976F5F Dominik Paľo  <dominik@palo.sk>, <dominik@slido.com>, <dominik@cisco.com>`

But, I have an idea - what about listing all GPG keys in a List component (instead of using a simple/text dropdown)? Something like this:
<img width="842" alt="image" src="https://user-images.githubusercontent.com/1623257/225935256-4b418af8-14b0-47ff-9708-26fb49d8c4b2.png">

**Comment by DanPristupov** [comment]
I think it's wrong to assume that the name of the identity is the same.
