### ISSUE TITLE
Issue with cs-cz characters in filename

### ISSUE THREAD

**Issue by ferben** [ForkIssues/Tracker#1803]
See screenshot.
There is file on disk "žluťoučký kůň.pdf" but after commit/push on Fork list this is badly encoded on macOS.

![ScreenShot 2023-02-06 at 13 39 18](https://user-images.githubusercontent.com/45659268/216974820-f42c3b54-d355-47a8-a117-5b77477f8a20.png)

**Comment by DanPristupov** [comment]
I can't reproduce that. How did you create that file?

<img width="410" alt="Screenshot 2023-02-06 at 14 57 46" src="https://user-images.githubusercontent.com/618115/216990430-51d3f325-1789-481a-b0d0-7bc19bbe72b3.png">
