### ISSUE TITLE
Feature Request: Add option to copy commit message in context menu when a commit is right-clicked

### ISSUE THREAD

**Issue by rstewa** [ForkIssues/Tracker#1804]
## Problem/Description

As a user, I want to be able to quickly copy a previous commits *Commit Subject/Description* so that I can reuse it in a new commit. 

My job requires me to use similar commit messages all the time so I hope you will consider adding this feature.

## Potential Solutions

I think a drop down menu of previously used commit messages could be added to the right of the commit subject box
![feature-request-img2](https://user-images.githubusercontent.com/70178227/217123433-ec0c9249-a074-450e-912c-4ecf19e52366.png)

### OR

this option could be added to the context menu when a commit is right-clicked
![feature-request-img1](https://user-images.githubusercontent.com/70178227/217124290-6e97afc2-e44f-45a7-824f-cac898361ad9.png)

**Comment by DanPristupov** [comment]
> I think a drop down menu of previously used commit messages could be added to the right of the commit subject box
![feature-request-img2](https://user-images.githubusercontent.com/70178227/217123433-ec0c9249-a074-450e-912c-4ecf19e52366.png)

It is here already. The arrow on your screenshot points to it.

> this option could be added to the context menu when a commit is right-clicked\
If you press Alt/Option, 'Copy Commit Info' will appear, though it also includes abbreviated (7 characters) SHA.

**Comment by rstewa** [comment]
Wow, I'm dumb. Not sure how I missed that. Thanks for the reply.
