### ISSUE TITLE
Fork doesn't show diffes in commits

### ISSUE THREAD

**Issue by xneg** [ForkIssues/Tracker#1805]
Whenever I click on any commit I get the following error
`gitUnknownError(output: "", error: "fatal: unknown value for --diff-merges: 1\n")`

<img width="577" alt="image" src="https://user-images.githubusercontent.com/5748886/217231687-adcccc58-4717-4aa2-bea2-febcfa7060b3.png">

Initially, it worked well but now something wrong. I think it is the issue with trailing `\n` but I don't know where can I fix it. Maybe there are some settings to make changes to?

**Comment by DanPristupov** [comment]
You are using old git. Either switch Fork back to the internal git or update your system git.

**Comment by xneg** [comment]
Thank you, @DanPristupov ! It helped!
