### ISSUE TITLE
Cancel button not working in squash menu

### ISSUE THREAD

**Issue by pierre-x** [ForkIssues/Tracker#1808]
When the repository contains non-accessible submodules, the cancel button in the squash menu no longer works.

**Comment by DanPristupov** [comment]
Which squash menu?

**Comment by pierre-x** [comment]
I mean the "interractively rebase <mybranch> to Here..." menu

<img width="573" alt="Screenshot" src="https://user-images.githubusercontent.com/17099105/223691698-b6181152-f42f-4401-9798-bf86f4badab7.png">
