### ISSUE TITLE
"Git Flow > Start Hotfix" starts a release instead of hotfix

### ISSUE THREAD

**Issue by pedrov** [ForkIssues/Tracker#181]
The "Start Hotfix" option on the "Git Flow" action menu actually starts a release instead of an hotfix.

![image](https://user-images.githubusercontent.com/491646/34096354-f0836046-e3cc-11e7-8708-a30f547c390e.png)

This issue is reproducible on latest version (1.0.61), without any special context conditions.

**Comment by DanPristupov** [comment]
@pedrov yes, you are right. Thank you for reporting that. Going to fix in the next update.

**Comment by pedrov** [comment]
Thank you. Congratulations on the application. Awesome piece of software.

**Comment by DanPristupov** [comment]
Fixed in 1.0.62
