### ISSUE TITLE
I'm no longer able to remove items from the toolbar (by dragging them away)

### ISSUE THREAD

**Issue by slymax** [ForkIssues/Tracker#1811]
Version 2.26 on macOS 12.6.2

**Comment by DanPristupov** [comment]
Looks like a bug in macOS 12.6.2. It worked for me on 12.5 and stopped after update to 12.6.2.

**Comment by slymax** [comment]
yeah I also noticed the issue just after updating. I just tried upgrading to 13.2 but toolbar customization is now disabled entirely (#1774). I guess I'm stuck with the default toolbar either way.
