### ISSUE TITLE
[Feature Request] Jump to branch keyboard shortcut

### ISSUE THREAD

**Issue by bbukraLTX** [ForkIssues/Tracker#1814]
Would be very useful if there was a keyboard shortcut to jump to another branch (maybe even without check out). As far as I can see there's currently no such option, and I have to filter my branch list manually to find my branch.

I tried to find a similar issue but couldn't, so sorry if it's a duplicate.

**Comment by DanPristupov** [comment]
You can use `Cmd+P` -> Checkout -> `<branch name>`

**Comment by DanPristupov** [comment]
As an alternative you can press `Cmd+B`, but I think we can remove that view in the future...

**Comment by bbukraLTX** [comment]
> As an alternative you can press Cmd+B, but I think we can remove that view in the future...

I think I'll find it very useful tbh. Also I can't see it documented in [here](https://github.com/fork-dev/Docs/blob/master/keyboard-shortcuts-mac.md), so perhaps it's worth adding that unless you end up removing.

**Comment by bbukraLTX** [comment]
@DanPristupov It seems like Cmd+B was removed, and Cmd+P is way more clunky. Any idea why it was removed? Was it changed to another key?
Also there should probably be a proper documentation of all keyboard shortcuts.
This file is truly not up to date.
https://github.com/fork-dev/Docs/blob/master/keyboard-shortcuts-mac.md

**Comment by NSArtem** [comment]
I'd like to fully support the request to return back this shortcut and would like to add my voice. I have almost three years of muscle memory of "Cmd+B" in Fork! :)

Now I'm sticking to version 2.27.

**Comment by DanPristupov** [comment]
In 2.29 we made `⌘B` open 'Quick Launch -> Checkout Branch' view.
