### ISSUE TITLE
When creating a GitHub pull request, allow selecting a target branch besides main

### ISSUE THREAD

**Issue by jehrenzweig-leagueapps** [ForkIssues/Tracker#1816]
I can't figure out how to create a GitHub PR for my current branch that targets a branch besides `main`.  If this feature already exists, I'd love to know how to do it.  Otherwise, read on...

Here's an example of what I see in Fork's left content pane, when I have the `web-work` repository opened:
```
Branches
   - main
   - ft-widget
   - ft-widget-buttton (checked out)
Remotes
Tags
Stashes
Submodules
```

Let's say I want to create a PR that merges the `ft-widget-buttton` branch into the `ft-widget` branch.  Here's what I'd like to do:

1. I verify that the `ft-widget-button` branch is currently checked out.
2. I right-click the `ft-widget` branch name, then click the "_Create Pull Request on 'origin'..._" menu option.
3. A new browser windows opens to `https://github.com/MyOrg/web-work/compare/ft-widget...ft-widget-button?expand=1`.

Right now, it seems like the browser window always opens to `https://github.com/MyOrg/web-work/compare/XXX?expand=1`, where `XXX` is the name of the branch you right-clicked on, and `main` is the target branch.

**Comment by DanPristupov** [comment]
Hi. Fork does not specify the destination branch. It just passes the target branch as a parameter and the web-ui allows to select the destination.
