### ISSUE TITLE
Failed using SSH over the HTTPS port

### ISSUE THREAD

**Issue by shiroyk** [ForkIssues/Tracker#1817]
The firewall of the network I'm using refuse to allow SSH connections entirely.
I attempt to using SSH over the HTTPS port.
It works fine on the terminal but not in Fork, and all SSH configuration not selected.
```
Host github
    HostName ssh.github.com
    User git
    Port 443
    ...
```
```
...
debug1: client_input_hostkeys: searching /Users/shiroyk/.ssh/known_hosts for [ssh.github.com]:443 / (none)
debug1: client_input_hostkeys: searching /Users/shiroyk/.ssh/known_hosts2 for [ssh.github.com]:443 / (none)
debug1: client_input_hostkeys: hostkeys file /Users/shiroyk/.ssh/known_hosts2 does not exist
debug1: client_input_hostkeys: host key found matching a different name/address, skipping UserKnownHostsFile update
debug1: Sending environment.
debug1: channel 0: setting env LC_TERMINAL_VERSION = "3.4.19"
debug1: channel 0: setting env LANG = "en_US.UTF-8"
debug1: channel 0: setting env LC_TERMINAL = "iTerm2"
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
Hi shiroyk! You've successfully authenticated, but GitHub does not provide shell access.
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 3156, received 2704 bytes, in 0.7 seconds
Bytes per second: sent 4417.5, received 3784.9
debug1: Exit status 1
```
<img width="682" alt="image" src="https://user-images.githubusercontent.com/20229086/219311786-5029018c-3a45-4fc1-aeea-fda672fe169d.png">
<img width="850" alt="image" src="https://user-images.githubusercontent.com/20229086/219311905-1d050428-8786-46ac-862d-0a40bf2e1cf5.png">

**Comment by DanPristupov** [comment]
Try to switch Fork to the system git instance

**Comment by shiroyk** [comment]
> Try to switch Fork to the system git instance

Not working, same error

**Comment by DanPristupov** [comment]
1. Does `git fetch` work in the command line?
2. I think it shouldn't because your config says:
```
Host github
    HostName ssh.github.com
```
However, the url doesn't match the host. Shouldn't it be `ssh://git@github.com/owner/repository.git`?

**Comment by shiroyk** [comment]
> 1. Does `git fetch` work in the command line?
> 2. I think it shouldn't because your config says:
> 
> ```
> Host github
>     HostName ssh.github.com
> ```
> 
> However, the url doesn't match the host. Shouldn't it be `ssh://git@github.com/owner/repository.git`?

omg my address is wrong, now is working, thinks.
