### ISSUE TITLE
Shift + Cmd + C aka Commit does not work

### ISSUE THREAD

**Issue by RalfKoch** [ForkIssues/Tracker#1818]
Hi, I am using Fork with my Mac, but the keyboard shortcut Shift + Cmd + C does not seem to work.
Can you check in on that?

And, keep up the good work!

**Comment by DanPristupov** [comment]
Still works for me. May be some other application steals it.
1. Try to restart the computer
2. Use Cmd+1 as an alternative.

**Comment by RalfKoch** [comment]
Found it: Safari when Developer Menu is active this command is being used to show the Javascript console.
