### ISSUE TITLE
[UI Suggestion with mockup] On the left sidebar, change the fixed links and small buttons to be a toolbar with big buttons only

### ISSUE THREAD

**Issue by ADTC** [ForkIssues/Tracker#1819]
Current UI vs Proposed UI:

<img width="269" alt="image" src="https://user-images.githubusercontent.com/6047296/219848409-3001208f-cb1f-44f5-a43d-b5d9a440a0e0.png"> <img width="268" alt="image" src="https://user-images.githubusercontent.com/6047296/219849882-1233ea44-61fe-4574-b20d-b3ccf225d934.png">

* The list with "Local Changes" and "All Commits" and the two small lonely buttons for Branches and Search are replaced with one toolbar with big buttons.
* To signify that the Branches and Search are for the left pane, and the other two are for the right side, they are arranged in that order and a separator is in between them.
* The blue indication color is also applied for Changes and Commits buttons to signify which one is active.
* The repo name is adjusted to align with the red traffic light (close button).
* The button for repo settings is enlarged and aligned the same distance from right edge as the repo name is from left edge.
* A tooltip should appear when the mouse hovers on each of the buttons, indicating the text description of its function (such as "Local Changes" or "Repository Settings").

_Note: The mock-up for the proposed UI is not pixel-perfect._

**Comment by DanPristupov** [comment]
I think the existing layout is more clear.

**Comment by ADTC** [comment]
Would be nice to have an option as I felt it is cluttered and the buttons are too small. I didn't think the visible labels are strictly necessary, since other toolbar buttons don't have any.

Anyway, just for your consideration. Thank you.
