### ISSUE TITLE
In a case you entered incorrect password, please update it in Keychain Access application.

### ISSUE THREAD

**Issue by dankehotfire** [ForkIssues/Tracker#1820]
After updating Ventura 13.2.1 i have this error while using fork. Everything is ok from terminal or other git clients
Before updating everything was good

<img width="962" alt="image" src="https://user-images.githubusercontent.com/77940475/220043300-5807747b-0f1a-4504-b482-91a84cdf7164.png">

**Comment by DanPristupov** [comment]
1. Open Fork -> Configure SSH keys and ensure that all ssh keys are unchecked. Otherwise Fork will override the system SSH configuration.
2. You man need to open KeyChain Access, find an entry related to your ssh `fork:/path/to/key` and delete it. Then fetch again.

**Comment by dankehotfire** [comment]
thanks a lot!
