### ISSUE TITLE
Option for merge commit message

### ISSUE THREAD

**Issue by jonstodle** [ForkIssues/Tracker#1821]
When merging a remote branch into another the commit message says:

> Merge remote-tracking branch 'origin/master' into my-local-branch

It'd be nice to have an option to set this default message. Either something templated, or something along the lines of what GitHub offers for PRs

![GitHub merge message options](https://user-images.githubusercontent.com/1719761/220321856-b000d73a-9bfe-4941-85bc-5b69b6967219.png)

**Comment by DanPristupov** [comment]
I think git doesn't allow to customize the default merge commit message.

**Comment by jonstodle** [comment]
Good enough for me

**Comment by DanPristupov** [comment]
Just FYI, if you merge with `don't commit' option, you will be able to edit the commit message in the 'Local Changes' view.

<img width="587" alt="Screenshot 2023-02-21 at 18 36 28" src="https://user-images.githubusercontent.com/618115/220418881-39da3614-b5c7-4d00-b976-e83ec203ad19.png">

Related topic: https://github.com/fork-dev/Tracker/issues/488
