### ISSUE TITLE
error: patch does not apply

### ISSUE THREAD

**Issue by pgundlach** [ForkIssues/Tracker#1822]
I currently evaluate Fork, but I have a problem with staging a few lines in my code:

<img width="1715" alt="fork-stage" src="https://user-images.githubusercontent.com/209434/220574545-64913bb7-6477-49f3-be3e-d7ca4aae61de.png">

When I click on `stage`, I get the following window:

<img width="837" alt="errorwindow" src="https://user-images.githubusercontent.com/209434/220574709-b62af9da-752e-4b85-83c5-7241ac18e352.png">

What can I do?

(Just to let you know: GitX does not have a problem with the code, but the change looks different:
  
   
<img width="1427" alt="gitx" src="https://user-images.githubusercontent.com/209434/220574979-3876e51c-ce7b-4d76-8874-7946a8979b9c.png">

)

I have tried Version 2.26.1 on macOS X (latest update)

**Comment by pgundlach** [comment]
I found out what causes this issue.

<img width="143" alt="ignorespace" src="https://user-images.githubusercontent.com/209434/220576135-7350eb9a-49f7-4dba-9915-959d20f79b09.png">

I had the 'ignore whitespace' button active. When I deactivate, I don't have the error anymore.

**Comment by DanPristupov** [comment]
Yes, sometimes git can't recognize patch when ignore-whitespaces is enabled.

**Comment by krin-san** [comment]
I don't have 'ignore whitespace' enabled but get the same error when trying to stage part of the file at the end of file. The key to reproduce it is to set "Number of visible lines" to minimum value of 1 line. More than that – and there's no error.

<img width="613" alt="Action" src="https://github.com/fork-dev/Tracker/assets/2318002/d2bb3a5e-bf45-431b-86be-eb0ec4c8f720">
<img width="495" alt="Error" src="https://github.com/fork-dev/Tracker/assets/2318002/62b60954-bb77-4414-ba8a-aa93b01a9718">


Committed file contents:
```
Committed

Committed
Committed
Committed
Committed
Committed

```
Changed file contents:
```
Committed

Keep that unstaged

Committed
Committed
Committed
Committed
Committed

Want to stage that

```

**Comment by DanPristupov** [comment]
@krin-san most likely git can't recognize the patch with that little context (just 1 line).
