### ISSUE TITLE
Squash acted like Fixup in Interactive Rebase

### ISSUE THREAD

**Issue by ADTC** [ForkIssues/Tracker#1824]
I tried Interactive Rebase in Fork and I must say I am **very disappointed**. I chose to Squash some commits and although the commit that they are squashing into (let's call it the target commit) had changed from Pick to Reword.

This is all well and good, but when I clicked Rebase, none of the these expectations happened:

- The messages from the Squash commits were not melded into the target commit's message.
- I had not been asked to confirm the rewording of the commits marked with "Reword". (When using `git rebase` on the command line, it stops for every instance of Reword with the melded commit message, asking me to confirm.)
- There was no log for the rebase commands in the command log list.
- There's no way to bring back the Interactive Rebase to make corrections. (If I start a new one I have to do all my changes over again, and I had spent a considerable amount of time.)

It looked like there's zero difference between Squash and Fixup. This is a serious failure and must be rectified ASAP.

**Comment by ADTC** [comment]
I'm testing and making some observations:
- If I select Squash downwards (commit 1, commit 2, commit 3) then the target commit 4 gets the melded commit message. The description has all the messages from 1 to 3. This seems to work correctly.
- But if I select Squash upwards (start with commit 3, then commit 2, commit 1), then the target commit 4 has an empty commit description and it says "Reword" even though nothing has changed in the commit message. This has to be fixed.
- If I change any commit with Squash to Fixup or Drop, then back to Squash again, its target commit remains with an empty commit description (acting as if it's still Fixup/Drop). This has to be fixed.

I think it's very important to stop at each commit with Reword, and ask to "Confirm" that the rewording is correct when I click on Rebase. Because once I click this button and the action is fully done, there's no going back! There's no way to return to the draft state of the interactive rebase.

Also, pressing Esc key with Interactive Rebase open just closes it without any confirmation. All draft work is lost. Wow!

**Comment by DanPristupov** [comment]
Thank you, we will have a look

**Comment by DanPristupov** [comment]
Fixed in 2.27
