### ISSUE TITLE
100% crash on my new laptop

### ISSUE THREAD

**Issue by maetolay** [ForkIssues/Tracker#1828]
Hi, I just got my new Mac M2 Pro today and get and constantly crashes on the application. The log can be found below.

Can you please help
[crashlog.log](https://github.com/fork-dev/Tracker/files/10831313/crashlog.log)

**Comment by DanPristupov** [comment]
Try `defaults delete com.DanPristupov.Fork` in terminal

**Comment by maetolay** [comment]
Yes!! That's working!! Thanks for very swift reply!!

This could be a very good help command on the main website BTW

**Comment by DanPristupov** [comment]
A better approach would be to fix that, I think :)
