### ISSUE TITLE
Create folder open action in macos

### ISSUE THREAD

**Issue by mnhattt** [ForkIssues/Tracker#1835]
As newest update, fork can't open repy by drag and drag. So How can I create folder quick action in macos which help open repo by fork cli ?

Thanks.

**Comment by DanPristupov** [comment]
If Fork is running, you can drag and drop a folder on the application window.
Otherwise you can downgrade to https://cdn.fork.dev/mac/Fork-2.25.5.dmg and wait for the fix

**Comment by mnhattt** [comment]
yep, I can't wait for the fix but open by quick action still the case :D

I best thing I can do with try with `--args` 
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/25035023/222666356-4d0eb408-9cdb-4144-bae0-956a086bc82b.png">

**Comment by DanPristupov** [comment]
Fork CLI tool (Preferences -> Integration) allows to use `fork /path/to/repo` command

**Comment by mnhattt** [comment]
thank for your support

I find the way

https://stackoverflow.com/questions/64040393/open-a-folder-in-vscode-through-finder-in-macos

Instead open with vscode, I choose fork
![image](https://user-images.githubusercontent.com/25035023/222881186-9b0763c7-ac00-4447-ad34-3c120cee168e.png)

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/25035023/222881275-5f53952d-90c0-4362-b291-83d3055a439a.png">
