### ISSUE TITLE
I get an error when trying to delete a branch

### ISSUE THREAD

**Issue by keith27staines** [ForkIssues/Tracker#184]
Seems to happen every time, whether or not I've already deleted the remote branch on github. Also happens even on purely local branches.

![screen shot 2017-12-20 at 08 54 14](https://user-images.githubusercontent.com/1099170/34198871-bb1ef792-e563-11e7-941d-8c49901fb9e0.png)

**Comment by DanPristupov** [comment]
This turned out to be a wrong error message. The fix is going to be available in 1.0.63
