### ISSUE TITLE
[BUG] `Show in file tree` on files over 3 levels deep crashes the app

### ISSUE THREAD

**Issue by gentique** [ForkIssues/Tracker#1840]
<img width="538" alt="issue" src="https://user-images.githubusercontent.com/15278390/224701286-41e3d5fc-394c-4f7d-bb92-601696771406.png">

If it doesn't crash, try collapsing the folders on the file tree view and going back to commits and retrying to show in file tree.

**Comment by DanPristupov** [comment]
I think we fixed that in 2.25.
