### ISSUE TITLE
[Feature] Support custom gpg path

### ISSUE THREAD

**Issue by cntrump** [ForkIssues/Tracker#1842]
I install gpg via macports, so `gpg` installed at `/opt/local/bin`

Fork can't find gpg unless it installed at `/usr/local/bin`

**Comment by DanPristupov** [comment]
Where gpg is installed on macports?

**Comment by cntrump** [comment]
> Where gpg is installed on macports?

```
/opt/local/bin/gpg

```

**Comment by daniel-white** [comment]
Yes please. I install via gpg tools. when i switch to using homebrew git, it looks for gpg in homebrew. i'm on apple silicon and gpg tools installed in /usr/local/bin/gpg

**Comment by DanPristupov** [comment]
@daniel-white what Fork version do you use? If it's 2.27, please try this one: https://cdn.fork.dev/mac/Fork-2.27.1.dmg

**Comment by daniel-white** [comment]
yea i just went to 2.27 this morning and it went fine. i also `brew install gnupg` and it did light up

**Comment by gfiumara** [comment]
There's also a git config parameter, [`gpg.program`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-gpgprogram), that could/should be consulted if present. You might consider looking for that _first_ in `Contents/Resources/gpg.sh`.

**Comment by cntrump** [comment]
Fork 2.7.1
```bash
#!/bin/sh

#  gpg.sh
#  Fork
#
#  Created by Danil on 19/10/2017.
#  Copyright © 2017 Danil. All rights reserved.

if [[ $(uname -m) == 'arm64' ]]; then

    if test -f "/opt/homebrew/bin/gpg"; then
        /opt/homebrew/bin/gpg --batch --no-tty "$@"
    else
        /usr/local/bin/gpg --batch --no-tty "$@"
    fi
else
    /usr/local/bin/gpg --batch --no-tty "$@"
fi
```

Why hardcode gpg path in shell script?

**Comment by DanPristupov** [comment]
Because I don't know where gpg is located.

**Comment by daniel-white** [comment]
@DanPristupov Why not use gits configuration for that or consult path?

**Comment by DanPristupov** [comment]
@daniel-white 

> Why not use gits configuration for that or consult path?

As I said, because we don't know where gpg is located.

There are other reasons as well:
1. Fork must be easy configurable
2. Fork gpg configuration must not affect other applications. So we can't change `gpg.program` globally.
3. `gpg.program` can be misconfigured (or configured to be used in a particular terminal, assuming ENV and PATH configuration).

**Comment by DanPristupov** [comment]
Even though Fork doesn't support custom gpg paths, it we added support for `macports` as the first post asked, so I think we can close this issue.
