### ISSUE TITLE
GPG signing using GPG Suite with 2.27

### ISSUE THREAD

**Issue by milanhorvatovic** [ForkIssues/Tracker#1843]
The new version 2.27 broke support for GPG signing using GPG Suite installation.

The difference is in gpg.sh what cause this problem:
2.26:
````
/usr/local/bin/gpg --batch --no-tty "$@"
````
2.27:
````
if [[ $(uname -m) == 'arm64' ]]; then
    /opt/homebrew/bin/gpg --batch --no-tty "$@"
else
    /usr/local/bin/gpg --batch --no-tty "$@"
fi
````

Would be possible to provide support to define path for GPG tool or extend this script to cover more possibilities?

**Comment by DanPristupov** [comment]
Hi, can you try 2.27.1? https://cdn.fork.dev/mac/Fork-2.27.1.dmg

In 2.27.1 it's:
```
if [[ $(uname -m) == 'arm64' ]]; then

    if test -f "/opt/homebrew/bin/gpg"; then
        /opt/homebrew/bin/gpg --batch --no-tty "$@"
    else
        /usr/local/bin/gpg --batch --no-tty "$@"
    fi
else
    /usr/local/bin/gpg --batch --no-tty "$@"
fi
```

**Comment by milanhorvatovic** [comment]
It works. 

Is it really necessary to check the arm64 architecture? I guess it should work with only test for Homebrew or standard fallback? 🤔

**Comment by DanPristupov** [comment]
Well, it turned out that it's not 👍. However when today I received a message that GPG suite doesn't work I had to fix that asap :)
