### ISSUE TITLE
Resolve conflict view is collapsed in Fork for Mac

### ISSUE THREAD

**Issue by vpoznyak** [ForkIssues/Tracker#1846]
**Fork Version** 2.27

**Device** MacBook Pro 16-inch, 2019 2,6 GHz 6-Core Intel Core i7, AMD Radeon Pro 5300M 4 GB, macOS 13.2.1 (22D68)

**What have happened**
When I drag the Fork window with merge conflict resolve view open from built in display to an external one, resolve conflict view collapsed like on a screenshot and I can not make it normal again.

**What I have tried**

1. Quit and restart Fork
2. Update Fork to latest version
3. Restart my MacBook
4. Move Fork app to the Bin and install it from scratch

Any ideas, how can that be fixed?

![Resolve_conflicts_area_collapsed_Fork](https://user-images.githubusercontent.com/118180235/227146829-3edba7fe-6e00-4574-a3be-1d18cfa6987a.png)

**Comment by DanPristupov** [comment]
Try to reset Fork settings by running the following in terminal: `defaults delete com.DanPristupov.Fork`

**Comment by vpoznyak** [comment]
@DanPristupov , that worked! Thank you!
