### ISSUE TITLE
Submodules revert to HEAD when master was the last selection 

### ISSUE THREAD

**Issue by tgunr** [ForkIssues/Tracker#1849]
Annoying behavior, when I have a submodule open and master is selected then closing the submodule and going back to the parent I expect the submodule to stay on master. Instead when I open the submodule again it is sitting at HEAD and I have to switch it back to master again.

**Comment by DanPristupov** [comment]
I don't see a proposal.
That's how git works.

**Comment by chucker** [comment]
>That's how git works.

With submodules, maybe, but not with regular repos.

Once you make a change on a submodule, fork (or git) will cause that change to be _detached_. So you have to manually reattach the commit to be on top of master again.

I don't know if this is regular git behavior, but it sure isn't what I would expect…
