### ISSUE TITLE
The key token is wrong. How to change it

### ISSUE THREAD

**Issue by Hei8-w** [ForkIssues/Tracker#1853]
error ：
In a case you entered incorrect password, please
update it in Keychain Access application.

I saw the previous post, but I don't know where to find Keychain Access, I can't find it and change it

**Comment by Hei8-w** [comment]
I entered the wrong password when I pushed the branch, but I clicked Save. How can I change the password that I should enter when I pushed the branch

**Comment by Hei8-w** [comment]
I hope the author can reply to me after seeing this. Thank you

**Comment by DanPristupov** [comment]
`Keychain Access` is an application on Mac which stores sensitive information.
Open Applciations -> Utilities -> Keychain Access.

**Comment by Hei8-w** [comment]
ooo,i find it. thank you
