### ISSUE TITLE
History dialog can no longer be exited by pressing Esc

### ISSUE THREAD

**Issue by DanielSWolf** [ForkIssues/Tracker#1855]
I frequently use the History dialog to quickly find out about recent changes to a file. I'm used to exiting out of that dialog by pressing the Escape key. In Fork 2.27, this no longer works. I'd greatly appreciate it if this could be added again.

**Comment by DanPristupov** [comment]
Thank you for reporting that. We'll fix the behavior in 2.28 which will be released today evening (yes, we deploy on fridays ;))

**Comment by DanPristupov** [comment]
We just released Fork 2.28

**Comment by DanielSWolf** [comment]
Works like a charm! Thank you, that makes my workflow much smoother again!
