### ISSUE TITLE
Commit list, file tree and changes dialogue box don't display any infos

### ISSUE THREAD

**Issue by ismaelguerrib** [ForkIssues/Tracker#1856]
On all my project connected to github, instead of having a commit list, change and file tree dialogue box displaying infos like the screenshot 1, I have an obscur error like in the screenshot 2. 

The error displaying in the box is : 

 error git UnknownError( output:"",error:"fatal:unrecognized argument= --diff-merges=1/n")

screenshot 1
<img width="1160" alt="Capture d’écran 2023-03-30 à 09 47 46" src="https://user-images.githubusercontent.com/50170060/228770253-25d2e4ae-6c94-4566-9ec3-679e0cb4174e.png">

screenshot 2
<img width="1165" alt="Capture d’écran 2023-03-30 à 09 42 33" src="https://user-images.githubusercontent.com/50170060/228770250-b2198308-af9c-452d-8b46-367506afe5dc.png">

**Comment by DanPristupov** [comment]
You switched Fork to an old git instance. Upgrade git or switch Fork to the internal git.

**Comment by ismaelguerrib** [comment]
Thanks I upgrade my git and switch Fork to the internal ( instead of Apple ) and it's works perfectly !
