### ISSUE TITLE
Turn off smart quotes in custom command text field

### ISSUE THREAD

**Issue by hesselmonk** [ForkIssues/Tracker#1857]
macOS 13.0, Fork version 2.27

When editing or pasting custom git commands in the custom shell commands interface the app/system substitutions are applied. I don't think these substitutions should be applied by default, similar to the terminal app. Quotation characters in particular have caught me out a couple of times:

(contrived example)
```
git restore "*.json"
```

Gets changed to this broken command by default
```
git restore “*.json”
```

I expect code fields not to apply text subtitution.

Possibly related to https://github.com/fork-dev/Tracker/issues/634

**Comment by DanPristupov** [comment]
Thank you for the bug report

**Comment by DanPristupov** [comment]
We fixed that in Fork 2.28. Please check for updates
