### ISSUE TITLE
[Feature request] Add "Filter" option to branch dropdown in "All commits" view

### ISSUE THREAD

**Issue by serhiipalash** [ForkIssues/Tracker#1858]
Usually when you want to review today's team work you fetch repository and go to "All commits" view, checking all most recently updated branches (1st screenshot), then you pick the branch you are interested and filter view on it, then start reviewing work through commits one by one. The problem hear is that to filter by branch you have to focus another area (sidebar) and spend time on finding branch there, because "Filter" button is only available in sidebar nearby branch name. Please add a "Filter" option to dropdown (2nd screenshot), so we can do things faster :)
 
<img width="1680" alt="Screenshot 2023-04-04 at 1 16 17 PM" src="https://user-images.githubusercontent.com/14208343/229761590-601e3264-ecaa-479b-8650-1989ac4a7bdc.png">

<img width="1680" alt="Screenshot 2023-04-04 at 1 17 17 PM" src="https://user-images.githubusercontent.com/14208343/229761843-e95d23e5-75a4-4292-a4bc-1ee99f29e46c.png">

**Comment by DanPristupov** [comment]
> Please add a "Filter" option to dropdown (2nd screenshot), so we can do things faster :)

<img width="624" alt="Screenshot 2023-04-04 at 12 33 01" src="https://user-images.githubusercontent.com/618115/229765615-50bddbd2-5f44-4776-bd37-9650aab98b5e.png">

**Comment by serhiipalash** [comment]
Aha! Sorry, it was hard to find because you are used to have only options in dropdown, but not buttons. Thank you @DanPristupov !
