### ISSUE TITLE
Dialog box buttons should be verbs

### ISSUE THREAD

**Issue by ZevEisenberg** [ForkIssues/Tracker#186]
Here's an example: when you go to delete a stash, the dialog box that says "Are you sure you want to delete the stash stash@{1}?" has the buttons No and **Yes**. These should be Cancel and **Delete**. I don't know if there are other such buttons in the app, but it may be worth auditing for them, since verby buttons tend to make the UI more clear.

**Comment by ZevEisenberg** [comment]
Oh, and the Escape key should activate the nondestructive button, i.e. the Cancel button.

**Comment by DanPristupov** [comment]
I reviewed all the windows and updated the ones which did not have verb buttons. There were about 3 such dialogs.

The yesterday update (1.0.62) includes these changes.

Thank you for creating this issue.

**Comment by infotexture** [comment]
If this is done & released w/ 1.0.62, looks like the issue can be closed.

@DanPristupov If you tag issues with [milestones](https://help.github.com/articles/about-milestones/), it makes it much easier to see which issues were fixed in each release.
