### ISSUE TITLE
Shared Custom Commands reordering on save

### ISSUE THREAD

**Issue by JohannesDeml** [ForkIssues/Tracker#1864]
I have the problem when doing any changes to the shared custom commands, the json file `.fork/custom-commands.json`reorders its values randomly resulting in a diff that makes it hard to see the actual changes. This is annoying and makes it harder to collaborate on changes, since the reordering creates merge conflicts more easily.
 Repro:
1. Go to Repository -> Settings for This Repository
2. Go to Custom Commands
3. Add at least three shared commands with some data in them
4. commit your changes and go back to the custom commands window
5. Edit the name of any command
6. Take a look at the changes to the file
7. Notice that there is not a single diff with just the name changed, but a whole lot of diffs with resorted data

Expected Behavior:
The sorting of the json data should be stable and only the lines that are really changed show up in the diff

**Comment by DanPristupov** [comment]
Yes, I know that :(.
The problem is that json dictionary is unsorted by the definition: 

https://www.rfc-editor.org/rfc/rfc8259.html :
> An object is an **unordered** collection of zero or more name/value
> pairs, where a name is a string and a value is a string, number,
> boolean, null, object, or array.

I didn't think about that when we added the ability to commit and share custom commands

**Comment by DanPristupov** [comment]
I found that we can have a custom json formatter and sort properties by keys. That is not perfect a perfect solution, but it's much better than random order every time.

Thank you very much for bringing attention to that.

**Comment by JohannesDeml** [comment]
Awesome, that already sounds like a huge improvement! Thanks a lot for taking a closer look into it 🥳

**Comment by DanPristupov** [comment]
We just released Fork 2.28 with the fix.

**Comment by JohannesDeml** [comment]
Yey, awesome, that was fast! I checked the new version and can approve that the order is now stable for us 🥳 

I found a different issue with the version number changing between 0 and 1 (depending on if I change the first entry in the list, or  a different one). What is the version actually for? Should it count up instead of switching between 0 and 1?
![Screenshot 2023-04-17 at 09 16 04](https://user-images.githubusercontent.com/4518980/232412494-9a0d3534-4faa-467f-8777-945b270b1125.png)

Do you want me to create a new issue for that, or should we keep discussing here?

**Comment by DanPristupov** [comment]
Ouch :(. That's a typo. It must start with `1`. I'm building a fix.

**Comment by DanPristupov** [comment]
Can you try `2.28.1`, please? https://cdn.fork.dev/mac/Fork-2.28.1.dmg

**Comment by JohannesDeml** [comment]
Yep, now it is stable at version 1 :)

**Comment by JohannesDeml** [comment]
Thanks for tackling this issue so quickly and in general pouring so much love in this great software!
