### ISSUE TITLE
[Feature Request] Add "Hide Branch" option to branch right-click menu

### ISSUE THREAD

**Issue by cade-rea** [ForkIssues/Tracker#1865]
It would be handy to be able to right click on a branch in the All Commits view and hide it, instead of having to find it in the branches sidebar.

**Comment by DanPristupov** [comment]
<img width="554" alt="Screenshot 2023-04-13 at 20 23 02" src="https://user-images.githubusercontent.com/618115/231849551-c4043997-3810-4f86-8ab6-f3a39a4a693b.png">

**Comment by cade-rea** [comment]
Oh thank you so much! I did not even notice that little row of icons!
