### ISSUE TITLE
Add Additional Copy Options

### ISSUE THREAD

**Issue by robmathers** [ForkIssues/Tracker#1867]
Having more flexibility to copy different information from one or more commits would be a helpful addition.

Currently the copy command will copy the commit hash for one or more selected commits. I think that's a reasonable starting point, but ideally, I'd love to see options to copy most metadata:
- Commit title
- Commit message
- Short hash
- Author
- Date

I could see these living under an additional "Copy as" submenu in the Edit and context menus, and behaving the same as existing copy for multiple selected commits.

For additional customization, perhaps a setting to allow changing the default copy behaviour to one of the above.

Thanks

**Comment by robmathers** [comment]
Looks like a subset of this has been requested in #1554 as well.

**Comment by DanPristupov** [comment]
No, I don't want to add 5 different 'Copy' items. Currently there are 'Copy SHA' (Cmd+C) and 'Copy commit info' (Alt+Cmd+C) which are sufficient for majority of cases.

**Comment by robmathers** [comment]
> No, I don't want to add 5 different 'Copy' items. Currently there are 'Copy SHA' (Cmd+C) and 'Copy commit info' (Alt+Cmd+C) which are sufficient for majority of cases.

Ah thanks, I had no idea Copy Commit Info was there. Might be helpful if it were either a separate menu item, or the Edit > Copy menu was active when commits were selected.

**Comment by DanPristupov** [comment]
> Might be helpful if it were either a separate menu item, or the Edit > Copy menu was active when commits were selected.

It works the same as in MacOS when you press the Option key

**Comment by DanPristupov** [comment]
https://user-images.githubusercontent.com/618115/233118840-ed3209f1-dd89-47cf-be2c-b232fdb45971.mov


https://user-images.githubusercontent.com/618115/233118989-e353b7f1-8ac4-4007-a8c4-5aa306d8c1f7.mov
