### ISSUE TITLE
cmd+b to change branch not working anymore

### ISSUE THREAD

**Issue by mskri** [ForkIssues/Tracker#1869]
Previously cmd+b would open a list of branches and allowed changing branch that way.  On version 2.28 this seems to not be working anymore. I'm only getting a "beep" sound.

**Comment by bbukraLTX** [comment]
https://github.com/fork-dev/Tracker/issues/1814

**Comment by DanPristupov** [comment]
In 2.29 we made `⌘B` open 'Quick Launch -> Checkout Branch' view.
