### ISSUE TITLE
Feature: Branch button on toolbar

### ISSUE THREAD

**Issue by FahimF** [ForkIssues/Tracker#187]
Having a branch button on the toolbar would make things much easier for those of us who create branches all the time.

**Comment by DanPristupov** [comment]
The new branch action is available is accessible on (+) button press in left-bottom corner.

![2018-01-08 at 09 24](https://user-images.githubusercontent.com/618115/34663186-d5696ed8-f455-11e7-9d93-4d2148a2f249.png)
