### ISSUE TITLE
[Feature Request] Add a checkbox confirming user will lose all uncommitted change when aborting conflicting merge

### ISSUE THREAD

**Issue by nguyentrong101094** [ForkIssues/Tracker#1870]
Currently, when I abort a merge with conflict using the "Abort" button that appears at the top of Fork, all my local changes are lost. It's necessary to require users to confirm they will lose all uncommitted changes. 

I've lost so many works because of this, just writing "All changes since the last commit will be deleted." is unclear to me, I thought it will revert the local repo to the state before the merge, which means it will keep uncommitted changes, but it does not.

In the command line equivalent, using 'git merge --abort' would throw an error and I would understand that it requires me to stash all uncommitted changes.

I'm using Fork for Mac.

**Comment by DanPristupov** [comment]
Abort does show the confirmation dialog: 
<img width="271" alt="Screenshot 2023-06-07 at 14 34 23" src="https://github.com/fork-dev/Tracker/assets/618115/5146e0e7-e8c3-4fd9-9f66-88707eff0a98">

> In the command line equivalent, using `git merge --abort` would throw an error and I would understand that it requires me to stash all uncommitted changes.

No, it will not.
