### ISSUE TITLE
Cannot push with Personal Access Token

### ISSUE THREAD

**Issue by cdhanna** [ForkIssues/Tracker#1873]
Hi, 
I've been using Fork with personal access tokens for years now, and I love it!
The other day, my access token expired, and Fork kindly told me so, and I went to update my token. However, I made a mistake, and I forgot to include "workflow" permissions. 
A few days later (today), I went to push a change that included a workflow file in Github, and I got this error,
```
Pushing to https://github.com/REDACED/REDACED.git
Enumerating objects: 29, done.
Delta compression using up to 10 threads
Total 15 (delta 12), reused 0 (delta 0), pack-reused 0
POST git-receive-pack (1368 bytes)
To https://github.com/REDACED/REDACED.git
 ! [remote rejected]     feature/REDACED → feature/REDACED (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/workflow.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/REDACED/REDACED.git'
```

I realized that I'd forgot to add the workflow scope, so I
1. when to Fork/Accounts, and removed my account. 
2. Then I added a new account from Github, and selected to use a PAT. I entered in a new PAT that has the correct permissions. I know this.
3. The account connected and the bubble turned green.
4. I went to push again, and got the same error! 
5. I tried pushing a different branch without a workflow file change, and it worked fine.
6. I went to push the original problematic branch, and the error was still there. 

I'm really confused. This all used to work great, but now I'm not sure if Fork is broken, or if Github is having a minor blip of an outage. I checked their status page, but that didn't show anything.

I'm on Version 2.28.1

Thanks for any help.

**Comment by cdhanna** [comment]
I also tried downgrading to Version 2.27, but that didn't help.

**Comment by cdhanna** [comment]
I also tried removing the account again, and signing in with OAuth, but I get the _exact_ same error message as before. I feel like my PAT isn't being cleared out somehow?

**Comment by DanPristupov** [comment]
Interesting. Try to open command line and run:

`curl -I -H 'Authorization: token <token>' https://api.github.com/rate_limit`

We interested in `x-oauth-scopes` parameter:

```
curl -I -H 'Authorization: token <token>' https://api.github.com/rate_limit
HTTP/2 200 
server: GitHub.com
date: Fri, 21 Apr 2023 07:50:13 GMT
...
x-oauth-scopes: read:user, repo, workflow <----
```

**Comment by DanPristupov** [comment]
You can also try to access API to show list of workflows (it must work even if there's none).

https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#list-repository-workflows
```
curl -L \
  -H "Authorization: Bearer <token>"\
  https://api.github.com/repos/OWNER/REPO/actions/workflows
```

**Comment by cdhanna** [comment]
Thanks for your response!
I ran the first one, here are the results...
```sh
chrishanna@Chriss-MacBook-Pro-2 REDACTED % curl -I -H 'Authorization: token REDACTED' https://api.github.com/rate_limit
HTTP/2 200 
server: GitHub.com
date: Fri, 21 Apr 2023 12:42:35 GMT
content-type: application/json; charset=utf-8
content-length: 1195
cache-control: no-cache
x-oauth-scopes: notifications, repo, user, workflow
x-accepted-oauth-scopes: 
github-authentication-token-expiration: 2023-06-19 21:53:05 UTC
x-github-media-type: github.v3; format=json
x-github-api-version-selected: 2022-11-28
x-ratelimit-limit: 5000
x-ratelimit-remaining: 4986
x-ratelimit-reset: 1682084398
x-ratelimit-used: 14
x-ratelimit-resource: core
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
vary: Accept-Encoding, Accept, X-Requested-With
x-github-request-id: C5C1:6AA8:139083:285833:644284BB
```

Yeah, this line is here,
`x-oauth-scopes: notifications, repo, user, workflow`, so that looks good.

---

I also ran the second command, and it indeed returned all my workflows :) There are 17 of them at the moment. The result data is just some straightforward ids and names of the actions though.

**Comment by cdhanna** [comment]
Well, I worked around the issue.
Here is my history from a shell,
```sh
 1011  git credential-osxkeychain erase ↵\nhost=github.com ↵\nprotocol=https ↵\n↵\n
 1012  git credential-osxkeychain erase
 1013  git config --global credential.helper
 1014  git config --global --unset credential.helper
 1015  git config --global credential.helper osxkeychain
 ```

And then I removed my account from Fork, restarted the application..
1. then I tried pushing (expecting it to fail with no auth what so ever), and it failed! (hooray!)
2. then I gave up on PAT, and went through the OAuth flow
3. then I tried to push, and it _worked_. Hoooooray! 

I guess I must have had stale data or something... 
Thanks for your quick response time. I'll check back here periodically to see if you want any more info from my machine.
