### ISSUE TITLE
[Feature Request] Add textbox to search/filter "File Tree"

### ISSUE THREAD

**Issue by justin-sonya** [ForkIssues/Tracker#1874]
OS: Mac
Version: 2.28.1

The "Blame/Timeline" "History" feature is fantastic.
However for deeply nested project, user have to navigate deeply to search for the file and also navigate to and fro to see the history of different files.
Would be great if there is a search/filter textbox where user can type in the filename and Fork will display matching all filename as the user is typing.

**Comment by DanPristupov** [comment]
Use:
```Cmd+P, blame, <filename>```
or
```Cmd+P, history, <filename>```

**Comment by justin-sonya** [comment]
Thanks! Works like a charm
