### ISSUE TITLE
Unable to commit while in an interactive rebase

### ISSUE THREAD

**Issue by DanielSWolf** [ForkIssues/Tracker#1875]
Since the last update I did, I cannot perform commits during an interactive rebase. I can stage files, but the commit-related fields in the lower-right corner are disabled. This forces me to commit via command line instead.

![image](https://user-images.githubusercontent.com/5963162/234216395-8662af5f-5f0f-4c1d-9b51-103e6bf36727.png)

**Comment by DanPristupov** [comment]
The commit subject is empty, so you can't commit.

Or do you want to continue rebase?

**Comment by DanPristupov** [comment]
I just checked, everything works for me.
I think we didn't change the submit button behavior recently, but who knows, I might have forgotten something.

You can try to download older versions: https://cdn.fork.dev/mac/Fork-2.27.1.dmg or https://cdn.fork.dev/mac/Fork-2.26.1.dmg
