### ISSUE TITLE
Ignored files should not be marked as unstaged

### ISSUE THREAD

**Issue by bwl21** [ForkIssues/Tracker#188]
When i put a file to .gitignore, it is still shown as unstaged. I cannot recognize that it is ignored. So I happens that I still stage it. Don't know if it is eventually committed ...

**Comment by DanPristupov** [comment]
Hi,

I just tried to add a new file and ignore it. The file disappeared immediately. May be the file you want to ignore is already tracked (i.e. have been committed)? In this way it's changes will be shown until you delete it.

**Comment by bwl21** [comment]
It could be that the file was already under version control.  In this case Fork should provide a "Stop Tracking" in the context menu and not offer "ignore"
