### ISSUE TITLE
[bug] Latest version vs. Releases on webpage and "check for updates"

### ISSUE THREAD

**Issue by ppuschmann** [ForkIssues/Tracker#1880]
Hi,

out of curiosity I checked the latest version via the "Check for Updates" menu item in the app.

Result:
<img width="262" alt="image" src="https://user-images.githubusercontent.com/3431761/236137870-1b17f6d1-fdad-4fd8-a1b3-da276a18b973.png">
Text:
```
You're up to date!
Fork 2.27.1 is currently the newest
version available.
(You are currently running version 2.28.)
```

Funny enough even the webpage currently does not track the version consistently: 

On the homepage https://cdn.fork.dev/mac/Fork-2.27.dmg vs. https://fork.dev/releasenotes --> 2.28 

This is only a minor issue.

**Comment by DanPristupov** [comment]
> You're up to date!
> Fork 2.27.1 is currently the newest

You switched Fork to the stable update channel.

> On the homepage https://cdn.fork.dev/mac/Fork-2.27.dmg 

The main page has a link to the stable build.

> https://fork.dev/releasenotes --> 2.28

The release notes describes all builds.
