### ISSUE TITLE
Git flow release finishing fails when gpg code signing is enabled in .gitconfig

### ISSUE THREAD

**Issue by MichaelYabko** [ForkIssues/Tracker#1882]
when GPG code signing is enabled in a .git config file it seems I am unable to properly finish a release branch. Here's a screen of my current .gitconfig. Note that I am using 1password as a ssh certificate managment tool, which works well in other code signing situations.

<img width="491" alt="image" src="https://user-images.githubusercontent.com/59970024/236475500-69660ec9-4ad8-4620-af77-8175a1b08e43.png">

Once attempting the release it shows "Finishing Release" but eventually timeout with the following error:

```
Already on 'master'
error: failed to fill whole buffer

fatal: failed to write commit object
Fatal: There were merge conflicts.
```

If I remove code signing in my .gitconfig (by setting gpgsign = false), then I am able to release again.

**Comment by DanPristupov** [comment]
Most likely the problem is in the 1Password tool. Try to check their docs: https://developer.1password.com/docs/ssh/agent/compatibility

**Comment by MichaelYabko** [comment]
The 1password integration works well in other scenarios, such as just doing regular commits to a branch. It only seems to fail during release or hotfix finishing.

**Comment by DanPristupov** [comment]
Then it's git-flow. I think it's deprecated and not supported anymore. I doubt there will be a fix.
https://github.com/petervanderdoes/gitflow-avh

**Comment by MichaelYabko** [comment]
That's unfortunate. Thanks for the quick replies :-)
