### ISSUE TITLE
Context search should include the full commit message, not just the first line

### ISSUE THREAD

**Issue by mikebeaton** [ForkIssues/Tracker#1883]
I was just trying to find a specific commit by searching in Fork for a word I was sure should be mentioned in the commit message. It turns out I was right, but the word was not in the first line of the commit message, but in the subsequent lines (which are only seen after selecting the commit).

I believe search should really include the full commit message, not just the first line - in order to help solve problems just like the one here.

Thanks!

**Comment by DanPristupov** [comment]
Currently the context search is searching in the commit subjects only.
The search on the sidebar searches in the full commit messages.

**Comment by mikebeaton** [comment]
Why are there two?! And why different? :-( If I find a search that searches in what I want to search (the context search does search in the commits) then I would assume that it is _the_ search that searches in what I want to search, I think.

**Comment by DanPristupov** [comment]
In Fork 2.34 the context search also takes commit description into account.
