### ISSUE TITLE
When using "Open With", I see duplicate and non-functional editor options. 

### ISSUE THREAD

**Issue by CaptainVincent** [ForkIssues/Tracker#1887]
<img width="494" alt="截圖 2023-05-11 上午8 13 16" src="https://github.com/fork-dev/Tracker/assets/12159865/18a350ea-a8a2-48f2-8924-21a54dfa648b">

(I once modified the mac icon of my Visual Studio Code before)

But for some unknown reason, my system now recognizes two versions of the editor, even though I only have one installed. 
And one of the versions is non-functional when clicked on.

Is there a way to clear the cache or perform some other action to force the system to recognize the editor correctly again?
Or can you suggest a way to remove the duplicates and ensure that the correct editor is recognized?

--

I already try uninstall and reinstall from homebrew and delete files/folder under 
`~/Library/Preferences/com.DanPristupov.Fork.plist` and `~/Library/Application Support/com.DanPristupov.Fork`

**Comment by DanPristupov** [comment]
This is the list provided by macOS for that file type. Fork doesn't create those menu items manually.

> I once modified the mac icon of my Visual Studio Code before
> ...
> my system now recognizes two versions of the editor
> ...
> can you suggest a way to remove the duplicates and ensure that the correct editor is recognized?

I would suggest to try first: https://duckduckgo.com/?q=mac+duplicate+app+in+open&t=osx&ia=web

> https://www.hongkiat.com/blog/mac-remove-duplicate-right-click-menus/
> Copy the following coding and paste in `Terminal` application, then press `Enter`:
> `/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user
`

Though, to be honest, I'm not sure what that command does exactly.

**Comment by CaptainVincent** [comment]
Thanks bro ~
I try the below command from [link](https://www.lifewire.com/remove-duplicate-applications-from-finder-open-with-menu-2260889). And it's looking good for me.
```
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user
```

**Comment by CaptainVincent** [comment]
To supplement, I have encountered another issue where mac's Spotlight would repeatedly index my software from my dropbox folder (used backup my older version vscode ). Therefore, in addition to the previous commands, I also need to ignore that specific folder from being reindexed by Spotlight.
