### ISSUE TITLE
Improve diff with regards to whitespace/tabs(?)

### ISSUE THREAD

**Issue by petterikamppuririchie** [ForkIssues/Tracker#189]
I believe whitespace/tabs(?) causes Fork to display diffs wrong. SourceTree has correct looking diffs.

I hope you can see how the Fork diff is extremely difficult to read.

<img width="654" alt="fork" src="https://user-images.githubusercontent.com/7383661/34817563-0e00249a-f6c1-11e7-933e-014597a198a8.png">

And how diff in SourceTree is nice and good.

<img width="638" alt="sourcetree" src="https://user-images.githubusercontent.com/7383661/34817556-09ad0552-f6c1-11e7-9f08-2713bb37ed6e.png">

Here are the file snippets as text files

[orig.txt](https://github.com/ForkIssues/Tracker/files/1621916/orig.txt)
[new.txt](https://github.com/ForkIssues/Tracker/files/1621917/new.txt)

Yes, I use tabs which are 4 spaces wide.

Any way to fix the diffs?

**Comment by DanPristupov** [comment]
It turned out this problem exists in 70% of macOS applications (both 3rd party and native Apple's ones). But the other 30% get it fixed somehow...

**Comment by petterikamppuririchie** [comment]
Just throwing this here: NSTextView's paragraphStyle might be using default `tabStops`, which default to `The default value is an array of 12 left-aligned tabs at 28-point intervals.` That would explain dozen tabs. So just have a tab style with with lots more tab stops?

**Comment by DanPristupov** [comment]
@petterikamppuririchie absolutely right, thank you! The fix gonna be available in the next Fork update (probably today).

**Comment by petterikamppuririchie** [comment]
Oh, this is great! Thank you!

**Comment by DanPristupov** [comment]
Fork 1.0.64 is out.

**Comment by petterikamppuririchie** [comment]
Thank you! Works great!
