### ISSUE TITLE
[Feature Request] Repository lists per workspace

### ISSUE THREAD

**Issue by CodingMarkus** [ForkIssues/Tracker#1895]
Shouldn't the repository lists be bound to the active workspace? If I get the same repositories everywhere (private, work, opensource, etc.), how is the workspace really a workspace? I switch to the private workspace and the first 15 repos I see in the list are work repos. If I remove them while the private workspace is active, I also lose them in the work workspace. So workspaces are only about remembering window states and positions? Couldn't I get the same behavior using different macOS desktops, arranging different Fork windows on each desktop and then switch between the desktops? To me a workspace should be like different instances of Fork running on different computers, as only then this feature adds an additional benefit I cannot get out of the box in macOS anyway.

**Comment by DanPristupov** [comment]
A workspace is just a way to quickly switch between groups of tabs.

> So workspaces are only about remembering window states and positions?

They only remember open tabs.

**Comment by CodingMarkus** [comment]
That's sad, as then I don't see the point of the feature at all. If I just want to remember two sets of open tabs, I can simply create two windows and have one tab set in one window and one stab set in another one and instead of switching workspaces, I can switch windows (by next window shortcut, using Missing Control, placing them on different desktops or screens, etc.) Guess then I won't have any use for that feature at all, as it provides nothing I cannot get way simpler and better by other means.
