### ISSUE TITLE
Git-LFS previews not loaded by default

### ISSUE THREAD

**Issue by ZevEisenberg** [ForkIssues/Tracker#1897]
I use Git-LFS to track snapshot test files in an iOS project. None of the snapshots is particularly large, so I'd like the option to automatically load the preview when viewing an LFS diff. Currently, I have to click two buttons to see the before/after view, and even then, it's not cached, so if I click on another file and come back, I have to load the diffs again. I usually have to use Kaleidoscope to assess these changes, because it automatically loads all LFS resources when diffing.

<img width="1343" alt="image" src="https://github.com/fork-dev/Tracker/assets/464574/93ce7989-240b-43f8-a770-3fe070376de9">

**Comment by saket** [comment]
+1 for this. I use fork when I'm working with screenshot tests to preview updated screenshots. Having to click load each time I switch windows is slightly painful.

**Comment by DanPristupov** [comment]
@saket 
It's not implemented yet because I'm worrying that automatic downloading may use a lot of LFS traffic (which is paid) and be a reason of large bills from GH.

**Comment by saket** [comment]
Can the local copies be loaded automatically? I've noticed that Sublime Merge and a few other git clients are able to do this.

**Comment by DanPristupov** [comment]
Yes, GitLFS caches objects in `.git/lfs` directory.
