### ISSUE TITLE
GitLab Server url incorrectly loaded.

### ISSUE THREAD

**Issue by liamcsmith** [ForkIssues/Tracker#1899]
### Issue Description
I'm having an issue where the URL of a self-hosted GitLab is seemingly not importing correctly into the system. I can successfully add the server and view repositories within the accounts pane, however the URL of the server is now displaying localhost rather than the supplied machine name. Attached are photos showing the accounts pane, that should highlight both the url redefinition (Screenshot 1) and the ability to still access the repositories hosted on the server (Screenshot 2).

### Screenshot 1 - Server profile
<img width="903" alt="Screenshot 2023-05-31 at 19 11 29" src="https://github.com/fork-dev/Tracker/assets/17933578/ac957d62-7448-4536-bef9-5f7dccc8c6b6">

### Screenshot 2 - Repositories visible within the server.
<img width="903" alt="Screenshot 2023-05-31 at 19 11 45" src="https://github.com/fork-dev/Tracker/assets/17933578/2e9e47dc-04e9-4c6c-ac3f-27757f8483a3">

**Comment by DanPristupov** [comment]
This url is the `web_url` value returned by your server: `/api/v4/user`.

https://docs.gitlab.com/ee/api/users.html#for-user
