### ISSUE TITLE
Support GPG Signing of Commits and Tags

### ISSUE THREAD

**Issue by nebhale** [ForkIssues/Tracker#19]
Using the Git command line and the [GPG Tools](https://gpgtools.org) library, signing Git commits and tags becomes very easy (`git config -g commit.gpgsign true`).  However this integration breaks if you try to use Fork to create a commit.

![screen shot 2017-04-28 at 09 57 07](https://cloud.githubusercontent.com/assets/60754/25538853/297ebab2-2bf9-11e7-8887-32dfb754f0a1.png)

Fork should support (and encourage!) the signing of commits and tags.

**Comment by DanPristupov** [comment]
What is your `git config gpg.program` value? This probably doesn't work because you use a relative path there. Try to replace it with an absolute one.

I'm going to add /usr/local to Fork's PATH environment in the next update. Hopefully this will help to solve majority of issues with GPG.

**Comment by nebhale** [comment]
I've had it set for some time to `/usr/local/bin/gpg` (as you'd expect with a Homebrew installation), but when it's not set it shows a different error more indicative of not being able to find the binary:

![screen shot 2017-04-30 at 2 50 14 pm](https://cloud.githubusercontent.com/assets/60754/25568302/88fdb35a-2db4-11e7-824a-fbc7e7193dc1.png)

They both share the `failed to sign` and `failed to write` lines, but without a set path, you see the `No such file or directory` (as expected).

**Comment by DanPristupov** [comment]
Did you update the gpg configs too?
Here's is a small tutorial: https://gist.github.com/danieleggert/b029d44d4a54b328c0bac65d46ba4c65

**Comment by nebhale** [comment]
Just missing the `no-tty` apparently.  I guess then, instead of "support" (which clearly already exists), maybe repurposing this issue into "suggest configuration to user then signing fails"?  I can open another issue if you'd like to have a clean history for that story.

**Comment by DanPristupov** [comment]
@nebhale I agree with everything. I opened a separate issue: https://github.com/ForkIssues/Tracker/issues/20

Closing this one.
