### ISSUE TITLE
Feature request: allow to change code color

### ISSUE THREAD

**Issue by dangh** [ForkIssues/Tracker#191]
The "not so dark" gray color is a bit harsh for my eye. It would be great if I can change it to a darker color.

In my screenshot the color is `#676767`, I would love it to be `#222222`
<img width="332" alt="screen shot 2018-01-17 at 10 55 43 am" src="https://user-images.githubusercontent.com/1020347/35023320-12052ab4-fb75-11e7-9957-a87b71036d5d.png">

**Comment by DanPristupov** [comment]
Fork has two themes and implementing an ability to change colors will end up as a huge change. Unfortunately right now I don't have time for this.

However I agree that current text color is too light and I gonna make it darker in the next release.

**Comment by DanPristupov** [comment]
Let's keep it open, otherwise I can forget about it ;).

**Comment by DanPristupov** [comment]
I made the text color darker in 1.0.63.
