### ISSUE TITLE
Request for clarification: Analytics

### ISSUE THREAD

**Issue by Idane** [ForkIssues/Tracker#1910]
Hi,

Does Fork use any type of analytics for anonymized usage/crash data?

**Comment by DanPristupov** [comment]
At the beginning we used Fabric to count the active users, but about 4 years ago we removed it. Now Fork doesn't send any telemetry or analytics and we don't know how many people use it.

We also removed Google Analytics from the website.

We use AppCenter as a crash handler. The analytics module is explicitly disabled (we only use 'Crashes'):

On Mac:
```
        AppCenter.start(withAppSecret: Const.appcenterSecret, services: [Crashes.self])
```

On Windows:
```
       AppCenter.Start(Const.AppcenterSecret, typeof(Crashes));
```

**Comment by Idane** [comment]
Thanks!
