### ISSUE TITLE
Reset File to > State before commit... results in strange error.

### ISSUE THREAD

**Issue by grigorye** [ForkIssues/Tracker#1912]
Fork: 2.29.2

I'm not sure about providing steps to reproduce because it fails every time, in any example/repo that I tried so far.

Update: while it fails in any repo on one of my machines, it does not fail on another machine. So, it looks like there's something related to global Git/machine config on that problematic machine.

Basically, an attempt to revert a file that was modified (just in case, not created) in some commit from the contextual menu command, results in something like this:

<img width="854" alt="Screenshot 2023-06-13 at 17 05 08" src="https://github.com/fork-dev/Tracker/assets/803905/8779ea4d-7929-48ab-ab96-9afa4a90435e">

Just in case, I encounter this issue only in Fork. Similar workflow in e.g. SmartGit works fine. Also, I did not encounter anything else suspicious working with Git on daily basisis, neither in Fork, Git CLI or SmartGit.

I also checked Git instance used by Fork - while they were initially different (problematic machine used Fork-bundled 23.7.5, the other machine used Apple-bundled 29.3.2), setting them both to Fork-supplied 23.7.5 did not make any difference (it still fails on problematic machine, and does not on another).

**Comment by DanPristupov** [comment]
This is a bug in Fork.

**Comment by DanPristupov** [comment]
The problem must be fixed in Fork 2.30

**Comment by grigorye** [comment]
OK, I can confirm that it's indeed fixed in 2.30. Thanks!
