### ISSUE TITLE
Kaleidoscope 4 seems not supported as external diff tool

### ISSUE THREAD

**Issue by masonmark** [ForkIssues/Tracker#1914]
Just set up a new Mac, and after installing the latest Fork (2.29.2) and the latest Kaleidoscope (Version 4.0.3 (3824)) and using its Integrations view to install `ksdiff` I nevertheless cannot select Kaleidoscope as my Merge Tool or External Diff Tool in Fork.

In the menus in the Integration pane of Fork's settings window, there are Kaleidoscope2 and Kaleidoscope3 menu items, but they are disabled.

Perhaps it needs an update for Kaleidoscope 4?

**Comment by DanPristupov** [comment]
Yes, thank you for reporting that.

**Comment by DanPristupov** [comment]
Could you check if the following build works properly? https://cdn.fork.dev/prerelease/Fork-2.39.3.dmg

**Comment by masonmark** [comment]
> Could you check if the following build works properly? https://cdn.fork.dev/prerelease/Fork-2.39.3.dmg

👍 Yes, seems to work fine with Kaleidoscope 4! Thanks.

**Comment by timkelty** [comment]
Works for me too!
