### ISSUE TITLE
[Bug] Amend commit is incorrectly selected after aborting an Interactive rebase with Edit 

### ISSUE THREAD

**Issue by gentique** [ForkIssues/Tracker#1917]
Fork Version 2.29.2

Interactively rebase and select edit on a commit
<img width="145" alt="Screenshot 2023-06-16 at 12 18 52 AM" src="https://github.com/fork-dev/Tracker/assets/15278390/46885cb1-af8f-48fb-8c74-3ca8f75718e2">

Abort the rebase
<img width="280" alt="Screenshot 2023-06-16 at 12 19 11 AM" src="https://github.com/fork-dev/Tracker/assets/15278390/1e9a883a-0829-46ca-84ff-f90b079761ca">

Amend option is selected incorrectly
<img width="744" alt="Screenshot 2023-06-16 at 12 19 20 AM" src="https://github.com/fork-dev/Tracker/assets/15278390/373ec04a-6213-4d2e-a2ee-351bb4e8c71e">

**Comment by DanPristupov** [comment]
I can't reproduce that. The `Amend` button becomes enabled only when you start IR.

**Comment by gentique** [comment]
> I can't reproduce that. The `Amend` button becomes enabled only when you start IR.

(If IR = Interactive Rebase)
That is what I am doing in the described steps, starting an interactive rebase where you are doing an `Edit` on a commit, then aborting the rebase.

**Comment by DanPristupov** [comment]
Is `Amend` unchecked before you start IR (interactive rebase) window?

**Comment by gentique** [comment]
I've attached a screen recording showcasing my steps:

https://github.com/fork-dev/Tracker/assets/15278390/bc36986c-2864-4053-8c86-76ff16162775

**Comment by DanPristupov** [comment]
I see, thanks.

**Comment by DanPristupov** [comment]
We fixed the problem in Fork 2.30

**Comment by gentique** [comment]
Amazing work Dan!
