### ISSUE TITLE
Feature: git revert

### ISSUE THREAD

**Issue by wsxyeah** [ForkIssues/Tracker#192]
Add git revert action

**Comment by DanPristupov** [comment]
Hi
![2018-01-17 at 14 05](https://user-images.githubusercontent.com/618115/35045041-d508edbc-fb92-11e7-81b6-4e9a0d3b61b8.png)

**Comment by DanPristupov** [comment]
Hi.
![2018-01-17 at 14 05](https://user-images.githubusercontent.com/618115/35045041-d508edbc-fb92-11e7-81b6-4e9a0d3b61b8.png)

**Comment by wsxyeah** [comment]
@DanPristupov Thank you.
