### ISSUE TITLE
Not all Github repositories are shown

### ISSUE THREAD

**Issue by Psygnomi** [ForkIssues/Tracker#1920]
When showing the list of repos during a Clone etc, not all the repos available to my GitHub account are shown; specifically from one particular organisation. All the repos for this org are shown in the repo list on GitHub.com itself, and I have full admin access to the org and repos, but they just don't appear within the app.

**Comment by DanPristupov** [comment]
Ensure that Fork has access to that organization: https://github.com/settings/connections/applications/166b00df5e7ea4f78d4b

**Comment by Psygnomi** [comment]
Wow - quick response! Thanks! I'll remember to look in there in future.
