### ISSUE TITLE
How to show very early commits in All commits list?

### ISSUE THREAD

**Issue by kaishiqi** [ForkIssues/Tracker#1922]
My working warehouse is a warehouse that has been used for a long time and is used very frequently. I forgot which version started. I found that all submission interfaces can only display submission information within one year, and I cannot see earlier submission content. How to refresh it? What about earlier commits?
Or what button can be provided to allow all submission interfaces to additionally load earlier submission information in batches?

**Comment by DanPristupov** [comment]
Currently the limit is 50,000 commits.

You can increase the limit using the following terminal command: `defaults write com.DanPristupov.fork maxCommitCount 150000`

**Comment by kaishiqi** [comment]
> Currently the limit is 50,000 commits.
> 
> You can increase the limit using the following terminal command: `defaults write com.DanPristupov.fork maxCommitCount 150000`

If it is in the window system, how to modify it? @DominikPalo

**Comment by DanPristupov** [comment]
Edit `MaxCommitCount` field in the `%localappdata%\fork\settings.json` file.

**Comment by kaishiqi** [comment]
Looking forward to adding this option to the settings panel soon @DanPristupov
