### ISSUE TITLE
Improve "HEAD" Styling in commit view

### ISSUE THREAD

**Issue by hipstersmoothie** [ForkIssues/Tracker#1924]
I find it really hard to scan the commit view and see where my HEAD is at. The checkmark + bold isn't really enough for me to discern the HEAD from any other commit.

Could you add an option to have a higher contrast / easier to see HEAD? Ideally I'd like the whole row to have a light grey background or something so I could see it while quickly scrolling

**Comment by DanPristupov** [comment]
You can press `Cmd+0` to jump to HEAD.
