### ISSUE TITLE
[Feature Request] Stash without discarding changes

### ISSUE THREAD

**Issue by wojciech-kulik** [ForkIssues/Tracker#1927]
I often use stash to make a temporary backup of my changes. It would be great to be able to stash changes without resetting files.

Currently, I have to stash changes and then immediately apply stash again.

**Comment by DanPristupov** [comment]
<img width="335" alt="Screenshot 2023-07-09 at 21 37 30" src="https://github.com/fork-dev/Tracker/assets/618115/03f5e7c1-5965-479c-b5a1-5acfe00dcc95">

**Comment by wojciech-kulik** [comment]
I've just accidentally discovered this feature at the same moment! 
Fork is great 🔥!
