### ISSUE TITLE
[Bug] Git Error - Unexpected error occurred while performing the git request

### ISSUE THREAD

**Issue by ronnyremesnik** [ForkIssues/Tracker#1928]
![Screenshot 2023-07-09 at 23 54 16](https://github.com/fork-dev/Tracker/assets/50165476/a7fe1ad5-22f4-4760-85f8-fa70edd1e782)

No error message...

in fork.log I see this : 

⚠️[GitRequest.swift:145] > Git error 'stash apply refs/stash@{0}':

❌[ErrorWindowController.swift:25] > gitUnknownError(output: "", error: "")
◽️[Stopwatch.swift:42] >  2045 GetRepositoryStatusGitCommand
🔷[RefreshRepositoryCommand.swift:87] > RefreshRepository canceled
◽️[Stopwatch.swift:42] >  2725 GetRepositoryStatusGitCommand

I just saved stash and tried to apply that again...that's it... I'm on last version 2.30
Mac ventura, 13.2.1

When I restart the app - I can apply the stash....happens only when save and apply immediately..

Thanks in advance...

**Comment by DanPristupov** [comment]
Just to ensure I understand how to reproduce that. Should I simply save and apply stash?
Can you reproduce this in any repository or only in a particular one?

**Comment by chobotoid** [comment]
Hello, I've repeatedly met a bug which seems to be the same as this. In my case it happens whenever I go to a repo -> "Local changes" -> stage -> commit x file/s. Whenever I try to commit, it shows the error, is there somehow a mistake in my settings or is it really a bug? thx in advance

<img width="1507" alt="fork-screenshot-bug" src="https://github.com/fork-dev/Tracker/assets/72510054/4dda8ac3-7907-49c8-ae58-20cc07eafd2d">

**Comment by DanPristupov** [comment]
@chobotoid the error says `gpg failed to sign the data`. Check Repository -> Settings for this repository -> GPG.
