### ISSUE TITLE
Github repository not found - private team repository

### ISSUE THREAD

**Issue by alamboley** [ForkIssues/Tracker#1929]
I setup Fork with Bitbucket AOuth at first, then some other Github AOuth accounts.

I clone via https, all my repositories. For some reasons, on my github accounts (in Fork for cloning) I can't see private repositories from team. Using https, I've a repository not found.

Then installing GitHub Desktop, I'd no issue cloning via this app. Still can't success via Fork.

Using Fork Version 2.29.2

**Comment by DanPristupov** [comment]
Check GitHub OAuth settings: https://github.com/settings/connections/applications/166b00df5e7ea4f78d4b

**Comment by alamboley** [comment]
Oh indeed, I've to ask for access. I see for GitHub Desktop everything is already authorized, I suppose this is because it's their own client?

**Comment by DanPristupov** [comment]
> I suppose this is because it's their own client?

Yes. They make it nicer for themselves and worse for the rest.
