### ISSUE TITLE
Allow resizing the commit message area

### ISSUE THREAD

**Issue by olivergierke** [ForkIssues/Tracker#193]
It would be cool if one could resize the commit message area just like one can the staged files area. Especially if you're crafting more verbose commit messages, being cramped into that narrow little text field feels a bit claustrophobic 😉.

Thanks for the great work!

**Comment by DanPristupov** [comment]
Hi Oliver!

Yes, I agree. Actually I always wanted to do this like you described but never had enough free time :).

I'll try to implement this soon. Hopefully won't get stuck because of the expand/collapse animation.

**Comment by DanPristupov** [comment]
I did not implement resizing yet, but I reworked the commit message area in 1.0.65.
![2018-03-16 at 09 28](https://user-images.githubusercontent.com/618115/37510705-5b3cbe36-28fc-11e8-881c-b2d21a79a0ae.png)

**Comment by nebhale** [comment]
This is hijacking the resizing issue a bit, but this seems like the appropriate place to respond to the commit message area changes.


I need to use it a bit more, but my initial impression of this change isn't great.  The biggest issue is that if you try to write a commit message by habit, it's not clear what the result actually is.

![screen shot 2018-03-16 at 6 48 39 am](https://user-images.githubusercontent.com/60754/37524112-17c1cf54-28e6-11e8-914e-36ec2d5996be.png)

This feels to me like an example of the UI being helpful, but it breaking the expectations of people who've spent time working at the command line.

In the spirit of constructive criticism, maybe what's need is a much more definitive separation between subject and body.  Not necessarily two boxes, but boundary lines, automatic trimming of the top empty space, or something along that path.

**Comment by DanPristupov** [comment]
@nebhale  Thank you very much for the feedback. I think current issue is a good place to discuss the topic.

> The biggest issue is that if you try to write a commit message by habit, it's not clear what the result actually is.

It was the same before. I received feedback that people are not sure how many space will be placed between. It was a bit more clear though.

My personal feeling about new layout is the following: I like where it goes, but the feature is not final yet. Let's try to improve it and if it won't work out fine, I'll revert my changes.

So, the current problems:
> It's not obvious how many empty lines will be placed between the subject and body.

We can add a more clear placeholder which will clarify this. Changing `Description` to `Commit description` makes it explicit, doesn't it?

> need ... much more definitive separation 

I can increase the empty space between Subject and Description and also add thin horizontal line.

I'll make a mockup on the weekend...

**Comment by DanPristupov** [comment]
OK, here's how it could look like:
![2018-03-16 at 15 52](https://user-images.githubusercontent.com/618115/37527321-0dd9d328-2932-11e8-8cd1-f3995620db10.png)

![2018-03-16 at 15 53](https://user-images.githubusercontent.com/618115/37527357-2908beac-2932-11e8-9d85-086490c96ff1.png)

**Comment by nebhale** [comment]
That would be much more obvious.

The keyboard interaction would be interesting to think about as well.  Typing a commit message in a standard text editor would be `<SUMMARY TEXT>+ENTER+ENTER+<DESCRIPTION TEXT>`.  I'm guessing the way the commit box works today is that the same keystrokes result in an extra newline in commit messages.  It might be helpful to eat one of those newlines (effectively have it represented by the hairline) as part of the interaction.  This way muscle memory doesn't result in a poorly formatted message.

One thing that keeps nagging at me though is the thought that this might be prescribing too much in the UI.  The summary + empty line + description is a convention (recommended certainly) but not a requirement.  If you chose to buck this convention, say one big paragraph of text with multiple lines but no empty line, how would you even do that with this UI?

**Comment by DanPristupov** [comment]
I made another change related to the description field. It's being resized automatically relying on the inner content up to the half of the screen. I also reduced jumping and blinking on focus.

<img width="547" alt="2018-07-16 at 14 47" src="https://user-images.githubusercontent.com/618115/42759399-23c299b0-8907-11e8-8b4d-51f41ab83a58.png">

<img width="400" alt="2018-07-16 at 14 47" src="https://user-images.githubusercontent.com/618115/42759387-14d14f78-8907-11e8-8d4d-334100db3e30.gif">

I'm pretty happy with the result and I think we can close the issue once the feature comes out publicly.
You can try it already in this build: http://git-fork.com/update/files/Fork-1.0.68.5.dmg

**Comment by szeiger** [comment]
I don't think the current design really solves the problem. I doubt I'm the only person who really hates to type text into such an automatically growing field at the bottom of the screen. I always want some empty space below the end of the content. This is something that editors like EMACS have done for decades.

The lack of empty space also makes the page guide completely useless. Due to the low contrast it is already very hard to if you have a decent amount of empty spacebut it is impossible to see behind the text without any empty space.

**Comment by gusutabopb** [comment]
Any chance this can be revisited? 
The commit message area is one of the few elements in the UI that can't be resized. The sidebar can be resized, the unstaged pane can be resized, the staged pane can be resized, the diff pane can be resized. But for some reason the commit message area can't (it's . 

As the OP, I find it pretty claustrophobic and often go back to Sourcetree just because of this.

**Comment by claraguoguo** [comment]
Same here. The commit message text field is really too small... Would be nice if we can make the UI resize-able!
