### ISSUE TITLE
OAuth authorization name

### ISSUE THREAD

**Issue by kieranparsons** [ForkIssues/Tracker#1930]
Our Enterprise users get really nervous about authorizing Fork in OAuth since the authorization is in the name "Dan" (and "DanPristupov"). They have no idea that this is the Fork developer and often ask if it's OK. Suggest a company name be used instead.

<img width="411" alt="Screenshot 2023-05-08 162419" src="https://github.com/fork-dev/Tracker/assets/54148619/2f60d99e-26d5-45cb-8c81-0c5f5350708c">

**Comment by DanPristupov** [comment]
I don't have a company.

P.S. There is a similar issue https://github.com/fork-dev/Tracker/issues/1163

**Comment by DanPristupov** [comment]
GitHub uses the account name of the application author. I'll think what I can do. I don't want to change my account name, but may be I can transfer the OAuth app to another account.

**Comment by DanPristupov** [comment]
We created a new GitHub OAuth entry owned by the `fork-dev` and starting the `2.31` update the GitHub authentication dialog will say to `Authorize Fork-dev`.
