### ISSUE TITLE
Consolidate Commit and Changes tabs in All Commits view

### ISSUE THREAD

**Issue by olivergierke** [ForkIssues/Tracker#194]
The separation of the Commit and Changes tabs in the All Commits view feels a bit arbitrary. I'd love to see a canonical view of the changes including the files' diffs but the complete commit message at the same time.

If the Changes tab exposed the complete commit message, that would already do the trick for me, but then the Commit tab is pretty much offering the same information but missing the diff. So it might be a chance to consolidate into one view?

**Comment by DanPristupov** [comment]
While I agree that the difference between Commit and Changes tabs is a bit unclear, I'm not sure how to improve that.

"Commit Overview" could be a more precise name for the "Commit" tab, but it's too long.

Generally I have two usage patterns:
- if I need to focus on reading commit description, I use the Commit tab.
- When I need to find a commit with particular changes and investigate them, I use the Changes tab.

I don't like neither ST or GitX approaches:
- in first case, because of short message and limited file list areas.
- in second case because of difficulty to check list of files when you go through list of commits

Merging two tabs into one will limit at least one of them.

> If the Changes tab exposed the complete commit message, that would already do the trick for me

Is there an example? The header is quite small to show commit description. Not sure how that is possible. I can show commit description as a tooltip, but this not what you want probably. Or you mean the GitX approach?

**Comment by Turbo87** [comment]
@DanPristupov FWIW I think the commit info can be dropped completely from the "Changes" tab. That would give us a bit more space to actually view the changes, while the commit metadata can be reviewed on the other tab or in the commit list above the panel.

**Comment by andion** [comment]
Hi @DanPristupov. Nice work on fork! I'm really loving it.

Like @olivergierke I also miss a more compact way of looking at commits. I also come from many years of GitX, but I miss that compactness from command line too where I use: [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy)

The commit tab could add the commit info a-la GitX without being verbose. I'll add a screenshot for those that did not know GitX.

![cica-web__extensiones-web__y_cica-web__branch__extensiones-web__y_fork_-_a_fast_and_friendly_git_client_for_mac](https://user-images.githubusercontent.com/20295/37024559-7bdab6e6-2129-11e8-9b13-f6e4761527d7.png)

Anyway thank you very much for fork and keep up the good work.

**Comment by DanPristupov** [comment]
@andion thank you for the mockup. I like it.

This can be tricky from performance point of view. All the file context should probably be lazy... May be I should implement a draft, hidden by default and add an option to enable it. Than we can start to gradually improve it. If it work out OK, I'll enable it for everybody. Otherwise, it'll stay hidden for majority of users.

**Comment by darekrusin** [comment]
I'm all for compactness and I do think Fork wastes a lot of space that could used better. I'm not sure though about including the change list in one view, the way GitX does.

This could work well when you're dealing with small commits, but what if, speaking from a game development scenario, the list includes lots of changes in:

* large, machine generated, text-based data assets (like Unity scenes),
* bitmaps (png, jpg)
* binary assets (audio),
* and finally code, all mixed together?

Then you have two problems:

1. Getting to the files I'm interested in (code) could take a **lot** of scrolling.
2. It will be hard to achieve any reasonable performance.

**Comment by DanPristupov** [comment]
OK, I checked the upvotes and here's what we will have in 1.0.70. This is basically what @olivergierke and @andion have proposed.

![ezgif com-video-to-gif-13](https://user-images.githubusercontent.com/618115/45432360-f3c06280-b6a9-11e8-8c8c-6a9e2b016c2b.gif)

**Comment by andion** [comment]
@DanPristupov I love it! Thank you for the good work!

**Comment by DanPristupov** [comment]
1.0.70 just out! Please try the new feature and give me some feedback.

**Comment by andion** [comment]
The new feature its great, thanks!

Minor bug I found. Sometimes the file icon/name appear overlapped like this:

![m2m_-_15_10_2018_-_k](https://user-images.githubusercontent.com/20295/46948518-a6eff300-d07e-11e8-8178-db5aee35fc64.png)

> macOs Hight Sierra & Fork 1.0.71.1

**Comment by DanPristupov** [comment]
@andion I've never seen such problem. How often does it occur? What happens when you click on such an item?

**Comment by ivanlomba** [comment]
I have the same problem. Occurs almost always, but only with the second file in the `expand all` view

BTW: Congrats, I love the new view!

**Comment by andion** [comment]
Like @ivanlomba it's almost always, and on the second file.

If you click on the item in the front it goes to that file. If you manage to click on the item on the back... it makes a third item appear exactly as the one that was on the top before.

![image](https://user-images.githubusercontent.com/20295/46955737-f42a8f80-d093-11e8-8771-815d868d2111.png)

But, if you click on that one, it makes consecutive file paths appear, and it collapses their respective expanded views... ending in something like this:

![image](https://user-images.githubusercontent.com/20295/46955852-2a680f00-d094-11e8-977b-c65c33e6fec9.png)

If it's not clear enough and it helps I can try to make a small vid.

**Comment by leandrofavarin** [comment]
I'm late to the game but I love this feature. Thank you so much for adding it.

One behaviour I have is to basically see the commits from my remote team when I wake up, and navigating with the up & down arrow keys makes it easy to see each commit. But it's currently a 2-step process where, for each commit that I focus on, I have to use the mouse to tap _Expand all_. Another alternative I have is to go to the _Changes_ tab and look it from there, as it stays as the selected tab as I move through the commits. But the downside of this alternative is that it doesn't show all files changed at once -- like the _Commit_ tab -- but one file at a time.

I was wondering if someone else has this routine as well.

**Comment by DanPristupov** [comment]
@leandrofavarin thank you for describing your use case.

There's https://github.com/ForkIssues/Tracker/issues/420 which is pretty much what you asked. I'm going to implement that soon.

Not sure about showing multiple files at once in the Changes tab though. Technically it's possible, but I don't want to make the UI too complicated.

**Comment by leandrofavarin** [comment]
@DanPristupov thank you 🙏  I apologize not looking at the Issues tab thoroughly to find a similar feedback. I believe #420 should suffice for my use case and avoid bringing complexity to the UI.
