### ISSUE TITLE
Clicking tag in the sidebar no longer jumps to the commit

### ISSUE THREAD

**Issue by AlekSi** [ForkIssues/Tracker#1943]
Fork 2.31, macOS 13.5. Clicking the tag in the sidebar used to make the other view jump to the referenced commit. That no longer works. It still works for branches, though. Please see the video:

https://github.com/fork-dev/Tracker/assets/11512/67d40173-1166-428d-acec-f5671b0e1d47

**Comment by macness-pavelh** [comment]
Same on Sonoma Seed

**Comment by DanPristupov** [comment]
Thank you very much for the bug report. I've just released the 2.31.2 hotfix:

<img width="623" alt="Screenshot 2023-07-31 at 15 19 42" src="https://github.com/fork-dev/Tracker/assets/618115/390147f3-e851-49c5-8573-ab2a218c8e0c">

**Comment by AlekSi** [comment]
Yep, it works, thank you!
