### ISSUE TITLE
Worktrees show up as "missing" in repo list

### ISSUE THREAD

**Issue by mtschoen-unity** [ForkIssues/Tracker#1945]
The latest update supports worktrees. Hooray! 🎉 

However, I think there's a bug (or at least weird behavior) where they now show up with the little yellow "missing" tag in the repo list. For example, you can see in this image I have a repo with a couple of worktrees, which were previously added in an earlier version:
<img width="183" alt="Screenshot 2023-07-31 at 2 19 17 PM" src="https://github.com/fork-dev/Tracker/assets/19391263/60c49e26-3dcc-44c4-9002-a50889f92f74">

If I remove a worktree and try to add it back, nothing happens. I assume the intended behavior is that you can't add worktrees to the project list? With my current situation, I can still double-click one of these "missing" repos and it will open Fork to that worktree. I'd still like to have this behavior, since otherwise it's _another_ double-click to first open the main repo, then go to worktrees and open the worktree I want. Maybe the repo list could nest worktrees under their owners?

**Comment by DanPristupov** [comment]
> I think there's a bug (or at least weird behavior) where they now show up with the little yellow "missing" tag in the repo list.

This is a bug. The icon must be constant.

> I assume the intended behavior is that you can't add worktrees to the project list?

No, currently there's no GUI for adding a worktree.

> Maybe the repo list could nest worktrees under their `owners`?

Yes, but I want to ensure that I understand the problem right. There's always just one `owner` which is the main primary repo. Then there are multiple worktrees which just reference to the .git dir of the primary repo. Am I right or I'm missing something?

**Comment by mtschoen-unity** [comment]
> Yes, but I want to ensure that I understand the problem right. There's always just one owner which is the main primary repo. Then there are multiple worktrees which just reference to the .git dir of the primary repo. Am I right or I'm missing something?

Yeah that's correct. I was just saying it would be nice to keep the ability to have the worktree be visible in the list of repos. That way you can get right to it, instead of having to first open the owner repo.

**Comment by mtschoen-unity** [comment]
I think this is fixed? I don't see anything wrong with my worktrees anymore 👍
