### ISSUE TITLE
GitHub Notifications

### ISSUE THREAD

**Issue by CT4TuEI3** [ForkIssues/Tracker#1948]
I can't figure out where I can turn on this feature?
<img width="1119" alt="image" src="https://github.com/fork-dev/Tracker/assets/31804144/d0687809-7675-41ad-82d1-a4bd268a9391">

**Comment by DanPristupov** [comment]
Fork -> Accounts -> GItHub

**Comment by CT4TuEI3** [comment]
> Fork -> Accounts -> GItHub

Thanks 🙏

**Comment by ospfranco** [comment]
I was also wondering how to enable this. Looked all over the place. It would be nice to have some extra documentation.
