### ISSUE TITLE
Add keyboard shortcut to enable Amend in Commit view

### ISSUE THREAD

**Issue by olivergierke** [ForkIssues/Tracker#195]
It would be cool to be able to use a keyboard shortcut (`CMD+SHIFT+A`) to stay with the conventions already used?) to switch to the amend mode in the commits view.

**Comment by DanPristupov** [comment]
Yes, `Cmd+Shift+A` fits into current convention. I will add this shortcut in the next release.

I probably won't use it myself because I prefer making potentially harmful operations with mouse to avoid mistakes, but many people should find it useful.

**Comment by DanPristupov** [comment]
@ngyikp I already implemented what Oliver asked. But I gonna check if there's any reason for Amend checkbox to not be focusable.
