### ISSUE TITLE
Opening submodule creates tab in the wrong window

### ISSUE THREAD

**Issue by snej** [ForkIssues/Tracker#1954]
Choosing “Open (name)…” from the context menu on a submodule in the sidebar opens the tab in a different window than the active one.

## Steps:

1. Have multiple windows open
2. In the active window, open the Submodules outline
3. Right-click a submodule
4. Choose “Open"

## Expected Result:

Submodule opens in a new tab in the same window

## Actual Result

Another open window activates and the submodule tab is added to it

## Configuration

macOS 13.4.1
Fork Version 2.32 (but this has been happening for months)

**Comment by YesThatAllen** [comment]
I came here to report this issue, then in testing versions 2.43.1 and 2.44, it seems that double clicking submodules opens them in the parent tab.

**Comment by YesThatAllen** [comment]
EDIT: I was mistaken.. one of my repos (`client-mac`) would reliably open submodules in the same tab, other repos would not. 

All my repos are checked out from github using the `ssh` protocol

the submodules in `client-mac` are also checked out using `ssh`
submodules in other repos are checked out via `https`. I don't know if that's related.

**Comment by YesThatAllen** [comment]
I just updated to 2.46.1 and tested this release note:

> Fixed: Opening submodule creates tab in the wrong window

It seems to be working for me.. thank you!

**Comment by EnixCoda** [comment]
I found this issue from changelog. Fix for this issue seems also fixed another issue on macOS that fork window opened from terminal would appear in another desktop where there is already a fork window open. Good job!
