### ISSUE TITLE
Optional preselection of the "force push" option when pushing to remote

### ISSUE THREAD

**Issue by kielgillard** [ForkIssues/Tracker#1958]
I like to rebase and force push every now and then. I suspect Fork could optimise the number of interactions required for me to do this. What follows is a suggested solution the problem.

I think a simple keyboard shortcut could help.

If I hold the Option key with this menu visible: 
<img width="340" alt="image" src="https://github.com/fork-dev/Tracker/assets/567949/c364ffe5-e7e7-4709-ad42-15baf1c2e847">

Can:
* the title change to "Force push 'x' to 'y'..." and
* and the "Force push" option automatically checked for subsequent dialog:
<img width="564" alt="image" src="https://github.com/fork-dev/Tracker/assets/567949/c4236882-1abf-4672-95f1-7f34c991251e">

I did notice that holding the Option key with the "Repository" menu open alternates "Push..." with "Quick Push". Perhaps this is not the best solution that reduces the number of interactions required to force push to a branch.

**Comment by DanPristupov** [comment]
> I like to rebase and force push every now and then. I suspect Fork could optimise the number of interactions required for me to do this.

Use Sync (it's available on the branch dropdown on the toolbar).

**Comment by kielgillard** [comment]
<img width="334" alt="image" src="https://github.com/fork-dev/Tracker/assets/567949/fd0d7a4c-b0fc-47cf-af09-ab6612a6a4f1">

It doesn't seem like it?

**Comment by DanPristupov** [comment]
I checked the source code. The default branch must be named `develop`, `main` or `master`. Otherwise the default branch can be configured in `Repository -> Settings for this repository -> General`.

**Comment by kielgillard** [comment]
Ah, that's it. Thanks! I'll give this feature a whirl. Thank you again!

**Comment by DanPristupov** [comment]
I think it's pretty useful. Nowadays my own workflow is mostly: Sync, Sync, Sync then Finish (merge into main). The important thing is that 'sync' is safe and excludes a user mistake. The user won't force-push a wrong thing by mistake.
