### ISSUE TITLE
I don't see content of the stash or commit

### ISSUE THREAD

**Issue by tomas-vahala-unbiased-co-uk** [ForkIssues/Tracker#1959]
Hi, after updating Fork, I need help finding the content of the commit in the Fork, and I have this message there.

`gitUnknownError(output:"", error: "fatal: unknown value for --diff-merges: 1\n")`

<img width="1077" alt="image" src="https://github.com/fork-dev/Tracker/assets/112933905/de702833-70a9-4b62-a3e1-097a72366a0f">

**Comment by DanPristupov** [comment]
Hi,

You switched Fork to a very old git instance. Update git or switch Fork back to the internal git.

**Comment by tomas-vahala-unbiased-co-uk** [comment]
@DanPristupov Thank you the git version was problem
