### ISSUE TITLE
Searching for a commit hash from the changes screen doesn't do anything

### ISSUE THREAD

**Issue by cantocass** [ForkIssues/Tracker#196]
Given a known commit hash, and when searching from the changes view, (I had no changes) the search box populates with the commit, but doesn't take me to that commit in the git log. I have a branch checked out, so it should be able to use that as a default branch.

**Comment by DanPristupov** [comment]
Hi. Thank you for creating this issue. Switching to the git log absolutely makes sense. I gonna fix this soon.

P.S. Actually now the search itself is very limited and must be re-imagined. Hopefully will do that soon.
