### ISSUE TITLE
[Feature Request] Implement Settings Export

### ISSUE THREAD

**Issue by rotorgames** [ForkIssues/Tracker#1962]
I wonder if I have ability to export all Fork settings into the .json file (or smth else) to keep a backup of all my settings and commands in the safe place just in case if my laptop is broken. 

I found only an option to save commands locally into the repository but this is not what I'm looking for. 

Cheers.

**Comment by DanPristupov** [comment]
Custom commands and the list of repos are stored in `~/Library/Application Support/com.DanPristupov.Fork`

**Comment by rotorgames** [comment]
@DanPristupov Thank you for the quick response. How's it safe using this db file as a backup? What if you make major changes in the file in over time and I'll not be able to use it? Or a structure of the file is not changing at all?

**Comment by DanPristupov** [comment]
You only need `*.json` files, the db file is obsolete.

There is migration from the old config formats, but it was never tested in manual mode (i.e. when you have a settings you need to import).


Anyway, there's not much settings in Fork, excepting custom commands, so I think saving `custom-commands.json` should be enough.

**Comment by SublimePeace** [comment]
For Windows users, you can find `custom-commands.json` and `settings.json` in `%LOCALAPPDATA%\Fork`. Those are the two files that contain all commands and settings. After you install Fork on your new machine, launch it once, then close it. Afterwards, navigate to that local appdata directory, and replace the two .json files with your backed up ones.
