### ISSUE TITLE
GitHub.com URL cut off in "Git" view

### ISSUE THREAD

**Issue by dewey** [ForkIssues/Tracker#1965]
Using Version 2.33 on macOS 13.5.2 (22G91) has a small cosmetic issue where the GitHub URL is cut off.

<img width="662" alt="Screenshot 2023-09-07 at 23 51 54 png@2x" src="https://github.com/fork-dev/Tracker/assets/790262/ad42ef7f-ca49-41c0-82f3-4260aee73eac">

**Comment by DanPristupov** [comment]
Fixed in 2.34
