### ISSUE TITLE
Custom Command: Could not read from temporary file path

### ISSUE THREAD

**Issue by chances** [ForkIssues/Tracker#1966]
<img height="350" alt="CLI bug" src="https://github.com/fork-dev/Tracker/assets/635049/8904ccb5-b72a-40de-b9f4-20cc609461cd">

```
Could not read from temporary file path: Error Domain=NSCocoaErrorDomain Code=4 "The file “extism” doesn’t exist." UserInfo={NSFilePath=/Users/chancesnow/GitHub/extism, NSUnderlyingError=0x600000cbe610 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

`/Users/chancesnow/GitHub/extism` is a folder that _does_ indeed exist in this case.

## Reproduction

1. Install Nova editor and [its CLI](https://help.panic.com/nova/cli-tool/).
2. Add a Custom Command:
    <img width="1055" alt="nova cli" src="https://github.com/fork-dev/Tracker/assets/635049/48c6f873-7e65-4fa1-8d8b-a9922f02cf50">
3. Use the command:
    <img width="250" alt="nova cli" src="https://github.com/fork-dev/Tracker/assets/635049/6a0d4276-cad4-436b-8252-c7fd8b6b2ce9">

**Comment by DanPristupov** [comment]
> The file "extism" doesn't exist.

Looks like the application you run expect some other apps (extism?) available in ENV.

Try to run fork from CLI using `open -a Fork` command

**Comment by chances** [comment]
> > The file "extism" doesn't exist.
> 
> Looks like the application you run expect some other apps (extism?) available in ENV.

No, `/Users/chancesnow/GitHub/extism` is a _folder_ that does indeed exist in this case.

> Try to run fork from CLI using `open -a Fork` command

Doing this has no effect on the issue.

**Comment by DanPristupov** [comment]
OK, then I don't know what could be wrong :(. This is an error returned by the tool you run, try to ask Panic about it.
