### ISSUE TITLE
Double click on commit doesn't lead to checkout

### ISSUE THREAD

**Issue by homm** [ForkIssues/Tracker#1969]
The problem is only happens with commits market as origin branches.

<img width="573" alt="Screenshot 2023-09-15 at 13 28 11" src="https://github.com/fork-dev/Tracker/assets/128982/f439ba7f-8b85-40b2-980e-9391a7eaaa34">

Don't know was it working before.

**Comment by DanPristupov** [comment]
You can't checkout a remote branch, so Fork makes checkout of the corresponding local branch.

If you want to checkout a commit and go to detached HEAD, you must do that explicitly: Right click -> Checkout commit.

**Comment by homm** [comment]
> If you want to checkout a commit and go to detached HEAD

Yes, this is what I want. For me this commit is the same as other nearest commits, which I can checkout in detached HEAD. Don't know how clear such behavior could be for most users.

**Comment by DanPristupov** [comment]
> Don't know how clear such behavior could be for most users.

It's more important not to switch to detached HEAD unintentionally.

**Comment by homm** [comment]
I'm ok with this if this is intentional.
