### ISSUE TITLE
Allow expanding the right sidebar on repository list screen

### ISSUE THREAD

**Issue by cdzombak** [ForkIssues/Tracker#197]
[low priority feature request]

On the following screen, the right sidebar cannot be expanded any further. This is unfortunate, since there's a lot of content in the sidebar, but the middle of the screen doesn't need to be very wide.

<img width="1792" alt="screen shot 2018-01-23 at 12 04 55" src="https://user-images.githubusercontent.com/102904/35290122-3e589c1a-0037-11e8-96d8-60539f139e24.png">

**Comment by DanPristupov** [comment]
Hi.

Great adea! It looks so great, that I'll make the sidebar twice wider by default in next release.
![2018-01-28 at 14 35](https://user-images.githubusercontent.com/618115/35482636-7f587ca8-0438-11e8-9cff-9f0f1aa0bed6.png)

**Comment by cdzombak** [comment]
Thanks, @DanPristupov. That'll look a lot better, I think.
