### ISSUE TITLE
Honour git config tagopt no-tags

### ISSUE THREAD

**Issue by neilmorton** [ForkIssues/Tracker#1973]
I have a repo where as well as origin, I have both an upstream remote, and another forked remote. I do this so I can cherry pick specific commits for my repo.

However, if I add a tag to my repo, and then the forked remote adds the same tag, I get a clobber error.

I have set the git config for the remote to `git config remote.<remote-name>.tagopt --no-tags` which I assumed should stop the tags being fetched, but this does not seem to be honoured by Fork.

- Is there / could there be a way to either honour the git config?

- Also, is there / could there be a way to manage this on a per remote basis from the UI?

Thanks.

**Comment by neilmorton** [comment]
Disable Settings > General > Always include tags into fetch (disabled by default).

Thanks for the heads up @DanPristupov .

**Comment by DanPristupov** [comment]
You are welcome👍
