### ISSUE TITLE
[BUG] CMD+Enter shortcut doesn't work

### ISSUE THREAD

**Issue by gentique** [ForkIssues/Tracker#1975]
Previously you were able to stage a file by using the CMD+Enter shortcut, now it gives a Beep (error) sound. 

Fork Version 2.34.1

**Comment by DanPristupov** [comment]
Most likely your system catches the event. Try to reboot.

**Comment by gentique** [comment]
> Most likely your system catches the event. Try to reboot.

That actually did it. Thank you!
