### ISSUE TITLE
Why are there two Fork "Authorized OAuth Apps" on GitHub?

### ISSUE THREAD

**Issue by jond01** [ForkIssues/Tracker#1978]
When I look at my Settings -> Integrations -> Applications -> [Authorized OAuth Apps](https://github.com/settings/applications)
I see this:

![image](https://github.com/fork-dev/Tracker/assets/36337649/7bbe7b0d-fb67-4121-a33e-a5b68366026b)

With links:
1. https://github.com/settings/connections/applications/debde513eaa447b74d51
2. https://github.com/settings/connections/applications/166b00df5e7ea4f78d4b

The second one ("Owned by [DanPristupov](https://github.com/DanPristupov)") is the one same as linked here:
https://github.com/fork-dev/Docs/blob/master/faq.md#permission-denied-when-accessing-repos-in-my-organization-on-github

It is not clear why both are needed, maybe a rename may help.

**Comment by DanPristupov** [comment]
The one owned by DanPristupov account is deprecated and not used for new logins.

You can find more details here: https://github.com/fork-dev/Tracker/issues/1930#issuecomment-1632584149

**Comment by jond01** [comment]
Ok thanks, I've just created https://github.com/fork-dev/Docs/pull/7 to avoid future confusion.

**Comment by DanPristupov** [comment]
Thank you :) 👍
