### ISSUE TITLE
configure separate tokens for each repo?

### ISSUE THREAD

**Issue by ssuess** [ForkIssues/Tracker#1980]
Recently there was a change made to our gitlab server that requires a PAT for each repo. I can create and use these in the terminal no problem, but the fork app does not seem to allow me to use more than one, so every time I set one on one repo that works, as soon as I switch to another repo (where I had set it up before) it is broken. I must be missing something in the interface, how can I use a token PER REPO? (https, not ssh btw)

**Comment by DanPristupov** [comment]
Right click on a remote on the sidebar -> `Edit`. Then select the account
