### ISSUE TITLE
Edit remote URL: Should also allow editing pushUrl

### ISSUE THREAD

**Issue by jnehlmeier** [ForkIssues/Tracker#1981]
I have a git repository which config contains 
```
[remote "origin"]
        url = https://domain/git-project
        pushurl = https://domain/git-project
        fetch = +refs/heads/*:refs/remotes/origin/*
```
I wanted to update the remote URL in the Fork UI and after doing so only `url` was changed and I still pushed to the old url. I wasn't aware that the config of that project had `url` and `pushurl` configured, so it was a bit unfortunate that I could not see this in Fork. 

Maybe the "edit remote" UI should show both urls if available so they can be both edited.

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/Tracker/issues?q=pushUrl

**Comment by markst** [comment]
Odd that this and #1700 were closed when this issue is still apparent. 

----

When editing origin using Fork.app only my 'Fetch URL' is updated. Meaning I can't push to my origin without manually editing using git.

```shell
git remote show origin
```
```
git remote show origin
* remote origin
  Fetch URL: git@bitbucket.org:xxx/xxx-app.git
  Push  URL: https://xxx@bitbucket.org/xxx/xxx-app.git
```

The resolution is to explicitly pass `--push` param when setting remote origin:
```shell
git remote set-url --push origin git@bitbucket.org:xxx/xxx-app.git
```

**Comment by DanPristupov** [comment]
@markst https://github.com/fork-dev/TrackerWin/issues/505#issuecomment-544137786

Run `git remote set-url --delete --push origin push.git`

**Comment by markst** [comment]
I'm well aware we can use the git command to resolve. I think the issue is the Fork.app UX could visually display both origins if there are multiple.

**Comment by DanPristupov** [comment]
@markst

> I think the issue is the Fork.app UX could visually display both origins if there are multiple.

Why? What is the point of having fetch and push urls different?

**Comment by jnehlmeier** [comment]
@DanPristupov If you have a pull-request based workflow without direct commit permission in the main repository, you can have a fetch url pointing to the main repo and a push url pointing to your personal fork. That way you can pull latest changes from main repo and push your features/fixes to the fork and finally do a pull request from fork to main.
 
Of course you can also solve that by having two remotes but handling two remotes requires more work (e.g. always selecting which remote you want to use for a given action).

**Comment by DanPristupov** [comment]
1. I didn't know about this. It seems like a hack which contradicts the docs:

https://git-scm.com/docs/git-remote#Documentation/git-remote.txt-emset-urlem says:

> Note that the push URL and the fetch URL, even though they can be set differently, must still refer to the same place. What you pushed to the push URL should be what you would see if you immediately fetched from the fetch URL.


2. Returning to the original problem. Even if someone uses this (assuming they know what they are doing), GUI should use `git remote set-url <remote> <url>` request and not erase the manual configuration.

**Comment by jnehlmeier** [comment]
A read-only mirror can also benefit from it. E.g. you pull from Github and push to Bitbucket via a single remote by simply doing git pull && git push.

Or if you own the Github repo and you work on it regularly you might want to update a mirror right away. Then you might have two (or more) pushUrls in a single remote and a single git push will update Githu + all read-only mirrors.

**Comment by jnehlmeier** [comment]
> I didn't know about this. It seems like a hack which contradicts the docs:

I think the recommendation in the docs is for repos that you really work with (read + write). But for mirring or push-only new branches it is totally fine.

> Returning to the original problem. Even if someone uses this (assuming they know what they are doing), GUI should use git remote set-url <remote> <url> request and not erase the manual configuration

Yes. Or the UI allows managing all URLs. Most of the time it is probably just two URLs by mistake, e.g. one SSH and the other HTTPS. But especially then it is irritating if you update the URL in the UI and it did not work 100% because you never knew you had different URLs configured.

**Comment by jnehlmeier** [comment]
Here is what [the commit message](https://github.com/git/git/commit/203462347fce0eab563fe77640648a7e8ae64d3b) says:

_This is useful, for example, in order to do passwordless fetches
(remote update) over the git transport but pushes over ssh_

So GIT+SSH URLs is what they had in mind.
