### ISSUE TITLE
[Feature Request] macOS - Show current workspace title somewhere in the app  

### ISSUE THREAD

**Issue by frameworker2019** [ForkIssues/Tracker#1984]
Switching workspaces leads me sometimes to be confusing because the title of the workspace doesn't appear anywhere in the menubar or the app window.
In case of doubt you have to click again on the workspace icon to see what a workspace you are currently working in.

Would be nice to display the current workspace title somewhere.

1. maybe above the repository name in the middle of the main window? (toolbar height constraint problem, I know)
2. or in the left up corner of. the sidebar above the current repository name? (seems there's a enough room for)

**Comment by DanPristupov** [comment]
> In case of doubt you have to click again on the workspace icon to see what a workspace you are currently working in.

The workspace item title itself has the active workspace name. You probably missed it:

<img width="191" alt="Screenshot 2023-10-13 at 10 56 08" src="https://github.com/fork-dev/Tracker/assets/618115/e8f6b509-d625-452c-9d04-0878588c6030">

**Comment by frameworker2019** [comment]
Okay, I was still on 2.27.1 which does not display the label below the icon.
After updating to the most current version it does, perfect!
