### ISSUE TITLE
[Feature Request] support copy commit message, now only support commit hash

### ISSUE THREAD

**Issue by chenjiangui** [ForkIssues/Tracker#1987]
![图片](https://github.com/fork-dev/Tracker/assets/18565140/0aaaac6f-80c1-4667-9932-c81c827f5fbe)

**Comment by DanPristupov** [comment]
Press Alt/Option.

**Comment by chenjiangui** [comment]
> Press Alt/Option.

This method is really obscure 😂😂😂

**Comment by DanPristupov** [comment]
It is not. Alternative actions on Alt key press is a common practice on macOS. Try to open menu in any application and press Alt.

https://github.com/fork-dev/Tracker/assets/618115/83bea64c-8e52-4e04-8136-b9760638e456
