### ISSUE TITLE
Private github and gitlab instances

### ISSUE THREAD

**Issue by barrylustig** [ForkIssues/Tracker#199]
It would be great if Fork supported private github or gitlab instances, not just github.com and gitlab.com.

**Comment by iancorbitt** [comment]
I will second this feature request.

**Comment by bdgeyter** [comment]
+1

**Comment by anragab** [comment]
Duplicates #134

**Comment by barrylustig** [comment]
anragab pointed out that this is a duplicate of #134, which it is.  I'm going to close this out.
