### ISSUE TITLE
Double click to open/close group in sidebar

### ISSUE THREAD

**Issue by overheadhunter** [ForkIssues/Tracker#1991]
Hi, I have a very simple feature request:

Instead of aiming on the small `>` and `⌄` icons in the side bar, I'd like to toggle the open/close state of groups such as branches, remotes, stashes, etc by double-clicking on the parent entry.

Keep up the great work!

**Comment by DanPristupov** [comment]
Fork uses the default macOS approach (and controls). Sidebar items do not expand/collapse in Finder, XCode, Notes, Calendar, Mail, or in Fork.
