### ISSUE TITLE
Will not scroll to single search value

### ISSUE THREAD

**Issue by tir38** [ForkIssues/Tracker#1993]
1. pick a SHA in your history
2. scroll to some random place in the git history
3. CMD + F
4. start to type in that SHA
5. After a few characters ( i.e there should only be one search result left) see that scrolling stops

If you manually scroll to the right point in history, the search will have correctly highlights that row. (i.e. search is finding result, just not scrolling there)

**Comment by DanPristupov** [comment]
Hi,

1. Did it work before or it's a new problem? Can you reproduce the problem in Fork 2.33 (https://cdn.fork.dev/mac/Fork-2.33.dmg)?
2. Does the log file have any errors? The log is located at `~/Library/Logs/Fork.log`

**Comment by tir38** [comment]
I just tested on 2.38. It's working fine now.
