### ISSUE TITLE
[BUG] Cannot commit just selected lines

### ISSUE THREAD

**Issue by touho** [ForkIssues/Tracker#1995]
When you have multiple changes lines in a single file and you have staged only some changed lines, commit button will include also unstaged changes in that file.

This bug didn't happen ~couple of weeks ago and Fork has auto updated meanwhile.

Fork Version: 2.33
Reproduced 3 out of 3 times.

**Comment by DanPristupov** [comment]
Check hooks you installed ~couple of weeks ago.

**Comment by TouhoHH** [comment]
What a fantastical advise!

Found a comment in our project's hooks:
`# Format every changed file & re-add to commit.`

Thanks for help! Sorry for suspecting the best git gui. 😄
