### ISSUE TITLE
Diff flags

### ISSUE THREAD

**Issue by RamenNoodlez** [ForkIssues/Tracker#2]
It would be great to be able to specify options in the preferences for flags in git diff.

Specifically, I'd love to be able to ignore whitespace.

**Comment by DanPristupov** [comment]
Hi,

So, the following are missing:
- Show Entire File
- Ignore Whitespaces

Is there anything I forgot about?

**Comment by DanPristupov** [comment]
Done in Fork 1.0.44

**Comment by RamenNoodlez** [comment]
Beautiful.

Thank you.
