### ISSUE TITLE
Make GPG signing more user friendly

### ISSUE THREAD

**Issue by DanPristupov** [ForkIssues/Tracker#20]
This issue has been inspired by @nebhale at #19.

Currently GPG integration can be installed using the following tutorial: https://gist.github.com/danieleggert/b029d44d4a54b328c0bac65d46ba4c65

We can make a similar tutorial for Fork and put it to a FAQ section on the website. However it would be much better if Fork simplify the GPG integration instead of explaining how to configure it properly.

Current issues:
- path to the gpg app must be absolute, which can confuse a lot of people
- user must run gpg from terminal, find the key and register it in `git config` manually.
- user must edit `gpg-agent.conf` to define `pinentry-program`
- user must edit `gpg.conf` to define `no-tty`

Improvements:
1. Create in Fork a Repository Settings view which will replace manual editing of `git config`. The view will contain:
- path to gpg program app (the view should try to guess the location automatically by checking the most common paths).
- combobox with a list of system signing keys (it would be great to be able to generate a key right there in the future).

2. Replace the `pinentry-program` (this is an app which asks for the password) with Fork. In this way user won't need to edit `~/.gnupg/gpg-agent.conf` manually.

3. Get rid of requirement to define `no-tty` option in `gpg.conf`.

Ideally gpg installation should as simple as:
- install gpg app
- generate key
- open repository settings, enable gpg checkbox and select the key (if there is more than one).

Any comments are appreciated.

**Comment by nebhale** [comment]
This definitely hits all the issues that I ran into.  I think it's a great solution to the issue of ensuring that GPG signing is configured in such a way that it's transparently usable in Fork.

**Comment by DanPristupov** [comment]
Finally I'm working on making GPG commit signing more friendly.

Here's how the repository settings view looks when there's no GPG installed in the system:
![2017-10-20 at 11 04](https://user-images.githubusercontent.com/618115/31813419-89638450-b586-11e7-8854-8bfe97d8c36c.gif)

When GPG in installed, the only thing user must do is to select a key. Here's how the configuration looks like:
![2017-10-20 at 11 08](https://user-images.githubusercontent.com/618115/31813544-1751706a-b587-11e7-9ddf-ff55de587bd6.gif)

**Comment by nebhale** [comment]
This looks great.  Re-reading the original requirements and seeing #2.  That would only be for Fork usage, right?  Specifically, I wouldn't expect it to hijack command line usage.

**Comment by DanPristupov** [comment]
@nebhale yes, exactly. I spent much time implementing that recently.
Fork is not going to change any system-wide settings/config.

The (2) and (3) points of the original proposal aren't correct (I didn't know exactly how GpgTools works when I wrote it).

**Comment by nebhale** [comment]
Awesome.  I figured you'd be doing the right thing there, just wanted to confirm.

**Comment by androvers** [comment]
@DanPristupov I don't know if this is related, but fork can't seem to find my GPG Keys?
<img width="484" alt="no-gpg" src="https://user-images.githubusercontent.com/23300542/31938744-515fc80c-b8b0-11e7-934b-d65df9c842f1.png">
I do have the GPG Suite installed.

**Comment by nebhale** [comment]
I see the same as @androvers.

**Comment by DanPristupov** [comment]
@androvers @nebhale guys, could you check if the Fork log file contains any errors and send them to support@git-fork.com please? The log is located at `~/Library/Caches/Fork/fork.log`

Thank you in advance.
