### ISSUE TITLE
Can't finish Git Flow feature

### ISSUE THREAD

**Issue by artemnovichkov** [ForkIssues/Tracker#200]
Sometimes I have an error with this text when I try to finish features (I use gitflow, BTW):
`Fatal: Cold not read Username for "https://github.com", No such device or address`

**Comment by DanPristupov** [comment]
Does this happen with any repositories or only with a particular one? Are your HTTPS credentials configured properly (i.e. can you fetch/push)?

**Comment by Najdan** [comment]
@DanPristupov I'm having the same issue. I can use push and fetch on repo but can't finish feature using git-flow.

**Comment by artemnovichkov** [comment]
Hi, @DanPristupov! I tried only with one project. Everything works fine in SourceTree.

**Comment by DanPristupov** [comment]
I could not reproduce that issue myself. However I made some related improvements in 1.0.64. Could you try it now please?

**Comment by artemnovichkov** [comment]
Thank you! I'll try it

**Comment by Najdan** [comment]
@DanPristupov I have updated Fork to the latest version and I'm still getting the same error.

Note that git-flow I'm using has prefix for feature branches something like this: `feature/NOT-` then goes number of branch. Maybe that's causing issue.

**Comment by FinesseRus** [comment]
Where can I find Git Flow in the Fork interface?

**Comment by DanPristupov** [comment]
Sorry, not fixed yet.

**Comment by artemnovichkov** [comment]
Maybe it's related to two-factor authentication...

**Comment by DanPristupov** [comment]
Guys, I updated git-flow to the latest version in 1.0.68 (https://github.com/ForkIssues/Tracker/issues/318). Could you please check whether your issue is fixed or not?

**Comment by Najdan** [comment]
@DanPristupov sorry for the late response. It seems like it is fixed for me. Just finished feature branch using git-flow with no issues.

**Comment by DanPristupov** [comment]
@Najdan sound great!

**Comment by artemnovichkov** [comment]
I have no the issue last weeks.
