### ISSUE TITLE
Commit message missing from commits view

### ISSUE THREAD

**Issue by matheusamazonas** [ForkIssues/Tracker#2001]
The message/title of one of the commits in the commit history ins't being rendered:
<img width="594" alt="Screenshot 2023-11-06 at 11 52 15" src="https://github.com/fork-dev/Tracker/assets/3589041/2fcc4055-a9bd-42ce-904c-628856108f3c">
If I click on the commit, both its message's title and body can be seen:
<img width="544" alt="Screenshot 2023-11-06 at 11 56 16" src="https://github.com/fork-dev/Tracker/assets/3589041/d6a38d43-5bd9-4d55-b173-1fafd188df75">
Closing and opening Fork does not fix it. The repo is a submodule that's being used in 2 other repos, and the same commit fails to render on both of them.

Fork 2.34.1
macOS Ventura 13.6.
MacBook Pro 16" with M1 Max, 64GB.

**Comment by DanPristupov** [comment]
Hi,

Can you run `git cat-file -p f81fa5fc > output.txt` in terminal and send the `output.txt` file to support@fork.dev, please?

**Comment by matheusamazonas** [comment]
I just did.

**Comment by matheusamazonas** [comment]
A colleague using a Windows Fork client showed me the problem:
![image](https://github.com/fork-dev/Tracker/assets/3589041/8e693b38-47a6-4cb3-9de2-532b862427ec)
When looking at the raw commit, the reason was clear: a `U+000D` (CR) was added at the beginning of the commit subject:
```
Subject: [PATCH] =?UTF-8?q?=0D=E2=99=BB=EF=B8=8F=20Add=20all=20relevant=20?=
```

I tried to reproduce it, but I wasn't able to. It's worth noting that we use [gitmojis](https://gitmoji.dev) on our commits, so their subject often starts with an emoji.

Edit: It's also worth noting that I often use the enter/return key to move from the subject to the description text field.

**Comment by DanPristupov** [comment]
Was that commit made on Windows, may be? Windows uses `CRLF` as a line separator.

**Comment by matheusamazonas** [comment]
Definitely not. I don't even own a Windows machine.

**Comment by DanPristupov** [comment]
Did you make that commit in Fork or in some other tool?

**Comment by matheusamazonas** [comment]
I can't say for certain because there's no way to prove it, but I'm almost sure I authored that commit in Fork. I always use Fork for writing commit messages and actually committing. That commit was from last week, and I don't remember writing a commit using the command line in the last weeks.

Which now is making me wonder how the hell that CR character got there.

**Comment by ghost** [comment]
Same issue for me with Fork 2.40.3 on macOS 14.4

Commits and date fields don't show anymore.

![Capture 2024-03-21 at 10 42 17](https://github.com/fork-dev/Tracker/assets/75068734/677477c0-0719-4172-806d-195ee514864e)

**Comment by DanPristupov** [comment]
@alex-geana try https://cdn.fork.dev/mac/Fork-2.40.5.dmg. Does it fix the problem?
If no, please send the log `~/Library/Logs/Fork.log` to support@fork.dev.

**Comment by ghost** [comment]
@DanPristupov yes! The 2.40.5 version solves the problem.

All good now, thank you!
