### ISSUE TITLE
How to show Repository Manager without opening a new tab

### ISSUE THREAD

**Issue by LeonardoGentile** [ForkIssues/Tracker#2003]
Totally noob question, I'd like to show the repository manager in the current tab instead of closing the current tab and open a new tab.
Is this possible? Is there a keyboard shortcut maybe?

Thanks for the good work 👍

**Comment by DanPristupov** [comment]
You can only open repo manager as a new tab (Cmd+T). If you want to switch repo, use Quick Launch (Cmd+P), then Cmd+Enter
