### ISSUE TITLE
Fork crashes when searching for commits by author

### ISSUE THREAD

**Issue by ovanderzee** [ForkIssues/Tracker#2008]
When it's time to write my hours, I always look for my own commits in the repository.
I use the magnifier-icon in the left pane, choose to search for author, then enter my name and hit enter. Then Fork crashes.

**Comment by ovanderzee** [comment]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Fork [1884]
Path:                  /Applications/Fork.app/Contents/MacOS/Fork
Identifier:            com.DanPristupov.Fork
Version:               2.36.1 (2.36.1)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-11-14 15:11:51.0694 +0100
OS Version:            macOS 14.1.1 (23B81)
Report Version:        12
Bridge OS Version:     8.1 (21P1069)
Anonymous UUID:        4D0630C2-69BC-5134-E6A5-E9AA86B3DFAE

Sleep/Wake UUID:       A3D024BB-39B1-4B77-A9CB-83F5FA689275

Time Awake Since Boot: 2300 seconds

System Integrity Protection: enabled

Crashed Thread:        7  Dispatch queue: com.apple.NSFileHandle.fd_monitoring

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [1884]

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff80c6a1a6e mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff80c6afe7a mach_msg2_internal + 84
2   libsystem_kernel.dylib        	    0x7ff80c6a8b92 mach_msg_overwrite + 653
3   libsystem_kernel.dylib        	    0x7ff80c6a1d5f mach_msg + 19
4   CoreFoundation                	    0x7ff80c7bc405 __CFRunLoopServiceMachPort + 143
5   CoreFoundation                	    0x7ff80c7bae75 __CFRunLoopRun + 1371
6   CoreFoundation                	    0x7ff80c7ba352 CFRunLoopRunSpecific + 557
7   HIToolbox                     	    0x7ff81705c9d9 RunCurrentEventLoopInMode + 292
8   HIToolbox                     	    0x7ff81705c7e6 ReceiveNextEventCommon + 665
9   HIToolbox                     	    0x7ff81705c531 _BlockUntilNextEventMatchingListInModeWithFilter + 66
10  AppKit                        	    0x7ff80fdca885 _DPSNextEvent + 880
11  AppKit                        	    0x7ff8106be348 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1304
12  AppKit                        	    0x7ff80fdbbdfa -[NSApplication run] + 603
13  AppKit                        	    0x7ff80fd8fe10 NSApplicationMain + 816
14  Fork                          	       0x100ff0f19 0x100df6000 + 2076441
15  dyld                          	    0x7ff80c3583a6 start + 1942

Thread 1:
0   libsystem_kernel.dylib        	    0x7ff80c6a1a6e mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff80c6afe7a mach_msg2_internal + 84
2   libsystem_kernel.dylib        	    0x7ff80c6a8b92 mach_msg_overwrite + 653
3   libsystem_kernel.dylib        	    0x7ff80c6a1d5f mach_msg + 19
4   Fork                          	       0x101329ee3 0x100df6000 + 5455587
5   libsystem_pthread.dylib       	    0x7ff80c6e1202 _pthread_start + 99
6   libsystem_pthread.dylib       	    0x7ff80c6dcbab thread_start + 15

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff80c6a1a6e mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff80c6afe7a mach_msg2_internal + 84
2   libsystem_kernel.dylib        	    0x7ff80c6a8b92 mach_msg_overwrite + 653
3   libsystem_kernel.dylib        	    0x7ff80c6a1d5f mach_msg + 19
4   CoreFoundation                	    0x7ff80c7bc405 __CFRunLoopServiceMachPort + 143
5   CoreFoundation                	    0x7ff80c7bae75 __CFRunLoopRun + 1371
6   CoreFoundation                	    0x7ff80c7ba352 CFRunLoopRunSpecific + 557
7   AppKit                        	    0x7ff80ff27a00 _NSEventThread + 122
8   libsystem_pthread.dylib       	    0x7ff80c6e1202 _pthread_start + 99
9   libsystem_pthread.dylib       	    0x7ff80c6dcbab thread_start + 15

Thread 3:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	    0x7ff80c6a1a6e mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff80c6afe7a mach_msg2_internal + 84
2   libsystem_kernel.dylib        	    0x7ff80c6a8b92 mach_msg_overwrite + 653
3   libsystem_kernel.dylib        	    0x7ff80c6a1d5f mach_msg + 19
4   CoreFoundation                	    0x7ff80c7bc405 __CFRunLoopServiceMachPort + 143
5   CoreFoundation                	    0x7ff80c7bae75 __CFRunLoopRun + 1371
6   CoreFoundation                	    0x7ff80c7ba352 CFRunLoopRunSpecific + 557
7   CFNetwork                     	    0x7ff811afe435 0x7ff8118b8000 + 2384949
8   Foundation                    	    0x7ff80d74d85c __NSThread__start__ + 1013
9   libsystem_pthread.dylib       	    0x7ff80c6e1202 _pthread_start + 99
10  libsystem_pthread.dylib       	    0x7ff80c6dcbab thread_start + 15

Thread 4::  Dispatch queue: NSOperationQueue 0x7fd44ed18640 (QOS: UNSPECIFIED)
0   libsystem_kernel.dylib        	    0x7ff80c6a3222 __ulock_wait + 10
1   libdispatch.dylib             	    0x7ff80c539db2 _dlock_wait + 46
2   libdispatch.dylib             	    0x7ff80c539bb0 _dispatch_wait_on_address + 129
3   libdispatch.dylib             	    0x7ff80c53a058 _dispatch_group_wait_slow + 42
4   libswiftDispatch.dylib        	    0x7ff8227f417f OS_dispatch_group.wait(wallTimeout:) + 15
5   Fork                          	       0x101045238 0x100df6000 + 2421304
6   Fork                          	       0x100f98b16 0x100df6000 + 1714966
7   Fork                          	       0x1010f4c40 0x100df6000 + 3140672
8   Fork                          	       0x1011902d0 0x100df6000 + 3777232
9   Fork                          	       0x10123e679 0x100df6000 + 4490873
10  Foundation                    	    0x7ff80d736bba __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
11  Foundation                    	    0x7ff80d736ab8 -[NSBlockOperation main] + 94
12  Foundation                    	    0x7ff80d736a4b __NSOPERATION_IS_INVOKING_MAIN__ + 17
13  Foundation                    	    0x7ff80d735cec -[NSOperation start] + 730
14  Foundation                    	    0x7ff80d735a0d __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
15  Foundation                    	    0x7ff80d7358de __NSOQSchedule_f + 182
16  libdispatch.dylib             	    0x7ff80c546002 _dispatch_block_async_invoke2 + 85
17  libdispatch.dylib             	    0x7ff80c53959a _dispatch_client_callout + 8
18  libdispatch.dylib             	    0x7ff80c53c0c7 _dispatch_continuation_pop + 523
19  libdispatch.dylib             	    0x7ff80c53b73c _dispatch_async_redirect_invoke + 710
20  libdispatch.dylib             	    0x7ff80c548776 _dispatch_root_queue_drain + 328
21  libdispatch.dylib             	    0x7ff80c548f22 _dispatch_worker_thread2 + 152
22  libsystem_pthread.dylib       	    0x7ff80c6ddc06 _pthread_wqthread + 262
23  libsystem_pthread.dylib       	    0x7ff80c6dcb97 start_wqthread + 15

Thread 5:
0   libsystem_pthread.dylib       	    0x7ff80c6dcb88 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	    0x7ff80c6dcb88 start_wqthread + 0

Thread 7 Crashed::  Dispatch queue: com.apple.NSFileHandle.fd_monitoring
0   libswiftCore.dylib            	    0x7ff81c95b576 _assertionFailure(_:_:file:line:flags:) + 502
1   Fork                          	       0x100f3b357 0x100df6000 + 1332055
2   Fork                          	       0x100f3b462 0x100df6000 + 1332322
3   Fork                          	       0x1010667af 0x100df6000 + 2557871
4   Fork                          	       0x100f9997f 0x100df6000 + 1718655
5   Fork                          	       0x100f99152 0x100df6000 + 1716562
6   Fork                          	       0x101047244 0x100df6000 + 2429508
7   Fork                          	       0x101055921 0x100df6000 + 2488609
8   Fork                          	       0x101046bf0 0x100df6000 + 2427888
9   Foundation                    	    0x7ff80de4a7c1 __33-[NSConcreteFileHandle _monitor:]_block_invoke + 48
10  libdispatch.dylib             	    0x7ff80c53959a _dispatch_client_callout + 8
11  libdispatch.dylib             	    0x7ff80c53c0c7 _dispatch_continuation_pop + 523
12  libdispatch.dylib             	    0x7ff80c54c6f8 _dispatch_source_invoke + 2076
13  libdispatch.dylib             	    0x7ff80c53f4bb _dispatch_lane_serial_drain + 387
14  libdispatch.dylib             	    0x7ff80c540100 _dispatch_lane_invoke + 377
15  libdispatch.dylib             	    0x7ff80c549aee _dispatch_root_queue_drain_deferred_wlh + 271
16  libdispatch.dylib             	    0x7ff80c5493fd _dispatch_workloop_worker_thread + 451
17  libsystem_pthread.dylib       	    0x7ff80c6ddc47 _pthread_wqthread + 327
18  libsystem_pthread.dylib       	    0x7ff80c6dcb97 start_wqthread + 15

Thread 8:
0   libsystem_pthread.dylib       	    0x7ff80c6dcb88 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	    0x7ff80c6dcb88 start_wqthread + 0


Thread 7 crashed with X86 Thread State (64-bit):
  rax: 0x00000000b424f1c1  rbx: 0x00000001013d0550  rcx: 0x00000000b424f1c1  rdx: 0x00000000000000bb
  rdi: 0xe000000000000000  rsi: 0x0000000000000ba0  rbp: 0x00007000092222b0  rsp: 0x0000700009222210
   r8: 0x00000000000003ff   r9: 0x00000000b444f8bb  r10: 0x000000000000009f  r11: 0x00000000000001c1
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0xe000000000000000  r15: 0x000000000000000b
  rip: 0x00007ff81c95b576  rfl: 0x0000000000010286  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000 
Trap Number:     6

Thread 7 instruction stream:
  94 00 00 00 6a 02 6a 18-50 e8 ac 02 00 00 4c 89  ....j.j.P.....L.
  f6 48 c1 ee 38 83 e6 0f-48 b8 ff ff ff ff ff ff  .H..8...H.......
  ff 00 4c 21 f0 4c 89 6d-c0 48 89 45 c8 48 83 ec  ..L!.L.m.H.E.H..
  08 44 0f b6 c1 48 8d 7d-c0 4c 89 e2 48 8b 4d 10  .D...H.}.L..H.M.
  49 89 d9 45 31 e4 8b 45-28 50 ff 75 20 41 57 e8  I..E1..E(P.u AW.
  36 0e 00 00 48 83 c4 20-4c 89 f7 e8 2a 6a 32 00  6...H.. L...*j2.
 [0f]0b 48 83 ec 08 48 8d-05 5d fc 43 00 48 8d 3d  ..H...H..].C.H.=	<==
  0a fc 43 00 48 8d 0d 1f-fc 43 00 be 0b 00 00 00  ..C.H....C......
  41 b8 2d 00 00 00 ba 02-00 00 00 41 b9 02 00 00  A.-........A....
  00 6a 01 68 62 0d 00 00-6a 02 6a 14 50 e8 18 02  .j.hb...j.j.P...
  00 00 48 83 ec 08 48 8d-05 fd fd 43 00 48 8d 3d  ..H...H....C.H.=
  ca fb 43 00 48 8d 0d bf-fd 43 00 be 0b 00 00 00  ..C.H....C......

Binary Images:
       0x104d61000 -        0x104d70fff libobjc-trampolines.dylib (*) <98971a5a-9c10-3af1-8886-451f2945c39e> /usr/lib/libobjc-trampolines.dylib
       0x101a01000 -        0x101a54fff org.sparkle-project.Sparkle (2.2.2) <d90b5cb2-08c0-3c48-9826-3c50fadfbd88> /Applications/Fork.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle
       0x101d4b000 -        0x101da2fff com.paddle.Paddle (4.1.0) <a2fe0c86-15c0-30fc-8ec5-bb2ad6717f7f> /Applications/Fork.app/Contents/Frameworks/Paddle.framework/Versions/A/Paddle
       0x100df6000 -        0x1014a9fff com.DanPristupov.Fork (2.36.1) <7f5442ce-8f45-3a74-802c-c5ddd38bc0ed> /Applications/Fork.app/Contents/MacOS/Fork
    0x7ff80c6a0000 -     0x7ff80c6daff7 libsystem_kernel.dylib (*) <4df0d732-7fc4-3200-8176-f1804c63f2c8> /usr/lib/system/libsystem_kernel.dylib
    0x7ff80c740000 -     0x7ff80cbdafec com.apple.CoreFoundation (6.9) <d148cf66-0478-3100-a9d6-0571b6f769e3> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff81702c000 -     0x7ff8172c7ff4 com.apple.HIToolbox (2.1.1) <06bf0872-3b34-3c7b-ad5b-7a447d793405> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7ff80fd8c000 -     0x7ff811191ffb com.apple.AppKit (6.9) <27fed5dd-d148-3238-bc95-1dac5dd57fa1> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7ff80c352000 -     0x7ff80c3ee3df dyld (*) <d5406f23-6967-39c4-beb5-6ae3293c7753> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff80c6db000 -     0x7ff80c6e6fff libsystem_pthread.dylib (*) <c64722b0-e96a-3fa5-96c3-b4beaf0c494a> /usr/lib/system/libsystem_pthread.dylib
    0x7ff8118b8000 -     0x7ff811c64ff5 com.apple.CFNetwork (1.0) <410765c1-18f6-3f9f-b360-cbfbcf6d87ea> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7ff80d6f8000 -     0x7ff80e336ffb com.apple.Foundation (6.9) <581d66fd-7cef-3a8c-8647-1d962624703b> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7ff80c536000 -     0x7ff80c57cffd libdispatch.dylib (*) <4472f1a5-1d47-3665-ac8d-7adb0e9d2d87> /usr/lib/system/libdispatch.dylib
    0x7ff8227e4000 -     0x7ff8227fafff libswiftDispatch.dylib (*) <73e5213b-4ffb-3e20-83d1-dc17013b5b41> /usr/lib/swift/libswiftDispatch.dylib
    0x7ff81c92b000 -     0x7ff81cdd5ff4 libswiftCore.dylib (*) <3311e651-9203-395c-9dc2-7eb7ed101e32> /usr/lib/swift/libswiftCore.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=697.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=697.6M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               256K        2 
Activity Tracing                   256K        1 
CG image                          1036K       49 
ColorSync                          244K       31 
CoreAnimation                     9372K      661 
CoreGraphics                        16K        3 
CoreImage                          288K        6 
CoreUI image data                 3788K       48 
Foundation                          36K        2 
Image IO                           940K       10 
Kernel Alloc Once                    8K        1 
MALLOC                           674.2M      145 
MALLOC guard page                   48K       12 
SQLite page cache                  384K        3 
STACK GUARD                       56.0M       10 
Stack                             12.6M       10 
VM_ALLOCATE                        292K       23 
__CTF                               824        1 
__DATA                            42.6M      691 
__DATA_CONST                      50.9M      469 
__DATA_DIRTY                      1957K      248 
__FONT_DATA                        2352        1 
__INFO_FILTER                         8        1 
__LINKEDIT                       181.5M        6 
__LLVM_COV                          32K        1 
__OBJC_RO                         70.8M        1 
__OBJC_RW                         2157K        2 
__TEXT                           823.7M      715 
dyld private memory                260K        2 
libnetwork                         128K        8 
mapped file                      424.4M      436 
shared memory                      792K       19 
===========                     =======  ======= 
TOTAL                              2.3G     3618

**Comment by DanPristupov** [comment]
Please check for updates

**Comment by ovanderzee** [comment]
That is very quick !
🥇
