### ISSUE TITLE
[Bug] Clear applied filter banner not displayed (UI glitch)

### ISSUE THREAD

**Issue by TomaszLizer** [ForkIssues/Tracker#2011]
# Description
When applying filters to git tree view there was UI (banner) show at the top of the git tree view.
It was showing currently applied filters as well as button to clear those filters.
Right now non-functional `Search` UI is displayed instead.
When trying to click this search UI in place where clear button is expected to be found, then indeed filters are removed.

# Reproduction
- Open repository
- Apply filter by clicking on filter icon next to any branch in the repository
- Inspect top of the git tree view

Expected result
- Applied filter UI at the top portion of view

Actual result
- Non functional search UI at the top portion of view

## Additional info
App version: 
- 2.36.2
- happening in few past releases too

Platform:
- Mac OS 14.0 (arm64)

https://github.com/fork-dev/Tracker/assets/93589480/b9ec245f-1b14-4e23-a663-83a06a291593

**Comment by riono210** [comment]
I'm experiencing the same issue.

When the branch filter is turned on, the Find banner is displayed, but input and search functions do not work. The Done button also does not function. However, if you turn on the branch filter after displaying the Find banner with commands such as ⌘F, it is displayed and functions correctly.

It is likely that the Find banner is affecting the functionality.

---
App version:
- 2.36.2

Platform:
- OSX 14.1 (m1)

https://github.com/fork-dev/Tracker/assets/23465206/f9bf2a88-055c-4b1a-a4c6-861aac35dc9b
