### ISSUE TITLE
Can't add individual submodules into repository anymore.

### ISSUE THREAD

**Issue by AlexBlack559** [ForkIssues/Tracker#2014]
After updating from 2.29.2 to 2.35.2 I can't add individual submodules.
I have a meta-repository containing many repositories. Usually I can add individual repositories in Fork and work with them as is. But after update I cannot add them anymore.

**Comment by DanPristupov** [comment]
> But after update I cannot add them anymore.

What's wrong?

**Comment by AlexBlack559** [comment]
@DanPristupov I've created an example repository for you to reproduce the bug:
1. In a terminal: git clone --recurse-submodules git@github.com:AlexBlack559/ExampleMetaRepository.git
2. In The Fork: right click on repositories in a left pane
3. Click "Add Repository"
4. Select "Example Submodule" in Finder window.

Actual result: Nothing happens
Expected result: Opens submodule repository like in older Fork versions.

**Comment by DanPristupov** [comment]
Submodules are not saved in the Repository Manager (never been).

**Comment by AlexBlack559** [comment]
I still have an old version of the app on my second Mac and this functionality works for me there. Missing this functionality is very unfortunate, cause main development happens in submodules.
Also working with submodules in fork is very inconvenient, because you cannot't see at a glance what branches are checked out in submodules.

**Comment by AlexBlack559** [comment]
@DanPristupov Just for your information. There are like 10 people using fork in my team. And we are all using an old version of Fork just because of this issue.
