### ISSUE TITLE
[Feature] Copy different properties of a commit at once

### ISSUE THREAD

**Issue by dherderich** [ForkIssues/Tracker#2016]
I often need to transfer the commit message, hash, date/time to a different place.
At moment I have to copy first the hash, and paste it, then copy the message and paste it, etc.
It would be nice, if I could choose in the settings which parts of a commit should be copied, when executing Copy (Ctrl/cmd +C).

**Comment by DanPristupov** [comment]
Alt+Cmd+C

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/Tracker/issues/1987
https://github.com/fork-dev/Tracker/issues/1867
https://github.com/fork-dev/Tracker/issues/1804
https://github.com/fork-dev/Tracker/issues/421

**Comment by dherderich** [comment]
> Alt+Cmd+C

As written in #421 the shortcut is also not working for me.
Furthermore, when executing this action from the context menu, only the short verison of the hash is copied. I need the full hash.

**Comment by DanPristupov** [comment]
> the shortcut is also not working for me.

Does Alt+Cmd+C work in Finder to copy full file path instead of file?

**Comment by dherderich** [comment]
> Does Alt+Cmd+C work in Finder to copy full file path instead of file?

No, it moves the window to the center of the screen. But I found the reason: The app Tiles added Option-Command-C as shortcut.
After removing this shortcut, Option-Command-C works now also in Fork again.

But nevertheless, I still request configureable settings for the commit and/or the full hash when copying the commit.

**Comment by DanPristupov** [comment]
> After removing this shortcut, Option-Command-C works now also in Fork again.

👍

> I still request configureable settings for the commit and/or the full hash when copying the commit.

No, most likely we won't have a time to implement and support that.
