### ISSUE TITLE
How to Check the Total Number of Changes in a Branch During Work

### ISSUE THREAD

**Issue by KaitoMuraoka** [ForkIssues/Tracker#2018]
How can I see the total number of changes in the branch I'm currently working on?

In Git, you can display it as shown below:

```sh
$ git diff main develop --shortstat
 18 files changed, 293 insertions(+), 332 deletions(-)
```

 I want to do something similar to this.

**Comment by DanPristupov** [comment]
There's no UI for that.

But may be you can create a branch custom command and call it from the branch context menu.

<img width="936" alt="Screenshot 2023-11-24 at 11 12 35" src="https://github.com/fork-dev/Tracker/assets/618115/0487fce7-3948-448b-adce-738d115033f1">
<img width="936" alt="Screenshot 2023-11-24 at 11 12 32" src="https://github.com/fork-dev/Tracker/assets/618115/a18d64a1-960c-44c7-a52d-3880fc3eeb39">
<img width="432" alt="Screenshot 2023-11-24 at 11 12 46" src="https://github.com/fork-dev/Tracker/assets/618115/0043f6db-8e5a-4d4c-b613-0b9f1ce54774">
<img width="625" alt="Screenshot 2023-11-24 at 11 12 57" src="https://github.com/fork-dev/Tracker/assets/618115/45f078d7-2022-438f-9efd-c5dd50a926db">

**Comment by KaitoMuraoka** [comment]
@DanPristupov 

Sorry for the late reply.

Thank you for telling me!

Thanks to you, I've come to like Fork even more!"
