### ISSUE TITLE
[Solved] [Crash] Fork crashes when opening (macOS)

### ISSUE THREAD

**Issue by hasanniz** [ForkIssues/Tracker#2019]
The app crashes whenever I open it, copying a fresh version of Fork.app into applications directory doesn't work.

Crashlog: [crashlog.txt](https://github.com/fork-dev/Tracker/files/13458962/crashlog.txt)

![2023-11-24_23-22-15 (3)](https://github.com/fork-dev/Tracker/assets/8472738/ac88ab36-dfa6-4e89-abf2-b902a7f7387e)

**Comment by DanPristupov** [comment]
Hi. Try to delete `~/Library/Application Support/com.DanPristupov.Fork/` directory

**Comment by hasanniz** [comment]
That did the trick, thanks Dan! Love the app btw ❤️

**Comment by DanPristupov** [comment]
Thank you for the nice words.

The crash report helped me to figure out the problem quickly 👍
