### ISSUE TITLE
Open GitHub's Pull Request site for the active branch

### ISSUE THREAD

**Issue by herrherrmann** [ForkIssues/Tracker#202]
Hello there!
I'm making a lot of use of GitHub's editor for writing pull requests (in order to get a proper MarkDown preview, mention other users and commits, add images etc.) — so I'd find it very helpful to be able to quickly open the compare site for the currently checked-out branch. The URL would look like this:
```
https://github.com/<author>/<repo>/compare/<branch-name>?expand=1
```

There's probably a similar link possible for GitLab repos!

**Comment by infotexture** [comment]
👍 for an option to create a new pull request from the active/selected branch.

Very handy in the other clients that have it, would be great to be able to do this from within Fork.

**Comment by DanPristupov** [comment]
This is a very good request. Fork has a 'Create Pull Request' window already, but I don't like it much. Plain-text text field doesn't make much sense when I compose a PR. I always need Markdown preview and image attachments, same as you.

I'd like to discuss the details:
1. Do you think we should keep the current "Pull Request" window alive or completely replace it with such link?
2. Currently, its only possible to create PR for a remote branch. Do we need an `Push to %remote% and create PR` option for local branches?
3. Do we need an ability to create a cross-repository PR?

**Comment by infotexture** [comment]
I was not aware that Fork can already create PRs for remote branches, as this feature _(like many others)_ is not available in the main menu — I never thought to check the context menu for a remote branch. 

_(Would be good to make these things more discoverable with menu items and/or toolbar buttons.)_

1. Most of the other GUIs I've tried just use the GitHub API to open the PR link in the browser.
2. This would save a step, since you could push & create the PR all at once.
3. The feature could default to the tracked remote, but in some cases the PR might need to be based on a different upstream remote, so the ability to select from multiple remotes would be helpful.

**Comment by herrherrmann** [comment]
1. I wouldn't really use the current "minimal" window anyway as my PR descriptions are usually lengthy and using mentions, images etc. — so I'd get rid of the current one in favor of a nice linkout.
2. For me it'd be fine to manage the branch in Fork before creating a PR — I don't really see a way around it unless you really only have one commit on the relevant branch?
3. Cross-repo ability sounds quite important, yes (especially when *forking* open-source projects)!

**Comment by nebhale** [comment]
1.  Drop it.  No need to have two ways to do a single thing.
1.  It might be useful to take a look at how the official [GitHub CLI](https://github.com/github/hub) works:
    ```
    $: git pull-request --help
    usage: git pull-request [-f] [-m <MESSAGE>|-F <FILE>|-i <ISSUE>|<ISSUE-URL>] [-o] [-b <BASE>] [-h <HEAD>] 
    
    Opens a pull request on GitHub for the project that the "origin" remote
    points to. The default head of the pull request is the current branch.
    Both base and head of the pull request can be explicitly given in one of
    the following formats: "branch", "owner:branch", "owner/repo:branch".
    This command will abort operation if it detects that the current topic
    branch has local commits that are not yet pushed to its upstream branch
    on the remote. To skip this check, use "-f".
    
    Without <MESSAGE> or <FILE>, a text editor will open in which title and body
    of the pull request can be entered in the same manner as git commit message.
    Pull request message can also be passed via stdin with "-F -".
    
    If instead of normal <TITLE> an issue number is given with "-i", the pull
    request will be attached to an existing GitHub issue. Alternatively, instead
    of title you can paste a full URL to an issue on GitHub.
    ```
    It appears that the tool expects a remote branch to already exist, and is tied to the `origin` remote.  My preference would be to align with both of those, but the preference isn't strong.  In nearly every situation I'd already have that remote branch in existence anyway, but    I can totally see other situations.
1.  The CLI supports cross repo (`owner:branch`, `owner/repo:branch`) so I'd say yes, Fork should support that as well.

One thing to keep in mind is that once a PR UI is open, GitHub provides everything you might need to fine-tune the PR location; what it's branched off of, what it's submitting to, etc.  So I think you should keep the Fork UI simple and cover the most common cases really solidly, and allow the edge cases to fall back to the GitHub UI.

**Comment by Djspaceg** [comment]
Having a direct way to get to various places on GitHub would be really convenient. A customizable set of toolbar buttons would be great. They could be pre-populated with tokenable URLs would make it platform independent too. Want a "Create PR" button, a "Compare Branches" button, "Open selected item on GitHub", just make a button yourself. These could be managed in a Preferences "tab", which then generate corresponding Toolbar Items. _(Probably also need some sort of Icon picker too.)_ :(

Regarding the built-in PR generator dialog, could the title and/or first part of the body be pre-populated with the first or last commit message from the branch? (The text from the item that was right-clicked or highlighted in the history screen perhaps). This would more closely resemble the functionality on GitHub and reduce the steps for smaller PRs. Some users may still want to go directly to GitHub for the more advanced features it offers.
