### ISSUE TITLE
[Feature] Less invasive update notification

### ISSUE THREAD

**Issue by svekl** [ForkIssues/Tracker#2021]
Current modal always jumps out of nowhere while I'm in a middle of something so have to just close it right away and forget that something useful arrived. Is it possible to make this notification to be something like in Chrome or Warp so we could see it while working and click when we have time for that and read what's new and update if we want?

**Comment by DanPristupov** [comment]
duplicate https://github.com/fork-dev/Tracker/issues/1065

**Comment by svekl** [comment]
Duplicate
