### ISSUE TITLE
How to diff 2 branches / tags

### ISSUE THREAD

**Issue by vnazarenko** [ForkIssues/Tracker#2022]
Looks like i lost this feature, previuously it was sub menu item : 'DIff with ... `. But now there is. no such, and also if i select 2 tags in left menu - nothing changes, Diff appear only if i select 2 commits in history, but it's not convenient if i want to get diff for 2 old tags, in console it would be something like `git diff v1.1.1..v1.2.0` but how to archive this in fork?

**Comment by DanPristupov** [comment]
Select a pair of branches/tags/commits to compare them.

**Comment by vnazarenko** [comment]
I do this  - but nothing change. Diff still shows me last selected commit in history

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/Tracker/assets/618115/c638eb1b-5944-4e89-837b-3bced957662e

**Comment by vnazarenko** [comment]
I found problem, branch filter was present - and only commits from current branch was shown - and that's why when i select any tag - ( and commits from there was not in current branch history ) nothing changed. But this was frustrating
