### ISSUE TITLE
Amending an author name

### ISSUE THREAD

**Issue by huntc** [ForkIssues/Tracker#2028]
Can you please advise on how an author name can be updated? I have a few "Your Name" authors in my commits.

**Comment by DanPristupov** [comment]
You can't change the author name of the latest commit from Fork, but you can do that in command line.

`git commit --amend --author="author <email>"`

https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---amend

**Comment by huntc** [comment]
Thanks. I suspected that was the case.
