### ISSUE TITLE
Commit description text is lost if field becomes hidden

### ISSUE THREAD

**Issue by petterikamppuririchie** [ForkIssues/Tracker#203]
For example, if I switch to "All Commits" view (Cmd-2) (and then go back to "Uncommitted Changes" view), the commit description text field loses any text I've typed. Really annoying to lose data just because I wanted to check something so I can type a good message.

Actually just pressing Cmd-1 causes the text field to be cleared.

**Comment by DanPristupov** [comment]
Hi. Thank you for the bug report. I just fixed this issue in Fork 1.0.63.

**Comment by petterikamppuririchie** [comment]
Supergreat 👍 It's so great to see bug reports actioned upon / already fixed. I'm so used to Apple's Radar, where bugs go to die 😄
