### ISSUE TITLE
Stash is empty in shallow clone/fetch repo

### ISSUE THREAD

**Issue by miku1958** [ForkIssues/Tracker#2030]
I updated a large repository using `git fetch --prune --verbose --depth 1 branch`, and as a result, all the stashes disappeared from Fork. `git stash list`  was able to show all the stashes.

**Comment by DanPristupov** [comment]
Please check if the log file has any errors. The log is located at `~/Library/Logs/Fork.log`

**Comment by miku1958** [comment]
`❌[BtResultExtensions.swift:33] > Bt error:
Failed to read stash objects for given oids: Failed to find object 9ffd2c7ce01a751bc621b666526eaae227ad05f0`

**Comment by DanPristupov** [comment]
Thank you. Wait a bit, please.

**Comment by DanPristupov** [comment]
I just tried that command and it removed some of stashes in my test repository. Most likely it did the same for you, so be prepared for that.

Please wait a bit more. I'll send a link to a build with a hotfix.

**Comment by DanPristupov** [comment]
Can you try this build, please? https://cdn.fork.dev/prerelease/Fork-2.36.10.dmg

**Comment by miku1958** [comment]
ok stashes back.

**Comment by DanPristupov** [comment]
OK, this fix will be part of the Fork 2.37 update.
