### ISSUE TITLE
Unexpected error when trying git pull while terminal is working ok

### ISSUE THREAD

**Issue by orliin** [ForkIssues/Tracker#2032]
When I try to pull, I get an error message:
<img width="851" alt="image" src="https://github.com/fork-dev/Tracker/assets/211612/02156c7f-776d-4e82-8c93-65f108aa5be5">
In the details there are 626 rows and all start with [up to date] with nothing special about them.

In the terminal git pull is working ok.

**Comment by DanPristupov** [comment]
> When I try to pull, I get an error message:

It means git returned a non-zero exit code.

> In the details there are 626 rows and all start with [up to date] with nothing special about them.

Check every line, there must be some error.

**Comment by orliin** [comment]
The problem was that remote tags had a conflict with local tags. VS Code git client offered me to override all tags using the remote and the problem was fixed.
