### ISSUE TITLE
Creating tag with keyboard only attaches it to the newest commit

### ISSUE THREAD

**Issue by SimJoSt** [ForkIssues/Tracker#2035]
Selecting a commit from "All commits" view and pressing the keyboard shortcut to create a tag `SHIFT` + `COMMAND` + `T`, brings up the tag creation modal.
Entering a name for the tag and pressing `ÈNTER`, adds this new tag to the most current tag, instead of the selected one.

**Comment by DanPristupov** [comment]
Yes, that's how it works.

https://github.com/fork-dev/Tracker/issues/1596

https://github.com/fork-dev/Tracker/issues/1577

https://github.com/fork-dev/Tracker/issues/1165

https://github.com/fork-dev/Tracker/issues/128

**Comment by SimJoSt** [comment]
Thanks for pointing out the duplicate bug reports. My duplicate search before posting is normally more thorough.
I'll follow the first one to track the progress on this.
