### ISSUE TITLE
Undo/Redo in the commit message/description textbox

### ISSUE THREAD

**Issue by ShlomoCode** [ForkIssues/Tracker#2037]
It is common for text boxes to use the keyboard shortcut command + to cancel the last change in the text, and command + shift + z to perform the operation again.
It exists, for example, everywhere on the Internet (since browsers such as Chrome implement it) as well as in VSCode SOURCE CONTROL, etc.
But in the excellent Fork software, this option does not exist, and if, for example, I accidentally paste a long piece of text or delete something, I have to manually correct the mistake, and cannot simply press command+z as usual.
I would love if you could implement this feature! If further clarification of the use case is required, let me know.
Thanks

**Comment by DanPristupov** [comment]
Works for me.

https://github.com/fork-dev/Tracker/assets/618115/0047e3c6-02a8-4377-8b83-a7e81cb5fae2

Try to reboot the computer

**Comment by ShlomoCode** [comment]
It hasn't worked for me for a long time, but it's probably a problem with my computer, I'll investigate. Sorry for the trouble
