### ISSUE TITLE
Large files freezes Fork when it tries to render it

### ISSUE THREAD

**Issue by SanderFlooris** [ForkIssues/Tracker#2038]
I sometimes have an SQL dump (300MB) in the project directory so I can import it into my Docker container more easily.

Normally that isn't an issue, but it does become an issue once Fork automatically select that file to render it while I try to wrap up the commit.
It freezes for multiple minutes, until it finally realizes the file is too big and gives up.

A possible solution might be to include an option where by default it won't render any file larger then a given amount, and you have to press a button in case you do want it to render it.
This probably also allows you to check if the file will be to complicated to render, before actually starting to render the change, which will most likely fix this issue.

Maybe something like this?
![Screenshot 2024-01-02 at 09 37 06](https://github.com/fork-dev/Tracker/assets/116890267/24553961-b0bb-4ec8-9c2b-251de6abf158)

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/Tracker/issues/1007

**Comment by DanPristupov** [comment]
Is the file untracked? If it is, we can check the file size before reading it.

**Comment by SanderFlooris** [comment]
Ah whoops, I didn't see that earlier issue 😅 

And yes, the file in question is untracked, so that could also be a suitable solution
