### ISSUE TITLE
[Feature] Add option to middle ellipsize repository names so not only the beginning is visible

### ISSUE THREAD

**Issue by balazsgerlei** [ForkIssues/Tracker#2039]
I work with a bunch of repositories that has the same, not particularly short prefix and only the end differs. When I have these repositories open in Fork, only the same prefix is displayed on the tabs, making it literally impossible to distiguish them (it doesn't help that even when opening them, the repository name is similarly clipped at the end on the top middle that displays the currently open repository).

Can you please add - at least as an option - to middle ellipsize names when they don't fit? Honestly I think it should even be the default, but making it a setting also makes sense.

It would really go a long way in usability of the app, thank you!

**Comment by DanPristupov** [comment]
No, macOS doesn't allow tab title customization.

**Comment by balazsgerlei** [comment]
I see, thank you. I'm sad but I understand.

Maybe my other idea could help my use case, I hope you would consider that: https://github.com/fork-dev/Tracker/issues/2040
It really slows me down every day that I have to guess which repo is which
