### ISSUE TITLE
Shortcuts do not work anymore in "Local Changes" window on MacOS Sonoma

### ISSUE THREAD

**Issue by schilchSICKAG** [ForkIssues/Tracker#2043]
After upgrading to MacOS Sonoma, I have noticed that shortcuts for stage / unstage, revert and other does not work anymore. They are still displayed when using the right click menu and can still triggered via click, but do not work as keyboard shortcuts. Shortcuts that do not use shift keys are still working (for example COMMAND+S will STAGE/UNSTAGE fine).

It looks like this when opening the right click menu:

![error-shortcuts](https://github.com/fork-dev/Tracker/assets/141909690/c60cb472-bbc8-48b6-a99d-62bae66acd6b)

**Comment by DanPristupov** [comment]
Did you change the keyboard layout, may be?

**Comment by schilchSICKAG** [comment]
Nope, still the default for my country (de_DE).

**Comment by schilchSICKAG** [comment]
It may very well be that a third party tool was "steeling" the shortcuts, in this case Rectangle. I killed the application, afterwards shortcuts work fine again. However, the options in the right click menu is still greyed out for "Revert" and "Revert all".
