### ISSUE TITLE
⌘⇧D - Discard selected file short cut not working

### ISSUE THREAD

**Issue by paulmach** [ForkIssues/Tracker#2044]
OS X - 14.2.1
Fork - 2.38

I click an unstaged file, press ⌘⇧D and nothing happens.  It used to work a few release ago.

**Comment by DanPristupov** [comment]
<img width="671" alt="Screenshot 2024-01-17 at 20 24 32" src="https://github.com/fork-dev/Tracker/assets/618115/1b89b2d4-ed61-40e8-885b-890b295975b3">

**Comment by paulmach** [comment]
wow, sorry
