### ISSUE TITLE
Fork crashes on one specific repo

### ISSUE THREAD

**Issue by deszip** [ForkIssues/Tracker#2045]
Hi there, I saw this issue on 2.37 and now it can be reproduced on 2.38.
Switching to a tab with opened repo crashes fork. It's a SIGTRAP on non-main thread, call stack shows some NSBlockOperation stuff. See full crash log attached.

Repo is a huge project with submodules managed by our own system, we also use LFS. It works totally fine before 2.37.
I tried to restart the app, start with tab closed, open same repo cloned to another destination. Same result. All other repos (100+) works fine, including repos with LFS.

System: 14.0 (23A344)
Fork: 2.38

Ping me if I can provide more info. Also glad to help if you need to test fix.
Thanks for amazing tool :)

[crash.log](https://github.com/fork-dev/Tracker/files/13988596/crash.log)

**Comment by DanPristupov** [comment]
Does the repository have an octopus-merge of more than 256 branches? 😳

**Comment by deszip** [comment]
First I thought you're asking about either 256 or any octopus merge. 
No, we don't have octopus merges at all.

**Comment by DanPristupov** [comment]
Can I send you a debug build with additional logging so I could fix the problem faster? Please contact me by email: support@fork.dev

**Comment by deszip** [comment]
Sure, glad to help.

**Comment by DanPristupov** [comment]
Just in a case someone reads this topic in the future.
It turns out that there was indeed an octopus merge commit with **47132** parent commits 😳
