### ISSUE TITLE
[Crash] Crashes when opening (macOS) 

### ISSUE THREAD

**Issue by hanjun-molocoads** [ForkIssues/Tracker#2049]
The same problem as in https://github.com/fork-dev/Tracker/issues/2019. I tried the solution in that thread, but no luck.
Crash log: 
[fork_crash.txt](https://github.com/fork-dev/Tracker/files/14002374/fork_crash.txt)

I also tried `defaults delete com.DanPristupov.Fork`, but no luck.

**Comment by DanPristupov** [comment]
Open command line and abort interactive rebase (`git rebase --abort`).

Did you start IR from the command line?
