### ISSUE TITLE
CLI support?

### ISSUE THREAD

**Issue by nrlquaker** [ForkIssues/Tracker#205]
Hello,
any chance you will include support for opening repos from CLI?
For example `fork .`, like in github or Visual Studio Code.

**Comment by DanPristupov** [comment]
Hi. There's Fork CLI tool.

![2018-02-01 at 14 25](https://user-images.githubusercontent.com/618115/35680882-e0949508-075b-11e8-8723-67987e62957f.png)

**Comment by nrlquaker** [comment]
Oh, thank you. Didn't see it.
