### ISSUE TITLE
Fork freezes when clicked on "Setting for This Repository.."

### ISSUE THREAD

**Issue by vladopar** [ForkIssues/Tracker#2050]
Hi,
in last 2 versions I ran into the issues when clicked on "Setting for This Repository.."
Fork freezes completly and I have to force quit it.
Not sure whether it occured right after updating to MacOs Sonoma or not.
Currently running
Sonoma 14.2.1 (23C71)
Fork 2.38
[Crash.txt](https://github.com/fork-dev/Tracker/files/14009582/Crash.txt)

**Comment by DanPristupov** [comment]
`gpg --list-secret-keys --with-colons` hangs.

Fork tries: `/opt/homebrew/bin/gpg`, `/usr/local/bin/gpg` and `/opt/local/bin/gpg`.

**Comment by vladopar** [comment]
Thanks deleted a .lock file, now it works.
