### ISSUE TITLE
Increase file size limit for file previews

### ISSUE THREAD

**Issue by saket** [ForkIssues/Tracker#2051]
Hi! A recent update seems to have brought in a size limit for file previews. Can this be increased/removed? We have hundreds of screenshot tests in our projects that can no longer be viewed in fork.

![image](https://github.com/fork-dev/Tracker/assets/2387680/e327f7ee-2c4c-4006-9ab1-076a17f12a43)

**Comment by DanPristupov** [comment]
Thank you for reporting this.

Can you wait until the end of the week?

**Comment by saket** [comment]
Yes of course!

I'm using Sublime Merge in the meantime. While it's not as nice as Fork, I can't wait to switch back.

**Comment by saket** [comment]
If you don't mind, can I also bring your attention to https://github.com/fork-dev/Tracker/issues/1897?

**Comment by DanPristupov** [comment]
We just released Fork 2.39 with the fix.

**Comment by saket** [comment]
❤️
