### ISSUE TITLE
[Feature Request]: Add option to push screen to skip pre-push hooks (--no-verify)

### ISSUE THREAD

**Issue by mattijsf** [ForkIssues/Tracker#2056]
It would be nice to have a checkbox that would allow me to push without running the pre-push hook:

<img width="524" alt="Screenshot 2024-01-26 at 12 55 26" src="https://github.com/fork-dev/Tracker/assets/706368/be05c29b-36c8-4897-ac7a-2f60062574ca">

**Comment by DanPristupov** [comment]
duplicate https://github.com/fork-dev/Tracker/issues/1239

**Comment by zackiepurr** [comment]
where isss iitt
