### ISSUE TITLE
Submodules not shown after update to version 2.39

### ISSUE THREAD

**Issue by sjovallx** [ForkIssues/Tracker#2057]
Previously submodules were shown under Submodules in UI (macOS).
After update to version 2.39 the Submodules is empty even if the repository has submodules:
<img width="250" alt="image" src="https://github.com/fork-dev/Tracker/assets/155151738/b7ba3342-0970-40d1-8d5b-8aeb6d61d6af">

In addition, unstaged submodule changes cannot be discarded from UI anymore.

**Comment by DanPristupov** [comment]
Can you try if https://cdn.fork.dev/mac/Fork-2.39.1.dmg works properly?

**Comment by sjovallx** [comment]
Yes, 2.39.1 works perfectly. Thanks!

**Comment by DanPristupov** [comment]
Someone probably edited the `.gitmodules` file in your repo manually and removed the trailing `\n'.

Fork failed to parse `.gitmodules` file when it has no `\n` at end of file. We released the hotfix, but don't push update to all users to not bother them too much.
