### ISSUE TITLE
Commit list ignores .mailmap

### ISSUE THREAD

**Issue by roefer** [ForkIssues/Tracker#2058]
Hi,

`git` uses the file `.mailmap` to unify author names. While the commit view in Fork correctly shows the mapped names, the author column in the history view does not. It would be nice to display the mapped names everywhere. For instance, `git log` always shows mapped names.

**Comment by DanPristupov** [comment]
Do you mean `History` from the file context menu or the main commit list?
Can you contact me by email, please? support@fork.dev

**Comment by roefer** [comment]
I mean the main commit list.

**Comment by DanPristupov** [comment]
Can you send me an email support@fork.dev, please?

**Comment by roefer** [comment]
It turned out that the .mailmap file used the wrong format in one line, which got Fork stuck. If the file is formatted correctly, it works.
