### ISSUE TITLE
Commit message template support

### ISSUE THREAD

**Issue by infotexture** [ForkIssues/Tracker#206]
Fork currently ignores the [commit.template](https://git-scm.com/docs/git-config#git-config-committemplate) option in the local repository configuration.

If this option is set, the commit UI should be populated with the content of the message template when the **Commit** command is called from the menu or <kbd>⇧</kbd><kbd>⌘</kbd><kbd>C</kbd> shortcut.

Bonus points for an option to edit the commit message template from the repository **Settings** dialog like in [SourceTree](https://www.sourcetreeapp.com).

**Comment by DanPristupov** [comment]
I'm going to implement that in the near future. Please do not hesitate to remind me if I forget. It's easy to get distracted because there are a lot of feature requests around.

**Comment by DanPristupov** [comment]
Done in 1.0.64. The commit template is populated automatically. There's also a UI to edit the message in the repository settings.

**Comment by DanPristupov** [comment]
@infotexture awesome. Thank you for the feedback. Will clarify the checkbox label and trim the template file path in the next update.
