### ISSUE TITLE
Request: Remove fork-specific prefixes from patch files

### ISSUE THREAD

**Issue by jb-gcx** [ForkIssues/Tracker#2060]
Creating a patch file from fork results in `forkSrcPrefix` and `forkDstPrefix` placeholders in the patch file. This makes it impossible for colleagues who are not using fork to apply the patches, unless I manually edit them to use relative paths.

I would really like if patch files were generated without these prefixes, for interoperability.

**Comment by DanPristupov** [comment]
What tool do they use? `git apply` handles those files just fine.

**Comment by jb-gcx** [comment]
So... They use `git apply`. I asked them again, they tried again, and it works. I don't know what happened a few weeks ago when we had issues, but we don't see them any more. Sorry, I shouldn't have created the issue without retesting myself 🙏
