### ISSUE TITLE
No diff for .po files

### ISSUE THREAD

**Issue by ismagilli** [ForkIssues/Tracker#2065]
I found that _fork_ does not display a text diff for files with `.po` extension.
Note: .po files are plain text (usually in utf8 encoding) files with translations. They are used by [GNU gettext](https://www.gnu.org/software/gettext/).

<img width="746" alt="image" src="https://github.com/fork-dev/Tracker/assets/38747776/acbb9539-46cc-4afd-8ab0-4087582164ab">

**Comment by DanPristupov** [comment]
> .po files are plain text (usually in utf8 encoding) files with translations. 

May be they are in utf-16 which is not handled well by git?

Try to add `*.po text` to the `.gitattributes` file.

**Comment by ismagilli** [comment]
@DanPristupov No, this is utf8 text. But the problem was with git attributes. In the repository I was working with, the `-diff` attribute was set for .po files. Thanks!
