### ISSUE TITLE
[Feature Request/Improvement] Tab Order Changing on Restart and Active Tab is Not Easy to Distinguish with Light Theme 

### ISSUE THREAD

**Issue by eddysnjack** [ForkIssues/Tracker#2066]
I looked for tab related issues but couldn't find exact matches to the situation. If this is a duplicate I'm sorry. Feel free to mention duplicates.

Problem 1:
I'm working on two repos, both of them has a submodule. So I have 4 tabs open. When reopen fork the last active tab going to most left and because I have same named branches on those repos, most of the time I dont even recognize I'm on wrong repo. 
I want to keep tab order as is before. An option for this behaviour would be awesome.

Problem 2:
This is also about tabs. Active and passive tab buttons can not distinguishable easily. Any improvement in that manner, a bold title on active tab or any shadow, vibrant color etc. would make life much easier imho. Thanks.

Light Theme Tab ScreenShot:
![Screenshot 2024-02-14 at 15 54 42](https://github.com/fork-dev/Tracker/assets/38407276/abd8ae6c-f7d8-48a9-9ab3-32591c22d0d5)

**Comment by DanPristupov** [comment]
> I'm working on two repos, both of them has a submodule. So I have 4 tabs open. When reopen fork the last active tab going to most left and because I have same named branches on those repos, most of the time I dont even recognize I'm on wrong repo.

Never noticed that. I'll have a look.

> Active and passive tab buttons can not distinguishable easily.

Same as in Finder, Safari, XCode, etc. This is the macOS design.
