### ISSUE TITLE
How to set automatically push `main` or `master` branch when finish release?

### ISSUE THREAD

**Issue by iluxsm** [ForkIssues/Tracker#2068]
Hello, everyone. I have one question.

## Background
To explain the background, my company has adopted and is using a git-flow strategy.
As a current company deployment policy, master branch protection rule has been applied.
Then, when the finish release was done on git-fork after PR approval, it was not pushed to the remote, so another PR for merging was needed after the finish release. So, after a little research, I found that if you add the `-p` or `-push` option to apply push on finish release, the remote will be automatically updated.

## Question
Can I set automatically push `main` or `master` branch when git flow finish release in fork?

---
Thanks in advance for your reply. Have a nice day.

**Comment by DanPristupov** [comment]
Hi,

> my company has adopted and is using a git-flow strategy.

You should not. git-flow is redundant and generally not recommended to use.

> Can I set automatically push main or master branch when git flow finish release in fork?

No, you must ensure that the merge is correct and then push manually.

**Comment by iluxsm** [comment]
Thank you for the very quick reply 👍🏽
