### ISSUE TITLE
Diffs are reversed when using cmd-D and Kaleidoscope

### ISSUE THREAD

**Issue by atomicbird** [ForkIssues/Tracker#207]
I have Fork 1.0.63 configured to use Kaleidoscope for external diffs. When I press cmd-D, the diffs shown in Kaleidoscope are reversed from the actual change. For example, added lines are shown as if they were deleted.

Diffs are shown correctly in Fork, and if I launch Kaleidoscope from the command line via `git difftool`, they're also correct.

For example, here's a simple diff as shown in Fork:

<img width="266" alt="screen shot 2018-02-01 at 4 18 55 pm" src="https://user-images.githubusercontent.com/15008/35708499-b8015cd8-076b-11e8-9f64-8085358fba18.png">

But if I press cmd-D, Kaleidoscope shows this:

<img width="606" alt="screen shot 2018-02-01 at 4 20 17 pm" src="https://user-images.githubusercontent.com/15008/35708534-d9cc38b0-076b-11e8-94ca-bdf1ddc32f6e.png">

It's not Kaleidoscope though, because if I launch it with `git difftool` I get the expected result:

<img width="539" alt="screen shot 2018-02-01 at 4 27 32 pm" src="https://user-images.githubusercontent.com/15008/35708763-d72670fc-076c-11e8-8c42-f900af1a22c7.png">

**Comment by DanPristupov** [comment]
Hi. Thank you for the bug report. Preparing hotfix right now.

**Comment by DanPristupov** [comment]
I released the hotfix build (Fork 1.0.63.**1**). Could you please perform update and check if diff is shown properly now.

**Comment by atomicbird** [comment]
Hey, thanks for the quick response. However I'm seeing the same results as above with 1.0.63.1.

**Comment by DanPristupov** [comment]
Sorry about that. I fixed Kaleidoscope blindly because my trial had expired and I don't have an easy way to run it. Supporting a bunch of paid merge tools is a bit tricky.

I just released 1.0.63.2 with another fix.

**Comment by atomicbird** [comment]
Much better. Thanks so much!

**Comment by dlpasco** [comment]
@DanPristupov hit up support@blackpixel.com and I'll get a license sent to you.

**Comment by nebhale** [comment]
@dlpasco Beat me to gifting him one 😄

**Comment by DanPristupov** [comment]
@dlpasco awesome! Will do. Thank you very much👍
