### ISSUE TITLE
Jump to parent commit not working anymore

### ISSUE THREAD

**Issue by craftey** [ForkIssues/Tracker#2070]
In the commit view under "All commits" I used the parent hashes to quickly navigate to previous commits.
<img width="420" alt="Bildschirmfoto 2024-02-20 um 10 57 53" src="https://github.com/fork-dev/Tracker/assets/17045396/149ae08b-3ed0-4215-b387-28f07b7cdc50">
But clicking on them now  (version 2.40) just opens a popup.
How can I jump to previous commits now?
If not possible, can you revert to the old behavior, please?

Kindly, craftey

**Comment by craftey** [comment]
Actually, using arrow keys instead of mouse for that purpose would be perfect. Atm arrow keys jump to previous commits over all branches. I would prefer to jump along a branch.

**Comment by DanPristupov** [comment]
Try https://cdn.fork.dev/mac/Fork-2.40.2.dmg

**Comment by craftey** [comment]
Click to jump works again. Thank you.

As feature request, I would like to have some key commands for this. Maybe as menu entry, so I could use macOS keyboard settings to set a shortcut myself. I know it might be difficult because merge commits have two parents.
And branches of a commit have two or more(!) childs.

Maybe jumping via shortcut forwards and backwards along the "default" branch typically "develop" or "main" would be useful for me. You could maybe use some heuristic based on branch names and the gitflow setup if initialized to detect the "default" branch or you can somehow ask the server, what the default branch is.

Of course, within a feature branch jumping would also be nice. Here maybe the active branch could be used to determine the branch along which the jumping goes.

But I really would like to jump along the "default" branch even if the current branch is some other (feature) branch.
That would be the most important shortcut for me.

**Comment by DanPristupov** [comment]
> But I really would like to jump along the "default" branch even if the current branch is some other (feature) branch.

You can press `left`

**Comment by craftey** [comment]
Some brainstorming, what about this:
If on a merge commit:
- down arrow jumps to left parent


If on a commit that branches:
- up arrow jumps to left child


within a branch (not on a merge commit):
- up and down just follow the branch

A:
- right arrow jumps to right parent of nearest child merge commit, if we are not already in that branch
- left arrow jumps to left parent of nearest child merge commit, if we are not already in that branch

if there is no child merge commit:
B:
- right arrow jumps to next right child commit of nearest parent commit that has sub branches
- left arrow jumps to next left child commit of nearest parent commit that has sub branches

The only difficult situation left is a loop in the graph. Here I have currently no other idea as to prefer rule A or B. I would go with A. 

A combination of A and B might be possible:
right arrow - like rule A + if there is no more right parent of nearest child merge commit (rule A) then we could switch to rule B.
left arrow - accordingly

**Comment by craftey** [comment]
> You can press `left`

Oh, interesting. It sort of hides the right parent branch on a merge commit and changes the minus to a plus on the merge commit. But how does this help me jump to parent commits along branches? My preferred topology sorting is by date, if that matters.

**Comment by craftey** [comment]
I see what might be your idea. Left arrow in combination with hiding all branches except the one I am interested in, this somewhat works. I am looking here into a repo with many long running branches.
But if other branches are visible, left arrow is not enough. Also if I just want to jump to parents I have to left-collapse all these commits on the way down and after that I have to undo this for all collapsed merge commits.

**Comment by craftey** [comment]
Actually, you already have some quite good heuristic to detect what commits might belong to a long running branch over time. The colors. Only in rare cases the color changes within a long running branch. So if up and down would follow the colored line, that would be quite helpful. Maybe some modifier key + up and down.

**Comment by craftey** [comment]
https://gitup.co does an ok job when it comes to navigating nodes in the branch tree with arrow keys. It is not perfect but maybe you can do something better. The goal is to be able to navigate along branches with up and down and somehow switch to sibling branches with left and right - in a date sorted tree (actually it can be a graph with cycles).
