### ISSUE TITLE
Create and Push button in Create Tag window can be clicked twice

### ISSUE THREAD

**Issue by vbezhenar** [ForkIssues/Tracker#2072]
Open any repository, choose `Repository`/`New Tag...`. In the dialog window type `Tag name`, check `Push to all remotes` and click `Create and Push`. Tag is created and push to the remote repository started. At this moment button `Create and Push` should become disabled. However it is not disabled and user can click it second time causing weird errors.

I'm using macOS version 2.40.2

**Comment by DanPristupov** [comment]
Fixed in Fork 2.41
