### ISSUE TITLE
Commit messages not shown in "All Commits" tab

### ISSUE THREAD

**Issue by mskri** [ForkIssues/Tracker#2075]
Updated Fork to 2.40.2 and the commit messages from the past month or so are not shown in the UI. Later commits from early January _(before Jan 10th)_ do show up.

Had to downgrade all the way down to version 2.37 to have the commit messages appear again. Not sure what could be the cause. Changing theme didn't have any effect. Not all of the repositories I have open have the issue.

With version >2.37 the commits look like this
![commits](https://github.com/fork-dev/Tracker/assets/2499987/b1d82e5c-7405-499d-8cb4-f980360055e5)

**Comment by DanPristupov** [comment]
Did you enable `git maintenance? https://github.com/fork-dev/TrackerWin/issues/2147#issuecomment-1953627592

**Comment by mskri** [comment]
> Did you enable `git maintenance? [fork-dev/TrackerWin#2147 (comment)](https://github.com/fork-dev/TrackerWin/issues/2147#issuecomment-1953627592)

Yes, the problematic repositories do have git maintenance enabled.

**Comment by DanPristupov** [comment]
I can't reproduce the problem myself.

If you didn't disable git maintenance yet, can you confirm that the following build fixes the problem?

https://cdn.fork.dev/prerelease/Fork-2.40.4.dmg

**Comment by LarsEckart** [comment]
sorry, should have had a more thourough look at the existing issies. I just filed a report through the app about exactly this issue. I installed 2.40.4 and it now displays again correctly all info as before.

**Comment by mskri** [comment]
> I can't reproduce the problem myself.
> 
> If you didn't disable git maintenance yet, can you confirm that the following build fixes the problem?
> 
> https://cdn.fork.dev/prerelease/Fork-2.40.4.dmg

Can confirm that in my case the new version displays the commit messages 👍

**Comment by Bombe** [comment]
This issue still occurs for me (macOS 13.6.7, Fork 2.43.1). The log file shows:

> ❌[BtResultExtensions.swift:33] > Bt error: Failed to read stashes in '/Users/bombe/Workspace/jFCPlib/.git': Cannot open object db '/Users/bombe/Workspace/jFCPlib/.git': Failed to open .idx file '/Users/bombe/Workspace/jFCPlib/.git/objects/pack/pack-33d9ee8860dd6eabcf1cfd98358e5d2c9ab4e546.idx': v1 .idx is not supported

So far, neither `git gc` (with `--aggressive` and/or `--prune`) nor `git repack` have been able to remedy the situation. `git maintenance` is not enabled on the repository.

**Comment by DanPristupov** [comment]
@Bombe 

1. Run `git index-pack`

2. It `git index-pack` doesn't help, please check if `/Users/bombe/Workspace/jFCPlib/.git/objects/pack/pack-33d9ee8860dd6eabcf1cfd98358e5d2c9ab4e546.idx` looks like a valid index.
- it must not be empty
- there must be a pair **.pack** file at `/Users/bombe/Workspace/jFCPlib/.git/objects/pack/pack-33d9ee8860dd6eabcf1cfd98358e5d2c9ab4e546.pack`.

If it's empty, make a backup and simply remove it.

**Comment by Bombe** [comment]
Running `git index-pack .git/objects/pack/pack-33d9ee8860dd6eabcf1cfd98358e5d2c9ab4e546.pack` fixed the problem. The `.idx` file looked like a valid index, I guess (no idea what it should look like, actually), it was 13736 bytes in size before `index-pack`, and 15856 bytes after `index-pack`. There was a `.keep` file present but no `.rev` file; after `index-pack` the `.rev` file has been created but the `.keep` file is still there.

My problem is solved, thank you! (If you need the repository For Science™, it’s an open source project and can be shared in its whole glory.)

**Comment by DanPristupov** [comment]
@Bombe I'm glad you made it work ☀️. Thank for sharing the details 👍. I don't need link to the repo.
