### ISSUE TITLE
Commit history disappeared

### ISSUE THREAD

**Issue by jnb-ableton** [ForkIssues/Tracker#2076]
Hi! 

Since this morning, Fork's commits view only displays the very last few commits in the history, and most of the git tree has disappeared.  
Some branches are not visible at all.

I have checked that everything shows normally in other git clients (Gitk), and also tired removing the cache, application support files, and preferences (I am on a Mac). I updated Fork to the latest (2.40.3) just in case, with no luck.

Everything worked just fine yesterday. I am a bit clueless about what went wrong and what to do. Is this a know issue? (this looks like possibly related to https://github.com/fork-dev/Tracker/issues/1401)

Thanks!

**Comment by DanPristupov** [comment]
<img width="471" alt="Screenshot 2024-02-28 at 10 06 28" src="https://github.com/fork-dev/Tracker/assets/618115/393b583f-f690-4100-b62a-deee33616fb2">

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/Tracker/issues/2075#issuecomment-1964453460

**Comment by jnb-ableton** [comment]
Sorry I should have mentioned I also tried 2.40.4 after reading that thread but it didn't solve the issue for me.

**Comment by jnb-ableton** [comment]
(In my case this is not about commit messages as in the other ticket, but the the actual commit history)

**Comment by DanPristupov** [comment]
> In my case this is not about commit messages as in the other ticket, but the the actual commit history

Can you show a screenshot, please? Or can you send it (and blur sensitive info) to support@fork.dev?

Do you use branch filter on the sidebar? Is it possible you set filter (or hide) some branch?

**Comment by jnb-ableton** [comment]
> Do you use branch filter on the sidebar? Is it possible you set filter (or hide) some branch?

Yes, I do use filters a lot. Without a filter I see some of the repository (but not all of it). With filters I see what seems to be the very late history of filtered ranches (1 day or so), or nothing.

**Comment by jnb-ableton** [comment]
Here is an example of how it looks (history cut earlier than today)

<img width="598" alt="Screenshot 2024-02-28 at 10 50 55" src="https://github.com/fork-dev/Tracker/assets/59610912/1f6a9588-e3d3-4653-88ec-a6e29296e8e6">

**Comment by DanPristupov** [comment]
I see now. Yes, you was right suspecting #1401.

Did you try to increase the max commit count in the command line?
Please notice that the command must be `defaults write com.DanPristupov.Fork maxCommitCount 150000`, i.e. the capitalization is important.

**Comment by jnb-ableton** [comment]
Ha! I did try that but indeed, had the captitalization wrong! That seems to do the trick! 

I am wondering why this suddenly happened today though, and why only the _very_ top of the history remained visible like this 🤔

**Comment by DanPristupov** [comment]
> I did try that but indeed, had the captitalization wrong! That seems to do the trick!

MacOS changed behavior recently. Previously it was case-insensitive. I updated the capitalization in the original post you mentioned, so it wasn't your fault.

> I am wondering why this suddenly happened today though, and why only the very top of the history remained visible like this 

Someone pushed a lot of commits to some other branch, I guess.

BTW, we are going to increase the default limit soon. Internally Fork becomes faster and now we can afford it :).

**Comment by jnb-ableton** [comment]
Thanks a lot. Fork is great!

**Comment by mju-ableton** [comment]
Indeed, fork is great! Thanks for providing the above solution!

**Comment by DanPristupov** [comment]
In Fork 2.41 we increased the commit limit from 50,000 to 100,000 commits. If you changed the limit manually, no additional action is needed.

**Comment by kuthair** [comment]
Hello,

I'm having this same problem where the commit messages are not displaying.

I am using Fork version 2.41.2.

Also, I checked total number of commits in this repo:

`$ git rev-list --all --count`
`1480`

No where near the 50k limit mentioned above.

**Comment by DanPristupov** [comment]
@kuthair it's a different problem. It's https://github.com/fork-dev/Tracker/issues/2075. Please send me the log `~/Library/Logs/Fork.log` to support@fork.dev.

**Comment by kuthair** [comment]
> @kuthair it's a different problem. It's #2075. Please send me the log `~/Library/Logs/Fork.log` to [support@fork.dev](mailto:support@fork.dev).

Ahh ok, I saw that other one too, but I wasn't sure which one to post under. Thanks.
