### ISSUE TITLE
[Feature Request] Hide branches in the commit list by regex

### ISSUE THREAD

**Issue by magauran** [ForkIssues/Tracker#2078]
It is now possible to hide either a specific branch or a folder in the commit list.
It would also be great to be able to hide all branches that satisfy the regular expression, instead of hiding each branch manually.

**Comment by DanPristupov** [comment]
You can hide folders. Regex is too complex and probably won't appear in the near future.

**Comment by DanPristupov** [comment]
I think it's a duplicate of https://github.com/fork-dev/Tracker/issues/614

**Comment by magauran** [comment]
Yes, I can hide folders. But some repositories have hundreds of branches that don't use folders. And I have to hide them all manually to be able to use the commit list.
Keeping only the active branch doesn't help either, as I want to see all the commits from my team (with a specific prefix).

**Comment by DanPristupov** [comment]
> I want to see all the commits from my team (with a specific prefix).

You can set filters on their folders.

**Comment by magauran** [comment]
Filters work for my case. Thanks!
