### ISSUE TITLE
Lost remote branch after update

### ISSUE THREAD

**Issue by codeWillwillCode** [ForkIssues/Tracker#208]
![](https://i.loli.net/2018/02/02/5a7413f614f35.png)
![](https://i.loli.net/2018/02/02/5a74147be201e.png)

**Comment by codeWillwillCode** [comment]
1.0.63

**Comment by Li-HaoYuan** [comment]
Me too. Anyone has 1.0.62 installation package here?

**Comment by DanPristupov** [comment]
@codeWillwillCode could you send me the log to support@git-fork.com please? The log file is located at ~/Library/Caches/Fork/fork.log. Then I'll be able to solve your problem ASAP. Thank you.

**Comment by DanPristupov** [comment]
I just released the hotfix build (Fork 1.0.63.**1**). Could you please check for updates and confirm that everything works again.

Sorry for the inconvenience guys.

**Comment by robdecker** [comment]
Still broken on 1.0.63.2

Origin info:
```
[remote "origin"]
	url = user@svn-12345.prod.hosting.acquia.com:reponame.git
	fetch = +refs/heads/*:refs/remotes/origin/*
	pushurl = user@svn-12345.prod.hosting.acquia.com:reponame.git
	pushurl = git@github.com:username/repo.git
```

**Comment by codeWillwillCode** [comment]
It's works , problem solved ! @DanPristupov

**Comment by DanPristupov** [comment]
@robdecker released 1.0.63.3. Please check for updates.

I apologize for these bugs. I had to rework remote-related code to be able to move toward fulfilling support for GitHub Enterprise / GitLab Enterprise (https://github.com/ForkIssues/Tracker/issues/199).

**Comment by robdecker** [comment]
@DanPristupov 1.0.63.3 fixed my issue. Thanks!

**Comment by DanPristupov** [comment]
@robdecker awesome! Gonna sleep well tonight :).
Thank you to everyone!
