### ISSUE TITLE
[Enhancement] Links to Azure Dev Ops work items in the UI

### ISSUE THREAD

**Issue by cnovel** [ForkIssues/Tracker#2080]
![image](https://github.com/fork-dev/Tracker/assets/5690282/98ba5199-09ba-4f59-babd-12a46ea29b64)

When the default origin is an Azure DevOps URL (eg https://dev.azure.com/{orgName}), if related work items are mentioned in the commit, create a link to the work items (eg https://dev.azure.com/{orgName}/_workitems/edit/1367697).

**Comment by DanPristupov** [comment]
In can configure that in Repository -> Settings for this repository -> Issue Tracker

**Comment by cnovel** [comment]
It's already the case:
![image](https://github.com/fork-dev/Tracker/assets/5690282/faa7376b-790d-48e3-911b-4ddb096cf634)

**Comment by DanPristupov** [comment]
The list is empty. Press '+' and add a rule for your server.

**Comment by cnovel** [comment]
OK, I was able to add the links to the work items! Thanks!
