### ISSUE TITLE
[Feature Request] Allow Fork to point to a symlink for custom commands

### ISSUE THREAD

**Issue by oehm** [ForkIssues/Tracker#2081]
I use fork on multiple windows machines. i would like to be able to sync my custom commands between machines. This could easily be done by storing the `custom-commands.json` in some sort of cloud storage (e.g. Google Drive) and creating a symlink to that file in `AppData/Local/Fork`. However when I try this, Fork overwrites the symlink with a local file, as soon as I do changes to my custom commands through the fork ui.

it would be greatly appreciated to have this work, or if anybody has another idea how to sync custom commands between machines.

Similar resolved issue:
#116 

PS: I love Fork, thank you for this great project. first git ui that I actually enjoy using!

**Comment by DanPristupov** [comment]
> Allow Fork to point to a symlink for custom commands

I think this is very unsecure.

> if anybody has another idea how to sync custom commands between machines.

Store custom commands in the repository: `Repository -> Settings for this Repository -> Custom Commands -> Share`

**Comment by oehm** [comment]
Thank you for your quick reply!

> Store custom commands in the repository: Repository -> Settings for this Repository -> Custom Commands -> Share

I see, never found this option before. It is nice feature, but not quite what fits my use case. Per repository sharing requires the commands to be in source control of the project, which is not desired. Also many team members do not use fork or have their own custom commands. Also this creates duplicates when the same command is defined in my `AppData/Local/Fork/custom-commands.json`

> I think this is very unsecure.

can you elaborate? I use the same setup to share configs for other software e.g. Visual Studio Snippets

**Comment by DanPristupov** [comment]
> > I think this is very unsecure.

> can you elaborate? 

If custom command would be owned by someone else, it could be remotely modified to perform something bad.

This is not an unfounded concern. There was a similar vulnerability in git: 

https://stackoverflow.com/questions/73485958/how-to-correct-git-reporting-detected-dubious-ownership-in-repository-withou
https://github.blog/2022-04-12-git-security-vulnerability-announced/
