### ISSUE TITLE
[Feature Request/Bug] Enhance Commit Log Filter to preserve color coding for Non-Active branches

### ISSUE THREAD

**Issue by ttphi88** [ForkIssues/Tracker#2082]
Hi, thank you for developing the Fork app; it's an amazing piece of software.

I'm not sure if this qualifies as a bug or a feature request. Let me explain.

(I'm using Fork version: 2.39.1)

Without the filter, the commit logs are displayed as follows:
The current active branch is `feature-1`, so Fork renders the commits not belonging to this branch in grey color (for example, commits `f2-1, f2-2`).
![Screenshot 2024-03-07 at 16 17 02](https://github.com/fork-dev/Tracker/assets/3007734/3d5eb93d-4f26-4469-9d01-eca1c57ce336)

However, when I activate the filters, the grey commits compared with the active branch no longer appear.
![Screenshot 2024-03-07 at 16 17 08](https://github.com/fork-dev/Tracker/assets/3007734/d512d243-085c-43d8-862e-d4dff50e6549)

What I would like is to have the grey commits feature working when using the filters, as I'm using it to compare two branches to see which commits are missing from the active branch.

The current workaround is to use the "eye" icon to hide all other branches, as shown here (I'm comparing `feature-1` & `feature-2`):
![Screenshot 2024-03-07 at 16 17 14](https://github.com/fork-dev/Tracker/assets/3007734/9fbba88c-0534-4c93-ba64-e18407f38415)

However, this method is quite troublesome when the repo contains many branches.

May I ask if this issue could be considered for a fix or enhancement? Thank you for your attention to this matter.

**Comment by DanPristupov** [comment]
We will have a look

**Comment by DanPristupov** [comment]
In 2.41 Fork will colorize unreachable commits when active branch is included into filter.
