### ISSUE TITLE
Specify commit message for merge

### ISSUE THREAD

**Issue by skjardenCode** [ForkIssues/Tracker#2083]
While using the rebase workflow, I often merge my work into our main branch via "No Fast-Forward". After that, I amend my commit to edit the commit message.

Is there a way (or would you implement it) to specify the commit message for the merge commit, so I do not have to amend my merge commit?

Thanks a lot for your help!

**Comment by DanPristupov** [comment]
If you select 'No-commit', you will be able to edit the merge commit message.
<img width="591" alt="Screenshot 2024-03-07 at 15 02 24" src="https://github.com/fork-dev/Tracker/assets/618115/a8c775ce-b0d5-44d6-8e1e-8563e89f976e">

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/Tracker/issues/488
https://github.com/fork-dev/Tracker/issues/1821
