### ISSUE TITLE
[Feature request] Custom hyperlink in commit message

### ISSUE THREAD

**Issue by dangh** [ForkIssues/Tracker#2084]
Hello,

It would be great to have a way to add custom linking to other tracking system apart from GitHub issue. We're using Notion and would love to link to our Notion project board with their [unique ID](https://www.notion.so/help/unique-id). Would save us bunch of time searching in Notion app.

In our case, it will be as simple as
- Looking for pattern `TASK-<number>`
- Link it to `https://notion.so/TASK-<number>`

**Comment by DanPristupov** [comment]
Repository -> Settings for this repository -> Issue Tracker

**Comment by dangh** [comment]
OMG didn't know it exist. Thank you so much.
