### ISSUE TITLE
[Feature Request] Add an option to skip Git hooks

### ISSUE THREAD

**Issue by VasylRomanets** [ForkIssues/Tracker#2085]
Hi, thank you for developing the GitFork, my favourite Git client.

I'd like to request a couple of enhancements:
1. An option to bypass the _pre-commit_ hook when committing.
<img width="718" alt="Screenshot 2024-03-11 at 13 26 02" src="https://github.com/fork-dev/Tracker/assets/23483473/e880277c-da4f-40ed-9b18-db189b83b5f6">

2. An option to bypass the _pre-push_ hook when pushing.
<img width="500" alt="Screenshot 2024-03-11 at 13 30 38" src="https://github.com/fork-dev/Tracker/assets/23483473/ee559aab-5557-42e8-b0b5-494cc9576772">

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/Tracker/issues/1239

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/Tracker/issues/2056
https://github.com/fork-dev/Tracker/issues/1239
https://github.com/fork-dev/Tracker/issues/948
