### ISSUE TITLE
parseError(error: "Cannot parse patch for 8545c4c")

### ISSUE THREAD

**Issue by leonhsieh** [ForkIssues/Tracker#2089]
Enviroment: Xcode 15.2, Fork version is 2.40.3
Issue: 
Commits section  shows _parseError(error: "Cannot parse patch for 8545c4c")_ after useing rescan repository feature
Newly committed node also unable to fetch git information.
![image](https://github.com/fork-dev/Tracker/assets/9204506/8865884a-398c-404d-a705-60fc6d7fa109)
![image](https://github.com/fork-dev/Tracker/assets/9204506/478578a9-ca3d-4d74-ae8a-3289a78f67db)

In terminal, the committed state is detached, but nothing can commit.
<img width="794" alt="image" src="https://github.com/fork-dev/Tracker/assets/9204506/e3cb3c38-61fe-4df7-a5e6-d1a57049e6d6">

**Comment by DanPristupov** [comment]
Do you use custom diff drivers? Check the `.gitattributes` file
