### ISSUE TITLE
Can't type '[' character in branch name

### ISSUE THREAD

**Issue by tibmanus** [ForkIssues/Tracker#209]
1. Try to create a new branch
2. Try to type `[` in the name field.

Expected result: `[` appears in branch name field
Actual result: `[` cannot be typed in branch name field

Additional info: all our branches tagged with a manner `[tag]`.

**Comment by DanPristupov** [comment]
@tibmanus as far as I know `[` is NOT a valid symbol for branch/tag.

**Comment by tibmanus** [comment]
Yep, overlooked this.
Looks like we're using a non-standard implementation.
