### ISSUE TITLE
[feature request] Could you please show the full path in the title bar?

### ISSUE THREAD

**Issue by JeroldLiu777** [ForkIssues/Tracker#2093]
<img width="424" alt="image" src="https://github.com/fork-dev/Tracker/assets/14341614/a3583a0a-dc25-484a-932e-e3a422b0095d">

Could you please show me the full path in this place?

Because I duplicated 4 projects, but I can't tell which project it is right now.

**Comment by DanPristupov** [comment]
Rename them
<img width="450" alt="Screenshot 2024-03-22 at 8 20 31" src="https://github.com/fork-dev/Tracker/assets/618115/5c9afdcf-73ac-4266-896e-3350eb2a3bee">
