### ISSUE TITLE
Adding a file or pattern to .gitignore doesn't refresh the Unstaged section

### ISSUE THREAD

**Issue by chsxf** [ForkIssues/Tracker#2095]
Adding a file or pattern to `.gitignore` doesn't refresh the **Unstaged** section.
It was working fine at some point, but now I have to manually refresh (Cmd+R) for the **Unstaged** section to clean itself.

Experienced on macOS, in version 2.40 and previously two or three versions before that.

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/Tracker/assets/618115/4eb0b393-6eed-4c20-bcbf-7f8ed3e20e13

**Comment by DanPristupov** [comment]
Ah, OK. You probably meant the 'Custom Pattern...' dialog

**Comment by chsxf** [comment]
Sorry, I thought the problem occured with every command, but it seems I've only encountered it with "Ignore All Files in ..." commands.

https://github.com/fork-dev/Tracker/assets/3322862/7f1babd8-0105-4e18-ab9b-872499f97127

**Comment by DanPristupov** [comment]
Fixed in 2.42 👍

**Comment by chsxf** [comment]
Thank your very much. I confirm version 2.42 fixes the issue 👍🏼
