### ISSUE TITLE
Git message not shown

### ISSUE THREAD

**Issue by PyGeek03** [ForkIssues/Tracker#2097]
One day, Fork suddenly stops showing git messages in a repo I've been working heavily in. My suspicion is that this is because I have quite a few stashes (10) and local branches (21) in this repo, because when I checked out a fresh copy of the same repo to another directory, Fork has no issue displaying git messages for that directory.

![image](https://github.com/fork-dev/Tracker/assets/16066807/0c6c678b-2d2f-4f9e-8744-115f949dbd50)

**Comment by DanPristupov** [comment]
What version do you use?

https://cdn.fork.dev/mac/Fork-2.41.1.dmg

**Comment by PyGeek03** [comment]
I was using 2.39.1. Looks like 2.41.1 has fixed that issue, thanks!
