### ISSUE TITLE
Add Bitbucket account with OAuth authentication error on macos

### ISSUE THREAD

**Issue by stiacs** [ForkIssues/Tracker#2099]
App version 2.41.1 for Macos.

Add new Bitbucket account. 
When asked for authentication - select "Log in on Bitbucket.org (OAuth)".

There is error at the end after successful login which is shown in popup "browser" :
```
Invalid redirect_uri
This integration is misconfigured. Contact the vendor for assistance.
```

**Comment by DanPristupov** [comment]
Thank you

**Comment by DanPristupov** [comment]
I'm releasing hotfix

**Comment by DanPristupov** [comment]
Can you check if the problem is resolved in https://cdn.fork.dev/mac/Fork-2.41.2.dmg?

**Comment by stiacs** [comment]
Hotfix works fine.

Thank you for quick fix.
