### ISSUE TITLE
Kaleidoscope support?

### ISSUE THREAD

**Issue by cdzombak** [ForkIssues/Tracker#21]
I notice Fork supports FileMerge and Beyond Compare (in the "Integrations" prefs).

Is it possible to add support for [Kaleidoscope](http://www.kaleidoscopeapp.com/)?

**Comment by DanPristupov** [comment]
Yes, it's possible. I'm going to add it when I finish interactive rebase.

**Comment by cdzombak** [comment]
Cool, thanks! It's not urgent at all, but would be nice to have.

**Comment by DanPristupov** [comment]
I've added Kaleidoscope support in Fork 1.0.45.

**Comment by cdzombak** [comment]
Cool; thank you!
