### ISSUE TITLE
Window with all repos and statuses like Sourcetree

### ISSUE THREAD

**Issue by dmorel** [ForkIssues/Tracker#2101]
I love Fork and use it all day, but there's one thing i'm missing which is a window like in Sourcetree which shows:

- all repos
- which branch is currently checked out
- indicators for git status
- ability to open a new window or tab just clicking on the name

Fork has the repos listed in a new tab, but afaict not all the information like mentioned above. If it did, it would be the perfect git client (since it's already the best in my opinion)

**Comment by DanPristupov** [comment]
Duplicate https://github.com/fork-dev/Tracker/issues/379
