### ISSUE TITLE
Repository manager is absent from top level menus on macOS

### ISSUE THREAD

**Issue by virtualzavie** [ForkIssues/Tracker#2105]
Hello,

While browsing to resolve a technical issue, I learned in in #710 that there is a Repository Manager screen, available from the shortcut Cmd+T.
As far as I can tell and unless I missed something, this screen is not available in any of the top level menus.

I would suggest to add an entry to access it from:
- The "Repository" menu
- The repository settings dialog

**Comment by DanPristupov** [comment]
Use File -> New Tab

**Comment by virtualzavie** [comment]
Oh, I'd never used that one, and given the name I didn't notice it when searching for the repository manager.
Sounds good enough then. :)
