### ISSUE TITLE
[Feature Request] Ability to Amend Commit Date during Rebase

### ISSUE THREAD

**Issue by Valgard** [ForkIssues/Tracker#2109]
Hello Fork Development Team,

I'm an active user of the Fork Git client and appreciate its user-centric design. I'm proposing a potential enhancement: the ability to amend the commit date during a rebase.

This feature draws inspiration from Git's native functionality, which allows users to modify the date of a commit using `git commit --amend --date`, for instance `git commit --amend --date="Wed Feb 16 14:00 2024 +0100" --no-edit`.

Including this feature into the Fork GUI would offer a more comprehensive Git experience, allowing users to maintain precise commit histories and manage project timelines effectively, particularly when needing to correct inaccurate commit dates or align project timelines accurately.

Thank you for considering this request. Looking forward to your thoughts and the continued evolution of the Fork Git client!

Best regards

**Comment by DanPristupov** [comment]
No, I think including this feature into the Fork GUI would not offer a more comprehensive Git experience and will mess up and complicate the UI.
