### ISSUE TITLE
Trailing slash appended to HTTPS remote URLs on fetch/push

### ISSUE THREAD

**Issue by infotexture** [ForkIssues/Tracker#211]
Given a remote URL of `https://github.com/username/repo.git`, Fork fails to fetch or push with an error that suggests a spurious trailing URL is being appended to the URL:

```sh
remote: Repository not found.
fatal: repository 'https://github.com/username/repo.git/' not found
```

The URL configured in `.git/config` is correct (with no trailing slash), and other clients fetch & push successfully from the same repo.

Switching to the corresponding SSH URL `git@github.com:username/repo.git` works fine, so it looks like there's a bug in the HTTPS implementation.

**Comment by DanPristupov** [comment]
Hi.

I just tried to add a wrong remote and fetch in terminal. The trailing slash appeared in the output. It looks like this is a small bug in git error messaging.

So, It looks like Fork fails to fetch because of some other reasons. Please check that URL and credentials are correct.

**Comment by infotexture** [comment]
> The URL configured in `.git/config` is correct (with no trailing slash), and other clients fetch & push successfully from the same repo.

Since this repo config & credentials work everywhere else (including on the CLI), I assumed the trailing slash was being appended by Fork, but your example suggests it may be deeper in the Git plumbing.

🤔 _Puzzling…_

**Comment by DanPristupov** [comment]
Probably you have an old password or expired github session in your keychain.

You can do the following:
1. Delete `Fork.github.com.https` entry in KeyChain Access application.
2. Login to your GitHub account in Repository Manager in Fork.

Then Fork will either ask you for a password or use the GitHub outh session to authenticate you.

**Comment by infotexture** [comment]
Thanks, that seems to have solved the problem. 

After deleting the old keychain entry, Fork prompted me for username on the next push, and after supplying my personal access token in the password prompt, the OAuth session was re-created and push succeeded.

I'll close this issue now.

**Comment by voytenko-d** [comment]
> Probably you have an old password or expired github session in your keychain.
> 
> You can do the following:
> 
> 1. Delete `Fork.github.com.https` entry in KeyChain Access application.
> 2. Login to your GitHub account in Repository Manager in Fork.
> 
> Then Fork will either ask you for a password or use the GitHub outh session to authenticate you.

Thanks, this is solved my issue. Guide for macOs - [here](https://docs.github.com/en/github/getting-started-with-github/getting-started-with-git/updating-credentials-from-the-macos-keychain)

**Comment by vodis** [comment]
> Probably you have an old password or expired github session in your keychain.
> 
> You can do the following:
> 
> 1. Delete `Fork.github.com.https` entry in KeyChain Access application.
> 2. Login to your GitHub account in Repository Manager in Fork.
> 
> Then Fork will either ask you for a password or use the GitHub outh session to authenticate you.

Thanks, this is solved my issue. Guide for macOs - [here](https://docs.github.com/en/github/getting-started-with-github/getting-started-with-git/updating-credentials-from-the-macos-keychain)
