### ISSUE TITLE
[Feature Request] Ability to Amend Commit Author during Rebase

### ISSUE THREAD

**Issue by Valgard** [ForkIssues/Tracker#2110]
Hello Fork Development Team,

I'm an active user of the Fork Git client and appreciate its user-centric design. I'm proposing a potential enhancement: the ability to amend the commit author during a rebase.

This feature draws inspiration from Git's native functionality, which allows users to modify the author of a commit using `git commit --amend --reset-author` or `git commit --amend --author`, for instance `git commit --amend --author="John Doe <john@example.com>" --no-edit`.

Integrating this feature into the Fork GUI would enrich the overall Git experience, empowering users to preserve accurate commit histories and manage project timelines more effectively. This becomes especially significant when there is a need to rectify erroneous commit author details or properly align project timelines.

Thank you for considering this request. Looking forward to your thoughts and the continued evolution of the Fork Git client!

Best regards

**Comment by DanPristupov** [comment]
No, I think including this feature into the Fork GUI would not offer a more comprehensive Git experience and will mess up and complicate the UI.
