### ISSUE TITLE
[Feature Request] Combine changes in conflicting files within Fork

### ISSUE THREAD

**Issue by talon-i-am** [ForkIssues/Tracker#2111]
Hello,

I searched high and low and didn't see this feature, but if it exists please let me know!

When resolving merge conflicts, Fork gives you the option to Merge in Fork or Merge in External Tool. I have VSCode set as my external tool and it allows me to accept a combination of the 2 files with the option of accepting changes from REMOTE or LOCAL first.

I didn't see an any way to accept a combination of the 2 files when using the Merge in Fork option. It seems like you can only choose 1 file or the other. I was thinking it would be a nice feature to have in Fork rather than needing to open another application.

**Comment by DanPristupov** [comment]
> I didn't see an any way to accept a combination of the 2 files when using the Merge in Fork option

Just select left and right

https://github.com/fork-dev/Tracker/assets/618115/36720c94-1b0b-4c26-b7d2-6483bde73eb7

**Comment by talon-i-am** [comment]
Wow I feel stoooooopid 😳. Thanks for the video! This is why Fork is so dope! 🙏🏼
