### ISSUE TITLE
[Feature] Open repository in VSCodium

### ISSUE THREAD

**Issue by SimplyDanny** [ForkIssues/Tracker#2120]
Opening a repository in VS Code works well. [VSCodium](https://vscodium.com) isn't recognized and/or offered in the "Open in" menu, though.

Like the binary for VC Code is called `code`, VSCodium comes with `codium`. All the arguments passed should be understood by `codium` likewise.

Thank you for this awesome application!

**Comment by qwadrox** [comment]
@SimplyDanny Hi! You can use a custom command, btw. I made one for cursor. 


<img width="643" alt="image" src="https://github.com/user-attachments/assets/834e6807-b323-4128-99a9-7e08762d1850">
<img width="827" alt="image" src="https://github.com/user-attachments/assets/efe51b5e-ddd1-4ee2-a58b-615c0430794b">

**Comment by SimplyDanny** [comment]
> @SimplyDanny Hi! You can use a custom command, btw. I made one for cursor.

Good point! I'm using custom commands already, but this one didn't come to my mind.
