### ISSUE TITLE
"Rescan Repositories…" in context menu … wants to rescan wrong folder

### ISSUE THREAD

**Issue by tomi-engel** [ForkIssues/Tracker#2123]
I use Version 2.42.2 … and 

- when I bring up the context menu in the left side bar for one of the shown folders 
- and click "Rescan Repositories…" 
- Fork asks me if I want to rescan the "default repository folder"

This is not what I was expecting from the context menu item.

For me this is a "bug"  … or is this "by design"?

Aloha

**Comment by DanPristupov** [comment]
Well, you should say what you expected.

**Comment by tomi-engel** [comment]
Sorry for not being precise enough.

I would have expected that the command would only rescan the folder on which I "right-clicked" to get the context menu.

If it actually does that (which I did not try) then at least the alert panel is confusing to me, because it explicitly mentions another folder (the default repo as defined in the settings).

**Comment by DanPristupov** [comment]
> I would have expected that the command would only rescan the folder on which I "right-clicked" to get the context menu.

No, rescanning a particular folder is not possible. Folders in repo-manager are not tied to folders on disk. You can reorganize them, delete an create new ones. They are virtual.

Regarding the 'Rescan' option, we added it to the context menu to make it more discoverable because some users couldn't find 'Rescan repos' in preferences.

**Comment by tomi-engel** [comment]
Thank you for clarifying … I did not realise so far, that the folder hierarchy is not a fix mapping of the actual folders … but a free form tree that is based on the initial folder hierarchy derived from the initial opening of my repos.

**Comment by tomi-engel** [comment]
Thank you for clarifying … I did not realise so far, that the folder hierarchy is not a fix mapping of the actual folders … but a free form tree that is based on the initial folder hierarchy derived from the initial opening of my repos.
