### ISSUE TITLE
How to prevent sub-folder being created when cloning?

### ISSUE THREAD

**Issue by s22-tech** [ForkIssues/Tracker#2135]
I just downloaded Fork and cloned a repository.  When I did, a sub-folder was automatically created and all the files placed into it.  I didn't want them in a subfolder, so I moved all the files up one level to the folder I had selected for cloning and then deleted the subfolder Fork had created.

Naturally, Fork couldn't find the files after that. 

I was able to solve this using git via iTerm2 but I'd like to be able to do it directly in Fork.  How can I clone a repository directly into a folder of my choosing without Fork creating a subfolder?

Thanks,
Marc

P.S.  Beautiful app, btw!

MacOS 13.5
Fork 2.41.2

**Comment by DanPristupov** [comment]
> How to prevent sub-folder being created when cloning?

The Clone dialog allows to edit the location

**Comment by s22-tech** [comment]
OK, thanks.  I must have missed that.

Is there a way to fix it "after the fact", or will I need to delete it and start again?

**Comment by DanPristupov** [comment]
Move the repo on disk, then open the new location from Fork (or drag the folder to Fork).
