### ISSUE TITLE
Unable to sign commit with GPG

### ISSUE THREAD

**Issue by foux** [ForkIssues/Tracker#2138]
Hi there,

Any time I try to sign a commit with GPG, I've got the following error : 
```
$ git -c gpg.program=/Applications/Fork.app/Contents/Resources/gpg.sh commit --gpg-sign=xxxxx --file=/var/folders/j4/vgcg6c491wvg6nt84h5935lm0000gn/T/xxxxxxx

error: gpg failed to sign the data:
[GNUPG:] KEY_CONSIDERED xxxxxxxxxxx 2
[GNUPG:] BEGIN_SIGNING H8
[GNUPG:] PINENTRY_LAUNCHED 2109 curses 1.3.0 - - NONE - 501/20 0
gpg: signing failed: Inappropriate ioctl for device
[GNUPG:] FAILURE sign xxxxxxx
gpg: signing failed: Inappropriate ioctl for device

fatal: failed to write commit object
```

Any idea on how to solve this?
Thanks

**Comment by DanPristupov** [comment]
Did you install pinentry-mac?
https://github.com/fork-dev/Tracker/issues/1187#issuecomment-1466054071

**Comment by foux** [comment]
It works after adding pinentry-mac and `echo "pinentry-program $(which pinentry-mac)" >> ~/.gnupg/gpg-agent.conf` thanks!

Just FYI, as I had GNUPG tools installed prior ro Fork, I didn't get the message explaining about pinentry.
Thanks for your help!

**Comment by crstauf** [comment]
I followed the instructions, but my key isn't being listed in Fork. Restarted Fork a couple of times, no difference. Is there another step? I used GPG Keychain to create my key if that matters.
