### ISSUE TITLE
Show the "from" path in a commit which used git mv

### ISSUE THREAD

**Issue by clounie** [ForkIssues/Tracker#214]
(Found my way back to a Mac...more than a little due to missing Fork.)

For this area:
![image](https://user-images.githubusercontent.com/11947182/36121229-c6f9f67e-1002-11e8-967e-d87de0e58c99.png)

Fork shows me where I moved a file **to**, but not where it was moved **from**. Showing the "from" file somewhere in the commit view (whether in the diff or the file list) would be helpful.

**Comment by DanPristupov** [comment]
Hi.

I'll consider to show path for renamed/copied change types in the following way:
`server/oldfilename.js → server/newfilename.js`

It can be a bit too long though 🤔

**Comment by nebhale** [comment]
The too long problem exists in the console as well (with a wrap typically, I think).  Maybe an ellipses with a full-length hover-over if needed?

**Comment by clounie** [comment]
That or indent the "to" file or both.

**Comment by DanPristupov** [comment]
In 1.0.64 I updated the view to show previous path as well.

![2018-02-22 at 09 58](https://user-images.githubusercontent.com/618115/36528913-03e32450-17b7-11e8-8d98-a18b1b6e7ca7.png)
