### ISSUE TITLE
Check for updates doestn't see last version

### ISSUE THREAD

**Issue by Neon4eg** [ForkIssues/Tracker#2149]
I have Version 2.42.2 installed (MacOS) but latest version on fork website is 2.43 at the moment (available from May 17).   
<img width="237" alt="Screenshot 2024-06-10 at 11 05 02" src="https://github.com/fork-dev/Tracker/assets/603762/60411297-86fc-495a-b449-9a276eb2bdd2">

Also Download button on [websilt](https://fork.dev) links to 2.42.2.
I've noticed such problem pretty long ago

OS: MacOS 14.5
Fork: 2.42.2

**Comment by DanPristupov** [comment]
You switched Fork to stable update channel which is always delayed. Switch it back to develop if you want to see 2.43.
