### ISSUE TITLE
Mac: Doesn't handle multiple "desktop spaces" well

### ISSUE THREAD

**Issue by hipstersmoothie** [ForkIssues/Tracker#2150]
This started happening a few months ago. I have fork open 1 in 1 space. It insists on following me around though. If other windows are on top it will briefly appear on top then go below.

https://github.com/fork-dev/Tracker/assets/1192452/a434f4e2-f974-4e2c-b396-97956435f1b1

**Comment by DanPristupov** [comment]
Did you assign Fork to 'All Desktops' maybe?
<img width="394" alt="Screenshot 2024-06-12 at 18 32 34" src="https://github.com/fork-dev/Tracker/assets/618115/386ef48b-235e-44fb-8e9f-e90b90fe1556">

**Comment by hipstersmoothie** [comment]
I didn't know that was a thing 🤦 Thank you so much!
