### ISSUE TITLE
[Feature request] Pull to branch without checking it out

### ISSUE THREAD

**Issue by timmb** [ForkIssues/Tracker#2151]
<img width="312" alt="image" src="https://github.com/fork-dev/Tracker/assets/772105/63e929f4-0fb2-454a-a2ce-8fb7e88744d2">

On my project it's quite slow to switch branches as a lot of scripts run. I'm on branch X and I want to merge in main, but my local main is now 100 commits behind. I want to pull remote/main into main without having to check out main.

**Comment by DanPristupov** [comment]
Right click on a branch -> Fast forward.

However, like in your case, you can't merge branches which are unsynchronized without checkout, because it may lead to a conflict which must be resoled in the working directory.

**Comment by timmb** [comment]
Got it. I think I was reading that option as fastforwarding my currently active branch to that branch.
