### ISSUE TITLE
Reveal in ... context menu improvement

### ISSUE THREAD

**Issue by gitjoost** [ForkIssues/Tracker#2155]
There is "Reveal line in Visual Studio Code" in the diff view context menu. I most commonly use swift in Xcode so that VSCode doesn't do me any good. I you add a Custom Command with Target of this context menu that allows an action something similar:

open -a Xcode $path && osascript -e 'tell application "Xcode" to activate' -e 'tell application "System Events" to keystroke "l" using {command down}' -e 'tell application "System Events" to keystroke $line' -e 'tell application "System Events" to key code 36'

to be specified?  That may work with many (any?) other code editor.

**Comment by DanPristupov** [comment]
Duplicate https://github.com/fork-dev/Tracker/issues/1719
