### ISSUE TITLE
Auto-Complete filename in commit subject and description

### ISSUE THREAD

**Issue by mduu** [ForkIssues/Tracker#2162]
I finally moved over to Fork and really, really like it. I miss just one thing I would use in many of my commit messages so here is the feature-request:

When I write the commit message often it would be very helpful and less error prone if I can pick&insert a filename from the list of changed files. This would greatly improve efficiency and reduce the risk of typos.

Possible solutions to show what I mean:
- Allow to auto-complete (dropdown) changed files filenames in subject and description text inputs.
  <img width="450" alt="image" src="https://github.com/user-attachments/assets/1eaec770-ba21-42d3-bf31-f62f97f355de">

- Have a right-click menu-item on the changed file item called "Copy filename" (without the whole path). Can then be pasted into the commit message manually.
- Right-click on a changed file and "Insert filename into message".
- ...

I know and love the first option from other clients but other solutions will also do the job.

**Comment by DanPristupov** [comment]
> When I write the commit message often it would be very helpful and less error prone if I can pick&insert a filename from the list of changed files. This would greatly improve efficiency and reduce the risk of typos.

The shortest solution is to double click (or select) the filename in the file header and copy it.

https://github.com/user-attachments/assets/be03be2a-8c22-4d5e-a6db-1643f9bfe0f3

> Allow to auto-complete (dropdown) changed files filenames in subject and description text inputs.

It was like this before, but we removed it as it only works well for `.cs` and `.java` (where file names correspond the class names). For other languages ​​this is more likely to cause confusion.

**Comment by mduu** [comment]
Thanks a lot for the workaround. Will try it asap.

About auto-complete: my bad that I am mainly a .Net dev 😀. Joke aside: I think it should work for other eco-systems too. Maybe not auto-show it but only on keyboard shortcut. But then it's kind of a hidden feature - not a great UX. I get your point 😉
