### ISSUE TITLE
Fork is not using the custom Homebrew path

### ISSUE THREAD

**Issue by miku1958** [ForkIssues/Tracker#2163]
Fork is always use /opt/homebrew in its PATH, so after I customize the path in .zprofile, Fork can't use the hook that use application from homebrew correctly.

**Comment by DanPristupov** [comment]
Try to start Fork from the command line using `open -a Fork .` command. This way it will use path of the parent process.

**Comment by thomasrichner-oviva** [comment]
That works, though is far more annoying than just running `fork .`. Kinda kills the UX :)

**Comment by DanPristupov** [comment]
Now you can switch Fork to use ENV of the system shell (Fork -> Preferences -> Git -> ENV PATH)

**Comment by RickyRomeroAZ** [comment]
@DanPristupov Can you please clarify how this is supposed to work?:

```
➜  ~ echo $0
-zsh
➜  ~ which node
/opt/homebrew/opt/node@23/bin/node
➜  ~ node --version
v23.3.0
➜  ~ cat ~/.zprofile 

[...]

# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"

# Add Node 23 to PATH
export PATH="/opt/homebrew/opt/node@23/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/node@23/lib"
export CPPFLAGS="-I/opt/homebrew/opt/node@23/include"

# Add Android SDK to PATH for React Native compatibility
export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH="$PATH:$ANDROID_HOME/emulator"
export PATH="$PATH:$ANDROID_HOME/platform-tools"

# Add pipx packages to PATH
export PATH="$PATH:/Users/rickyrmo/.local/bin"

[...]
```

When pushing my code, I get this error on my pre-push hook. (I'm using [Husky.](https://typicode.github.io/husky/))

```
Pushing to ssh://[REDACTED]
env: node: No such file or directory
error: failed to push some refs to 'ssh://[REDACTED]'
```

**Fork > Settings > Git > ENV PATH** is set to **System shell '/bin/zsh'**, but it seems to fail no matter what setting I use. This setup worked before the recent changes around how the shell works. Just opening the project directory in Terminal and manually running `git push` works fine.
