### ISSUE TITLE
[Bug] Fork Freezes When Interactive Rebasing

### ISSUE THREAD

**Issue by mikemike396** [ForkIssues/Tracker#2164]
When I perform an interactive rebase the commit window shows a spinner and then the application locks up. Only way to get out of this is to force quite the application. I have tried different interactive rebase actions renaming, amending they all seem to produce the issue. Interestingly doing a single commit amend does not freeze the app. Any help would be appreciated!

<img width="1747" alt="Fork_Spinning" src="https://github.com/user-attachments/assets/5c979c5c-e8a3-4d55-8d33-459008e76e77">

**Version:** 2.44.6

**Comment by DanPristupov** [comment]
1. Try to reboot
2. Check if the log file has any errors. The log is located at `~/Library/Logs/Fork.log`.
3. Does normal rebase work?

**Comment by mikemike396** [comment]
> 1. Try to reboot
> 2. Check if the log file has any errors. The log is located at `~/Library/Logs/Fork.log`.
> 3. Does normal rebase work?

1. I have seen this issue for months even on older versions of the app. Was hoping it would get fixed in an update.
2. When I press rebase in the interactive window I get this in the logs. Nothing else the app just spins
   ```
   ◽️[RebaseInteractiveController.swift:280] > prepareTodoListForRebase received
   ```
3. Yes both the `branch rebase on` and `pull .. rebase checkbox` both work great!

**Comment by DanPristupov** [comment]
Can you check if interactive rebase works in command line? Try to run `git rebase -i <commit>`, then edit todo list in vim: mark some entries as 'fixup' and exit (`:wq`).


If it works in cli, then we can investigate this problem together with a help of debug build. It will take some time, though. Please contact me by email: support@fork.dev.

**Comment by mikemike396** [comment]
Worked via terminal. I'll send an email. Thanks!

> Successfully rebased and updated refs/heads/task/myBranch.

**Comment by mikemike396** [comment]
Closing this out, seems to have went away not 100% sure what the issue was.

**Comment by jbsilva** [comment]
This happened today with me on Fork Version 2.63.2 (Git: internal).
CLI works fine.

**Comment by mdekstrand** [comment]
Also hitting this problem, was doing a rebase with several rewords. I've never had a reword rebase work correctly.

Logs:

```
🔷[RefreshRepositoryCommand.swift:149] > Refresh 'lkpy' status. Updated (0 files)
◽️[RebaseInteractiveController.swift:277] > prepareTodoListForRebase received
❌[RebaseInteractiveController.swift:553] > IPC connection failed: POSIXErrorCode(rawValue: 50): Network is down
```
