### ISSUE TITLE
No information is returned after PUSH is successful

### ISSUE THREAD

**Issue by Alex-dengxz** [ForkIssues/Tracker#2165]
I have encountered a problem since yesterday: 
After the PUSH is successful, no return information is displayed (detail is empty). I checked the server and the PUSH is successful. At the same time, I can use the console to return the information correctly. 
It is worth mentioning that if there is an error in the submission, the error message can be output correctly.

I use custom commands to push: 
git symbolic-ref --short -q HEAD | xargs -I F git push origin HEAD:refs/for/"F"
This works great before.

**Comment by DanPristupov** [comment]
It's on Mac, right?

**Comment by Alex-dengxz** [comment]
Yes, macOS 14.5, M2

**Comment by DanPristupov** [comment]
Can you what I should do to reproduce the problem, please?
