### ISSUE TITLE
Allow Rename for Unpushed Commits

### ISSUE THREAD

**Issue by Saida-Lachgar** [ForkIssues/Tracker#2166]
### Problem

Currently, when I need to modify the merge commit message before i push, I have to resort to using amend in the terminal each time. 

### Proposed Solution

It would be beneficial to have a feature within Git Fork that allows users to rename merge commit messages for unpushed commits directly through the interface, without needing to use terminal commands.

_Thank you for considering this feature request._

**Comment by DanPristupov** [comment]
> Currently, when I need to modify the merge commit message before i push, I have to resort to using amend in the terminal each time.

The Local Changes view has the  'amend' checkbox

**Comment by Saida-Lachgar** [comment]
@DanPristupov Ahn nice, i thought am gonna find it in the context menu. thank you 🙏
