### ISSUE TITLE
gitlab server login  help

### ISSUE THREAD

**Issue by pengyucui** [ForkIssues/Tracker#2167]
![Snipaste_2024-07-22_15-09-15](https://github.com/user-attachments/assets/9a4d1874-5170-41ea-8296-1b312292e293)
this is git server Tower login ，I can success

**Comment by pengyucui** [comment]
![image](https://github.com/user-attachments/assets/86859dfa-7c0f-4a0d-a9aa-b454562ff243)
how use fork  login

**Comment by DanPristupov** [comment]
It's the same. Enter url and the token

**Comment by pengyucui** [comment]
@DanPristupov  but don't have username  。 I login fail

**Comment by DanPristupov** [comment]
Token authentication doesn't require username.

**Comment by DanPristupov** [comment]
Here is the GitLab API docs: https://docs.gitlab.com/ee/api/rest/#personalprojectgroup-access-tokens

> Example of using the personal, project, or group access token in a parameter:
> `curl --header "Authorization: Bearer <your_access_token>" "https://gitlab.example.com/api/v4/projects"`

There is no username in the request, only the token

**Comment by pengyucui** [comment]
@DanPristupov  use fork don't add username  is fail ，thorw error not found 404 https://******.com/api/v4/user  。Does this have anything to do with the gitlab server version?  i'm  user GitLab Community Edition 8.15.2  version

**Comment by DanPristupov** [comment]
> i'm user GitLab Community Edition 8.15.2 version

GitLab 8.15.2 It's almost 10 years old. It's possible the API was different back then.

You can't create an account in Fork then. However you can still fetch and push to the repos. When you fetch, a login/password prompt will appear.
