### ISSUE TITLE
No way to select default account on Mac

### ISSUE THREAD

**Issue by doug-a-brunner** [ForkIssues/Tracker#2170]
I have two different Bitbucket accounts registered in Fork. When working with a Bitbucket repo that doesn't have a username specified in its `origin`, Fork defaults to using the first Bitbucket account registered (highest in the Accounts list).

Unfortunately, there doesn't seem to be a way to re-order accounts to change the default. Dragging an account up or down just changes the one that's selected. It looks like I'd have to delete and re-create accounts to get the desired order. Could you add a button, drag support, or some other means to change the default?

I'm using Fork for Mac (2.44.4) on an M3 Max MacBook Pro (Nov 2023).

**Comment by DanPristupov** [comment]
> When working with a Bitbucket repo that doesn't have a username specified in its `origin`, Fork defaults to using the first Bitbucket account registered (highest in the Accounts list).

You can right click on `origin` on the sidebar, click 'Edit' in the context menu and select the account.
