### ISSUE TITLE
[Feature Request] Preselect "Close" when git commit reports an error

### ISSUE THREAD

**Issue by paulgessinger** [ForkIssues/Tracker#2173]
When git commit reports an error, for example because of a pre-commit hook, 99% of the time, I want to continue and update the commit to be compliant. The modal does not have buttons preselected, so hitting the enter key does not do anything.

It'd be awesome, if the enter key just dismissed the error modal.

**Comment by DanPristupov** [comment]
The close button is triggered by the escape key.

**Comment by paulgessinger** [comment]
Ha, I didn't think of trying that 😅

**Comment by DanPristupov** [comment]
On all macOS applications Enter key is bound to OK/Apply button and Escape to Cancel. I think Close is more like Cancel because it doesn't ask for an agreement neither confirm a change.
