### ISSUE TITLE
Can't edit tag name in "Create tag" dialog

### ISSUE THREAD

**Issue by homm** [ForkIssues/Tracker#2176]
For example, if I have cursor in `v9.2|.0.post0` position, I can't delete "2" char. I suppose this is because of tag name validation (there are not possible to have two dots ".."), but still it's very confusing that I just can't edit the name.

<img width="642" alt="Screenshot 2024-08-10 at 15 38 36" src="https://github.com/user-attachments/assets/c8b7955f-80c2-48db-9814-3f14f5f8d15d">

**Comment by DanPristupov** [comment]
> I suppose this is because of tag name validation (there are not possible to have two dots "..")

Yes, you right.

P.S. There is a similar issue already: https://github.com/fork-dev/Tracker/issues/1387

**Comment by DanPristupov** [comment]
This must be fixed in 2.46

**Comment by homm** [comment]
Thanks!
