### ISSUE TITLE
Custom command: `${repo:name}` not resolved in title of output window

### ISSUE THREAD

**Issue by tflo** [ForkIssues/Tracker#2177]
I have a couple of repository custom commands with the variable `${repo:name}` in their title, so that the actual repo name appears in the menu item and dialogue. (Visual feedback that I'm running the script on the correct repo).

This works fine for the menu item and the confirmation dialogue, but in the title and subtitle of the shell script's output window, the variable is not resolved, i.e. it appears as a literal string _${repo:name}._

This is a purely cosmetic problem.

Fork 2.44.3.

**Comment by tflo** [comment]
Seems to be fixed in 2.45.2. Thanks!

**Comment by DanPristupov** [comment]
Yes, it is. Thank you for the confirmation.
