### ISSUE TITLE
Auto generate commit messages

### ISSUE THREAD

**Issue by pdevito3** [ForkIssues/Tracker#2178]
i saw a git client come up a few weeks ago that could do this and i wish i remembered the name of it but it would be awesome if we could have fork automatically generate commit messages based on the file changes. even better, if it could have rules like adding a ticket number if in the branch name or starting the commit message with `feat` `fix` `build` etc

**Comment by DanPristupov** [comment]
Duplicate https://github.com/fork-dev/Tracker/issues/1886

**Comment by DanPristupov** [comment]
What you look for is probably https://gitbutler.com

**Comment by pdevito3** [comment]
Ah sorry I looked for dupes and didn't see this. 

Yeah it was gitbutler, thanks! But I do majorly love fork and would love to see it enhance our already awesome tool
