### ISSUE TITLE
Support for APNG

### ISSUE THREAD

**Issue by saket** [ForkIssues/Tracker#2180]
My company has started using APNG as a replacement of GIFs for recording animations of our UI, along with other screenshot tests in our project. Would `fork` be able to support APNGs by any chance? They're currently displayed as a single frame image.

**Comment by DanPristupov** [comment]
It uses the same `.png` extension, right? Or do you use `. apng`?

**Comment by DanPristupov** [comment]
https://en.wikipedia.org/wiki/APNG says that it uses the same `.png` file extension. I tried to put 
https://upload.wikimedia.org/wikipedia/commons/1/14/Animated_PNG_example_bouncing_beach_ball.png to a repo andFork displayed the preview.

P.S. Finder in MacOS behaves the same way: `.png` is recognized and `.apng` is not.

**Comment by saket** [comment]
Sorry I missed your comment. Here's an animated PNG that isn't displayed in fork: 
https://github.com/cashapp/paparazzi/blob/5b35dad3a89a5a37de5effdf165a69e71fb9b203/paparazzi/src/test/resources/simple_animation.png

**Comment by saket** [comment]
Woo! I'm able to see animated PNGs in the latest version of the app (2.59.2). The frame rate is slower than what it should be, but this is still a huge improvement.
