### ISSUE TITLE
[idea] offer to stash or delete changes when switching branches

### ISSUE THREAD

**Issue by mikemaccana** [ForkIssues/Tracker#2186]
I am currently moving between branches regularly, and fork tells me:

```
error: Your local changes to the following files would be overwritten by checkout:
	package-lock.json
Please commit your changes or stash them before you switch branches.
Aborting
```

I can fix this myself, but it would be easier if fork simply asked me what I wanted to do with my changes.

**Comment by DanPristupov** [comment]
Doesn't Fork propose this already?

<img width="520" alt="Screenshot 2024-08-20 at 22 27 13" src="https://github.com/user-attachments/assets/1f0103c5-9798-44ee-ba8e-df3c3af75a35">
