### ISSUE TITLE
[Feature] Option to hide Menu Bar icon

### ISSUE THREAD

**Issue by venomgfx** [ForkIssues/Tracker#2189]
Apologies if this exists but I couldn't find a way to hide the Fork icon in the top menu bar.

![menu bar](https://github.com/user-attachments/assets/33236db9-b613-43a2-9e0f-5a74eebba98e)

**Comment by DanPristupov** [comment]
Hi!

Fork -> Accounts -> GitHub -> Enable notifications in menu bar

**Comment by venomgfx** [comment]
> Hi!

Hi!

> Fork -> Accounts -> GitHub -> Enable notifications in menu bar

Oooh it is _per account_! I was looking in the Appearance settings or View menu

![Appearance](https://github.com/user-attachments/assets/6439e113-c14d-4f4d-a8c5-f2487b46dd17)
![View menu](https://github.com/user-attachments/assets/3119133e-7f90-493f-bd50-6f9bb64e8dec)

I think a global switch would be easier to find, and when having multiple accounts we don't have to go one by one disabling them all. But if I'm the only one who ran into it all this time then I'm just getting old.

Thank you so much for the swift response! 🧡
