### ISSUE TITLE
[Improvement request] Add a way to create the 1st worktree via the UI

### ISSUE THREAD

**Issue by lm2s** [ForkIssues/Tracker#2196]
Currently it's not possible (or at least not obvious) to add a worktree when there are none.

The worktrees section disappears when there are no worktrees which makes it impossible to create a new worktree via right click it.
And also it's not possible to create a worktree by right clicking in a branch.

The best IMO would be to have a "Create worktree" option when right clicking a branch. But always showing the Worktree section even if it's empty would also work.

**Comment by DanPristupov** [comment]
> Currently it's not possible (or at least not obvious) to add a worktree when there are none.

Repository -> Add Worktree.

> The best IMO would be to have a "Create worktree" option when right clicking a branch. But always showing the Worktree section even if it's empty would also work.

The majority of users don't need worktrees and I don't want to unnecessary complicate the UI for them.

**Comment by lm2s** [comment]
Don't know how I missed this menu entry.
Thanks for pointing it out and sorry for the noise.
