### ISSUE TITLE
Warning during push is treated as an error by Fork

### ISSUE THREAD

**Issue by lane-eden** [ForkIssues/Tracker#2197]
Hi, we use a redirect due to a proxy in front of GHES instance and I don't want to get this warning interrupting my workflow every time I push. When I push using the git command line, the warning prints but doesn't interrupt me:

```
>> git push
warning: redirecting to https://stash.vpn:1234/scm/org/repo.git/
Everything up-to-date
```

Unfortunately in stash, a modal pops up every time I push:

```
Git Error
An unexpected error occurred while performing the git request.

Error Details:
Pushing to https://git.vpn/org/repo.git
warning: redirecting to https://stash.vpn:1234/scm/org/repo.git
...
```

**Comment by DanPristupov** [comment]
> Warning during push is treated as an error by Fork 

No, it's not like that. Fork doesn't care about the output and handles the exit code instead. Warning is unrelated.

**Comment by lane-eden** [comment]
@DanPristupov I don't understand your response, the modal does pop up every time I push. This issue was about not popping up a modal for this redirect warning.

**Comment by DanPristupov** [comment]
> the modal does pop up every time I push

Check the exit code of your push. May be you have some hook which returns failure.

> This issue was about not popping up a modal for this redirect warning.

It doesn't matter if output contains warning, error or any other content. Fork doesn't read it. Fork only handles the process exit code.
