### ISSUE TITLE
Improve branch renaming

### ISSUE THREAD

**Issue by Turbo87** [ForkIssues/Tracker#2199]
I often use the `wip/` prefix on branches that are not ready for pushing yet. Once ready I use the "Rename local branch" dialog to rename them. As an example, I would rename `wip/some-feature` to `some-feature`. 

Unfortunately the software currently prevents me from putting the cursor at the start of the branch name and pressing the <kbd>Delete</kbd> key to remove the prefix. It works for the first to key presses, but at `p/some-feature` it stops working, supposedly because `/some-feature` would be an invalid branch name.

My suggestion: allow invalid branch names to be entered, but disable the "Rename" button until they are valid again.

**Comment by DanPristupov** [comment]
> My suggestion: allow invalid branch names to be entered, but disable the "Rename" button until they are valid again.

We implemented this in the 2.46 update.

**Comment by Turbo87** [comment]
great, thank you!

**Comment by lobsterkatie** [comment]
@Turbo87 - I do a similar thing with my branches. To make things easier, I've set up custom commands in the Fork preferences to make the branch-name changes I want.

![image](https://github.com/user-attachments/assets/757447a5-de6d-4dbe-8fb6-9d600f58292e)

![image](https://github.com/user-attachments/assets/0a93a5d2-045d-4345-a996-4e17ecf89889)

Then all I have to do is right-click on a branch and choose the relevant rename command at the bottom of the context menu:

![image](https://github.com/user-attachments/assets/1bfa4724-7278-4994-8e95-068891f87cdd)

![image](https://github.com/user-attachments/assets/7d194180-5106-46a4-9a65-e86242ecdb6a)

**Comment by Turbo87** [comment]
oh cool! thanks for the tip :)

**Comment by DanPristupov** [comment]
@lobsterkatie impressive! Thank you for sharing

As a side note, you could put all those 'Mark*' commands into a submenu using `/` in the name. E.g. `Mark branch/closed`, `Mark branch/draft PRed`, etc.
