### ISSUE TITLE
Delete Multiple Branches Support

### ISSUE THREAD

**Issue by mergesort** [ForkIssues/Tracker#22]
I don't know of any git client that does this, but I would love it if it was possible to highlight multiple branches, and press delete on them.

<img width="232" alt="branches" src="https://cloud.githubusercontent.com/assets/716513/25668916/0ec28202-2ff6-11e7-941b-460f5e681407.png">

Like in the layout above, it's always such a pain to have to click on each branch and delete one by one, even though they've gone stale.

There were a few questions raised, notably:

>Should we use --force-delete (otherwise non-merged branches won’t be removed)?

I think taking destructive action can lead to unintended consequences. I have a couple of suggestions as to how that could be handled.

Ideally I would want every branch that can be deleted safely to be deleted in this action.

For unsafe deletes, offer the user the option whether they want to delete non-merged branches. This can be done en masse, by deleting all the ones the user had selected, after they confirm that's what they would like to do, or better yet, an option to select which branches you'd still like to force delete.

A simpler approach after deleting all the safe ones would be to just say, we could not delete these non-merged branches and don't allow it because it's a potential destructive action.

I'm open to other ideas, those are just the ones that came to mind.

>Should we also implement this for remote branches and tags?

I would love it if this could be done for remote branches and tags as well. Currently navigating through GitHub isn't bad, but it would be ideal if I could handle it all without leaving Fork. I would say this is secondary though, and I wouldn't have it hold up doing it locally if it's a significant amount more work.

If there are other concerns, feel free to raise them as well.

Thanks a lot!

**Comment by DanPristupov** [comment]
This is a great proposal!

Here are my thoughts:

#### Delete multiple local branches when some of them are unmerged

There's an analogy in OS X when user work with a bunch of files.
![2017-05-03 at 21 23](https://cloud.githubusercontent.com/assets/618115/25677590/d8fd9368-3046-11e7-9ac1-dfce65b5df34.png)
For local branches we can show a warning dialog: `The branch X is not merged into HEAD. Do you really want to remove it?` Below should be the `Apply to All` checkbox and 3 buttons: `Skip`, `Stop`, `Delete`.

**Question**: the remove **local** branch dialog also allows to remove the corresponding remote branch. Do we need to enable this option when user deletes multiple branches?

#### Delete multiple remote branches.
This should be fine. However we need to improve the confirmation dialog and list all the branches which are going to be removed. The delete button must mention the number of branches which are going to be deleted (like "Delete 6 Remote Branches". That should be enough to avoid accidents.

I made a mockup:
<img width="556" alt="2017-05-03 at 21 43" src="https://cloud.githubusercontent.com/assets/618115/25678331/aad9648c-3049-11e7-8148-332e05ffee1c.png">

#### Delete multiple tags
Not sure here. Technically there's no problem.
Can this be harmful? Do we need to allow to remove tags from remote repositories?

**Comment by mergesort** [comment]
>Question: the remove local branch dialog also allows to remove the corresponding remote branch. Do we need to enable this option when user deletes multiple branches?

>Delete multiple remote branches.

I'd say by going off your mock up, you'd be able to combine both options into one. That could be the UI for deleting local branches, with a toggle to delete matching remote branches. If you're deleting only from the remote server, then you wouldn't need a toggle, and it would look just like your mock up.

>Delete multiple local branches when some of them are unmerged

I'd be ok with either the macOS style dialog, or alternatively the option to use the mock up you made as a basis, and allow the user to highlight/unhighlight rows containing branches they'd like to unselect. This would keep the overall UI more consistent with regards to deleting multiple branches.

How does that sound?

**Comment by DanPristupov** [comment]
I summarized majority of the ideas and released Fork 1.0.45 with an initial version of multiple items delete. The change affects both local and remote branches and tags.

<img width="509" alt="2017-05-10 at 15 49" src="https://cloud.githubusercontent.com/assets/618115/25901884/58ab4488-3598-11e7-82dd-dba987a98b3b.png">

Please let me know if you think something can be improved.

**Comment by mergesort** [comment]
I think it looks great, I can't wait to try it out.

Thanks a lot!
