### ISSUE TITLE
Allow --first-parent history

### ISSUE THREAD

**Issue by passsy** [ForkIssues/Tracker#220]
To get a rough overview of the latest changes on the `develop` branch I usually look at the first-parent commits of `develop`. Unlike SourceTree this filter is not available in Fork.

```
> git log develop --first-parent --oneline
```

**Comment by DanPristupov** [comment]
Hi. I've never heard about this feature. Going to check it out.

**Comment by chiahsien** [comment]
Any update on this request? Super useful feature for me, too!

**Comment by YesThatAllen** [comment]
We use this feature to perform more concise rubocop comparisons as well. I'm tossing in my 👍 vote for more `--first-parent` features.

**Comment by DanPristupov** [comment]
I'm thinking about introducing this option in the next release but not sure where to put it. Will it be OK, if `--first-parent` will be available as menu item in the View application menu until I find a better place for it?

**Comment by passsy** [comment]
`--first-parent` only makes sense when looking at a single branch. It would therefore make sense in the branch's context menu.

**Comment by DanPristupov** [comment]
@chiahsien @passsy `--first-parent` is applied for whole graph (while will be used mostly on a single branch). So, adding the option to the branch context menu can be confusing in multi-filter and no-filter state. Do you agree?

**Comment by chiahsien** [comment]
Hello @DanPristupov , any update on this request?

**Comment by kwiersma** [comment]
First off great work on Fork! This is the only feature that keeps me opening SourceTree. :) If you are able to add it, even just in the view menu for now, that would be awesome!

**Comment by ApolloTang** [comment]
me too, this is the only reason i still opening Source tree.

**Comment by DanPristupov** [comment]
First-parent mode is available as an experimental feature in 1.0.88.10 prerelease (https://github.com/ForkIssues/Tracker/issues/865). Does it work as you expect?

**Comment by passsy** [comment]
No, it's not what I expected. It still shows branches I'm not currently on.

The result of `--first-parent` in git CLI and sourcetree is a single chain of commits from `HEAD` to initial commit. No other branches are shown. It looks like a repository which only rebases, never merges.

**Comment by DanPristupov** [comment]
OK, I see. Most probably it looks like a single chain of commits in CLI because git shows only current branch by default. Fork shows something like `git log --all --first-parent` until you set filter on the active branch (`Cmd+Shift+A`).

**Comment by passsy** [comment]
That's it!

**Comment by CaptainDX** [comment]
I would like this also with the view file history option, It could help in some situations.
