### ISSUE TITLE
Unable to run pre-commit correctly

### ISSUE THREAD

**Issue by wekerSnail** [ForkIssues/Tracker#2201]
I switched the node version with nvm and it can't run correctly in fork. When I use the command tool, I can commit normally, but it will report an error when I use fork. .git/hooks/pre-commit: line 12: pnpm: command not found. When I set the node version to the default correct version, I can't solve this problem.

**Comment by wekerSnail** [comment]
<img width="873" alt="image" src="https://github.com/user-attachments/assets/90787680-6ed3-4383-8d64-258bbd7e5757">

**Comment by niightly** [comment]
I've run in the same issue, close your fork client and try this:

```sh
open -a Fork .
```

then try to run your pre-commit again.

**Comment by wekerSnail** [comment]
> I've run in the same issue, close your fork client and try this:
> 
> ```shell
> open -a Fork .
> ```
> 
> then try to run your pre-commit again.

This solves my problem, so every time I switch node versions, I need to turn off fork and run it again?

**Comment by DanPristupov** [comment]
Can you contact me by email (support@fork.dev), please? I need a help with testing.

**Comment by wekerSnail** [comment]
> Can you contact me by email ([support@fork.dev](mailto:support@fork.dev)), please? I need a help with testing.

no problem,what should I do

**Comment by Luckyfella73** [comment]
Hi,

I wrote an email about this to you @DanPristupov but it might be good to add that information here.
Using NVM and husky pre-commit hooks I was able to solve the PATH issue when using the Fork app by having this `.huskyrc` in my users root-path (working on MacOs):
```
# ~/.huskyrc

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```
It seemed to stop working after I updated the Fork-App. After reading the Fork changelog
[https://git-fork.com/releasenotes](https://git-fork.com/releasenotes)

> Improved Use bash instead of sh for custom commands (Fork version 2.46)

I thought it might be related to that and installed Fork in version 2.45 (the version before that change). Now the husky pre-commit hook works again (no PATH issue here).

If I can help to solve that issue by testing or providing more details - I would be glad to do that.


**EDIT:**
Thanks again Dan for your clarification via email - looks like I missed some information in the release notes.
In case somebody has the same issue/missunderstanding like me - this helped me fix the issue:

```
# ~/.huskyrc
export PATH="$HOME/.nvm/versions/node/$(nvm current)/bin:$PATH"
```

while having _Fork/settings/Git/ENV PATH_ set to `System shell 'bin/zsh' default`

**Comment by sandrodz** [comment]
I've brew installed nvm, and this worked:

```
# ~/.huskyrc
# Fixes issues with fork git commit error
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm

```

**Comment by jesusfj710** [comment]
> I've brew installed nvm, and this worked:
> 
> ```
> # ~/.huskyrc
> # Fixes issues with fork git commit error
> export NVM_DIR="$HOME/.nvm"
> [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
> 
> ```

Not all heroes wear capes. Thanks for this 😃
