### ISSUE TITLE
Add a continuously scrolling diff view

### ISSUE THREAD

**Issue by naiyerasif** [ForkIssues/Tracker#2202]
Currently when I have to look at the diff of unstaged / staged changes or commits, I have to manually select a file to view the changes. This becomes tedious when I have to look at large changes.

I request a continuously scrolling diff view where I can start browsing a change without any need to select a file in the change. This is very nicely implemented as the Summary view in [Sublime Merge](https://www.sublimemerge.com/) where all files in a change are presented as a list of collapsibles which I can navigate without selecting them one by one. It is particularly effective in keeping my focus solely on the change rather than forcing me to switch between selecting a file to view a change.

**Comment by DanPristupov** [comment]
Duplicate https://github.com/fork-dev/Tracker/issues/29, https://github.com/fork-dev/Tracker/issues/261, https://github.com/fork-dev/Tracker/issues/912

**Comment by naiyerasif** [comment]
Whoops! Closing this since there are already similar requests.
