### ISSUE TITLE
"Disable syntax highlighting" highlights code

### ISSUE THREAD

**Issue by bbriano** [ForkIssues/Tracker#2206]
Fork: Version 2.46.1
OS: MacOS 10.15.7

Reproduce:
Set "Disable syntax highlighting" in Preferences > General

Expected:
For code to not be highlighted

But:
Code are still highlighted

**Comment by DanPristupov** [comment]
I confirm the bug.

**Comment by DanPristupov** [comment]
I don't want to disturb the users with a minor bug update, so you can download the hotfix manually: https://cdn.fork.dev/mac/Fork-2.46.2.dmg
