### ISSUE TITLE
Removing local branch shouldn't offer to remove remote branch by default

### ISSUE THREAD

**Issue by gergelysanta** [ForkIssues/Tracker#221]
Steps to reproduce:

1. Remove a local branch
2. Check “Remove remote branch” (unchecked by default)
3. Click OK (local and remote branches will be deleted)
4. Remove another local branch

Here “Remove remote branch” is checked by default because I checked it when I was removing the first branch. This should be OFF all the time when sheet is displayed. I nearly accidentally removed a remote branch because didn’t notice it was pre-selected.

**Comment by DanPristupov** [comment]
It's actually a feature, Fork remembers the last dialog settings deliberately. 
Anyway, I agree with you. It would be safer to keep it unchecked initially.

**Comment by gergelysanta** [comment]
IMHO it's dangerous. I work with different branches and don't keep them all locally. I removed recently a local branch and didn't notice that checkbox is on. The only thing what saved that remote branch was my network. It was disconnected :)

**Comment by DanPristupov** [comment]
Fixed in 1.0.64

**Comment by gergelysanta** [comment]
Thank You!
