### ISSUE TITLE
Rename branch: warning only partially visible

### ISSUE THREAD

**Issue by abentele** [ForkIssues/Tracker#2210]
When I rename a branch with a long name, the warning is only partially displayed, see screenshot.
Also the input field and the checkbox don't display the full name of the branch.

While I use to use short branch names, sometimes my branch names get longer, especially when I use semantic prefixes like here ("postponed/").

<img width="533" alt="screenshot" src="https://github.com/user-attachments/assets/bcff1932-4773-4ec7-8405-1f918d890a85">

**Comment by DanPristupov** [comment]
Fixed in Fork 2.47

**Comment by abentele** [comment]
Cannot confirm. Exactly same problem in 2.47.
How was it fixed?

**Comment by DanPristupov** [comment]
Warning has a tooltip now.

**Comment by abentele** [comment]
Ok, was not obvious for me, thanks.
As it's an edge case in my opinion, this solution is sufficient for me.

Please close the issue if it can be closed.
