### ISSUE TITLE
Opening submodule hides all other tabs

### ISSUE THREAD

**Issue by ShmelPolosatik** [ForkIssues/Tracker#2212]
Hello,

I’ve encountered an issue where, upon opening a submodule, all of my existing tabs are hidden. The only way I can navigate back to them is through “Quick Launch,” which is quite inconvenient.

I noticed that this may be related to the issue fixed in version 2.46 (Opening submodule creates a tab in the wrong window). Could you please confirm if this is the same issue or related? If so, could you provide an approximate release date for this fix?

Alternatively, if it’s not possible to resolve immediately, could you guide me on how to downgrade to version 2.45.0?

Thank you for your assistance.

**Comment by ShmelPolosatik** [comment]
My Fork version is 2.45.2

**Comment by DanPristupov** [comment]
> Could you please confirm if this is the same issue or related?

Not sure. It's easier to try. Switch Fork back to the develop update channel and check for updates.

**Comment by ShmelPolosatik** [comment]
I found a link to version 2.46.2 in another thread (which hasn’t been officially released yet). I updated to this version and can confirm that the issue is fixed. For user convenience, I would like to suggest providing a list of previous released versions to allow for downgrades if needed. Currently, your site only offers the latest version, which contains a critical bug, and there’s no option to revert to a working version.

**Comment by ShmelPolosatik** [comment]
I also tried to send feedback from the app several times but I’m not sure if it was actually sent. The spinner icon appeared and then disappeared, but there was no confirmation, so it’s unclear whether the message was successfully sent.

**Comment by DanPristupov** [comment]
> I found a link to version 2.46.2 in another thread (which hasn’t been officially released yet)

It was, but you switched Fork the non-default stable update channel which is always delayed.

> I also tried to send feedback from the app several times but I’m not sure if it was actually sent.

No, I didn't receive it. I guess the request was blocked by your firewall, proxy or VPN.

**Comment by ShmelPolosatik** [comment]
> It was, but you switched Fork the non-default stable update channel which is always delayed.

I haven't done anything like that. Could you please give me details how this could be and how to switch back to the default stable update channel.

**Comment by ShmelPolosatik** [comment]
<img width="438" alt="image" src="https://github.com/user-attachments/assets/4065fdeb-e2ae-41a1-82af-fd4a2569ffc8">

Isn’t this the default? I believe downloading from the stable version is a good practice.

**Comment by DanPristupov** [comment]
No, it's not default.
