### ISSUE TITLE
Wrap text in error dialog

### ISSUE THREAD

**Issue by ZevEisenberg** [ForkIssues/Tracker#2215]
Sometimes, the output of Git commands is long, and the important part is scrolled off screen:

![image](https://github.com/user-attachments/assets/db555009-f25f-451a-bff0-cc3ea5d81dfa)

When I run the same command in the Terminal, the lines wrap so I can read it:

![image](https://github.com/user-attachments/assets/9bb87c61-a376-4398-9e50-1972cc541b17)

**Comment by DanPristupov** [comment]
Right 👍.
We made the error dialog to wrap the output in Fork 2.47.

**Comment by ZevEisenberg** [comment]
Works like a charm! ❤️🙇🏻
