### ISSUE TITLE
Crashes on Japanese characters in commit changes

### ISSUE THREAD

**Issue by ow-ro** [ForkIssues/Tracker#2216]
Was editing a japanese strings.xml file for an android project, committed the changes, now whenever i click to view the commit details/check the changes it crashes.

Mac 2.46

**Comment by ow-ro** [comment]
![image](https://github.com/user-attachments/assets/497dc7c9-5879-4a3e-a5c5-c3d7286c6264)

Here is the change in question on GH

**Comment by DanPristupov** [comment]
> Mac 2.46

Please check for updates. There is Mac 2.46.2.

**Comment by ow-ro** [comment]
fixed, thanks
