### ISSUE TITLE
[BUG/SNAG] Images in LFS repo not showing unless clicked on

### ISSUE THREAD

**Issue by timmb** [ForkIssues/Tracker#2218]
I'm comparing a large number of images in my repo (with LFS). For some reason, the diff view is just showing two icons instead of images. If I click on the icon, the image will then show, but this makes the whole process much slower to do.

What I see:
<img width="710" alt="image" src="https://github.com/user-attachments/assets/c9e406df-e9ba-4e8b-960a-e762c1766d3e">

What I expect to see:
- The old image and the new image

**Comment by DanPristupov** [comment]
The images must be downloaded first. When they are cached, the will be shown immediately.

**Comment by timmb** [comment]
Hmm, does that mean this is a local issue with my repo? In that case, we can close this issue

**Comment by DanPristupov** [comment]
Do I understand that you never see the images even when you deselect a file and then select it again? If it's so, it's not normal.

**Comment by timmb** [comment]
I've actually already rebuilt my repo and now it's working. Will close the issue. Thanks for the help!
