### ISSUE TITLE
"Merge conflict" window is counter-intuitive and unusable

### ISSUE THREAD

**Issue by vitalyster** [ForkIssues/Tracker#222]
1. How to view "local" and "remote" changes before merge? How to edit result?
2. How to abort merge?

**Comment by mika76** [comment]
I struggled with merging too - would be helpful to be able to open the merge conflict file in own program like beyond compare as a 3 way merge...

**Comment by DanPristupov** [comment]
@vitalyster I agree.
1. There's no way to view them. I need to implement that.
2. Abort button is located on the top bar which is visible only in Commit list view. This bar should be visible for all views.
Thank you for the feedback.

@mika76 you can configure 3rd-party merger in Fork preferences. BC is supported.

**Comment by mika76** [comment]
@DanPristupov oh thanks - didn't see that 👍

**Comment by aonez** [comment]
This might be closed, since there's now an integrated view to merge (plus the third party button)

**Comment by DanPristupov** [comment]
@aonez the abort button is still visible only in commit list view which might be confusing. I'll keep this issue open until I fix that.

**Comment by DanPristupov** [comment]
In 1.0.72 the merge conflict bar is global and is visible in both repository and commit views.
