### ISSUE TITLE
Lots of error after pushing a commit, even though the push is done

### ISSUE THREAD

**Issue by morgaraf** [ForkIssues/Tracker#2224]
Every time I am pushing a commit, I am getting a window like this:

![Screenshot 2024-10-27 at 3 43 31 p m](https://github.com/user-attachments/assets/ed7d78ac-3c34-45a9-bbe3-d37aa1467d25)

Yet, the push works.

This is happening after upgrading to version 2.47.1 on MacOS.

Regards,
Rafael

**Comment by DanPristupov** [comment]
> Lots of error after pushing a commit

It's just a single error.

The last line in the output describes the problem.

If you uncheck 'push all tags' in the push dialog, this error will not appear.
