### ISSUE TITLE
Rebase UI suggestions

### ISSUE THREAD

**Issue by vitalyster** [ForkIssues/Tracker#223]
I have some branches and want to rebase each on master. Now I need: checkout some branch, select master(sic!) branch in branches tree and check "Interactive rebase on master..."(what? which branch?). I think it will be more intuitive to have "rebase on master" (default branch) in the *current* branch context menu.

**Comment by DanPristupov** [comment]
Many git environments have more that 1 default branch (e.g. master and develop), so 'Rebase on %defaultbranch%' menu item doesn't make much sense.

Instead, you can just drag and drop branches on the sidebar (more info there: https://github.com/ForkIssues/Tracker/issues/82).
![2017-10-23 at 14 59](https://user-images.githubusercontent.com/618115/31890289-db5a936a-b802-11e7-88d3-5a27fe104805.gif)

**Comment by vitalyster** [comment]
%defaultbranch% is where HEAD now (bold in branches list), it can be added to others context menu
Anyway, thanks for drap and drop suggestion
