### ISSUE TITLE
Operations on SSH proxy jump remotes hanging

### ISSUE THREAD

**Issue by gfiumara** [ForkIssues/Tracker#2231]
I connect to a remote via an SSH proxy jump, configured in `~/.ssh/config`. This has worked fine in Fork forever (apps really shouldn't care), but doesn't work with recent updates. Commands hang with no output to be seen. I see these commands running when I try a fetch from the remote:

```
/Applications/Fork.app/Contents/Resources/git-instance/bin/git fetch --prune --tags ssh_tunnel_remote_name --verbose --progress
/usr/bin/ssh -o SendEnv=GIT_PROTOCOL remote_hostname git-upload-pack '/remote/path/of/repo'
```

Sometimes, I get this error or it it'll hang indefinitely. I've tried jumping backwards several versions without consistency in it working.

> ssh: connect to host first_proxy_jump_host port 22: Undefined error: 0
> banner exchange: Connection to UNKNOWN port 65535: Broken pipe
> Connection closed by UNKNOWN port 65535
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> 
> 
> In a case you entered incorrect password, please
> update it in Keychain Access application.

All jumps in the process use the same password.

**Comment by DanPristupov** [comment]
> doesn't work with recent updates

Do you mean 2.47.4 which was released a week ago? Does it work with https://cdn.fork.dev/mac/Fork-2.46.2.dmg?

**Comment by gfiumara** [comment]
Yes, 2.47.4. I've rolled back to 2.46.2 and receive the ssh error on the first operation, and then hangs on subsequent operations.

**Comment by DanPristupov** [comment]
> I've rolled back to 2.46.2 and receive the ssh error on the first operation, and then hangs on subsequent operations.

So, it wasn't broken by the latest update...

1. Ensure that all SSH keys in the Fork -> Configure SSH keys dialog are unchecked.
2. Try to switch Fork to your system git instance (Fork -> Preferences -> Git -> Git instance)

**Comment by gfiumara** [comment]
I am closing this. I think this is actually an issue caused by some newly-deployed corporate IT settings and nothing to do with Fork. I can use Fork as expected with SSH proxy jumps on different machines/networks. I apologize for the trouble!
