### ISSUE TITLE
error: could not delete references: cannot lock ref 

### ISSUE THREAD

**Issue by orhuidobro** [ForkIssues/Tracker#2246]
Suddenly, with the latest update to `2.47.4` on Mac, any pull or fetch in an specific repository fails.
The mentioned lock file doesn't exist (path edited by me in the pasted error).
I can run pulls and fetchs using GIT Cli or other tools (like VS code), and they work well.
I restarted the computer, making no difference.

```
error: could not delete references: cannot lock ref 'refs/remotes/origin/yk/refactor-dso-643': Unable to create '/.../.git/refs/remotes/origin/yk/refactor-dso-643.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'.  Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
From github.com:UA-Cloudops/infra-terraform
 - [deleted]         (none)                  → origin/DSO-1385
 - [deleted]         (none)                  → origin/DSO-643
 ...
```

**Comment by DanPristupov** [comment]
> I can run pulls and fetchs using GIT Cli or other tools (like VS code), and they work well.

May be your system git is different.

Try to delete this branch remotely and then fetch.

**Comment by DanPristupov** [comment]
May be this can be helpful: https://stackoverflow.com/questions/45141188/git-fatal-cannot-lock-ref

**Comment by orhuidobro** [comment]
Thak you @DanPristupov . The StackOverflow discussion you sent me was helpful.

My problem was solved running: `git fetch --prune origin`
