### ISSUE TITLE
Fork 2.48 is Apple silicon only??

### ISSUE THREAD

**Issue by Meorge** [ForkIssues/Tracker#2248]
This morning I was working with Fork and got a pop-up that version 2.48 was available with some small improvements, so I clicked Update. When it finished and I asked it to relaunch the app, I got this message:

![CleanShot 2024-11-15 at 08 56 47@2x](https://github.com/user-attachments/assets/9e2b65a8-7951-43bb-85f8-f545c1600616)

Indeed, looking at the app via Get Info, I can see it's now an Apple silicon app:

![CleanShot 2024-11-15 at 09 03 51@2x](https://github.com/user-attachments/assets/3b32499e-ff46-4c50-b648-f19bf3b5b778)

I don't see anything in the changelogs about the app moving to Apple silicon only, so I'm guessing this must have been unintentional. As someone whose primary computer is an Intel iMac and who also uses Fork a lot for managing Git, this was a bit terrifying to see though.

~~In the meantime, is there a way to downgrade to 2.47 (or whichever was the previous version that included Intel support)?~~
The download link on [the website](https://fork.dev) has 2.46.2, which still runs on the Intel iMac 😄

**Comment by DanPristupov** [comment]
Thank you for reporting. I'm investigating.

**Comment by DanPristupov** [comment]
I've released 2.48.1 hotfix. Can you try it, please?

https://cdn.fork.dev/mac/Fork-2.48.1.dmg

<img width="250" alt="Screenshot 2024-11-15 at 18 29 19" src="https://github.com/user-attachments/assets/464b02c5-03e9-401b-9e36-10fc8d40e72c">

**Comment by Meorge** [comment]
It's working for me, thanks so much for the quick fix!! 😄 

![CleanShot 2024-11-15 at 09 30 40@2x](https://github.com/user-attachments/assets/c8e8f460-8be1-462e-93d6-c85f0fb7247a)

**Comment by DexterWernJr** [comment]
>2 **NSA**NSA**NSA**
