### ISSUE TITLE
git reset: Add keyboard shortcuts

### ISSUE THREAD

**Issue by Turbo87** [ForkIssues/Tracker#226]
When the "Reset `<branch>` to here" modal is open it would be great to have keyboard shortcuts to select the "Reset Type" (e.g. <kbd>H</kbd> for `--hard`).

**Comment by DanPristupov** [comment]
Available in 1.0.71

**Comment by Turbo87** [comment]
oh, awesome, thank you :)

**Comment by DanPristupov** [comment]
Yeah, I know it was a long time ago. Sometimes I go to review old requests and check if I forgot something...
