### ISSUE TITLE
Feature: Double- or ⌘-click on filter icon (funnel)

### ISSUE THREAD

**Issue by svoop** [ForkIssues/Tracker#2269]
Branch filters are very powerful to only display the parts of the history you're actually interested in. I'm talking about the funnel icons in the branch list (left), here selected in blue:

<img width="270" alt="image" src="https://github.com/user-attachments/assets/91306436-2bec-4c57-b8a8-c972864b37bd" />

One or multiple active filters are listed above the commit list (right):

<img width="594" alt="image" src="https://github.com/user-attachments/assets/dc42545b-6a98-42b7-abcf-c3af586cedc9" />

A common situation: Given one or more branch filters are active (as in the screenshot above), I'd like to switch to filtering one and only one other branch instead. To do so, you first have to click the "clear filters" link, then click the funnel icon of the branch in question.

Would it be possible (and make sense) to add a new shortcut to perform these two steps (clear all filters, activate this filter only) when you double-click on the funnel icon?

If double-click appears too similar to single-click, maybe ⌘-click would be an alternative.

**Comment by DanPristupov** [comment]
>  I'd like to switch to filtering one and only one other branch instead
> ⌘-click would be an alternative.

It is ⌘-click already.

**Comment by svoop** [comment]
Caramba... I've tried double-click and ctrl-click (no good, context menu), but then changed it here to cmd-click without trying it first. Jeez, you're way ahead of me. 

Well then, least I can do is wishing you a Happy New Year instead! 😄 Cheers!!

**Comment by DanPristupov** [comment]
Happy New Year 🎄!

Let the software predict your ideas in 2025 :).
