### ISSUE TITLE
Add checkbox on push dialog to track branch

### ISSUE THREAD

**Issue by tandr** [ForkIssues/Tracker#228]
Instead (in addition) of opening a second dialog with "Do you want to track origin/XXXXX?" add one more checkbox to Push dialog

**Comment by DanPristupov** [comment]
Hi. This pop-up is an inheritance of the very first versions :).
I agree with you, it's time to improve that behavior.

**Comment by tandr** [comment]
Are you sure?
<img width="522" alt="screen shot 2018-03-16 at 2 12 41 pm" src="https://user-images.githubusercontent.com/5227075/37542564-3516d0f2-2924-11e8-915a-8af8e02a2ee9.png">

**Comment by DanPristupov** [comment]
Yes, the checkbox appears only for local branches without tracking reference. Just select a different branch in combobox.

**Comment by DanPristupov** [comment]
![2018-03-16 at 21 41](https://user-images.githubusercontent.com/618115/37543743-e76a38b4-2962-11e8-8fdc-66f3e083ed56.gif)

**Comment by tandr** [comment]
I was totally expecting for this button to show for all of them, so I can "untrack" branch or change tracking to another remote if needed.

**Comment by DanPristupov** [comment]
Untrack/change tracing is not related to push. It's a **local** operation. You can untrack (and track) branches using context menu on the sidebar.
![2018-03-16 at 22 29](https://user-images.githubusercontent.com/618115/37545595-a08d1b8a-2969-11e8-9815-1e9225412e06.png)

**Comment by tandr** [comment]
Thank you very much Dan, that's solves it.
