### ISSUE TITLE
`git status` parsing when file copied?

### ISSUE THREAD

**Issue by dmay** [ForkIssues/Tracker#23]
Here is output of `git status`

    On branch develop
    Your branch is up-to-date with 'origin/develop'.
    Changes to be committed:
      (use "git reset HEAD <file>..." to unstage)
        new file:   Procedures/Orders/Posting/SES_CL_Orders_Validate.sql
        modified:   Procedures/Orders/SES_CL_Orders_Get.sql
        copied:     Procedures/Orders/SES_CL_Orders_Get.sql -> Procedures/Orders/SES_CL_Orders_GetLines.sql

And here is what Fork displays:
![image](https://cloud.githubusercontent.com/assets/1068398/25711858/cd30cb0a-30a4-11e7-8e9d-23acd6cb8886.png)

**Comment by DanPristupov** [comment]
Could you show the result of `git status --porcelain --untracked-files=all` command please?

**Comment by dmay** [comment]
>> git status --porcelain --untracked-files=all
    A  Procedures/Orders/Posting/SES_CL_Orders_Validate.sql
    M  Procedures/Orders/SES_CL_Orders_Get.sql
    C  Procedures/Orders/SES_CL_Orders_Get.sql -> Procedures/Orders/SES_CL_Orders_GetLines.sql

    >> git --version
    git version 2.11.0 (Apple Git-81)

**Comment by DanPristupov** [comment]
@dmay thanks. I'm going to investigate this in few days.

**Comment by DanPristupov** [comment]
The fix will be available in next Fork update (1.0.45)

**Comment by DanPristupov** [comment]
Just released Fork 1.0.45 where this problem is fixed.

**Comment by dmay** [comment]
Thank you! :)
