### ISSUE TITLE
Auto update doesn't work for me

### ISSUE THREAD

**Issue by homm** [ForkIssues/Tracker#230]
I'm using Fork client several months and during this time I was able to automatically update one or two times.

Most time I see "Software update" dialog with release notes and prompt to update. When I'm pressing Install update, the bundle is downloaded and when I'm pressing "Install & relaunch", Fork application just closes and nothing else happens. When I'm opening it again, it's still the previous version and asks for the update.

**Comment by DanPristupov** [comment]
Fork uses the Sparkle framework (https://github.com/sparkle-project/Sparkle) and there's not much I can do. I regularly update it, but this bug still exists and difficult to reproduce. But I noticed that such update failures occur in other applications which use Sparkle too.

May be the problem is somehow related to application size. The update started failing more often when I bundled git into Fork (https://github.com/ForkIssues/Tracker/issues/72). I will try to implement delta-updates support which should decrease update size to 2-3 Mb and hopefully also decrease chances of a failure.

**Comment by DanPristupov** [comment]
When update fails again, could you please send me Sparkle log file to support@git-fork.com. It might contain some warnings. The log file is located at `~Library/Logs/SparkleUpdate.log`. Thank you in advance.

**Comment by homm** [comment]
> When update fails again

Sure. Unfortunately, today update was successful :-D

**Comment by homm** [comment]
`~/Library/Logs/SparkleUpdate.log` is empty, it even isn't created. 
Here logs from Console.app:

```
19.04.18 20:06:00,218 Fork [Sparkle][71475]: copyItemAtPath:/Volumes/4890189C-D661-4B81-B000-5B24BA34B97C/.background toPath:/Users/Master/Library/Caches/com.DanPristupov.Fork/org.sparkle-project.Sparkle/Fork 1.0.66/.background
19.04.18 20:06:00,229 Fork [Sparkle][71475]: copyItemAtPath:/Volumes/4890189C-D661-4B81-B000-5B24BA34B97C/.DS_Store toPath:/Users/Master/Library/Caches/com.DanPristupov.Fork/org.sparkle-project.Sparkle/Fork 1.0.66/.DS_Store
19.04.18 20:06:00,233 Fork [Sparkle][71475]: copyItemAtPath:/Volumes/4890189C-D661-4B81-B000-5B24BA34B97C/Applications toPath:/Users/Master/Library/Caches/com.DanPristupov.Fork/org.sparkle-project.Sparkle/Fork 1.0.66/Applications
19.04.18 20:06:00,233 Fork [Sparkle][71475]: copyItemAtPath:/Volumes/4890189C-D661-4B81-B000-5B24BA34B97C/Fork.app toPath:/Users/Master/Library/Caches/com.DanPristupov.Fork/org.sparkle-project.Sparkle/Fork 1.0.66/Fork.app
19.04.18 20:06:37,264 Autoupdate [Sparkle][71639]: PID to listen: 71475
```

Folder `/Users/Master/Library/Caches/com.DanPristupov.Fork/org.sparkle-project.Sparkle` exists, but is empty.

**Comment by DanPristupov** [comment]
I'll investigate, may be there's a way to turn on verbose logging..

**Comment by homm** [comment]
This is not happens anymore (I believe after update to Mojave), so don't worry
