### ISSUE TITLE
Display server response comments after push

### ISSUE THREAD

**Issue by tandr** [ForkIssues/Tracker#231]
Sometimes there are more info coming back from remote that is currently impossible to see after push.

For example, out Gitlab instance provides response comments after push that shows an easy link to go and create a merge request.

**Comment by DanPristupov** [comment]
This feature is in my todo list. I will implement it one day when I have a time, but there are always tasks which are more important :).

**Comment by filipp** [comment]
I think this also affects pre-commit hook behaviour. If a hook fails and the server returns a description of the error (both to stdout and err), Fork will not show it and will only display a generic " ! [remote rejected]       master -> master (pre-receive hook declined)... error: failed to push some refs to..." message.

**Comment by tandr** [comment]
well... Until it is fixed, I am bound to use pushes from command line

**Comment by DanPristupov** [comment]
@filipp I'll check this. This is definitely a bug.

**Comment by DanPristupov** [comment]
In 1.0.67 I introduced Activity manager where you can see the output from push/fetch/clone operations.

**Comment by tandr** [comment]
How do I access this "Activity Manager"?

**Comment by DanPristupov** [comment]
@tandr click on the 'list' button on the status bar
<img width="600" alt="activity" src="https://user-images.githubusercontent.com/618115/40822160-3335e5b0-656b-11e8-9e2b-ae282d24085f.png">

**Comment by tandr** [comment]
Resolved.

If I may only ask for the links in the output text to be clickable, that would be an absolute perfection!

**Comment by tandr** [comment]
Guys, you are awesome - link is now clickable! Thank you very much!

**Comment by DanPristupov** [comment]
@tandr you are welcome :)
