### ISSUE TITLE
Commits that are cherry-picked are not signed

### ISSUE THREAD

**Issue by maksimovic** [ForkIssues/Tracker#232]
When GPG signature is turned on in repository settings and commits are cherry-picked, they do not get signed (even if the cherry-picked ones have already been signed).

As per the screenshot below, commits without "Verified" label have been cherry-picked:

<img width="708" alt="screen shot 2018-02-28 at 09 04 31" src="https://user-images.githubusercontent.com/1126226/36776607-b045d1f8-1c66-11e8-8c0a-9f1727dddb4d.png">

**Comment by DanPristupov** [comment]
Thank you for letting me know. Will fix this.

**Comment by DanPristupov** [comment]
Could you please confirm if this is fixed in 1.0.65?

**Comment by maksimovic** [comment]
Now cherry-picking does not work at all :D

I can see the progress at the status bar, it appears as if it's working something but quickly finishes, but there's no commit applied. Even without "Commit the Changes" ticked in the cherry-pick dialog it doesn't apply the changes.

I've tried to see if there's some sort of "console log" or something similar to check what are the commands/output, but I can't find anything in the interface. Is there a log somewhere so I can check it to provide some debug info?

**Comment by DanPristupov** [comment]
@maksimovic ouch! I'll stop 1.0.65 update, until I fix this. Investigating.

**Comment by DanPristupov** [comment]
@maksimovic released 1.0.65. Fixed cherry-pick, signing does work properly. Also fixed the problem with avoiding error messages.

Since we are here, should `--sign-off`be also applied to cherry-pick?

**Comment by maksimovic** [comment]
@DanPristupov I've just updated Fork, cherry-picking works now and those commits are signed as well 🎉 

Personally I'm not using `--sign-off`, but I guess it would be nice to have that as well, so the commit is "copied" in full.

**Comment by maksimovic** [comment]
Just figured out that revert commits aren't getting signed as well 😁
