### ISSUE TITLE
Open Quickly dialog doesn't close, and moves slightly

### ISSUE THREAD

**Issue by lukakerr** [ForkIssues/Tracker#235]
Show in the gif below, the open quickly dialog when invoked with Shift+Command+O opens, and if Shift+Comment+O is pressed again and again and again, the dialog doesn't close but instead shifts slightly down to the right each time

![2018-03-02 16 49 28](https://user-images.githubusercontent.com/20056300/36885212-c9d2bd6e-1e39-11e8-90a7-eb32a4a4bff3.gif)

**Comment by DanPristupov** [comment]
I reproduced the problem. I cannot even imagine how you've found that :)
