### ISSUE TITLE
Request: Add preference to not show README preview

### ISSUE THREAD

**Issue by lukakerr** [ForkIssues/Tracker#237]
When opening Fork, it loads the README of the first repository in the "All" folder. For me this repo happens to have a massive README, which takes 10+ seconds to load, and uses quite a bit of CPU. 

It would be good to have a preference to not show the README preview at all, and just the repo information

**Comment by DanPristupov** [comment]
What a strange problem :). How big is your readme file? Does it freeze the UI? If so, I can load it in background thread and cancel loading when you change focus.

**Comment by DanPristupov** [comment]
I checked, even huge readme file doesn't slow down UI. However calculating repository size could be a long operations and I made a few improvements there in 1.0.68
