### ISSUE TITLE
Add tooltip for the Stash toolbar button

### ISSUE THREAD

**Issue by kitgrose** [ForkIssues/Tracker#238]
Other toolbar buttons (fetch, pull, push, etc.) have tooltips, but the Stash button does not (or it doesn't open for me).

**Comment by DanPristupov** [comment]
Thank you for reporting that. Gonna fix in the next update.

**Comment by DanPristupov** [comment]
Fixed. Thanks.
![2018-03-16 at 08 55](https://user-images.githubusercontent.com/618115/37509500-de33de00-28f7-11e8-8a70-fee994beead1.png)
