### ISSUE TITLE
Right edge of the fetch/pull/push toolbar button group is clipped

### ISSUE THREAD

**Issue by kitgrose** [ForkIssues/Tracker#239]
The right border on the set of buttons is clipped in version 1.0.64.1.

This is most noticeable when the window loses focus:
![Screen shot demonstrating the clipped border](https://user-images.githubusercontent.com/165977/37008902-73d700bc-2138-11e8-977e-8748b23fd13c.png)

**Comment by DanPristupov** [comment]
Good catch! Never noticed that :)

**Comment by DanPristupov** [comment]
Fixed in 1.0.65:
![2018-03-16 at 08 55](https://user-images.githubusercontent.com/618115/37509518-f172dc64-28f7-11e8-9e07-f724cb2e14b8.png)
