### ISSUE TITLE
Link to this issues tracker from within the app or from the main web site

### ISSUE THREAD

**Issue by dmay** [ForkIssues/Tracker#24]
Right now the only way (i've found) to learn about this tracker is through discussion with support@git-fork.com

That would be much convenient for users, who want to report some issues, to have a link here from Help menu, About window and from the home page of the web site.

**Comment by DanPristupov** [comment]
@dmay thank you for reporting this.
I added the Issue Tracker and website links to the Help menu in 1.0.47.
