### ISSUE TITLE
Bug: unreadable commit message tooltip in the dark theme

### ISSUE THREAD

**Issue by FinesseRus** [ForkIssues/Tracker#242]
If you choose the dark theme in the application preferences and hold the cursor over a commit message in the commits list, you will get a tooltip with a white text on a white background (the full commit message is unreadable).

The light theme:
![2018-03-13 11 55 51](https://user-images.githubusercontent.com/9006227/37318415-0fa23142-26b6-11e8-9ee6-9f5d8a12984c.png)

The dark theme:
![2018-03-13 11 56 22](https://user-images.githubusercontent.com/9006227/37318394-f4954eca-26b5-11e8-98d4-c086d502e168.png)

I face this problem on macOS 10.13.3. I didn't try it on other OSs.

**Comment by DanPristupov** [comment]
@FinesseRus Thank you for reporting the issue. I've reproduced it.

**Comment by DanPristupov** [comment]
OK, fixed that. Will be available in 1.0.65 update.
![2018-03-15 at 10 04](https://user-images.githubusercontent.com/618115/37454086-e793476a-2839-11e8-8ad7-7de3558bea5f.png)

**Comment by FinesseRus** [comment]
@DanPristupov Thank you

**Comment by FinesseRus** [comment]
As I can see, this is fixed
