### ISSUE TITLE
Typo in contextual menu for changed submodule

### ISSUE THREAD

**Issue by bomberstudios** [ForkIssues/Tracker#244]
When a submodule is dirty, the context menu shows 'Discard **Submobule** Changes…', when it should show 'Discard Submodule Changes…':

![screen shot 2018-03-15 at 18 36 22](https://user-images.githubusercontent.com/3832/37480605-f129a602-287f-11e8-9b5a-f0abec60a40f.png)

**Comment by DanPristupov** [comment]
Fixed in 1.0.65. Thank you.
