### ISSUE TITLE
Cherry pick broken

### ISSUE THREAD

**Issue by petterikamppuririchie** [ForkIssues/Tracker#245]
Hi!

It seems doing cherry pick doesn't actually do anything. Broke in the latest version (1.0.65).

**Comment by DanPristupov** [comment]
@petterikamppuririchie please check for updates. 1.0.65.1 has been released. More info there: https://github.com/ForkIssues/Tracker/issues/232

Sorry for the inconvenience.

**Comment by petterikamppuririchie** [comment]
Super, fixed, thanks! Gotta love the response times :) 👍
