### ISSUE TITLE
Feature Request: After finish relese or hotfix add "release" or "hotfix" to tag name.

### ISSUE THREAD

**Issue by kissferenc** [ForkIssues/Tracker#246]
I like the automatic tag after release or hotfix. But will be better to add type of branch.
Example the branch name of release is "v0.4" then the tag name will be "release/v0.4" or hotfix branche name is "fix-pasteboard" then the tag name will be "hotfix/fix-pasteboard".
(Sorry my bad english! :))

**Comment by DanPristupov** [comment]
Hey,
This is how GitFlow works, Fork just uses the library, which is maintained there: https://github.com/petervanderdoes/gitflow-avh.

Git-Flow is about 10 years old, so I suppose they won't change the behavior easily.

**Comment by FinesseRus** [comment]
This is not Git Flow. So I'm against.

**Comment by kissferenc** [comment]
I close the issue becouse I can solve this easily in other way (without rename).
