### ISSUE TITLE
Hard to read description for Command Line Integration Preferences

### ISSUE THREAD

**Issue by ngyikp** [ForkIssues/Tracker#248]
<img width="500" alt="screen shot 2018-03-17 at 4 06 38 pm" src="https://user-images.githubusercontent.com/6135313/37553172-7999b13e-29fd-11e8-81df-3fae4fb91728.png">

Preferences window has translucency which makes this description really difficult to read on dark backgrounds.

**Comment by FinesseRus** [comment]
I don't have this problem on my computer:
![2018-03-18 18 48 59](https://user-images.githubusercontent.com/9006227/37564227-2b3170dc-2add-11e8-8d3a-9f5e91607320.png)

**Comment by FinesseRus** [comment]
This problem appears only with the Dark theme

**Comment by DanPristupov** [comment]
Will be fixed in next version. Thank you.

**Comment by ngyikp** [comment]
Seems to be fixed on 1.0.66
