### ISSUE TITLE
Checkout Remote Branch via Context Menu

### ISSUE THREAD

**Issue by clounie** [ForkIssues/Tracker#25]
I can see a remote branch in my tree, but there is no option to "Checkout Branch" (or maybe "Checkout and Track") when I right-click unless I already have a local copy of the branch. 

Just some polish really, but would be nice to have.

**Comment by DanPristupov** [comment]
@clounie There is 'Track %remoteBranch%...' option which should do what you want. Is there any problem with it?

**Comment by clounie** [comment]
Nope, no bug - just a misunderstanding.

Given context:

*Current Branch:* `foo`
*I click on:* "Track 'origin/bar'..."

I assumed that the "Track" menu option would do this: `git branch --set-upstream-to upstream/bar foo`

Something like "Checkout & Track" or "Create & Track" would have made it clear; as it was, I just avoided it.

**Comment by DanPristupov** [comment]
@clounie I've implemented this in Fork 1.0.55. Now you can "checkout" remote branches:
- if remote branch is tracked, Fork will check out the corresponding local branch
- if remote branch is not tracked, Fork will propose to track it and then automatically checkout the local one.

P.S. I also added remote branches to the status bar dropdown list, which makes switching to remote branches faster (press Cmd+B, type first letters of the name, press Enter).

**Comment by clounie** [comment]
That's great - can't wait to use the Cmd+B functionality too!

Thanks Dan.
