### ISSUE TITLE
Checking out a remote branch: typing branch name lags

### ISSUE THREAD

**Issue by maksimovic** [ForkIssues/Tracker#255]
If I want to checkout someone's branch, e.g. from someone else's remote, typing the name that I want to use lags quite a lot. Roughly estimated: if I type a five-letters word, then I need to wait approximately 2 seconds for all letters to appear.

The screen I'm talking about:
<img width="506" alt="screen shot 2018-03-30 at 11 06 15" src="https://user-images.githubusercontent.com/1126226/38132336-f7481f8c-340a-11e8-8b09-7673c365103f.png">

It seems to be related to the number of remotes and most likely the overall number of branches. In this particular repository:

```
| => git branch -a | wc -l
    2055
```

In another repository where this number is 63, there seems to be no lag at all.

As far as I've managed to investigate, it's fetching the branches on keypress in order to check if the name is already taken. `git branch -a` takes around 0.3s, which looks like the per-character delay I'm experiencing. If that is the case, then I'm not sure if the `-a` needs to be used, because the name collision will occur only if the branch matches the one from the `git branch` list?

**Comment by DanPristupov** [comment]
I reproduced the problem, will fix in the next update. You are right, it depends on the number of branches in repository. I solved this problem everywhere, but seems to forgot about the Track Remote Branch window.
