### ISSUE TITLE
Git LFS (large file storage)

### ISSUE THREAD

**Issue by DanPristupov** [ForkIssues/Tracker#26]
I'm creating this issue to get a feedback if Git-LFS support is important.

**Comment by mrcarriere** [comment]
As a game developer, several of our projects have switched to using Git-LFS.

**Comment by DanPristupov** [comment]
I just released Fork 1.0.52 with Git LFS support.

**Comment by idmarjr** [comment]
Hello folks!
First of all, congratulations for the great job that you're doing in Fork :)

I would like to know what version of Git LFS Fork is using in it's core.
Thanks!

**Comment by Murazaki** [comment]
Hi,
I would like to know if it's known that Git LFS does not initialize on new setups for people cloning a new Git LFS project on Mac ?
I've had this issue with at least two users already.
