### ISSUE TITLE
How to compare between branch and tag

### ISSUE THREAD

**Issue by chiahsien** [ForkIssues/Tracker#262]
I find it interesting that I can select 2 local branches / remote branches / tags for comparison, but I can't mix them (e.g., local + remote, local + tag, or remote + tag).

Even I checkout a tag, I still can't select the `HEAD` + local branches.

So my question: is there any way to compare a tag and a branch?

**Comment by DanPristupov** [comment]
I think I implemented that in 1.0.71.
