### ISSUE TITLE
Do not save "Check out after create" state

### ISSUE THREAD

**Issue by Turbo87** [ForkIssues/Tracker#263]
It seems to happen to me quite a lot that I create a branch without checking it out, and the next time I want to create a branch I forget to turn the checkbox on again, don't notice it and continue working on the wrong branch.

I think "Check out after create" should be the default and I would prefer it if it didn't not keep the state for the next time that dialog is shown.

Feel free to disagree with me and just close the issue though 😉

**Comment by DanPristupov** [comment]
@Turbo87 ok, I'll add an option :)

**Comment by DanPristupov** [comment]
🎁 -> https://github.com/ForkIssues/Tracker/issues/287
