### ISSUE TITLE
`Contact support` form is broken

### ISSUE THREAD

**Issue by petterikamppuririchie** [ForkIssues/Tracker#265]
Can't type anything in `Contact support` form. Somehow can't focus the text fields. I get a beep when trying to type. I have a unresolved merge in progress in my repo, maybe that affects things.

<img width="567" alt="screen shot 2018-04-17 at 9 33 39" src="https://user-images.githubusercontent.com/7383661/38852419-80f956fe-4222-11e8-99bc-a05b392df07a.png">

Hmm, actually clicking somewhere in the actual repo window (not on the Contact sheet) fixed focus issue.

**Comment by DanPristupov** [comment]
Mac OS also has bugs. Sometimes I ask people to restart computer and it helps.

**Comment by DanPristupov** [comment]
I receive a bunch of messages every day, so I'll close this. Please let me know if the problem still exists.

**Comment by elia** [comment]
@DanPristupov Just happened to me, I was able to type some characters and then using the keyboard stopped working, seems connected with hitting the ⇧ key, when it stops it also loses the blue focus halo around the text field. <kbd>esc</kbd> still works to abandon the form but reopening it doesn't help, except after a while, if I start typing right away, if I wait 4-5 seconds the blue halo goes away and it stops working.

Sorry for the blurb of text, take everything with a grain of salt 🙂
