### ISSUE TITLE
Truncated repo names in the New Tab

### ISSUE THREAD

**Issue by homm** [ForkIssues/Tracker#268]
Names of the most repository are truncated, though there is a lot of space.

<img width="1110" alt="screen shot 2018-04-20 at 9 22 44" src="https://user-images.githubusercontent.com/128982/39033899-f77ae930-447c-11e8-91e9-56aed38ea14f.png">

Moreover, if I resize the column, when I open the New Tab next time, the column has old width.

<img width="1108" alt="screen shot 2018-04-20 at 9 28 58" src="https://user-images.githubusercontent.com/128982/39033980-50730a7c-447d-11e8-988a-6062b6a72a99.png">

**Comment by DanPristupov** [comment]
Ouch! Thank you for reporting that.
