### ISSUE TITLE
`Ignore Whitespaces` is not available on Changes page right click context menu

### ISSUE THREAD

**Issue by aziz** [ForkIssues/Tracker#27]
If I look at my commits, I can right click on a file and choose `Ignore whitespaces`. 
I want the same functionality on my Changes diff view

**Comment by DanPristupov** [comment]
I've tried to do this already. Allowing 'Ignore whitespaces' mode leads to many misunderstandings.

For example: user can stage all file chunks, but the file will stay in the 'unstaged' list, because it still contains unstaged whitespace changes (which are invisible for user).

**Comment by dmay** [comment]
@DanPristupov How do you gather diff info? Can you detect empty output, notify user somehow (yellow message strip at the top of diff window for example) and force displaying full diff?

**Comment by DanPristupov** [comment]
@dmay Yes, it's possible to detect an empty output. The idea to show a notification/warning bar with a 'enable whitespaces' button sounds good.

I'll enable this feature in my local build and give it another try. If it makes no problems I'll consider adding it to the release.

If you guys are interested to get an early access to this functionality, please let me know.

**Comment by dmay** [comment]
@DanPristupov That would be interesting :)

**Comment by prenaux** [comment]
Please add me to the beta for this feature. I use the commit staging to do a final code review before doing the actual commit and not having "ignore whitespace" there is really problematic for me.

**Comment by bwl21** [comment]
How about this issue, will it come? pls add me to the early access.

**Comment by sjuchno** [comment]
Please add this. Source Tree has this. I'm trying to ditch Source Tree but so far I still need it from time to time.

**Comment by DanPristupov** [comment]
Just released 1.0.65 which has `Ignore Whitespaces` context menu option in commit view.
