### ISSUE TITLE
Use standard Mac document behavior

### ISSUE THREAD

**Issue by nsabovic** [ForkIssues/Tracker#277]
I have seen (and written) a few bugs and confusion about how the tabs and windows behave, and the reason is that Fork departs from the standard macOS behavior, and I think it would be easier and faster to use if that were fixed.

If you don't go out of your way to override `DocumentManager` and `ApplicationDelegate` behaviors, this is how a macOS app (like Finder, TextEdit, Safari, SublimeText, Firefox, Chrome, Word, Excel, Keynote, Pages, OmniPlan) work:

  - When it opens, it shows the windows that were open the last time. If there are no such widows, it shows the default window (project folder in Fork, Desktop in Finder, new document in TextEdit, welcome screen in Word).
  - If you close the last window, the app is running, but no windows are shown. The app does not exit, so you can open another document quickly.
  - Clicking the app's icon in Dock or launching it again shows the default window if there are no windows on the screen.
  - If launched with a document/command line, opens that window in addition to restored windows. If the app is already running, just open that window.

Fork has these workflows changed, and I think for the worse. You can press ⌘W all you want and not kill the window, but pressing the close button kills the app. Showing a window I did not ask for (project folder in Fork) when I close the last window is very annoying to me. Since I use the app mostly from command line, I have to wait for it to start up each time so I can do 10 seconds of work, and then I have to shut it down by pressing ⌘Q or aiming for the close button.

Also, tabbed interface is a great addition to UIs with a lot of documents, like Finder and Chrome, but the default should really be to open another window. I have two monitors, and sometimes I want to look at two repositories side-by-side, and there is no way to do that. I also prefer to have a new document launched in a slightly different position (which it does by default) so as to have a visual cue that something different opened.

There's a whole uncanny valley of other paper cuts too, all stemming from overriding the default app behavior. Is this something that bothers anyone else, or do people prefer the current design and I am using it very differently than most?

**Comment by DanPristupov** [comment]
I absolutely agree with all you've written. Fork got tabs before Apple introduced them to developers. That's why the behavior differs. I could not switch no native implementation until majority of users got upgraded to new macOS.

I think now is a good time to finally start working on the migration to native tabs.

**Comment by nsabovic** [comment]
Amazing!!! I will comment over in the prerelease thread.

**Comment by nsabovic** [comment]
Fork 1.0.68.2 works perfectly, so I am closing this.

Thank you.
