### ISSUE TITLE
[Feature Request] Support bug-tracker links

### ISSUE THREAD

**Issue by nsabovic** [ForkIssues/Tracker#278]
A lot of online git UIs boast of bug-tracker integrations, and all it boils down to is the ability to recognize bug references, and convert these to links that can be clicked.

When I write #277 in GitHub (like in this box), it gets converted to a link that that takes me to the bug tracker.

Instead of inventing our own way of doing this, I'd go with the [way that TortoiseGit on Windows does it](https://tortoisegit.org/docs/tortoisegit/tgit-dug-bugtracker.html) because it seems they have thought about it thoroughly, and it would be nice to have some interop. They basically use two git config parameters:

1. `bugtraq.logregex` has a regex that captures the bug id (like `#(\d+)` or `JIRA-(\d+)`).
2. `bugtraq.url` is the URL with ` %BUGID%` replaced with the bug id that we extracted (like `https://github.com/ForkIssues/Tracker/issues/%BUGID%`).

Then that regex is run on the status messages and replaced with the links. I can store these settings in either my local project git config regardless of the project owner, or that project owner can distribute a .gitconfig file that I can include. Note that .gitconfig is not included by default for security reasons, and it would not be cool to randomly execute settings from the project.

**Comment by kervich** [comment]
I think this all comes down to Markdown support in general - that way you can configure `#numbers` or whatever else in pre-commit hooks - I for one have to use Redmine at work and reference both redmine ticket and GitHub PR as per my commit/pr template which is then converted to Markdown replacing respective tags to whatever should be there (url, some other text, whatever)

**Comment by nsabovic** [comment]
I respectfully disagree.

I think that markdown support is a separate issue. Pre-commit hook would only work for the projects which use markdown, and would require changes to the actual stored commit messages. Even if they wanted to implement markdown it wouldn't work in the past.

**Comment by susan51531** [comment]
GitHub Desktop has similar feature.
![8bf7a675-e4dc-4814-a4fa-e948f0a428e0](https://user-images.githubusercontent.com/2595468/44311482-f74e2a00-a41a-11e8-98ab-10e127b6eca9.png)

**Comment by gigi81** [comment]
It would be a really useful feature indeed.
Also it would be even better if the implementation could support multiple bug tracking system. Like having multiple bug tracking systems with different regex/url pairs. For example [this is another implementation example](http://www.syntevo.com/doc/pages/viewpage.action?pageId=1704589)

**Comment by DanPristupov** [comment]
I forgot to close this. The issue tracker integration was introduced in 1.0.76.
