### ISSUE TITLE
[Feature Request] Push to remote checkbox beside amend.

### ISSUE THREAD

**Issue by isuda** [ForkIssues/Tracker#279]
It would be nice to have the ability to push to a remote branch via a checkbox in the commit area like in sourcetree:

![image](https://user-images.githubusercontent.com/25780/39823040-fe149622-5360-11e8-93f5-9b6941496b2c.png)

I know there is a setting to automatically push to remote, but I don't want to do that every time. But it is convenient to do it sometimes (ex: when doing a quick bugfix).

**Comment by DanPristupov** [comment]
Hi,

You can hold alt/option key to commit and push

Dan Pristupov
