### ISSUE TITLE
[Feature request] Open repository in editor

### ISSUE THREAD

**Issue by pawelkondraciuk** [ForkIssues/Tracker#280]
Add possibility to open a current repository in the selected editor just below "Open in Terminal", similar to merge conflict button (merge in "Editor")

![image](https://user-images.githubusercontent.com/7136191/39916921-3a8abe9a-550c-11e8-9726-7afc8c34ca3f.png)

**Comment by DanPristupov** [comment]
What would be the 'selected editor'? You mean to open whole repository in text editor like Sublime?

**Comment by pawelkondraciuk** [comment]
Yes. In vscode you need to run command `code .` in selected directory or
`code directoryPath`

pt., 11 maj 2018, 18:11 użytkownik Dan <notifications@github.com> napisał:

**Comment by dmay** [comment]
Been there :) https://github.com/ForkIssues/Tracker/issues/76

**Comment by kervich** [comment]
As long as you have your project file added to Git repository and your system configured to open that kind of file everything works OOTB: contol-click on the project file and select 'Open' from the popup menu (or 'Open With...' if you have a few apps configured to open that file). There's nothing to do with Fork here.

**Comment by DanPristupov** [comment]
@kervich I think @pawelkondraciuk meant environments which don't have a dedicated project file (like node-js, C/C++, etc).

I can add **general** editors to the 'Open in' toolbar dropdown (if some of them installed):
- Sublime
- VS Code
- Atom
- MacVim (?)

Dedicated IDE's could be added using custom actions (will be introduced in the next update).

**Comment by kervich** [comment]
@DanPristupov I got it, for that you may list installed applications capable of editing `public.source-code` files (or those with UTIs derived from `public.source-code`) and capable of opening `public.directory`/`public.folder` UTIs at the same type - I guess that's a single query to LaunchServices API on macOS. In my system that would be TextMate and BBEdit for general directory/folder types, Xcode and VSCode would only care to open some specific UTIs that are derived from `com.apple.package` - so you might want to look for those in the top-level of the directory as well.

**Comment by DanPristupov** [comment]
Ok, I implemented this. Now you can open the current project in VSCode, Sublime or Atom (if they are installed).

![2018-05-21 at 18 31](https://user-images.githubusercontent.com/618115/40318603-6097adac-5d25-11e8-8827-e5539a98cbf5.png)

You can try it in 1.0.67 (https://github.com/ForkIssues/Tracker/issues/287)
