### ISSUE TITLE
"Stage All" button

### ISSUE THREAD

**Issue by Turbo87** [ForkIssues/Tracker#286]
In the Commit view it might be nice to have a "Stage All" button since most of the time that's what you would want to do. I'm not sure if that's technically possible, but I could imagine using a button group with a "Stage" and an "All" button so that it's clear that it means "Stage All" without using up too much space 🤔

**Comment by kervich** [comment]
<kbd>Cmd</kbd>+<kbd>A</kbd> then <kbd>Stage</kbd>, no?

**Comment by dmay** [comment]
When you hold `Alt/Opt` both Stage and Unstage buttons turn to Stage All and Unstage All respectively. This is one of very basic conceptions in Mac OS.

**Comment by kervich** [comment]
Indeed - how could I forget about that! However as far as I can see this is mostly a common practice for menus that assume alternative action (eg. "save"/"save as..", and rarely for toolbar buttons (even in stock apps bundled with macOS - i could only find this behaviour in QuickView toolbar button added to Finder)

**Comment by bwl21** [comment]
To be honest, I don't think "Stage All" is necessary. you could click on CMD-A and then stage.

Most of the time, I do stage file by file, to do a final review before committing. This avoids some garbage going to the repository.

**Comment by fuwaneko** [comment]
How about UI similar to SourceTree or Git plugin in Jetbrains IDE with checkboxes? One checkbox near every file to stage, and one on top of the list to stage all. I find it very intuitive and quick to use.

**Comment by DanPristupov** [comment]
I added the Stage All button in 1.0.70

**Comment by Turbo87** [comment]
Awesome, thanks
