### ISSUE TITLE
[Feature request] Filter branches

### ISSUE THREAD

**Issue by pawelkondraciuk** [ForkIssues/Tracker#289]
My repository consists of a lot of active branches, it would be great to have an option to filter tree view and show just selected or active branch

**Comment by DanPristupov** [comment]
Did you try to set branch filter on the sidebar (it also can be set on multiple branches)
![2018-05-28 at 10 07](https://user-images.githubusercontent.com/618115/40604338-02424066-625f-11e8-9eba-d5f4434b15aa.png)

**Comment by pawelkondraciuk** [comment]
Sadly it looks like a hidden feature, it would be great to add it also to right mouse menu :)
