### ISSUE TITLE
Diff toggle (spacebar), need toggle twice to make it visible if it is hidden by main window.

### ISSUE THREAD

**Issue by susan51531** [ForkIssues/Tracker#290]
Steps:
1:press space to a new diff window;
2:click form main window to make the diff window lost focus and put behind the main window.
3: A: If i want show the diff again on the same file, i will need toggle **twice** or using switch window between current app shortcut;
    B: if i want show the diff on different will, i need choose the file and do the steps as A;

Are there any more convenient way to toggle diff window when it is totally hided by the main window?

**Comment by DanPristupov** [comment]
> Are there any more convenient way to toggle diff window when it is totally hided by the main window?
No. I will handle this case and bring up the diff window when it's behind the main window.

**Comment by DanPristupov** [comment]
Couldn't fix this, unfortunately. Will try again in the future.

**Comment by DanPristupov** [comment]
This problem is finally fixed (Fork 1.0.85).
