### ISSUE TITLE
[Bug] 'Open' and 'Open With' are always disabled in File Tree.

### ISSUE THREAD

**Issue by susan51531** [ForkIssues/Tracker#292]
Version: Mac 1.0.67.2

**Comment by DanPristupov** [comment]
Good catch. Not sure when this happened. Will fix in the next update.

**Comment by DanPristupov** [comment]
Fixed as a part of 1.0.67.5 security update.

**Comment by susan51531** [comment]
@DanPristupov Hi, The lastest version(1.0.69.3), 'Open' and 'Open With' is only available if selected file is exists in worksapce. Files cannot be dragged, dragging file not working.
According to #291, these two menu items should always be available  to open files in the selected commit's version.
