### ISSUE TITLE
Rare crash when closing tab with modal configuration panel open

### ISSUE THREAD

**Issue by aonez** [ForkIssues/Tracker#293]
Tested with yesterday's update `1.0.67.2`, affects older versions.

## To reproduce (two or more repositories):

1. Open two or more repositories (two or more tabs at once)
2. On one of them, open the repository configuration panel
3. Close the active tab with `command + W` shortcut (`File` - `Close Tab` also works)
4. Close the configuration panel

## To reproduce (one repositories):

1. Open one repository
2. Open the repository configuration panel
3. Close the tab with `command + W` shortcut (`File` - `Close Tab` also works)
4. Open another repository
5. Close the configuration panel

At this point Fork should crash. I suppose just closing the configuration panel if opened when closing the tab should fix this.

Thanks for Fork!!!

**Comment by DanPristupov** [comment]
Awesome! Thank you, will fix in next update.

**Comment by DanPristupov** [comment]
Fixed this as a part of 1.0.67.5 security update.

**Comment by aonez** [comment]
Thanks for the fix! Anyway is strange to have the configuration panel of a repository that is closed, maybe closing it when closing the repository will make sense. Up to you! 👍
