### ISSUE TITLE
Custom actions: add/update, output modal's title

### ISSUE THREAD

**Issue by maksimovic** [ForkIssues/Tracker#294]
I've missed testing the early version - and kudos for the updates in 1.0.67 - but here are a couple of things that are a bit annoying 😁 

- Adding/Editing a custom action: data in the list on the left gets updated only if you click `+`, or if you navigate away from custom actions and come back. I'd expect it to change when the focus from the property being edited is moved away. E.g. if I type the name and move to the script path, then the name should get updated in the list on the left
- The title of the output modal gets cut off:
<img width="920" alt="screenshot_5_29_18__4_06_pm" src="https://user-images.githubusercontent.com/1126226/40664574-83bcf134-635b-11e8-8ffb-e2596ea15ba2.png">

Once again, great work, liking the new version a lot.

**Comment by DanPristupov** [comment]
I've fixed this as a part of 1.0.67.5 security update.

**Comment by maksimovic** [comment]
Confirmed that both thingies are now working like a charm 🍻
