### ISSUE TITLE
[Bug] Commit and Push button looks pixelated on 1080p monitors

### ISSUE THREAD

**Issue by CptSeasick** [ForkIssues/Tracker#297]
So I've started to use Fork today on both my work machine and my home machine which both have 1080p monitors (not the same monitor of course). The "Commit and Push" button looks very odd compared to other macOS buttons. I would describe it as rather pixelated. I'm running the latest version of Fork (v. 1.0.67.2) and both instances are completely clean installations since I started to use the app today.

The thing is that this just happens when using the light theme of the app. As you can see in the screenshots below, the dark mode looks just fine. I've attached more screenshots for comparison purposes. All these screenshots are captured on my 1080p monitor at home.

![screen shot 2018-05-30 at 20 39 13](https://user-images.githubusercontent.com/7465075/40743927-3a0efeee-6453-11e8-8268-3045a20e49bb.png)
Fork using light theme with pixelated button

![screen shot 2018-05-30 at 21 45 27](https://user-images.githubusercontent.com/7465075/40743924-39b853a0-6453-11e8-9bc4-ef75bcba233c.png)
Fork using dark theme looking just fine

![screen shot 2018-05-30 at 20 41 34](https://user-images.githubusercontent.com/7465075/40743926-39f2f37a-6453-11e8-827f-9d2306804299.png)
SourceTree with it's Commit button looking just fine

![screen shot 2018-05-30 at 21 42 25](https://user-images.githubusercontent.com/7465075/40743925-39d748c8-6453-11e8-9bfb-60f2c17b1805.png)
macOS system dialog button, also looking fine

**Comment by DanPristupov** [comment]
Do submit buttons in dialog windows also look blurry?

**Comment by CptSeasick** [comment]
Other buttons look just fine, see the Fetch button for example:

![screen shot 2018-06-01 at 12 29 26](https://user-images.githubusercontent.com/7465075/40836591-8f36ecac-6597-11e8-938a-c25950d43d84.png)

**Comment by DanPristupov** [comment]
I could not find any logical answer to that. However recently I was solving a similar problem and found that macOS has a strange option (see the screenshot). Is it possible that 'Open in Low resolution' somehow got enabled on your computer?
<img width="270" alt="2018-07-11 at 15 41" src="https://user-images.githubusercontent.com/618115/42575542-0cb7bbc2-8521-11e8-81e6-d43900302bdd.png">
