### ISSUE TITLE
Clone button doesn't do anything

### ISSUE THREAD

**Issue by mtschoen-unity** [ForkIssues/Tracker#298]
Hard to say why... setting up a new mac and trying to clone some private github repos. Setting the URL and hitting clone just has no effect. No warning, no issue, just doesn't clone.

**Comment by mtschoen-unity** [comment]
It looks like the underlying issue is that I don't have access to the repo. Even still, an error message would be nice.

**Comment by DanPristupov** [comment]
I fixed that problem already (in dev environment). It happens when you open clone window from Repository Manager.

Thank you.

**Comment by DanPristupov** [comment]
Fixed in 1.0.65.5 security hotfix.
