### ISSUE TITLE
UX: Get rid of UI jumps during launch of the application

### ISSUE THREAD

**Issue by aziz** [ForkIssues/Tracker#30]
- UI jumps mainly because of sudden appearance of the tabs, can it be avoided?
- Everything is Toolbar jump because of the change in width of "Repository Status" section
- Sidebar jumps up and down and the labels are changing. Can things be cached to improve this?

**Comment by DanPristupov** [comment]
Good catch. Honestly I got used to these glitches and don't notice them. Will have a look on them. Thanks
