### ISSUE TITLE
[Feature Request] Only close current window by clicking the close button 

### ISSUE THREAD

**Issue by ihomway** [ForkIssues/Tracker#302]
I always close the window by clicking the **close** button on the top-left, and it turns out that not only the current window is closed, but also the app is quit. So I'm asking if you can add an option on **Preferences...** to choose whether I want to quit the app when clicking on the close button or just close current window.

**Fork** is an awesome git client for me, **Thank You** sooooo much!!!

**Comment by DanPristupov** [comment]
Improving this right now. This will be a part of a global layout change.
