### ISSUE TITLE
Show output of pre-commit hooks interactively

### ISSUE THREAD

**Issue by ulope** [ForkIssues/Tracker#303]
It would be very useful if the output of pre-commit hooks could (maybe optionally) be displayed interactively. 

Use case: I'm using https://pre-commit.com and depending on the number and type of checks and how many files are to be committed it can take anywhere from one to a few tens of seconds to finish all checks.

**Comment by DanPristupov** [comment]
Hi. Thank you for the feature request. Hopefully will implement that in the next release.

**Comment by DanPristupov** [comment]
I didn't have a time for that in 1.68 and moved that request to 1.69.

**Comment by DanPristupov** [comment]
In 1.0.69 you can see the commit output in the activity manager. It includes the following data:
- `commit-message` hook output
- `pre-commit` hook output
- commit output
