### ISSUE TITLE
[Bug] Repository -> Commit is always greyed out

### ISSUE THREAD

**Issue by jespertheend** [ForkIssues/Tracker#305]
A while ago I mentioned (via email) that the commit shortcut (⌘⇧C) wasn't doing anything. So it's been changed to focus on the commit field, and I've been using this shortcut ever since. But now this menu item seems to be greyed out at all times, and so the shortcut doesn't work anymore :(

I might be misunderstanding what this menu item is for, but I couldn't find a situation where the item is not greyed out.

**Comment by DanPristupov** [comment]
Hi. Yes, I remember your email. It's strange, everything still works properly for me in 1.0.47.5.

Could you try the following please?
* Use the alternative <kbd>⌘</kbd><kbd>1</kbd> combination
* Restart Fork
* Restart macOS

**Comment by jespertheend** [comment]
Hi,

Strange indeed. Everything seems to be working fine for me now. I think I restarted fork somewhere between three days ago and now, so that probably fixed it. I'll let you know if it happens again.
I didn't know that ⌘1 worked as well by the way, that's nice :)

**Comment by jespertheend** [comment]
I just had the issue again, restarting fork fixed it. It's a minor issue and hard to replicate, so not too much of a problem. I'll let you know when I find out what's causing it.
