### ISSUE TITLE
[Bug] UI Issues with macOS 10.14 beta

### ISSUE THREAD

**Issue by tomaculum** [ForkIssues/Tracker#306]
Hi,

I am running Fork 1.0.67.5 on macOS 10.14 beta (18A293u) and saw some ui issues in the repository view as well as in the repository settings popup.

I assume this is easily reproducible. If not, please let me know and I will provide more information.

Best regards,
Tom

(Default theme and dark theme of Fork (not macOS dark mode))

<img width="219" alt="bildschirmfoto 2018-06-08 um 17 24 55" src="https://user-images.githubusercontent.com/16617007/41166709-45ec5cee-6b41-11e8-8e78-126cda78bd94.png">   <img width="217" alt="bildschirmfoto 2018-06-08 um 17 25 20" src="https://user-images.githubusercontent.com/16617007/41166708-45d19b5c-6b41-11e8-92fc-aef0b7f01d09.png">    

<img width="544" alt="bildschirmfoto 2018-06-08 um 17 24 32" src="https://user-images.githubusercontent.com/16617007/41166827-82bf7a0c-6b41-11e8-8d2a-f422c432b5b5.png">
<img width="522" alt="bildschirmfoto 2018-06-08 um 17 25 46" src="https://user-images.githubusercontent.com/16617007/41166826-82a5bacc-6b41-11e8-8f85-b1b1900909e2.png">

**Comment by tomaculum** [comment]
On a separate computer: MBP10,1
I have noticed this issues in the Fork dark theme as well and updated the screenshots above. And I do not know if this is somehow relevant but if I enable the dark mode in macOS there is no change to the above shown images - no font color change or something I have noticed.

**Comment by DanPristupov** [comment]
OK, I'm going install the Mojave beta as a VM and then have a look at the problems.

**Comment by DanPristupov** [comment]
Just sharing the status. I could not fix the problem yet, it requires more investigation.

**Comment by DanPristupov** [comment]
Tom, I improved a many things and made them available in the 1.0.68.2 prerelease. Could you please try it out? https://github.com/ForkIssues/Tracker/issues/318

- Fixed sidebar transparency
- Fixed incorrect layout in the commit view (lines did not match)
- The toolbar in the repository settings window was an OS X bug and has been fixed in beta 3.

**Comment by DanPristupov** [comment]
These fixes are available in 1.0.68 update.
