### ISSUE TITLE
"Repository Website" position in toolbar is not remembered

### ISSUE THREAD

**Issue by aziz** [ForkIssues/Tracker#31]
If I change the position of "Repository Website" toolbar button, it'll go back to its original position on the next launch. other buttons in the toolbar can be repositioned and their position is remembered and persisted across relaunches.

**Comment by DanPristupov** [comment]
Yes, I know this issue :). I'll check if I can fix it without spending much time (since there are more important things now).

**Comment by DanPristupov** [comment]
Should be fixed in 1.0.67 :)
