### ISSUE TITLE
Missing licensing policy

### ISSUE THREAD

**Issue by pshirshov** [ForkIssues/Tracker#312]
For some teams it's a showstopper.

Under some conditions (for example, in case you develop medical or fintec software) you can't use software which is close-sourced, has no any declaration of licensing conditions and it's completely unknown who is behind it. You may be even happy to pay for it - but you can't use it at all.

Please add the missing information and clarify the license.

**Comment by DanPristupov** [comment]
Is the common 'The software is provided "as is"' enough?

**Comment by pshirshov** [comment]
Unfortunately no. 
At least you should mention a legal entity which is developing the software, it may be a person but better a company.
When you need to add a typical EULA and a privacy policy mentioning if you collect any user data/stats/etc or no.
Otherwise it would not pass any fucking approval/validation process.

**Comment by DanPristupov** [comment]
OK, we have one now: https://forkapp.io/license.

> By the way, could you clarify if you are going to make the software paid in future please?

We are a family of two programmers and we can afford to keep Fork free. However it's absolutely possible that Fork will become paid in the future (with a **reasonable** price, **not** a subscription).

**Comment by Tricertops** [comment]
Just found this thread as my new employer also requires some legal boilerplate around the apps we use for development. One of the problems for them is the lack of Privacy Policy, which should be easy to add. It would also help if the software was sold by a company, not individual and if that company had security certification (whatever that means). I know that’s shitty, but I think there are some steps you @DanPristupov could make to target developers in big enterprises (they pay big money).

I’ve been using Fork for years and it’s the best git app I’ve ever had, but it’s simply _blocked_ our company machines for the reasons above. I now have to resort to some other git UI app, which I’m absolutely not happy about 🙁
