### ISSUE TITLE
Unwanted connections somewhere outside

### ISSUE THREAD

**Issue by pshirshov** [ForkIssues/Tracker#313]
Could you explain why Fork opens multiple https connections to different hosts in amazon cloud?

From all my understanding it's not neccessary for any kind of Fork functionality, so why is it required? Your app wouldn't pass an audit in a restricted environment because of that.

In case you are collecting application usage statistics, you should explicitly mention that before making any connections and let user to opt-out. 

Also, please keep in mind that  in EU it's illegal to collect any kind of personal information/telemetry/usage statistics and/or identifiers without letting your user know and letting him/her to opt-out. Please read about GDPR.

**Comment by DanPristupov** [comment]
Fork uses Fabric to track number of active users. You can disable that in Preferences.

**Comment by pshirshov** [comment]
Thank you for the hint. Though I guess you should ask for user's consent during first startup.

**Comment by zePanzerfaust** [comment]
Does this also apply to the windows version or did you completely disable the functionality?
I am missing such an option on Windows.

![fork-preferences](https://user-images.githubusercontent.com/14841658/42647148-6aa1aef4-8603-11e8-9661-ae9a6a447b21.png)

**Comment by DanPristupov** [comment]
@pshirshov thank you for reminding me. Yes, the option must be added to Windows version too.
