### ISSUE TITLE
CLI: "fork open" doesn't open current repository

### ISSUE THREAD

**Issue by takezoe** [ForkIssues/Tracker#315]
After I updated to 1.0.67.5 on Mac, `fork open` doesn't open the current repository in a new tab. It had been worked in earlier versions.

**Comment by luongvo209** [comment]
Hm. I wonder why don't use you `fork .` it will open the current directory in fork

**Comment by DanPristupov** [comment]
Fork has the `open` because of some historical reasons...

Simple `fork` (without the dot symbol) will open the current directory.

**Comment by takezoe** [comment]
Closed this issue because my problem was solved. Thanks!
