### ISSUE TITLE
Custom action for Xcode projects

### ISSUE THREAD

**Issue by artemnovichkov** [ForkIssues/Tracker#316]
Can I implement a custom action for opening Xcode projects/workspaces?

**Comment by DanPristupov** [comment]
Yes, you can. Is there any problem with that?

Just create an sh script with the following logic (didn't test):
```
#!/bin/sh
find . -maxdepth 1 -name '*.xcodeproj' | head -n 1 | open -a XCode
```
Set executable rights (chmod +x) and create a corresponding custom action call.

**Comment by artemnovichkov** [comment]
I have a function in .zshrc:
```bash
# Xcode via @orta
openx(){
  if test -n "$(find . -maxdepth 1 -name '*.xcworkspace' -print -quit)"
  then
    echo "Opening workspace"
    open *.xcworkspace
    return
  else
    if test -n "$(find . -maxdepth 1 -name '*.xcodeproj' -print -quit)"
    then
      echo "Opening project"
      open *.xcodeproj
      return
    else
      echo "Nothing found"
    fi
  fi
}
```
And have tried your script, saved to a file and added a path to custom action. The error for both cases:
![screen shot 2018-06-21 at 13 39 02](https://user-images.githubusercontent.com/5051597/41704696-bcf621b4-7558-11e8-82f7-56e40c47c0e9.png)

**Comment by DanPristupov** [comment]
`Unknown error` is my mistake which already got fixed but is not released yet. It happens when the file doesn't have executable rights.

**Comment by DanPristupov** [comment]
I made the following script called `openxcode`:

```
#!/bin/sh

  if test -n "$(find . -maxdepth 1 -name '*.xcworkspace' -print -quit)"
  then
    echo "Opening workspace"
    open *.xcworkspace
  else
    if test -n "$(find . -maxdepth 1 -name '*.xcodeproj' -print -quit)"
    then
      echo "Opening project"
      open *.xcodeproj
    else
      echo "Nothing found"
    fi
  fi
```

then did: `chmod +x openxcode`

Then created custom action:
<img width="454" alt="2018-06-21 at 09 52" src="https://user-images.githubusercontent.com/618115/41705275-d1b3308a-7538-11e8-9e30-77966d06734a.png">

It works.

**Comment by artemnovichkov** [comment]
@jt3k did it https://github.com/ForkIssues/Tracker/issues/370
