### ISSUE TITLE
Fork hangs while pre-commit scripts are running

### ISSUE THREAD

**Issue by uxuf** [ForkIssues/Tracker#317]
I have got a few sanity tests as well as a linter on a pre-commit hook. When committing, the UI becomes unresponsive as the pre-commit hook is running, with no indication of what's happening.

**Comment by ulope** [comment]
Related to #303

**Comment by DanPristupov** [comment]
Sorry for avoiding this. I'm going to fix the freeze in the next update (1.0.69)

**Comment by DanPristupov** [comment]
I created a `pre-commit` hook in the main Fork repository with the following content `sleep 5s`. I think it should boost the development ;)

**Comment by DanPristupov** [comment]
In 1.0.69 Fork performs commits as a background activity and don't freeze the UI.
