### ISSUE TITLE
ForkWin hangs on large files

### ISSUE THREAD

**Issue by ChadTaljaardt** [ForkIssues/Tracker#319]
When i open a large file using fork, it crashes when it tried to display the changes in that file.

**Comment by DanPristupov** [comment]
How large? What type of file?

**Comment by ChadTaljaardt** [comment]
@DanPristupov 360kb is the file size of one of the files it's crashing on. 

the file is a compiled CSS file for my web application. 

This is the only issue that is stopping me from switching over to fork, but every time I click the "Changes" button, where I have over 600files that have been built, it crashes the app.

**Comment by ChadTaljaardt** [comment]
I can send an example file if you'd like?

**Comment by DanPristupov** [comment]
@ChadTaljaardt that would be great! support@git-fork.com. Thank you

**Comment by ChadTaljaardt** [comment]
@DanPristupov Just emailed you :+1:
