### ISSUE TITLE
'Fork' doesn't display remotes with @ symbol

### ISSUE THREAD

**Issue by yutasa** [ForkIssues/Tracker#320]
v1.0.67.5 on mac

1. Clone any repo on Fork.
1. Edit "remote" manually on .git/config. For example, delete "remote" lines.
1. Add some remote. Either with or without Fork.
1. And try to fetch or push with Fork.
1. No "remotes" on Fork, and showin only 'Add New Remote'.
1. Adding the remote again, it says 'fatal: remote *** already exists.'
1. With reopening the tab, rebooting the app, or rebooting the machine, nothing changes.

of course, the remote can be handled via command line or some other clients like Sourcetree.

**Comment by DanPristupov** [comment]
I just added new remote to .git/config manually, everything works properly, Fork displays it immediately.

> 2. Edit "remote" manually on .git/config. For example, delete "remote" lines.

Why? Use `git remote rm xxx` instead? Otherwise dead remote branches will remain in the repository.

**Comment by yutasa** [comment]
i found it.
when remote name contains "@", it disappears.

**Comment by DanPristupov** [comment]
The bug must be fixed already.
