### ISSUE TITLE
Unable to watch new commits

### ISSUE THREAD

**Issue by artemnovichkov** [ForkIssues/Tracker#324]
I can't open commits after 29 June.  I guess it's not a fixed date.
![screen shot 2018-07-03 at 11 06 42](https://user-images.githubusercontent.com/5051597/42199606-2f1d0c2e-7eb1-11e8-8c39-871a87f741bd.png)

**Comment by DanPristupov** [comment]
@artemnovichkov could you check the log file which is located at `~/Library/Caches/Fork/Fork.log`? Or you can send it to me to support@git-fork.com

**Comment by artemnovichkov** [comment]
@DanPristupov have sent the logs.

**Comment by artemnovichkov** [comment]
It's my fault, used filters for master.
