### ISSUE TITLE
[Bug] Diff view doesn't scroll to top automatically

### ISSUE THREAD

**Issue by chiahsien** [ForkIssues/Tracker#326]
When I select a file, the diff view doesn't scroll to top automatically.

So I have to scroll to top manually (if the diff is more than one page long) every time when I select a file. I believe this should be a bug.

**Comment by maksimovic** [comment]
True. It's not a big deal usually, but these days it's bugging me more than usually since I'm on a mission to refactor big chunks of code, and self-code-review is itching me a bit because of this.

**Comment by chiahsien** [comment]
So, because something wrong with the cache design, first selected file doesn't scroll to top? Is it hard to fix? I can imagine it would be useful when I need to code-review and switch files back and forth.

**Comment by DanPristupov** [comment]
I just released 1.0.70 which automatically remembers and restores the scrollbar position.
