### ISSUE TITLE
External GitLab Account Support

### ISSUE THREAD

**Issue by Thejuse** [ForkIssues/Tracker#327]
hello,

can you add external Gitlab support? So that i can add my account der easy?

Thanks
Yours
jseidl

**Comment by Yoshi325** [comment]
I would also find External GitLab support a very useful feature.

**Comment by DanPristupov** [comment]
Hi. Yes. I'm working on this now.

Currently there's a problem in Fork with GitLab integration, because GitLab had changed their API and I didn't implement the support in time.

**Comment by Yoshi325** [comment]
Yay! And good luck accommodating the API changes.

**Comment by 2called-chaos** [comment]
Duplicates #34

<sub>_This action was performed by a bored human that looks for a perfect git client. I'm trying to reference all duplicates to make life easier for the maintainers and to show that we really want this feature._</sub>
