### ISSUE TITLE
[Feature request] Display repository status in tab title

### ISSUE THREAD

**Issue by evgeny-sureev** [ForkIssues/Tracker#332]
You can show in tab titles number of unpushed commits, number of commits to pull, uncommited local changes, etc.

**Comment by DanPristupov** [comment]
I thought few days about this. It seems to be an interesting idea on the first look. But what exactly should tabs show to be helpful?
- unpushed commits don't make much sense without an active repository name. Showing 'MyRepositoryName - feature/myfeature - (10↑5↓)' for **each** tab will be too noisy.
- number of uncommited changes doesn't really matter too. I think nobody cares about a particular number of changes. It will not change anyway when repository is a background tab. Instead users often need to know if repository contains **any** uncommitted changes. So, we can show  uncommited changes as a star symbol: 'MyRepositoryName*'.

**Comment by maksimovic** [comment]
Regarding changes not pulled/pushed: maybe without the branch name, those can get pretty lengthy, so just:

`MyRepositoryName - (10↑5↓)`

and, optionally if there are uncommited changes:

`MyRepositoryName* - (10↑5↓)`
