### ISSUE TITLE
Open Repository does not work on second drive on Windows

### ISSUE THREAD

**Issue by zePanzerfaust** [ForkIssues/Tracker#334]
Hello,

I cannot open a repository on a second drive D:\ on Windows.
"File" => "Open repository..." select the folder and click "Select Folder".
Fork does not load the repository, nor it displays anything.
Dragging the folder from the Explorer to Fork does open the repository.

If the repository is on the C:\ drive, both methods work.

Windows 10 Professional (10.0.17134)
Fork 1.18.1.0

**Comment by DanPristupov** [comment]
Hi. Could you repost your issue here please? https://github.com/ForkIssues/TrackerWin/issues

**Comment by zePanzerfaust** [comment]
Moved to https://github.com/ForkIssues/TrackerWin/issues/1
