### ISSUE TITLE
[Feature request] Option to never delete remote branches

### ISSUE THREAD

**Issue by james-rabbit** [ForkIssues/Tracker#335]
When I delete a local branch, Fork asks me if I would like to delete the remote branch too. There is also a right-click context menu that allows me to directly delete remote branches.

I never really want to delete remote branches, and I have done it by accident, so I would love a global option to disable that feature!

**Comment by Finesse** [comment]
It is [recommended](https://stackoverflow.com/q/29316225/1118709) to always delete stale unused branches.

**Comment by mezz** [comment]
I agree that is good practice. In this scenario these branches are used by coworkers or submitted as a PR for code review, I just add a commit or two and then delete my local branch. I use GitHub to delete remote branches after they are merged, it has a good interface for doing it without making mistakes.

**Comment by DanPristupov** [comment]
@james-rabbit wait, there's already an option, right? And it's even disabled by default.

Actually the workflow sounds slightly wrong. We track remote branches because we want them to be **linked** and behave correspondingly. It looks like you really need to have a local branch which doesn't strictly track the remote one (i.e. is independent). Then you can still push, but removing won't cause any other effects. Does it makes sense?

You can remote the tracking reference using the context menu:
<img width="576" alt="2018-07-13 at 15 10" src="https://user-images.githubusercontent.com/618115/42693357-317d4c12-86af-11e8-832d-cf5f671274e7.png">

**Comment by james-rabbit** [comment]
Hmm I'm not sure my workflow being wrong is that relevant here, but let me try to explain better with some scenarios I am in every day. 

### Scenario 1
I am doing code review on someone else's PR, and to test it I have checked out their branch locally.
When checking out a branch, it tracks the remote by default. This is good because I might have to submit a commit to fix up something.
Once everything in the review looks fine, I have approved the PR and I would like to delete my local branch.
It is not my branch, so I am not responsible for deleting the remote branch after it is merged.

### Scenario 2
For my own commits, I use Github to delete remote branches after they are merged. It has a button at the bottom of PRs to delete the branch, and also has a dedicated page which shows which branches have been merged and which still have open PRs so that I can delete stale or merged branches that I have forgotten. 
After the remote branch has been deleted, I delete my local branch that was tracking it.

### Request
Since there is no case in my workflow where I would intentionally delete a remote branch from Fork, I would love an option in the global preferences to hide these two items from the UI:

![delete-origin-rightclick](https://user-images.githubusercontent.com/28719012/42704998-bffb46ca-8686-11e8-92d9-240f83e8c846.png)
![delete-origin-confirm-menu](https://user-images.githubusercontent.com/28719012/42704997-bfe0bad0-8686-11e8-8d9f-99ed425d0893.png)

**Comment by james-rabbit** [comment]
I have not run into this issue again, and it is not getting interest from other users so I will close it.
