### ISSUE TITLE
[Feature request] Keep the window size when Fork is quitted and opened again

### ISSUE THREAD

**Issue by Finesse** [ForkIssues/Tracker#336]
Before the 1.0.68 update Fork saved its window size (when I resized the window) and restored it when I started the application.

Now the Fork window size is reset to default every time I quit and start the application. This is annoying as I need to resize the windows to a comfortable size every day. Could you please return the windows size behaviour back?

Fork: 1.0.68.4
macOS: 10.13.6

**Comment by Finesse** [comment]
@DanPristupov I also restores the last opened repositories. I didn't know about that. Thanks!

Keeping the repositories is not a big issue but keeping the window size is important IMHO.

**Comment by maksimovic** [comment]
In my case it never restores anything, even after `CMD`+`Q` - every time Fork starts, it offers bookmarks/recent repos :(

**Comment by DanPristupov** [comment]
@maksimovic what about this settings?  https://user-images.githubusercontent.com/618115/42635895-94e9fc00-85e7-11e8-9c14-1ad63d16fbbd.png

**Comment by maksimovic** [comment]
@DanPristupov FML. I had that ticked on 🤦‍♂️  All good now.

**Comment by DanPristupov** [comment]
What a BS Apple did. Why do we even need this settings ?.. :(
It looks like I need to start looking for a workaround to always restore the session.

**Comment by maksimovic** [comment]
Actually it's the first time I've noticed something different. And, wouldn't even know where to look unless you pointed me where to look at. I'd expect the settings to be on an application level (e.g. "Reopen windows"), not like this. I don't remember if it was ticked on by default, or maybe it was me looking around and checked it thinking it might be convenient.

**Comment by Finesse** [comment]
This is resolved. Thank you!
