### ISSUE TITLE
First item in "Open Quickly" dialog is too dark when using dark theme 

### ISSUE THREAD

**Issue by djdmbrwsk** [ForkIssues/Tracker#337]
![screen shot 2018-07-13 at 6 00 57 am](https://user-images.githubusercontent.com/886305/42686083-d9359952-8662-11e8-9346-9ba93fe427d1.png)

**Comment by DanPristupov** [comment]
Yes, confirm that. This is a recent 1.0.68 issue. I'll fix it in the next update.
