### ISSUE TITLE
When pulling, offer a "do not create a local merge" option

### ISSUE THREAD

**Issue by YesThatAllen** [ForkIssues/Tracker#339]
Currently there is a checkbox to "Rebase instead of merge" .

To be honest, I'm not sure that I know the difference in behavior

![2018-07-14_09-36-14](https://user-images.githubusercontent.com/2879972/42725465-5e5cbd04-8749-11e8-8ec7-4ca13c719b52.png)

What I don't want is to try to pull, and end up with a merge in my local that I don't intend to push up to github (etc)

not ideal: 
 
![2018-07-08_09-33-03](https://user-images.githubusercontent.com/2879972/42725451-1a56f1c4-8749-11e8-8017-4c36e81f953d.png)

I feel like this checkbox would be more awesome if it was "prevent me from doing something stupid"

 by that I mean: 
 - do pull from origin if it's at all possible while incorporating changes in my local

 - stop & take no action if brining origin in to the current branch/staged/working copy would have conflicts.

So, yes, on the surface the current checkbox is great. I think it could be made just a bit more awesome if it would prevent my from shooting myself in the foot with a merge commit of my local trash.

**Comment by luongvo209** [comment]
> To be honest, I'm not sure that I know the difference in behavior

I suggest that you read more about the difference of merge and rebase. 

> I feel like this checkbox would be more awesome if it was "prevent me from doing something stupid"

We should respect all users by using formal language. This is straightforward, but too explicit for a checkbox information.

**Comment by DanPristupov** [comment]
We've got a fast-forward pull in Fork 1.0.72.
