### ISSUE TITLE
Running `fork [open]` in subdirectory opens new tab for existing repo tab

### ISSUE THREAD

**Issue by jayrhynas** [ForkIssues/Tracker#341]
This may be due to the new tab & window system, but the behaviour of the `fork` CLI tool seems to have changed.

Previously, running `fork` in a git repo would open a tab for that repo, or switch to that tab if it's already open. That behaviour would hold no matter where in the subdirectories you ran the command.

Now, running `fork` from a subdirectory opens a tab named for that subdirectory. Each time `fork` is run form a different subdirectory, a new tab is opened for the same repo; it seems to be matching on the tab name/directory rather than the repo.

Fork Version 1.0.68.4

**Comment by DanPristupov** [comment]
That's a bug, obviously. It will be fixed in the next update. Thank you!
