### ISSUE TITLE
Feature request: init with .gitignore, LICENSE, and default README

### ISSUE THREAD

**Issue by texastoland** [ForkIssues/Tracker#342]
![GitKraken init wizard](https://user-images.githubusercontent.com/48431/42739407-673b129a-885c-11e8-9bbc-889a2cecda30.png)
Like GitHub or GitKraken. The latter can be local or upstream too.

**Comment by DanPristupov** [comment]
Great request, thank you!

**Comment by texastoland** [comment]
🙌🏽 thank you!
