### ISSUE TITLE
Feature request: Git bare repository

### ISSUE THREAD

**Issue by texastoland** [ForkIssues/Tracker#343]
I honestly don't know what app supports it but I use it for dotfiles per [Atlassian's writeup](https://developer.atlassian.com/blog/2016/02/best-way-to-store-dotfiles-git-bare-repo/). One way I got it to work in VS Code is `export GIT_DIR=$DOTFILES_REPO; export GIT_WORK_TREE=~; code-insiders ~`.

**Comment by DanPristupov** [comment]
Is that a duplicate? https://github.com/ForkIssues/Tracker/issues/247

**Comment by texastoland** [comment]
🙊 indeed I searched it in vscode but not here.
