### ISSUE TITLE
When restoring a previous session, tab names don't respect custom repository names

### ISSUE THREAD

**Issue by maksimovic** [ForkIssues/Tracker#344]
- Have a repository renamed, e.g. like this:
<img width="1274" alt="this_repo_has_a_custom_name" src="https://user-images.githubusercontent.com/1126226/42747670-aa7abf16-88dd-11e8-8e99-649a8bab3abb.png">

- Quit Fork and open it again

- Now the tab title displays the directory name where the repository is located at:
<img width="1273" alt="contributions-demo" src="https://user-images.githubusercontent.com/1126226/42747710-ca813d3a-88dd-11e8-90df-c56376c97afc.png">

**Comment by DanPristupov** [comment]
Thanks. I'm planning to release the bugfix release by the end of the week.
