### ISSUE TITLE
Suggestion: improve revision graph drawing

### ISSUE THREAD

**Issue by jakob** [ForkIssues/Tracker#345]
In some cases the branch view can be a bit confusing.

Instead of explaining, let me show an example:

<img width="554" src="https://user-images.githubusercontent.com/198305/42747727-d6c86a46-88dd-11e8-96bc-fc9129c8caeb.png">

I thought that the brown branch originates from master "Merge Pull Request 44" but in reality the branch starts somewhere further down.

I think it would be best to use different curves for "branching" and "lane changes". Lane changes shouldn't be angular, but smooth.

Here's what I mean:

<img width="300" src="https://user-images.githubusercontent.com/198305/42748115-3829cd9c-88df-11e8-8eb2-ed469da60a85.jpg">

What do you think?

**Comment by maksimovic** [comment]
Indeed, it can be rather hard to figure out who branched from which poin. Another example:

<img width="564" alt="valtari" src="https://user-images.githubusercontent.com/1126226/42748609-16b0e0fe-88e1-11e8-8a3e-eea9f4d0597c.png">

**Comment by maksimovic** [comment]
Just don't sacrifice the performance, it's one of the main Fork's selling points for me.

The flow can be figured out, just with paying a bit more attention.

**Comment by DanPristupov** [comment]
@maksimovic graph visualization used to be a bottleneck, but about 10 versions ago I made it lazy, so it calculates only the visible area. So, ideally the algorithm must be lazy.

Could you run `git log --all --pretty="%h|%p|%d" `, past the output here http://bit-booster.com/graph.html and share the result?

Here are some other existing implementations:
- https://marketplace.atlassian.com/apps/1212520/git-flow-chart?hosting=cloud&tab=overview
- https://marketplace.atlassian.com/apps/1212147/charts-graphs-for-bitbucket?hosting=server&tab=overview
- https://marketplace.atlassian.com/apps/1219256/commit-graph-for-bitbucket-server?hosting=server&tab=overview

**Comment by jakob** [comment]
@DanPristupov Thank you for your consideration. I know it's a hard problem (I've done some graph layout and drawing before).

I'm not suggesting to actually change the layout of the graph (the hard part). I think the layout is fine. I'm only suggesting a small change to the way that the actual bezier paths are drawn:

- make lines angular where they meet (either merge or branch)
- make lines smooth when they do not meet

It should have very little performance impact, since it would only affect the drawing of a few bezier paths that are on screen.

I can try to build a small example app with the drawing code that I have in mind, I just wonder how to do it without having to write all the graph layout code...

**Comment by DanPristupov** [comment]
@jakob yes, it makes sense. I'll check the code and try to draw a different connection type for that case.

P.S. However different connection drawing won't help much in @maksimovic's case.

**Comment by DanPristupov** [comment]
@jakob do you use date commit order? I think commit graph can be improved in your case if you use topo-order in Fork preference.

**Comment by maksimovic** [comment]
I'm using topological sort, but I don't think that very complex/edge cases are worth the struggle.

The congestion screenshoted above in bit-booster's version:

<img width="828" alt="screen shot 2018-07-16 at 11 00 31 am" src="https://user-images.githubusercontent.com/1126226/42750597-165211ee-88e8-11e8-819e-10b159e848cd.png">

**Comment by jakob** [comment]
@DanPristupov I just checked and topological order is selected. It indeed looks better than date order.

Just to repeat: I have no complaints about the layout itself. It's very clear most of the time, and I really like the graph view in fork. My only complaint is about the way that the bezier curves are drawn. I think the problem is that they are angled on one side, and smooth on the other side -- most of the examples you linked above are either angled on both sides, or smooth on both sides.

I'll try to write some example code and share it here later (I like writing drawing code!)

**Comment by DanPristupov** [comment]
What do you think guys?

Before:
<img width="186" alt="2018-07-16 at 11 51" src="https://user-images.githubusercontent.com/618115/42752560-96e21af6-88ee-11e8-9f3f-5f60486972c2.png">

After:
<img width="191" alt="2018-07-16 at 11 50" src="https://user-images.githubusercontent.com/618115/42752537-884ca4a2-88ee-11e8-871d-b3befc3f79a2.png">

**Comment by DanPristupov** [comment]
Case (2):

Before:
<img width="130" alt="2018-07-16 at 11 53" src="https://user-images.githubusercontent.com/618115/42752649-db2075f0-88ee-11e8-92fd-af4c60609588.png">

After: 
<img width="135" alt="2018-07-16 at 11 53" src="https://user-images.githubusercontent.com/618115/42752683-f6953aaa-88ee-11e8-982a-a66abc152721.png">

**Comment by maksimovic** [comment]
Wow, that's nice!

Do you still think it's going to affect performance? If yes, then I'm willing take some pre-release for a spin to check how it's behaving here.

**Comment by DanPristupov** [comment]
No, actually it would be even a bit faster. When one returns to an algorithm he/she spent a lot of time on in the past, often new ideas come out of nowhere :).

I'm going to tweak the curves a bit more and then share the pre-release.

**Comment by jakob** [comment]
@DanPristupov Thanks for the explanations, I think I understand now. I see why it is not so trivial as I imagined.

Anyway, the new version definitely looks less confusing, but I think your old version looks prettier...

**Comment by DanPristupov** [comment]
@jakob yes, I agree. Here's an improved version. I think it's better.

1st case:
Before/improved/now:
<img width="186" alt="2018-07-16 at 11 51" src="https://user-images.githubusercontent.com/618115/42752560-96e21af6-88ee-11e8-9f3f-5f60486972c2.png"> <img width="191" alt="2018-07-16 at 11 50" src="https://user-images.githubusercontent.com/618115/42752537-884ca4a2-88ee-11e8-871d-b3befc3f79a2.png"> <img width="197" alt="2018-07-16 at 14 14" src="https://user-images.githubusercontent.com/618115/42758131-b023b70e-8902-11e8-9897-abbe7bd4f43c.png">

2nd case:
Before/improved/now:
<img width="130" alt="2018-07-16 at 11 53" src="https://user-images.githubusercontent.com/618115/42752649-db2075f0-88ee-11e8-92fd-af4c60609588.png"> <img width="135" alt="2018-07-16 at 11 53" src="https://user-images.githubusercontent.com/618115/42752683-f6953aaa-88ee-11e8-982a-a66abc152721.png"> <img width="134" alt="2018-07-16 at 14 21" src="https://user-images.githubusercontent.com/618115/42758374-93ba108a-8903-11e8-9b0b-f1fa91ccf438.png">

I'm quite happy with the latest result now.

You can try it yourselves: http://git-fork.com/update/files/Fork-1.0.68.5.dmg.

P.S. Since we are here, this version also contains the improved commit description field in the commit view. It resizes automatically relying on the context.

**Comment by maksimovic** [comment]
Way better. Unfortunately, I can't reproduce my original screenshot in the new fashion because the log is now quite different and I'm actually lacking horizontal space there (btw, are we going to be able to resize columns in the log view sometimes?)

However, here's another complex case which is now surprisingly good-looking:
<img width="446" alt="screen shot 2018-07-16 at 3 06 12 pm" src="https://user-images.githubusercontent.com/1126226/42760168-de928c44-8909-11e8-80fa-9c2ec982bc88.png">

**Comment by jakob** [comment]
@DanPristupov looks a lot better now! Here's a screenshot of the part that I initially complained about:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/198305/42762525-df3978b8-8910-11e8-8ba4-9eba0fe555ad.png">

Looks beautiful!

**Comment by DanPristupov** [comment]
@jakob looks really great now. Thank you very much for starting this issue initially!

**Comment by jakob** [comment]
Perfect. Should I close the issue or do you want to leave it open?

**Comment by DanPristupov** [comment]
Leave it open please. I will review the issues after the public release of the new version and take care of it.

**Comment by rbukovansky** [comment]
Hi there,
as requested by Dan per my complaint about those branch/merge curves looking little bit weird (for me they look like first attempt of rounded corners of Photoshop beginner; I do believe you do remember websites with it), so I'm attaching screenshots from my favorite Git GUI client GitKraken and Sourcetree which is used in company I'm working for. GitKraken is using normally rounded corners and Sourcetree is using straight skewed (right word?) lines. I'm not saying they are perfect, but they look better to me... For now...

If you want me to try them on something more complicated, please give me URL of repo. Thanks.

GitKraken:
![screen shot 2018-07-24 at 11 46 01](https://user-images.githubusercontent.com/1004491/43130723-9045a7f4-8f37-11e8-87d5-64cfdc3d02d0.png)

Sourcetree:
![screen shot 2018-07-24 at 11 47 10](https://user-images.githubusercontent.com/1004491/43130724-90605e1e-8f37-11e8-83af-d9d68c9b4d0f.png)
