### ISSUE TITLE
Require 'force delete' checkbox for deleting unmerged branches

### ISSUE THREAD

**Issue by syedrakib** [ForkIssues/Tracker#348]
I like the behavior in sourcetree which is safer. By default it deletes a branch well and nice: `-d`. But if attempting to delete an unmerged branch, then it prevents from deleting that branch and instead requires to check a `Force Delete` option: `-D`. This much safer.

**Comment by syedrakib** [comment]
Sorry guys. Spoke too soon. Looks like it's already there in a dialog.

**Comment by borisrorsvort** [comment]
Seems this has disappeared again 😢

**Comment by DanPristupov** [comment]
<img width="510" alt="Screenshot 2020-05-11 at 23 18 42" src="https://user-images.githubusercontent.com/618115/81612854-c3c8e580-93dd-11ea-9000-91374d49f98e.png">
