### ISSUE TITLE
Fork crashes while restoring session

### ISSUE THREAD

**Issue by Niels-NTG** [ForkIssues/Tracker#349]
Fork 1.0.68.4 on MacOS 10.13.6 crashes every time when restoring its window and tabs configuration from the last session. I had a single window with 4 tabs open, all of them submodule repositories. When Fork offers me to recover the session, it crashes again. 

I have attached the error log below.

[20180717 Fork 2459 crash log.txt](https://github.com/ForkIssues/Tracker/files/2200838/20180717.Fork.2459.crash.log.txt)

**Comment by DanPristupov** [comment]
Did you manage to solve this problem?

**Comment by Niels-NTG** [comment]
Without me changing anything, it hasn't occurred again.
