### ISSUE TITLE
Fetch remote changes automatically

### ISSUE THREAD

**Issue by duxet** [ForkIssues/Tracker#35]
It would be awesome to have possibility to automatically fetch remote changes every few minutes.

**Comment by DanPristupov** [comment]
Yes, I agree. I personally miss this feature too :).

**Comment by petterikamppuririchie** [comment]
Yeah, I just tested our app with wrong code because Fork doesn't fetch changes and show unpulled commits automatically.

**Comment by DanPristupov** [comment]
OK, make this feature the top priority. Hopefully we gonna have it in the next release.

**Comment by petterikamppuririchie** [comment]
Thank you very much! This has been one thing Sourcetree does better :) (I want to get rid of it :) Just to pile stuff here: another thing I like about Sourcetree is non-modal history browsing.

**Comment by DanPristupov** [comment]
@petterikamppuririchie Could you please create a separate issue for non-modal file history, so we don't bother other people in this topic?

**Comment by petterikamppuririchie** [comment]
Sure, it wasn't a feature request per se, more of a wish :) But will create a separate request.

**Comment by DanPristupov** [comment]
Sorry guys. I spent too much time working on merge conflict resolver and already delayed the release, so could not implement automatic fetch in time. Will add it in the next update.

**Comment by petterikamppuririchie** [comment]
No worries, I still have Sourcetree :) Merge conflict resolving has been another thing I've been using Sourcetree for, actually. Looking forward to improvements :)

**Comment by DanPristupov** [comment]
Hi. The automatic fetch is going to appear in Fork 1.0.67. You can try it already in the early-access release: https://github.com/ForkIssues/Tracker/issues/287

Few notes:
- Fork automatically fetches all remotes in open tabs every 20 minutes
- You can disable auto-fetch for a particular remote
![2018-05-21 at 18 01](https://user-images.githubusercontent.com/618115/40317207-1d1cb35a-5d21-11e8-89f9-8144836a5a60.png)
- You can disable automatic fetch globally in Fork preferences

**Comment by joshallenit** [comment]
Glad I found this in preferences, because it sure is annoying trying to find the commit you want to rebase against when this is turned on :) Otherwise ❤️  Fork
