### ISSUE TITLE
Submodules with the same name across multiple repos are not longer distinguishable since 1.0.68

### ISSUE THREAD

**Issue by mattijsf** [ForkIssues/Tracker#350]
I maintain several projects which contain submodules with the same name. Consider the following structure:
- `app1` (repo) -> `core` (submodule)
- `app2` (repo) -> `core` (submodule)

On the previous version when I would open the two repos + their submodules I could observe the following tabs:
- `app1`
- `app1: core`
- `app2`
- `app2: core`

Since 1.0.68 I have the following tabs:
- `app1`
- `core`
- `app2`
- `core`

The equally named submodules (which is quite common) can no longer be distinguished

**Comment by DanPristupov** [comment]
Hi. Thank you for reporting that. That's already fixed and the fix will be a part of 1.0.69 update.

**Comment by DanPristupov** [comment]
I've just released 1.0.69 with the hotfix

**Comment by mattijsf** [comment]
Got the update. It works now! Thanks!

**Comment by DanPristupov** [comment]
Thank you for the confirmation.
