### ISSUE TITLE
1.0.69 loading repo seems to take longer than previous version

### ISSUE THREAD

**Issue by ooopscc** [ForkIssues/Tracker#359]
Not sure if it is window restore issue, but what I feel is Fork takes more time to load repo first time when open from terminal by using fork command. I hope fork can keep high performance when adding new feature or fixing bugs, because that's a key advantage than SourceTree.

**Comment by DanPristupov** [comment]
How much longer? On my computer it takes about a second to show the Fork window.

**Comment by DanPristupov** [comment]
@ooopscc I don't remember myself doing anything in this area. Can you contact me by email support@git-fork.com so I could find out the bottle neck faster?

**Comment by DanPristupov** [comment]
I think we can close this issue.
BTW, in Fork 1.0.72 repositories should be loaded much faster.
