### ISSUE TITLE
⌘W should close last open window

### ISSUE THREAD

**Issue by jbergstroem** [ForkIssues/Tracker#36]
It currently has a 'untitled' tab which quickly reopens again.

**Comment by dmay** [comment]
⌘W Should close window if it only has one tab, you mean?
I would  +1 it.

```
[        Window        ]
[   Rep1   ][   Rep2   ]

⌘W

[        Window        ]
[         Rep1         ]

⌘W
```

Expected:

```
No window
```

Actual:

```
[        Window        ]
[       Untitled       ]
```

**Comment by jbergstroem** [comment]
> @dmay said:
> ⌘W Should close window if it only has one tab, you mean?

Yeah; a more descriptive comment could have been connecting the analogy of "one window" = "one window with tab", but since fork is basically one window only, I didn't. Thanks for clarifying!

**Comment by DanPristupov** [comment]
There's an option in the preferences: `Quit when all tabs are closed`.

And yes, currently Fork is limited to 1 window (which is a mistake which I didn't realize at the time).

**Comment by joshuajabbour** [comment]
Yes, the preference will mostly work for me, but this is how I'd ideally like it to work:

- cmd-w closes each tab, one at at time
- with one tab remaining, cmd-w closes last tab
- shows window with repository list (as it currently does). probably needs a better name than "Untitled" however
- cmd-w again closes the entire window (or I guess in this case, quits the app)

I think the preference could be removed, as the above is how Mac apps generally work (the quitting is unusual, so maybe this needs to wait until it supports multiple windows)
