### ISSUE TITLE
Accidentally rename a repo causes another repo to be renamed

### ISSUE THREAD

**Issue by kuthair** [ForkIssues/Tracker#362]
In the Repository Manager, it's way too easy to rename a repo. I click on the name to open it and instead immediately find myself renaming a repo.

That's not the only problem.

Trying to cancel the rename, causes a **DIFFERENT** repo to be renamed.

I've attached a video of the problem -- this video can be opened in QuickTime on Mac.

In my repo manager, I click on the "saas-tracking" repo -- inadvertently activating the rename feature. Then when I hit enter (to keep the name the same) the "blue-laurel" repo at the top is renamed to "saas-tracking", resulting in 2 identically named repos.

[fork-rename-bug.zip](https://github.com/ForkIssues/Tracker/files/2229300/fork-rename-bug.zip)

**Comment by DanPristupov** [comment]
Thank you for reporting that. I'll fix fix this in the next update.

**Comment by opotapov-sygic** [comment]
Yop. This happens also when opening new tab and clicking on a repo. This triggers "rename" action and then follows the @kuthair's description.

**Comment by peterfox** [comment]
Found this happening to me this week

**Comment by IrishAdo** [comment]
This issue is no longer effecting me so this issue should be closed.

**Comment by kuthair** [comment]
Issue resolved for also. Thank you.
