### ISSUE TITLE
Automatically create remote "upstream" when cloning a fork

### ISSUE THREAD

**Issue by texastoland** [ForkIssues/Tracker#363]
A couple times a week, before I PR, I need to add the remote "upstream" for the source project. It'd help if that were automatic like "origin". It'd be nice to suggest remotes from the network when adding other remotes, but much less common.

**Comment by DanPristupov** [comment]
Yes, I know the problem. Every time I need to update a fresh repository fork, I need to go to GitHub and copy the upstream url.

I think I can fetch that info from GitHub and pre-populate the address field in the Add Remote dialog.

I'm absolutely sure we should not create a remote **automatically**, but suggest that action to user.

Do you see any other ways how we can suggest the "upstream" remote url politely?

**Comment by maksimovic** [comment]
Can you dynamically show (or not) an additional checkbox in the Clone dialogue, after the repository URL is entered and you're sure you can get the upstream repository?

It could be done for "Other" repository type there as well, based on the URL (e.g. I don't have GitHub integration enabled).

**Comment by texastoland** [comment]
> I'm absolutely sure we should not create a remote automatically, but suggest that action to user.

Is there any use case the upstream remote might be undesirable?

**Comment by texastoland** [comment]
Or better in the preferences since no one should click it ever.

**Comment by texastoland** [comment]
Better idea!! An input field for upstream remote. It would be empty unless a fork then filled with its source repo. Any other fork could be selected from a dropdown.

**Comment by tbussmann** [comment]
What did happen to this feature request? Why was it closed? As far as I can see, this was not implemented yet but would be quite useful.

**Comment by tbussmann** [comment]
@DanPristupov could you reopen this FR again? I think it was closed in error.
