### ISSUE TITLE
Dark Theme: Icons are barely visible for highlighted sidebar items

### ISSUE THREAD

**Issue by herrherrmann** [ForkIssues/Tracker#364]
While the text of a highlighted sidebar menu item turns black, the icon stays grey-ish and has almost the same color as the highlight background color.

![2018-07-29 13 33 11](https://user-images.githubusercontent.com/6429568/43365899-525afc0e-9334-11e8-956c-9a200b9cd00e.gif)

…so, maybe the icons should also turn to black when highlighted?

**Comment by luongvo209** [comment]
Yeah I can confirm that this has been present for a long time. Maybe you should consider changing the  color of the icon @DanPristupov !?

**Comment by noheger** [comment]
Same issue in light mode:

![image](https://user-images.githubusercontent.com/42006266/43543279-cfeeb56e-95cf-11e8-922e-90b16f707f27.png)

Actually, it should be sufficient to turn those icons into template images, for example by appending “Template” to the icon’s name. They are monochrome anyway, so they are perfectly suited for being used as templates. Cocoa will then invert the color automatically on dark backgrounds (i.e. when highlighted).

See also:
https://developer.apple.com/documentation/appkit/nsimage/1520017-template

**Comment by DanPristupov** [comment]
@noheger not sure if I'm doing something wrong but template images are drawn incorrectly when I use them in translucent TableView/OutlineView. The transparent background is visible!

May be I'm missing something...

Light theme, selected, active:
<img width="228" alt="2018-08-08 at 07 36" src="https://user-images.githubusercontent.com/618115/43818190-c821b83c-9add-11e8-9be5-aff234a660a1.png">

Light theme, selected, inactive: 
<img width="231" alt="2018-08-08 at 07 35" src="https://user-images.githubusercontent.com/618115/43818174-b8356644-9add-11e8-87bb-678f4de8de75.png">

It's even worse in dark mode:
<img width="228" alt="2018-08-08 at 07 39" src="https://user-images.githubusercontent.com/618115/43818282-3355ab72-9ade-11e8-925c-2085abe7d695.png">

**Comment by noheger** [comment]
Is this a regular `NSImageView` in the sidebar? You might try subclassing the image view and override `allowsVibrancy` to return `NO`.

**Comment by noheger** [comment]
@DanPristupov Is this a regular `NSImageView` in the sidebar? You might try subclassing the image view and override `allowsVibrancy` to return `NO`.

**Comment by DanPristupov** [comment]
@noheger that's a good point. I'll try. Thank you.

**Comment by DanPristupov** [comment]
@noheger Aaaa! It works! 
Thank you very much, I spent so much time looking for a way to fix it! 🎉

**Comment by elia** [comment]
Fixed!

<img width="198" alt="image" src="https://user-images.githubusercontent.com/1051/47799267-34dc0700-dd2a-11e8-8f86-bba3a8bfd3d2.png">
