### ISSUE TITLE
Entering emoji at repo search can crash Fork

### ISSUE THREAD

**Issue by ngyikp** [ForkIssues/Tracker#365]
Copy this emoji -> 😀
Then paste it to the top-right repo search, Fork will instantly crash

Fork version 1.0.69.4
macOS 10.13.6

**Comment by DanPristupov** [comment]
Thank you for the bug report. I've no idea how you found that :)

Dan Pristupov

**Comment by hyarion** [comment]
Still got this issue on 1.0.71.2.
Sometimes we use 👾 to indicate white space removal at work. Searching for them is a bit tricky currently.
After some testing it looks like Fork supports 3 byte UTF-8 characters but not when they are 4 bytes.
Using emoji's in commit messages might not be best practice but there are other 4-byte UTF-8 characters that could cause problems too. Like 𩸽, which also crashes the program.

**Comment by DanPristupov** [comment]
Fixed in 1.0.72

**Comment by hyarion** [comment]
Works perfect, thanks! 👍
