### ISSUE TITLE
"stash and reapply" in the pull dialog

### ISSUE THREAD

**Issue by jt3k** [ForkIssues/Tracker#367]
Can we make a stash before pull if there are uncommitted changes?

I often have to do this manually:

1. I am working on task A
2. Then I push it and in the same branch I do task B
3. Ok, now I need to do push task B
4. I need to switch to the master branch to create a new branch here.
5. I switch to the master, and here there is an option "stash and reapply". I want the same option for the pull dialog.

Because before pull I have to do a stash and then apply stash

UPD: hmm, it seems preferences -> Custom Actions can help me solve this problem

But still I would like to have a built-in feature

**Comment by DanPristupov** [comment]
Hi,

You mean, same as in the checkout branch dialog?

Dan Pristupov

**Comment by jt3k** [comment]
@DanPristupov Yes exactly

**Comment by DanPristupov** [comment]
Done in 1.0.72
