### ISSUE TITLE
[Feature request] Add --ff-only option to Repository / Pull

### ISSUE THREAD

**Issue by bsamuel-ui** [ForkIssues/Tracker#368]
User story:

> As a user, I often want to update a branch to the latest remote tracking branch, and see an error if a merge needs to be done rather than take any automated action. In particular, on a busy repo, I may run "Repository/Fetch", see no updates, and then "Repository/Pull" and have a merge or rebase performed without my knowledge. On the command-line, this is what I'd use `git pull --ff-only` to accomplish.

Existing ways to accomplish this:

1. Repository / Pull without "pull instead of rebase": 
  * `git pull` will attempt to create a merge commit, which I may not want.
2. Repository / Pull with "pull instead of rebase": 
  * `git pull --rebase` will attempt to rebase my changes against the upstream, which I may not want.
3. Repository / Fetch and the Repository / Pull:
  * It doesn't actually do a merge, so there is a potential race condition on a busy branch.
  * In a real-life repo, I have to scrutinize the branches fairly carefully to perform a very simple task.
4. Repository / Fetch, find the tracking branch, right-click Merge into branch:
  * This definitely works, though it's not obvious and error prone.
  * It's easier to drop into a terminal.

Priority: This is not a blocker, but I think it's an option an experienced git user is likely to look for.

This may be a dupe of #339, though that issue's description is not clear.

**Comment by DanPristupov** [comment]
I have some ideas which I'd like to discuss when I'm back from my vacation. As for now, you can create a repository-wide custom action, right?

Dan Pristupov

**Comment by bsamuel-ui** [comment]
Ah, never noticed custom actions. Go vacation harder!

**Comment by DanPristupov** [comment]
I introduced ability to pull a branch, without checking it out (`Fast-forward pull`) in Fork 1.0.72.

<img width="516" alt="screenshot 2018-12-01 at 17 03 31" src="https://user-images.githubusercontent.com/618115/49330149-16686600-f58b-11e8-9fc2-abb3e96325fa.png">

**Comment by bsamuel-ui** [comment]
That's an excellent solution for merging other branches! I had a custom action to jump through the "git fetch . origin/master:master" hoops, but this meets that need nicely. As pulling the active branch with `--ff-only` can be cleanly solved with a custom action, I'm closing the ticket.

**Comment by DanPristupov** [comment]
@bsamuel-ui in the next version I'll update the 'Fast-forward Pull' to pull with the `--ff-only` option if we call it for the *active* local branch. Then you'll be able to remove your other custom action :).
