### ISSUE TITLE
Dark Theme: Toolbar icons dim with 'Increased Contrast'

### ISSUE THREAD

**Issue by n4580** [ForkIssues/Tracker#369]
The dark theme's toolbar icons are extremely difficult to see while using the Increased Contrast accessibility setting on macOS (System Preferences -> Accessibility -> Display -> Increased contrast).
![image](https://user-images.githubusercontent.com/11352747/43437043-bad9fd34-944c-11e8-99d3-4202518c95d1.png)

**Comment by elia** [comment]
Looks like it's fixed 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1051/47799199-137b1b00-dd2a-11e8-917c-3c24826c8790.png">
