### ISSUE TITLE
Interactive rebase: reword is quirky

### ISSUE THREAD

**Issue by jbergstroem** [ForkIssues/Tracker#37]
Using: 1.0.47.

When choosing "reword" during an interactive rebase, you get greeted with a small dropdown note. If you leave focus (for instance, copy pasting a url from your browser to add for metadata), the dropdown disappears and any info you've previously put into it is gone.

I think this highlights a design problem rather than stickiness/state.

**Comment by DanPristupov** [comment]
Hi.

Yes, I agree. There is a design problem.

As for now I can do the following improvements:
1. Keep the dropdown open when application loses focus.
2. Save and restore incomplete message if user accidentally close the dropdown.

**Comment by DanPristupov** [comment]
I improved the reword popover in Fork 1.0.48. Now it remembers the message drafts.
