### ISSUE TITLE
Keyboard shortcut for Commit does not work

### ISSUE THREAD

**Issue by jgoldhammer** [ForkIssues/Tracker#372]
When I have entered a commit for some staged changes, I cannot commit via keyboard. I always have to click on the button via mouse. Even the commit in the repository menu does not work...

Thanks
Jens

**Comment by jgoldhammer** [comment]
?

**Comment by DanPristupov** [comment]
Sorry, I just returned from my vacation.
So, you are saying <kbd>⌘</kbd><kbd>Enter</kbd> doesn't work?

**Comment by jgoldhammer** [comment]
Only mouse click on the commit button in the ui works- no shortcut and no commit entry in the repository menu...

**Comment by 2called-chaos** [comment]
works for me (enter to stage, cmd+shift+c to jump to commit, type subject and press cmd+enter to actually commit)
