### ISSUE TITLE
New tab opens new window

### ISSUE THREAD

**Issue by neemanjabu** [ForkIssues/Tracker#375]
- OS: **Mac OS** X El Capitain 10.1.16
- Fork: 1.0.69.4

Steps to reproduce:
- **Click on File / New Tab**

Expected result:
- New tab is opened within the same window 

Result:
- **New window is opened**

**Comment by DanPristupov** [comment]
Fork uses native tabs which are supported starting from macOS Sierra.

**Comment by neemanjabu** [comment]
Confirmed it works on Sierra.
