### ISSUE TITLE
Changes count is not updated

### ISSUE THREAD

**Issue by neemanjabu** [ForkIssues/Tracker#376]
- OS: Mac OS X El Capitain 10.1.16
- Fork: 1.0.69.4

Steps to reproduce:

- Make change in one file
- Changes count updated to 1
- Commit and push previously made update

Expected result:

- Changes count does not exist

Result:

- Changes count remains the same

![fork_changes_issue](https://user-images.githubusercontent.com/2862818/43807593-7d6b00b6-9aa9-11e8-8edc-1ce40eeca3ce.png)

**Comment by DanPristupov** [comment]
Can you reproduce this problem twice?

**Comment by neemanjabu** [comment]
Yes, it happens every time changes are made or discarded.
Count is updated correctly only if repository is closed and reopened.

**Comment by BrElio** [comment]
Same issue here with:

Mac OS X El Capitain 10.11.6
Fork 1.0.70

**Comment by DanPristupov** [comment]
@BrElio do you know how to reproduce the issue?

**Comment by BrElio** [comment]
Hi, there's nothing to do to replicate it, the issue is there since I launch the program.
When it starts it shows the correct number of changes to commit. If I make any other change it won't update. If I stage and commit the changes the number doesn't update either.

**Comment by DanPristupov** [comment]
This might be fixed in 1.0.72
