### ISSUE TITLE
Please Bundle git Binary within Fork.app

### ISSUE THREAD

**Issue by luxlogica** [ForkIssues/Tracker#38]
Downloaded Fork, but was disappointed to see that it requires me to instal developer command-line tools. Trying to do any operations without the tools installed immediately brings up a dialog offering to instal them for me.

<img width="507" alt="screen shot 2017-05-30 at 4 12 12 pm" src="https://cloud.githubusercontent.com/assets/2994472/26570265/dbb7553c-4552-11e7-9b37-62accf52eeba.png">

I am a web developer that uses version control on a daily basis. I do **not** want to have Xcode or the command-line developer tools installed in my computer - I try to keep my base system as lean as possible. 

Other competing products - such as [Tower](https://www.git-tower.com/mac/) - bundle their own version of git within the app binary itself. Alternatively, they also allow us through Preferences to set the location of our custom, pre-installed git binary - in case we want a newer version of git than the one bundled with the app.

**Comment by DanPristupov** [comment]
Hi.

This is a good point. I'll add an option to select a custom git instance in the next update.

Regarding the git bundling. I need to implement incremental/partial updates for Fork to prevent excessive downloads. Then I will also be able to bungle a whole git instance in the app.

**Comment by DanPristupov** [comment]
I just released Fork 1.0.49 with an option to select a custom git binary. I'll keep an eye on the feedback and if everything is stable, I'll bundle a standalone git into Fork.

**Comment by DanPristupov** [comment]
In Fork 1.0.52 I bundled git binary into the app. Please let me know if you notice any problem.
