### ISSUE TITLE
Bug: Using arrow keys on Unstaged Files and pressing Enter to stage it.

### ISSUE THREAD

**Issue by kkorus** [ForkIssues/Tracker#380]
Windows, ver: 1.19.0.0

When I'm using arrow keys (up/down) on "Unstaged Files" and press `Enter` when I want to add something to "Staged Files" , pressing again arrow keys to go to next file it jumps to first one file on list instead of to next one.

**Comment by DanPristupov** [comment]
Could you repost this issue to the Windows version issue tracker? 
https://github.com/ForkIssues/TrackerWin
