### ISSUE TITLE
[Feature Request] Make Dark theme change along with macOS Mojave Dark Mode

### ISSUE THREAD

**Issue by Reggian** [ForkIssues/Tracker#381]
It would be nice if the Dark theme would automatically change along with macOS Mojave Dark Mode changes (similar as Xcode does).

Maybe have options: _Light_, _Dark_, _Automatic_
where the latter would observe the system theme.

**Comment by Reggian** [comment]
Introduced with Fork 1.0.71.
Thanks!

**Comment by DanPristupov** [comment]
Thank you for closing the issue. I forgot about it :)
