### ISSUE TITLE
[FEATURE] Repo manager categorisation.

### ISSUE THREAD

**Issue by IrishAdo** [ForkIssues/Tracker#384]
It would be great to be able o group certain repos together so that different projects have all repos together and my personal repos are not visible while in work (ie I minimise the "Personal" category/folder)

**Comment by DanPristupov** [comment]
Hi. Do you mean subdirectories? Just create a new category and use drag and drop.
<img width="316" alt="2018-08-15 at 13 08" src="https://user-images.githubusercontent.com/618115/44145575-67a92eae-a08c-11e8-9f82-6bb8bc2accd1.png">

**Comment by IrishAdo** [comment]
I didn't see that option DOH!!!!

**Comment by DanPristupov** [comment]
BTW, you can use drag and drop to create subfolders.
