### ISSUE TITLE
Dark mode: Opened repository history item text color is black instead of white

### ISSUE THREAD

**Issue by rbukovansky** [ForkIssues/Tracker#390]
This is what I'm getting when I open a repository from recent repositories...

![screen shot 2018-08-17 at 11 22 22](https://user-images.githubusercontent.com/1004491/44260314-4d04b580-a214-11e8-8ba0-70f906282365.png)

**Comment by Finesse** [comment]
The text is black on black only in one case: the item is selected and the app window is not focused

**Comment by maksimovic** [comment]
Or, if you're on a branch X and you click branch B (not switching to it, just clicking it once):

<img width="221" alt="screen shot 2018-09-25 at 10 35 43 am" src="https://user-images.githubusercontent.com/1126226/46002667-f6aa5280-c0ae-11e8-88a2-b5f66fb37fe3.png">

Btw, could this be related to dark mode in macOS Mojave? I don't remember seeing these issues prior to the macOS upgrade.

**Comment by DanPristupov** [comment]
Yes, Mojave introduces many visual glitches.

I'm going to have quite a hell migrating to native dark theme (and keeping dark theme for older OS versions at the same time), but hopefully if will get better soon :).
