### ISSUE TITLE
[Setting Request]:  Open Last Project instead of Repo Manager

### ISSUE THREAD

**Issue by kuthair** [ForkIssues/Tracker#391]
Please add a setting to open the last project used instead of the repo manager.

On Mac, I like to close the window, but not quit Fork (when not actively using it). Next time I click the Fork icon in my Dock it opens the repo manager and I have to find and select my last repo again.

A setting would be nice so it opens my last used repo right away.

Thanks for the consideration.

**Comment by DanPristupov** [comment]
Do you close application with `Cmd+Q`?

**Comment by kuthair** [comment]
No. Cmd+W, close the window.

**Comment by kissferenc** [comment]
@kuthair File->Open Recent

**Comment by kuthair** [comment]
@kissferenc: Thanks, but I'd rather use the repo manager.
