### ISSUE TITLE
[Feature Request] Disable diff for certain files

### ISSUE THREAD

**Issue by SoyYuma** [ForkIssues/Tracker#393]
Some times you want to disallow diffing files that are too big or that you know the diff doesn't make sense. For example, in a Unity project, the .unity files (when saved not-binary) are diffed by default. These files are usually big, which makes the UI to stall. Also the diffs of these files are usually very difficult to understand, so it's a bit useless except in very limited situations.

It'll be great to have the option to disallow Fork's diff panel for files depending on:
- Extension (Ex: *.unity are disallowed)
- File Size (Ex: > 0.5 MiB are disallowed)

Thanks!
ALE

**Comment by AdamModus** [comment]
I agree with @SoyYuma point of view. I would like to be able to not have fork try to render diffing for my package.lock or yarn.lock files, that usually are quite long and end up freezing the UI while it computes the rendering.

This is the single feature I have on SourceTree that I would like for Fork to have. I still <3 it though! 😄

**Comment by DanPristupov** [comment]
What are `package.lock` and `yarn.lock` files? Are they a part of some dev environment?
