### ISSUE TITLE
Various features breaking when remote name includes emoji

### ISSUE THREAD

**Issue by tor-ocean** [ForkIssues/Tracker#397]
I wanted to make my remotes stand out a little better and tried **right click -> Rename origin…** to add an emoji to the name.

It sort of worked - both Fork and git accepted it, and the new name showed up in the commit graph. Plenty of other functionality stopped working entirely though.

For example, the fetch/pull/push sheets did not work at all, and the origin no longer showed up in the sidebar, which as far as I can tell means there's no way to change the name back from within Fork. Fortunately I could change the name back from the terminal.

**Comment by DanPristupov** [comment]
Thank you. I fixed that and now remotes with emojis work properly on my computer.

This is quite a big change though and I need to test it a lot before publishing. Would you like to get a pre-release version and check if everything works now?

<img width="447" alt="2018-09-01 at 15 51" src="https://user-images.githubusercontent.com/618115/44946575-e92ae100-adfe-11e8-8b1b-5dc9f60e2141.png">
