### ISSUE TITLE
Interactive rebase table: all columns show commit message for dropped commits

### ISSUE THREAD

**Issue by homm** [ForkIssues/Tracker#400]
Take a look at the crossed out text for dropped commits. Each column contains a commit message.

<img width="999" alt="screen shot 2018-09-08 at 18 49 18" src="https://user-images.githubusercontent.com/128982/45255978-53f89100-b398-11e8-8907-bcfd70bf77e1.png">

**Comment by DanPristupov** [comment]
Fixed in 1.0.70
