### ISSUE TITLE
Interactive Rebase: Set action for multiple commits

### ISSUE THREAD

**Issue by Turbo87** [ForkIssues/Tracker#401]
I often end up on branches with several commits and want to extract the top few commits onto their own branch. One option is cherry-picking them one-by-one, but the easier solution is using interactive rebase for this and dropping all the commits that I don't want on the new branch. Unfortunately the UI is not letting me set the drop action for multiple commits at once.

It would be awesome if the key shortcuts also worked when multiple commits are selected.

**Comment by nebhale** [comment]
@Turbo87 Is your issue that you cannot select multiple Drops in the UI, or that when you apply it doesn't work?

**Comment by Turbo87** [comment]
I can not select multiple lines, yes.

**Comment by DanPristupov** [comment]
What about other options? There's no problem with: pick, squash, fixup, drop.

How should we handle reword? Or it should be simple disabled when multiple commits are selected?

**Comment by Turbo87** [comment]
yeah, I think disabling reword with multiple selected seems reasonable.

**Comment by Turbo87** [comment]
I was about to write an issue for this, but then remembered that I had already opened one 😅 

is anything blocking this? :)

**Comment by DanPristupov** [comment]
No, we didn't forget about it. Actually it was planned for the 1.0.86 release, but we didn't have a time for that. The problem is, it's a quite complex feature with a nice-to-have priority (not a **must**-have one).

For the next update (1.0.87) we have the improved search in todo list, which is again a more important feature... So, most probably we can expect it in 1.0.88 or so.

**Comment by Turbo87** [comment]
okay, thanks for the update :)

**Comment by DanPristupov** [comment]
I forgot to mention that we implemented operations on multiple commits in IR in 1.0.91.

**Comment by Turbo87** [comment]
yep, I noticed, and I love it!! thanks a lot for implementing this :)
