### ISSUE TITLE
[feature request] toggle tags in commit list

### ISSUE THREAD

**Issue by AlexTugarev** [ForkIssues/Tracker#402]
it would be awesome to make rendering of tags in the commit list optional. for instance in projects with CD pipelines, it can be really noisy.

**Comment by DanPristupov** [comment]
Hi. Do you need the tags at all? Can that be a solution for you? https://github.com/ForkIssues/Tracker/issues/403

**Comment by DanPristupov** [comment]
I just checked, I can add an option to hide tags.

Could tell a bit more about your use case?
* I suppose you need this option enabled only for some repositories, not for the whole application, right?
* Should the state persist after restart?

**Comment by maksimovic** [comment]
+1 for this, too. Also, answers to the questions above in my case:

- Only for some repositories, not for the whole application
- The state should persist after restart
- No, for such repositories tags are completely irrelevant

While we're here (tags-related discussion), it's quite annoying that tags remain expanded after canceling the search. I've got around 7k tags in one repo and it's frustrating to sometimes scroll into that huge list which cannot be collapsed via keyboard shortcut (that I know of), then having to scroll up to find the arrow and collapse it back using the mouse 😬

**Comment by DanPristupov** [comment]
@maksimovic great feedback as always! I'll rush to include this feature in the 1.0.70 update.

Not sure how to solve the expanded item after search though, but will create a task to not forget about this.

**Comment by DanPristupov** [comment]
- [x] 1.0.70

**Comment by AlexTugarev** [comment]
Thanks @DanPristupov this works great!

**Comment by DanPristupov** [comment]
@AlexTugarev cool, thank you!
