### ISSUE TITLE
Cannot prevent fetch (during 'pull' operation) pulling all remote tags

### ISSUE THREAD

**Issue by RoystonS** [ForkIssues/Tracker#403]
I'm just evaluating GitFork, and it's mostly lovely, but I can't stop it fetching all the tags from my remote.  This is a big issue for us as our build system (which is outside of our control) puts a tag on the source for every build. I don't want all 6000+ tags appearing in my workspace; it's a huge clutter.

I've tried adding the 'tagOpt' option to my .gitconfig to prevent tags being fetched (via `git config remote.origin.tagOpt --no-tags`, as the Git documentation suggests) but this has no effect.  It looks like GitFork always adds an explicit `--tags` option when running `git fetch` when doing a 'pull', which is overriding the setting I have in my repo config file.

**Comment by DanPristupov** [comment]
I just checked the source code. Fork does respect the `Fetch All Tags` option.

However automatic fetch which happens every 20 minutes **always** fetches all tags. I will make it use the last fetch preferences used in the UI. Do you agree? If so, I will release the fix during next few days.

P.S. Sorry for the inconvenience, I didn't even know such a problem could exist :).

**Comment by DanPristupov** [comment]
@RoystonS I checked the code again, yes, you are absolutely right. It's already late today, so I will investigate why there's `--tags` tomorrow. It doesn't make much sense since `pull` should download the tags by default.

**Comment by DanPristupov** [comment]
OK, `pull` should not download tags when we pull a particular branch.

One day I added `--tags` option as a workaround, which is fine for majority of people, but not for you.

So, I'll add a "Fetch All Tags" checkbox to the pull dialog and hopefully make everybody happy.

**Comment by RoystonS** [comment]
Thank you very much!

**Comment by DanPristupov** [comment]
I just released 1.0.70. Please let me know if the problem is fixed.

**Comment by RoystonS** [comment]
Yep, all great - thanks so much for the fast fix!
