### ISSUE TITLE
Selecting the branch which is already selected in the sidebar doesn't take you to "All Changes"

### ISSUE THREAD

**Issue by rlabrecque** [ForkIssues/Tracker#408]
Windows 1.20.1.0

Example:

https://i.imgur.com/ANfT3CE.gifv

**Comment by DanPristupov** [comment]
The Windows version has a different issue tracker https://github.com/ForkIssues/TrackerWin

**Comment by rlabrecque** [comment]
Missed that, thanks! Moving it!
