### ISSUE TITLE
Please add the ability to fixup commits 🙏

### ISSUE THREAD

**Issue by vassilevsky** [ForkIssues/Tracker#41]
Hello 🖖

Fork has great "Amend" functionality. But previous commits (before the last one) cannot be easily fixed up.

In SourceTree I added a custom command: `git commit --fixup $SHA`. It appears in commit context menu.

I can stage changes, switch to log, right-click a previous commit, and choose "Fixup this commit".

Then I rebase my branch with `git rebase --autosqash` and the commits are fixed.

It would have been nice to have similar functionality in Fork.

**Comment by DanPristupov** [comment]
Hi.

Why don't you use interactive rebase in this case?

1. Commit your changes with some temporary message.
2. Make interactive rebase to the commit before the one you want to edit.
3. Fixup new commit into the target one.
4. Press Rebase. Done

I can make a short GIF if you want.

**Comment by DanPristupov** [comment]
![2017-06-02 at 17 05](https://cloud.githubusercontent.com/assets/618115/26731887/d1c64578-47b5-11e7-9cf9-7c26b4d7c140.gif)

**Comment by vassilevsky** [comment]
Wow I was not aware of this feature at all!

I will definitely try it.

**Comment by DanPristupov** [comment]
OK, it looks like I can close this.

**Comment by laurentvaills** [comment]
I think the feature you described would be really useful: right-click on a commit to create a "fixup commit" : this is really handy. 
The workaround described in this issue work, but we then loose the "magic" of the autosquash option, and we need to remember where to move that commit, and to set the fixup action. If Fork could take care of that for us that would be pretty nice and handy !
