### ISSUE TITLE
Dark Mode in Mojave: 'About' window

### ISSUE THREAD

**Issue by DevilDimon** [ForkIssues/Tracker#415]
If I choose the dark appearance in System Preferences using macOS 10.14, the About window retains the light theme:
<img width="1280" alt="screenshot 2018-09-26 at 18 56 37" src="https://user-images.githubusercontent.com/10220441/46078328-04023280-c1be-11e8-84d7-4e4d25a3c031.png">
While Xcode, for example, uses the dark theme for the same menu:
<img width="1280" alt="screenshot 2018-09-26 at 18 56 59" src="https://user-images.githubusercontent.com/10220441/46078345-13817b80-c1be-11e8-8367-e8bc5e10fef2.png">

**Comment by DanPristupov** [comment]
Hi. Thank you for the bug report.
I'm working on the full Mojave dark theme support right now.

**Comment by elia** [comment]
<img width="362" alt="image" src="https://user-images.githubusercontent.com/1051/47799093-e169b900-dd29-11e8-8d4b-7bf7dd4c1e14.png">

Seems fixed, this can be closed.
