### ISSUE TITLE
Gitflow not initializing

### ISSUE THREAD

**Issue by rubinchyk** [ForkIssues/Tracker#418]
Can't init GitFlow for repository, has an error:
```
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 158: _flags_fatal: command not found
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 1022: [: -ne: unary operator expected
flags:WARN /Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 739: /Applications/Sourcetree.app/Contents/Resources/bin/getopt: No such file or directory
flags:FATAL unable to parse provided options with getopt.
```

**Comment by DanPristupov** [comment]
You removed SourceTree and it broke your environment.

**Comment by DanPristupov** [comment]
More details in that tweet: https://twitter.com/Alastor8472/status/1045577731319234560

Remove the source tree path from there:
~/.gitflow_export

**Comment by rubinchyk** [comment]
Thank you! Working.

**Comment by DanPristupov** [comment]
Not sure how to behave in such case... I'll try to find a workaround to override those settings.

**Comment by dill0wn** [comment]
Thank you! I was having the same issue. It only appeared after SourceTree was no longer present :)

I couldn't find anything in the usual places that would reference /Applications/SourceTree.app/Contents

Thanks for the solution!

p.s. It was rather difficult to find this github page. Is there a link anywhere on git-fork.com?

**Comment by dill0wn** [comment]
p.p.s Keep up the good work. Fork is my favorite git gui 💯

**Comment by DanPristupov** [comment]
@dill0wn no, there's no such link. But it's a good idea. It would be great to have a 'troubleshooting' page somewhere.

**Comment by tomwalsh-home** [comment]
@DanPristupov Awesome! worked for me! Pesky sourcetree!

**Comment by dlpigpen** [comment]
> More details in that tweet: https://twitter.com/Alastor8472/status/1045577731319234560
> 
> Remove the source tree path from there:
> ~/.gitflow_export

Thank you it works for me.

**Comment by pridemusvaire** [comment]
> > More details in that tweet: https://twitter.com/Alastor8472/status/1045577731319234560
> > Remove the source tree path from there:
> > ~/.gitflow_export
> 
> Thank you it works for me.

Works thanks.

**Comment by Fi5t** [comment]
> More details in that tweet: https://twitter.com/Alastor8472/status/1045577731319234560
> 
> Remove the source tree path from there:
> ~/.gitflow_export

It's pure magic! Thank you a lot.

**Comment by emoonadev** [comment]
> More details in that tweet: https://twitter.com/Alastor8472/status/1045577731319234560
> 
> Remove the source tree path from there:
> ~/.gitflow_export

Can we have a detailed procedure to resolve this problem, I do not understand what I should do, what to delete and where?

**Comment by JonasPardon** [comment]
@emoonadev 

1. Go to your terminal and type:
`cat ~/.gitflow_export`
2. You should see the line `export FLAGS_GETOPT_CMD=/Applications/Sourcetree.app/Contents/Resources/bin/getopt%` or something similar there.
3. If you do see that line, type `nano ~/.gitflow_export` and remove that line from the file. Press `Ctrl + X` to quit the editor.  You might have to confirm: `y` and `ENTER`

**Comment by ulkoart** [comment]
> More details in that tweet: https://twitter.com/Alastor8472/status/1045577731319234560
> 
> Remove the source tree path from there:
> ~/.gitflow_export

Thanks!

**Comment by iamleetvin** [comment]
> 

Useful answer！！！thank you！！！

**Comment by iamleetvin** [comment]
> More details in that tweet: https://twitter.com/Alastor8472/status/1045577731319234560
> 
> Remove the source tree path from there: ~/.gitflow_export


Useful answer！！！thank you！！！

**Comment by ErisonSales** [comment]
> Mais detalhes nesse tweet: https://twitter.com/Alastor8472/status/1045577731319234560
> 
> Remova o caminho da árvore de origem de lá: ~/.gitflow_export

Funcionando, obrigado!
