### ISSUE TITLE
"Discard changes" option needs confirmation dialog or backup commit

### ISSUE THREAD

**Issue by EgorKomarov** [ForkIssues/Tracker#419]
When switching to another branch while changed files exist in working directory or staging area, a dialog appears with options to "Stash and reapply", "Don't change" or "Discard" local changes. Selected option is preserved between feature uses, and there is not any confirmation dialog for the last option, which made me really sad today.
I believe that confirmation dialog isn't enough though, and it would be better to make a commit with all the changes and add "backup/..." tag to it before discarding any files (even unstaged ones), similarly with "rebase" implementation.

**Comment by DanPristupov** [comment]
Could you update the misleading title please?

**Comment by DanPristupov** [comment]
Backup is a good idea. May be we can save all the staged area as a patch and put it to the Trash directory on mac. Then it can be restored (if needed).

**Comment by DanPristupov** [comment]
In 1.0.71 I made Checkout dialog to not remember the 'Discard' option.

**Comment by bebound** [comment]
What does “Don't change” option do?

**Comment by DanPristupov** [comment]
@bebound runs checkout with default arguments, which is `git checkout <branch_name>`
