### ISSUE TITLE
Feature request: Drag and drop files from File Tree under selected commit

### ISSUE THREAD

**Issue by dmay** [ForkIssues/Tracker#42]
![image](https://user-images.githubusercontent.com/1068398/26897274-cf6dc362-4b7c-11e7-9382-e82027c4f633.png)

**Comment by DanPristupov** [comment]
@dmay thank you for asking this.
I've just released Fork 1.0.48 with this feature. I also implemented drag and drop for items in commit view to other applications.

**Comment by dmay** [comment]
The fastest feature request in my life 😱

**Comment by DanPristupov** [comment]
`¯\_(ツ)_/¯`
