### ISSUE TITLE
Copy Commit Info

### ISSUE THREAD

**Issue by fecundf** [ForkIssues/Tracker#421]
Used to be cmd-C copied the commit info, and I used that nearly daily to put commit hash+summary into an issue tracker.

Now, not only is the shortcut gone- the entire menu option is gone...

Can we have "Copy Commit Info" back, with a shortcut like cmd-shift-C or cmd-alt-C for it?

**Comment by DanPristupov** [comment]
> cmd-alt-C
Bingo!

**Comment by fecundf** [comment]
Oh, it's already there as cmd-alt-C! I didn't see that anywhere in the UI, nor does Help search bring it up when looking for "copy" or "info" - so consider this a request to expose it in a menu, any menu, to make it findable.

**Comment by DanPristupov** [comment]
It is in the menu and becomes visible when you press ⌥.
This approach is a widely used macOS convention, which is used by almost every default application (Finder, Safari, etc)

**Comment by ravinggenius** [comment]
When I select a commit and try to copy info with `⌥⌘C`, the system emits an audible "ding", but nothing is copied to the clipboard. The only way I found to copy info is to right-click on a commit first, then press/hold `⌥`, then select "Copy Commit Info".

In GitX "copy info" is what you get when you do a regular copy (`⌘C`), which is far more useful for me than the full SHA.

**Comment by DanPristupov** [comment]
I just tried and both shortcuts work. Could you try to restart the application?

**Comment by ravinggenius** [comment]
I restarted and checked for updates to verify I have the latest version (`1.0.74.2` on macOS). I still hear an error "bell" and nothing is copied.

**Comment by DanPristupov** [comment]
Do you use `U.S. key mapping`?

**Comment by ravinggenius** [comment]
I'm guessing I do. I don't recall changing it, and I'm in the US.

**Comment by DanPristupov** [comment]
I just noticed it can not work with some mappings.

I already have a lot of things planned for the next update, so I will check this later.
