### ISSUE TITLE
Allow http github urls

### ISSUE THREAD

**Issue by cyberwombat** [ForkIssues/Tracker#422]
I'm migrating from Tower to Fork and Ive noticed that Ive had to change all my origins - my old setup just used http urls (ex: https://github.com/foo/bar.git) and this worked well with CLI and Tower but Fork just errors saying the server does not exist. Changing origins to use SSH (ex: git@github.com:foo/bar.git) solves the issue but its kinda annoying. Is there a reason https url are not supported?. I am using Fork 1.0.70.

**Comment by nebhale** [comment]
I suspect that something else is up here.  I use HTTPS with Fork, exclusively with no issues, so maybe a bug?

**Comment by cyberwombat** [comment]
Do you use it on private repo? I wonder if that makes a diff

**Comment by nebhale** [comment]
I do.  You might need to integrate some credential management in order to make it work with a private repository.  My `gitconfig` is tied to the macOS keychain so when Fork attempts to do things with private repos, the credentials are transparently available.

**Comment by cyberwombat** [comment]
OK. So this is what is happening. When I try to push to an https repo I get server not found. My GH credentials are fine  and I redid them to be sure. However when I went to clone a repo it gives me the option to pic which GH url - by default its SSH which works but when I picked the https option I got a similar but more verbose error:

    warning: templates not found /usr/local/git/share/git-core/templates

I am using the Git Fork option in my preferences - changing that to the Apple Git makes all my issues go away so the initial problem of server not found is due to missing templates.  I see fixes online but I guess the problem should not exist in first place. Being that this git instance is called Fork instance does that mean that Fork installed it? There is actually no /usr/local/git dir in my machine.

**Comment by DanPristupov** [comment]
@cyberwombat 

Is that possible that you entered an incorrect password and Fork remembered it?
Fork stores all the credential information in Keychain Access. Please open the Keychain Access application and remote the entries in the password category which belongs to Fork (they look like `Fork.hostname`).

Another option is to login to your GitHub account in Fork (in 'repository manager', which is located on a new tab), then Fork will use oAuth session instead of password to authenticate you.

**Comment by cyberwombat** [comment]
@DanPristupov  - did you see my last comment? it's a git cli issue

**Comment by infotexture** [comment]
See #211 for related issue & workaround.

**Comment by cyberwombat** [comment]
Not related to auth. Tried reinstalling but no go.  It just never creates a /usr/local/git directory. SourceTree people have same issue `https://community.atlassian.com/t5/Git-questions/About-git-path-for-Sourcetree/qaq-p/186483`. Either create the directory manually or use another git which is what I ended up doing (using native apple git).

**Comment by jamienk** [comment]
I had this same problem (with Private GitHub repo) and the solution (switch to /usr/bin/git and use ssh url) worked
