### ISSUE TITLE
[Feature Request] word wrap in changes view

### ISSUE THREAD

**Issue by robinwhittleton** [ForkIssues/Tracker#424]
At the moment I’m finding that I use Kaleidoscope as a difftool because it has the ability to wordwrap line changes. I produce epubs so it’s not unusual to find lines with multiple changes and 10k+ characters. Fork helps a bit by highlighting from the first to the last change in a particular line, which lets me know that I can continue on to the next change when the highlighting stops. A word wrap mode would mean that I could drop Kaleidoscope though. Thanks!

**Comment by DanPristupov** [comment]
May be I'm missing something... What do you mean by 'word wrap'?

Fork has an ability to enable to word wrapping. It's available in every context menu and is above every text control (including one in Changes view).

<img width="307" alt="screenshot 2018-10-04 at 11 55 28" src="https://user-images.githubusercontent.com/618115/46466827-92814000-c7cc-11e8-8862-1709591b3d28.png">

<img width="271" alt="screenshot 2018-10-04 at 11 51 50" src="https://user-images.githubusercontent.com/618115/46466558-eb040d80-c7cb-11e8-8bef-af6305064fd4.png">

**Comment by robinwhittleton** [comment]
Ah! I’d honestly completely missed that option 😅 So yes, that’s 80% of my feature request. The other is the option to highlight just the changed parts of a line when in word wrap mode, and if we’re shooting for the stars a side-by-side review view would be nice (line matchup, as per File Merge, Kaleidoscope etc). But I’m super happy that word wrap exists!

**Comment by robinwhittleton** [comment]
And I’ve just found the side-by-side mode, although that doesn’t seem to have word wrap available there.

**Comment by robinwhittleton** [comment]
Thanks, will follow #100. For (2), Kaleidoscope manages it:

![Screenshot from Kaleidoscope](https://user-images.githubusercontent.com/7414/46471575-9fa52b80-c7da-11e8-91af-3025f7bf9c16.png)

As does FileMerge:

![Screenshot of FileMerge](https://user-images.githubusercontent.com/7414/46471646-cc594300-c7da-11e8-99f2-95761fb47754.png)

Obviously this is a fairly niche request and I seriously don’t expect you to implement it for one person, but it is something that I think is possible and useful (for me at least). I’m happy if you want to close this though, the majority of what I wanted turns out to be implemented already for which I’m very happy :)

**Comment by DanPristupov** [comment]
@robinwhittleton thank you for the screenshots. Most probably I will implement such a layout one day, but right now there are much more important tasks for me.

I'll close that issue since the original problem is solved.
