### ISSUE TITLE
Missing Ahead/Behind indicators on branches

### ISSUE THREAD

**Issue by infotexture** [ForkIssues/Tracker#425]
In recent versions, it seems the numeric indicators are no longer shown on branches in the sidebar when the local branch has commits that are not on the tracked branch (or vice versa).

Seen on 1.0.71.1 _and previous version(s?)_ on macOS Sierra 10.12.6.

— Never realized how useful these were until they disappeared…

**Comment by DanPristupov** [comment]
Everything still works on my side.

Questions:
1. Are you sure your local branch tracks the remote branch? You can check that in tooltip over local branch on the sidebar
2. Does this happen in any repository?

**Comment by infotexture** [comment]
> Are you sure your local branch tracks the remote branch?

That was my first thought: that tracking had somehow been disabled, but the indicators are still missing:

![fork-issue-425-missing-indicators](https://user-images.githubusercontent.com/129995/46746578-9ec73a80-ccaf-11e8-9c6c-644a7c3ff865.png)

That said, it _does_ seem to be repository-specific, as I have other repositories where it works as expected, and several where it doesn't. 🤔

**Comment by DanPristupov** [comment]
Could you show the result of the following request please?
`git for-each-ref --format="%(refname:short) %(upstream) %(upstream:track)" refs/heads/develop`

**Comment by infotexture** [comment]
```
develop refs/remotes/dita-ot/develop [behind 3]
```

**Comment by DanPristupov** [comment]
I think I've fixed this bug in 1.0.72. When you have a time, please check it.

**Comment by infotexture** [comment]
Yep, fixed in 1.0.72.

Thanks! Closing…
