### ISSUE TITLE
Renamed local tracked branch creates new remote branch on push

### ISSUE THREAD

**Issue by infotexture** [ForkIssues/Tracker#426]
I work on a Bitbucket project where very long branch names are created on the server side when users create branches in the Jira UI.

When I check out a local copy of the remote branch, I let Fork set up the tracking reference, then rename the local copy to something shorter _(the tracking reference is retained)_.

When I push from the local branch, Fork creates a new remote branch based on the local branch name, instead of respecting the configured tracking settings for this branch and pushing to the original remote branch.

**Comment by DanPristupov** [comment]
Fixed in 1.0.72

**Comment by infotexture** [comment]
Verified in 1.0.72. 

Closing…
