### ISSUE TITLE
Git Flow deletes remote branch anyway

### ISSUE THREAD

**Issue by infotexture** [ForkIssues/Tracker#427]
When finishing a hotfix via Git Flow, the remote branch was deleted even though the **Delete branch** option was _unchecked_ in Fork's Finish dialog.

_(The local branch was correctly retained, but the remote branch deletion was immediately pushed.)_

Not sure if this is a bug in the underlying `git-flow` code — or the [git-flow (AVH Edition)](https://github.com/petervanderdoes/gitflow-avh) I installed via Homebrew — or whether Fork is passing the wrong options to the `git-flow` binaries.

**Comment by DanPristupov** [comment]
I just checked, The local branch remained.

Here's the request: `flow hotfix finish --keeplocal hotfixname`

Do you think the `--keepremote` option should also be included?

**Comment by infotexture** [comment]
> I just checked, The local branch remained.

Yes, that part works for me too. It's the remote branch deletion that was surprising.

> Do you think the `--keepremote` option should also be included?

Yes, that should solve the problem.

The Git Flow commands seem to support 3 related options: `keep`, `keepremote` and `keeplocal`

If you're passing only `--keeplocal`, that might imply remote branch deletion. 

Adding the `--keepremote` option should explicitly preserve it. 

_(Not sure if the plain  `keep` option would keep both.)_ 🤔

**Comment by DanPristupov** [comment]
Just opened the source code:

git-flow-hotfix
```
	# Keeping both branches implies the --keep flag to be true.
	if flag keepremote && flag keeplocal; then
		FLAGS_keep=$FLAGS_TRUE
	fi
```

I don't use the hotfixes at all, so I'm not sure what is the correct behavior.

However, I will use the 'k' option instead and here's how `finish hotfix` will work in 1.0.71.2:
- I renamed 'Delete branch' to 'Delete branch**es**'
- That option will affect both branches
  - When enabled: both branches will be deleted and only tag remain.
  - Otherwise: local, remote branches and tag will remain.

**Comment by infotexture** [comment]
👍 Thanks, that sounds like the right approach.

I only recall seeing this issue with hotfixes, but while you're in this part of the code, you might also want to verify whether the same issue exists for releases.

**Comment by DanPristupov** [comment]
Since we are here. I stopped using gitflow myself because it is excessive for only two programmers.

So, If you miss some feature or would like something to be improved, please let me know.

**Comment by DanPristupov** [comment]
Just released 1.0.71.2. Please check for updates.

**Comment by infotexture** [comment]
Thanks for the quick fix. I tested the following:

- [ ] Finishing a feature with **Delete branch** enabled deletes both local branch **AND** remote branch
- [x] Finishing a hotfix with **Delete branches** DISabled retains both local and remote branches 🎉 
- [ ] Finishing a release with **Delete branch** DISabled still deletes the remote branch 👎 

For features and releases, I suggest you align the labels and behavior with the changes for hotfixes to avoid confusion.

**Comment by DanPristupov** [comment]
In 1.0.72 I updated the 'Finish Feature' and 'Finish Release' dialogs. That should be it now.

**Comment by infotexture** [comment]
Thanks, much better. 

Local and remote feature and release branches are now preserved as expected when *Delete branches* is disabled. 👍 

One small detail left: 

Just noticed that the default action button in the **Finish Release** dialog uses the **Submit** label, whereas the **Finish Feature** and **Finish Hotfix** dialogs use **Finish**, which is much more clear.
