### ISSUE TITLE
Not getting a new version (1.0.71)

### ISSUE THREAD

**Issue by maksimovic** [ForkIssues/Tracker#429]
I thought that a friend of mine is talking nonsense, but apparently [there's a release](https://git-fork.com/releasenotes) that my Fork instance isn't picking up - it says I'm already up-to-date with 1.0.70.

Are the updates throttled or my Fork has some personal issues? 😁

**Comment by BrutalSoloH** [comment]
> P.S. Having two dark modes (old and new native) is such a mess... Each UI change must be tested in two different systems.

Why do you do that? Are you making a light version? Else you can just insert NSRequiresAquaSystemAppearance as TRUE in your app's plist.

Also, I did manage to upgrade to 1.0.71 and the QuickView on a file is crashing Fork.

**Comment by DanPristupov** [comment]
> Why do you do that? Are you making a light version? Else you can just insert NSRequiresAquaSystemAppearance as TRUE in your app's plist.

NSRequiresAquaSystemAppearance will disable the native dark theme in Mojave right? I want to use it instead. But I also want to keep the old dark theme for users with older systems. 

Fork got a dark theme 2 years ago. At the time it was really tricky and required a lot of customization to work properly. Now I'm trying to slowly migrate to the native solution. When old (custom) dark theme will be used by less than 2% of Fork users (i.e. when majority of people will migrate to Mojave), I'll remove it.

**Comment by DanPristupov** [comment]
1.0.71.**2** just came out. Please check for updates.

> Also, I did manage to upgrade to 1.0.71 and the QuickView on a file is crashing Fork.

This one is fixed there.

> Are the updates throttled or my Fork
No. But actually I'm going to set up CDN to make updates faster for everybody.
