### ISSUE TITLE
Handle 'github-mac://openRepo/' urls

### ISSUE THREAD

**Issue by DanPristupov** [ForkIssues/Tracker#43]
There's is an url convention which allows to create a web address which raises clone window in system defined Git Client.

You probably have seen this on GitHub many times.
I create this issue to check how important this feature is. Please upvote if you want to see it in Fork.

<img width="559" alt="2017-06-09 at 09 06" src="https://user-images.githubusercontent.com/618115/26964766-52be139e-4cf3-11e7-8440-ebf54f9b2780.png">

**Comment by kitgrose** [comment]
What happens if both Fork and GitHub Desktop are installed, though?

**Comment by DanPristupov** [comment]
@kitgrose sorry for missing your question.

There's only a single 'handler' for a specific url type. So, either GitHub Desktop or an other git client will be triggered. This is similar to "default browser" macOS setting.

**Comment by kleerkoat** [comment]
i don't think it works like that. if you don't have Git Hub Desktop installed and you click on it, it starts to install.

so i don't think the devs here can do anything. BUT they might be able to work up a custom url scheme to use in a bookmarklet.

**Comment by DanPristupov** [comment]
I implemented that in 1.0.68. The option in available in Fork preferences on the 'integration' tab.
