### ISSUE TITLE
Pre-commit hook failed on fish shell

### ISSUE THREAD

**Issue by re-fort** [ForkIssues/Tracker#430]
Hi,

When i commit and run pre-commit hook on Fork, it has failed.
On terminal, it works correctly.

Here's the full error:
```
Pre-commit hook 'pre-commit' has failed:
/Users/me/.anyenv/libexec/../completions/anyenv.fish: line 2: syntax error near unexpected token `set'
/Users/me/.anyenv/libexec/../completions/anyenv.fish: line 2: `  set cmd (commandline -opc)'
/Users/me/.bash_profile: eval: line 3: syntax error near unexpected token `set'
/Users/me/.bash_profile: eval: line 3: `  set command $argv[1]'
./node_modules/pre-commit/hook: line 49: : command not found
./node_modules/pre-commit/hook: line 49: : command not found
```
`anyenv.fish` might be called as bash script because the output of `sh anyenv.fish` is the same as above.
Let me know if you have any workaround.

versions:
Fork 1.0.72
mac OS 10.13.6
fish 2.7.1

**Comment by DanPristupov** [comment]
Most probably Fork has different `ENV`.

Solutions:
1. Use absolute paths in your hook. Sometimes that can be tricky (or impossible).
2. Start Fork from your command line and it will derive `ENV` of the parent process. You can do that using `open -a Fork` command or just `fork` if you installed Fork CLI tools.

**Comment by re-fort** [comment]
Thank you for taking your time!
The latter solution works perfectly :)

**Comment by deepeshhmehta** [comment]
Every-time this needs to be done? it is super annoying that for every commit i make i have to kill git-fork and start it again using terminal command "open -a fork".

If anyone has a better solution please do comment

**Comment by DanPristupov** [comment]
There are other solutions, but I'm not sure if they are much better.

https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x

**Comment by sneko** [comment]
@DanPristupov pointed me this issue.

Just here to say it's still a painful issue in 2022 👍 

In my case the precommit hooks from Git are not able to find `node` (whereas it's available in my terminals):
```
$ git commit --file=/var/folders/03/n3sz6dd577gdnfyzlvjsr9500000gn/T/85BAD342-1F11-49E9-A8F7-CA226A31B020

env: node: No such file or directory
husky - pre-commit hook exited with code 127 (error)
```

* NOT WORKING: `fork` (launch fork from the repository folder)
* **WORKING**: `open -a Fork`

@DanPristupov in case my Fork was launched in a different way, any chance we could simulate `open -a Fork` to get the good `ENV`?



> There are other solutions, but I'm not sure if they are much better.
> 
> https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x

Not sure to understand what can be done on this side? Is it to populate an envVar from the MacOS perspective, and not through scripting like `.bash_profile` and `.zshrc`?

Thank you,

**Comment by gpoole** [comment]
I ran into this issue using NVM and Husky, and the `open -a` fix above solves the problem.

Just to share with anyone having the same problem with Husky and NVM specifically, a fairly clean option is to add a `.huskyrc` [as suggested in the manual](https://typicode.github.io/husky/troubleshooting.html#command-not-found). If you're not using Husky that might be a compelling use case.

If you're just using plain NVM and a pre-commit script, you can also try just adding the [two lines of NVM initialisation](https://github.com/nvm-sh/nvm#install--update-script) directly to your actual pre-commit hook and then adding a `nvm use` after that and making sure you've got a `.nvmrc` to your project root.
