### ISSUE TITLE
Unnecessary border at top of commit list

### ISSUE THREAD

**Issue by otto-md** [ForkIssues/Tracker#432]
In a slightly lighter shade of gray. See marked in red here:

![screenshot 2018-10-11 at 22 56 56](https://user-images.githubusercontent.com/31409359/46833962-52145a00-cdaa-11e8-8e7d-2658d81a0e47.png)

Running dark mode on Mojave.

Also another smaller issue Ive noticed; when I unstage a hunk (a bit down in a longer file) in the changes view, the view scrolls to the top. This is slightly annoying if you want to unstage multiple hunks.

**Comment by DanPristupov** [comment]
I fixed the issue in 1.0.72. Please wait for the update.

Regarding the stage/unstage jump. Recently I made many changes there, please let me know if the problem still exists in the latest version.

**Comment by otto-md** [comment]
Its looking great. Thanks!
