### ISSUE TITLE
Custom Actions Parameters

### ISSUE THREAD

**Issue by FranciscoAmado** [ForkIssues/Tracker#435]
Hi there!

Do you know if it's possible to pass a custom action **Available Variable** into the _Parameters_?

Would be great if it was possible to do something like this
![screen shot 2018-10-15 at 15 30 22](https://user-images.githubusercontent.com/6344795/46957999-c1cb6300-d090-11e8-827b-5e44ec5449ff.png)

Cheers 👍🏻

Fork version 1.0.71.2

**Comment by DanPristupov** [comment]
Assuming that I understood your question correctly, yes you can use the variables in any custom action field.

In your case $repopath will be replaced with the repository path.

**Comment by DanPristupov** [comment]
Ouch! Just noticed in the source code that the hint is incorrect. The parameter is called `$path`, not `$repopath`.

I will fix that in the next update.
