### ISSUE TITLE
[Bug] Staging image

### ISSUE THREAD

**Issue by FeBe95** [ForkIssues/Tracker#437]
### Steps to reproduce:
- add image to repo
- select added image in "Unstaged Files"
- click the "Stage" button in the diff-viewer on the right side
### Expected result:
- image gets staged
### Actual result:
- image gets staged, but "modified" image remains in "Unstaged Files"

### Info:
- Fork Version: 1.21.0.0
- OS: Win10 1803
- Git Version: 2.18.0.windows.1

**Comment by DanPristupov** [comment]
The Windows version has a separate issue tracker: https://github.com/ForkIssues/TrackerWin/issues.

I will it more visible...

**Comment by FeBe95** [comment]
@DanPristupov oh okay, I am going to opening a new issue for a it. I am closing this issue here. If this bug can be reproduced on Mac, please reopen it again, I can't test it.
