### ISSUE TITLE
Add Show/Hide invisible/whitespace/hidden characters option to the diff view

### ISSUE THREAD

**Issue by scratchee** [ForkIssues/Tracker#447]
Apologies if this is already available (or already logged), but I couldn't find it anywhere.

I usually use the final stage/commit process as a final opportunity to track down any whitespace mistakes I may have made. Whilst issue #340 would catch accidental changes to whitespace (and would be a nice improvement!), it won't reveal inconsistent whitespace decisions on newly added lines.

Many editors and vcs gui tools I've used offer a "show/hide invisibles" (aka whitespace, aka hidden characters) option to reveal the spaces, tabs, newlines, carriage returns, etc (unicode probably extends this list to ridiculous levels, but those are the most common). This is especially useful in the commit process since even if you find them obnoxious in an ordinary editor, the diff view is a perfect time to have them on for reviewing where they're not likely to get in the way too much.

People can use this to confirm a newly added line uses the same whitespace style as the rest of the file, or that it matches line endings to the original (Xcode isn't great at handling Windows line endings, or worse: mixed line endings, so I often have to fix this up when working with files using poorly chosen line endings, as an example).

I'd recommend this be added as a toggle button above the diff view. I'd also recommend having whitespace use some transparency or low contrast colouring, so that it can be left on without being too distracting (it can be hard to read text with high contrast visible whitespace).

**Comment by scratchee** [comment]
<img width="1314" alt="screenshot 2018-10-31 at 14 23 46" src="https://user-images.githubusercontent.com/6053685/47794633-bf1b6f80-dd18-11e8-8777-e608fdad3114.png">
Here is how the attached horribly crafted file is shown currently.
[whitespaceExample.cpp.txt](https://github.com/ForkIssues/Tracker/files/2534802/whitespaceExample.cpp.txt)

**Comment by DanPristupov** [comment]
I hope this is still actual :).

The option to show hidden symbols has been implemented. Currently 3 types of characters are supported: space, tab and newline (depends on git `auto clrf` settings).

<img width="653" alt="image" src="https://user-images.githubusercontent.com/618115/56581412-31d51b80-65d5-11e9-8bc1-e2e83f2ad0ec.png">

I just released Fork 1.0.77, please check for updates.

**Comment by scratchee** [comment]
Brilliant, works great from what I've seen, nicely done!

In the meantime Xcode has recovered its non-unix-newline support up from "complete garbage" to "passable", so the need for reviewing that specifically is lower than when I logged the question (Xcode now uses the newline type it thinks the file has, rather than the previous methods of either blasting the entire file with unix newlines, or just throwing unix newlines at anything it touches, even after undoing).

Given that, the need for visibility on alternative newlines has dropped, so I'm happy to close this as solving the core requirements 👍
