### ISSUE TITLE
[Dark mode] dim commit view file status icons

### ISSUE THREAD

**Issue by elia** [ForkIssues/Tracker#449]
Currently the colors are very bright, the system generally dims them a bit in dark mode

<img width="51" alt="image" src="https://user-images.githubusercontent.com/1051/47799861-6e614200-dd2b-11e8-9bdd-9bd7142da588.png">

**Comment by DanPristupov** [comment]
Yes, true. Thank you for reporting that.

**Comment by DanPristupov** [comment]
In 1.0.72 I updated the colors with the ones recommended by Apple for the dark mode.
