### ISSUE TITLE
Update fail

### ISSUE THREAD

**Issue by soloradish** [ForkIssues/Tracker#45]
OS: 10.12.5 (16F73)
update from version 1.0.47.1 to 1.0.48 
after push "install and relaunch", the app close itself and nothing more happend.

I launch the app from launch pad, but version still 1.0.47.1.

**Comment by DanPristupov** [comment]
This has happened to me once. Then I clicked update again and it updated properly. Could you try to check for update manually please (Fork -> Check for Updates...)?

P.S. Sorry for the delay. I've been very busy fixing crash on new macOS High Sierra (10.13) systems.

**Comment by soloradish** [comment]
"check for update" is no help, finally I update from new version dmg package. 
Thx

**Comment by DanPristupov** [comment]
I use https://sparkle-project.org for updates and sometimes such problems happen (https://github.com/ForkIssues/Tracker/issues/11). The problem is they are very rare and almost unreproducible.

**Comment by soloradish** [comment]
upstream's bad..^-^
