### ISSUE TITLE
Pushing to a wrong branch on someone else's remote

### ISSUE THREAD

**Issue by maksimovic** [ForkIssues/Tracker#456]
The title is a bit vague, but I tried to avoid setting a mile long one... Here's the problem:

Our workflow with bigger feature branches is to have someone create a "main" feature branch where all other people involved send their PR's, and at the end that main feature branch gets merged into the `master`. For example:

1. Joe creates a `feature-xyz` branch where everybody else will send their PR's
2. I check it out as `feature-xyz` and push it to my own fork (tracking `origin/feature-xyz`)
3. For convenience, I also check out Joe's `feature-xyz` but under a different name, so I can track the changes coming in from other people easier. Fork says that it's tracking `joe/feature-xyz`, which is correct as I have Joe's remote added as `joe`.
4. Sometimes I just want to push changes to Joe's branch directly, e.g. changes from `master`, which don't really require a review/PR. However, here comes the problem: if I merge master to my `joe/feature-xyz` and push it to `joe` remote, it actually **creates** a _**new**_ `joe/feature-xyz` branch in Joe's fork instead of pushing the changes to Joe's `feature-xyz` branch.

If Fork claims that the tracking branch is `feature-xyz`, shouldn't it push the changes there, regardless of the name that I gave to the branch?

**Comment by DanPristupov** [comment]
Sorry for such a long silence.

This is a big bug and I will fix it during that week. The remote tracking branch must be always respected (until we push to another remote).

As a related topic, we probably need to be more flexible and be able to push any local branch to any remote branch. I'm thinking about a convenient way to allow to select the destination branch...

**Comment by maksimovic** [comment]
No worries, I've already stopped using Fork.

😜 kidding, of course

I agree about pushing any local branch to any remote branch. Maybe after selecting a remote in the "Push to" menu show a prompt with a search-as-you-type input (something similar to the one which opens when checking out a remote branch)?

**Comment by DanPristupov** [comment]
I fixed the original issue. Now Fork respects the upstream (remote tracking branch).

The ability to push to any branch is in my todo list.

**Comment by hegyre** [comment]
Hello,
On my side I would like to have the old behavior, which was in the description.

As on my own branch, I want to remotely track a main branch, but still pushing to my own branch instead of the main branch.
This is also the sourcetree behavior.

Maybe you could add an option somewhere to tell if Remote Tracking should be only for downstream (pull), or also for upstream (push) ?
