### ISSUE TITLE
Scroll offset in Changes Diff view

### ISSUE THREAD

**Issue by eligat** [ForkIssues/Tracker#457]
Horizontal scroll offset seems like exactly equal to the width of line numbers ribbon
Can reproduce in the latest version `1.0.71.2` running on macOS `10.14`
Happens only if diff is large enough to fill the whole diff view from top to bottom.
<img width="419" alt="screenshot 2018-11-13 at 13 54 47" src="https://user-images.githubusercontent.com/2590644/48420636-6672ba80-e78d-11e8-835e-0aadfc74bca1.png">

**Comment by DanPristupov** [comment]
Fixed in 1.0.72! Thank you for reporting this problem.
