### ISSUE TITLE
feature: Quickly launch through EDITOR=""

### ISSUE THREAD

**Issue by jbergstroem** [ForkIssues/Tracker#461]
It would be both convenient and very useful to get a special window for a commit message view that could replace your normal editor when launched via `EDITOR=""` in your environment.

**Comment by DanPristupov** [comment]
Not sure I understand the use case. Can you elaborate? What other GUI applications have this feature?

**Comment by jbergstroem** [comment]
> Not sure I understand the use case. Can you elaborate? What other GUI applications have this feature?

Sorry for not replying (casual 18 months later). The idea is to open the commit view window so fork can help with the commit message and overview. I think we can achieve this now with `fork --commit`?

**Comment by DanPristupov** [comment]
> I think we can achieve this now with fork --commit?

Yes.

```
$ fork --help
Fork Command Line Tools v4.
usage: fork [<options>] <command> [<args>]

These are common Fork commands:
...
    fork status		open current repository in Fork and show the Commit view
    fork commit		same as 'fork status'
```

You can use `fork status` or `fork commit`.
