### ISSUE TITLE
Interactive rebase has problems with messages that start with #

### ISSUE THREAD

**Issue by bhuman** [ForkIssues/Tracker#462]
The interactive rebase feature sometimes interprets messages starting with # as comments and ignores them. Such messages are sometimes lost or the interactive rebase completely breaks if there is a conflict in a commit with such a message. After resolving the conflict, git complains that the message is empty and refuses to accepts the commit.

GitLab uses # followed by a number to link commits to issues. Therefore, commit messages often start with #.

**Comment by roefer** [comment]
A related problem is that such problems can usually be avoided by changing the git settings "core.commentChar". However, this does not work with Fork, because the interactive rebase window is empty when the comment char is redefined.

**Comment by bhuman** [comment]
Interactive rebase seems to work now. Using a different commentChar does still not work, but that's not the topic of this issue.
