### ISSUE TITLE
macOS version getting stuck if post-checkout hook has IO

### ISSUE THREAD

**Issue by igor-makarov** [ForkIssues/Tracker#464]
I think the hook runs in some kind of shell without IO redirection. 

Whenever I was running a ruby script there which expected IO to work, it would hang.
App becomes completely stuck and needs force quit.

I worked around it by redirecting the ruby script input and outputs to `/dev/null`.

Contact me if you need a to reproduce it.

Other than that, amazing app! Love using it.

**Comment by DanPristupov** [comment]
Thank you for the good news.

Regarding the checkout dialog: I'll fix this in the next update.

**Comment by DanPristupov** [comment]
I improved the 'commit checkout' as a part of 1.0.72.2 hotfix.

**Comment by igor-makarov** [comment]
Everything looks good on this front!
