### ISSUE TITLE
Consolidate "Edit Remote" dialogs

### ISSUE THREAD

**Issue by Turbo87** [ForkIssues/Tracker#465]
There is one dialog (and menu item) to change the name of the remote, and another to change the URL of the remote. I understand that these are two separate git commands, but it would be great if the dialog would allow us to change both on the same dialog. I regularly open the wrong one, have to close it again, go to the menu and try the other option.

**Comment by DanPristupov** [comment]
OK, let's split this in two.
1. It looks like the `Edit Remote...` title is a bit misleading and should be `Edit Remote URL...`. Do you agree?

2. I like the idea of merging 2 dialogs into one. Having 2 dialogs is just a 1:1 binding to git commands, which is not really intuitive. I'm going to implement that, but not in the next update.

**Comment by Turbo87** [comment]
>     1. It looks like the `Edit Remote...` title is a bit misleading and should be `Edit Remote URL...`. Do you agree?

yeah, that would be a good first step

>     2. I like the idea of merging 2 dialogs into one. Having 2 dialogs is just a 1:1 binding to git commands, which is not really intuitive. I'm going to implement that, but not in the next update.

great, thanks 🙏

**Comment by DanPristupov** [comment]
I couldn't resist. It's done in 1.0.72 :)

**Comment by Turbo87** [comment]
hahaha, awesome! thanks a lot!
