### ISSUE TITLE
1px wide holes in the diff view

### ISSUE THREAD

**Issue by dkiszkiel** [ForkIssues/Tracker#466]
There are random 1px wide gaps in the diff view, both in the red and green backgrounds. The issue happens both in the high and low dpi displays, but is much more noticeable with the low dpi.
Fork 1.0.71.2
![zrzut ekranu 2018-11-28 o 10 43 34](https://user-images.githubusercontent.com/30291437/49143230-e60a9880-f2fa-11e8-97bc-9d694a7c660b.png)

**Comment by DanPristupov** [comment]
Bug in NSTextView https://stackoverflow.com/questions/48282512/visual-glitch-in-nstextview
