### ISSUE TITLE
Behind/ahead info no longer displayed next to branch

### ISSUE THREAD

**Issue by lpeabody** [ForkIssues/Tracker#468]
Version 1.0.72.1

Prior versions showed the number of commits to be pulled/pushed from the remote tracking branch. I no longer see this information displayed next to the branch name. I currently have two commits that were not pushed up to the remote and there is no indicator of this next to the branch name in the sidebar.

**Comment by DanPristupov** [comment]
Hi. This is a bug. Behind/ahead info is not displayed for branches in subdirectories. I'm going to release the hotfix ASAP.

**Comment by DanPristupov** [comment]
Please check for the 1.0.72.2 update.

**Comment by kuthair** [comment]
This is working.
