### ISSUE TITLE
Display buttons "Commit" & "Commit and Push" in the same view

### ISSUE THREAD

**Issue by Niels-NTG** [ForkIssues/Tracker#47]
In my workflow I often switch between committing and immediately pushing or just committing. To prevent myself between going into preferences to toggle this option multiple times a day, I would like to suggest to display both buttons below the commit message field:

- Commit
- Commit and Push

The option in preferences then decides what button is highlighted by default.

**Comment by DanPristupov** [comment]
Hi @Niels-NTG. Thank you for describing your workflow, it makes sense.

I don't like the idea of adding one more button which will be used by very few people. I'd rather use the `alt`-modifier instead.

For example in the Commit view the Stage/Unstage buttons become Stage-All/Unstage-All when user holds the `option` key. I think handling `alt`+Commit as "Commit and Push" should logically fit there. What's your opinion?

**Comment by Niels-NTG** [comment]
An ⌥-modifier sounds great! Looking forward to it!

**Comment by DanPristupov** [comment]
Hi Niels. I just released Fork 1.0.50 which allows to commit and push when you hold the `option` key.
![2017-06-30 at 16 00](https://user-images.githubusercontent.com/618115/27738993-65eba7d6-5dad-11e7-90cb-4d757678b474.gif)
P.S. The release also contains some other features you requested.

**Comment by Niels-NTG** [comment]
Great! One thing: it would make more sense if this worked no matter if "Automatically push on commit" is enabled or not.

**Comment by DanPristupov** [comment]
@Niels-NTG not sure I understand you correctly. It's an absolutely standalone feature. it works for every user regardless on "Automatically push on commit" settings.

**Comment by Niels-NTG** [comment]
@DanPristupov This doesn't seem to be the case on my build of 1.0.50

**Comment by DanPristupov** [comment]
What happens when you press alt? Does the submit button become "Commit and push"?

**Comment by Niels-NTG** [comment]
When  "Automatically push on commit" is enabled, the button "Commit and push" doesn't change into "Commit" when pressing alt as expected.

**Comment by DanPristupov** [comment]
Ah, right... I missed that.

**Comment by DanPristupov** [comment]
OK, I've fixed this. I don't want to annoy people too much with frequent updates, so I'll send you the fixed build by email. The rest will get it in 1.0.51 :).
