### ISSUE TITLE
Fork no longer sees merge conflicts resolved using external tools.

### ISSUE THREAD

**Issue by kuthair** [ForkIssues/Tracker#470]
When resolving merge conflicts using external tools -- whether initiated from within Fork (using "merge in External tool") or outside -- are no longer "seen" by Fork.

Fork keeps the files listed as in conflict.

**Comment by DanPristupov** [comment]
I've fixed that already. I'm going to sleep, double check everything tomorrow morning and release the update.

**Comment by kuthair** [comment]
Ha! Awesome... I figured you were on top of it, but thought better safe than sorry.

**Comment by DanPristupov** [comment]
Please check for updates.

**Comment by kuthair** [comment]
Working.. thanks!
