### ISSUE TITLE
1000 days of Fork

### ISSUE THREAD

**Issue by DanPristupov** [ForkIssues/Tracker#479]
Today is 1000 days since I made my initial commit to the Fork repository. I think it could be interesting to look at some stats.

**Project Name** Fork
**Generated** 2018-12-13 13:43:59 (in 15 seconds)
**Report Period** 2016-03-19 11:30:49 to 2018-12-13 13:39:37
**Age** 1000 days, 623 active days (62.24%)
**Total Files** 955
**Total Lines of Code** 90873 (215763 added, 124890 removed)
**Total Commits** 3893 (average 6.2 commits per active day, 3.9 per all days)
**Authors** 2

### List of Authors
<img width="756" alt="screenshot 2018-12-13 at 13 54 22" src="https://user-images.githubusercontent.com/618115/49940000-ac32b800-fede-11e8-9f3f-f61a33a71104.png">

### Lines of Code
![image](https://user-images.githubusercontent.com/618115/49939878-5231f280-fede-11e8-8abb-de74f254fff1.png)

**Comment by DanPristupov** [comment]
May be it would be nice to have similar stats in Fork.

**Comment by maksimovic** [comment]
After seeing just the title, I thought you're sharing stats from the user base 😈 

I love these kinds of reports, would be nice to see some stats in Fork, too :D

**Comment by ChadTaljaardt** [comment]
This is really cool, 

Good job!
