### ISSUE TITLE
The "Stage" and "Discard Changes..." buttons disappear after clicking

### ISSUE THREAD

**Issue by darinkrauss** [ForkIssues/Tracker#480]
I'm running Fork 1.0.72.2 on Mac.

In the Uncommitted Changes view, in the right-hand pane with the list of changes, if I hover over a chunk of changes then a popup appears in the upper-right corner with "Stage" and "Discard Changes..." buttons. If I click either button those buttons will disappear even if there is another block of code following that has to be staged (or not). I have to move the mouse a small amount for the buttons to reappear so I can click "Stage" or "Discard Changes..." again.

This behavior gets in the way of quickly reviewing and accepting a long list of changes in a file.

Let me know if you need any further information.

**Comment by DanPristupov** [comment]
It makes sense. I'll have a look if that can be improved.
