### ISSUE TITLE
Opening submodule after cloning repository doesn't work

### ISSUE THREAD

**Issue by Tunous** [ForkIssues/Tracker#482]
When I clone a repository that has submodules and open it in Fork I'm initially unable to open submodules. Right clicking and selecting open action or double-clicking doesn't do anything. To fix the issue I first have to perform pull action from the toolbar. It would be nice for Fork to automatically init submodules when trying to open them.

**Comment by Tunous** [comment]
It might be that this repository was cloned from the command line without the recursive flag. I'm not sure right now. I'll try to reproduce this again tomorrow testing both ways.

**Comment by Tunous** [comment]
I've managed to reproduce the issue. It happens both when cloning from Fork or command line but requirements are a bit specific. The repository I was testing this on has a default master branch which has no submodule directories in it. The submodules are only added on develop branch. So after switching from master to develop submodules appear in the sidebar but it is not possible to open them.

**Comment by DanPristupov** [comment]
OK, so wee need the ability to fetch submodule changes, right?

**Comment by Tunous** [comment]
That appears to be happening when you perform pull action, but it's not easy to find this when you run into a situation where submodule doesn't open. Ideally that data should be fetched when you attempt to open the submodule so it would always open correctly.

**Comment by DanPristupov** [comment]
I forgot to mention that in 1.0.74 I introduce an option to update submodules (it's available in the context menu).
