### ISSUE TITLE
Commit message gets cut off last character

### ISSUE THREAD

**Issue by oonoo** [ForkIssues/Tracker#483]
When I enter a commit message and hit the keyboard with CMD + Return the commit message gets cut off the last character and the commit gets made. 

I would not expect the commit message to get cut off the last character. It doesn't happen with other git tools.

Example: I enter "Fix typo" in the commit message text field and then hit CMD + RETURN. The result is a commit with the commit message "Fix typ". The "o" in the end is missing.

**Comment by DanPristupov** [comment]
I can't reproduce that. Please check if you have a commit-message hook.
