### ISSUE TITLE
Created new branch has tracking original branch automatically

### ISSUE THREAD

**Issue by kmrmshk** [ForkIssues/Tracker#484]
I'm using 1.0.72.1 for mac.
When I try to create new branch from remote branch, it has checked tracking origin branch on remote automatically.
However, sometimes that is not checked by same procedure.
Is it in the specifications?

**Comment by DanPristupov** [comment]
Technically, we can't checkout a remote branch, we can only checkout a local one.

So, when we checkout Remote Branch there are two cases:
- if there's a local branch which tracks that remote branch, then checkout it. It's possible that the local branch is located on a different commit though.
- if there's no corresponding local branch, propose to create one (i.e. to track it).

**Comment by sunyuu** [comment]
The same question for me, when i create new branch from master, sometimes i just push the commit to the master.if it possible, i hope there is a preference setting that a new branch not tracking any branch.
