### ISSUE TITLE
[Feature Request] portable Fork

### ISSUE THREAD

**Issue by bennieboj** [ForkIssues/Tracker#486]
Would it be possible to to store all data inside the Fork install folder and make all paths relative instead of the hardcoded? (%LOCALAPPDATA%/Fork or something similar on unix)
It would be so useful to be able to share this program across computers :)

**Comment by DanPristupov** [comment]
This is a mac OS tracker. Is mac OS applications are not supposed to keep store any data in the installation folder.

**Comment by bennieboj** [comment]
Ok good to know, thanks!
This issue can be closed and the discussion can continue here: [https://github.com/ForkIssues/TrackerWin/issues/85](https://github.com/ForkIssues/TrackerWin/issues/85)
