### ISSUE TITLE
Support Ctrl+Cmd+F to switch into Fullscreen mode on MacOS

### ISSUE THREAD

**Issue by rax-valtech** [ForkIssues/Tracker#49]
Most MacOS apps support this shortcut to toggle into Fullscreen mode. It would be nice if it was supported. Currently I have to click on the expand icon in the left upper corner of the window to expand into Fullscreen mode.

**Comment by DanPristupov** [comment]
Hi @rax-valtech. Thank you for the request. Will add the Ctrl+Cmd+F shortcut in the next update (1.0.50).

**Comment by DanPristupov** [comment]
Done.
