### ISSUE TITLE
How can I do a squash merge

### ISSUE THREAD

**Issue by bwl21** [ForkIssues/Tracker#491]
I cannot find how to do the equivalent of 

```
git checkout master
git merge --squash bugfix
git commit
```

using fork

**Comment by DanPristupov** [comment]
There isn't such an option, however you can squash commits using Interactive Rebase.

But you can create a branch custom action which will perform what you want.

**Comment by bwl21** [comment]
Could you add a checkbox in the merge dialog?

**Comment by ChrisChinchilla** [comment]
I always liked the way tower does squashing, could look there for inspiration…?

**Comment by DanPristupov** [comment]
@ChrisChinchilla could you show a screenshot?

**Comment by ChrisChinchilla** [comment]
<img width="1440" alt="Screenshot 2019-06-24 18 50 41" src="https://user-images.githubusercontent.com/42080/60037074-fcba7780-96b0-11e9-86a8-646cdd205acb.png">

There you go. You select multiple commits, right click, and select squash.

**Comment by DanPristupov** [comment]
We are planning to introduce a similar option which will open the IR dialog with predefined settings.

Similar to what we have now:
<img width="519" alt="image" src="https://user-images.githubusercontent.com/618115/60037894-21afea00-96b3-11e9-9dce-e03c64a17a24.png">

**Comment by ChrisChinchilla** [comment]
Ahh, I hadn't noticed that @DanPristupov I think I was too used to the way Tower does it, and this looks similar, but just the other way around. I'll try this next time, maybe it solves the use case I personally have.

**Comment by DanPristupov** [comment]
Regarding the original request. In Fork 1.0.85 we introduced the `merge --squash` option:
<img width="509" alt="Screenshot 2019-10-18 at 14 45 22" src="https://user-images.githubusercontent.com/618115/67095327-eda68a80-f1b5-11e9-80c3-072b0b476a36.png">
