### ISSUE TITLE
Show stderr too in pre-commit hooks

### ISSUE THREAD

**Issue by elia** [ForkIssues/Tracker#493]
pre-commit hooks stderr output is being cut off, some tools use it to show the actual errors that prevented the commit

**Comment by elia** [comment]
Upon further inspection it was due to missing env vars causing a sub-command not to run (and that's another issue)

**Comment by DanPristupov** [comment]
This could be helpful: https://github.com/ForkIssues/Tracker/issues/430#issuecomment-429013890
