### ISSUE TITLE
Request: command history

### ISSUE THREAD

**Issue by jakebathman** [ForkIssues/Tracker#494]
Sometimes I'd like to see the `git` commands that Fork has run for a certain operation. It'd be great to see that command history somewhere, possibly including the output from the `git` commands as well.

**Comment by maksimovic** [comment]
I'd find this useful sometimes, too. Something like `View` -> `Console` (example from Sequel Pro) or something similar.

**Comment by stianhoiland** [comment]
I'd love to see this, too. Any comment?

**Comment by DanPristupov** [comment]
Technically, it's not what my code is prepared for. In Fork git requests are quite low-level stuff and there's no easy way to show them in UI (because they are on absolutely different application layers). I might introduce some cross-cut notifications for that, but it's a not really nice approach...

Could you give me some examples of what requests you'd like to see?

**Comment by YesThatAllen** [comment]
I just tried to add a submodule to a repo, but the access I have to that submodule is via another github account/ssh key.

Being able to see the command Fork was trying to use to add a submodule would be useful

**Comment by DanPristupov** [comment]
Fork rarely does complicated stuff. In that case it's just `git submodule add url`.

If you have a question like that in the future, feel free to use the feedback button, I usually answer quite fast.

**Comment by chriswill0w** [comment]
The functionality I am looking for would be similar to "Command History" in SourceTree (View -> Show Command History). A nice place in Fork would be in the popup which opens when you click in the top toolbar on the button to the left of the branch name. The executed/executing actions are already listed there and the exact git command(s) could be shown there.

**Comment by maxpdx** [comment]
Here's what I'd LOVE to see in Fork(git commands ran in a "activity history" panel/window):
<img width="551" alt="Screen Shot 2019-09-17 at 10 38 00 AM" src="https://user-images.githubusercontent.com/15226023/65065616-9e133b80-d937-11e9-8ecd-1915f6eddd99.png">
![command-output](https://user-images.githubusercontent.com/15226023/65065075-9b641680-d936-11e9-948b-364386ff889d.png)
![git-output](https://user-images.githubusercontent.com/15226023/65065084-9f903400-d936-11e9-91f6-44d82fc18035.png)
some screenshots from smartgit

**Comment by DanPristupov** [comment]
Activity manager shows output for important commands (clone, fetch, pull, push, checkout, commit, etc).

<img width="711" alt="Screenshot 2019-09-17 at 19 59 26" src="https://user-images.githubusercontent.com/618115/65066932-a98d5380-d985-11e9-943d-7872d4edf85d.png">

**Comment by DanPristupov** [comment]
In 1.0.88 more commands are shown in the activity manager
<img width="910" alt="Screenshot 2019-12-13 at 16 19 47" src="https://user-images.githubusercontent.com/618115/70810608-63009700-1dc4-11ea-999c-17073b780d50.png">
