### ISSUE TITLE
Cannot create remote on new repository

### ISSUE THREAD

**Issue by mtschoen-unity** [ForkIssues/Tracker#495]
Hello there,

I'm reporting what I think is probably a minor oversight. When you create a new repository with Fork on OS X, or probably are viewing any repository without any remotes, you cannot create a new one. Right-clicking on the Remotes foldout doesn't do anything until I go into terminal, add a new remote, and then come back to Fork. At that point I can add new remotes as expected.

Thanks!

**Comment by DanPristupov** [comment]
I just checked in 1.0.72 (and 1.0.73) and couldn't reproduce no problem. Right click on the `Remotes` shows the context menu as required:

<img width="381" alt="image" src="https://user-images.githubusercontent.com/618115/52044808-4c9e7380-2543-11e9-8148-37bb9f23a59e.png">

**Comment by mtschoen-unity** [comment]
Great! I'll let you know if I find anything else that comes up in my worflow :)

**Comment by mtschoen-unity** [comment]
Confirmed the fix in 1.0.73
