### ISSUE TITLE
Adding submodule doesn't give option for recursive checkout

### ISSUE THREAD

**Issue by mtschoen-unity** [ForkIssues/Tracker#496]
Seems petty explanatory. I'd like to see an option to do a recursive clone when first adding a submodule. Or just do a recursive clone by default.

**Comment by DanPristupov** [comment]
Just a note. I just checked the source code and the usual repository clone in Fork always uses the `--recurse-submodules` option, so everything is OK when we clone a whole repo.

Regarding the submodule adding.
According to documentation (https://git-scm.com/docs/git-submodule), there's no `--recursive` option for the `git sudmodule add` command. So, I suppose Fork should perform two requests to achieve that:
1. `git submodule add ...` to add and clone the target submodule
2. `git submodule update ..` to clone the nested submodules

**Comment by descorp** [comment]
@DanPristupov what about "Update" option for submodules in general?

I have been trying to create Custom Action for 
'git submodule update --recursive --remote'

But it seems that Custom Actions only support **basic** git operations.
Fork Mac, Version 1.0.73.5

**Comment by mtschoen-unity** [comment]
I would say recursive can/should always be an option. I may have some large repo that I want to add as a submodule and essentially just "indicate" that it's there for the purpose of making the modification locally, without having to endure the actual download of all of its contents. I have sometimes used otherwise-empty repos as pointer collections to other repos, and if you clone them non-recursively you only download a few kilobytes.

**Comment by DanPristupov** [comment]
@descorp If I remember correctly, `git submodule` requires `:/usr/local/bin` in your PATH ENV.
You have two options:
- run Fork from terminal (in this way it will inherit ENV of the parent process)
- make a small .sh script which will set PATH and run your command

**Comment by DanPristupov** [comment]
@descorp ignore my previous post. I will make it work out of the box in the next update.

**Comment by DanPristupov** [comment]
I added a quick option to update submodule to the context menu on the sidebar. Please check for the 1.0.74 update.

We are planning to introduce more submodule-related improvements in 1.0.75.

**Comment by mtschoen-unity** [comment]
Confirmed the new option. Just to be clear, the process would be to Submodule Add... and then Submodule Update on the new submod? Works for me! 👍

**Comment by DanPristupov** [comment]
To be honest, I'm not sure. Now it works same way as in git. It means users will not be confused anyway, right?

However we can proceed with the initial request and add a checkbox to the 'Add Submodule' dialog.

**Comment by mtschoen-unity** [comment]
👍 to the checkbox in Add Submodule. And at least from now on _I_ won't be confused :)

**Comment by descorp** [comment]
Hey @DanPristupov 

I just tried new feature in 1.0.74
Works smoothly, but command log shows nothing:
![screenshot 2019-02-18 at 16 12 40](https://user-images.githubusercontent.com/2648655/52960212-96d38180-3398-11e9-8d6a-53b7ddda10b3.png)

**Comment by DanPristupov** [comment]
That's what `git submodule update` shows.

**Comment by DanPristupov** [comment]
We added the 'fetch recursive' checkbox to the add submodule dialog in Fork 1.0.75
