### ISSUE TITLE
multiple windows

### ISSUE THREAD

**Issue by danh1979** [ForkIssues/Tracker#5]
I would like to be able to have multiple Fork windows open.

Usually, I'm using multiple Desktops, with a different set of terminals, text editors (usually TextMate), etc. open on each one, probably for different long-running projects or tasks.

I can assign the Fork window to all desktops via the icon in the Dock, but that blurs the boundaries between why I'm using different Desktops in the first place.

Currently, I just keep closing tabs and reopening them. I've recently discovered I can run multiple instances of Fork from the terminal, like ` /Applications/Fork.app/Contents/MacOS/Fork`, but haven't tried it long enough to see if that breaks anything. Edit: nope, as of 1.0.43, both windows update when opening another project.

**Comment by aziz** [comment]
couldn't agree more. Tabs are great idea but they shouldn't replace the windows feature. I should be able to tear apart a tab into a separate window and merge them back again. All my favorite dev tools, e.g. iterm2 and sublime, can do this already and it feels so natural to have it in fork as well

**Comment by aziz** [comment]
Another related feature request: 
### Hide tab bar if only one tab is open
The tab bar is redundant when you have only one tab open, which in 99% of the time for me.

**Comment by clounie** [comment]
Like the window idea.

Disagree @ hiding the tab bar. Having to look to the top when I'm used to looking for the tab bar would be annoying. So maybe as an option if anything? Though that should probably be a separate issue.

**Comment by DanPristupov** [comment]
Thanks guys. I see that having multiple windows is an important feature for you all.
I can't add this feature quickly because currently Fork is tight-coupled to a single window. I'm going to start gradually refactoring the architecture which will allow me implement multi-window GUI in the future.

Hiding the tab bar can be done as an option in the preferences, but this should be discussed in a separate issue as @clounie mentioned.

**Comment by danh1979** [comment]
Awesome, thanks!

**Comment by kissferenc** [comment]
I also want this feature. When will be arrived?
I working on multiple projects. One project has multiple gits. So I would like separate projects by windows.

**Comment by DanPristupov** [comment]
I just released Fork 1.0.68 prerelease (https://github.com/ForkIssues/Tracker/issues/318).

@kissferenc Finally, it's there. Could you try it?
