### ISSUE TITLE
Make sure all items in the toolbar are also in the menus.

### ISSUE THREAD

**Issue by prenaux** [ForkIssues/Tracker#50]
I'd like to hide the toolbar but I need "Open in Terminal" which is only in the toolbar and can't be found in the menu.

**Comment by cdzombak** [comment]
This also allows an item to be accessible via the `⌘⇧/` search shortcut, which is helpful even if you haven't hidden the menu bar.

**Comment by DanPristupov** [comment]
I started working in this issue and noticed that "Open In Terminal" already in the repository submenu:
<img width="260" alt="2017-06-30 at 08 52" src="https://user-images.githubusercontent.com/618115/27724306-9ffa5396-5d71-11e7-9c71-c2086020eb39.png">

So, the only toolbar item which is not in the menu yet is "Save stash" and I'm going to add it. Is there anything else I'm missing?

@cdzombak, I didn't know about it, thanks. Very useful.

**Comment by DanPristupov** [comment]
Done in 1.0.50
