### ISSUE TITLE
Git messages can display in wrong language if multiple Preferred Languages are set in System Preferences

### ISSUE THREAD

**Issue by Wevah** [ForkIssues/Tracker#501]
I have 3 languages set in my Preferred Languages in the Language & Region prefpane: English, German, and Japanese. Git messages through Fork display in German, unless I remove German from the list (also tested with French in the second spot; same thing, just with French messages). The UI properly displays in english.

**Comment by Wevah** [comment]
Upon further testing, this looks like a Git/my computer issue. Setting a LANG, LC_ALL, and LC_CTYPE to an empty string causes Git to display messages in German for me as well.

**Comment by Wevah** [comment]
If anyone was curious, it looks like the culprit was a missing `en_US` directory + proper files in `/usr/local/share/locale`, which I think was installed by a non-system compile of a library I installed at some point.

Renaming/deleting `/usr/local/share/locale` seems to fix the issue. I also deleted my self-installed libiconv + headers so it would recompile with the system one, but the renaming of the directory is what caused it to display properly for me. (Alternatively, I suppose, setting the `LANG` or `LC_ALL `environment variable could work around it.)

**Comment by Wevah** [comment]
One last comment with more clarification: Apparently `locale/de/` had a `git.mo` file in it, but no English one did (and the only one of those was `en_GB` for some odd reason).

(Using self-compiled Fit, fwiw.)

**Comment by Wevah** [comment]
Looks like the localization stuff is via the gettext library. Will test compiling without it.

**Comment by Wevah** [comment]
Ok, as far as I can tell it's a bug in gettext on macOS. The macOS-specific fallback code only checks for the literal string `"en"`, but not the prefix `"en-"` on language codes it gets back from the `"AppleLanguages"` defaults key.

**Comment by Wevah** [comment]
Okay, real last post probably. This can be fixed in gettext by replacing both instances of

    if (strcmp (buf, "en") == 0)

with

    if (strncmp (buf, "en", 2) == 0)

in gettext's langprefs.c. I've replied to that thread on the Git mailing list, and am going to submit a patch to gettext's maintainer once I find out how.

**Comment by Wevah** [comment]
I received a reply that this is fixed in the current gettext git master, and will show up in the next release.

(Ref: https://savannah.gnu.org/bugs/?49560)

**Comment by DanPristupov** [comment]
Congratulations on actually fixing the problem!

Just for my curiosity, why do you use self-compiled Git?

**Comment by Wevah** [comment]
I like my Git to be up-to-date, and compiling it is really simple as it doesn't have very many dependencies. Compiling stuff myself is also just kind of fun, for some reason.
