### ISSUE TITLE
"View on" and "Terminal" buttons look inactive in dark mode

### ISSUE THREAD

**Issue by Niels-NTG** [ForkIssues/Tracker#51]
![image](https://user-images.githubusercontent.com/6061595/27484468-979a0702-5829-11e7-8f57-004947dbf74d.png)

See screenshot above. "View on" and "Terminal" buttons look like they aren't clickable in dark mode, yet they work normally.

**Comment by DanPristupov** [comment]
Hi.

Thanks for reporting this. I'll fix the icons in the upcoming update (1.0.50).
