### ISSUE TITLE
Invalid Git binary

### ISSUE THREAD

**Issue by dooreelko** [ForkIssues/Tracker#510]
I have a shell script (called `git` in some directory not on path) that detects and configures proxy settings and then passes the control to the actual git binary. When I try to point Fork to use it, it tells me `... is not a valid Git binary.` What is the check behind that?

**Comment by DanPristupov** [comment]
There are 3 checks:
1. The target path exists
2. Git-core directory path exists (so, if your git path is `/path/to/git/bin/git`, the `/path/to/git/libexec/git-core` directory must exist)
3. `git version` request must return correct response.

**Comment by DanPristupov** [comment]
Regarding the `git-core` path (2). Previously it was required to ensure that submodule commands work properly.
However I just made a shallow looks and it seems that nowadays it's not needed anymore. I might remove it in the future.

**Comment by dooreelko** [comment]
Let's happily close this, unless you want to reuse it later for git-core check.

**Comment by DanPristupov** [comment]
I'll create a separate issue in my internal issue tracker.

**Comment by DanPristupov** [comment]
For the rocket scientists: we must have `git-core` in PATH, otherwise `git submodule ...` requests don't work.

**Comment by slatlasdev** [comment]
Can this be revisited? `git-core` is not required, the base `git` command supports `submodule` fine. This makes getting custom git wrappers working harder than it needs to be.
