### ISSUE TITLE
Invoking new branch shortcut multiple times will bring the prompt multiple times as well

### ISSUE THREAD

**Issue by maksimovic** [ForkIssues/Tracker#511]
1. Hold <kbd>Shift</kbd>+<kbd>Cmd</kbd>
2. While holding those keys, press <kbd>B</kbd> a few times (not too many 😄), like maybe 3 times: <kbd>B</kbd><kbd>B</kbd><kbd>B</kbd>.
3. Cancel the prompt, and another one will appear. Cancel that one, too, and ANOTHER one will appear. So, as many times as you hit <kbd>B</kbd>, you'll get that many prompts 😁 

I found this by accident, because the first prompt didn't appear quickly enough (Fork has been idle for a long time while I was busy with other stuff) and I thought that I failed to press one of the keys, so I pressed <kbd>Shift</kbd>+<kbd>Cmd</kbd>+<kbd>B</kbd> one more time, and after creating a branch I got the prompt again.

I'm on 1.0.73.1 pre-release if it matters, but it probably affects the current stable version as well.

**Comment by DanPristupov** [comment]
Fixed, thanks.

> a few times (not too many 😄), like maybe 3 times

I was brave and pressed 6 times may be. Then I realized your warning :).

**Comment by maksimovic** [comment]
Got the v1.0.73.2, no more B-spam allowed 🎉
