### ISSUE TITLE
Push doesn't preselect remote tracking branch when its name differs

### ISSUE THREAD

**Issue by maksimovic** [ForkIssues/Tracker#512]
So, if I check out someone else's branch `X` as branch `Y`, create a few commits and then go to push changes, Fork automatically wants to create a new branch Y on that remote - instead of offering the push to the branch on the remote which is being tracked (`X`).

I would suggest that, if there's already a tracking reference from local branch `Y` to `remote/X`, then by default offer pushing at `remote/X` instead of offering the push to a new `remote/Y`.

In my case, just locating the branch `remote/X` in the dropdown takes a while 😅

**Comment by DanPristupov** [comment]
Is that still true in 1.0.73-74?

**Comment by maksimovic** [comment]
Yes, but it doesn't seem to be consistent. Now the same branch that was driving me nuts the entire day started to be nice and offer the proper remote branch for the push.

Will try to play around more in order to figure out a pattern... if there's one 😁

**Comment by DanPristupov** [comment]
OK. On my side, I'll check the code tomorrow morning.

**Comment by DanPristupov** [comment]
Yes, it's exactly as you described. I'll fix this in 1.75

**Comment by DanPristupov** [comment]
Fixed

**Comment by maksimovic** [comment]
Looks good 🎉
