### ISSUE TITLE
Allow to skip pre-commit hooks (some way)

### ISSUE THREAD

**Issue by elia** [ForkIssues/Tracker#513]
I work on a project that's very heavy on pre-commit hooks, and often they need to be skipped. I know the "commit with no-verify" has been removed recently. These are the alternative solutions I that I can see working for me:

- Add a check near `amend` to skip verification
- Add a key modifier that will change the commit button in "commit without verifying"
- Allow to easily copy the whole commit message (⌘A + ⌘C) so that I can go to the terminal and do `git commit -n` manually

**Comment by DanPristupov** [comment]
I think we will proceed with the the first option. I will introduce an option to skip hooks.

**Comment by DanPristupov** [comment]
Alright, the option to skip pre-commit hooks is back in 1.0.74. After a week I found another approach to make it work. Please check for updates.

**Comment by Naatan** [comment]
Where is this option? Mine seems to always be skipping pre-commit hooks.. :\

**Comment by DanPristupov** [comment]
@Naatan The option to skip pre-commit hooks will appear in the error dialog which appears on hook failure.

Actually Fork doesn't run hooks, git does.
Are you sure your hook has executable rights (`chmod +x`)?
Did it work previously?

**Comment by debone** [comment]
I used to be able to skip this hooks some time ago, but now the pop-up is showing up like this
![image](https://user-images.githubusercontent.com/763457/56726380-e6df1380-674e-11e9-8d5a-0e24719b6b62.png)
Was there any changes related to it? I'm on version 1.0.77

**Comment by DanPristupov** [comment]
@debone Are you sure you have a `pre-commit`, `commit-msg` or `post-commit` hook in `.git/hooks`?

**Comment by debone** [comment]
Hey @DanPristupov, yes, I do have only a pre-commit

```bash
~/sources/project/ <master> » cat .git/hooks/pre-commit
#!/bin/sh

npm run lint
```
And this command fails because reasons, and I'd like to skip it as I'm not looking into fix it

**Comment by DanPristupov** [comment]
@debone are you sure your hook fails because of reasons and not because of different ENV? Did you start Fork from CLI? If not, then you probably should.

**Comment by debone** [comment]
Yeah, I start it from the CLI. I wrote reasons because the hook doesn’t work on the CLI also, and it’s not a straight forward reason. I just wanted to skip it :p
