### ISSUE TITLE
Tab indicator for uncommitted changes

### ISSUE THREAD

**Issue by vassilevsky** [ForkIssues/Tracker#515]
Hello 👻

I usually have Fork open during my entire work day. I have about 15 tabs open, with all the repos I actively maintain and contribute to.

Throughout the day, I make changes to some of them. Often times I make small changes to test locally and then I forget about it.

There is currently no way for me to see which repos are dirty after my work day. It would be cool if they were visible somehow.

Thanks! 😘

**Comment by DanPristupov** [comment]
Will a 'dirty' icon (or symbol) in the tab header be helpful?

**Comment by DanPristupov** [comment]
Aaand it's here! Please check for updates!

**Comment by vassilevsky** [comment]
Wow! So fast! Yes, it works! Thank yo very much! 😘

**Comment by DanPristupov** [comment]
I would implement it earlier if you had asked ;) `¯\_(ツ)_/¯`
