### ISSUE TITLE
integrate with Azure Devops

### ISSUE THREAD

**Issue by fbfmarc** [ForkIssues/Tracker#518]
Fork has integration with several cloud based get repo providers.  I could make extensive use of Fork if it could integrate with Azure Devops repos.  Then I could use this client on a much broader set of projects.  Thank you!

**Comment by Meligy** [comment]
I'm using Fork with an Azure DevOps repo right now, and have been doing so since forever. It works just fine.

It might be useful to specify which areas of the app that require specific treatment of Azure DevOps that the feature requests.

**Comment by fbfmarc** [comment]
That would be wonderful - where did you configure it?



On February 18, 2019 at 22:23:04, Meligy, GuruStop.NET (notifications@github.com<mailto:notifications@github.com>) wrote:

I'm using Fork with an Azure DevOps repo right now, and have been doing so since forever. It works just fine.

It might be useful to specify which areas of the app that require specific treatment of Azure DevOps that the feature requests.

**Comment by DanPristupov** [comment]
@fbfmarc he probably meant that you don't need any special support to work with Azure repos. Fork will prompt the credentials on fetch/push.

**Comment by Meligy** [comment]
If you are talking about credentials, then yes I'm not sure how the login flow works in Flow.

I usually clone the repos in terminal using Microsoft's Git-Credential-Manager ([Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows) | [Mac/Linux](https://github.com/Microsoft/Git-Credential-Manager-for-Mac-and-Linux)), which integrates well with browser based login.

**Comment by fbfmarc** [comment]
Ah! OK. Use command line to set everything up and then access the local repo with Fork.  Got it.  thanks



On February 19, 2019 at 21:09:42, Meligy, GuruStop.NET (notifications@github.com<mailto:notifications@github.com>) wrote:

If you are talking about credentials, then yes I'm not sure how the login flow works in Flow.

I usually clone the repos in terminal using Microsoft's Git-Credential-Manager (Windows<https://github.com/Microsoft/Git-Credential-Manager-for-Windows> | Mac/Linux<https://github.com/Microsoft/Git-Credential-Manager-for-Mac-and-Linux>), which integrates well with browser based login.

**Comment by chucker** [comment]
A few integrations Fork has for GitHub but not for Azure DevOps*

* when cloning, available repositories are populated*
* inside a repo, there's a **View on GitHub** item (in the Share button menu)

I'm guessing there's more.

I in particular use Azure DevOps Server (rather than the cloud version), so integration might be tricky.

*) This suggests that Fork manages "accounts" or "services" somewhere, but I can't actually find a UI for that right now. If it does, it'd be nice if Azure DevOps could be another service type.

**Comment by jesusramondovale** [comment]
Hi! I've using Fork with my enterprise Azure DevOps and now I can't authenticate anymore. Is it not compatible?

**Comment by DanPristupov** [comment]
> I've using Fork with my enterprise Azure DevOps and now I can't authenticate anymore.

How did you authenticate before?

**Comment by jesusramondovale** [comment]
I got it working now, I had to clone the repo on git bash, which creates the git:https credential on Windows Credential Manager. That's a little bad because I've got to change the password once a month. 

Before this I was using a SSH key
