### ISSUE TITLE
How do I stop tracking a remote branch?

### ISSUE THREAD

**Issue by tamilveeran** [ForkIssues/Tracker#521]
I created a new branch from a commit. Add more commits and tried to push. Now the local tracks the remote branch (from which I checked out) when I try to push. But I want to create it as a new branch on origin. How do I stop tracking remote ?

**Comment by DanPristupov** [comment]
Hi. You can change (or remove) tracking reference in context menu for local branch on the sidebar.

<img width="500" alt="screenshot 2019-02-13 at 08 39 08" src="https://user-images.githubusercontent.com/618115/52694704-d9492880-2f6a-11e9-9193-1d87cc6e063d.png">
