### ISSUE TITLE
Submodule diff is broken when git config has `diff.submodule=log`

### ISSUE THREAD

**Issue by stk-ableton** [ForkIssues/Tracker#522]
If your git config contains `diff.submodule=log`, then the diff area for submodule changes is empty. When removing the option, submodule diffs show properly.

(As a fix, you probably need to add `--submodule=short` to the `git diff` command that you run to get the changes, so that you're independent of the config.)

**Comment by DanPristupov** [comment]
> As a fix, you probably need to add `--submodule=short` to the `git diff` 

Absolutely correct!

**Comment by DanPristupov** [comment]
Fixed in 1.0.74
