### ISSUE TITLE
Crash when creating a new branch

### ISSUE THREAD

**Issue by mtancock** [ForkIssues/Tracker#523]
I'm in a submodule of my main repo, and every time I create a new branch (right clicking on the left-hand panel), I fill in the branch name and click "Create & Checkout" and fork crashes.

When I restart Fork, the branch has been created and checked out. This has happened about 5 times in a row now, so seems fairly reproducible. Unfortunately I can't see any crash reports in console.log but maybe I'm looking in the wrong place.

I'm running the latest version according to "Check for Updates": 1.0.73.4

**Comment by DanPristupov** [comment]
Hi. Thank you for the report.

Do you use submodules?

**Comment by mtancock** [comment]
I do (I mentioned that I was in a submodule originally) although I just checked on a repo which doesn't have any submodules and still got a crash. I have 3 tabs open, (some of which contain / are submodules).

**Comment by DanPristupov** [comment]
Could you please open terminal and run `git submodule update --init --recursive` and then try to create a branch again?

**Comment by DanPristupov** [comment]
Do you use 'Fork git instance' in Fork preferences?

**Comment by mtancock** [comment]
Updating the submodules didn't seem to help. I updated the parent repo, and it still crashed.

I'm using Apple's Git (as it seems to be a slightly later update (2.17.2 vs 2.17.1)

I just tried switching to the Fork one, restarting Fork and then doing the same thing and it still crashed.

**Comment by DanPristupov** [comment]
Some people experience that issue but I can't understand why that happens.

Can I send you a develop build with additional logging? Please contact me by email support@forkapp.io and I'll do my best to fix this ASAP.

**Comment by DanPristupov** [comment]
Just an idea. Do you have enough free RAM?

**Comment by mtancock** [comment]
I'll e-mail you. A dev build will be fine. I appear to have enough free RAM. Activity Monitor says only 20 of my 24GB available is in use.

**Comment by DanPristupov** [comment]
I just found the bug 🎉! I'm going to send you a hotfix release during an hour.
The official Fork update is going to come out Tomorrow.

**Comment by DanPristupov** [comment]
1.0.74 is out!
