### ISSUE TITLE
[Windows] Resolve conflicts issue

### ISSUE THREAD

**Issue by s-dezign** [ForkIssues/Tracker#524]
Hi,
Found an issue with resolving the conflicts at least on Windows. 
It can't detect end of functions or and of conflicts and I can't manually add a lines. Or manually fix the result of the merging. 

You can see in screenshot example. It missing the closed brackets in both cases. And I can't add it manually.

![cb0417d](https://user-images.githubusercontent.com/35158142/52815785-2c070b00-3065-11e9-81dd-78e72cc5bb08.PNG)

**Comment by DanPristupov** [comment]
Hi. Fork for Windows has a different tracker. It also has the corresponding issue already: 
https://github.com/ForkIssues/TrackerWin/issues/101
