### ISSUE TITLE
Filter UI forces window width to expand

### ISSUE THREAD

**Issue by mtschoen-unity** [ForkIssues/Tracker#525]
Hello there!

Thanks for all the recent updates you've been doing. It's really helped improve the tool a lot, especially the submodule diff view where I can update submods via GUI. That was pretty much the only thing I needed Terminal for up until now. :)

The latest version displays a nice "Filtered by" UI in the log view, but I encountered an unfortunate side-effect, which is that as the text in this view grows, it forces the window to expand to accomodate. If I filter based on a bunch of branches, I can get a window that extends beyond the edge of the monitor. I have noticed this on Mac OS. Not sure about the Windows version.

My expected fix would be to just truncate the list of branches with a "..." and call it a day 👍

**Comment by DanPristupov** [comment]
Hi. Thank you for the feedback.

I will release a fix for the layout problem today.

FYI: In the next update multi-filter will be available on ⌘-Click on the funnel icon. The usual click will reset the active filter. More details there https://github.com/ForkIssues/Tracker/issues/520

**Comment by DanPristupov** [comment]
The original problem is fixed in 1.0.74. Please check for updates.

**Comment by mtschoen-unity** [comment]
Confirmed
