### ISSUE TITLE
Windows - Let user select location of SSH key (WSL)

### ISSUE THREAD

**Issue by clounie** [ForkIssues/Tracker#528]
For WSL users it would help to be able to specify the location of your SSH key.

On my home windows computer, it's hidden away in a Linux-only directory. If I had the ability to specify an absolute path for the Git key, I could just select the key and be done with it.

**Comment by DanPristupov** [comment]
The Windows version has a separate tracker: 
https://github.com/ForkIssues/TrackerWin

**Comment by clounie** [comment]
New issue - https://github.com/ForkIssues/Tracker/issues/528
