### ISSUE TITLE
GitHub permission scope is too broad

### ISSUE THREAD

**Issue by dgreene-r7** [ForkIssues/Tracker#529]
![image](https://user-images.githubusercontent.com/15327249/52917325-0aea2880-32b8-11e9-8640-26b9abc0c575.png)

`Full control of orgs and teams` is extremely excessive. What exactly is Fork doing that it would require that scope?

**Comment by DanPristupov** [comment]
Fork receives user notifications, manages ssh keys and reads list of user repositories.

**Comment by dgreene-r7** [comment]
Sure, but what of those actions fit into the `admin:org` scope? I'd love to use the GitHub integration in Fork but not at the risk of it being able to make changes to my org.

**Comment by DanPristupov** [comment]
It seems to be unused right now.
Extending permission scope is tricky. I suppose I added this scope in order to be able to create new repos in user account in the future.

**Comment by dgreene-r7** [comment]
Doesn't the `repo` scope allow this already?

**Comment by DanPristupov** [comment]
Not sure.
I'll double check. If 'admin:org' is really not required I'll remote it in the next update.

**Comment by dgreene-r7** [comment]
Terrific! Thanks for looking into this. Mind leaving this issue open and posting in it if/when you confirm?

**Comment by DanPristupov** [comment]
Yes, sure. I always get back to the issues and report the completion.

**Comment by DanPristupov** [comment]
Let me know if you need that ASAP, I can create an early build for you tomorrow.

**Comment by dgreene-r7** [comment]
Not at all. I can use Fork without the GitHub integration until you sort this out. No rush on my part in any way.

Thanks again!

**Comment by DanPristupov** [comment]
I just released 1.0.74.2 hotfix.

**Comment by dgreene-r7** [comment]
Terrific. Thank you so much! I'm going to close this ticket now.
