### ISSUE TITLE
View menu entries are initially disabled (sometimes)

### ISSUE THREAD

**Issue by stk-ableton** [ForkIssues/Tracker#532]
I have one repository where most of the View menu entries are disabled after starting Fork:

<img width="308" alt="screenshot 2019-02-18 at 10 53 09" src="https://user-images.githubusercontent.com/7702697/52942585-8822a580-336b-11e9-9bda-26064ad37e52.png">

If I click on the "Changes" entry in the top left corner, they become functional and stay that way. It only happens in this one repo, all my other ones don't have this problem. I have tried to figure out what's different in this one, but haven't been able to come up with anything yet. Let me know if there are any tests you want me to do.

**Comment by DanPristupov** [comment]
The menu items become enabled when repository view is active. So, it should not be related to a particular repository.

**Comment by stk-ableton** [comment]
You are right, it isn't specific to a certain repository.

It turns out that the keyboard focus was on a toolbar item when this happened. (I have my keyboard preferences set to move keyboard focus between "All controls" when pressing tab, so it's possible for me to put the focus on a button in the toolbar.) Clicking another tab to switch to a different repo moved the focus down to the tab area, and that enabled the menus.

Is there any reason why the menus are disabled when the focus is on the toolbar? An easy way to reproduce this is to put the focus in the search field in the top right corner. I don't see why it shouldn't be possible to hit Command-1 or Command-2 in this situation to switch between changes and all commits.

**Comment by stk-ableton** [comment]
Bump; I'm running into this pretty often (every time I quit and restart Fork), and it is annoying. I'd like to repeat the question why the menu items are disabled when the focus is in the toolbar.

**Comment by DanPristupov** [comment]
> I'd like to repeat the question why the menu items are disabled when the focus is in the toolbar.

The menu actions are bound to the focused repository view. When toolbar is focused, there's no handler for the Repository menu items in the active view hierarchy.

**Comment by stk-ableton** [comment]
Ok, I understand that. However, as a user I wasn't so much interested in the _technical_ explanation of why the code behaves this way, but more whether there are any UX reasons for this behavior. As a user I would expect the menu items to be enabled and to act on the active/visible repository (there can only be one, so there's no ambiguity). After all, the search field in the toolbar also knows which repository to act on, even though it's not focused.

But if that's difficult to implement, another option that would solve the problem for me would be to programmatically set the focus to the repository view at startup (and/or whenever a tab is opened, probably).

**Comment by DanPristupov** [comment]
> However, as a user I wasn't so much interested in the technical explanation of why the code behaves this way, but more whether there are any UX reasons for this behavior.

Ah, OK. Yes, it is (was) a technical problem.

I reworked the whole menu and now it should be working properly.

Thank you for bringing my attention to that bug.

**Comment by DanPristupov** [comment]
I fixed this issue In 1.0.79 (and also introduced some minor bugs https://github.com/ForkIssues/Tracker/issues/642)

**Comment by stk-ableton** [comment]
Awesome, thanks!
