### ISSUE TITLE
Discard changes action very slow on many files

### ISSUE THREAD

**Issue by scratchee** [ForkIssues/Tracker#535]
When you select multiple files and select "Discard Changes...", it can take a very long time. ~100 files can take me about 2 minutes. It does eventually complete successfully.

It looks like each file is discarded with an individual git command, which is fine for 1-10 files, but past that the cost of repeating the process can be excessive.

Experienced on Fork for Mac 1.0.74, and on previous versions too.
My git repo/configuration is almost certainly a contributing factor, it is a particularly large repo and I've avoided most of the costs of this by using a sparse worktree, perhaps one or both of those cause whichever git command you're using under the hood to be unusually expensive. It looks like the git processes that are spawned per file are taking 1-2s each.

Given the performance is acceptable for individual discards, I'm hoping this is relatively easy to fix by combining the discard actions. I suspect this will help with especially large discards even on less extreme git setups.

Here's the most common stack trace in one of the git processes spawned during the process, in case it's helpful:
<img width="242" alt="screenshot 2019-02-20 at 09 57 33" src="https://user-images.githubusercontent.com/6053685/53083103-322e3900-34f6-11e9-97fa-5a3a99ffaaf6.png">
That does suggest that writing the index is the main cause of overhead, which isn't surprising, my repo has a 150MB index file.

Turns out I'd forgotten to enable --split-index, which helps, but only halves the time of each process (bringing the entire ~100 file discard to about 1 minute instead).
The heaviest trace does chang with that enabled:
<img width="267" alt="screenshot 2019-02-20 at 10 17 22" src="https://user-images.githubusercontent.com/6053685/53084533-ef219500-34f8-11e9-9cc8-cf25872ae7cd.png">

So still looks like an index-size related cost. I suspect there isn't much more I can do to speed this up from the git side, without radically changing my repository setup.

**Comment by DanPristupov** [comment]
Are you able to reproduce the same state?

Could you do a measurement with **same** changes in working directory:
* discard all files in Fork
* perform `time git checkout -- .`in terminal

**Comment by scratchee** [comment]
Hi, sorry for slow reply, busy week.

I've tested 3 cases (all discarding the same 118 changes):

```
Fork.app (timed by hand):
1m 25s

$ time git checkout -- .

real	0m0.660s
user	0m0.501s
sys	0m0.227s

$ time ls | xargs -I % git checkout -- ./%
      
real	1m28.172s
user	1m11.635s
sys	0m26.182s
```

(the 3 extra seconds is probably because that folder had a few unchanged files which were unnecessarily receiving checkout commands, whereas fork only discarded changes it had already identified)

But I think this confirms that the issue is running the commands separately.

**Comment by DanPristupov** [comment]
> Hi, sorry for slow reply, busy week.

No worries, same here :).

Thank you for the great feedback. I'll do my best to improve that behavior in the next update.

I think we also need a progress indicator there for a case when discard still takes long.
Ability to cancel can also be helpful.

**Comment by DanPristupov** [comment]
I just released Fork 1.0.75 with the improvement.

**Comment by maksimovic** [comment]
I tested this with discarding changes in over 12k files, and it took around 5 seconds on my MBP.

**Comment by DanPristupov** [comment]
@maksimovic this is a good result I think.

Next I need to update the UI to not get frozen for those 5 seconds ;)

**Comment by scratchee** [comment]
I just repeated my test on the new build and it took less than 1 second to complete.
Thanks for sorting that, and for getting it done so quickly, it's a great improvement 👍
