### ISSUE TITLE
[Feature Request] Open submodule when double clicked

### ISSUE THREAD

**Issue by stvchester** [ForkIssues/Tracker#538]
Double clicking currently opens the submodule in a new tab, but does not change focus to the new tab.  I'd like to see it switch focus to the tab for the submodule.

**Comment by DanPristupov** [comment]
Is that a Mac version issue? If not, the Windows version has a separate issue tracker: https://github.com/ForkIssues/TrackerWin/issues/155

**Comment by stvchester** [comment]
It is for Windows. Sorry didn't realize there were seperate sections.
