### ISSUE TITLE
Mac-OS: Open-in Terminal does not cd into correct directory

### ISSUE THREAD

**Issue by gernotstarke** [ForkIssues/Tracker#539]
when opening a repository in terminal (in my case: iterm2), the terminal opens a shell
on the users' root directory - instead of the repository root.

**Comment by DanPristupov** [comment]
The default Terminal works fine.

Fork just calls `open -a /path/to/terminal /path/to/repository`

Try to reboot the computer.

**Comment by DanPristupov** [comment]
I turned out I have iTerm installed. Everything works properly.

Try to reboot the computer.

**Comment by gernotstarke** [comment]
with:
* MacOS default Terminal, it works fine.
* iterm2 it does NOT work...

**Comment by DanPristupov** [comment]
Did you try the `open` command?
Open macOS terminal, go to your repo and run:
`open -a /Applications/iTerm.app/Contents/MacOS/iTerm2 .`

**Comment by gernotstarke** [comment]
that opens iterm2 in root directory, NOT in correct repository-root...

seems to be an iterm2 issue.

**Comment by DanPristupov** [comment]
Try to reset iTerm settings. Otherwise install a different version.

**Comment by gernotstarke** [comment]
closed, as it is an iterm2 issue.

Thanx Dan for your support.
