### ISSUE TITLE
Error on any git flow command

### ISSUE THREAD

**Issue by jmfederico** [ForkIssues/Tracker#541]
I am using version 1.0.74.2

Running any git-flow command from Fork generates the following errors:

```
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 158: _flags_fatal: command not found
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 1022: [: -ne: unary operator expected
flags:WARN /Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 739: /Applications/Sourcetree.app/Contents/Resources/bin/getopt: No such file or directory
flags:FATAL unable to parse provided options with getopt.
```

Having git-flow locally installed or not does not change anything.

I am not sure what other information can be relevant.

Anything else you need to know, I will provide.

**Comment by jmfederico** [comment]
Invoking `git flow` from the cli works fine.

**Comment by DanPristupov** [comment]
Read the message:
> line 739: /Applications/Sourcetree.app

ST changed your global/system git-flow settings. Remove the source tree path from: ~/.gitflow_export

**Comment by jmfederico** [comment]
You are absolutely right.

Thanks and done!

**Comment by borut-t** [comment]
Thanks, @DanPristupov, this solved my issue too 🎉

**Comment by aholla** [comment]
> Read the message:
> 
> > line 739: /Applications/Sourcetree.app
> 
> ST changed your global/system git-flow settings. Remove the source tree path from: ~/.gitflow_export

How do I do this?

**Comment by DanPristupov** [comment]
Open `.gitflow_export` in any text editor and remove the `export FLAGS_GETOPT_CMD...` line.

You can find a more detailed answer here: https://github.com/fork-dev/Tracker/issues/418#issuecomment-582329014

**Comment by aholla** [comment]
Thanks!!!

**Comment by alexmwalker** [comment]
Excellent advice, fellas. Thanks a heap.

**Comment by WuJunjieGit** [comment]
@DanPristupov Thanks!!! Solved my problem
