### ISSUE TITLE
FR: support vscode as merge tool

### ISSUE THREAD

**Issue by jimblue** [ForkIssues/Tracker#546]
Vscode is very nice free difftool.
Could you add it in the list of the Fork difftool?

Cheers

**Comment by jrocaspana** [comment]
use the following settings:
- Merger: Custom
- Merger Path: path to Code.exe
- Merge tool arguments: `--wait "$MERGED"`
- External diff tool arguments: `--wait --diff "$LOCAL" "$REMOTE"`

**Comment by DanPristupov** [comment]
@jrocaspana the Mac version of Fork doesn't have `custom` tool yet

**Comment by DanPristupov** [comment]
I forgot about that issue. Why don't you just use the 'Open' command in context menu? It does exactly what you want.

**Comment by jimblue** [comment]
Sorry I don't see what you mean... Which open command? It will use vscode as merge tool?

**Comment by DanPristupov** [comment]
When you have a merge conflict, right click on a conflicted file in the file list -> Open With -> VSCode. This should work.

**Comment by jimblue** [comment]
Ok great. But what about adding the custom tool? 😄

**Comment by jimblue** [comment]
Done in last release! 🎉
