### ISSUE TITLE
Almost invisible numbers on selected branch

### ISSUE THREAD

**Issue by zxcat** [ForkIssues/Tracker#547]
Sometimes Fork hides that branch is outdated:
![forkt-clr-bug](https://user-images.githubusercontent.com/550974/53297272-00d2a780-382d-11e9-9f67-2fc805a1bff9.gif)

Fork 1.0.74.2
macOS 10.12.6

**Comment by DanPristupov** [comment]
This problem doesn't exist in macOS 10.14.

<img width="231" alt="image" src="https://user-images.githubusercontent.com/618115/53447862-6df56100-3a16-11e9-8009-edff91a8d2bb.png">

Internally, there are two different dark themes. One for macOS 10.14 and other one for the older systems. It's very tricky for me to support both of them.
