### ISSUE TITLE
When Fork is removed from OAuth apps in Github profile, then it doesn't offer "re-auth"

### ISSUE THREAD

**Issue by maksimovic** [ForkIssues/Tracker#549]
I've removed Fork from my Github account's settings at some point, but now I cannot add it again from Fork - it just complains about bad credentials.

<img width="555" alt="" src="https://user-images.githubusercontent.com/1126226/53477331-c2c7c480-3a74-11e9-965d-f9e30c626132.png">

**Comment by DanPristupov** [comment]
Hi. Open GitHub settings (on the sidebar in RepositoryManager) and signout/sign-in.

**Comment by maksimovic** [comment]
Oh 😭 All good now, thanks!
