### ISSUE TITLE
Auto-expand stashes when adding the first stash (and maybe do the same for nested branches)

### ISSUE THREAD

**Issue by herrherrmann** [ForkIssues/Tracker#55]
Hello there,

whenever I create my first stash, I often end up forgetting about it because the list of stashes in the sidebar seems empty although it's just collapsed. It'd be a neat little UI detail if this list would expand automatically as soon as there are stashes available in order to keep an eye on what's available. It's just a tiny thing but it would help me and most probably other developers, too!

P.S.: A similar behavior could make sense for branches and nested branches. Example: I create a new release branch via gitflow but the `releases` branches are all collapsed and I can only access a nested release branch (like `releases/1.0.4`) after expanding the parent branch.

**Comment by DanPristupov** [comment]
That's a good idea. I will make ensure that the target item is visible after actions with stashes/branches/tags.
If item is collapsed -> expand parents.
If item is out of sidebar view port -> scroll the sidebar, so the item is visible.

**Comment by DanPristupov** [comment]
I made stashes to be expanded on start by default. I think that's what everybody needs.
