### ISSUE TITLE
[Bug] It is not possible to dsicard a deleted line

### ISSUE THREAD

**Issue by DominikPalo** [ForkIssues/Tracker#550]
When I select a deleted line and click on the "Discard..." button nothing happens. I would expect that the line will be "restored".
<img width="649" alt="fork-discard" src="https://user-images.githubusercontent.com/1623257/53480873-58b31d80-3a7c-11e9-9ae3-14295d916347.png">

Version: Fork 1.0.74.2 (macOS)

**Comment by DanPristupov** [comment]
I don't see selection on your screenshot. It looks like you selected '\n'. Try to select at least one symbol.

Does stage work?
Do you use `ignore-whitespaces` diff mode?

**Comment by DominikPalo** [comment]
@DanPristupov on the screenshot in the first post I have selected the entire line (with a double-click).

But today I've encountered a similar case - I want to unstage an empty new line and it is not possible:
Steps to replicate:
1) Double-click on an empty line
2) Click the "Unstage" button
3) Nothing happens

Video: https://gyazo.com/c2eb690af3fc6e3df29b0d5be356d028
