### ISSUE TITLE
“View on”? On what?

### ISSUE THREAD

**Issue by marcomasser** [ForkIssues/Tracker#551]
I have a repository checked out on my computer and the only remote is a server on the LAN. In the menu bar, there’s a button that offers three options:

<img width="216" alt="screen shot 2019-02-27 at 15 45 28" src="https://user-images.githubusercontent.com/624299/53498490-b8262300-3aa6-11e9-9c7b-5e5ca0d34487.png">

The third option doesn’t do anything. I assume that is intended for repositories that are hosted on a service like GitHub? For other repositories, this should probably be removed.

**Comment by lxnk** [comment]
I get this option when the remote is on local GitLab server. Also does nothing.
