### ISSUE TITLE
Additional lines of commit message are in monospace font after showing an emoji

### ISSUE THREAD

**Issue by marcomasser** [ForkIssues/Tracker#552]
If a line of a commit message that is not the first line starts with an emoji, the text field for that part of the message switches to a monospaced font.

![emoji bug](https://user-images.githubusercontent.com/624299/53500202-31734500-3aaa-11e9-8dd9-7275f581fb73.gif)

I’ve seen such issues before. In those cases it was always that the `NSAttributedString` that is used to render the text has the private, internal font for emoji rendering set. I suspect that this could be the case here. Maybe the emoji’s font hangs around for the whole of the text field when the string is replaced. Setting the font explicitly should fix this.

**Comment by DanPristupov** [comment]
Thank you for the bug report 👍
This might also be related to another issue: https://github.com/ForkIssues/Tracker/issues/504

**Comment by marcomasser** [comment]
Oh, I wanted to mention that I think it might be related to #504 but forgot to include it 🤦‍♂️

**Comment by DanPristupov** [comment]
Fixed in 1.0.75
