### ISSUE TITLE
[Bug] Duplicate branches when finishing release in Git Flow

### ISSUE THREAD

**Issue by nclandrei** [ForkIssues/Tracker#555]
When trying to finish a release branch in Git Flow, the release branches dropdown contains the one the user wants to finish twice.

Screenshot: 
<img width="1680" alt="screen shot 2019-02-28 at 12 26 05" src="https://user-images.githubusercontent.com/5888783/53563481-705dd500-3b54-11e9-8ff0-0166e703f1ca.png">

If I click on any of them, it correctly finishes the release. However, the problem is that it shows it twice, even though there is only one.

**Comment by nclandrei** [comment]
By the way - thanks for this amazing app and keep up the great work!

**Comment by DanPristupov** [comment]
Fixed in 1.0.76. Thank you!
