### ISSUE TITLE
Can't start Git Flow release: why sourcetree getopt not found ?

### ISSUE THREAD

**Issue by git4coder** [ForkIssues/Tracker#557]
mac v1.0.74.2
develop branch -> right click -> Git Flow -> Start Release ... ->DIALOG: release/[v4.0.0] +  Start at [develop] -> Start Release button:
Error Details:
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 158: _flags_fatal: command not found
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 1022: [: -ne: unary operator expected
flags:WARN /Applications/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 739: /Applications/Sourcetree.app/Contents/Resources/bin/getopt: No such file or directory
flags:FATAL unable to parse provided options with getopt.

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/Tracker/issues/541
