### ISSUE TITLE
Interactive rebase quits in progress, does rebase without applying changes

### ISSUE THREAD

**Issue by vadsiraly** [ForkIssues/Tracker#559]
We are trying to rebase a ~100 commit branch to master, during interactive rebase, after a few minutes the dialog just closes by itself, and the rebase is done (there were no conflicts, we rebased multiple times in the past, using the traditional rebase featue), and none of the changes we set in the interactive rebase window are applied.

We are using the Windows client version 1.29.1.0.

**Comment by DanPristupov** [comment]
The Windows version has a different issue tracker: 
https://github.com/ForkIssues/TrackerWin

**Comment by vadsiraly** [comment]
Ah, my bad, sorry.
