### ISSUE TITLE
'Commit and Push' cannot be triggered with ⌥⌘⮐

### ISSUE THREAD

**Issue by marcomasser** [ForkIssues/Tracker#561]
While writing a commit message and holding down the Option key, the “Commit x Files” button changes to “Commit x Files and Push” and it retains its visual indication that it is the default button. This leads me to expect that it can be triggered using the Return key, but that doesn’t actually work. Instead, Option-Return enters a newline (which is the default in macOS for that combination) in the commit message field.

**Comment by DanPristupov** [comment]
The `Commit` button is triggered with <kbd>⌘</kbd><kbd>Return</kbd>.
So, most probably the `Commit and Push` combination should be <kbd>⌥</kbd><kbd>⌘</kbd><kbd>Return</kbd>.

**Comment by marcomasser** [comment]
Ah, yes, that makes sense, of course. But that combination doesn’t do anything.

**Comment by DanPristupov** [comment]
OK, I'll try to implement that in the next update.

**Comment by DanPristupov** [comment]
1.0.75 just out, please check for updates.

**Comment by SamuelSchepp** [comment]
Works perfectly now. Thank you.
