### ISSUE TITLE
Sort remotes alphabetically

### ISSUE THREAD

**Issue by infotexture** [ForkIssues/Tracker#564]
It's great that we can sort tags in v1.0.74 after the changes for #213.

Would it be possible to apply the same approach to remotes?

Currently, right-clicking the **Remotes** item in the sidebar shows the **Sort Branches** option in  context menu, but no corresponding option for remotes as [commented](https://github.com/ForkIssues/Tracker/issues/213#issuecomment-365073082) in the original feature request.

**Comment by DanPristupov** [comment]
You can sort remote branches in the same way as tags.
<img width="315" alt="image" src="https://user-images.githubusercontent.com/618115/53916166-bf7a9d00-4061-11e9-881f-d5235933b0ff.png">

Or do you want to sort the server list? If so, it would be tricky I think.

**Comment by infotexture** [comment]
Yes, sorry that was unclear. I was suggesting an option to sort the remote server list alphabetically by server name.

I'm aware that I can edit the `.git/config` file to change the order of these entries (and I see that Fork respects the revised order when I do), just thought it would be convenient to do this in the UI.

**Comment by DanPristupov** [comment]
I think we should always sort them alphabetically.
