### ISSUE TITLE
Commit button sometimes disabled after failed commit

### ISSUE THREAD

**Issue by marcomasser** [ForkIssues/Tracker#565]
When committing fails at the Git level (like in the attached GIF – sorry for the black bars – where I entered an incorrect PIN for the hardware authentication device that stores the private key for signing the commits using GPG), Fork shows a window-modal sheet with Git’s error output. Closing that sheet returns the UI to the usual state, but the commit button is disabled.

![disabled commit button copy](https://user-images.githubusercontent.com/624299/53945939-0351be80-40c3-11e9-862c-907fcc1fd937.gif)

There doesn’t seem to be a way to re-enable it except changing the whole view, e.g. clicking “All Commits” in the left sidebar and then back again.

**Comment by DanPristupov** [comment]
Thank you for reporting that. I've reproduced the problem.

**Comment by marcomasser** [comment]
Man, you’re fast! 🏎

**Comment by DanPristupov** [comment]
Fixed in 1.0.75
