### ISSUE TITLE
Add keyboard shortcut to select current HEAD

### ISSUE THREAD

**Issue by marcomasser** [ForkIssues/Tracker#566]
In the _View_ menu, there’s already:

    Show Uncommitted Changes   ⌘1
    Show All Commits           ⌘2

I’d suggest adding right below that:

    Show Current HEAD          ⌘3

… which would do the same as clicking the current HEAD in the left sidebar.

**Comment by DanPristupov** [comment]
What if I add a third view in the future? Would you expect me to shift the "Short HEAD" shortcut to ⌘4?

**Comment by marcomasser** [comment]
Yes. Just the same as I’d expect the ⌘1 or ⌘2 shortcuts to change when that new view is listed above or between the respective views.

An alternative would be to use ⌘0, which also has precedent in macOS apps. For example, Mail uses dynamic shortcuts using ⌘ and a number for the various mailboxes you can drag into a bar below the toolbar, but ⌘0 always selects the message viewer.

**Comment by DanPristupov** [comment]
Available in 1.0.75
