### ISSUE TITLE
Side by side diff view is hidden when switching back from another app

### ISSUE THREAD

**Issue by ravinggenius** [ForkIssues/Tracker#568]
Steps to reproduce:

1. Open any side-by-side diff
2. Switch to another application, but leave diff open
3. Switch back to Fork
4. Notice diff view is now behind main Fork window

Pressing `[space]` will still close the diff view, so a work-around is to simply hit `[space]` twice.

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/Tracker/issues/290

**Comment by ravinggenius** [comment]
Sorry about the duplicate! I searched, but didn't find it.

**Comment by DanPristupov** [comment]
No problem.

This issue bothers me too, but I couldn't find a solution yet.
