### ISSUE TITLE
Allow other key commands for stage/unstage

### ISSUE THREAD

**Issue by mergesort** [ForkIssues/Tracker#57]
The new change to allow side by side diffs seems like a good one (though not one I personally use), but using `spacebar` for the key command seems confusing. All other git clients in my testing seem to use `spacebar` for staging and unstaging, and having to remember different key commands to move between the two areas (`⌘ + ⇪ + s` and `⌘ + ⇪ + u`) makes it very difficult to stage/unstage in practice.

Personally I would prefer the change be reverted, but also would make a case moving the commands into the menu bar, so the key commands could be customized to our liking.

Thanks a lot!

**Comment by DanPristupov** [comment]
Hi Joe,
The stage/unstage will be handled by Enter in the next Fork update (going to release it tomorrow). More details in this issue: https://github.com/ForkIssues/Tracker/issues/54.

Sorry for the inconvenience. I received a bunch of emails asking me to return the spacebar shortcut. However everybody agreed that Enter replacement is good enough.

Do you think Enter will work for you?

**Comment by mergesort** [comment]
I prefer spacebar, but enter will definitely suffice. As long as it's consistent, I don't really mind. 🙂

**Comment by DanPristupov** [comment]
Just released Fork 1.0.51 with the following mapping:

Stage/Unstage: `Cmd+Shift+S` or `Enter`
Unstage: `Cmd+Shift+U` (for backward compatibility)
Discard: `Cmd+Shift+D` or `Backspace`

**Comment by mergesort** [comment]
Thanks!

**Comment by mergesort** [comment]
After using this today, I'd love to re-up the idea to be able to remap the staging key.

I realized that a big part of my flow is pressing spacebar with one hand, and using the other to go up and down between files. This is a lot harder to do since the enter key and the up/down arrow keys are used by the same hand.

Just to show that I'm not completely tone-deaf, I completely acknowledge that I sound like this.

![](https://imgs.xkcd.com/comics/workflow_2x.png)

**Comment by clounie** [comment]
Perhaps that's a more general "re-map keyboard shortcuts" ticket?

**Comment by DanPristupov** [comment]
OK, let me try to explain myself. I'm tending to implement Fork in a way it helps people to make better commits.

In my opinion
- the `spacebar` key represents impulsive and spontaneous action.
- the `enter` key is a consistent action.

That's the thing. I deliberately want to make a review to be spontaneous and stage - consistent. Not the opposite.

So, I know that `enter` is less accessible than the `spacebar` and this is intentional.

I'd like to take a month pause and have a fresh look at the experience.

**Comment by mergesort** [comment]
Ok. My hypothesis is that my opinion won't change, since I usually do my thinking ahead of time before getting to the staging screen, but I'll be fair to give it a shot. I might be back in a month. 🙂
