### ISSUE TITLE
"Page guide at column" is ignored

### ISSUE THREAD

**Issue by ravinggenius** [ForkIssues/Tracker#570]
I have the column guide option enabled, but it appears to be ignored.

<img width="323" alt="Screen Shot 2019-03-10 at 11 56 56" src="https://user-images.githubusercontent.com/21517/54087676-a4db4900-432b-11e9-8d9c-21e0820c1e95.png" />

<img width="918" alt="Screen Shot 2019-03-10 at 11 58 22" src="https://user-images.githubusercontent.com/21517/54087694-d9e79b80-432b-11e9-9ce7-ebc68e3c837a.png" />

**Comment by DanPristupov** [comment]
It might be too dark, but I do see it on your screenshot.

**Comment by ravinggenius** [comment]
Wait is the column guide the number off to the side? I was expecting to see a vertical line.

What about the message body area? A vertical line there would be even more useful.

**Comment by maksimovic** [comment]
It's the "dashed" vertical line, but it's light gray on dark gray so it's not easy to spot.

From Dan's example:
<img width="630" alt="54112637-ed0b7180-43e6-11e9-9110-0e5e9bd75d78" src="https://user-images.githubusercontent.com/1126226/54340463-b5dfcf00-4637-11e9-8947-defa2273c609.png">

And in your own screenshot:
<img width="918" alt="54087694-d9e79b80-432b-11e9-9ce7-ebc68e3c837a" src="https://user-images.githubusercontent.com/1126226/54340430-a2346880-4637-11e9-8746-e51365feb5ae.png">

The images are scaled down in comments, you might want to right-click and "view image" to see the full size.

**Comment by ravinggenius** [comment]
Okay I can see it in the screenshots when I blow them up, but not in the app. I noticed the counter contrast in the subject line increases as you type, so maybe the message body line could do the same? If that isn't possible please just increase the contrast. I honestly can't see it.
