### ISSUE TITLE
Too many domain names

### ISSUE THREAD

**Issue by ravinggenius** [ForkIssues/Tracker#571]
The Fork website has at least three domain names, each of which is pointing to (what appears to be) a separate instances of the website. I haven't done an exhaustive comparison of each page, but they all appear to serve the same information. If that is the case, please consider nominating one domain as canonical, and redirecting the others (while preserving whatever path was entered).

* https://fork.dev/
* https://forkapp.io/
* https://git-fork.com/

**Comment by DanPristupov** [comment]
I just registered fork.dev last week. We will migrate every link to it one day.

All three names point to the same server.
