### ISSUE TITLE
JIRA bug-tracker sample produces wrong link

### ISSUE THREAD

**Issue by haaanz** [ForkIssues/Tracker#577]
link to JIRA are highlighted but link is wrong

**Steps to reproduce**

- add sample JIRA rule
- use test message PROJ-28 Fix documentation of the build process 

link is https://jira.yourcompany.com/browse/PROJ-$2
and it should be https://jira.yourcompany.com/browse/PROJ-28

**Comment by Tunous** [comment]
I've encountered the same issue and fixed it by using `$1` instead of `$2` in settings.

**Comment by haaanz** [comment]
thanks, it work!
So just the sample 'Result Url' field has wrong predefined value.

**Comment by DanPristupov** [comment]
Good catch! I've changed the sample rules a lot of times and finally made a mistake.

**Comment by DanPristupov** [comment]
I've just released the 1.0.75.1 hotfix (it will not bother people who already updated to 1.0.75).
