### ISSUE TITLE
MacOS Split-View Not Respected/Preserved

### ISSUE THREAD

**Issue by EBGToo** [ForkIssues/Tracker#578]
Hi.  Great GIT tool.

I use MacOS Split View to show Xcode on the left and Fork on the right in a full screen window.  When I swap monitors (working at home on an external monitor; disconnect; move to work; connect an external monitor at work), Fork 'forgets' about the Split View setup.  Result is that I get two full screen windows - one with Xcode, one with Fork; instead of one window with Xcode+Fork.

This doesn't happen w/ other Apps in Split View w/ Xcode; thus I've concluded that it is something in the Fork code.

**Comment by DanPristupov** [comment]
Not sure if I will be able to test this. The new MBP doesn't have an HDMI port anymore.

**Comment by EBGToo** [comment]
My setup is a USB-C to mDP cable to a 4K monitor.

**Comment by EBGToo** [comment]
Using an external monitor, set up a Space with a Split View - say Xcode + Fork.  Disconnect the monitor, wait a bit (few seconds), reconnect the monitor - the split view has disappeared; you'll have two full screen views.  Try it with Xcode+Safari; on reconnect they will still be in a Split View.

Cheers!

**Comment by EBGToo** [comment]
This is an issue of 'minimum window' sizes.  Something like the sum of 'Xcode minimum' + 'Fork minimum' > screen size.  https://discussions.apple.com/thread/7250923
