### ISSUE TITLE
Problem with buttons when deleting not merged branch with long name

### ISSUE THREAD

**Issue by browakles** [ForkIssues/Tracker#580]
<img width="436" alt="Zrzut ekranu 2019-03-20 o 18 28 22" src="https://user-images.githubusercontent.com/4276118/54706358-02973e80-4b3f-11e9-8118-5460b8e83d2d.png">

When deleting not merged branch and it's name is too long, buttons are covered by label and it's impossible to click any of them.

**Comment by DanPristupov** [comment]
Fixed in 1.0.76
