### ISSUE TITLE
Manage different identities

### ISSUE THREAD

**Issue by btxtiger** [ForkIssues/Tracker#583]
I noticed some confusing behavior while configuring the git identity.

When configuring a name, that matches some part of the email adress, the commits will be applied as "John Doe".

![image](https://user-images.githubusercontent.com/15804690/55010343-5513a780-4fe4-11e9-8fc5-5ad0de92019a.png)

E.g.

Name: jackson
Email: jackson@email.com

Is this some "hidden feature" of Fork or do you think there is something wrong with my git config? I didn't find some indications yet.

Independently, I have a feature request:
I would be so helpful to be able to quickly switch between different identities, in order to be able to manage different projects (e.g. I am not using the same identity on github, as I would use in my company).

**Comment by DanPristupov** [comment]
>  I didn't find some indications yet.
Kraken?

**Comment by btxtiger** [comment]
I'm also using GitKraken, but also there isn't configured "John Doe" anywhere.
When disabling global git credentials for the repository, the commits are applied as expected.

**Comment by DanPristupov** [comment]
I believe you registered in Kraken with a fake email and a fake name, and it changes the global git settings every time you run it.

**Comment by btxtiger** [comment]
Hmm, not really. I'm using my regular gitkraken account. I'll try do some research on this behaviour, and add some details here if I find something. 
Issue can be closed, thanks.

**Comment by DanPristupov** [comment]
From time to time I receive similar reports which always end up like I described :).

I did check the source code to be sure, and I couldn't find any "John Doe" occurrence.
