### ISSUE TITLE
Merge ForkIssues/TrackerWin into ForkIssues/Tracker

### ISSUE THREAD

**Issue by mloskot** [ForkIssues/Tracker#585]
This is proposal to combine this tracker and https://github.com/ForkIssues/TrackerWin into one, and introduce label or `[win]` tag in subject to distinguish Windows-specific issues.

Currently, it is unclear when to report a generic Git issues observed in the Fork.
* If I use Fork for Windows, should I always considere issues Windows-specific?
* When do I know when to report issues to general Tracker and whn to TrackerWin?

**Comment by DanPristupov** [comment]
The applications are separate and don't share any code.

> If I use Fork for Windows, should I always consider issues Windows-specific?

Yes

> When do I know when to report issues to general Tracker and when to TrackerWin?

Tracker is for Mac, TrackerWin is for Windows.

**Comment by mloskot** [comment]
I see. I thought that Fork is the core + Mac UI and Fork for Windows is just the Windows UI, so they share implementation of the core functionality. Hence, I was confused where to report 'core' problems or ideas.
