### ISSUE TITLE
[Feature Request] Keyboard shortcuts to recent commit message

### ISSUE THREAD

**Issue by michael-letcher** [ForkIssues/Tracker#587]
Sourcetree allows you to reuse previous commit messages with Alt+Up then you can select from the drop down.

_I'm new to Fork but I'm already loving it, having had enough of Sourcetree crashing everyday. Thank you for this awesome app!_

**Comment by DanPristupov** [comment]
The shortcut is just `up/down`

**Comment by michael-letcher** [comment]
@DanPristupov Haha, I cannot believe I did not try that. Thanks!
