### ISSUE TITLE
Bug: Save commit range as patch not working

### ISSUE THREAD

**Issue by hohwille** [ForkIssues/Tracker#594]
In Fork 1.0.76 on MacOS I select two distinct commits and right click to choose `Save commit range as patch...`. Next I twice click on `Save`. Then I get this error:
![Screenshot 2019-04-08 at 12 11 31](https://user-images.githubusercontent.com/1923119/55716560-90a46d80-59f7-11e9-97c2-7ef2d28ea178.png)

```
fatal: ambiguous argument '9f80029b4a84b555c1341d0fb326ebe095f9157f~..0cd9306f303e57729abedc2cb8b7fb2b7d7ae598': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by DanPristupov** [comment]
Did you select the initial repository commit maybe?
