### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by yonaskolb** [ForkIssues/Tracker#597]
Hello

First of all, thank you so much for the fantastic tool! I've tried many git GUIs over the years, but this one is quickly becoming my favourite.

I've been using the macOS app for a couple of weeks now. I wanted to get some real usage out of it first and have been collecting my thoughts to post here. As some of these may have been discussed already, I'd thought I'd just list them here and if they have merit I can open some specific issues. Apologies in advance for the length of what follows 😄

In no particular order here is a list of small and larger feature requests:

### 1. Easier staging of individual lines
At the moment it's possible to hover over chunks to stage them individually. It's also possible to select certain lines within the content but this could be improved. It would be nice if:
- the line numbers were drag-selectable. This includes changing the cursor. At the moment the cursor over the line numbers is sometimes a text selection bar and some times a pointer. Dragging over the text is not obvious as that is typically reserved for simple text selection as the cursor suggests.
- it was clearer which lines are selected. The current blue highlight is very subtle when on top of green lines. If the line numbers look selected as well this would do the job
- pressing enter would stage/unstage the selected lines

### 2. Offer to force push
If a push fails because your branch is out of date it would be great if there was a dialog that offered to force push the branch. It's possible to leave the force push option selected in the push window, but this is dangerous as usually you don't want to accidentally force push your changes on top of others work. This way you can easily choose to force push on a case by case basis when rebasing your own changes. It also plays nicer with quick push (holding ALT)

### 3. Multi-select changed files
When viewing a commit in the `Changes` tab, it would be nice to multi-select files and then see all file changes vertically one after another in the right pane instead of just a single file. This also enables a nice workflow of pressing CMD-A and then scrolling through all the changes. I know the `Commit` tab has an `Expand All` button, but this seems easier to use.

### 4. Single commit rebase actions
The interactive rebase UI is a fantastic part of Git Fork! But sometimes you just want to modify a single commit without going through a whole interactive rebase. It would be great if you could right-click on a commit and select some rebasing actions that would then be applied automatically by rebasing on the commit's parent. These could possibly live under a single `Rebase actions` subheading. The actions would be:

- Move up
- Move down
- Fixup
- Squash
- Drop
- Reword (would show a text entry field)
- Edit (this would be a bit tricker, but interactive rebase already handles it)

These could possibly have shortcuts but not sure what they would be without conflicting too much. Perhaps the shortcuts used in the interactive rebase window could be reused somehow with a modifier.

### 5. Run custom actions via keyboard
Would be nice to be able to run custom actions via the keyboard. They could be given custom keyboard shortcuts but I think a better way would be a single shortcut that allows you to search through them and then pressing enter, similar to the open quickly dialog that is shown with CMD-O. They could possibly live within open quickly or else in their own searchable window.

### 6. Split commit
The rebasing is powerful but has its limits. One use case that is tricky without moving commits around and amending is the ability to split commits. You could right-click on a commit and hit `Split` which would show a staging view with all the changes in that commit. Anything staged would go into a new commit with a custom name.

### 7. Multi-file selection behaviour when staging
At the moment if you multi-select files in the staging area the right pane is empty and just shows the GitFork logo. This seems like a missed opportunity. There could either be large buttons to stage/unstage OR better yet it showed all the diffs vertically similar to **Multi-select changed files** above

### 8. Multiple file quicklook
When files are selected in commit details or in the staging area you can press SPACE to view the diff in a fullscreen side by side. Similar to **Multi-select changed files** and **Multi-file selection behaviour when staging** above it would be nice to be able to show diffs for multiple files vertically if multiple are selected when you press space.

### 9. Ordered repository actions
At the moment the order of custom repository actions in the `repository` menu and the `share` sheet seems to be random. These could be sorted alphabetically but better yet have them be able to be sortable in the custom actions window in preferences by dragging them.

### 10. Drag from/to remote branches
At the moment you can drag local branches onto each other which offers to rebase or merge. It would be great to be able to do this on remote branches, so you could, for example, drag a local branch onto a remote branch to rebase off of it. This saves you from checking out and keeping a local branch updated just so you can rebase off it.

### 11. Quick Fetch and Pull
Pushing has an ALT modifier that skips the dialog. Would be nice to have the same for the fetch and pull keyboard shortcuts. The same goes for holding alt and clicking on the toolbar icons

### 12. Custom action commands
Maybe this is more of a question that a request, but I can't seem to figure out how to create a custom action that calls a command that isn't a git command without placing it in an external script. For example, I might want to run the following command (for a poor man's way of fixing up a commit)
```
GIT_SEQUENCE_EDITOR="sed -i -re 's/^pick $sha/fixup $sha /'" git rebase -i $sha ~2
```
But what do I put in the script path? If I put:
- nothing, I get an error saying `Launch path is not executable ''`
- `/bin/bash` I get an error `/bin/bash: GIT_SEQUENCE_EDITOR="sed: No such file or directory` 

It seems it would be easier if a custom action could either run from a script or you could just specify the whole command without splitting the `$git` path into a separate field. In other words, be able to run executables without knowing their full path.

---
So there you have it! Thanks for reading all of that. Apologies if anything has been brought up before or I've misunderstood something or just not found a given feature. I'm not expecting any of this to be implemented but just wanted to have my thoughts known. I'll probably come across some other things as I use Git Fork more. Thanks again for creating it!

**Comment by DanPristupov** [comment]
This is a great feedback 👍 (even though it doesn't really fit into the bugtracker format).

Majority of your points make sense, but I a some time to think to answer you properly.

**Comment by DanPristupov** [comment]
> 4. Single commit rebase actions

In 1.0.78 we introduced quick actions for IR.
<img width="672" alt="image" src="https://user-images.githubusercontent.com/618115/58860336-2bde5a00-86ac-11e9-8e0e-588e0d5ef425.png">

**Comment by yonaskolb** [comment]
@DanPristupov yeah I saw that, nice one! Thank you! 😄 

Small additions to that feature that would be cool are:
- adding a move up and move down
- as they are "quick" actions not evening opening the interactive dialog. (Though obviously `Reword message` needs some input). If you wanted to keep the dialog, perhaps it might skip it when holding ALT, like the quick push
- potential keyboard shortcut support, though I don't have good suggestions for these

Do you have any comments on the other items? (I know there's a lot there)

**Comment by DanPristupov** [comment]
OK, I'll try :)

Generally speaking I agree with most of them and they are in todo list, however some ones require a lot of work.


> 1. Easier staging of individual lines

> the line numbers were drag-selectable. 

This is in my todo list with a low priority. In every text editor you usually select the text and perform the action.

For example:

Bold: select text -> press [B]
Cut: select text -> cut

etc,
Why should staging behave differently?

Stage: select -> stage

> The current blue highlight is very subtle when on top of green lines. 

I improved chunk highlighting in 1.0.79

> pressing enter would stage/unstage the selected lines

This is planned for 1.0.80.

> 2. Offer to force push

Not sure about that one. Yes, quite often we need to force push and it **is** save (for example amend or rebase of feature branch).

However force push could be dangerous and dangerous actions should not be easy to make.

I'd like Fork to not create situations like the following:

- a git newbie came to a new company and was asked to push his/her changes to master
- everything seemed to be in sync, but some other developer managed to make other push last second (happens every time)
- push dialog showed error and proposed two options: Force Push and Close. Not a wide choise for a newbie :).
- pressed Force Push and got the worse day in his/her life.

Currently force push intentionally takes some time when user can realize what he's doing.

> 3. Multi-select changed files
> 7. Multi-file selection behaviour when staging
> 8. Multiple file quicklook

https://github.com/ForkIssues/Tracker/issues/261
This is quick difficult and requires very big changes. I think there are more important things at the time (like side by side diff mode).

> 5. Run custom actions via keyboard

I didn't have a time for that yet.
There's a trick for though: https://github.com/ForkIssues/Tracker/issues/438#issuecomment-497623866

> 6. Split commit

Good idea.

> 9. Ordered repository actions

I'm planning to rework all Custom Actions in the future and this issue should be part of it.

> 10. Drag from/to remote branches

I'll check that. However in your case (`This saves you from checking out and keeping a local branch updated just so you can rebase off it) you can just make fast forward pull, which allows to make branch up-to-date without checkout.

> 11. Quick Fetch and Pull

In todo list.

> 12. Custom action commands

This is tricky. Fork is not a real bash shell with pipes, it just runs the external process. I think creating an `.sh` script is the correct way.
