### ISSUE TITLE
Viewing tall image breaks layout

### ISSUE THREAD

**Issue by mtschoen-unity** [ForkIssues/Tracker#598]
Hi there. I found a bug :)

If you have a particularly tall image (This one was only 1024px tall, but ymmv) in the diff view, it can force Fork to have a minimum height that is taller than the screen. The window stays constrained, but the inner UI pokes up above the top of the window and is inaccessible. I can provide a screenshot if you want, but just add a tall, skinny image to your project and try to view it, and you should reproduce the issue. Here is the image that breaks things for me:
![image](https://user-images.githubusercontent.com/19391263/56449096-50cc6880-62ca-11e9-942c-fc7883803a00.png)

**Comment by DanPristupov** [comment]
Fixed in 1.0.81. Sorry for the delay. I didn't consider the problem as serious until I saw it myself :).
