### ISSUE TITLE
Fork 1.0.77 / MacOS Mojave Repository Status in toolbar clips overflow

### ISSUE THREAD

**Issue by js3692** [ForkIssues/Tracker#601]
Recently upgraded to 1.0.77 on my MacOS Mojave. Really love using Fork, btw!

Is there a way to let the "Repository Status" component grow out if there's space left? It also currently clips any overflow awkwardly (clipping is fine but perhaps something like an ellipsis could make it look better):

<img width="1440" alt="Screen Shot 2019-04-24 at 10 10 53 AM" src="https://user-images.githubusercontent.com/14022304/56666095-479c1c80-6679-11e9-8a13-961333f19b1a.png">

**Comment by DanPristupov** [comment]
Thank you for the bug report. This is a pretty long one :).
I'll improve that in the next update.

**Comment by DanPristupov** [comment]
Fixed in 1.0.78.

**Comment by js3692** [comment]
Awesome - thank you! Not sure what the protocol is for this repo, but closing since it's fixed.
