### ISSUE TITLE
menu bar disappeared?

### ISSUE THREAD

**Issue by StefanoCecere** [ForkIssues/Tracker#602]
macos 1.0.77 on Mojave 10.14.4
i don't see the menu bar icon anymore.. and no way to enable it...

**Comment by DanPristupov** [comment]
What is menu bar icon? Can you show a screenshot?

**Comment by DanPristupov** [comment]
Do you mean the notification icon near the clock in the system menu?

**Comment by StefanoCecere** [comment]
> Do you mean the notification icon near the clock in the system menu?

yes! was it removed in latest updates?

**Comment by StefanoCecere** [comment]
ahhh solved!
it was under the GitHub accoutn settings... sorry!

**Comment by DanPristupov** [comment]
Phew :)
