### ISSUE TITLE
Toolbar button misaligned on a non-retina screen in 1.0.77

### ISSUE THREAD

**Issue by homm** [ForkIssues/Tracker#605]
1:1

![Screenshot 2019-04-26 at 14 30 03](https://user-images.githubusercontent.com/128982/56805145-c091a480-6830-11e9-8263-c78a4869ac9c.png)

Zoom:

![Screenshot 2019-04-26 at 14 31 04](https://user-images.githubusercontent.com/128982/56805155-c8e9df80-6830-11e9-9311-f643b7e5ce25.png)

**Comment by kitgrose** [comment]
For the record, this is still an issue as of v1.0.79.4.

**Comment by DanPristupov** [comment]
On retina everything is correct (I checked the pixels). I don't have an ability to reproduce that, so have no idea how to fix unfortunately.

**Comment by wachilt** [comment]
Confirmed on a non-retina 2017 MacBook Air.
Looks like it's just the Stash icon that requires adjusting though.

**Comment by kitgrose** [comment]
You could try [opening Fork in low-resolution mode](https://apple.stackexchange.com/a/177096/19112)?

**Comment by DanPristupov** [comment]
@kitgrose good idea. It worked.

**Comment by DanPristupov** [comment]
Fixed in 1.0.80. Please check for updates.

**Comment by wachilt** [comment]
Thank you, Dan. :)

**Comment by homm** [comment]
Thanks!
