### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by willsilvano** [ForkIssues/Tracker#607]
Hi, there are plans to release a linux version?
I tried to install through Wine but it dit not work. :(
I really love this client for git.

**Comment by DanPristupov** [comment]
Hi.
No. You can find more details here: https://github.com/ForkIssues/Tracker/issues/153

> I tried to install through Wine but it dit not work. :(

Fork for Windows uses WPF which is not supported by Wine.

**Comment by ListeningGarden** [comment]
Would love to see Fork eventually make its way to Linux. I am moving away from Windows more and more, and we are hurting for good options for GUI oriented Git clients there! Fork has been a joy to use, so I'm not looking forward to losing it when I eventually phase out Windows usage for my dev environment.
