### ISSUE TITLE
No merge tool option during rebase

### ISSUE THREAD

**Issue by lirao** [ForkIssues/Tracker#608]
Mac version 1.0.77

I just installed this because Sourcetree integration with merge tool stopped working, but it looks like I can't even merge here? 
Installed Fork because the integrated merge tool looks like exactly what I needed, but looks like there's something wrong here.
<img width="547" alt="Screen Shot 2019-05-01 at 2 36 15 PM" src="https://user-images.githubusercontent.com/6883412/57044170-7dfc0d80-6c1e-11e9-9c01-22891130ff2c.png">

**Comment by DanPristupov** [comment]
> I can't even merge here?

That's is correct. There's nothing to merge because the file was **removed** in master and **modified** in your branch. You can either keep the modified one or remove the file.

**Comment by calvintam236** [comment]
I think @lirao's idea is to able to select which part of chuck to be stay, something like commit with diff?

**Comment by DanPristupov** [comment]
This is a boolean question. The file **either** exists or not. There's nothing to 'merge'. We cannot merge `string` and `null`.

> to able to select which part of chuck to be stay

Looks like you want the file to exist, then you need to select the `modified` case. You can edit the file afterwards if you want, but it's not related to the merge conflict.
