### ISSUE TITLE
[MAC] Git error on interaction with repository

### ISSUE THREAD

**Issue by broql** [ForkIssues/Tracker#610]
I've just updated Fork client and got this error every time i try to interact with repository (pull/push etc.). My passwords, keys are fine.

dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /Applications/Fork.app/Contents/Resources/fork_askpasswd
  Reason: image not found
git@stash.intranet.com: Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

In a case you entered incorrect password, please
update it in Keychain Access application.

**Comment by DanPristupov** [comment]
What is your Fork version?
1.0.78.1. should show a special dialog with details on this error.

**Comment by broql** [comment]
Just downloaded your hotfix. Works like charm. Thank you!

**Comment by carlosvkwasek** [comment]
I have version 1.0.88 but I still get the error.

**Comment by DanPristupov** [comment]
@carlosvkwasek https://github.com/ForkIssues/Tracker/issues/611
