### ISSUE TITLE
fork cli dyld error

### ISSUE THREAD

**Issue by dobe** [ForkIssues/Tracker#612]
version: 1.0.78

os: 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

since a week or so my fork cli does not work anymore, it fails witth:

```
$ fork
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /usr/local/bin/fork
  Reason: image not found
Abort trap: 6
```

however starting it with open works:

```
open -a Fork .
```

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/Tracker/issues/611
