### ISSUE TITLE
Gitgub with 2FA is always offline

### ISSUE THREAD

**Issue by mskonovalov** [ForkIssues/Tracker#615]
I have GH account with 2FA enavled. Each time I start the app it says that it is offline.
The weird thing is that I'm unable to pull changes even considering that I have ssh key set up. So I can pull via cmd but cannot via app until I'll be online.

To go online I need to enter not only 2nd factor but username and password each time.
It would be great to save username and password at least.

**Comment by maksimovic** [comment]
It shouldn't be that way. I too have a Github account connected and it has 2FA enabled, but I have none of those issues.

Did you set up 2FA after adding your GH account to Fork, maybe? Wondering if that could mess some things up. While I (just a regular user) don't have a better suggestion than to try removing and adding the GH account again, I hope @DanPristupov will have some more useful advice for your case, though.

**Comment by DanPristupov** [comment]
This is an unusual issue.
In addition to what @maksimovic said, I'd advice to check log at ~/Library/Caches/Fork/fork.log

**Comment by mskonovalov** [comment]
Guys, thanks for the info.
I'll try to re-add the account. Though I'm pretty sure I added 2FA way before starting to use fork :)
But I'm just curious how it should work?
So for me weird issue is that if I'm offline I cannot pull changes. I'm pretty sure it should work with ssh key.
Also while fork is running it will keep token in memory but if I turn it off next time will I need to enter username/password/2Fa again? Or it should be stored somehow between runs?

**Comment by mskonovalov** [comment]
I'll close this for now as it seems to start working :)
