### ISSUE TITLE
Push failed to organization repo: permission denied

### ISSUE THREAD

**Issue by calvintam236** [ForkIssues/Tracker#617]
Git 2.21 Fork instance, Fork 1.0.78.2, Linked Github account in Fork

Tried to push the repos in organization. Fork gives error.

```log
Pushing to https://github.com/<removed>/<removed>git
remote: Permission to <removed>/<removed>.git denied to calvintam236.
fatal: unable to access 'https://github.comr/<removed>/<removed>.git/': The requested URL returned error: 403
```

However, I can push it using ```git push``` in terminal..

**Comment by DanPristupov** [comment]
Does Fork has access to your organization? https://github.com/settings/applications

**Comment by calvintam236** [comment]
There's the setting for individual organization. Thanks, @DanPristupov.
I wish Fork would prompt user to grant such permission.

**Comment by DanPristupov** [comment]
I think this problem was created by https://github.com/ForkIssues/Tracker/issues/529

**Comment by Darthagnon** [comment]
I just had this same issue with the latest version of Fork (v1.76.5.0) and the solution was to goto: https://github.com/organizations/org-name/settings/oauth_application_policy and disable the **Third-party application access policy** (it by default blocks access via 3rd party apps, giving `403` on git push, and I couldn't find any way to add 3rd party apps to any "owned/approved" list)
