### ISSUE TITLE
Blame name list displaced

### ISSUE THREAD

**Issue by DanielAdolfsson** [ForkIssues/Tracker#618]
In the blame window, the Committer+Date is displaced by one line.

![Screenshot 2019-05-12 at 19 55 08](https://user-images.githubusercontent.com/593645/57586052-331ca880-74f0-11e9-8b32-d8c3f2c61ba5.png)

**Comment by DanPristupov** [comment]
I need more details on how to reproduce that.

**Comment by DanPristupov** [comment]
No response -> No fix.
