### ISSUE TITLE
Rebase error

### ISSUE THREAD

**Issue by thangnm-rikkeisoft** [ForkIssues/Tracker#623]
I got this error when i try to rebase.
(Fork 1.0.78.2)

dyld: Symbol not found: _$s8RawValueSYTl
  Referenced from: /Applications/Fork.app/Contents/Resources/fork_ri
  Expected in: /usr/local/lib/libswiftCore.dylib
 in /Applications/Fork.app/Contents/Resources/fork_ri
error: "/Applications/Fork.app/Contents/Resources/fork_ri" died of signal 6
error: There was a problem with the editor '"/Applications/Fork.app/Contents/Resources/fork_ri"'.

**Comment by DanPristupov** [comment]
What macOS version do you have? Can this (https://github.com/ForkIssues/Tracker/issues/611) be related?

**Comment by thangnm-rikkeisoft** [comment]
@DanPristupov I run on macOS 10.13.6.

**Comment by thangnm-rikkeisoft** [comment]
Thank @DanPristupov so much!
I install Swift 5 command line and it works fine!
