### ISSUE TITLE
Shortcut to open list of branches

### ISSUE THREAD

**Issue by leandrofavarin** [ForkIssues/Tracker#63]
v1.0.51 added listing of branches, but there's currently no way to open it using a shortcut.

Like GitHub for Mac (the non Electron version), you can type Cmd+B to start filtering and finally press enter to checkout the selected branch.

v1.0.51 already moves the cursor to filtering, but it can't yet have an all hands-on experience just like GitHub for Mac.

**Comment by DanPristupov** [comment]
This is a great proposal. I'll add the shortcut in the next update.

**Comment by DanPristupov** [comment]
@leandrofavarin I just released Fork 1.0.52 with the Cmd+B shortcut which opens the branches list.

**Comment by leandrofavarin** [comment]
Fantastic! Thank you so much ⭐️
