### ISSUE TITLE
Rebase: Save rewording with fn+return (macOS)

### ISSUE THREAD

**Issue by qqilihq** [ForkIssues/Tracker#630]
I LOVE the rebase dialog, however I'm constantly stumbling when rewording a commit:

1. I open the **Interactive Rebase** dialog 
2. Select a commit
3. Hit **r**
4. Rewrite my message
5. Hit **fn+return**, expecting that this will save my message by triggering the **OK** button in the bubble

Instead, the fn+return triggers the **Rebase** button, and my edit is lost.

![Bildschirmfoto 2019-05-26 um 13 05 03](https://user-images.githubusercontent.com/2172260/58380868-323b4a80-7fb7-11e9-8f2d-5acca0b28671.png)

**Comment by DanPristupov** [comment]
Do you use the latest update (Fork 1.0.78)?

**Comment by qqilihq** [comment]
Yes, Fork 1.0.78.2 on macOS 10.13.6

**Comment by DanPristupov** [comment]
I will investigate that.

The Reword dialog should behave in the same way as the Commit view:
- Return should move the focus to the description field
- ⌘Return should confirm the changes.

**Comment by qqilihq** [comment]
Thank you! I can confirm that **cmd+return** behaves as expected.

I'm not sure why I’m always trying **fn+return** instead (probably I’m still used to it from using a different Git client back then). As **cmd+return** works fine, this is probably not a real bug and just my bad habit and I need to re-align :-)

Thanks again.

**Comment by DanPristupov** [comment]
I made `Fn+Return` to not close the rebase dialog.

**Comment by qqilihq** [comment]
Awesome! Thank you!
