### ISSUE TITLE
Login issue when repo has multiple origins on the same host

### ISSUE THREAD

**Issue by rjaakke** [ForkIssues/Tracker#631]
I have a repo with 2 origins, both on dev.azure.com

For instance:
https://personal@dev.azure.com/personal/MyRepo/_git/MyRepo
https://work@dev.azure.com/work/MyRepo/_git/MyRepo

When I fetch them for the first time it asks for a password and it is stored in my keychain.
However, if a dot a "Fetch all remotes" Fork only succeeds in fetch one and errors the other.

_From https://personal@dev.azure.com/personal/MyRepo/_git/MyRepo
 = [up to date]      develop          → origin/develop
  = [up to date]      master           → origin/master
fatal: Authentication failed for 'https://work@dev.azure.com/work/MyRepo/_git/MyRepo'
error: Could not fetch Work

In a case you entered incorrect password, please
update it in Keychain Access application._

Fetching them individually fails the first time but succeeds the second time until I try to fetch the other remote.

It looks it fails to get the correct entry from my keychain because of the same hostname.
My keychains show 2 entries for "Fork.dev.azure.com.https"

**Comment by DanPristupov** [comment]
Hi. Could you send me the log file (`~/Library/Caches/Fork/fork.log`) after reproducing the problem? My email is support@forkapp.io
