### ISSUE TITLE
Page guide in commit message field is too hard to see

### ISSUE THREAD

**Issue by stk-ableton** [ForkIssues/Tracker#632]
The page guide that shows the allowed width of commit messages is almost impossible to see. Would be great to display this much more prominently.

**Comment by stk-ableton** [comment]
Related: the page guide doesn't seem to show at all in the "reword message" sheet. It would be useful there, too.

**Comment by DanPristupov** [comment]
I improved the visibility in 1.0.79.

The reword popover still misses the guideline though

**Comment by DanPristupov** [comment]
I added guideline in 1.0.80
