### ISSUE TITLE
Stage with Enter no more working

### ISSUE THREAD

**Issue by IlyaSemenov** [ForkIssues/Tracker#638]
Stage/Unstage always used to work with Enter (it's even still documented here - https://github.com/ForkIssues/Tracker/issues/309). With the last update, Enter is no more working. It's now either "documented" Shift-Cmd-S, or (as I discovered) Ctrl-Enter. Both are less convenient than simple Enter. Can the change be reverted?

**Comment by DanPristupov** [comment]
Thank you. This is bug. I'm going to release hotfix in a few hours.

**Comment by DanPristupov** [comment]
I've just released the 1.0.79.3 hotfix.
