### ISSUE TITLE
Custom folder/groups in repo manager removed?

### ISSUE THREAD

**Issue by wachilt** [ForkIssues/Tracker#639]
Hi,

The previous version of Fork (1.0.78) allowed me to set a custom folder/directory within the repo manager for grouping related local repos. This appears to have disappeared in the latest build (1.0.79). I am unsure if the is a bug at my side or this functionality has been deliberately removed in the latest built. If it _has_ been removed, I would love to see it make a come back as it makes organising local repos much more intuitive.

Thanks :)

**Comment by DanPristupov** [comment]
No, it's still there:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/618115/58762647-34228200-8552-11e9-9292-1ccdba997e57.png">

**Comment by wachilt** [comment]
*blush*

Thank you Dan.

Personal note: never open an issue the day after the (Saturday) night before. ;)
