### ISSUE TITLE
"Stage All" button doesn't stage unselected files

### ISSUE THREAD

**Issue by Niels-NTG** [ForkIssues/Tracker#64]
In version 1.0.51 I've noticed that pressing the "Stage All" button only stages files that are currently selected. I would expect that "Stage All" would stage ALL unstaged files.

**Comment by DanPristupov** [comment]
Hi. Thank you for reporting that.

I reproduced the bug: "Stage All" doesn't work, however "Unstage All" still works. This is going to be fixed in next update.
