### ISSUE TITLE
[Improvement] make repo autoscan deeper

### ISSUE THREAD

**Issue by jimblue** [ForkIssues/Tracker#640]
Hi,

I've just update to the latest release and I tried the new `scan repositories` feature.
I was a bit surprise to see only 2 repositories left on more than 20...

The 2 repositories that have been effectively scanned by Fork are 2 levels down from the default source folder.

So I guess the problem come from the new autoscan that is not scanning deep enough in the folder structure for repositories.

Could you please fix that?

Thank you so much.

Cheers

**Comment by DanPristupov** [comment]
What is your folder structure?

**Comment by jimblue** [comment]
Deepest repos are 4 levels down

**repositories (default source folder)**
- websites:
  - website1:
    - design
    - html (repo is here)
    - time-machine

**Comment by jimblue** [comment]
Hey @DanPristupov, does my previous message help you to understand the problem?
Basically Fork should scan for git project on more subfolder.

I know using a lot of subfolders to organise repositories is probably not the best, but they is no better option for now.

What could fix this is to be able to add tag in Fork to organise folder by type. But it's an other feature.

**Comment by DanPristupov** [comment]
Yes, I understood the problem, thank you.

I will try to make the scanning deeper but I'm really careful about performance:

- Getting into folders like `node_modules` could be crazy.
- Some people don't think much and point default source directory to user root (`~/`).

I think a good improvement could be to allow to drag and drop folders containing other repos from Finder to Fork.

**Comment by jimblue** [comment]
To prevent performance problems you could scanning deeper while ignoring `node_modules` and `vendors` folders.
Drag and drop could be nice too 😄

**Comment by DanPristupov** [comment]
I improved the automatic scan in 1.0.80. Could you try it and give some feedback?

**Comment by jimblue** [comment]
Awesome! Perfectly working now 🎉 
Thank you so much Dan!
