### ISSUE TITLE
Some toolbar icons are blurry on non-Retina displays

### ISSUE THREAD

**Issue by kitgrose** [ForkIssues/Tracker#643]
The Fork-specific toolbar icons (especially Open Quickly and Stash) are not aligned to the pixel grid on non-Retina displays, so they appear blurry, especially compared to the system-native Open In button which is also on the toolbar:

![Blurry-Buttons](https://user-images.githubusercontent.com/165977/58946387-14e15a00-87c9-11e9-8157-e9e259ef581a.png)

I've produced 32px × 32px versions of the icons (half-res) that are adjusted to align to the pixel grid at 32px and 16px square. All I've done here is extract `OpenQuickly_Normal@2x.png` and `Stash_Normal@2x.png` from `Fork.app/Contents/Resources/Assets.car` and adjust the artwork to align to every 4th pixel, then resized them down:

![OpenQuickly_Normal](https://user-images.githubusercontent.com/165977/58945381-1c9fff00-87c7-11e9-9d7d-81982658e3a8.png) ![Stash_Normal](https://user-images.githubusercontent.com/165977/58945382-1c9fff00-87c7-11e9-9997-ea0084760423.png)

I'm not sure why your toolbar icons would be currently produced at 4x instead of 2x but I figured it was more helpful for you to have them as simple drop-in versions at half your 2x scale. Just in case native 16px square ones are somehow more useful for you, I've produced those too:

![OpenQuickly_Normal@0 5x](https://user-images.githubusercontent.com/165977/58945636-9afca100-87c7-11e9-91ea-383422672f90.png) ![Stash_Normal@0 5x](https://user-images.githubusercontent.com/165977/58945637-9afca100-87c7-11e9-92af-ba22c1ed2a96.png)

**Comment by ZevEisenberg** [comment]
+1 they’re also blurry in the sidebar on non-Retina displays. Fork 1.0.85.1, macOS 10.15 (19A602).
![Screen Shot](https://user-images.githubusercontent.com/464574/67117622-26903080-f1b1-11e9-9b3a-55187b4e5a34.png)

**Comment by DanPristupov** [comment]
This one is tricky. I don't have a non-retina Mac.

**Comment by ZevEisenberg** [comment]
@DanPristupov you can run the app in low-res mode! I don’t know if you can do it directly from Xcode, but you can do it in the Finder like this: https://www.idownloadblog.com/2016/06/24/launching-apps-in-low-resolution-mode-on-retina-display-macs/

It’s not perfect, since non-retina apps on a Retina display look different than on a non-Retina display, but it might be enough to help debug.

Also, if you can get access to a non-Retina monitor or TV, you could connect your Mac to that. Just make sure you’re running at the display’s native resolution, with no extra scaling or interpolation applied.

**Comment by akloeber** [comment]
Same here. Some icons are blurry on the external screen while they are perfect when dragged onto my MacBook Pro's Retina screen. See the following screenshots which show the exact same instance of Fork dragged from one screen to the other (first one is non-Retina):
![Bildschirmfoto 2019-10-29 um 12 48 54](https://user-images.githubusercontent.com/968308/67764834-0e3ed200-fa4b-11e9-9123-d0a7ca9e508f.png)
<img width="1367" alt="Bildschirmfoto 2019-10-29 um 12 49 09" src="https://user-images.githubusercontent.com/968308/67764839-126aef80-fa4b-11e9-8b72-1dd421da44f2.png">

**Comment by DanPristupov** [comment]
Alright, when you update to 1.0.86 the icons should look better. It took us a lot of time because we had to literally redraw every icon twice (@1 and @2). I'm looking forward to hear your feedback :)

**Comment by akloeber** [comment]
For me this issue is solved with v1.0.86. Icons look perfect on both Retina and non-Retina displays.
Thanks a lot!!

**Comment by ZevEisenberg** [comment]
![source](https://user-images.githubusercontent.com/464574/68601420-480fcf80-0472-11ea-9221-d6cddabb6704.gif)

**Comment by kitgrose** [comment]
What an incredible improvement!

The icons are still blurry (most notably the Stash icon) if you check the "Use Small Size" option for the toolbar, but I don't (I didn't even know it was an option until I went looking). I wouldn't have any qualms with marking this issue as resolved.
