### ISSUE TITLE
“Use monospace font in commit description” option doesn’t work when rewording

### ISSUE THREAD

**Issue by yvt** [ForkIssues/Tracker#644]
This option, which changes the commit message’s font, doesn’t seem to work inside the “Reword” popup:

<img width="706" alt="Screen Shot 2019-06-05 at 23 31 55" src="https://user-images.githubusercontent.com/5253988/58964598-271fc000-87ea-11e9-9055-a49fa6216be9.png">

**Comment by DanPristupov** [comment]
Fixed in 1.0.80

**Comment by yvt** [comment]
Cool, I confirmed that it's now rendered using a monospace font. Thank you!
<img width="692" alt="Screen Shot 2019-06-15 at 21 37 56" src="https://user-images.githubusercontent.com/5253988/59551526-060f5a00-8fb6-11e9-8ae1-e6e33670f3b1.png">
