### ISSUE TITLE
[Change Request] Remember directory folding in Repository Manager

### ISSUE THREAD

**Issue by dl6nm** [ForkIssues/Tracker#645]
I am using Fork for Mac also now at home and I expect the same behavior as I know from Fork for Windows.

Regarding to the corresponding [TrackerWin Issue No. 158](https://github.com/ForkIssues/TrackerWin/issues/158), it would be a good idea to remember the folding state of directories in the Repository Manager.

**Comment by DanPristupov** [comment]
Thank you for the feature request.
Implemented in Fork 1.0.80.

**Comment by dl6nm** [comment]
Works as expected! 
Thank you Dan.

**Comment by DanPristupov** [comment]
👊
