### ISSUE TITLE
[Bug] Staging specific lines commits entire file

### ISSUE THREAD

**Issue by loralee90** [ForkIssues/Tracker#647]
This used to work but seems to be broken now. Committing after staging specific lines in a file commits the entire file.

**Comment by DanPristupov** [comment]
Can you write steps to reproduce that?

**Comment by maksimovic** [comment]
I cannot reproduce this in 1.0.79.4

I added 3 new lines in a file, selected two of them, staged them and commited - the remaining new line remained in staging area, while the two lines got commited properly.

**Comment by loralee90** [comment]
Interesting. I'm also using 1.0.79.4. After playing around with it a bit I realized that the issue only arises when I'm working on frontend files, particularly `.jsx` and `.js` files. Working on backend ruby files seems to work properly.

**Comment by DanPristupov** [comment]
Are you sure Fork performs the commit?
What message does the commit have?
Do you use any 3rd party software/IDE which can track changes and commit?

**Comment by DanPristupov** [comment]
Please check the log file: `~/Library/Caches/Fork/fork.log`. It might reveal new details.

**Comment by loralee90** [comment]
Hi there, you're right, the issue isn't fork. We have a js pre commit hook and are using Prettier on each commit, which stages the entire file instead of just the specific lines. 

Closing this, but thank you so much for your responsiveness and help!!! And thanks for all your work on this app. Love fork ❤

**Comment by DanPristupov** [comment]
At least it made your code prettier :).
