### ISSUE TITLE
Folder names not clear if I have a white background

### ISSUE THREAD

**Issue by wyred** [ForkIssues/Tracker#648]
I like to use the 4 finger swipe down to quickly open my repos, but because I have a white background, the folder name blends in very well making it difficult to read.

<img width="396" alt="スクリーンショット 2019-06-11 15 36 32" src="https://user-images.githubusercontent.com/432325/59252795-6e310980-8c5f-11e9-80e8-81823224ac2a.png">

**Comment by DanPristupov** [comment]
Isn't that a macOS feature?

**Comment by wyred** [comment]
I see, sorry, I didn't see this in other apps so I thought it was something special done for Fork.
