### ISSUE TITLE
Configure "unstage" prompt

### ISSUE THREAD

**Issue by clounie** [ForkIssues/Tracker#65]
Right now if you `Cmd+Shift+S` on a selected area when the file is already unstaged, Fork will remove the changes without further questioning. 

This is honestly kind of nice (not to confirm), but not consistent with the UI when you right click -> Discard changes.

So:
1. Please match behavior of the keyboard shortcut and the mouse UI
2. It'd be nice to have a "do not ask for confirmation in future" configuration option for this.

**Comment by DanPristupov** [comment]
Not sure I understand you.

When you `Cmd+Shift+S` on an unstaged file, Fork will stage it, not remove.

**Comment by clounie** [comment]
To reproduce:
1. Make at least two changes in a file and leave it unstaged
2. Select (only) one of the areas
3. Ctrl+Shift+S

So really just a bug. Wasn't fully thinking when I posted, I guess!
