### ISSUE TITLE
Open Repository Manager is not updated when repo added via `fork` command

### ISSUE THREAD

**Issue by flit** [ForkIssues/Tracker#650]
**Steps to reproduce**
1. Open a Repository Manager tab.
2. Use `fork` command to open a repo not currently managed by Fork.

**Actual**
A new tab is created for the new repo, but the existing Repository Manager tab does not show the new repo. Creating a new Repository Manager tab does list the new repo.

**Expected**
The new repo is opened in a new tab, and the existing Repository Manager is updated to list the new repo.

**Platform**
macOS 10.14.5

(Many, many thanks for creating the best git GUI interface! 🙇🏽‍♂️)

**Comment by DanPristupov** [comment]
Fixed in 1.0.80.
Thank you for bug report.
