### ISSUE TITLE
Repository Manager rescan fails to find all repositories

### ISSUE THREAD

**Issue by anobleperson** [ForkIssues/Tracker#653]
In the new repository manager I've lost visibility to all my repositories because the "rescan" feature only finds 4 repositories out of about 30 that are in sub-directories below the default folder.

Fork version - 1.0.79.4

Here is what Repo Manager shows:
![image](https://user-images.githubusercontent.com/2583737/59475510-4f18be80-8e8f-11e9-8946-b34e09ecbe88.png)
Here is (part of) what Finder shows:
![image](https://user-images.githubusercontent.com/2583737/59475552-7a9ba900-8e8f-11e9-9689-1e201e456092.png)

Let me know if there are any logs I can provide to help debug.

**Comment by DanPristupov** [comment]
Probably same as https://github.com/ForkIssues/Tracker/issues/640

**Comment by anobleperson** [comment]
Agreed, I did try to find existing issues but must have used the wrong keyword sorry.  it Is a bit annoying having to open each repository to get to it rather than the list like old repo manager.  A configurable depth scan would be handy.

**Comment by DanPristupov** [comment]
Fixed in 1.0.80.

**Comment by anobleperson** [comment]
Working well now, thanks!
