### ISSUE TITLE
[Feature Request] Sort Commits By Date

### ISSUE THREAD

**Issue by aethe** [ForkIssues/Tracker#655]
Hi,

Fork reorders commits in a way so that commits to one branch appear one right after another (when possible). While it makes it easier to have an overview of the work done on a particular branch, I think displaying commits in the chronological order would make more sense. It would be easier to navigate through the history, see all commits happened on a particular day, search for a commit knowing only its approximate date, etc.

Please consider adding this as an improvement or an optional feature.

Cheers

**Comment by DanPristupov** [comment]
Check the preferences please.
<img width="556" alt="image" src="https://user-images.githubusercontent.com/618115/59551721-49e66d00-8f7e-11e9-80fc-a2aad200572b.png">

**Comment by aethe** [comment]
Well, I am happy to know this feature is already there, but no idea how I overlooked it when I searched for it last time. 😕 Thanks for pointing out!
