### ISSUE TITLE
Do not propose to stash and reapply when only submodules are changed

### ISSUE THREAD

**Issue by Weiged** [ForkIssues/Tracker#658]
When i pull something and there are only submodule changes in workspace. If i choose "stash" from the dialog that message would be shown with "Git Error".
![image](https://user-images.githubusercontent.com/41810718/59650601-2d824480-91b9-11e9-8d8f-506927fd1b12.png)

**Comment by Weiged** [comment]
my version is 
![image](https://user-images.githubusercontent.com/41810718/59650699-8520b000-91b9-11e9-9550-e34a9795fde1.png)

**Comment by DanPristupov** [comment]
Thank you. I'll fix this in the next update.

**Comment by Weiged** [comment]
😁

**Comment by DanPristupov** [comment]
Just want to mention there that the 'stash and reapply' option in the checkout dialog is also affected.

**Comment by Weiged** [comment]
GREAT!!!

**Comment by DanPristupov** [comment]
Fixed in 1.0.81.

Thank you for reporting that.
