### ISSUE TITLE
Commit message fields gets cleared when switching to "All Commits" view

### ISSUE THREAD

**Issue by Niels-NTG** [ForkIssues/Tracker#66]
When something is typed in the "Enter commit subject here" text field and switch to the "All Commits" view and back again, the contents of this field are gone and I have to type my message again.

**Comment by DanPristupov** [comment]
Hi,

I can't reproduce this. Can you create a step-by-step guide and record your actions? (https://support.apple.com/kb/PH5882?locale=en_US&viewlocale=en_US)

Thanks.

**Comment by Niels-NTG** [comment]
[issue 66 screen recording.mov.zip](https://github.com/ForkIssues/Tracker/files/1145031/issue.66.screen.recording.mov.zip)

**Comment by DanPristupov** [comment]
Here's what I did:
<img src="https://user-images.githubusercontent.com/618115/28165283-79e9382c-67d3-11e7-9496-25d47b05809c.gif" width="300"/>

**Comment by DanPristupov** [comment]
@Niels-NTG that's strange. You do exactly what I did.

Could you restart Fork please? Does this problem exist with other repositories?

**Comment by Niels-NTG** [comment]
It only seem to happen with repos that are submodules.

**Comment by DanPristupov** [comment]
@Niels-NTG good catch! 👍 That's probably the cause. I'm going to investigate the problem.

**Comment by DanPristupov** [comment]
@Niels-NTG Hi. The problem has been fixed in 1.0.53.
