### ISSUE TITLE
[Feature request] Shortcut for "Stage All" command

### ISSUE THREAD

**Issue by fkoehler** [ForkIssues/Tracker#661]
Maybe I am too stupid but I can't find a keyboard shortcut for the "Stage All" button

**Comment by DanPristupov** [comment]
I think we don't have that yet.

**Comment by DanPristupov** [comment]
I added the  ⌥⇧⌘S shortcut in 1.0.81

**Comment by fkoehler** [comment]
I already tried it and it works great.

One follow up question maybe: The only reason I know this shortcut exists
is this issue. I could not find any hint in the app. Is there are list of
all shortcuts I am missing?

Am Di., 9. Juli 2019 um 15:19 Uhr schrieb Dan <notifications@github.com>:

**Comment by DanPristupov** [comment]
All shortcuts are mentioned in menus:

<img width="225" alt="image" src="https://user-images.githubusercontent.com/618115/60897385-489c1d80-a268-11e9-9e7d-31fdbda297fa.png">

I should publish a list of available keyboard shortcuts to the website.
