### ISSUE TITLE
[Feature request] Allow to force push in push dialog

### ISSUE THREAD

**Issue by fkoehler** [ForkIssues/Tracker#664]
I would like to foce push `git push -f` to my branch because I changed the history locally inside the push dialog:

![image](https://user-images.githubusercontent.com/943818/60042159-588afd80-96bd-11e9-9263-ff58a1813d44.png)

Having a shortcut for this would be an extra bonus. This might open up the push dialog with force push preselected.

**Comment by DanPristupov** [comment]
The force push checkbox will appear when you push a branch with a tracked reference.

**Comment by fkoehler** [comment]
The problem seems to be that when I amend my last commit in the branch and it is the only commit which I would like to force push but I can't because the checkbox does not show up

**Comment by DanPristupov** [comment]
Ensure that your local branch tracks the remote one (that option is available in local branch context menu on the sidebar).

**Comment by fkoehler** [comment]
Of course it works once the branch is tracked :) Sorry for the noise
