### ISSUE TITLE
Option to apply patch by drag and drop

### ISSUE THREAD

**Issue by Tunous** [ForkIssues/Tracker#666]
It would save me a lot of time if it was possible to apply patches by performing **drag and drop** operation. Right now I have a patch file that I sometimes have to apply to my repository and it's a bit time consuming having to select apply patch action from menu and search for that file each time.

I know that as an alternative I could save that patch as an stash to have easier access to it, but I prefer to keep my stash list less cluttered and keep less commonly applied changes saved as patches. Such a feature would save me some time.

**Comment by Tunous** [comment]
Thanks, it now works in 1.0.81.

**Comment by DanPristupov** [comment]
Yes. Sorry, I forgot to mention that.
