### ISSUE TITLE
ERROR: remote: Repository not found.

### ISSUE THREAD

**Issue by StefanoCecere** [ForkIssues/Tracker#669]
i moved (transferring ownership) some private repos from one account to another. and now Fork doesn't see them anymore:

```
remote: Repository not found.
fatal: repository 'https://github.com/rtr-solutions/SE_eCatalog3D_U3D.git/' not found
error: Could not fetch origin
```

the strange thing is that GitHub Desktop sees them perfectly.

is there any real difference in the login system with GitHub between Fork and GitHub Desktop?

NOTE: i have OAuth token login and the git connection with SSH key
i logged out and relogin, and even rebooted..

**Comment by DanPristupov** [comment]
This might be a problem with GitHub authentication (https://github.com/ForkIssues/Tracker/issues/498#issuecomment-504157668), in this way, this is a problem in Fork.

1. Try to open your account preferences and give Fork an access to that repo.
2. Log out from GitHub account and Fork and use the default HTTPS authentication
3. Switch to ssh authentication.

**Comment by StefanoCecere** [comment]
ok, problem solved: i had to add Fork to the Authorized OAuth apps list
the request was sent then to the owner of the team of that private repo. when Fork was enabled i could access to the repo.

NB: GitHub desktop works maybe because it's an always authorized app?

![Screenshot 2019-07-02 at 16 47 19](https://user-images.githubusercontent.com/640536/60522439-44f91b80-9ce9-11e9-8296-3d70fb15e421.png)

**Comment by DanPristupov** [comment]
I just released Fork 1.0.82 which uses web-flow way to authenticate on GitHub. Hopefully this will solve the issue.

**Comment by parthamlani** [comment]
Hello I am having the same issue. Could you provide a link to download Fork 1.0.82?

**Comment by StefanoCecere** [comment]
@parthamlani the app auto updates! or re-download from https://fork.dev/

**Comment by parthamlani** [comment]
@StefanoCecere Thank you. I am able to update it now. I was not able to update it yesterday for some reason.

**Comment by jpinnix** [comment]
How do we trigger this web-flow in Fork? I don't see a place in Preferences or in the Repo settings.

**Comment by DanPristupov** [comment]
@jpinnix Repository Manager (Cmd+T) -> GitHub

**Comment by yamahito** [comment]
Had a similar issue that needed me to sign out and re-authenticate...  but it wasn't at all clear that's what I had to do - may I suggest that as soon as github authentication fails, the user is directed to 1/ check their internet connection 2/ re-authenticate to github?

**Comment by jkaunert** [comment]
Using the Apple git instance should fix the issue:

Fork > Preferences > Git

![image](https://user-images.githubusercontent.com/44586402/82125823-3e8f5900-976e-11ea-9742-6d8b936a9d26.png)

**Comment by didley** [comment]
Using the `Personal Access Token` flow to link GitHub instead of `OAuth` allowed me to use the Fork git instance and not require my org to approve the access.

<img width="900" alt="Image" src="https://github.com/user-attachments/assets/d22c814e-9b29-481e-bd0a-cd736b6bb1ea" />
