### ISSUE TITLE
git-sh-i18n: No such file or directory

### ISSUE THREAD

**Issue by rogalski** [ForkIssues/Tracker#67]
After updating to 1.0.52, any action that runs git command in the background ends with error message in popup:

```
/Applications/Fork.app/Contents/Resources/git-instance/libexec/git-core/git-sh-setup: line 46: /usr/local/git/libexec/git-core/git-sh-i18n: No such file or directory
```

macOS Sierra 10.12.5 (16F73) on Man Mini (Late 2014).

**Comment by DanPristupov** [comment]
@rogalski it looks like there's something wrong with your PATH environment.
I'm investigating the problem.
Did you start Fork from terminal?
Could you please run in terminal the following command and send the result to support@git-fork.com:
`>$PATH`.

**Comment by sevenfourk** [comment]
same here, just installed to try that out.  ran Fork from Dock.

Oh, that's weird, why to put git into app distribution, when git is there in the system anyway. I suspect from UI app just to be a skin for a foundation ready there in system. Git distribution here occupies more space than the app itself. 

Anyway, as I see it:
```
lpt-mao-m:git-core sevenfourk$ ls -la /Applications/Fork.app/Contents/Resources/git-instance/libexec/git-core/git-sh-setup
-rw-r--r--  1 sevenfourk  staff  9252 Jul 14 06:44 /Applications/Fork.app/Contents/Resources/git-instance/libexec/git-core/git-sh-setup
lpt-mao-m:git-core sevenfourk$ 
lpt-mao-m:git-core sevenfourk$ /Applications/Fork.app/Contents/Resources/git-instance/libexec/git-core/git-sh-setup
-bash: /Applications/Fork.app/Contents/Resources/git-instance/libexec/git-core/git-sh-setup: Permission denied
lpt-mao-m:git-core sevenfourk$ 
```

**Comment by DanPristupov** [comment]
@rogalski @sevenfourk I made a separate hotfix build. https://git-fork.com/update/files/Fork_1.0.52.1.dmg

Please let me know if the problem is solved so I could release it for everybody.

@sevenfourk regarding the question why to bundle a git binary at all. Many people don't have git in their systems and don't want to install it manually. Here's more information: https://github.com/ForkIssues/Tracker/issues/38

**Comment by sevenfourk** [comment]
@DanPristupov, thanks.

**Comment by DanPristupov** [comment]
@sevenfourk did the new version fix the problem?

**Comment by sevenfourk** [comment]
@DanPristupov, that works. thank you.

**Comment by DanPristupov** [comment]
I released the hotfix publicly.

@rogalski @sevenfourk thank you for you involvement guys ❤️
