### ISSUE TITLE
Remote branch processing issue when remote has case-sensitive branch names

### ISSUE THREAD

**Issue by jsmreese** [ForkIssues/Tracker#670]
I'm working with a remote that has two branches that require case-sensitive processing: `X1` and `x1`.

In the fork app (on Mac), this remote shows an `X1` branch but the commits on that branch as shown in the fork app are those of the remote's `x1` branch.

In the fork app, I do not see a `x1` branch on my remote.

**Comment by DanPristupov** [comment]
Does terminal output give you a correct result?

Git branches are **literally** files on your disk in `.git/refs/` directory. Since macOS by default use a case-insensitive file system, there's no way to recognize the difference. I suppose, you can't have both `X1` and `x1` files in the same folder.

**Comment by jsmreese** [comment]
When I fetch using Fork, I have only `.git/refs/<remote>/X1`, pointing to the tip of the `x1` branch.

When I fetch using the terminal, I see this output:

**Comment by jsmreese** [comment]
Sorry about the close/reopen... based on your comments and what I observe on my filesystem, I'm not convinced there's anything to be done here :(
