### ISSUE TITLE
[Feature Request] Stash but don't apply

### ISSUE THREAD

**Issue by kuthair** [ForkIssues/Tracker#672]
During checkout/switch different branch, it would be nice to have an option to "Stash but don't apply".

Thanks.

**Comment by DanPristupov** [comment]
Why don't you stash your changes before checkout?

There's a stash button on the toolbar and even a Quick Stash shortcut (Option+Shift+Cmd+H)

**Comment by kuthair** [comment]
Ya, that's what I do -- just a shortcut -- totally not necessary.
