### ISSUE TITLE
Feature Request: custom UI actions

### ISSUE THREAD

**Issue by davedelong** [ForkIssues/Tracker#675]
I'd like to create some of my own custom actions in the preferences window and have those show up in places around the app.

When creating a custom action, I'd want to specify the kinds of objects it can operate on, such as a repository, a commit, a tag, a remote, etc.

Then for these actions, I'd like to provide a name, an icon, and a small script to run.

This would let me create actions such as:

- [repository action]: open in terminal
- [remote action]: open in browser
- [commit action]: if pushed, open in in browser
- [tag action]: if pushed, browse tree in browser

Once I've created these actions, I'd like them to show up in the Main Menu, when I right-click on things, and also have them be in the "Customize Toolbar..." sheet for the window.

**Comment by davedelong** [comment]
I would expect that details about the object (`REPO_URL` or `COMMIT_HASH` or `TAG_NAME`) etc would be provided as environment variables to the script so I could pull them out and use them, such as `open "$REMOTE_URL"`

**Comment by DanPristupov** [comment]
I made a quick mock up how this might look like:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/618115/60891966-901dac00-a25e-11e9-8827-43e79e3bd4b9.png">

<img width="435" alt="image" src="https://user-images.githubusercontent.com/618115/60892008-ae83a780-a25e-11e9-93ff-15a31c32647a.png">

**Comment by davedelong** [comment]
🤩 That looks awesome!

**Comment by jasonfharris** [comment]
I wanted to also say it would be very nice to be able to select two revisions as well. Eg one such custom action with two revisions selected could be for instance:
   `difftool --no-prompt --tool opendiff --dir-diff $SHA1..$SHA2`

**Comment by loki980** [comment]
I agree with @jasonfharris.  This feature is found in SourceTree and breaks our workflow.  This feature is requested in #702.

**Comment by DanPristupov** [comment]
@loki980 vote for it
