### ISSUE TITLE
Gitlab.com Account Sign-In Fails with 2FA Enabled

### ISSUE THREAD

**Issue by wohclams** [ForkIssues/Tracker#68]
Signing in to a Gitlab.com account from the Accounts preference pane fails when the Gitlab account has 2-factor authentication enabled. An "Unable to log in" error message is displayed. Neither the account password nor a Gitlab Personal Access Tokens is accepted.
Disabling 2-factor auth on the account fixes the problem (the username and account password are accepted to sign in).

Not quite sure if this is an issue in Fork or a limitation of Gitlab's 2-factor and I'm not sure how Fork interacts with gitlab.com. Based on [their documentation](https://docs.gitlab.com/ce/user/profile/personal_access_tokens.html), a Personal Access Token as a password should allow apps to interact with the Gitlab API when 2-factor is enabled.

**Comment by DanPristupov** [comment]
@wohclams,

even though this is a GitLab's limitation, it's not an excuse for not working properly in Fork.  So, I consider this as Fork's issue and going to fix it soon.
2FA support for Gitlab must be implemented in next major update (which will also include BitBucket support).

**Comment by DanPristupov** [comment]
@wohclams private access token authentication for GitLab is available in Fork 1.0.55. Logging into 2FA accounts works now.
(Bitbucket support is not done yet though).
