### ISSUE TITLE
Support $() operation in custom action

### ISSUE THREAD

**Issue by zentby** [ForkIssues/Tracker#681]
The default action parameter doesn't have "current branch name".

So alternatively, I tried to eval the value from bash command 
`$(git branch | grep \* | cut -d ' ' -f2)`
but when I add this to the parameter and exec it throws error. Seems something relating to the `$` handler.

![image](https://user-images.githubusercontent.com/4077259/61343172-6e847c00-a87f-11e9-9515-d6e3647e8985.png)

![image](https://user-images.githubusercontent.com/4077259/61343149-61678d00-a87f-11e9-9f06-76fc1ec57eca.png)

**Comment by DanPristupov** [comment]
Put this into an SH script. This is what custom actions are supposed to be.

I'm not sure whether I should spend time and try to replicate shell with a support of pipes.

**Comment by zentby** [comment]
Yeah, script file could be a workaround. Not sure how the implementation is but replicate is definitely not an option.

**Comment by kissferenc** [comment]
I think the closing “ is missing at the end of line.
