### ISSUE TITLE
View file at a specific revision in MacOS

### ISSUE THREAD

**Issue by mbarashkov** [ForkIssues/Tracker#682]
It seems like there's no way to view a file at a specific revision in the MacOS app.
Please consider adding it, as it's a common thing to do.

**Comment by DanPristupov** [comment]
<img width="1032" alt="Screenshot 2019-07-17 at 17 32 04" src="https://user-images.githubusercontent.com/618115/61389222-d0150c80-a8b8-11e9-969b-5b0673e81e32.png">

**Comment by mbarashkov** [comment]
Thanks @DanPristupov 
the only thing lacking is the ability to save this file locally. Of course, I can copy entire contents, but...

**Comment by bjtitus** [comment]
@mbarashkov Can't you drag and drop the file from the outline view on the left of that bottom "File Tree" pane? It seems to work for me.

**Comment by mbarashkov** [comment]
I couldn't guess that.
Thanks!!
