### ISSUE TITLE
the filePath hava Chinese, the file history can not show

### ISSUE THREAD

**Issue by chenjiangui** [ForkIssues/Tracker#683]
the filePath hava Chinese, the file history can not show
![bug](https://user-images.githubusercontent.com/18565140/61439809-cbae2980-a974-11e9-92d8-569e7b22281a.jpg)

**Comment by chenjiangui** [comment]
hi i create a simple repository https://github.com/chenjiangui/fork-filePath-bug.git

**Comment by DanPristupov** [comment]
When I run git log, it returns incorrect paths:

> git log --oneline --name-status --follow -- TestPath/测试/testPath.txt


> 7e14cac change file
> M       "TestPath/\346\265\213\350\257\225/testPath.txt"
> d38a979 first creat testPath.txt
> A       "TestPath/\346\265\213\350\257\225/testPath.txt"
> 

This is quite confusing? Do you have an idea why this happens?

This might be a bug in git, because other commands don't encode paths that way.

**Comment by chenjiangui** [comment]
maybe you should decode path.  the sourcetree, xcode, idea are work ok

**Comment by chenjiangui** [comment]
how do you get history change, i try ```git log -p TestPath/测试/testPath.txt```, the history log correct

**Comment by chenjiangui** [comment]
hi,  i config git with ```git config --global core.quotepath false```, the path will not encode
![image](https://user-images.githubusercontent.com/18565140/61600504-8a16ca80-ac63-11e9-9997-b67a6024294f.png)

**Comment by chenjiangui** [comment]
I config the global git, fork working ok now.

**Comment by DanPristupov** [comment]
Thank you for sharing the solution.
