### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftAppKit.dylib

### ISSUE THREAD

**Issue by melriffe** [ForkIssues/Tracker#686]
I recently upgraded to 1.0.82 and now I get this message when I try to run fork from the command line:

```
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /usr/local/bin/fork
  Reason: image not found
[1]    96200 abort      fork .
```

I'm not sure how to fix this. What additional information can I provide to help debug this?

I'm on macOS 10.13.6.

**Comment by DanPristupov** [comment]
Install Swift static libraries: https://support.apple.com/kb/DL1998?locale=en_US

https://github.com/ForkIssues/Tracker/issues/611
https://github.com/ForkIssues/Tracker/issues/612

**Comment by melriffe** [comment]
Installing now... Thanks for the quick response 👍
