### ISSUE TITLE
[Feature Request] Allow selecting multiple lines in file history 

### ISSUE THREAD

**Issue by mamiller93** [ForkIssues/Tracker#687]
Right now you can click on each commit to see the delta between that commit and the previous one. It would be neat to select multiple consecutive lines and see the before and after, accounting for all of the changes throughout those commits. 

![Screenshot of File History window](https://user-images.githubusercontent.com/577603/61803557-fb878200-adf7-11e9-948d-67cda6f634db.png)

**Comment by DanPristupov** [comment]
You can!

**Comment by mamiller93** [comment]
@DanPristupov How?! I try holding down shift, command, option, control while selecting multiple lines but it doesn't work.

**Comment by DanPristupov** [comment]
Ouch, sorry! I was mistaken. This feature is available on Windows already, but not on Mac. Adding to my todo list then.

**Comment by mamiller93** [comment]
Haha no worries! What a roller coaster of emotions - I was, for a brief few minutes, very excited. I'll wait patiently :) Thank you!

I also forgot to mention that I am on Mac. Good catch!

**Comment by DanPristupov** [comment]
Implemented in 1.0.84
