### ISSUE TITLE
Add push -force option

### ISSUE THREAD

**Issue by info170** [ForkIssues/Tracker#689]
please

**Comment by DanPristupov** [comment]
What do you mean?

**Comment by info170** [comment]
I mean fast-forward mode
I try to push my local branch to another remote branch and got an error -

Pushing to ssh://xxxxx
To ssh://xxxxx
 = [up to date]      add → add
 ! [rejected]        my → master (non-fast-forward)
error: failed to push some refs to 'ssh://xxxxx'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by jasperkuperus** [comment]
Force push is already available:

![Screenshot 2019-08-01 at 10 03 13](https://user-images.githubusercontent.com/1655683/62276129-a8d74700-b443-11e9-8e91-6633c60afcec.png)

**Comment by info170** [comment]
Why it is absent here?
<img width="494" alt="Снимок экрана 2019-08-01 в 14 52 17" src="https://user-images.githubusercontent.com/3503708/62291353-670ec680-b46c-11e9-810a-cdc54543cc5e.png">

**Comment by jasperkuperus** [comment]
Did you already push your branch to the remote? I guess it only shows the `Force push` option when the branch is already available on the remote. @DanPristupov

**Comment by DanPristupov** [comment]
Because the local branch doesn't have a remote tracking reference.


________________________________

**Comment by jasperkuperus** [comment]
Right, hence the `(new)` suffix in the screenshot.

**Comment by info170** [comment]
It happens if I try to push to master too. May be I do smth wrong?
- I clone remote repo
- create my local branch on last origin-master commit (with checkout)
- make changes in file, amend to last commit and try to push my branch to origin-master (check force)
and got error "Updates were rejected because a pushed branch tip is behind its remote ...."

**Comment by DanPristupov** [comment]
Fork doesn not allow to force push to a random branch. You need to create a tracking reference. Check context menu for the local branch on the sidebar.


________________________________

**Comment by info170** [comment]
Yes, thanks it's working after adding tracking reference.
