### ISSUE TITLE
Fork registers itself as `sourcetree` URL scheme handler

### ISSUE THREAD

**Issue by Strajk** [ForkIssues/Tracker#692]
Hi

SourceTree requires authentication to use the app (shitty practice, but ¯\_(ツ)_/¯).
The authentication is done in a browser and uses `sourcetree` URL Scheme for redirecting back to the app.

It seems that Fork is registering itself as a handler for this scheme and making authentication impossible. (IMO in best intentions so Fork can be used as default Git app)

![image](https://user-images.githubusercontent.com/697301/62134299-8547bb80-b2e0-11e9-9d03-92db9ac18b6d.png)

**Comment by DanPristupov** [comment]
Thank you, I didn’t know that.

This is a bad behavior indeed :(. I will check if I can handle it, otherwise I will need to remove the support for ‘Clone’ button in BitBucket.

I think this behavior is disabled by default, but I need to double-check that.


________________________________

**Comment by coultonluke** [comment]
Does this also explain why you have to give permissions to your repo (Bitbucket in my case) to 'Sourcetree for Windows'?:

![image](https://user-images.githubusercontent.com/16463338/109959428-604ad400-7cdf-11eb-9ff8-24be2c6fb240.png)

**Comment by DanPristupov** [comment]
@coultonluke No. This page is caused by OAuth client id used by git credential manager, which is maintained by BitBucket

(https://github.com/microsoft/Git-Credential-Manager-Core/blob/ef29f9adf57abac337a00169fe85b57dcad884e7/src/shared/Atlassian.Bitbucket/BitbucketConstants.cs). 
```
        // TODO: use the GCM client ID and secret once we have this approved.
        // Until then continue to use Sourcetree's values like GCM Windows. <---
```
You will see the same page if you try to fetch from the command line.

**Comment by coultonluke** [comment]
Thank you for confirming. It seemed very strange, I wondered if something other than fork was asking for permissions.

**Comment by DanPristupov** [comment]
> I wondered if something other than fork was asking for permissions

To be precise, it was git-for-windows which asked for credentials. It uses GitCredentialManager by default.

If you log in to your Bitbucket account in Fork (File -> Accounts -> + -> Bitbucket). This way Fork will use its own credential manager and you will see a similar page for Fork.

**Comment by yossizahn** [comment]
> It seems that Fork is registering itself as a handler for this scheme and making authentication impossible. (IMO in best intentions so Fork can be used as default Git app)

Just ran into this... any update on this issue?

**Comment by DanPristupov** [comment]
@yossizahn This is the behavior which you can configure in Fork preferences (Preferences -> Integration -> Default Bitbucket Tool). It's disabled by default, by the way.
