### ISSUE TITLE
[Feature Request] Open Recent Repository, semi fuzzy search

### ISSUE THREAD

**Issue by jasperkuperus** [ForkIssues/Tracker#694]
Ok, first of all, I really love Fork. After having used the command line and SourceTree for ages, Fork is really feature complete and fast!

When I switch projects in other applications, like e.g. VSCode, I can simply type e.g. `mypro` and it will match `myproject`, `my-project` or `my_project`. So, when I use the `Open Quickly ...` feature, I keep on typing `mypro`, but it won't match `my-project`. So, I see myself backspacing and entering `my-pro` to get the match.

It would be nice to have `Open Quickly ...` skip characters like dashes and underscores while matching repositories. It would be a productivity gain for me.

**Comment by DanPristupov** [comment]
Good idea.

**Comment by DanPristupov** [comment]
Implemented in 1.0.85.

**Comment by jasperkuperus** [comment]
Works like a charm! Thanks! Closing this issue.
