### ISSUE TITLE
Hello, how to create a remote repository?

### ISSUE THREAD

**Issue by uclort** [ForkIssues/Tracker#695]
Hello, how to create a remote repository?
I built a project locally. After I added it to fork, how do I create a remote repository and push it?

**Comment by DanPristupov** [comment]
I suppose you want to add another remote, right? Right click on Remotes on the sidebar -> Add New.


________________________________

**Comment by uclort** [comment]
But can't push, prompt Repository not found, I have to create a library on GitHub first? Can't I create and push it automatically?

发件人: Dan <notifications@github.com>
答复: ForkIssues/Tracker <reply@reply.github.com>
日期: 2019年8月1日 星期四 下午6:23
收件人: ForkIssues/Tracker <Tracker@noreply.github.com>
抄送: Null <0x000mm@gmail.com>, Author <author@noreply.github.com>
主题: Re: [ForkIssues/Tracker] Hello, how to create a remote repository? (#695)

I suppose you want to add another remote, right? Right click on Remotes on the sidebar -> Add New.


________________________________

**Comment by DanPristupov** [comment]
Yes, you need to create a new *empty* repo on github. It's a different service which has no relations to Fork.

Regards,
Dan


________________________________
