### ISSUE TITLE
Feature request: Option to only delete remote branches from specific remotes

### ISSUE THREAD

**Issue by esotericist** [ForkIssues/Tracker#697]
I love the ability to be able to bulk delete branches with their remote versions, but I *only* ever want to use this feature to delete remote branches in my repository (what I have as `origin`), and not any other remote repositories I may have open to have pulled branches from for local testing.

Is there any way of limiting this without having to manually check the source repository of every single branch before trying to delete them?

I know I can also delete branches by hand from the repository in a different part of the list, but it'd be nice to be able to safely do it all in one step without any risk of accidentally deleting branches I have permissions for but are not "mine".

**Comment by DanPristupov** [comment]
This is an old issue and I'm not sure if it's still actual...

Remote branche are always prefixed with the remote name. So, if a branch called `origin/branchname` it definitely belongs to `origin`. If a branch has no prefix, it's a local branch.
