### ISSUE TITLE
Can't open fork from the terminal

### ISSUE THREAD

**Issue by romk1n** [ForkIssues/Tracker#698]
When trying to open Fork from terminal I am getting the following error. I have tried reinstall fork from the local/bin by removing and running install from the Fork Preferences. 

Mac OS version  - 10.13.6 (17G8030) (High Sierra)
Fork version - 1.0.82.1

```bash
$ fork 
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /usr/local/bin/fork
  Reason: image not found
[1]    46510 abort      fork
```

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/Tracker/issues/611

**Comment by romk1n** [comment]
@DanPristupov that helped. would be nice to add this somewhere next to install tools, maybe by detecting the version can give a hint to go and download the package! Thanks.

**Comment by DanPristupov** [comment]
Yes, it's a good idea.
