### ISSUE TITLE
[Feature] Option to sort all repositories alphabetically

### ISSUE THREAD

**Issue by edwardloveall** [ForkIssues/Tracker#699]
I have a folder where I store most of my git repositories. There are several hundred organized into folders. When I add them to Fork, they are added in a seemly random order. I'd love to see folders get added in alphabetical order (first the folders, then the items inside the folders recursively), or have an option to sort all folder alphabetically.

Thanks for Fork!

**Comment by DanPristupov** [comment]
Hi. Sorry it looks like we were returning from vacation that time and I missed that request.

Repositories in the repo manager should be displayed alphabetically (folders first). This is how it works in my environment at least.

Does the problem still exist?

P.S. I'd recommend to use the Open Quickly dialog. In the upcoming update (1.0.84) it will get some improvements and also a handy <kbd>⌘</kbd><kbd>P</kbd> keyboard shortcut.

**Comment by edwardloveall** [comment]
Looking now it does seem to work that way! Maybe that was changed recently? Maybe I was just complete wrong. Who know! Thanks for responding and thanks for the great app!
