### ISSUE TITLE
drag and drop to open a git folder is broken v1.0.82.1

### ISSUE THREAD

**Issue by ApolloTang** [ForkIssues/Tracker#700]
After open a new empty Folk window [command-N], I used to be able to open a git repo by drag and drop a finder folder.  After I updated to v1.0.82.1 today, I am no longer able to do that. The only way to open a new git repo now is to ...open [command-o], and then navigate to my repo location.

Not sure if this feature is removed or it is simply broken.  If it is removed could you please restore ? It is alot easy to drag and drop instead of open and then navigate.

**Comment by DanPristupov** [comment]
I will check.

**Comment by ApolloTang** [comment]
This is now fixed

 Thank you!! 

I am using 1.0.85.2 
closing issue now.
