### ISSUE TITLE
[feature request] show location of git repo in file system

### ISSUE THREAD

**Issue by ApolloTang** [ForkIssues/Tracker#701]
I have two copies of the same repos in two different folder location in my file system (see image):

![Screen Shot 2019-08-05 at 4 26 29 AM](https://user-images.githubusercontent.com/1150961/62450098-a58cd580-b739-11e9-9b84-2d26fd1ead3c.png)

Currently I have no way to tell which is which other than open in Terminal [ctrl-cmd-T] or open in Finder[ctrl-cmd-O] 

Would it be possible to have a way to know this information ? like hover the mouse over the window header or the repo name then a tool tip pop up will  show the folder path ?

**Comment by DanPristupov** [comment]
I think a better solution would be to rename one of the repositories. The option to rename is available in context menu in the Repository Manager (Cmd+T).

**Comment by ApolloTang** [comment]
Thanks for reply and offer solution @DanPristupov.

I cannot rename the repos because they are dependency subrepo. I have two copies of the project and used Fork to examine the history in the dependency (for debug purpose). 

in Repository Manager State of the app, I can see the path (see below img) but once I open the repo that information is no longer available
![Screen Shot 2019-08-06 at 3 44 01 AM](https://user-images.githubusercontent.com/1150961/62520923-915ddc80-b7fc-11e9-9bc4-774f9d261a3e.png)

I do think this is a legit UI use case, please consider.

By the way, I love your apps, SourceTree mess up big time, thanks to your app to rescue !!!

**Comment by ApolloTang** [comment]
By the way,  there isn't really a "legit" way to navigate to "Repository Manager", Repository Manager is the "New Window" or the "New Tab".

Repository Manager is an important function: I can easily has 30 repos manage under Fork, It should be a more emphasis instead of hidden in New Window (feels like a hack).

**Comment by ApolloTang** [comment]
this feature is now available by right click on the window's title:
![Screen Shot 2019-10-31 at 11 08 05 PM](https://user-images.githubusercontent.com/1150961/67999612-7b14c080-fc33-11e9-921a-9673472411db.png)

Thank you  !!! 

I am using version 1.0.85.2

closing this issue
