### ISSUE TITLE
[Feature Request] ⌘S to stage/unstage changes

### ISSUE THREAD

**Issue by millerdev** [ForkIssues/Tracker#703]
The hotkey to stage or unstag changes (⇧⌘S on Mac) is unnecessarily complex. The much more natural and easy-to-reach ⌘S is unassigned. This is a request to change it to the easier two-key version. If that is undesirable, please allow hotkey assignments to be changed.

**Comment by DanPristupov** [comment]
There's an alternative `Enter` shortcut for stage.

I don't really remember why we use ⇧⌘S, but I'm sure there was a good reason for that :).

**Comment by millerdev** [comment]
Hi @DanPristupov, thanks for the quick reply.

> There's an alternative `Enter` shortcut for stage.

I've noticed that, but it doesn't always work (looks like the `Return` key works, but the `Enter` key, on the keypad, does not).

Also, the `Return` and `Enter` keys are on the right side of the keyboard, which means one must move the right hand from the mouse to the keyboard or move the left hand across the keyboard to hit it. ⌘S is on the left, so is easily typed while keeping right hand on the mouse.

**Comment by millerdev** [comment]
@DanPristupov in trying to adopt your suggestion of using the `Enter` (`Return`) key, I've noticed that the behavior of that key is inconsistent. Sometimes it will cause staged changes to be committed rather than un/staging the selected file, which is quite annoying and unexpected.

**Comment by DanPristupov** [comment]
This is quite strange, because the Commit button is linked to the <kbd>⌘</kbd><kbd>Return</kbd> shortcut. Anyway, I will start using it, may be I'll be able to reproduce the problem.

**Comment by millerdev** [comment]
I think it happens when amending a commit.

**Comment by DanPristupov** [comment]
I added the <kbd>⌘</kbd><kbd>S</kbd> keyboard shortcut to stage/unstage in 1.0.90.

**Comment by millerdev** [comment]
💯 Thank you!
