### ISSUE TITLE
User Information not filled from .gitconfig

### ISSUE THREAD

**Issue by alkazandzhiev** [ForkIssues/Tracker#705]
I am using git from command line and it's fully configured already. I did a first-time install of Fork and it is asking for User Information.
It would be best if this data is with single instance so it won't get de-synchronised when changing between git/Fork/whatever other I may use. I would definitely like to retain the command line git functionality and have it consistent with Fork. So could Fork use the information from the ~/.gitconfig file instead of duplicating it?

**Comment by DanPristupov** [comment]
> I did a first-time install of Fork and it is asking for User Information.
> So could Fork use the information from the ~/.gitconfig file instead of duplicating it?

The problem is that Fork doesn't have a git instance and can't request the global user info at the time you see that window. Extracting git takes a few minutes and is being performed in the next step.
