### ISSUE TITLE
Crashes when trying to hit Show entire file button

### ISSUE THREAD

**Issue by Grjweik** [ForkIssues/Tracker#706]
Crashes all the time when trying to hit 'Show entire file' button. MacOS.
![image](https://user-images.githubusercontent.com/43851797/62859919-4e719c80-bd07-11e9-98cb-042a499cfc6b.png)

**Comment by DanPristupov** [comment]
Does this really happen every time? Did you try different files/repos?

**Comment by Grjweik** [comment]
Hmm, looks like it is a floating bug. I tried to reproduce and failed. But I have some crash reports. Attached them.


[fork_crashes.zip](https://github.com/ForkIssues/Tracker/files/3497226/fork_crashes.zip)

**Comment by DanPristupov** [comment]
Thank you for the crash files.

Not sure if that's possible, but the crash stack looks like a memory corruption is OS. Could you reboot the computer and report if you see the crash once again?

**Comment by Grjweik** [comment]
I experienced this bug on 2 different machines. It started approximately from version 1.0.80.

**Comment by DanPristupov** [comment]
OK, there must be a way to reproduce it then. I will take an attention to that behavior.

**Comment by codingmanu** [comment]
Happened to me a couple times too. I'm using Version 1.0.90. I'll try to find a way to replicate it.

**Comment by DanPristupov** [comment]
It happens when you do **something**, close the tab and then press any button on the toolbar in other tab. But I don't know what exactly to do. It should be something slightly uncommon (like merge conflict, submodule diff, lfs diff etc), otherwise it would be easily reproducible.

**Comment by matthesoundman** [comment]
This just happened to me. It has happened only once before.
[Fork_2020-04-16-160109_.crash.zip](https://github.com/ForkIssues/Tracker/files/4490116/Fork_2020-04-16-160109_.crash.zip)
