### ISSUE TITLE
Status rescan after failed commit?

### ISSUE THREAD

**Issue by stk-ableton** [ForkIssues/Tracker#707]
We have a pre-commit hook that checks the formatting of source files, and rejects the commit if the formatting is not correct. As an additional convenience, the hook reformats the files for you (but doesn't stage them, let alone commit the reformatted files; we know that would be bad).

Now the problem is that the reformatted files don't show up as modified in the "Unstaged changes" view. I have to hide and show Fork to force the status to refresh. Would you consider adding a status refresh after failed commits to solve this?

**Comment by stk-ableton** [comment]
I only just realized that I can also press ⌘R to refresh manually. I had no idea that Fork has this command, as I have never needed it before. Which kind of proves my point.

**Comment by DanPristupov** [comment]
> Would you consider adding a status refresh after failed commits to solve this?

Yes, makes sense.
