### ISSUE TITLE
Show child(ren) of a commit in the 'Commit' section/tab

### ISSUE THREAD

**Issue by ScriptShot** [ForkIssues/Tracker#709]
I know, i just asked for it per email. You replyed that you don't know how to get this info from a commit. 

I think this works like this:

`git rev-list --all --not $COMMIT^@ --children | grep "^$COMMIT"`

Please try out :) 
I would be very happy if, in addition to the parents info, the children would also be shown.

**Comment by DanPristupov** [comment]
Most probably I've answered that I don't know a **fast and reliable** way.

```
Dan:Sources dan$ cd samples/chromium
Dan:chromium dan$ time git rev-list --all --not HEAD^@ --children | grep "^HEAD"

real	0m3.396s
user	0m1.239s
sys	0m0.867s
```

It took **3.4** seconds to determine children of HEAD on the Chromium repo.

**Comment by ScriptShot** [comment]
I don't know for sure, but 'git rev-list --all --not HEAD^@ --children | grep "^HEAD"' does not the job. 

I tried '$ git rev-list --all --not $COMMIT^@ --children | grep "^2e18a22"'

$ time git rev-list --all --not $COMMIT^@ --children | grep "^2e18a22"
2e18a228e9723573d7b89915f5bf3cf1bcec2101 f03069c6c25dc02f90ce07ef4cbd9414fa2af7f6 c3f592661c101c60daa6e974cbcf937cd96952b4

real    0m0.432s
user    0m0.046s
sys     0m0.046s

Seems to be fast. And maybe reliable too :)

**Comment by ScriptShot** [comment]
> Most probably I've answered that I don't know a **fast and reliable** way.
> 
> ```
> Dan:Sources dan$ cd samples/chromium
> Dan:chromium dan$ time git rev-list --all --not HEAD^@ --children | grep "^HEAD"
> 
> real	0m3.396s
> user	0m1.239s
> sys	0m0.867s
> ```
> 
> It took **3.4** seconds to determine children of HEAD on the Chromium repo.

You only have to search on commits, i think. Forgive me if I'm stupid.

**Comment by DanPristupov** [comment]
```
Dan:chromium dan$ time git rev-list --all --not $COMMIT^@ --children | grep "^1ca17c55"
1ca17c55c4e23840893be64e18b80518ea26da85 f9395d77ab8feb15a222dc8e2b3608ac6db22302

real	0m3.700s
user	0m3.808s
sys	0m1.358s
```

**Comment by DanPristupov** [comment]
> You only have to search on commits, i think.

Exactly! Determining children takes at least O(n) walk through all the commits of the repo.

For instance, currently my Chromium repo contains 811 781 commits.

P.S. I just checked the swift language repo. `real	0m1.685s`

**Comment by ScriptShot** [comment]
Maybe this is an hardware issue? My rep has many files, too. I don't know... Maybe you can provide this feature by an option in the repository settings of Fork - default false? So i can switch it on and you can leave this untouched. I think this a really helpful feature. eGit (eclipse) does provide it to. That is the reason for my interest in it.

**Comment by ScriptShot** [comment]
811 781 commits... I see. Thats much.... 
But sometimes it makes sense. Do you have eclipse to try these projects with eGit? I would be interested to know what it looks like then

**Comment by DanPristupov** [comment]
I know, this is an old post and the problem might be already solved, but check this: https://stackoverflow.com/questions/10255403/suggestions-on-optimizing-the-egit-on-eclipse

>  am using EGit on **fairly large and complex** set of Java projects (more than a million line of code) and a decade worth of history. 
> Here I am facing serious performance issues with EGit, as even small one line change in the Java file causes EGit to re-index for couple of minutes which is slowing the entire system.

**Comment by ScriptShot** [comment]
Ok, convinced ... It's an option that is not a good idea for repositories with a long history if you want to work fast. For all those who work on smaller, that's a great feature. 
Thx for the informative discussion 👍

**Comment by DanPristupov** [comment]
Just to explain myself. There are users with very different requirements. Some of them have huge repos, others have lots of images or use sumodules/git LFS/checkout hooks/etc. I'm listening to very diverse feedback and trying to do my best to keep the balance (i.e. introduce new features, which don't make upset the rest of users :) ).

**Comment by ScriptShot** [comment]
You don't have to explain yourself. You make a great job! And i fully understand.

**Comment by ScriptShot** [comment]
For now there are more important things.
