### ISSUE TITLE
How to configure an application password?

### ISSUE THREAD

**Issue by dani-mp** [ForkIssues/Tracker#710]
Hi, I've enabled 2FA for my Bitbucket account and I can't find a way to make my repositories work, I always receive a 403 error. Is it possible to configure an application password?

Thanks.

**Comment by DanPristupov** [comment]
>  I've enabled 2FA for my Bitbucket account
> ...
>  Is it possible to configure an application password?

Most probably yes. Read their docs.

As an alternative you can also switch from HTTPS to SSH protocol.

**Comment by DanPristupov** [comment]
Open BitBucket.org

BitBucket Settings -> App passwords -> Create app password

**Comment by dani-mp** [comment]
I had already created one, I meant how to use it in Fork.

**Comment by DanPristupov** [comment]
Did you try to enter it instead of password?

**Comment by DanPristupov** [comment]
If you need remove old password, open the 'KeyChain access' application and remove the 'Fork.BitBucket.* entry here'.

You can also open Repository Manager (Cmd+T), click on BitBucket and login there.

**Comment by dani-mp** [comment]
It doesn't ask me for it in the first place when doing the clone. I will try that.

**Comment by DanPristupov** [comment]
Most probably it didn't ask you because it used the old password which is stored in KeyChain. Please remove it and try to fetch/clone again.

**Comment by dani-mp** [comment]
Thanks, I didn't know about the Repository Manager.

I made it work logging in again using the app password, and I've also configured a ssh key.

**Comment by DanPristupov** [comment]
Generally speaking, SSH is much easier to use. You generate a key once, add it to all your accounts (GitHub/BitBucket/Work/Home) and never have an authentication problem again.

You can also copy it from one system to another (which is not recommended though).

**Comment by dani-mp** [comment]
Yeah, I had it like that for GitHub but not for Bitbucket (and I don't remember why), and that caused my problems when switching to 2FA.

Thanks again, Fork is a very nice app and it works very well. Do you have a donation page or something?

**Comment by DanPristupov** [comment]
No, not yet but we will add some way soon. Here's more details (https://github.com/ForkIssues/Tracker/issues/562#issuecomment-470288652)
