### ISSUE TITLE
Show output while custom actions are running

### ISSUE THREAD

**Issue by nsh-ableton** [ForkIssues/Tracker#713]
Since some custom actions can take a while, it would be lovely if checking "Show Output" would open the output window right away, and fill it with whatever comes from running the action.

**Comment by DanPristupov** [comment]
I'm investigating this and can't find out why it happens.

May be there's some internal buffer in the output stream/pipe when running another process.

UPD: OK, it looks like the output gets returned exactly after 128 bytes, which seems to be a default size of some buffer

**Comment by DanPristupov** [comment]
OK, I improved the behavior. We are planning to release 1.0.83 tomorrow evening. Please give me some feedback when you get a chance to try it.

**Comment by nsh-ableton** [comment]
Awesome! Will do! Thanks so much!

**Comment by nsh-ableton** [comment]
I've tried this with 1.0.83, but I don't see any difference.

Just for some context: the custom action in question here is a `git push --force-with-lease` command that I added. Since we have a number of git push hooks in place, on a branch with a significant number of commits there can be quite a delay while all the hooks run. So from a terminal, I'll see the `checking X commits` message right away, but there will be a wait before I see the rest. Whereas running the custom action inside Fork, I just see the spinning wheel until all the output is available (at least that's how it seems).

**Comment by DanPristupov** [comment]
Could you test with the following .sh script please?

```
#!/bin/sh

for i in {1..30}
do
   echo "$i   x"
   sleep 0.5s
done

```
Update: here's how it looks on my computer. Everything seems to be fine:
![ezgif com-video-to-gif-6](https://user-images.githubusercontent.com/618115/64076593-1be40f80-ccc7-11e9-8ef2-a27040040c39.gif)

**Comment by nsh-ableton** [comment]
I get something quite different; just re-confirmed I'm running 1.0.83. The output doesn't appear until the whole loop has completed. (Trying to figure out how to convert saved screen capture to GitHub-supported format.....)

**Comment by DanPristupov** [comment]
> Trying to figure out how to convert saved screen capture to GitHub-supported format.....

I used Quick Time Player to record the screen and save as `.mov` and https://ezgif.com/video-to-gif to convert it to `.gif`

**Comment by nsh-ableton** [comment]
Okay, here we go. I had to shorten it to 30 seconds, so the beginning where I show the About box to verify that it's 1.0.83 isn't there 😄
![Fork - custom action console output](https://user-images.githubusercontent.com/7703111/64079501-688c1280-cce8-11e9-8353-5af8b9e82f4f.gif)

**Comment by DanPristupov** [comment]
I might be missing something, but I don't see you opening the activity manager. It doesn't open automatically.

Check, what I'm doing on the video. You must open it manually (i.e. click on the icon in the left-bottom corner on the status control).

**Comment by nsh-ableton** [comment]
Ah! Whoa! 🤦‍♂ I completely missed that. Did not realize that was even a thing. I was only aware of the final output window. Sorry. Now I see it behaving just exactly as you show in the video. I didn't watch it closely enough.

D'oh! Thanks! `:embarrassed:`

**Comment by DanPristupov** [comment]
OK, great. So, as I mentioned previously, please use it for some time and share if it works fine.

Notes:

- Showing the output dialog after running custom action is optional and can be disabled.
- Commit/Fetch/Push operations still use old approach and don't show progress in realtime yet

A few ideas:
- I suppose we can make activity manager more discoverable if we make entire status message clickable (i.e. title + subtitle, when an operation is in progress).
- We can show the active custom action status in realtime in the subtitle (same as fetch/push do)

**Comment by nsh-ableton** [comment]
This seems to work nicely for me, so I think it would make sense to close this issue.

I do like the idea of making the activity manager more discoverable.
