### ISSUE TITLE
Stash in worktree not recognised

### ISSUE THREAD

**Issue by Chadehoc** [ForkIssues/Tracker#715]
I am using Fork with worktrees. Unlike what is said in issue #527, I find that it works acceptably (just open the worktrees as independent repositories and remember you are in a worktree).

However there is a bug with stashes: when done from a worktree, the stash is not shown in the left column. In fact, it is shown only in the primary repository.

However, if I open a console in the initial worktree, commands like `git stash list` or `git stash pop` see the stash normally. Currently it is the only way to use stashes from worktrees (once created).

**Comment by gimbo** [comment]
Just to say I don't see this behaviour today. At least, I have two worktrees vs the same (bare) repo, and when I added a stash in one of them, it showed up in Fork in the other one too — both in the commits list and the sidebar.

So maybe this issue isn't live any more?
