### ISSUE TITLE
Can’t use FileMerge as my external diff tool

### ISSUE THREAD

**Issue by natesilva** [ForkIssues/Tracker#716]
I’ve been unable to use FileMerge as my external diff tool. When I select it in Fork, then request an External Diff, nothing happens. I don’t see FileMerge starting up or any indication that something happened.

* I can select Kaleidoscope or VSCode—both work.
* FileMerge is installed in `/Applications/Xcode.app/Contents/Applications/FileMerge.app`. I’ve also tried copying it to `~/Applications` and `/Applications`.
* In the Fork Preferences dialog, FileMerge has an icon next to it. All the merge apps that I have installed have icons in that list; those that I don’t have installed, don’t have icons.
* macOS 10.14.6, Fork 1.0.82.1, FileMerge 2.11 (14490.5)

**Comment by natesilva** [comment]
So I’ve also been able to duplicate this problem in other Git tools (SourceTree, GitUp). It may be a local problem with my system, or perhaps it’s related to the latest version of Xcode. I wonder if anyone else has a similar problem?

**Comment by DanPristupov** [comment]
Fork runs FileMerge using `/usr/bin/opendiff` runner.

1. Please ensure that your xCode command line tools are installed
2. Run xCode and check if some EULA awaits for a confirmation (all the xcode cli-tools will be blocked until that).

**Comment by natesilva** [comment]
Thank you.

**Short version (the fix):**

```shell
$ sudo xcode-select --reset
```

**Long version:**
As far as I could tell the command line tools were installed. There was no EULA that needed to be confirmed.

When I tried to run `/usr/bin/opendiff` it reported:
```
xcode-select: error: tool 'opendiff' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

I don’t know what this error means, but running `sudo xcode-select --reset` fixed it.

Hopefully this information can be of use to anyone else having this problem.
