### ISSUE TITLE
Sometimes it shows blank repo

### ISSUE THREAD

**Issue by ithieund** [ForkIssues/Tracker#718]
Sometimes when I start the app end click an repo from recent list, it shows a blank window
When I try to click on the left column, it display the commit description on the right, but now file shows.

![image](https://user-images.githubusercontent.com/4217195/63661337-5f7cdc00-c7e4-11e9-9904-7e756b8abda8.png)

**Comment by DanPristupov** [comment]
Does the log file (`~/Library/Caches/Fork/fork.log`) contain any error?
