### ISSUE TITLE
Can't abort a rebase that isn't in progress anyway

### ISSUE THREAD

**Issue by stacey-gammon** [ForkIssues/Tracker#721]
I can't seem to get out of this "Rebasing branch 'master' onto ''. message and it doesn't let me commit through fork.  Clicking `Abort` button does nothing, also trying to abort via command line does nothing. I imagine there is some random file I need to delete to clear out this bad state, but I'm not sure what it is.

Doesn't seem to matter what branch I am on:
<img width="1679" alt="Screen Shot 2019-08-27 at 9 08 02 AM" src="https://user-images.githubusercontent.com/16563603/63774031-61a96e00-c8aa-11e9-9465-974da3550c32.png">
<img width="842" alt="Screen Shot 2019-08-27 at 9 09 18 AM" src="https://user-images.githubusercontent.com/16563603/63774033-61a96e00-c8aa-11e9-98ba-b0402d126507.png">

No rebase in progress:
<img width="630" alt="Screen Shot 2019-08-27 at 9 08 09 AM" src="https://user-images.githubusercontent.com/16563603/63774032-61a96e00-c8aa-11e9-98b8-bf57103fc38d.png">

Not able to commit via Fork, but can do so via command line.
<img width="884" alt="Screen Shot 2019-08-27 at 9 11 15 AM" src="https://user-images.githubusercontent.com/16563603/63774167-aaf9bd80-c8aa-11e9-8681-a59bb910fdea.png">

**Comment by DanPristupov** [comment]
Is there a `.git/rebase-merge` directory? If so, remove it.

**Comment by stacey-gammon** [comment]
Ah, yes indeed, thanks so much.  Didn't notice github was looking for the more specific `.git/rebase-merge/*head_name*`.
