### ISSUE TITLE
[Feature Request] Parse and trim input URLs when cloning repository

### ISSUE THREAD

**Issue by aaronmorgan** [ForkIssues/Tracker#722]
Some source repository dashboards provide more than just the URL to a repository when choosing to clone it, e.g. BitBucket pushes the repository URL prefixed with `git clone ` to the clipboard.

When this is pasted into Fork the textbox isn't wide enough to show the full repository URL and the prefix can remain hidden. Clone attempts then report a git error, `too many arguments`.

It would be nice if Fork checked for such prefixes and trimmed the string pasted into the Clone field to just the URL. In a way helping get the user out of their own way :)

**Comment by DanPristupov** [comment]
This is done in 1.0.85.
