### ISSUE TITLE
[Feature Request] add pull request support

### ISSUE THREAD

**Issue by chenjiangui** [ForkIssues/Tracker#723]
the other git client like tower, gitkraken, smartGit provide it.  i can not leave pull request in custom host gitlab.

**Comment by DanPristupov** [comment]
<img width="631" alt="Screenshot 2019-08-28 at 07 50 18" src="https://user-images.githubusercontent.com/618115/63828987-7d734980-c968-11e9-9e48-7c518e6870fa.png">

**Comment by chenjiangui** [comment]
fork only support gitlab,  the custom host of gitlab is not support, like this
![image](https://user-images.githubusercontent.com/18565140/63830026-a4983e00-c99d-11e9-923c-92b6fb463e50.png)

**Comment by chenjiangui** [comment]
tower,  gitkraken can support custom host of gitlab

**Comment by ghost** [comment]
Please also add support for Bitbucket (on premises and cloud)
