### ISSUE TITLE
[Feature Request] Push multiple branches at once

### ISSUE THREAD

**Issue by jasperkuperus** [ForkIssues/Tracker#724]
Again. I love Fork. There's only 1 feature I miss, that SourceTree did have.

Every once in a while, I merge and rebase a few branches to get everything sorted again. Then when I'm done, I wish to push multiple branches. In Fork, I have to check out the first branch, push the first branch, check out the second branch, push the second branch, etc. In SourceTree you're able to push all branches that have something to push at once:

![Screenshot 2019-08-16 at 13 16 51](https://user-images.githubusercontent.com/1655683/63839882-65a7bf80-c980-11e9-804c-f3d30be0c4d9.png)

**Comment by DanPristupov** [comment]
Hi. In 1.0.86 we added ability to push multiple branches at once as a context menu option on the sidebar.

<img width="456" alt="Screenshot 2019-11-08 at 18 00 45" src="https://user-images.githubusercontent.com/618115/68496025-b1fd5e80-0251-11ea-81ca-3d5d04b9ce36.png">

**Comment by jasperkuperus** [comment]
Awesome, thanks!

**Comment by DanPristupov** [comment]
I didn't want to bloat the push dialog with a table, so we introduced the context menu item.

**Comment by jasperkuperus** [comment]
Works for me, but it can be a bit hard to find for people.

**Comment by DanPristupov** [comment]
Yeah, I agree. However I think the location is consistent with the 'Delete multiple branches' and 'Push tag' features which are also a bit hidden.

**Comment by fo-fo** [comment]
Any chance for a "Force push" option for the multi-branch push dialog? It could come in handy in "branch on branch" scenarios, when using rebase with `--update-refs`.

Alternatively, maybe something like a "Push dependent branches" option when pushing a branch, similar to the "Update dependent branches" checkbox in the rebase dialog.

**Comment by DanPristupov** [comment]
> Any chance for a "Force push" option for the multi-branch push dialog?

I'm not sure... We are usually very careful about such things. Likely, not in the near future.
