### ISSUE TITLE
Can't split screen between 2 Fork windows in latest update

### ISSUE THREAD

**Issue by matkatmusic** [ForkIssues/Tracker#727]
Running OS X 10.13.16, 
Fork v1.0.83

The previous version allowed 2 instances of Fork windows to split the monitor in Kiosk/Full-Screen mode.  Now we can't do that.  

My use-case is a bit of an edge case, I have 2 windows open of the same repository, and I'm am cherry-picking commits from one branch in a remote, to my local branch.  I have one window showing the changes so I can tackle any conflicts that require external merge.  The other window is showing the remote commits. 

<img width="840" alt="Screen Shot 2019-08-31 at 10 54 15 AM" src="https://user-images.githubusercontent.com/2929847/64067490-1232ad00-cbde-11e9-9dfd-91200e0a16f3.png">

**Comment by DanPristupov** [comment]
What should I do to reproduce the problem?

**Comment by matkatmusic** [comment]
if you click-hold the green Full-Screen button, you can full-screen an app into one half of the screen.  

Make 2 Fork windows (File -> New Window)
click-hold the green full-screen button on one of them.  
select which side of the screen you want it to appear. 
on the other half of the screen, you can pick another app window to occupy the other half of the screen.  
OS X will not let you select the 2nd Fork window.

**Comment by DanPristupov** [comment]
Most probably I reproduced the problem. And yes, 1.82 seems to not have this problem (you can download it here: https://forkapp.ams3.cdn.digitaloceanspaces.com/mac/Fork-1.0.82.1.dmg).

This is very strange, because I'm sure I didn't change anything related (most probably I'm wrong ;) ).

**Comment by matkatmusic** [comment]
awesome.  thank you for looking into it and confirming it.  Maybe it has to do with the minimum window width?

**Comment by DanPristupov** [comment]
Please download 1.0.83.1 manually. The problem must be fixed there: https://forkapp.ams3.cdn.digitaloceanspaces.com/mac/Fork-1.0.83.1.dmg
