### ISSUE TITLE
[Clarify] Multi-Cherry Pick functionality

### ISSUE THREAD

**Issue by matkatmusic** [ForkIssues/Tracker#728]
When I select a bunch of commits in sequence to cherry pick between branches, I get this error: 

<img width="676" alt="Screen Shot 2019-08-31 at 4 36 44 PM" src="https://user-images.githubusercontent.com/2929847/64070066-a1a38480-cc0d-11e9-8d64-41125bda18e1.png">

What is the secret to getting this feature to work?

**Comment by DanPristupov** [comment]
Like it says it looks like there's some other cherry pick in progress. This might appear if you had a conflict.

To fix, open terminal (cmd+shift+t) and run `git cherry-pick --abort`.

I will investigate to handle this properly

**Comment by DanPristupov** [comment]
I released 1.0.83.1 hotfix. You can download it manually here: https://forkapp.ams3.cdn.digitaloceanspaces.com/mac/Fork-1.0.83.1.dmg
