### ISSUE TITLE
[Bug] Overlapping buttons in Stash uncommitted changes dialog

### ISSUE THREAD

**Issue by zelenomodrypes** [ForkIssues/Tracker#729]
Hi,

I can't read text on first button in Stash uncommitted changes dialog:

![Screenshot 2019-09-02 09 18 13](https://user-images.githubusercontent.com/755065/64097715-44bae200-cd65-11e9-9357-a13edeefe657.png)

(OS X El Capitan 10.11.6)

**Comment by DanPristupov** [comment]
It works fine on 10.14.
Not sure if I'll be able to fix this because I don't have an access to macOS 10.11.

**Comment by zelenomodrypes** [comment]
Also on 10.12 it works fine.
Is there a way I can help you with that?
