### ISSUE TITLE
Feature Request: Multi-funnel

### ISSUE THREAD

**Issue by martin82** [ForkIssues/Tracker#73]
I'm a big brancher and something I would find very useful is the ability to select multiple branches or even entire folders of branches (i.e. "features/*") in the sidebar for funneling.
Say I want to focus the main commit view on feature branches only and hide all branches not "backwards reachable" from any feature branch.
A less complex version of this feature may be to just allow hiding of tags, stashes and / or remote branches.

**Comment by DanPristupov** [comment]
Hi,

Thank you for the idea. I'll think about it during the upcoming pinned branches implementation: https://github.com/ForkIssues/Tracker/issues/15

**Comment by DanPristupov** [comment]
@martin82 
I implemented multi-funneling and it's available in 1.0.59.4 prerelease (#152)!

**Comment by martin82** [comment]
Just tried it out, exciting! Thanks! You can definitely close this request.
