### ISSUE TITLE
[Issue] : Getting permission denied on latest version (1.0.82.1)

### ISSUE THREAD

**Issue by prsh9** [ForkIssues/Tracker#733]
Getting below error with the latest update 1.0.82.1
Older version was working fine

------
git@\<github enterprise host>: Permission denied (publickey).

fatal: Could not read from remote repository.

------

On Mac OS, and git commands are working fine using Terminal

**Comment by DanPristupov** [comment]
Open Open KeyChain Access application, find `SSH:/path/to/your/key` entry and either remove it or ensure Fork has access to it. Then fetch again

**Comment by prsh9** [comment]
Thanks ! Somehow updating Fork (or something else) messed up KeyChain entries. It is working now
