### ISSUE TITLE
Pushing branch doesn't show Force option

### ISSUE THREAD

**Issue by peterfox** [ForkIssues/Tracker#734]
In previous versions I used to be able to do a push on a branch and it would ask me if I want to do a force push before continuing. I no longer get this prompt or see an option to be able to do a force push.

**Comment by DanPristupov** [comment]
Most probably Fork doesn't show push dialog if you call it from the context menu.

You can still open Push dialog by clicking on the icon on the toolbar.

**Comment by peterfox** [comment]
It feels like a weird change to me, I liked being able to do it from clicking on the branch and pushing as it meant I could do it quickly while not being on that branch. I can get used to it though. I assume it wouldn't be added as an option to turn on or off?

**Comment by DanPristupov** [comment]
Sorry, I forgot to mention, that you can hold alt/option to open that dialog.

**Comment by peterfox** [comment]
Ok, that will do for me, thank you for your help 👍

**Comment by DanPristupov** [comment]
I rolled back those changes. We need to think more about the 'silent mode'
