### ISSUE TITLE
Strange thin lines rendered on diff output 

### ISSUE THREAD

**Issue by mihaicris** [ForkIssues/Tracker#735]
I see some thin darker lines in the diff output, click to enlarge. Is it only on my machine?
Fork version: 1.0.83.1 
<img width="351" alt="Screenshot 2019-09-05 at 13 41 33" src="https://user-images.githubusercontent.com/5946912/64335391-61644d80-cfe3-11e9-95d7-f627f83e51c1.png">

**Comment by maksimovic** [comment]
Strange, I see those lines in some diffs, not all of them.

<img width="483" alt="Screenshot 2019-09-05 at 13 30 23" src="https://user-images.githubusercontent.com/1126226/64338201-704a0080-cfe1-11e9-8972-64bae4b49b56.png">
<img width="369" alt="Screenshot 2019-09-05 at 13 29 40" src="https://user-images.githubusercontent.com/1126226/64338202-70e29700-cfe1-11e9-8e37-56ddbee70550.png">
<img width="282" alt="Screenshot 2019-09-05 at 13 29 22" src="https://user-images.githubusercontent.com/1126226/64338203-70e29700-cfe1-11e9-8196-5723ab73a2f8.png">

**Comment by DanPristupov** [comment]
No, everyone see that. https://github.com/ForkIssues/Tracker/issues/466
