### ISSUE TITLE
Missing fast-forward pull for `master` and other branches

### ISSUE THREAD

**Issue by dbart01** [ForkIssues/Tracker#736]
Previous version of Fork had a convenient `Fast-foward pull 'master'` option when right-clicking a branch in the sidebar. That option is no longer available.

<img width="362" alt="Screen Shot 2019-09-10 at 7 08 06 AM" src="https://user-images.githubusercontent.com/5244861/64609132-35a5e680-d39a-11e9-82de-a734d82f5c0b.png">

Above version: 1.0.83.1

**Comment by DanPristupov** [comment]
Can you see it in context menu  in commit list?

**Comment by DanPristupov** [comment]
We replaced 'fast-forward pull' with 'fast-forward' (i.e. without fetch).

It should be visible when remote branch is ahead of local.

<img width="454" alt="Screenshot 2019-09-10 at 13 15 06" src="https://user-images.githubusercontent.com/618115/64609317-03fa4300-d3cd-11e9-871f-a74fc78e407d.png">

**Comment by dbart01** [comment]
No, not visible in commit list either.

<img width="564" alt="Screen Shot 2019-09-10 at 7 15 16 AM" src="https://user-images.githubusercontent.com/5244861/64609344-c54b9500-d39a-11e9-8597-235358db0d73.png">

**Comment by dbart01** [comment]
`Fast-forward` doesn't serve the same purpose. If I'm on a feature branch and I need to pull `master` to rebase a feature branch, `fast-forward` won't help. I also don't see the `Fast-forward` option.

**Comment by DanPristupov** [comment]
Does `master` have a tracking reference? You can check that in tooltip on the sidebar.

**Comment by dbart01** [comment]
Yes, it does.

<img width="351" alt="Screen Shot 2019-09-10 at 7 26 29 AM" src="https://user-images.githubusercontent.com/5244861/64610035-553e0e80-d39c-11e9-9e39-7b5ebe7793a0.png">

**Comment by DanPristupov** [comment]
Do you have an enabled filter may be?

**Comment by DanPristupov** [comment]
Do any other local branches have the fast-forward option?

I checked the source code, the menu item can be hidden if corresponding remote branch doesn't exist or points to the same commit as the local branch. Could you check if 'origin/master' has a checkmark in the 'tracking' submenu?

<img width="596" alt="Screenshot 2019-09-10 at 13 53 49" src="https://user-images.githubusercontent.com/618115/64611739-6d308500-d3d2-11e9-890c-73c8fae22326.png">

**Comment by dbart01** [comment]
No filters and checkmark is present. Your comment about pointing to the same commit gave me an idea. Doing a fetch updates the remote `master` branch and reveals the `Fast-forward to 'origin/master'`:

![Screen Shot 2019-09-10 at 8 11 50 AM](https://user-images.githubusercontent.com/5244861/64612797-ab15b500-d3a2-11e9-8900-b0c00fffae9e.png)

But it is disabled. I can no longer fast-forward pull `master` while checked out on a feature branch. **This was the best feature**.

**Comment by DanPristupov** [comment]
Did you understand why it had become visible?
It's probably disabled because fast-forward is not possible? Isn't that so?

**Comment by dbart01** [comment]
I can't fast-forward the _current_ branch to `origin/master`, yes. I suspect that is what Fork is expecting. However, a few versions ago (or the previous version?) I was able to pull the `origin/master` into `master`, _while_ on a different branch. Doing so saves a lot of time. Without it I have to:

1. Stash or commit local changes on feature branch
2. Checkout `master`
3. Pull `master`
4. Checkout feature branch
5. Re-apply stash

With fast-foward pull I was able to do it all in one step:

1. Fast-forward pull `master`

**Comment by dbart01** [comment]
> Did you understand why it had become visible?

Yes, previously `master` had no new commits. Doing a fetch revealed new commits and made `Fast-foward` option visible (but disabled).

**Comment by DanPristupov** [comment]
> However, a few versions ago (or the previous version?) I was able to pull the origin/master into master, while on a different branch.

Only (!) if fast-forward was possible. I.e. only if your local branch didn't contain new commits. Otherwise there would be an error that fast-forward is not possible.

**Comment by dbart01** [comment]
I'm not sure I understand. My current `master` branch _can_ perform a fast-forward pull. It's a strict subset of `origin/master` and doesn't have any conflicting commits.

**Comment by DanPristupov** [comment]
Can you show a screenshot please?

**Comment by dbart01** [comment]
The last screenshot is still what I'm seeing but perhaps I'm not explaining my intentions clearly. This is the use case that was previously possible. After updating Fork this feature has vanished.

- `origin/master` is 23 commits ahead
- My current branch is `feature-123` and it is 3 commits ahead of `master` but behind `origin/master`. A rebase is required.
- Previously, I was able to `Fast-forward 'master' to 'origin/master'` _without_ leaving `feature-123` branch via right click (as seen in the last screenshot) and perform an interactive rebase after the pull completed.
- Now, the current flow requires me to leave my current branch, checkout `master`, pull, checkout feature branch and then rebase.

What is preventing me from pulling `master` _without_ leaving my current branch?

**Comment by DanPristupov** [comment]
Show me a screenshot which shows 'master' and 'origin/master' locations.

**Comment by dbart01** [comment]
Ohh I think I found the problem. If `Hide remote branches in commit list` is enabled, `master` doesn't appear to recognize that there are new commits (even if theres a "new commits" count to the right of the branch). As soon as I enabled the remote branches in commit list, the `Fast-forward` option became enabled.

**Comment by dbart01** [comment]
Previously, `Hide remote branches in commit list` didn't affect the state of the `Fast-forward` option.

**Comment by dbart01** [comment]
I would still consider this an issue. I should be able to fast-forward pull a (non-checked out) branch with remote branches hidden.

**Comment by dbart01** [comment]
Looks like this has been fixed in `1.0.84` ❤️
