### ISSUE TITLE
Right-click 'Push X to Y' pushing to wrong repo

### ISSUE THREAD

**Issue by kdambekalns** [ForkIssues/Tracker#737]
When right-clicking on a branch name in the tree on the right and selecting "Push > Push X to Y" the push is made to "origin", not "Y". Quite annoying (and potentially dangerous!)

Using the "regular push dialog" it works fine.

**Comment by DanPristupov** [comment]
Thank you very much for the bug report.

**Comment by DanPristupov** [comment]
I've just released the 1.0.83.**2** hotfix. Please check for updates (Application Menu -> Fork -> Check for updates)

**Comment by kdambekalns** [comment]
I only get 1.0.83.2 when checking for updates, but it includes the fix – and it works. Thanks!

**Comment by DanPristupov** [comment]
Yes, you are right. It's 1.0.83.2. Sorry for the typo.
