### ISSUE TITLE
Ignoring whitespace still shows whitespace changes in line

### ISSUE THREAD

**Issue by cwensley** [ForkIssues/Tracker#738]
When you have ignore whitespaces turned on, it still shows whitespace changes such as a space inserted/removed before a bracket or curly brace.  E.g.

<img width="526" alt="Screen Shot 2019-09-11 at 9 39 28 AM" src="https://user-images.githubusercontent.com/367446/64716945-38770900-d478-11e9-96d2-9e6d15d4f81e.png">

and 

<img width="455" alt="Screen Shot 2019-09-11 at 9 41 17 AM" src="https://user-images.githubusercontent.com/367446/64717009-53497d80-d478-11e9-8931-27a579658f3c.png">

I think at one point Fork didn't do this, so it would be nice if these spaces were also ignored or at least have an option to make them ignored... like "really ignore whitespace". 😁

Thanks for Fork btw, it is the best git client by _far_ on either Windows or Mac imo.

**Comment by DanPristupov** [comment]
Hi. Fork uses `--ignore-space-change` [mode](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt-ignore-space-change):
> ignore-space-change
> Ignore changes in amount of whitespace. This ignores whitespace at line end, and considers all  other sequences of one or more whitespace characters to be equivalent.

Full `ignore whitespaces` will make partial staging error prone, because git won't be able to recognize many chunks.
