### ISSUE TITLE
Staging lines often stages extra lines

### ISSUE THREAD

**Issue by aaroncrespo** [ForkIssues/Tracker#74]
![screen shot 2017-08-03 at 10 03 20 am](https://user-images.githubusercontent.com/431662/28925492-131325de-7833-11e7-8f15-afa5a43891c2.png)

Pretty frequently the above stage operation will stage both the addition and the subtraction when only one was selected.

**Comment by DanPristupov** [comment]
@aaroncrespo I've reproduced the problem. Will fix it soon. Thanks

**Comment by DanPristupov** [comment]
@aaroncrespo this is fixed in Fork 1.0.54 which I just released. Please update.
