### ISSUE TITLE
[Feature Request/Issue] Authentication via HTTPS

### ISSUE THREAD

**Issue by nasserabdullah** [ForkIssues/Tracker#743]
If your git repo's remote url is set to something like:
https://github.com/<someone>/<something>.git
instead of git@github.com:<someone>/<something>.git

No remote git operations work e.g. git pull, fetch, push etc. 

It would be great if https could be supported.
Or at least throw an error/alert, it keeps on spinning at the moment.

**Comment by DanPristupov** [comment]
I'm not sure what 'don't work' means, but ensure that you didn't enter incorrect password. Open KeyChain Access application and remove the Fork.servername* entry.
