### ISSUE TITLE
Re-orderable custom actions

### ISSUE THREAD

**Issue by nsh-ableton** [ForkIssues/Tracker#749]
I'd love to be able to re-order my custom actions. Short of that, if they're stored in an easily-editable file, I'd be glad to know where that is, so I can manually re-order them. 😄

**Comment by DanPristupov** [comment]
I see. We need to allow to change the order.

Currently we keep them in UserDefaults which is a closed format.

We should probably rework the whole custom command subsystem in the future. I'd like to ask a few related questions:

* Would you find it useful if we store CAs in a text file (similar to the `issuetracker` file).
* Would you like to be able to copy/share custom actions?
* Would you like to have local (per-repository) custom actions?

And a separate one:
* Would you like to have parametrized custom actions? For example: a custom action that prompts a local branch and a remote which will later available as parameters

**Comment by nsh-ableton** [comment]
A big yes to all four questions! 😄

**Comment by DanPristupov** [comment]
I made custom actions sorted in 1.0.84. This is at least a bit better than the unsortered order.

In addition to this 1.0.84 contains some related improvements:
* Quick Launch (⌘P) with ability to call custom actions
* Branch custom actions
* Combination of previous features allows to call a custom action and select a branch from the proposed list

**Comment by nsh-ableton** [comment]
These sound like great improvements. Unfortunately, I'm not seeing my custom actions sorted (I assume you mean alphabetically):
<img width="240" alt="Screen Shot 2019-09-23 at 14 02 46" src="https://user-images.githubusercontent.com/7703111/65424076-eb494e80-de0a-11e9-9ecb-e5b80abd5b72.png">

**Comment by DanPristupov** [comment]
They are sorted on save. Please try to edit one in preferences.

**Comment by nsh-ableton** [comment]
Yes indeed! They are indeed sorted after I've edited one.

**Comment by nsh-ableton** [comment]
So, I really like the changes you made, especially the Quick Launch.

If I want to sync my custom commands to another machine, is/are there a file/fiiles that I can copy over?

**Comment by DanPristupov** [comment]
No, unfortunately I don't know a way to export the settings easily. Currently Fork uses UserDefaults as a storage and it's not possible to copy it (AFAIK).

We need to improve this and migrate to either git config or a json format, but I don't know which one is better. Git config is easier to read but json is more flexible.

If you really need this, I can create some workaround to export/import in the next update. Otherwise those changes are planned on ~ end of Dec-Jan.

**Comment by nsh-ableton** [comment]
Nothing urgent here, just thinking about what would be nice. It's interesting that you mention a git config format — I hadn't even considered that. So the idea would be that the commands would also exist as git aliases? Or how would that work?

**Comment by carlosefonseca** [comment]
I've been looking for how to backup and restore the custom commands and I found this thread. I also found that the custom commands are now stored in `~/Library/Application Support/com.DanPristupov.Fork/custom-commands.json`. It might be useful for someone else looking for this.

**Comment by DanPristupov** [comment]
In 2.27 we introduced nesting for custom commands using `/` as a folder separator. For example, you can create `Build/Start` and `Build/Run Tests` custom commands and have a `Build` submenu with `Start` and `Run Tests` items.

As a side-effect, now custom commands are always sorted alphabetically.
