### ISSUE TITLE
Unified behavior of the default buttons (confirmation buttons)

### ISSUE THREAD

**Issue by tflo** [ForkIssues/Tracker#751]
The confirmation button for commits responds to <kbd>⌘</kbd><kbd>Return</kbd> and to <kbd>fn</kbd><kbd>Return</kbd> (= Enter), whereas other default buttons (e.g. in the Fetch or LFS Track dialogs) don’t seem to respond to <kbd>⌘</kbd><kbd>Return</kbd>.

I would prefer to see a more unified behavior here.

(Since <kbd>⌘</kbd> is easier to press than <kbd>fn</kbd> I’ve taken the habit to confirm my commits with <kbd>⌘</kbd><kbd>Return</kbd>, and my fingers now always try to do the same in other dialogs…)

***

Slightly related question: Is it possible to fetch without opening the dialog?

**Comment by DanPristupov** [comment]
Submit on Cmd+Return is a common behavior in views with multiline fields:

* Mail
* Messages
* Skype
* The GitHub comment field you just have typed
* etc

>  Is it possible to fetch without opening the dialog?

There used to be option+click behavior (or Cmd+Option+Shift+F), but it seems to not work now. I'll check why.

**Comment by tflo** [comment]
> Submit on Cmd+Return is a common behavior in views with multiline fields:

OK, seems consistent from this point of view. Have to educate my fingers then ;)

> There used to be option+click behavior (or Cmd+Option+Shift+F), but it seems to not work now. I'll check why.

Thanks for investigating. Similar with Pull, I guess.

**Comment by DanPristupov** [comment]
In 1.0.85 we returned Quick Fetch and Quick Pull (hold alt/option key)
