### ISSUE TITLE
Fuzzy search in Quick Launch command palette (⌘P)

### ISSUE THREAD

**Issue by infotexture** [ForkIssues/Tracker#755]
The Quick Launch menu command palette (⌘P) introduced in Fork 1.0.84 is a great start and already super helpful.

One thing that would make it better though would be to align the implementation with similar features in other tools like Sublime Text and Virtual Studio Code, which support "fuzzy search" (approximate string matching) in the command palette.

This would make it much easier to open something by entering any of the characters in the item's name, rather than the exact string.

So for example, *File History* could be invoked just by typing `FH`, instead of `FILE H` or `HIST`.

See also related "fuzzy search" issues:
- https://github.com/ForkIssues/Tracker/issues/531
- https://github.com/ForkIssues/Tracker/issues/694

**Comment by DanPristupov** [comment]
Thank you for the feature request! I implemented fuzzy search in 1.0.85.

> So for example, File History could be invoked just by typing FH, instead of FILE H or HIST.

<img width="517" alt="Screenshot 2019-10-18 at 14 52 17" src="https://user-images.githubusercontent.com/618115/67095704-e338c080-f1b6-11e9-9c57-2dfcaf2297b3.png">
