### ISSUE TITLE
Feature Request: 'Open in MyMostFavoriteEditor'

### ISSUE THREAD

**Issue by dmay** [ForkIssues/Tracker#76]
That would be great to be able to open repository folder in some predefined app. And absolutely perfect if the app (and an object to open) can be re-defined for specific repositories.

User story:

> I have 10 repositories, with projects of various kind and nature.
> 
> For 7 of them, I every time do 'Open in Terminal' > 'vscode' > folder is opened in VS Code.
> Instead of it I would like to press a button in the toolbar 'Open in VS Code' and go straight to work.
> 
> The other 3, however, hold XCode projects. So for them I would like to press a button in the toolbar to get XYZ.xcodeproj opened in XCode.
>

**Comment by DanPristupov** [comment]
@dmay Hi. Sorry for the delay. This sounds like a reasonable request, but I'm not sure how to implement in a way people really use it. Do you know any application example where such functionality is implemented and works nicely?

Here is what I personally do in such case:
- open some repository
for application with projects (like xcode project):
- click `open in` -> `show in finder`
- double click on the project file

for application without projects (like nodejs app):
- click `open in` -> `open in terminal`
- type a command, like `start node.js` or something. You can type there `code .` to open the directory in VSCode.

This is very flexible and covers 95% of project types.

**Comment by dmay** [comment]
> Do you know any application example where such functionality is implemented and works nicely?

VS Code itself :) Their `.vscode/tasks.json` is a real THING.

> This is very flexible and covers 95% of project types.

This request is about getting rid of those additional steps after 'Click `open in`'. Not a deal-breaker, but could improve developers' quality of life :)

I believe that for properly configured and prepared project developer should (almost) never see it in Finder or even in Terminal. You access repos through git client MRU list, projects through IDE MRU list, all build/pack/deploy/whatever operations are scripted and available in IDE at shortcuts. Only downside is when you need to poke some actual files in Finder and can't remember where exactly it located :)

This feature would eliminate need of IDE MRU (VS Code MRU simply sucks), need of IDE be kept in the Dock, need to think in one more place where it's not necessary :)

An idea how it could be implemented, mimicking VS Code approach:
Fork looks for `.fork/tasks.json` file in repo. File contains list of 'tasks' - name + command to execute. + probably icon to display on the toolbar. 
Toolbar introduces new pull-down button which lists all tasks from the file OR executes the first one if it's single.

**Comment by DanPristupov** [comment]
I implemented ability to open repository in Sublime, VSCode and Atom in 1.0.67
