### ISSUE TITLE
Feature: Visual improvements of the left column

### ISSUE THREAD

**Issue by svoop** [ForkIssues/Tracker#760]
The left column is rather hard to navigate due to missing visual anchors. Furthermore, local and remote branches usually have similar or identical names which doesn't help. Here are a few ideas to improve this:

* On 99.5% of the repos, the `master` branch is most important, hence the name. It should always be listed on top above all other.
* Directories should be listed below the `master` branch but above all other branches (dupe of #621).
* Root elements of this tree should be separated visually.

As an example, the before and after of a possible implementation. (I'm no UI specialist, so those who are, please chime in with better suggestions.)

Before:

<img width="307" alt="Screen Shot 2019-09-30 at 13 42 51" src="https://user-images.githubusercontent.com/7255/65875788-47bae980-e388-11e9-9c20-43a13dd8b0e2.png">

After:

<img width="307" alt="Screen Shot 2019-09-30 at 13 42 51" src="https://user-images.githubusercontent.com/7255/65882354-26acc580-e395-11e9-940d-ecb9464aee3e.png">

* Top level lines have a bigger font, bold and underlined
* Additional whitespace above top level lines
* Branches ordered as master first, directories (alphabetically) and branches (alphabetically)

**Comment by DanPristupov** [comment]
First of all this doesn't looks like a common visual approach used in macOS.

> Top level lines have a bigger font, bold and underlined

Ideally we must use the same style as in Finder, however we use an other one because of a bug in macOS which draws such headers incorrectly in dark theme in macOS < 10.13. May be we can finally disable dark theme for such people (there's about 3% of them).

The rest of issues are very individual. Fork had `master and folders first`, but many people reported that their branches are sorted incorrectly I rolled the changes back.

**Comment by svoop** [comment]
You're right. However, whitespace above top level lines do, see Mail.app:

<img width="224" alt="Screen Shot 2019-09-30 at 15 36 33" src="https://user-images.githubusercontent.com/7255/65883932-41346e00-e398-11e9-8661-1ab5c0901588.png">

As for the sorting, I'm a little biased since I've just switched from Tower which some years ago introduced the "master, directories, branches" order which I personally found a big step forward. But of course, other's mileage may vary – maybe the sorting would make a useful preference?

**Comment by maksimovic** [comment]
Could showing the master branch on top (or master/directories/branches) be a config option in Fork's preferences?

I'm kinda used to having master now in the middle of whatever list, but I must admit that I miss the previous implementation.

**Comment by DanPristupov** [comment]
@maksimovic what about folders?

**Comment by maksimovic** [comment]
My personal preference would be the same as @svoop suggested:
- `master`
- `dir`
  - `something`
  - `something-else`
- `branch-a`
- `branch-b`
- `branch-n`

This (in some way) mimics the sorting I've always been used to (file managers), where directories are always listed first. I know Apple has different opinion, but even Finder now allows setting folders to be on the top when sorting by name.

**Comment by DanPristupov** [comment]
Any idea how we can call such option? 'Keep folders and master on top' is too long.

> but even Finder now allows setting folders to be on the top when sorting by name.

it seems that they even fixed the bug in jumping to a directory by typing first letters of the name.

**Comment by svoop** [comment]
Maybe "Sort branches by type" or "Master and folders on top"?

**Comment by DanPristupov** [comment]
I forgot to mention that now we have the following menu ('Recently used' is used for tags):
<img width="334" alt="Screenshot 2019-09-30 at 16 20 58" src="https://user-images.githubusercontent.com/618115/65887497-4b596b00-e39e-11e9-9190-a17785a9159f.png">



So, could it be like following?

* Alphabetically
* Alphabetically, master and folders on top
* Recently used

I suppose we can avoid the 'Recently used + folders on top' combination.

**Comment by svoop** [comment]
Looks awesome to me.

**Comment by maksimovic** [comment]
> Alphabetically, master and folders on top

That'd be great!

**Comment by DanPristupov** [comment]
OK, good.

Not sure if we can make `Alphabetically, master and folders on top` default. I'm afraid of the people anger :).

UPD: 💡We'll make it default for the new users only! They don't know how it worked before ;).

**Comment by svoop** [comment]
> UPD: 💡We'll make it default for the new users only! They don't know how it worked before ;).

Good idea!

**Comment by maksimovic** [comment]
:D yes, that's a good idea. Whatever the initial implementation is, once you change it people will complain, no matter how good or bad it was. Habits are hard to change 🙃

**Comment by DanPristupov** [comment]
Alright, here you are (1.0.85):
<img width="407" alt="Screenshot 2019-10-18 at 14 47 34" src="https://user-images.githubusercontent.com/618115/67095450-39f1ca80-f1b6-11e9-896e-47cf89bfe4c8.png">

**Comment by svoop** [comment]
Cool, thanks a lot! 🎉

**Comment by svoop** [comment]
@DanPristupov Could the same sorting be applied to the "Starred" section as well? I don't think it makes much sense to have a second sort selection there, just applying the sort selection from "Branches" to "Starred" as well would be the expected behavior – at least to me.

**Comment by maksimovic** [comment]
Why is the active branch pushed to the top of the list now?

The point of sorting is to have a predictable, stable list - from my point of view at least.

Now, if i need to chase list items around every time I switch a branch, then it's not really an improvement.

Also, when the sorting is set to "Recently used", then the selected branch stays in its place (not pushed to the top of the list). So it's inconsistent as well. However, I don't like this sorting type as it's changing the order of of branches all the time.

**Comment by DanPristupov** [comment]
@maksimovic could this be a habit problem? I used the new sort order for 2 weeks and was 100% happy with it. If it isn't, I'll remove the active branch from the first position in the next update.

**Comment by maksimovic** [comment]
Perhaps it's a habit in part, too. I expected to be able to have a new sorting method, instead got that + something I've never preferred (not related to Fork only, just any sort of list that changes after I select an item in it is... annoying _to me_).

However, I imagine that someone who has really a lot of branches in that list could be pissed off as well - the list scrolls up every time you switch a branch, in addition to actually **moving** a branch from its place.

Also, it's contradicting the "master and folders on top", because e.g. `master` is on top only if you actually switch to it. Otherwise it's always 2nd, which isn't really the top 😁 

No need to undo something or make it exist for 1 person, by the way. I'm just expressing my own thoughts on this :D Maybe wait for others to upgrade and see if the eggs will be flying your way.

**Comment by svoop** [comment]
@DanPristupov Sounds good, I'll give it a fair try as well. At first glance, I tend to agree with @maksimovic though (it goes against POLA – principle of least surprise). However, if it proves to be useful like that, other sections such as "Starred" should behave consistently IMO.

**Comment by DanPristupov** [comment]
As I initially said this feature is quite controversial :).

OK, I'll keep the active branch with the others in the next update (1.0.86 or an 1.0.85.* hotfix).

**Comment by DanPristupov** [comment]
I don't want to bother the rest of users with another update, so I released a 'silent' one. You can download the new version there: https://cdn.fork.dev/mac/Fork-1.0.85.1.dmg

**Comment by svoop** [comment]
@DanPristupov Would it be very difficult to apply the order to the "Starred" section as well? 

I've just produced a major fuckup today not realizing that I was on the visually hidden Master branch instead of one of my current feature branches marked as favorites. Would be cool to have Master on the "Starred" section as well, but since the order rules don't apply there, I'd be back on square one.

**Comment by DanPristupov** [comment]
@svoop I will check. I remember there was some technical problem.
