### ISSUE TITLE
Save stash adds extra characters

### ISSUE THREAD

**Issue by infotexture** [ForkIssues/Tracker#762]
When a stash is saved via the **Save stash** sheet, the specified stash message is prefixed with 2 hyphens and a space `-- `.

It appears in the **Stashes** list in the sidebar as 
- `-- Stash message` instead of just 
- `Stash message`.

_Seen in Fork 1.0.84 on macOS Mojave 10.14.6 (18G103)_

**Comment by DanPristupov** [comment]
Thank you for the bug report. Fixed in 1.0.85.
