### ISSUE TITLE
Crash on corrupted image preview

### ISSUE THREAD

**Issue by homm** [ForkIssues/Tracker#764]
I have an image that I want to add to the repo. The problem is the image is partly corrupted and I think this is the reason why Fork crashes when I select this file in Changes.

https://user-images.githubusercontent.com/128982/66392826-a2cc8c00-e9d9-11e9-8508-0ab96f87473a.gif

**Comment by DanPristupov** [comment]
Somehow, Fork doesn't crash anymore. So, I think I can close this issue.

<img width="368" alt="Screenshot 2021-09-22 at 11 03 56" src="https://user-images.githubusercontent.com/618115/134315091-782c4b83-cc75-49e1-9e7b-191a25f306d9.png">
