### ISSUE TITLE
changes made to bug tracker rules require restart to take affect

### ISSUE THREAD

**Issue by cmcpasserby** [ForkIssues/Tracker#765]
when ever i change the parsing regex, or the result url i have to restart Fork for it to recognize these changes.

running fork 1.0.84 on macOS Mojave

**Comment by DanPristupov** [comment]
Hi. I improved the behavior in 1.0.85. Could you check for updates please?

**Comment by cmcpasserby** [comment]
seems to work perfect now, testing with both shared and local.
thanks
