### ISSUE TITLE
[Feature Request] Specify default push destination if there are multiple upstreams

### ISSUE THREAD

**Issue by kvithayathil** [ForkIssues/Tracker#767]
If a project has multiple upstreams defined - the user should able to set the default for push actions (or possibly automatically default to an upstream named origin)

**Comment by tbussmann** [comment]
Isn't this what 'remote tracking' is for? Right click on the (local) branch and select one remote branch in the popup under 'Tracking'.

**Comment by DanPristupov** [comment]
Since 2.12 Fork remembers the recently used remote for untracked branches.
