### ISSUE TITLE
[Feature Request] Undo steps of git stage

### ISSUE THREAD

**Issue by duncanbeevers** [ForkIssues/Tracker#768]
Sometimes I'm building up a commit, and I add a few files, check their contents, etc…
But maybe they weren't the right files!

I want to Cmd+Z to undo the staging of just those files, ideally returning to the same selection state I was in before I did the stage.

**Comment by DanPristupov** [comment]
I think this isn't possible.
There can be a large problem if some stage operation was made by 3rd party application (CLI, IDE or other git  client).
