### ISSUE TITLE
Add 'Commit and Push'

### ISSUE THREAD

**Issue by adam-26** [ForkIssues/Tracker#77]
It can convenient to have a commit automatically pushed at time of commit, maybe a 'checkbox' could be added to the commit UI that can be used to automatically push after commit?

**Comment by DanPristupov** [comment]
Hi Adam.

There are two possibilities:
1. If you need this occasionally. Hold the `alt` key in the commit view (the commit button will change to "Commit and push")
2. If you need this all the time. Enable 'Automatically Push on Commit' in the application settings to push every time you commit.

Hope this helps.

**Comment by adam-26** [comment]
Thanks, thats great!
