### ISSUE TITLE
Allow skipping pre-commit hooks (--no-verify)

### ISSUE THREAD

**Issue by passsy** [ForkIssues/Tracker#776]
Skipping pre-commit hooks when committing is one of the few cases where I still have to go back to `Terminal`.

It would be great to have an additional checkbox next to "Amend" to skip pre-commit hooks.

I use pre-commit hooks to fix formatting and run linting. Sometimes I know about errors but I'm way more interested pushing my WIP branch to `origin` than I care about lint warnings. That's when I use `git commit --no-verify`.

**Comment by passsy** [comment]
I just discovered https://github.com/ForkIssues/Tracker/issues/513. Seems like fork already supports it, but I don't see a "skip pre-commit hooks" Button when committing. Is it a regression?

Maybe the detection of pre-commit hooks doesn't work in my case. My pre-commit hook is located in `<projectRoot>/.githooks/pre-commit` and connected to git via `.git/config`

```
[core]
	hooksPath = .githooks
```

**Comment by DanPristupov** [comment]
> It would be great to have an additional checkbox next to "Amend" to skip pre-commit hooks.

I can't add a checkbox for every feature. However you can skip commit hooks in the error dialog:

<img width="698" alt="Screenshot 2019-10-17 at 14 38 01" src="https://user-images.githubusercontent.com/618115/67009351-bc618800-f0eb-11e9-8b22-4746997bf3d1.png">

**Comment by DanPristupov** [comment]
> My pre-commit hook is located in <projectRoot>/.githooks/pre-commit

That's the reason. Fork checks `.git/hooks/pre-commit` and `.git/hooks/commit-message`

**Comment by passsy** [comment]
Speaks something against checking `git config core.hooksPath`?

**Comment by DanPristupov** [comment]
Yes, time. It's not a trivial change.

- Checking `git config` value on every commit is quite expensive (~50ms).
- Checking it on repository open will lead to problems like 'I just updated the config value, but Fork doesn't see it'. Tracking the changes of the global .config file seems to be excessive.

**Comment by passsy** [comment]
True, the checkbox is a bad idea.

What about checking for an existing `pre-commit` hooks *after* committing fails? It doesn't require tracking changes.

**Comment by DanPristupov** [comment]
> What about checking for an existing pre-commit hooks after committing fails? It doesn't require tracking changes.

Good point. That's what I do right now actually.

**Comment by DanPristupov** [comment]
I just released Fork 1.0.85 which should improve that. Could you check it please?

**Comment by passsy** [comment]
I checked `1.0.85.1` and I don't see the button.

![Screen-Shot-2019-10-18-16-42-16 13](https://user-images.githubusercontent.com/1096485/67103885-48e07900-f1c6-11e9-8e06-516e48bf31d7.png)


```
$ git config core.hooksPath 
.githooks

$ ls .githooks 
pre-commit
```

**Comment by DanPristupov** [comment]
What .githooks points to? Fork expects `core.hooksPath` to be an absolute path. For example `~/.hooks`

**Comment by passsy** [comment]
It's a relative path because the hooks are part of the repository. An absolute path doesn't make sense in that case.

```
[core]
	hooksPath = .githooks
```

**Comment by DanPristupov** [comment]
Does `git rev-parse --git-path hooks` return a correct path to the hooks directory for the repository on your computer?

**Comment by passsy** [comment]
```
$ git rev-parse --git-path hooks
.githooks
```

It returns the relative path

**Comment by DanPristupov** [comment]
I'll try to use that, instead of calling git config.

**Comment by DanPristupov** [comment]
I improved the behavior in 1.0.86. Could you try it please?

**Comment by passsy** [comment]
I can confirm that it works with `1.0.86`

Thank you very much!

**Comment by pzi** [comment]
~~Hi there, related but different question.. what if there was a way to have a checkbox or keyboard shortcut to `git push --no-verify` or is that already a thing (and I missed out)?~~

welp...https://github.com/fork-dev/Tracker/issues/2056 and https://github.com/fork-dev/Tracker/issues/1239

**Comment by arphox** [comment]
Hi @DanPristupov,  
The button doesn't appear for me either, could you please take a look?
![kép](https://github.com/fork-dev/Tracker/assets/17320094/24245a1a-ef83-4a83-8bff-cef87e03c558)

```
$ git config core.hooksPath
.githooks

$ ls .githooks
_README.md  pre-commit  prepare-commit-msg

$ git rev-parse --git-path hooks
.githooks
```


Fork version: 1.96.0.0
OS: Windows 21H2 (OS Build 22000.2538)

**Edit**: I just realized I may have commented to the wrong repository (/Tracker instad of /TrackerWin). Should this feature work on Windows? (Also, if there is a /TrackerWin issue for this, please link it).

**Comment by marlonjames71** [comment]
Maybe I'm misunderstanding, but why couldn't there be a "No Verify" checkbox that essentially adds `--no-verify` to the commit under the hood?

**Comment by DanPristupov** [comment]
I don't want to clutter the layout.

**Comment by marlonjames71** [comment]
I feel like there is a lot of room here.

![Image](https://github.com/user-attachments/assets/d062deac-cd0d-45b0-a64b-ed9af2e506a3)

Or maybe the "Commit" button can turn to "Commit No Verify" when the CTRL key is held down, similar to "Commit and Push" when the OPT key is held down.

**Comment by pzi** [comment]
As someone who also uses `no-verify` on a semi-regular basis, it'd be awesome if there was another checkbox next to Amend to `Skip pre-commit hooks` which appends `--no-verify` flag to commit cmd.

**Comment by marlonjames71** [comment]
I've been having to use it a lot more lately as well. It's odd that Fork doesn't already have this since Fork might be the most feature rich git GUI that I've used and maybe exists. Currently I check the work and stage in Fork, but have been having to move to the terminal to actually commit.

**Comment by normanlolx** [comment]
Yeah, this checkbox totally should get added. We need desperately need it.

**Comment by normanlolx** [comment]
@DanPristupov – Please re-open this issue. We must a way. 💪🏻

**Comment by Turburlar** [comment]
I think this could be improved. The error dialog does not work for me....I am getting no error. I have other reasons for skipping pre commit hooks from time to time.

**Comment by marlonjames71** [comment]
I agree this ticket should be reopened.

**Comment by ikljaic-nubilum** [comment]
I find this option in sourcetree extremely useful. As a Repo Admin I need to run it quite often. I would suggest it, to become an option in the "Commit" Drop-Button. We have it there, so why not extend it. 
In sourcetree it is also there, as a MultiChoice DropDown Button. There you can find it, as well as "Amend".
I love the Amend Button, but it can also easily be moved there as Commit options. I would even go so far to modify it as a multi choice and make "Push on Commit" another option, unlike it being now a exclusive choice.

Another suggestion, ... add to the settings a list of options, so that you can enable/disable them.
