### ISSUE TITLE
Ensure user-custom Git instance is available to avoid crashes

### ISSUE THREAD

**Issue by ngyikp** [ForkIssues/Tracker#78]
**Reproduction steps:**

1. Install an older version of git through Homebrew (e.g. `brew reinstall https://github.com/Homebrew/homebrew-core/raw/2f2325f2c5b77a155cf8bd981af7b1cdf6985f7c/Formula/git.rb`)
2. On Fork preferences, set the Git Instance to Homebrew `/usr/local/bin/git`. Notice that it will point to `/usr/local/Cellar/git/2.14.0/bin/git`
    <img width="552" alt="fork bug 1" src="https://user-images.githubusercontent.com/6135313/29251261-7c8fceaa-8084-11e7-9391-f3e53579b8c7.png">
3. Run `brew upgrade git` and then `brew cleanup`. This will install v2.14.1 and then remove 2.14.0
4. Launch Fork

**Expected result:**

Fork should still work and just fallback to its own Git instance. Perhaps even an error message telling that the user selected Git instance is unavailable?

**Actual result:**

Fork is unresponsive, and the Git section inside Preferences is unusable. The only way to fix this is to trash `~/Library/Preferences/com.DanPristupov.Fork.plist` or remove the `customGitInstancePath` key inside that file.

<img width="552" alt="fork bug 2" src="https://user-images.githubusercontent.com/6135313/29251259-75ee62be-8084-11e7-976d-94cb0973496b.png">

**Comment by nebhale** [comment]
I too experienced this, and the (very technical) workaround is to remove the key from the preferences plist directly.  Not recommended, but can at least get you back up and running.

**Comment by DanPristupov** [comment]
Fixed this in 1.0.55. Thanks guys!
