### ISSUE TITLE
[Bug] Stash message misinterpreted as path spec in 1.0.85.2

### ISSUE THREAD

**Issue by rsfinn** [ForkIssues/Tracker#781]
In the latest update (1.0.85.2), if I click the stash toolbar button, type "stash message", and select "Save Stash", I get a "Git error" sheet where the error details read:

> error: pathspec 'stash message' did not match any file(s) known to git
> Did you forget to 'git add'?

In other words, the stash message is not being interpreted as a message argument (as if the "-m" flag was missing).  This is a regression from 1.0.84, which behaves as expected.  (This repo does contain a pre-commit hook, if that makes a difference.)

**Comment by DanPristupov** [comment]
It looks like git command conflicts with some file in your repository (most probably in the repository root or in the `.git` directory).

I can't reproduce the problem on my computer, but most probably I know how to fix that.

**Comment by jomnius** [comment]
Similar problems, cannot create any new stashes after last update. Is there any info you would need to debug this?

**Comment by DanPristupov** [comment]
>  cannot create any new stashes after last update

Any or only a one with a message?

**Comment by DanPristupov** [comment]
Is that possible that you switched Fork to use some other git instance?

<img width="550" alt="Screenshot 2019-10-22 at 09 22 43" src="https://user-images.githubusercontent.com/618115/67265238-889cae80-f4ad-11e9-951e-57d4e1a1a7a2.png">

**Comment by Macintron** [comment]
Same behaviour with Apple Git-122. No git-app changes before/after update.
Creating a stash without a message creates a stash `WIP on branch_name`.

**Comment by jomnius** [comment]
Using by default `2.21.0 (Apple Git-122) /usr/bin/git`, haven't touched setting ever. Also have not yet updated to Catalina, but using latest (auto-updated) Xcode 11.1

**Comment by DanPristupov** [comment]
Try to use the default Fork git instance (2.23.0). Does the problem still occurs?

**Comment by Macintron** [comment]
Using the default fork-git instance (2.23.0) works.
For a temporary workaround this fine.

**Comment by jomnius** [comment]
Same here, works now! That was a quick fix, thank :D

**Comment by Rmafive** [comment]
Had the same issue, was able to resolve by switching to the fork-git instance (2.23.0).

**Comment by herrherrmann** [comment]
I encountered the same with my local git version (2.21.0). But yes, the integrated Fork instance is working properly.

**Comment by rsfinn** [comment]
I can also confirm that using the embedded git instance works around the issue.  (I do prefer to use the system git for consistency with other tools and team members, but this will do as a work around for now.)

**Comment by Macintron** [comment]
Just for history:
Bug was in Apple Git-122. (command line  didn't accept a comment either).
Solved with update to Xcode 11.3 (Apple Git-122.2).
