### ISSUE TITLE
Cannot selectively commit code when in 'Ignore whitespace' mode

### ISSUE THREAD

**Issue by asjustis** [ForkIssues/Tracker#782]
When in 'Ignore Whitespace' mode, the following diff not going to staged area selectively. If I turn off the 'Ignore Whitespace' it's fine. 

<img width="1173" alt="Screenshot 2019-10-22 at 13 41 59" src="https://user-images.githubusercontent.com/1465112/67278779-518cc400-f4d2-11e9-8a05-be70edb023fc.png">

Weird, but for a similar diff in another file it works okay.

Noticed on 1.0.84, still happening in 1.0.85.2 version.
Cheers

**Comment by DanPristupov** [comment]
Sometimes git can't recognize a code chunk when whitespaces are trimmed.
This is not a bug.

**Comment by asjustis** [comment]
Ah, understood, gotta keep more careful about 'ignore whitespaces' from now on :) Closing the issue.
