### ISSUE TITLE
Cannot discard single empty line anymore

### ISSUE THREAD

**Issue by asjustis** [ForkIssues/Tracker#783]
If I select a single blank line and want to discard it, it does nothing. If there are at least two lines, it works fine. This happens no matter if "Ignore whitespace" is on or off.

BTW, thanks for Fork, an amazing tool!

**Comment by DanPristupov** [comment]
Ensure that you don't select the end of line symbol

**Comment by asjustis** [comment]
Hm, but the issue happens with an empty line for me, where the end of line symbols is the only one - how do I select it at all then? Thanks

**Comment by lpeabody** [comment]
I can confirm this. If there is only a single line you want to discard and you select that line and click "Discard changes..." nothing happens. But if I select a line above it and also the line I want to discard, then I get prompted "are you sure..." and I confirm and it is successfully discarded.

**Comment by dewey** [comment]
Just had the same issue, here's what it looks like to me with Fork Version 1.0.93.6:

![out](https://user-images.githubusercontent.com/790262/85180840-c0e6cd80-b284-11ea-8d59-9b5de465ff27.gif)
