### ISSUE TITLE
GPG support broken in 1.0.85

### ISSUE THREAD

**Issue by odrotbohm** [ForkIssues/Tracker#787]
I am not entirely sure this is GitFork's fault only but it looks like the version has issues to look up available GPG keys as the GPG Settings tab of my repositories only show a single GPG key now with the ones I need to use not listed anymore.

I've verified my GPG installation (driven by GPG Tools) and I can encrypt messages using the keys that are missing in GitFork just fine.

I saw 1.0.85 shipped an improvement "Add support for brew gpg". Did that maybe have a side-effect?

**Comment by DanPristupov** [comment]
It might be related to https://github.com/ForkIssues/Tracker/issues/378, but I'm not sure.

The only difference I made, is that now I run `/usr/local/bin/gpg` instead of `/usr/local/MacGPG2/bin/gpg2`

Could you show outputs of `gpg --version` and `/usr/local/MacGPG2/bin/gpg2 --version`?

Does `gpg --list-secret-keys` returns a correct output?

UPD: Gnupg must install symbolic link `/usr/local/bin/gpg -> /usr/local/MacGPG2/bin/gpg2`

**Comment by odrotbohm** [comment]
```
$ /usr/local/MacGPG2/bin/gpg2 --version
gpg (GnuPG/MacGPG2) 2.2.17
libgcrypt 1.8.4
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/odrotbohm/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

```
$ gpg --version
gpg (GnuPG) 1.4.7
Copyright (C) 2006 Free Software Foundation, Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions. See the file COPYING for details.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
Cipher: 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

```
$ which gpg
/usr/local/bin/gpg
```

Looks like that move "downgraded" me from 1.8.4 to 1.4.7. Suspecting the binary in  `/usr/local/bin` originates from a previous brew installation.

The output of `--list-secret-keys` is the same in terms of which keys are listed. However the format is different. I also noticed that the only key that's still available to me to choose from in Fork is the first key listed in that output. Maybe the parsing doesn't work for the old format?

**Comment by odrotbohm** [comment]
I just checked: brew currently serves 2.2.17. I could just try to install and rather use that? 1.4.7 sounds pretty dated in the first place.

**Comment by odrotbohm** [comment]
I just did that and keys appear properly in Fork's GPG tab. So please excuse the noise. Maybe providing the ability to select which binary to use including listing the versions just like for the Git binary would help diagnosing these cases?

**Comment by DanPristupov** [comment]
> Maybe providing the ability to select which binary to use including listing the versions just like for the Git binary would help diagnosing these cases?

Currently, no other people reported this problem, so not sure if we need that. We'll see.

**Comment by odrotbohm** [comment]
Is there anything to consider regarding the passphrase? I have a ASCII window popping up in my Terminal in case GPG wants a password. That "window" doesn't seem to capture input properly. Now I have to run the command line you issue in the Terminal once and can then use Fork for the time GPG caches the password but I don't remember that to have been the same way before. 🤔

**Comment by DanPristupov** [comment]
> Is there anything to consider regarding the passphrase?

I'm not a pro in this area and may understand something wrong. However I think this should be a job of `pinentry`: https://github.com/ForkIssues/Tracker/issues/378 (May be @svoop can comment this?)

In my case  I did the following. 

1. ```$ brew install pinentry-mac```
2. Added ```pinentry-program /usr/local/bin/pinentry-mac``` to ```~/.gnupg/gpg-agent.conf```
3. restarted gpg agent ```killall gpg-agent```

Then the prompt window was the same like with MacGPG2 and used to memorize the passphrase once a day or so.

**Comment by svoop** [comment]
@odrotbohm You have to install `pinentry-mac` and configure the GPG agent to use it as described by @DanPristupov above for GPG to render an input window when it requires the passphrase. Otherwise, GPG falls back to the default method which is a console prompt. In the context of macOS, this would only work when using the terminal for all GPG activities, with Fork and other GUI apps, it won't do the trick.

**Comment by odrotbohm** [comment]
That was helpful thanks. I was just puzzled as this wasn't needed before. Thanks, folks!
