### ISSUE TITLE
Opening from the command line appears to be broken

### ISSUE THREAD

**Issue by davedelong** [ForkIssues/Tracker#788]
I have an alias in git called `ui`, which will open the current directory in Fork. It's basically a faster way to do `open -a Fork .`.

Recently, this seems to have completely broken on me. When I launch fork in this way, it seems to always be pulling out a particular submodule within my repository, and not the actual top-level .git repository I'm pointing to.

I'm on the latest version of Fork, on Catalina using zsh (zsh 5.7.1 (x86_64-apple-darwin19.0)).

**Comment by davedelong** [comment]
Additionally, when I try to open the folder in Fork using ⌘O, it *still* opens the submodule, and not the folder I actually told it to open.

**Comment by davedelong** [comment]
... and now it seems to be working again. Weird.

**Comment by DanPristupov** [comment]
You can also install fork CLI tools:
<img width="516" alt="Screenshot 2019-10-26 at 15 15 27" src="https://user-images.githubusercontent.com/618115/67620105-7307eb80-f803-11e9-9950-64c1e333e133.png">
