### ISSUE TITLE
Suggestion: Close finished milestones

### ISSUE THREAD

**Issue by filiphr** [ForkIssues/Tracker#789]
First of all I have to say big thank you for git-fork it is by far the best git GUI that I have ever used. It is so easy and fast that I don't know how I haven't discovered it earlier 😄.

I was trying to understand what features are coming next or what is on your roadmap, but it was a bit difficult. Currently there are 14 milestones open, but I presume they should all be closed since the last released version is 1.0.85.2 (or at only 1.0.85) should be open. 

If my understanding is wrong then I am sorry and feel free to close this issue.

**Comment by DanPristupov** [comment]
> I was trying to understand what features are coming next or what is on your roadmap, but it was a bit difficult

Because we don't have one :). Fork development is driven by feature requests from our users. Generally speaking we implement the issues which have more 'likes'.

We use milestones as a todo list. Sometimes not all tasks are finished and I keep the milestone open as a reminder that something in not 100% done.

**Comment by filiphr** [comment]
>Because we don't have one :). Fork development is driven by feature requests from our users. Generally speaking we implement the issues which have more 'likes'.

All I can say keep up the awesome work.

>We use milestones as a todo list. Sometimes not all tasks are finished and I keep the milestone open as a reminder that something in not 100% done.

Thanks for clarifying this. Should I close this issue? Perhaps you can add an FAQ section to your website where you would be able to have answer to questions like this.
