### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by james-rabbit** [ForkIssues/Tracker#79]
I figured a free git tool would be open to PRs but I wasn't able to find the source code.
Are there plans to monetize it as a closed source app later, or am I just bad at searching?
Either way this looks like a nice app and I'll try to report any new bugs I find.
Thanks!

**Comment by DanPristupov** [comment]
Hi James,

Thank you for proposing your help. I appreciate any feedback, bug reports or feature requests. You can contact me here or by email support@git-fork.com.

Regarding the source. I don't have plans to open source Fork. I'm 100% sure, if I do, next day somebody will rename the application, slightly change the design, put different logo and start selling it. There are some plans to monetize Fork in the future, but now I can afford to keep it free for some time.

**Comment by james-rabbit** [comment]
It is possible to set things up in a way so that it is illegal to sell altered copies of your code. You may want to consider a license that does not allow derivative works, but leaves the source visible and allows contributions from developers that sign a CLA. I understand if you don't want to do that though, there may not be much benefit.

**Comment by BirkhoffLee** [comment]
^

**Comment by nebhale** [comment]
Not that he needs it, but to support @DanPristupov, there’s a big difference between a license that makes it illegal to sell altered copies of your code, and actually preventing people from selling illegal copies of your code.  I’ve worked exclusively on open source software for more than a decade and can say from experience that licenses are only as useful as your lawyers.  In much of the world, intellectual property is not viewed anywhere nearly as strongly as it is in the US and Europe.  The cultural norms are such that software licenses are ignored and theft (if you view it that way) is rampant. The only way to enforce a license is to use lawyers to convince distributing platforms (_not_ the actual infringers) to stop distributing these illegal copies.

I think that Dan is absolutely following the right path if he ever hopes to monetize Fork.  As someone who uses his product dozens if not hundreds of times a day, I cannot wait to pay him.

**Comment by cdzombak** [comment]
> I think that Dan is absolutely following the right path if he ever hopes to monetize Fork. As someone who uses his product dozens if not hundreds of times a day, I cannot wait to pay him.

Agreed. @DanPristupov, please let us give you money 😉

**Comment by DanPristupov** [comment]
@nebhale @cdzombak thanks for the support guys ❤️

**Comment by dmay** [comment]
Late for the party, but, @DanPristupov keep it commercial, keep it grow. 👍 

But, please-please-please, publish if you decide to abandon it :)
