### ISSUE TITLE
a/b style's branch name should auto expand upon open repo

### ISSUE THREAD

**Issue by yam-liu** [ForkIssues/Tracker#790]
For instance, I have a branch named feature/add_gpg_support.
The repo not exist in current Fork, I open it by `fork my_repo`.
A new tab shows, but the current branch not show up in the left with bold font and check mark, because it is collapsed by default.
It should be auto expand if HEAD it like a/b style. 
Thanks.
![image](https://user-images.githubusercontent.com/1056803/67672598-3e3a9680-f9b3-11e9-97da-17e77bdc0097.png)

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/Tracker/issues/165
