### ISSUE TITLE
Option to push tag to remote

### ISSUE THREAD

**Issue by otri** [ForkIssues/Tracker#794]
It would be great if while adding a tag, there's a checkbox to push to remote.  Right now it's a two step process, and not obvious if a particular tag got pushed to remote (i.e. created local-only).  Also I propose; local-only tags should have a dashed outline, and if pushed to any remote then the tags gets a solid outline.

**Comment by DanPristupov** [comment]
> Also I propose; local-only tags should have a dashed outline, and if pushed to any remote then the tags gets a solid outline.

How to determine if a tag is a local-only? I think it's impossible.

**Comment by otri** [comment]
I'm thinking something like this dotted outline could implicitly represent local-only tags.
https://images.app.goo.gl/GKbVSL58mXHtmsfQA

**Comment by DanPristupov** [comment]
I mean technically. Show me a git request or a link to the documentation.

**Comment by otri** [comment]
I'm assuming that given you can get current tags from the remote servers on a fetch, then it's possible to corroborate if a particular local tag is matching with the remote or not.  Might require a local cache that gets updated on a fetch, much like how git refreshes its remotes state on a fetch.

**Comment by marcheimendinger** [comment]
I'm also for an option to push the tag at creation.

**Comment by leofeyer** [comment]
Maybe when holding down the `[option]` key, the button "Create Tag" could become "Create and Push Tag"? Similar to the "Commit" button, which becomes a "Commit and Push" button.

**Comment by samdeane** [comment]
It would also be good to have an "Automatically push tags" preference to complement the "Automatically push on commit" preference. Currently the tags aren't included in the automatic push, which can get confusing, as it's particularly easy to forget that you've not pushed a tag when normal commits are auto-pushed.

**Comment by DanPristupov** [comment]
@samdeane I'm not sure what to do when user has multiple remotes. In a case of commit we know the corresponding remote from the remote tracking branch, otherwise the push dialog will be shown.

**Comment by samdeane** [comment]
>  I'm not sure what to do when user has multiple remotes. In a case of commit we know the corresponding remote from the remote tracking branch, otherwise the push dialog will be shown.

I was thinking that auto-pushing tags would only happen when also auto-pushing a commit, and so they would be pushed to the remote that the commit is pushed to.

**Comment by joepsyko** [comment]
I'd also add a push tag option when creating a new tag, the two ste process is such an annoying thing

**Comment by SimJoSt** [comment]
Oh yeah, the feature existed for some time now on macOS. As far as I know, it is only possible to push it to all remotes. Not a specific one.
