### ISSUE TITLE
401 Unauthorized while sign in to GitLab

### ISSUE THREAD

**Issue by alpergunay** [ForkIssues/Tracker#796]
I am getting 401 Unauthorized error while signing to GitLab with using my PAT 
![image](https://user-images.githubusercontent.com/25134503/68008968-9e6e5880-fc91-11e9-8c27-9429af2f77ea.png)

**Comment by HansJK** [comment]
Same here...

**Comment by DanPristupov** [comment]
I just tried and it worked for me.

1. I clicked on the first link in the dialog (GitLab.com)
2. Entered key name, enabled the 'API' checkbox, clicked on "Create"
3. Copied the key and entered it in Fork.

**Comment by baptistecdr** [comment]
Just tried and I have the same problem with my school's GitLab.

**Comment by alpergunay** [comment]
> I just tried and it worked for me.
> 
> 1. I clicked on the first link in the dialog (GitLab.com)
> 2. Entered key name, enabled the 'API' checkbox, clicked on "Create"
> 3. Copied the key and entered it in Fork.

Please try with using Gitlab API v4.0 to see the problem

**Comment by DanPristupov** [comment]
What do you mean?

**Comment by alpergunay** [comment]
> What do you mean?

Which gitlab version are you using ? Gitlab changed their API's and if you are trying to connect old version of Gitlab, you will not see the problem.

**Comment by DanPristupov** [comment]
There's just one version on Gitlab.com.

**Comment by alpergunay** [comment]
> There's just one version on Gitlab.com.

![image](https://user-images.githubusercontent.com/25134503/68395825-8dd24c80-0181-11ea-9eb0-d443d3bccc3a.png)

**Comment by HansJK** [comment]
Is there a way to use a privat repo with Fork?

**Comment by DanPristupov** [comment]
@HansJK yes, I use private repos on GitLab myself.

**Comment by baptistecdr** [comment]
My school is using GitLab 11.7.5 (CE). 🤔

**Comment by DanPristupov** [comment]
@alpergunay are you sure you are trying to connect to GitLab.com? We do not support other servers.

**Comment by HansJK** [comment]
How do I use Fork then? I get the same 401 error. And I don't see anywhere to change away for gitlab.com

**Comment by HansJK** [comment]
Why don't you support privat servers? Seems like a standard feature.

**Comment by DanPristupov** [comment]
What feature? What feature do you miss?

If you want to fetch/push to your repository, just do that. What else do you miss?

**Comment by HansJK** [comment]
> @alpergunay are you sure you are trying to connect to GitLab.com? We do not support other servers.

You said you don't support privat gitlab server.

**Comment by DanPristupov** [comment]
@alpergunay Fork only supports gitlab.com and the version it has. Custom instances are not supported.

P.S. Yes, Fork uses the 4.0 API

**Comment by alpergunay** [comment]
@DanPristupov we are using gitlab on premise.

**Comment by HansJK** [comment]
If you don't support that, I guess I have to use Sourcetree instead, because I know they support it.

**Comment by alpergunay** [comment]
> If you don't support that, I guess I have to use Sourcetree instead, because I know they support it.

Yes, I am using Sourcetree without any problem with using private gitlab.

**Comment by DanPristupov** [comment]
Yes, they may have support it.

We don't have a time for that. We are a small team. I'm still not sure what **feature** you miss though.

@alpergunay you don't need any special integration to **use** any repos. Just fetch and push and Fork will prompt credentials

**Comment by HansJK** [comment]
> We don't have a time for that. We are a small team. I'm still not sure what **feature** you miss though.

Private gitlab server feature.
