### ISSUE TITLE
[Minor] Make commit message area resizeable.

### ISSUE THREAD

**Issue by Antonz0** [ForkIssues/Tracker#799]
Commit message area is only two-line (Subject and Description) and for big messages it's starts scrolling and hard to edit and see. I see no option to increase its size too. 
It will be nice, if area can be increased and second line input area can be seen multi-line.

Also, it's rather strange decision to separate it to the two sub-fields, I see no real convenience in this, but this is more questionable.

**Comment by DanPristupov** [comment]
The second field is multi-line.

**Comment by Antonz0** [comment]
I see. It just seems that it doesn't gets enabled sometimes and everything goes to first, especially on pasting. Played with it a bit, and it looks ok, nevermind.
