### ISSUE TITLE
Add ability to rebase branch on another

### ISSUE THREAD

**Issue by eseres** [ForkIssues/Tracker#80]
If there are two branches, each branching off, say, master, I would like the ability to put one on top of the other if that makes sense... Is this possible with Fork? If so, I could not figure out how.

**Comment by DanPristupov** [comment]
Come on! Just click on any branch or revision and you'll see both Rebase and Interactive Rebase.
<img width="346" alt="2017-08-23 at 15 22" src="https://user-images.githubusercontent.com/618115/29617965-e8a1c456-8816-11e7-9a30-781b0efa2ce3.png">

**Comment by eseres** [comment]
Right, but many times those options are greyed out or the branch I am intending to rebase on, is not offered. I don't yet see the pattern yet as to when that happens though. I hope it's just me doing something wrong.

**Comment by eseres** [comment]
Hmm, I can't duplicate what I think I was seeing earlier. So it must have been user error. Sorry for the false alarm.

**Comment by DanPristupov** [comment]
I just checked the source code. Here's what I've found out:
- You can **rebase** on any branch other that active one.
- You can **rebase interactively** on any commit in repository

**Comment by eseres** [comment]
That makes sense, thanks for checking.

**Comment by danez** [comment]
Could we add the `Rebase on "maser"` also in the sidebar branch view? currently only interactive is there and it took me a while to figure out that i have to right click in the history view.

![bildschirmfoto 2017-11-29 um 16 19 49](https://user-images.githubusercontent.com/231804/33382482-2529a7d4-d521-11e7-8f3d-8dd4f468a068.png)
