### ISSUE TITLE
"Initialize Git LFS" does Git Flow instead

### ISSUE THREAD

**Issue by andrews05** [ForkIssues/Tracker#800]
Choosing the "Git LFS > Initialize Git LFS" menu item brings up the window for initializing Git Flow. I'm pretty sure this isn't correct.

**Comment by DanPristupov** [comment]
Yes, this will be fixed in 1.86. Thank you for the bug report.

**Comment by andrews05** [comment]
Cool, thank you!

**Comment by DanPristupov** [comment]
1.0.86 is out.

**Comment by andrews05** [comment]
Great, all working :)
