### ISSUE TITLE
Ability to filter multiple branches

### ISSUE THREAD

**Issue by prsh9** [ForkIssues/Tracker#802]
Is there a possible way to allow filter multiple branches (maybe even restrict and say filter by 2 branches). Lets say filter by 2 branches which would mean union of the commits from both the branches.

UseCase: Working on a branch for a feature which now needs to be re-based to the latest feature branch commit to resolve conflicts, the filtering would help understand where both the branches diverge, how-many/what commits in feature and by whom.

Its a great product by the way and would love to donate 👍

**Comment by DanPristupov** [comment]
Hold ⌘

<img width="392" alt="Screenshot 2019-11-06 at 07 46 28" src="https://user-images.githubusercontent.com/618115/68274487-8f105600-0069-11ea-91da-bcb76fea7080.png">
