### ISSUE TITLE
Kitty Terminal macOS

### ISSUE THREAD

**Issue by kmplngj** [ForkIssues/Tracker#803]
Hi,

would it be possible to add support for Kitty Terminal? https://github.com/kovidgoyal/kitty

Thanks
Jan

**Comment by vr8hub** [comment]
Wow, I didn't know Kovid had a terminal emulator. (He's the author of the calibre ebook manager.)
I'll second this request.

**Comment by DanPristupov** [comment]
@vr8hub then like the first comment please

**Comment by ewnu** [comment]
any update on this topic?
Thanks

**Comment by ewnu** [comment]
I made Open in Kitty custom command for people who use kitty.

[Fork Custom command](https://gist.github.com/oktomus/e284923a7fce837615bb756a1060e5dc?permalink_comment_id=4164457#gistcomment-4164457)

**Comment by DanPristupov** [comment]
Hi. We added the predefined settings for Kitty in 2.21

**Comment by dylanleung** [comment]
#2117 please add Alacritty
