### ISSUE TITLE
Allow configuring the maximum number of commits shown in history

### ISSUE THREAD

**Issue by roefer** [ForkIssues/Tracker#804]
Hi,

it seems that Fork only displays a limited number of commits in the history (about 25000). This limit not only results in the history being incomplete, but also means that older commits cannot be displayed even if the are found through other means. For instance, if I list the history of a certain file, it is complete, but double-clicking older commits does not reveal them in the main history, because they are not listed there. This means that I cannot find out about the other files that were changed in that commit.

Would it be possible to let users configure the maximum number of commits shown?

**Comment by kambala-decapitator** [comment]
also came across this limitation when tried to open specific commit (with search) that is 7 years old

**Comment by DanPristupov** [comment]
Some time ago the commit limit was increased to 50,000.

You can also change it using the following terminal command: `defaults write com.DanPristupov.fork maxCommitCount 150000`

**Comment by zoujyjs** [comment]
what about windows

**Comment by DanPristupov** [comment]
@zoujyjs https://github.com/fork-dev/TrackerWin/issues?q=maxCommitCount+
