### ISSUE TITLE
Dark Mode: bold text is hard to distinguish

### ISSUE THREAD

**Issue by gunarkroeger** [ForkIssues/Tracker#805]
![image](https://user-images.githubusercontent.com/22892870/68414516-1bf10780-016f-11ea-80ca-e6bd227dc904.png)
![image](https://user-images.githubusercontent.com/22892870/68414563-31663180-016f-11ea-9ce2-94f5c485b7bc.png)

I find it hard to see what commit I'm at when scrolling through a lot of commits and I always end up changing to light mode just to find it faster because with dark mode it's hard to distinguish the bold from the normal text.  
I also don't understand the logic of why some commits are greyed out and some are not, so they just make it more confusing than help.

I really love fork, and I'm only creating this issue to help make it better!

**Comment by DanPristupov** [comment]
Hi. Fork grays out the commits which are not reachable (i.e. the commits which are note merged into your current branch).

**Comment by gunarkroeger** [comment]
I'll add that the main problem I had with scrolling and trying to find the bold line has been solved now that there is the ALT+0 shortcut. Thanks for the continuous improvements!
