### ISSUE TITLE
[Bug] Library not loaded: @rpath/libswiftCore.dylib (Interactive rebase)

### ISSUE THREAD

**Issue by spaceemotion** [ForkIssues/Tracker#810]
I just wanted to open interactive Rebase and it crashed with the following error:

```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Applications/Fork.app/Contents/Resources/fork_ri
  Reason: image not found
error: "/Applications/Fork.app/Contents/Resources/fork_ri" died of signal 6
error: There was a problem with the editor '"/Applications/Fork.app/Contents/Resources/fork_ri"'.
```

I still got Mac OS 10.12.6 (16G2128) installed, if that's of any help (maybe swift comes preinstalled in future versions?).

**Comment by DanPristupov** [comment]
Yes, install https://support.apple.com/kb/DL1998?locale=en_US

https://github.com/ForkIssues/Tracker/issues/611

**Comment by spaceemotion** [comment]
Wow, that was quick - problem fixed, cheers!
