### ISSUE TITLE
Stuck with "loading..." cannot view/create branches

### ISSUE THREAD

**Issue by ryzr** [ForkIssues/Tracker#811]
This is my first time installing Fork. My first time using, I linked my Gitlab account and added a new SSH key.

When opening a Gitlab repo locally I'm stuck with the loading indicator pictured below:

<img width="713" alt="Screen Shot 2019-11-12 at 12 09 54 pm" src="https://user-images.githubusercontent.com/9389421/68634495-9c37b400-0545-11ea-9f7e-f4669230ece0.png">

Expanding Branches, Remotes, Tags, etc in the sidebar all reveal nothing. 

The repo I'm working on has three branches: master, rfc/sleep and features/races (active). I have a couple of repos that DO work, which only have one branch: master.

My .gitconfig can be seen here:
https://github.com/ryzr/dotfiles/blob/master/git/config

**Comment by DanPristupov** [comment]
Hi, could you check the content of the ~/Library/Logs/Fork.log file please?
It would be better if you send it to support@forkapp.io

**Comment by ryzr** [comment]
Hey @DanPristupov,

Here's a copy of the log:
```
ℹ️> Fork Version: 1.0.86 Build: 1.0.86 PID: 33338
ℹ️> XCGLogger Version: 7.0.0 - Level: Debug
ℹ️> XCGLogger writing log to: file:///Users/ryan/Library/Logs/Fork.log
ℹ️[AppDelegate.swift:108] applicationDidFinishLaunching(_:) > Git instance: local
ℹ️[RemoteServiceNotificationManager.swift:73] stop() > Stop checking GitHub notifications
ℹ️[RemoteServiceNotificationManager.swift:48] start() > Start checking GitHub notifications
ℹ️[RemoteServiceNotificationManager.swift:95] refresh(force:) > Refresh GitHub notifications...
❗️[RefreshRepositoryCommand.swift:222] refreshRepositoryData(_:_:_:_:_:_:_:_:_:) > cannotParse(error: "Cannot parse author date in \'b5c8dc0528aefdeb2f4a8eab4d12ae4b4fa245d0\'")
ℹ️[RefreshRepositoryCommand.swift:180] refreshRepositoryStatus(_:_:_:_:_:_:_:_:_:) > Refresh 'core' status. Updated (1 files).
```

`git show b5c8dc0528aefdeb2f4a8eab4d12ae4b4fa245d0`
```
commit b5c8dc0528aefdeb2f4a8eab4d12ae4b4fa245d0 (HEAD -> develop, origin/develop)
gpg: Signature made Tue 12 Nov 16:05:07 2019 ACDT
gpg:                using RSA key BB9E90A7925087B130C4CB3A0CA949CACE2D6B82
gpg: Good signature from "Ryan Brereton-Canham <ryan@luminsports.com>" [ultimate]
Primary key fingerprint: 3ABB E675 0580 2EF7 E22E  94F4 41FE 1E88 2B2F D710
     Subkey fingerprint: BB9E 90A7 9250 87B1 30C4  CB3A 0CA9 49CA CE2D 6B82
Author: Ryan Brereton-Canham <ryan@luminsports.com>
Date:   Tue Nov 12 16:05:07 2019 +1030

    refactor: fix user namespace
```

EDIT: sorry, I read your comment a little fast and ignored the email to support. Sending through now. Feel free to close if you would rather manage there.

**Comment by ryzr** [comment]
Aha! The culprit was the .gitconfig setting:

```
[log]
        showSignature = true
```

I decided this wasn't super necessary for me and disabled it. Things are back up and running now :-)

**Comment by DanPristupov** [comment]
> showSignature = true

I'll make Fork handle this properly in the next update.

**Comment by DanPristupov** [comment]
Sorry, we forgot to merge the fix in the update :(.
