### ISSUE TITLE
Can't create a new stash

### ISSUE THREAD

**Issue by maksimovic** [ForkIssues/Tracker#813]
I'm trying to stash some changes:

<img width="501" alt="Screenshot 2019-11-12 at 09 30 35" src="https://user-images.githubusercontent.com/1126226/68655065-a2229a80-052f-11ea-884d-8d17b0b86ed4.png">

But then this happens:
<img width="679" alt="Screenshot 2019-11-12 at 09 30 47" src="https://user-images.githubusercontent.com/1126226/68655085-ab136c00-052f-11ea-9423-eb611df51fb3.png">

`~/Library/Logs/Fork.log` says:

```
⚠️[GitRequest.swift:148] execute(suppressErrorLogging:cancelationToken:) > Git error 'stash save -m user-logs-cleanup':
error: pathspec 'user-logs-cleanup' did not match any file(s) known to git
Did you forget to 'git add'?

❗️[ErrorWindowController.swift:25] initialize(errorResult:) > gitUnknownError(output: "", error: "error: pathspec \'user-logs-cleanup\' did not match any file(s) known to git\nDid you forget to \'git add\'?\n")
```

Edit: Using Fork 1.0.86

**Comment by DanPristupov** [comment]
Update system git or switch fork to the internal one: https://github.com/ForkIssues/Tracker/issues/781

**Comment by maksimovic** [comment]
🤦‍♂ Done, thanks, and sorry for the duplicate
