### ISSUE TITLE
Smarter version of "Hide Remote Branches"

### ISSUE THREAD

**Issue by n8gray** [ForkIssues/Tracker#816]
On a big team the "Hide Remote Branches" feature is a lifesaver.  I'd like to be able to use it to focus on the branches that matter for my daily work, but it hides a bit too much information.  In addition to my local branches I'm usually interested in a couple types of remote branches:

* Remote branches that my feature branches track, so I know how far ahead or behind I am
* A small set of key remote branches such as `master`, `dev`, `stable`, `release`, etc, so I can monitor team progress and anticipate any merge challenges

If there was a "smart" mode for "Hide Remote Branches" that didn't hide tracked upstream branches or starred branches it would be perfect, since I've already starred those key remote branches.

This would be very much in line with the way filtering works.  When you filter by a local branch you also see its tracked remote branch.

Thanks!

**Comment by DanPristupov** [comment]
Did you try multi-filter? (⌘+click on filter)

It does exactly what you want (until I miss something)

**Comment by n8gray** [comment]
While multi-filter almost makes it possible to build a filter like the one I'm describing, it would require me to Cmd-Click on every local branch and every starred branch every time I wanted to enter this mode.  Also, when "Hide Remote Branches" is enabled branch heads are not shown for the remote branches, even if they are manually selected as filters (maybe a bug?).

The utility of the mode I propose is that with one click it would automatically filter the remote branches down to the precise set which is most relevant to the user.  Personally, I would almost never have a reason to leave this mode -- it would instantly make Fork the most useful git client on the market to me.

**Comment by DanPristupov** [comment]
I think we need an option to save filter state. Kind of ability to save different 'views'.

**Comment by n8gray** [comment]
If you're talking about adding more advanced predicates for filters, like "all local branches", "all tracked remote branches", or "all starred branches", then yeah, that would work.  Actually, something like an "Only Show My Branches" toggle along with a way to configure what gets included in "My Branches" would be brilliant!

If you wonder why I care so much about this, here's the actual view that greeted me yesterday when I returned to our server repo after a little time away:
![Screen Shot 2019-11-13 at 9 49 34 AM](https://user-images.githubusercontent.com/82794/68789787-f8a8db00-05fa-11ea-82a9-c87012a24a57.png)

**Comment by DanPristupov** [comment]
In Fork 2.6 you can filter and hide folders and remotes.
