### ISSUE TITLE
Branch Sidebar Gestures

### ISSUE THREAD

**Issue by bdgeyter** [ForkIssues/Tracker#82]
Branches in the sidebar could support gestures for common actions:
1) Drag 'n Drop to merge a branch into another (see eg. Tower)
2) Swipe right to Pull
3) Swipe left to Push

**Comment by DanPristupov** [comment]
Hi,

(1) Do you find such a behavior useful?

(2) and (3)
Swipe gesture seems to be a great idea on the first look, but it must be polished:
- Swipe to Push is OK.
- Swipe to Pull is probably dangerous. Pull = Fetch + Merge. Pulling branch X, when branch Y is active, will merge X -> Y. Users rarely need to pull branches other than the corresponding tracked branch (e.g. origin/master for master). I think such gesture will rather hurt than help.
- We can do Swipe to Fetch instead. But this is going to be pointless in the near future when Fork starts fetching automatically.

**Comment by clounie** [comment]
I think if there was a "Merge || Rebase || PR" confirmation dialog with From/To branches when you did a Drag 'n Drop, I would use it.

**Comment by dmay** [comment]
Swipes are not 'action' gestures, they are 'navigation' gestures. HUGs say so, all browsers do so, even the OS do so for Spaces and full-screen apps.

Drag&drop to merge sound interesting, but, for not checked out branches, it will only work in limited scenarios.

**Comment by bdgeyter** [comment]
1) **Drag 'n Drop**:  Here's a gif of the feature in Tower 
![merge-dragdrop](https://user-images.githubusercontent.com/4182170/29731598-3bd93f4e-89e5-11e7-9061-160f0a4f582e.gif) 
Do find it very useful, as I tend to do this action several times a day. 
@dmay For branches that are not checked out, you can (a) don't allow it as a drop target or (b) show a dialog asking you if you want to checkout the branch first (with option to autostash changes). 

2) **Swipe**: @dmay don't agree. Although not as common yet on desktop, you can now swipe in the Mail app on emails, and Messages, just like on mobile. Same for apps like Spark, and other mail clients. It depends on the context.

    @DanPristupov: Definitely needs to be refined and tested. It should always require some extra confirmation from the user, either through a dialog, or by adding resistance (see e.g.. Mail app how they implemented this, or a double swipe, i.e. swipe to confirm).

    About Swipe to Pull: it's a valid comment about it being dangerous. I do think the vast majority of git users keep a one on one correspondence between local and remote branches: eg. if i'm on a feature branch, and I swipe develop, it would checkout develop, and then pull origin/develop into develop.

    You could even go one step further: autostash if you have changes, do the checkout/pull on develop, checkout the feature branch when you're done, and replay the stash (In general, I think there's a big opportunity for a Git client to make some of these complex git steps a lot easier!) 

@clounie Love the drag 'n drop to PR idea!

Either way, if you add gestures, their usefulness would depend on an individual user's use case, so making them configurable in Settings would be key. In the end, that's what makes a Git client stand out over command line: making common tasks faster or more intuitive. One of the big reasons I love Fork, is it's UI for creating PRs for example!

**Comment by dmay** [comment]
>  Although not as common yet on desktop, you can now swipe in the Mail app on emails, and Messages, just like on mobile.

Important point here is those swipes don't perform any *actions*, they only display or hide additional document-specific controls.

**Comment by DanPristupov** [comment]
@dmay very long swipes seem to perform the actions though

**Comment by DanPristupov** [comment]
I implemented drag'n'drop In 1.0.58 as @bdgeyter advised. What is really nice is that you can drag an drop even non-active branches.
Here's how it looks like:
![2017-10-23 at 14 59](https://user-images.githubusercontent.com/618115/31890289-db5a936a-b802-11e7-88d3-5a27fe104805.gif)

**Comment by bdgeyter** [comment]
Oh wow, that looks really really cool!!! 🙌🏻💯

**Comment by bdgeyter** [comment]
Been using it for a couple of days now, and I just absolutely love the feature!! Great job @DanPristupov!

**Comment by DanPristupov** [comment]
I think I can close this now.

**Comment by clounie** [comment]
Features like this are why I keep a Mac open beside my Linux desktop, just for Git Fork and 1-2 other apps. ;)

Using other Git GUIs is downright painful in comparison..
