### ISSUE TITLE
[Bug] Problems in which characters in Korean messages committed in the Mac are separated

### ISSUE THREAD

**Issue by datumflux** [ForkIssues/Tracker#822]
I know this is a problem that was reported a long time ago. But I don't think it's corrected yet, so I'm reporting again.

![Fork_Problem](https://user-images.githubusercontent.com/40652766/68913373-63464c00-079e-11ea-9232-a9d3a182cb15.PNG)

The message in the blue circle of the screen shot was committed in the Mac.

I understand the problem caused by Mac processing Unicode characters.
Applying the git setting does not solve the problem. (core.precomposeunicode = true)

Share StackOverflow issues for troubleshooting.

https://stackoverflow.com/questions/43856141/compare-arabic-strings-with-special-characters-ios

**Comment by GomPam** [comment]
already reported this problem.
but, not fixed yet..
@DanPristupov 

Issues:
[Bug] unicode normalization problem #444
[BUG] Certain characters get weird in commit messages. #656
