### ISSUE TITLE
Rebase doesn't work since last update

### ISSUE THREAD

**Issue by jimblue** [ForkIssues/Tracker#824]
Hello,

First thank you so much for your amazing work on Fork, I love it.

I'm using Version 1.0.86 on Mac and I've just found that rebase doesn't work as before.

When I use interactive rebase on, all the comit are last and the branch is just rebase with no comit into the target branch.

Are you also able to reproduce that issue?

I never add this problem before.

Cheers

**Comment by DanPristupov** [comment]
Hi. Can you show screenshot of before and after states?

**Comment by jimblue** [comment]
Sure, I've made multiple screenshots to show you all the steps:

![Screenshot 2019-11-17 at 19 33 46](https://user-images.githubusercontent.com/10623367/69012040-56c61d00-0971-11ea-88bf-168d0e58a5a1.png)
![Screenshot 2019-11-17 at 19 33 55](https://user-images.githubusercontent.com/10623367/69012042-59287700-0971-11ea-8bb0-d9b1582cc06e.png)
![Screenshot 2019-11-17 at 19 34 04](https://user-images.githubusercontent.com/10623367/69012043-5d549480-0971-11ea-8c80-8cec605e287b.png)
![Screenshot 2019-11-17 at 19 34 16](https://user-images.githubusercontent.com/10623367/69012045-5fb6ee80-0971-11ea-8a59-d8fceea7ab16.png)

**Comment by DanPristupov** [comment]
Could you send me the content of the log (`~/Library/Logs/Fork.log`) to support@forkapp.io please?

Did you change the comment symbol in git (`core.commentchar`)?

**Comment by jimblue** [comment]
Ya I have a custom `.gitconfig` with `commentchar =  "'"` and other changes. Just shared it with the log file.

**Comment by DanPristupov** [comment]
The custom comment char causes the problem.

**Comment by jimblue** [comment]
Indeed problem solved by removing `commentchar = "'"` in  `. gitconfig `

Thank you 👍
