### ISSUE TITLE
Push detached HEAD to remote

### ISSUE THREAD

**Issue by jwestbrook** [ForkIssues/Tracker#825]
I ran into a merge conflict when attempting to merge my changes into another branch which left me in a detached HEAD state. I resolved the merge and wanted to push my resolved branch to the remote, but my detached HEAD branch is not listed on the push branch drop down.

**Comment by DanPristupov** [comment]
This doesn't make much sense, to be honest.

Detached HEAD means 'no branch is active' (active branch == null). There's nothing to push.

Working in detached HEAD could also be dangerous, because your changes will disappear once you checkout some branch.

Merge can not move your repo into detached HEAD, it must be something else.

**Comment by jwestbrook** [comment]
Apologies, that is true git merge didnt leave me in a detached state, my teams git strategy checks out the remote without creating the branch then merges my branch into that remote. The merge conflict at that point left me in a detached HEAD.

I totally get working in a detached HEAD for any length of time is a bad idea. Typically its for the merge resolution, push to the remote branch then I'm done with it.

The only reason I opened the issue was that I've been trying lots of other OSX git GUIs but Fork seems to make everything easier, but its missing that process (the other ones included it)

**Comment by DanPristupov** [comment]
- If you want to push a branch, which already exists, you don't need to checkout it.
- If you want to push HEAD to some remote branch, you can create a custom branch command for that.

Something like the following (I didn't test it).
<img width="550" alt="Screenshot 2019-11-19 at 18 19 51" src="https://user-images.githubusercontent.com/618115/69169763-31fcb180-0af9-11ea-9efa-a74d18e4958e.png">
<img width="300" alt="Screenshot 2019-11-19 at 18 21 59" src="https://user-images.githubusercontent.com/618115/69169938-7ee08800-0af9-11ea-9f3f-de8cfa40f7ba.png">

**Comment by jwestbrook** [comment]
What is this magic? Custom commands that just work?

`<obligatory Party Parrot GIF>`
