### ISSUE TITLE
Search order in command palette

### ISSUE THREAD

**Issue by povesteam** [ForkIssues/Tracker#826]
Fork is great, I use it daily, it became my go-to app for git management.

The command palette search (⌘P) could use a simple MRU (most recently used) item ordering, so that sorting is done according to each user's behaviour.

I often switch projects, and I would expect `adr` to become first choice after a few positive searches.

![image](https://user-images.githubusercontent.com/506532/69123692-af4d0580-0aaa-11ea-8704-26a9d33cd4ce.png)

I use Fork 1.0.86 for Mac.

Thanks!

**Comment by DanPristupov** [comment]
The problem is simple. The Commands section is always first.

**Comment by povesteam** [comment]
I see, but I usually search for Repositories, not Commands.

**Comment by DanPristupov** [comment]
In 1.0.88 the section with the best match will be on the first position.

**Comment by povesteam** [comment]
Awesome, thanks!

**Comment by povesteam** [comment]
It works perfectly now for my case. Thanks!

![image](https://user-images.githubusercontent.com/506532/71069413-593eb100-2181-11ea-9893-23a6ddfdc413.png)
