### ISSUE TITLE
Pre-commit hook error - Executable not found 

### ISSUE THREAD

**Issue by spongeboy** [ForkIssues/Tracker#829]
Versions: Fork 1.0.86 on OS X Mojave 10.14.6

I am using the wonderful [Pre-Commit](https://pre-commit.com/) framework, and have added some pre-commit hooks to my repository.

When I commit from the terminal, I have no problems - all hooks run correctly.

When I commit from Fork, one of the hooks (`dotnet format`) fails to run due to "Executable not found". The other hooks successfully complete.

```
$ git commit -m This is a test commit

Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...............................................................Passed
Check for added large files..............................................Passed
Terraform fmt............................................................Passed
Terraform validate without variables.....................................Passed
Terraform docs...........................................................Passed
Format cs files..........................................................Failed
hookid: dotnet-format

Executable `dotnet` not found
```

Any ideas? My best guess is that Fork is using a different PATH to what my terminal is using?

Thanks, keep up the great work!

**Comment by DanPristupov** [comment]
> My best guess is that Fork is using a different PATH to what my terminal is using?

May be it uses aliases, difficult to say. You can get the same PATH by starting from the terminal (https://github.com/ForkIssues/Tracker/issues/430).

**Comment by DanPristupov** [comment]
I could not find an info how to enable some `verbose` mode in `Pre-Commit`. It would nice to see the **exact** problem and try to fix it.

**Comment by spongeboy** [comment]
Wonderful - running `fork` from the terminal has fixed the issue!

(I probably should have made clear initially - I am using Fork 1.0.86 on OS X Mojave 10.14.6)

Re: `Pre-commit` - it can be run from the command line with `pre-commit run -v` for verbose mode. Also, errors are logged to `/Users/YOUR_USERNAME/.cache/pre-commit/pre-commit.log`

However, I don't think this issue is related to `pre-commit`. The Pre-commit framework just takes a configuration file and will install your desired hooks into a repo. So at commit time, it's not Pre-commit that is running, but a generated hook code file.

I was able to alter this hook code file (.git/hooks/pre-commit) to print out the environment. I basically changed the main function to start with-
```
def main():
    subprocess.call('env')
    return 1
```
This printed out the environment.

By running `type -a dotnet` I can see that the `dotnet` command is in `/usr/local/share/dotnet/dotnet`. This directory is present in my terminal PATH but not my default Fork path.

I found this [SuperUser question about altering the path and env for OS X GUI applications](https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x). This appears to be a common issue with the application launcher not mirroring any custom bash profile you may have.

It looks non-trivial, so I am happy to continue at the moment to just use `fork` from the command line. At least until I hit this problem in another guise :).

Many many many thanks for your help!
