### ISSUE TITLE
Global git config is ignored?

### ISSUE THREAD

**Issue by ElfSundae** [ForkIssues/Tracker#831]
Fork 1.0.86, macOS 10.15.1
It seems the global git config `~/.gitconfig` is ignored?

**Comment by ElfSundae** [comment]
I configured `http.proxy` in `~/.gitconfig`, but in Fork it does not work.

**Comment by DanPristupov** [comment]
You can open git bash in Fork and run `git config --list --show-origin` to see which values are used

**Comment by ElfSundae** [comment]
~~What do you mean of "open git bash in Fork"?~~

**Comment by DanPristupov** [comment]
Sorry, sometimes I'm messing between Windows and Mac issue trackers :)

 I meant the default terminal (Ctrl+Cmd+T).

**Comment by ElfSundae** [comment]
Thank you, and very sorry, my mistake.
`git config` shows OK, the list includes `~/.gitconfig`.

The remote URL is an SSH URL, the proxy configuration is effected by my SSH config `~/.ssh/config`, not `~/.gitconfig`.

**Comment by ElfSundae** [comment]
There seems different between CLI and Fork.

Steps to reproduce：

1. Edit the SSH config file `~/.ssh/config`, fill a successful configuration for github.com, e.g.

    ```ruby
    Host            github.com
    IdentityFile    ~/.ssh/id_rsa
    ```

    Test the config file:

    ```console
    $ ssh -T git@github.com
    Hi ElfSundae! You've successfully authenticated, but GitHub does not provide shell access.
    ```

2. Configure a bad proxy for github SSH:

    ```diff
      Host            github.com
      IdentityFile    ~/.ssh/id_rsa
    + ProxyCommand    nc -X 5 -x 127.0.0.1:1081 %h %p
    ```

    Test the config file:

    ```console
    $ ssh -T git@github.com
    ssh_exchange_identification: Connection closed by remote host

    $ git clone git@github.com:ForkIssues/Tracker.git
    Cloning into 'Tracker'...
    ssh_exchange_identification: Connection closed by remote host
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
    ```

3. Clone in Fork: File -> Clone... `git@github.com:ForkIssues/Tracker.git`

    **It succeeded!**

    ![image](https://user-images.githubusercontent.com/526008/69654076-2a1baf00-10af-11ea-9fe7-96bd1efeedf1.png)

    Here I don't know why the `ProxyCommand` configuration is _ignored_.

4. Add a new Custom Command in Fork:

    ![image](https://user-images.githubusercontent.com/526008/69654313-87affb80-10af-11ea-9899-bb12c28ac981.png)

    Then run this command, and it failed as expected:

    ![image](https://user-images.githubusercontent.com/526008/69654463-cf368780-10af-11ea-86f4-6e988c6426e5.png)

**Comment by DanPristupov** [comment]
~~This can be different in CLI and Fork because the process environments are different. Try to start Fork from CLI using `open -a Fork .` command.~~

P.S. Are you sure you didn't select an SSH key in the GitHub configuration in Fork (Cmd+T -> GItHub) ?

**Comment by ElfSundae** [comment]
Actually, I configured a proper proxy in the SSH config file. I'm in China, because of the [GFW](https://en.wikipedia.org/wiki/Great_Firewall), the network connection to github.com is very slow and it often fails, then I use a foreign gateway server as proxy for github.com . But in Fork, the proxy configuration is not enabled when cloning, fetch/pull/push etc, as shown in step 3.

**Comment by ElfSundae** [comment]
tried `open -a Fork .`, no difference.

**Comment by DanPristupov** [comment]
Please ensure that no ssh key is selected in the GitHub configuration. It should be 'system default'. Otherwise the ssh agent key will be overridden.

<img width="891" alt="Screenshot 2019-11-26 at 18 38 26" src="https://user-images.githubusercontent.com/618115/69658153-f1161700-107b-11ea-8e4e-8590a90e70f4.png">

**Comment by ElfSundae** [comment]
> Please ensure that no ssh key is selected in the GitHub configuration. It should be 'system default'. Otherwise the ssh agent value will be overridden.

IT WORKS! YOU ARE AWESOME! 🌹

**Comment by DanPristupov** [comment]
Actually I didn't know that the configuration of proxy + ssh (not https!) is so complicated. We should probably introduce a friendly UI for that.

**Comment by ElfSundae** [comment]
I should have changed the SSH Key config before, because there is a warning message if I select System Default.
![image](https://user-images.githubusercontent.com/526008/69659144-8931f180-10b8-11ea-877b-6d17001a3762.png)
VS
![image](https://user-images.githubusercontent.com/526008/69659325-e9c12e80-10b8-11ea-957a-00eb3c4521aa.png)

Thanks very much, you saved my life.

**Comment by ElfSundae** [comment]
I should have changed the SSH Key config before, because there is a warning message if I select System Default.
![image](https://user-images.githubusercontent.com/526008/69659144-8931f180-10b8-11ea-877b-6d17001a3762.png)
VS
![image](https://user-images.githubusercontent.com/526008/69659325-e9c12e80-10b8-11ea-957a-00eb3c4521aa.png)

Thanks very much, you saved my life.

**Comment by DanPristupov** [comment]
You are welcome. I'm glad I could help 👍.

**Comment by ElfSundae** [comment]
Some doubts:
For SSH key, the System Default does not mean`$HOME/.ssh/id_rsa.pub`?
In Fork, different ways to run built-in git commands and Custom Commands?

**Comment by DanPristupov** [comment]
This field only affects 4 git commands: clone/fetch/pull/push.

- 'System Default' means 'use the system default settings' (this one is selected, fetch will run in the same way as custom commands)
- If you select a key, it overrides SSH command using the following ENV variable: `GIT_SSH_COMMAND = ssh -i /path/to/ssh/key -F '/dev/null`

This ENV variable is the only difference between running build-in fetch/clone/push commands and the custom commands.

**Comment by ElfSundae** [comment]
I see, maybe we should remove `-F /dev/null` from `GIT_SSH_COMMAND` ? just `-i ssh/key` if any.

And for the System Default, I don't know whether the warning message "No local SSH keys registered in your GitHub account." is always shown. If so, I think we can determine the existing ssh key using `ssh -v git@github.com`.

**Comment by EnixCoda** [comment]
Hi, I am having the same issue. But I have no GitHub accounts setup in Fork. My settings are as followings.

```
> cat ~/.ssh/config
Host github.com
    User		git
    ProxyCommand	nc -X 5 -x 127.0.0.1:1080 %h %p
```

Using Fork's internal git instance.
![image](https://user-images.githubusercontent.com/7480839/126859133-d58d6a8f-8b82-4a02-a96c-e83e741e285f.png)

My repository's remote URL is SSH URL instead of HTTPS URL.

Push and pull always fail in Fork.

But push & pull work well in CLI, which indicates my proxy is working properly.

```
> git push origin refs/heads/main --verbose
Pushing to github.com:EnixCoda/repo.git
To github.com:EnixCoda/repo.git
 = [up to date]      main -> main
updating local tracking ref 'refs/remotes/origin/main'
Everything up-to-date
```

**Comment by EnixCoda** [comment]
Well, I solved my problem by switching to another DNS, which could resolve `github.com` properly. But I am still confused about why CLI always works even with a bad DNS.

**Comment by DanPristupov** [comment]
@EnixCoda ensure that all SSH keys in the SSH configuration dialog (Fork -> Configure SSH keys) are unchecked. Otherwise Fork will override ssh settings.

**Comment by EnixCoda** [comment]
@DanPristupov Thank you for the fast response! Let me see... I do have one SSH key checked in that dialog.

Now I have unchecked it and Fork can push & pull successfully! And it failed **as expected** after modifying the `proxyCommand` to make it invalid, which proves Fork is using making use of `~/.ssh/config` as expected. Great!

I get some new questions.

1. I do not remember it was myself that checked the SSH key in the SSH configuration dialog, was it automated by Fork?
    1. If so, is it necessary to check the default SSH key automatically as it will disable the default SSH config and sometimes make users confused? It is an advanced feature to my point of view, perhaps it should be disabled it by default.
2. It is a nice feature of Fork to be able to configure multiple SSH keys and switch them dynamically! IMHO it would be better if Fork could keep making use of the default SSH config file even if some of them are checked. What is the reason behind the current behavior? Or, What do you think of providing a similar dialog to the SSH keys' for SSH configs that can take effect even when SSH configs are checked?

Thank you!

**Comment by DanPristupov** [comment]
> I do not remember it was myself that checked the SSH key in the SSH configuration dialog, was it automated by Fork?

No. I guess, previously you selected SSH key in the SSH configuration for an account (GitHub or GitLab). Some time ago we moved that UI to the dedicated window for the SSH configuration, but Fork never selected a key automatically.

> It is a nice feature of Fork to be able to configure multiple SSH keys and switch them dynamically!

You can select multiple keys. But during a request there's no way to recognize what key must be used if you have multiple identities on same host.

> it would be better if Fork could keep making use of the default SSH config file even if some of them are checked.

Currently there are two ways: you either use the system config and configure it the way you want or select a key in Fork.

I'm not sure if it's possible to take the system config into account and add a custom key to it. Even if it is possible there might be a conflict between the selected key and the one in the config. Errors in SSH is very difficult to debug because by default SSH doesn't tell much info.

> What is the reason behind the current behavior?

The reason is to make both worlds happy. I you know how SSH works, then configure the SSH agent manually the way you want. If you don't know how SSH works, then select a key in the dialog and SSH authentication will work out of the box.

> What do you think of providing a similar dialog to the SSH keys' for SSH configs that can take effect even when SSH configs are checked?

Not sure if it is worth the time. First of all, I don't know which SSH agent is used. There are more than one. Second, SSH config is much more complicated than a simple list of SSH keys. There are hosts, options, etc.
