### ISSUE TITLE
Saving stash with a message does not work

### ISSUE THREAD

**Issue by HernanZh** [ForkIssues/Tracker#834]
Hi, quick thank you for making Fork, I really like it :)

Anyway, whenever I write a stash message when saving a stash, I get the following error:
```
error: pathspec 'my-stash-message' did not match any file(s) known to git
Did you forget to 'git add'?
```
This does not occur when I leave the stash message blank. 
Happens on 1.0.86 on MacOS (happened on the previous version as well, not sure when it started)

**Comment by DanPristupov** [comment]
You use an old git instance. Update it or switch Fork back to the internal one.

**Comment by HernanZh** [comment]
Ah, thanks that seems to work (updated from 2.21.0 to 2.23.0)
