### ISSUE TITLE
remote.xxx.pushurl git config cannot be changed in ui

### ISSUE THREAD

**Issue by jounii** [ForkIssues/Tracker#836]
I had need to change the remote url of the repository. I did this from the Fork's dialog for editing the remote url, however for some reason the pushes were still failing. By manually checking the .git/config I noticed there was pushurl value and there's no way of changing it in the Fork's UI right now.

https://git-scm.com/docs/git-config#Documentation/git-config.txt-remoteltnamegtpushurl

**Comment by DanPristupov** [comment]
Hi. Could that be the issue https://github.com/ForkIssues/TrackerWin/issues/505?

**Comment by jounii** [comment]
Yes same thing. I tried to search, but obviously it was only for open issues and those are closed. So it's kind of okay, but I'd say it's bug/missing feature. Also SourceTree is probably to "blame" having the pushurl there in the first place.

**Comment by DanPristupov** [comment]
No problem. It's in the Windows tracker, so that's why you couldn't find it :).

Not sure if I should handle this. I don't want to silently remove or edit `pushurl` in the user repo.

**Comment by jounii** [comment]
It's tricky thing. Probably would myself edit it "silently" if it's same as the url and/or provide field in the UI for that as well. If it's different, then there's probably some "advanced" reason.

SourceTree seems to just edit both to same values and for remote's url display it uses pushurl if it's available.
