### ISSUE TITLE
Merge commit uses refs/heads/<branch> instead of <branch>

### ISSUE THREAD

**Issue by albertopesquerabrooktec** [ForkIssues/Tracker#837]
Hello!
I have not been able to find any issue about this. Sorry if I'm duplicating issues.
For some time every merge I do has "refs/heads" in it's commit message. It happens to both fork git instance and computer git instance. I'm using Fork version 1.0.86.
Is there any way to have `Merge branch 'develop'` only as message?
Thanks!

**Comment by DanPristupov** [comment]
Hi. Thank you for asking. I was also confused, but could not find the problem. After your post I tried again and found out that it's actually a result of a change in Fork. I already fixed the problem and the fix will be available in the 1.0.87 update which is planned for tomorrow evening. Sorry for the inconvenience.

**Comment by albertopesquerabrooktec** [comment]
Wow... That was really fast! Thank you!
