### ISSUE TITLE
How to know the properfies (such as remote address) of a repo?

### ISSUE THREAD

**Issue by eviluess** [ForkIssues/Tracker#838]
Hey guys,
I need "git remote -v" to get the remote address in terminal.
I'm not so familiar with the commands above.
So if fork can view the properties of a repo, it will be sweet.

Thanks!

**Comment by DanPristupov** [comment]
<img width="288" alt="Screenshot 2019-12-01 at 11 08 55" src="https://user-images.githubusercontent.com/618115/69912544-fcc25e80-142a-11ea-87e9-8047d0f498dc.png">
<img width="295" alt="Screenshot 2019-12-01 at 11 10 10" src="https://user-images.githubusercontent.com/618115/69912557-2da29380-142b-11ea-874c-f1102306aa5f.png">

**Comment by eviluess** [comment]
Thank you, Dan!
