### ISSUE TITLE
Open link in `git push` output

### ISSUE THREAD

**Issue by Turbo87** [ForkIssues/Tracker#839]
GitHub and GitLab both provide a URL in the output of `git push`. It would be great if the "Push" dialog had a checkbox to automatically open that URL in the browser.

Currently you have to open the "Activity Manager", scroll in the output and click the link. Opening it automatically would speed up that process significantly :)

One possible improvement would be to enable this option automatically for **new** branches and disable it when pushing to an existing branch.

Now that I see it, this might be related to https://github.com/ForkIssues/Tracker/issues/659

**Comment by DanPristupov** [comment]
> It would be great if the "Push" dialog had a checkbox to automatically open that URL in the browser.

No, there's already too many options.

> Currently you have to open the "Activity Manager", scroll in the output and click the link.

I think the solution could be to always scroll to the end of output. Then you only need one click on the status control to see the link.
