### ISSUE TITLE
[Feature parity requesst] side-by-side diff: main window and word-wrapping

### ISSUE THREAD

**Issue by daviehh** [ForkIssues/Tracker#841]
Compared with the windows version screen capture at https://fork.dev/blog/posts/forkwin-1.38/ , side-by-side diff is enabled in the main gui window but on mac it's in a second-level right-click/spacebar; also, looks like there's no option to have word-wrap for long lines in the side-by-side diff on mac (latest Version 1.0.87.3). Thanks a lot!

**Comment by mclarkos** [comment]
I would love to see this as well. For me, the "Side by side diff" button is missing for files in the "Changes" area. It does exist for files under "All Commits" as a button to the right of button "Show entire file".
