### ISSUE TITLE
Icons in source list become blocks on Sierra when row is selected

### ISSUE THREAD

**Issue by devtimi** [ForkIssues/Tracker#843]
Mac OS Sierra 10.12.6
Fork 1.0.87.2
Fork in dark mode, system in light mode

![Screen Shot 2019-12-07 at 7 55 56 PM](https://user-images.githubusercontent.com/2067469/70382551-23e9c600-192c-11ea-8def-9565f351c537.png)

**Comment by DanPristupov** [comment]
It will be very tricky to fix this. I don't have ability to test on Sierra.

I think we can't keep the dark mode feature in old systems (macOS <10.14) any longer.

**Comment by DanPristupov** [comment]
A similar issue: https://github.com/ForkIssues/Tracker/issues/586

**Comment by devtimi** [comment]
Gosh, that's a disappointment but I do understand. If I can be of any help with my system let me know.
