### ISSUE TITLE
[Bug] Merge conflict: Theirs and Ours switched

### ISSUE THREAD

**Issue by Lonli-Lokli** [ForkIssues/Tracker#846]
In case of solving conflicts during rebase
Theirs means actually local branch
Ours - origin

So when I select resolve Mine it's actually choosing changes from origin

**Comment by DanPristupov** [comment]
This is how git works: https://stackoverflow.com/a/25576672/6116850

**Comment by Lonli-Lokli** [comment]
That's completely frustrating. 
Thanks for sharing.
