### ISSUE TITLE
Fork fails to update from 1.0.87.2 to 1.0.88

### ISSUE THREAD

**Issue by gkopff** [ForkIssues/Tracker#850]
**Fork fails to update from 1.0.87.2 to 1.0.88**

It downloads the update, and then proceeds to 'Extracting update ...'  However, this then reports:

**Update Error!**

An error occurred while extracting the archive. Please try again later.

**Comment by DanPristupov** [comment]
Try to check for updates again. Sometimes it has some glitch.

**Comment by gkopff** [comment]
I've tried 4 or 5 times over the last few days, and the same thing happens.  I will persevere and report back on my progress in a few more days.

**Comment by mattcroxson** [comment]
Attempting to update using `brew cask upgrade fork` returns this: 

```
==> Upgrading fork
==> Downloading https://forkapp.ams3.cdn.digitaloceanspaces.com/mac/Fork-1.0.88.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'fork'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
==> Purging files for version 1.0.88 of Cask fork
Error: Checksum for Cask 'fork' does not match.
Expected: 3ca47cb7fc2cc01b5a57cb22b78c73d173861d47f1c7878db7439b8332618f37
  Actual: a79a625003884cf10fbd2347f65b253e95f8654a5fcf8826c6a81650663982a6
```

I tried updating brew like it suggested and it didn't help. Updating also fails using the in-app updater. 

Is there a log file we can send you from the app to help diagnose?

**Comment by DanPristupov** [comment]
Interesting. I just downloaded versions from both the website and the CDN. They match the expected Checksum

https://forkapp.ams3.cdn.digitaloceanspaces.com/mac/Fork-1.0.88.dmg
https://git-fork.com/update/files/Fork.dmg

```
$ shasum -a 256 Fork-1.0.88.dmg
3ca47cb7fc2cc01b5a57cb22b78c73d173861d47f1c7878db7439b8332618f37  Fork-1.0.88.dmg
```

**Comment by mattcroxson** [comment]
Hi Dan, 

I just downloaded the DMG from both locations manually in Safari. The `git-fork.com` link seems good (checksum matches, DMG opens etc.) but the CDN is not

This is the result of the checksum:
```
$ shasum -a 256 Fork-1.0.88.dmg 
a79a625003884cf10fbd2347f65b253e95f8654a5fcf8826c6a81650663982a6  Fork-1.0.88.dmg
```

When I try to open the DMG in Finder I get this:
<img width="484" alt="Screen Shot 2019-12-19 at 08 07 59" src="https://user-images.githubusercontent.com/874405/71123403-ae88ca00-2236-11ea-8b8d-f354d93d9b51.png">

This is the size of the actual file.
<img width="377" alt="Screen Shot 2019-12-19 at 08 08 35" src="https://user-images.githubusercontent.com/874405/71123495-e5f77680-2236-11ea-890b-d8aa03c9708b.png">

**Comment by DanPristupov** [comment]
Looks like the CDN-server which is close to you (Singapore?) has a wrong copy of the file. I've never seen this in real life, but this must be the case.

I just cleared the cache for the file on all edges (end-servers). Could you try to download the file again and check it?

**Comment by mattcroxson** [comment]
I am in Melbourne, Australia but not knowing where Digital Ocean has their CDN clusters its possible the file was coming from Singapore.

Downloaded the file again everything looks good now. 

- File has the correct checksum
- The image will decompress and mount. The contained app runs.
- The in-app updater is also working (tested upgrading from version 1.0.87.2).

Thanks Dan! 😄 

Edit: trying to find out where Digital Ocean have their edge locations lead me to this article on their website specifically regarding the AMS3 location that is in the URL you posted earlier. It's possible that it's unrelated, but thought you might like to know just in case. https://www.digitalocean.com/docs/platform/release-notes/2019/spaces-ams3/

**Comment by gkopff** [comment]
I'm Queensland, Australia.  I tried the auto-update again from the app and it installed successfully.  Thank you @DanPristupov.
