### ISSUE TITLE
[Feature Request] Search Branch names

### ISSUE THREAD

**Issue by EdenTurgeman** [ForkIssues/Tracker#854]
The current search feature is awesome, but i find myself daily wanting to search branch names and not being able to.
The current search feature allows for SHA, author and message.
![image](https://user-images.githubusercontent.com/12447231/71557131-b15f9800-2a4a-11ea-9a7a-be33bfba2980.png)
Would love to see support for searching branch names as part of that list.

**Comment by bstrobach** [comment]
Also, searching for tags would be nice.

**Comment by maksimovic** [comment]
On the left pane, at the bottom, there's a filter for branches/tags/stashes.

**Comment by DanPristupov** [comment]
> The current search feature allows for SHA, author and message.

It also takes branches and tags into account

**Comment by EdenTurgeman** [comment]
@DanPristupov Just realized it did, but the marking for it is really bad and i couldn't notice it did it's work
