### ISSUE TITLE
[Feature Request] Quick Launch should navigate to existing tab of a repository, if the tab exists 

### ISSUE THREAD

**Issue by anupam-gh** [ForkIssues/Tracker#856]
The `File ➝ Quick launch…` command should navigate to the tab of the chosen repository if the tab has already been opened earlier. If the selected repository is _not_ already open, then a _new_ tab can be opened (this can be a preference setting as well).

The current behavior is to _replace_ the current tab content with the selected repository.

The rationale for this request is that one might have multiple tabs already open across various repositories (with the tabs ordered in a particular way), and in this scenario, the `Quick Launch…` command can become useful for quickly _navigating_ to a repository tab.

**Comment by oyarzun** [comment]
@anupam-gh this is fixed in v2.25.1. see #1750
