### ISSUE TITLE
High energy use in steady state

### ISSUE THREAD

**Issue by IanVS** [ForkIssues/Tracker#858]
I just started trying out Fork after having used gitx for several years, and so far I'm really loving it!  I did notice, however, that it's pretty power-hungry.  While sitting around seemingly doing nothing for at least the last 5 minutes, it's at >100 "energy impact" in the activity monitor, and using pretty much a full core.  I'm on Catalina, fwiw.

![image](https://user-images.githubusercontent.com/4616705/71627387-20aac880-2bc0-11ea-87e0-31fbfcd181c4.png)

![image](https://user-images.githubusercontent.com/4616705/71627424-4f28a380-2bc0-11ea-87ff-c442b4e97e57.png)

![image](https://user-images.githubusercontent.com/4616705/71627430-59e33880-2bc0-11ea-8a69-93fef6a89064.png)

<details>
<summary>Open files and ports</summary>
cwd
/
txt
/Applications/Fork.app/Contents/MacOS/Fork
txt
/Applications/Fork.app/Contents/Frameworks/SQLite.framework/Versions/A/SQLite
txt
/Applications/Fork.app/Contents/Frameworks/XCGLogger.framework/Versions/A/XCGLogger
txt
/Applications/Fork.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
txt
/Applications/Fork.app/Contents/Frameworks/Paddle.framework/Versions/A/Paddle
txt
/Applications/Fork.app/Contents/Frameworks/ObjcExceptionBridging.framework/Versions/A/ObjcExceptionBridging
txt
/Library/Preferences/Logging/.plist-cache.JDhFdCfv
txt
/usr/share/icu/icudt64l.dat
txt
/private/var/db/timezone/tz/2019c.1.0/icutz/icutz44l.dat
txt
/private/var/db/dyld/dyld_shared_cache_x86_64h
txt
/Library/Caches/com.apple.iconservices.store/DDF6B0E6-4DB6-31FC-AA8D-1E50500B56F8.isdata
txt
/Library/Caches/com.apple.iconservices.store/C29955AD-29E2-3536-B5EB-E28BDBE819C2.isdata
txt
/System/Library/Frameworks/Security.framework/Versions/A/PlugIns/csparser.bundle/Contents/MacOS/csparser
txt
/Library/Caches/com.apple.iconservices.store/E4C98D48-177C-3E45-8CB0-1C4ED162ABC4.isdata
txt
/Applications/Fork.app/Contents/Resources/Terminal.png
txt
/Applications/Fork.app/Contents/Resources/CheckMark.png
txt
/Library/Caches/com.apple.iconservices.store/62352E24-036D-3C2B-BEC5-7954AC8D622B.isdata
txt
/Library/Caches/com.apple.iconservices.store/C3D42A4E-E4D7-3C9D-A359-229518DF56FA.isdata
txt
/Library/Caches/com.apple.iconservices.store/CB583E8D-A7CC-3E75-B55F-5D4A33605516.isdata
txt
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/Base.lproj/NSTextTouchBarItems.nib
txt
/Library/Caches/com.apple.iconservices.store/C09E5831-D9E1-3CEA-9344-9F6C0037AD98.isdata
txt
/System/Library/Fonts/Keyboard.ttf
txt
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/NSAppearanceNameCandidateBar.car
txt
/Library/Caches/com.apple.iconservices.store/4FCB9E0B-0888-3264-A5DD-D5EBB3FF32FE.isdata
txt
/Library/Caches/com.apple.iconservices.store/6757EC14-7CCB-3EEF-9509-5A63483FCB27.isdata
txt
/Library/Caches/com.apple.iconservices.store/D85FAD50-EA04-3B5F-9676-D989D5CE7EAD.isdata
txt
/Applications/Fork.app/Contents/Resources/icon_128x128.png
txt
/Library/Caches/com.apple.iconservices.store/B5143E6D-623A-3CF8-A58E-F6704FF5DAAE.isdata
txt
/System/Library/LinguisticData/Latn/Dict2.dat
txt
/Library/Caches/com.apple.iconservices.store/92A7FC41-99B4-3F7F-8065-B57CD578FEDB.isdata
txt
/System/Library/Extensions/AMDRadeonX6000GLDriver.bundle/Contents/MacOS/AMDRadeonX6000GLDriver
txt
/Library/Caches/com.apple.iconservices.store/4236BF9D-7B61-30DD-8AF8-34FF213E0AC2.isdata
txt
/Applications/Fork.app/Contents/Resources/GitLab.png
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/SystemAppearance.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkAquaAppearance.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkAppearance.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Assets.car
txt
/System/Library/Fonts/SFNS.ttf
txt
/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Resources/Extras2.rsrc
txt
/Applications/Fork.app/Contents/Resources/QuickSearch.png
txt
/Applications/Fork.app/Contents/Resources/Swap.png
txt
/Applications/Fork.app/Contents/Resources/Fetch.png
txt
/Applications/Fork.app/Contents/Resources/Pull.png
txt
/Applications/Fork.app/Contents/Resources/Push.png
txt
/Applications/Fork.app/Contents/Resources/HistoryMenu.png
txt
/private/var/folders/8v/nt6q98150ss138rdc78htqxr0000gn/C/com.DanPristupov.Fork/com.apple.metal/3902/libraries.data
txt
/private/var/folders/8v/nt6q98150ss138rdc78htqxr0000gn/C/com.DanPristupov.Fork/com.apple.metal/Intel(R) UHD Graphics 630/functions.data
txt
/Users/ianvs/Library/Caches/com.DanPristupov.Fork/Cache.db-shm
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantLightAppearance.car
txt
/System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/AppleKeyboardLayouts-L.dat
txt
/System/Library/Caches/com.apple.IntlDataCache.le.kbdx
txt
/usr/lib/libobjc-trampolines.dylib
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FunctionRowAppearance.car
txt
/System/Library/Frameworks/FileProvider.framework/OverrideBundles/CloudDocsFileProvider.bundle/Contents/MacOS/CloudDocsFileProvider
txt
/Applications/Fork.app/Contents/Resources/Assets.car
txt
/System/Library/Fonts/Helvetica.ttc
txt
/System/Library/Fonts/Menlo.ttc
txt
/Library/Caches/com.apple.iconservices.store/62CF8DDB-6E3C-3425-A826-CCE4D8195B57.isdata
txt
/Applications/Fork.app/Contents/Resources/BitBucket.png
txt
/System/Library/PrivateFrameworks/MarkupUI.framework/PlugIns/Markup.appex/Contents/Resources/Icon_Template.pdf
txt
/Library/Caches/com.apple.iconservices.store/7D2DCD26-8ECC-3E18-A044-72E33B22F16F.isdata
txt
/Library/Caches/com.apple.iconservices.store/26F788BE-51C4-3FAE-8269-819E980F42DE.isdata
txt
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/Assets.car
txt
/System/Library/Frameworks/FileProvider.framework/OverrideBundles/FileProviderOverride.bundle/Contents/MacOS/FileProviderOverride
txt
/System/Library/Frameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride
txt
/Library/Caches/com.apple.iconservices.store/DA21AD4E-FC80-32D0-AFEA-9E9DA48F544B.isdata
txt
/private/var/db/analyticsd/events.whitelist
txt
/Applications/Fork.app/Contents/Resources/GitHub.png
txt
/private/var/db/mds/messages/501/se_SecurityMessages
txt
/System/Library/LinguisticData/Latn/Dict1.dat
txt
/System/Library/PrivateFrameworks/ShareKit.framework/Versions/A/Resources/Assets.car
txt
/System/Library/Fonts/SFCompactText.ttf
txt
/System/Library/PrivateFrameworks/MarkupUI.framework/PlugIns/Markup.appex/Contents/Resources/Assets.car
txt
/usr/share/langid/langid.inv
txt
/System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/Resources/tokruleLE.data
txt
/System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/Resources/com.apple.datadetectorscore.cache.urlifier.system
txt
/System/Applications/Notes.app/Contents/PlugIns/com.apple.Notes.SharingExtension.appex/Contents/Resources/Assets.car
txt
/System/Library/Fonts/HelveticaNeue.ttc
txt
/System/Applications/Reminders.app/Contents/PlugIns/RemindersSharingExtension.appex/Contents/Resources/Assets.car
txt
/System/Library/MessageTracer/SubmitDiagInfo.default.domains.searchtree
txt
/Library/Caches/com.apple.iconservices.store/B0847487-25A3-36F0-A0CF-85E00F4389F6.isdata
txt
/System/Applications/Mail.app/Contents/PlugIns/MailShareExtension.appex/Contents/Resources/Assets.car
txt
/System/Applications/Mail.app/Contents/PlugIns/MailShareExtension.appex/Contents/Resources/ApplicationIcon.icns
txt
/System/Library/Fonts/\xe3\x83\x92\xe3\x83\xa9\xe3\x82\xad\xe3\x82\x99\xe3\x83\x8e\xe8\xa7\x92\xe3\x82\xb3\xe3\x82\x99\xe3\x82\xb7\xe3\x83\x83\xe3\x82\xaf W3.ttc
txt
/System/Library/Assets/com_apple_MobileAsset_LinguisticData/70e3cbe8b7828d1e6545ca9e1d477d23a26644b9.asset/AssetData/pos.dat
txt
/System/Applications/Messages.app/Contents/PlugIns/Messages Reply Extension.appex/Contents/Resources/MessagesAppIcon.icns
txt
/System/Applications/Messages.app/Contents/PlugIns/Messages Share Extension.appex/Contents/Resources/MessagesAppIcon.icns
txt
/System/Library/Fonts/ArabicUIText.ttc
txt
/System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/Resources/com.apple.datadetectorscore.cache.full.europe.system
txt
/System/Library/Fonts/Kohinoor.ttc
txt
/usr/lib/dyld
txt
/System/Library/Fonts/Apple Color Emoji.ttc
txt
/System/Library/Fonts/AppleSDGothicNeo.ttc
txt
/System/Library/Assets/com_apple_MobileAsset_LinguisticData/70e3cbe8b7828d1e6545ca9e1d477d23a26644b9.asset/AssetData/ner_v2.dat
txt
/usr/share/germantok/german.index
txt
/private/var/folders/8v/nt6q98150ss138rdc78htqxr0000gn/0/com.apple.LaunchServices.dv/com.apple.LaunchServices-1080-v2.csstore
0
/dev/null
1
/dev/null
2
/dev/null
3
4
/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_stdlib.metallib
5
/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_filters.metallib
6
/private/var/folders/8v/nt6q98150ss138rdc78htqxr0000gn/C/com.DanPristupov.Fork/com.apple.metal/3902/libraries.maps
7
/private/var/folders/8v/nt6q98150ss138rdc78htqxr0000gn/C/com.DanPristupov.Fork/com.apple.metal/3902/libraries.data
8
/private/var/folders/8v/nt6q98150ss138rdc78htqxr0000gn/C/com.DanPristupov.Fork/com.apple.metal/Intel(R) UHD Graphics 630/functions.maps
9
/private/var/folders/8v/nt6q98150ss138rdc78htqxr0000gn/C/com.DanPristupov.Fork/com.apple.metal/Intel(R) UHD Graphics 630/functions.data
10
/Users/ianvs/Library/Logs/Fork.log
11
/Users/ianvs/Library/Application Support/com.DanPristupov.Fork/db.sqlite3
12
->0xec657e061446dafb
13
/System/Library/MessageTracer/SubmitDiagInfo.default.domains.searchtree
14
15
/Users/ianvs/Library/Saved Application State/com.DanPristupov.Fork.savedState/window_1.data
16
/Users/ianvs/Library/Saved Application State/com.DanPristupov.Fork.savedState/data.data
17
/Users/ianvs/Library/Saved Application State/com.DanPristupov.Fork.savedState/windows.plist
18
19
20
21
/Users/ianvs/Library/Saved Application State/com.DanPristupov.Fork.savedState/window_2.data
22
23
24
/Users/ianvs/Library/Caches/com.DanPristupov.Fork/Cache.db
25
26
/Users/ianvs/Library/Caches/com.DanPristupov.Fork/Cache.db-wal
27
/Users/ianvs/Library/Caches/com.DanPristupov.Fork/Cache.db-shm
28
FNetwork.defaultStorageSession
29
30
[ctl com.apple.netsrc id 7 unit 29]
31
32
33
36
39
40
45

</details>

Is this behavior normal?  Is there anything else I can check on to see if it's contributing?

Edit: More details.  I quit and re-opened, and it seems to be back to normal, with nearly zero cpu usage.  Prior to noticing the 100% usage, I had used the beta merge-confict tool built into fork (on a very large file), I wonder if that could have something to do with it.  I'll keep my eyes peeled for it happening again.

**Comment by DanPristupov** [comment]
I never experienced this problem myself. Please let me know if the problem occurs again.

**Comment by barrylustig** [comment]
![image](https://user-images.githubusercontent.com/11999741/71635859-44303c00-2bdd-11ea-8749-878442ada1ad.png)

You can always grab a sample.  See the bottom left of the window.  Or even better, a spindump:

![image](https://user-images.githubusercontent.com/11999741/71635872-6de96300-2bdd-11ea-97f3-5233cd1d10d4.png)

**Comment by IanVS** [comment]
Thanks @barrylustig, I'll do that if/when it happens again.
