### ISSUE TITLE
Licensed and Non-Licensed version

### ISSUE THREAD

**Issue by L1cardo** [ForkIssues/Tracker#859]
I have a question: 
 - What is the differences between Licensed and Non-Licensed version. or is it just a donation method ?

I am s student who is using fork for over six month and found it really amazing. I want to know the differences between Licensed and Non-Licensed version so that I can decide whether to pay.
I want to make a donation for such an amazing app, but $49.9 is a bit high.

**Comment by Niid** [comment]
Hi ! For now this is just a donation method, and then it will basically get mandatory to get a license to support the devs. It is a one-time purchase, see [Forkissues/TrackerWin#571](https://github.com/ForkIssues/TrackerWin/issues/571) for more info. 

The announcement has been made on the Windows bug tracker but it's quite safe to assume that this is valid for both Windows and IOS.

**Comment by DanPristupov** [comment]
It was also here: https://github.com/ForkIssues/Tracker/issues/562#issuecomment-553339374

**Comment by tbm98** [comment]
Hi @DanPristupov.
I think so.
Many students cannot afford to pay $ 50. I think it is advisable to limit some functions to the users who have activated.
I am also a student.

**Comment by DanPristupov** [comment]
We are not going to block the application (or any particular features) in the non-licensed version. If you can't pay for Fork right now, just use it and don't mind :). If in the future Fork helps you to earn money, please consider buying it.

**Comment by tbm98** [comment]
Oh Thank you!
In the future I will buy it if I can. Thank you very much!

**Comment by Someguynamedpie** [comment]
> 
> 
> We are not going to block the application (or any particular features) in the non-licensed version. If you can't pay for Fork right now, just use it and don't mind :). If in the future Fork helps you to earn money, please consider buying it.

I deeply appreciate this stance, and this alone has convinced me to pay at my nearest capability. I am pretty concerned by the activation limit however as I have several development machines (2 work, 3 personal) so please reconsider either upping it or removing it (and revocation of abusers, of course)

**Comment by ChadTaljaardt** [comment]
If you aren't going to block any features from the non licensed versions, why is there an activation limit?

**Comment by rbq** [comment]
I would like to buy, but I don't want any of the disadvantages DRM introduces, such as software phoning home, depending on a remote licensing server, not working after migrating to a new machine, etc. Could you introduce an option to just buy a license and use Fork without any additional anti-features? I just want to pay, not deal with any of that "activation" nonsense.

**Comment by DanPristupov** [comment]
@rbq We have limited resources and don't have time to support multiple versions.

**Comment by lexxmt** [comment]
> I would like to buy, but I don't want any of the disadvantages DRM introduces, such as software phoning home, depending on a remote licensing server, not working after migrating to a new machine, etc. Could you introduce an option to just buy a license and use Fork without any additional anti-features? I just want to pay, not deal with any of that "activation" nonsense.

let me know when you get version without DRM protection / Will be happy to buy it.
