### ISSUE TITLE
Merge conflict with deleted and modified file: weird behaviour

### ISSUE THREAD

**Issue by bdgeyter** [ForkIssues/Tracker#86]
Recently had a merge conflict where a file had been deleted on one branch and modified on the other. In the merge conflict resolver, it showed both options, and I selected the side where the file had been deleted. Clicking merge then resulted in that file actually being added to the staged changes instead of being deleted. Don't know if this is an issue with Git, but either way, it's definitely not what you'd expect from the UI in that case.

**Comment by DanPristupov** [comment]
@bdgeyter thank you for reporting that problem. I'm going to release Fork update tomorrow and then will investigate this issue with highest priority.

**Comment by DanPristupov** [comment]
@bdgeyter I've reproduced and fixed that problem. The fix will be available in 1.0.56.
Thank you very much!

**Comment by bdgeyter** [comment]
Nice!! Glad you could reproduce and got it fixed so quickly.
