### ISSUE TITLE
[Feature Request] Home page button

### ISSUE THREAD

**Issue by L1cardo** [ForkIssues/Tracker#860]
It would be nice if we can have a button to return to home page(repo manager)
![image](https://user-images.githubusercontent.com/33802186/71643266-5d76dc80-2cf2-11ea-878f-c0b2d52dd385.png)
![image](https://user-images.githubusercontent.com/33802186/71643273-754e6080-2cf2-11ea-88af-ffafe4bac493.png)

**Comment by DanPristupov** [comment]
The repository manager is located on the new tab (Cmd+T)

**Comment by L1cardo** [comment]
@DanPristupov I know this , but I want to go back to repo manager without any repo remaining open.
Now I have to open a new tab and close the previous tab

**Comment by MathiasCodes** [comment]
@L1cardo You can just close the open tab with [Ctrl+W], then the repo manager gets displayed. No need to open a new tab first.

**Comment by L1cardo** [comment]
@Kromi75 Thanks dude! This will work!
But is there any button that I can click with my mouse? Because I am more a mouse-person than keyboard.

**Comment by MathiasCodes** [comment]
Well, it depends. Problem is, the macOS version hides the tab title bar completely when only one tab is open. There's an x button each tab title that appears when the mouse is hovering over it, but that doesn't help if you have only one open tab.
In the Windows version, the tab title is also visible when only one tab is open, so there you have a button.
