### ISSUE TITLE
Clone dialogue doesn't clear after clone/cancel

### ISSUE THREAD

**Issue by carlwhittick** [ForkIssues/Tracker#862]
After cloning a repository I would expect the **Repository Url** and the **Name** fields in the dialogue to be empty if I reopen the dialogue to clone another repo. Instead it is still populated with the last cloned items URL and name.

This is a small thing but when cloning a few repos it would be nice to not have to clear the fields before the auto copy/paste code kicks in! 

P.S. Thank you for making such a great tool! 👍

**Comment by DanPristupov** [comment]
The clone dialog tries to automatically parse the url in your clipboard.
