### ISSUE TITLE
Cloning from Bitbucket doesn't Rescan Repositories

### ISSUE THREAD

**Issue by matkatmusic** [ForkIssues/Tracker#864]
I cloned via the window that lets me see all of my repos in my bitbucket account.  The clone completed successfully, but I had to manually "Rescan Repositories" before the cloned one showed up.  It would be nice if the refresh happened automatically after cloning from our own online repos.

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/Tracker/issues/853

**Comment by DanPristupov** [comment]
Fixed in 1.0.89.
