### ISSUE TITLE
[Prerelease] 1.0.89

### ISSUE THREAD

**Issue by DanPristupov** [ForkIssues/Tracker#865]
Hi guys!

✨

During the holidays we made some big changes in order to improve performance for large repos. On our side everything seems to be working properly, but it would be great if you could also try the update in your environment.

All the changes are related to visualization. In other words, you can safely use this build in production.

Changelist:

* Improved filter performance (This could be interesting to @stk-ableton, @mtschoen-unity, @maksimovic)
* Faster branch operations (checkout, create branch, etc)
* Faster commit
* Experimental: First-parent mode (https://github.com/ForkIssues/Tracker/issues/220, https://github.com/ForkIssues/Tracker/issues/227)
* Fixed: Repositories not updated after clone (https://github.com/ForkIssues/Tracker/issues/853, https://github.com/ForkIssues/Tracker/issues/864)

I would be really glad to hear some feedback or comments.

Here's the download link:
🤞https://cdn.fork.dev/prerelease/Fork-1.0.88.10.dmg

**Comment by maksimovic** [comment]
Filtering seems to be very fast now - almost instant when e.g. showing commits from a particular branch only. Also, find-as-you-type is pretty much instant. Not sure if it was bumped in this version, though. One thing that's annoying there for me is that after clearing the search the "Tags" group remains expanded, which is in my case a list of 6500+ tags, burying Stashes and submodules all the way down.

Branch / commit operations seem to be even faster now.

Overall, I like this update 🎉 

P.S. Aren't holidays supposed to be spent by actually not working? 😁

**Comment by DanPristupov** [comment]
Ouch, I didn't expect such a quick response😀. It took me longer to type my initial message :).

> One thing that's annoying there for me is that after clearing the search the "Tags" group remains expanded, which is in my case a list of 6500+ tags, burying Stashes and submodules all the way down.

Did the problem exist in 1.0.88?

A related info: in an upcoming update (1.0.89-90) we will make the sidebar show only limited number of recent tags (15 may be) and a "Show all tags" button.

> Aren't holidays supposed to be spent by actually not working?

Those were long holidays this year so I had much time to figure out :).

**Comment by maksimovic** [comment]
> Ouch, I didn't expect such a quick response😀

I just came back from my lunch break so I had time to test. I'd probably forget to do it if I were to save it for later 🙄 😁 

> Did the problem exist in 1.0.88?

I think yes. Remotes were also kept as expanded if I remember correctly, but maybe that's been fixed earlier? I remember having to collapse a lot after performing a search... Now just the tags are getting expanded and staying that way - although they don't even contain a match.

**Comment by DreierF** [comment]
Really nice 🙂Thank you for this great app
Have been wistfully waiting for First-parent mode since I started using Fork 🎉
I would have intuitively expected the "First parent mode" to be available in the filter bar that is shown when filtering on a specific branch. Would also make it easier to discover it.
