### ISSUE TITLE
[Feature Request/Question] Open project tree after clone

### ISSUE THREAD

**Issue by DmitryZemlyuk** [ForkIssues/Tracker#870]
macOS Catalina 10.15.1 (19B88)
Hi. How can we open project tree after clone from Fork? Need clone project and then go to File->Open and choose cloned project. This is not very convenient if I have a lot of projects.

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/Tracker/issues/853

**Comment by DanPristupov** [comment]
Fixed in 1.0.89.

**Comment by DmitryZemlyuk** [comment]
Fixed, thanks =)
