### ISSUE TITLE
Question: Issue with github auth, cannot find private repo

### ISSUE THREAD

**Issue by willemodendaal** [ForkIssues/Tracker#871]
Thanks for a fantastic tool, I really like Fork. It's top quality.

This is probably not a bug, but more likely me not understanding how the system works.

Under /services/github, by account is authenticated, and online, and has an associated SSH key (the green tick below the ssh key dropdown says "SSH key '***' configured properly". So everything looks in order.

However, when I try to fetch or push to my remote on github (a private repo that falls under an organization), I get "remote: Repository not found." errors.

If I try fetching/pushing via the commandline however (same folder), everything works fine. Do I need to do special config to get Fork to use my github credentials somehow?

**Comment by DanPristupov** [comment]
Are you sure you use SSH protocol?
The protocol is defined by the remote server url (right click on remote -> 'Edit').

- If url starts with https://, then login/password will be used.
- If url start with git@ or ssh://, then the private key will be used.

**Comment by willemodendaal** [comment]
Ah, that was the issue. I was using HTTP. I didn't realize Fork needed SSH.

Thanks a mil.
