### ISSUE TITLE
[Feature Request] Detect git installed via brew

### ISSUE THREAD

**Issue by Stanzilla** [ForkIssues/Tracker#876]
Might be nice to automatically detect the git version installed via brew, it's at `/usr/local/bin/git` and my Fork only detected the version at `/usr/bin/git` which is the Apple version

**Comment by DmitryZemlyuk** [comment]
Hi. You can choose custom Git  instance from Fork preferences. If I understood correctly, I think this is your best option for now.
![Screenshot at Jan 21 09-57-31](https://user-images.githubusercontent.com/9571965/72785704-7e1cbd00-3c34-11ea-95e7-2b170608fc82.png)

**Comment by DanPristupov** [comment]
I suppose he meant that Fork should detect an installed brew version and add it to the dropdown as well.

**Comment by DmitryZemlyuk** [comment]
Yes, I suppose it is, but there's always the temporary fix while we wait for feature implementation. =)

**Comment by Stanzilla** [comment]
Yes I did, sorry for being unclear :)

**Comment by DanPristupov** [comment]
In 1.0.89 brew git instance must be identified as you asked. Could you please check if it works as expected?

**Comment by Stanzilla** [comment]
I now have it twice because I had added it manually before but otherwise, nice! :)

**Comment by lhaeger** [comment]
While you're still at it: please also auto-detect git installed via [MacPorts](https://www.macports.org/) at /opt/local/bin/git... :-)
