### ISSUE TITLE
[Feature request] Ability to give a repo a custom display name instead of using its directory name

### ISSUE THREAD

**Issue by vilya** [ForkIssues/Tracker#877]
I'd like to be able to give my repos a name for display in the UI without having to change the name of the directory it's checked out into.

The reason is that I unfortunately have to work with several repos at the moment where the directory containing .git is called 'src'. When I have them all open in Fork it's very hard to tell which tab is for which repo, but I can't just rename the 'src' directories to something more sensible because that would break the build scripts.

Is this possible now? Or if not, could it be added?

**Comment by vilya** [comment]
For reference, this is what Fork looks like for me with these projects open:
![image](https://user-images.githubusercontent.com/109662/72751716-440dd580-3bb8-11ea-971c-c17e08108982.png)

**Comment by DanPristupov** [comment]
You can do that in repository manager (Cmd+T):
<img width="319" alt="Screenshot 2020-01-20 at 20 24 54" src="https://user-images.githubusercontent.com/618115/72752605-edf25f80-3bc2-11ea-83e2-baa5248a4b74.png">

**Comment by vilya** [comment]
Brilliant, thanks - that's exactly what I wanted!

I don't spend much time in the repository manager so it just never occurred to me to look there - I thought it would be somewhere in the repository settings popup if anywhere.

Thanks again!
