### ISSUE TITLE
Scrollbar in diff window is disappeared

### ISSUE THREAD

**Issue by ElfSundae** [ForkIssues/Tracker#88]
v1.0.54.1

![qq20170903-030523](https://user-images.githubusercontent.com/526008/29998097-c1dd7a5e-9054-11e7-9366-4dead8c611e1.png)

When I open a new tab, this scrollbar is always disappeared, so I can not scroll the diff window horizontally using a Mouse. At this time, I can get it back if I switch scrollbar options in System Preferences:

![image](https://user-images.githubusercontent.com/526008/29998157-c65daebc-9056-11e7-8a9a-931ff30c8a0c.png)

And, when I open a new tab at this moment, the bar is still disappeared.

**Comment by DanPristupov** [comment]
@ElfSundae does this happen every time? Could you try to restart the computer please?

**Comment by ElfSundae** [comment]
Yes, every time, and restarting computer does not help, I tried.

**Comment by ElfSundae** [comment]
Still disappeared on 1.0.55 😭

**Comment by DanPristupov** [comment]
I've reproduced the problem. This problem appears when user connects a mouse device. I don't know how to fix it though. Will investigate the problem later.

**Comment by ElfSundae** [comment]
@DanPristupov Any progress?

**Comment by DanPristupov** [comment]
Hi. Thank you fore reminding me. It was tricky previously. I'm going to make another attempt this week. Will let you know about the results.

**Comment by ElfSundae** [comment]
OK.

**Comment by DanPristupov** [comment]
Fixed in 1.0.60

**Comment by ElfSundae** [comment]
❤️
