### ISSUE TITLE
[Feature Request] Quick locate current branch in the branches list

### ISSUE THREAD

**Issue by yichengchen** [ForkIssues/Tracker#880]
In my company repo, I have a lot of branches spreads in many folder. Some time I want to copy the branch name, I need to manually expand the folder in the left panel and find my branch to copy.

I wish there is a shortcut work like 'Command+Shift+J' in the xcode, which quick select the current branch in the left branch list tree

**Comment by DanPristupov** [comment]
> I wish there is a shortcut work like 'Command+Shift+J' in the xcode

We already have a similar shortcut ⌘0 which reveals the HEAD in the commit list.

What do you think if we make ⌘0 reveal the active branch on the sidebar as well?

**Comment by yichengchen** [comment]
> > I wish there is a shortcut work like 'Command+Shift+J' in the xcode
> 
> We already have a similar shortcut ⌘0 which reveals the HEAD in the commit list.
> 
> What do you think if we make ⌘0 reveal the active branch on the sidebar as well?

Yes, this sounds good.

**Comment by DanPristupov** [comment]
Done in 1.0.89
