### ISSUE TITLE
[Feature request] hide branch

### ISSUE THREAD

**Issue by alexjeffburke** [ForkIssues/Tracker#882]
Hi there,

I've been using fork for some time now, love the app! At my current workplace, art of our release process is to merge into a release branch. There is so much activity that if is rendered in the UI you can't really see much else making the repository overview often impossible to use.

If we were able to hide that branch in the repository commit rendering then the commits overview would return to being a central part of visualising in-progress work.

Thanks for the consideration, Alex J Burke.

**Comment by DanPristupov** [comment]
Currently you can't hide a particular branch.

As an alternative you can try to set multi-filter on the branches you want to see.

**Comment by alexjeffburke** [comment]
@DanPristupov thanks for the response :) Yeah, I looked around for something like this in the UI and decided it didn't exist hence the suggestion. You mentioned `multi-filter` as a workaround, how do I use that feature?

**Comment by DanPristupov** [comment]
Use ⌘ key
<img width="390" alt="Screenshot 2020-01-22 at 16 00 37" src="https://user-images.githubusercontent.com/618115/72905140-56128400-3d30-11ea-8012-525a92312f54.png">

**Comment by alexjeffburke** [comment]
@DanPristupov ahhh I hadn't realised you could multi-select them! This is a a pretty nice workaround for my issue :)

**Comment by DanPristupov** [comment]
Please try the prerelease: https://github.com/ForkIssues/Tracker/issues/865

It has a lot of performance improvements in the filter infrastructure.

We will also introduce the ability to **hide** branches in the future, but can't figure out the UI design yet.

**Comment by hardkrash** [comment]
My first thought was to try the option key to invert the case.
When that didn't work I came to the issue tracker and found this.

option click for `not filter`
command click for `multi select filter` add
option command click `multi select not filter` add.
    This would be made redundant if a `multi select filter` was added...

**Comment by DanPristupov** [comment]
In Fork 2.6 you can hide branches

**Comment by alexjeffburke** [comment]
Just tried the feature in v2.6 and it's almost exactly what I'd hoped for when I opened this issue. Thanks for implementing this - think it's time to close this out :)
