### ISSUE TITLE
Branch comparison wrong files state

### ISSUE THREAD

**Issue by marcocadei** [ForkIssues/Tracker#889]
Sometimes when i compare branches to see changes before creating a PR (btw, this is one of the coolest features imho) some files are marked as deleted even if I've created them in the current branch.

Concrete example: I created `branchA` and added `fileA` and this is my current branch. If I select it and then - keeping command pressed - I select `develop` in order to see the differences sometimes `fileA` is marked in red as if I deleted in the current branch while actually I've added it.

Am I doing something wrong or is there a known bug?
Thank you and advance and congrats for the amazing product!

**Comment by DanPristupov** [comment]
There's Swap button for this case.
<img width="647" alt="Screenshot 2020-01-30 at 10 18 01" src="https://user-images.githubusercontent.com/618115/73435894-cda46c80-4349-11ea-997b-bf64e7bf8aa2.png">

**Comment by marcocadei** [comment]
Amazing, thank you very much 😄
