### ISSUE TITLE
clone forces git@ address, no https://github.com/ allowed

### ISSUE THREAD

**Issue by matkatmusic** [ForkIssues/Tracker#891]
It appears that the Clone window does not let you clone your own github account repos if you haven't set up ssh keys locally.   The address defaults to git@github.com, and we cannot choose to clone via an https address instead.  What's the point of asking for our user credentials if we can't clone our own repos?

**Comment by matkatmusic** [comment]
Specifically referring to this view: 
![Screen Shot 2020-01-30 at 4 13 25 PM](https://user-images.githubusercontent.com/2929847/73501670-79b27b80-437b-11ea-99b9-a122058bdc8b.png)

**Comment by DanPristupov** [comment]
Hi. I'm not sure I understand the issue. Could you add steps to reproduce please?

> The address defaults to git@github.com, and we cannot choose to clone via an https address instead. 

<img width="570" alt="Screenshot 2020-01-31 at 07 29 37" src="https://user-images.githubusercontent.com/618115/73517324-71018a00-43fb-11ea-8f5f-378257014e19.png">

<img width="570" alt="Screenshot 2020-01-31 at 07 30 26" src="https://user-images.githubusercontent.com/618115/73517363-8eceef00-43fb-11ea-81ae-a800b324da0b.png">

**Comment by matkatmusic** [comment]
Do this on a computer you don't have SSH keys set up on:
Open the Clone dialog box,
click "GitHub",
sign in to your github account,
try to clone a repo in your account.

It will fail because the git repo url is a 'git@github.com/' url, not a '
https://github.com/' address.  You can't clone those unless you have SSH
keys set up and added to the repo.

**Comment by DanPristupov** [comment]
Did you try to use HTTPS protocol?

**Comment by matkatmusic** [comment]
That clone dialog doesn't allow choosing protocols to use when cloning.  It
forces the SSH url

**Comment by matkatmusic** [comment]
my fault, it does let you choose.  Sorry I missed that!  It isn't as intuitive as one would hope.  

Perhaps a preference choice could be added to let us pick if we want to display SSH urls or HTTPS urls on the clone page as the pre-selected URL?

**Comment by DanPristupov** [comment]
Fork remembers your last choice.
