### ISSUE TITLE
Please make "Hide remote branches in commit list" sticky

### ISSUE THREAD

**Issue by ianwremmel** [ForkIssues/Tracker#892]
I work on a large team and the number of remote branches we have makes the the commit viewer really challenging. Hide remote branches is great, but I need to set it nearly everytime I open the commit viewer. Is there any way to store its state on a given repo so it stays that way until manually changed?

**Comment by DanPristupov** [comment]
No, there's isn't such way because I don't know how to show user that 'No remotes' mode is enabled.

P.S. A related issue: https://github.com/ForkIssues/Tracker/issues/637
