### ISSUE TITLE
Hide Tags still shows the tags label in the commit list

### ISSUE THREAD

**Issue by Sandrock02** [ForkIssues/Tracker#893]
As title mentioned:
I hided the tags to not disturb me a bit. but when I upgrade the Folk to 1.0.89, this doesn't work any more. Whatever I turn on or turn off the settings, it always shows the tags in the commit list. That setting just hides the tags node in the left panel tree.

MacBook pro 16" 2019
macOS 10.15.1

**Comment by DanPristupov** [comment]
Confirm that. Thank you for the bug report.

**Comment by DanPristupov** [comment]
Fixed in Fork 1.0.90
