### ISSUE TITLE
[Feature] Different symbol for tracking branches in list

### ISSUE THREAD

**Issue by svoop** [ForkIssues/Tracker#903]
<img width="125" alt="Screen Shot 2020-02-11 at 13 09 46" src="https://user-images.githubusercontent.com/7255/74235670-d7c25580-4ccf-11ea-8453-3f1a7325a4cf.png">

In the branches list, it's not possible to see which local branches are tracking or not. How about either changing the symbol for tracking branches, e.g. adding a little plus sign?

![tracking_branch](https://user-images.githubusercontent.com/7255/74235977-7b136a80-4cd0-11ea-8576-4c4ee786c54d.jpg)

Or maybe coloring the symbol blue (like the favorite and filter toggles) for tracking branches?

The advantage of some form of difference between tracking and non-tracking local branches:

* It's easy to spot local branches which are no longer tracking remote branches because they have been deleted (e.g. after a merged PR).
* It's easy to tell whether you're on a local branch which means hammering around in the commit histroy won't do any harm.

**Comment by DanPristupov** [comment]
Surprisingly, this feature is already planned for 1.0.89.

Here's a screenshot:

<img width="234" alt="Screenshot 2020-02-11 at 16 02 26" src="https://user-images.githubusercontent.com/618115/74248464-e87ec580-4ce7-11ea-80f2-40884a0a1f86.png">

- Local Branch with a tracking reference
- Local Branch without a tracking reference
- Local branch with an invalid (removed) tracking reference.

**Comment by svoop** [comment]
@DanPristupov Wow, very cool!! This will make my life so much easier, thanks a bunch!

**Comment by svoop** [comment]
Btw, 1.0.89 is the current version.

**Comment by DanPristupov** [comment]
I just released Fork 1.0.90. Please check for updates
