### ISSUE TITLE
[Bug|Feature] Improve "View -> Hide Remote Branches in Commit List"

### ISSUE THREAD

**Issue by svoop** [ForkIssues/Tracker#904]
This "View -> Hide Remote Branches in Commit List" setting is not persisted between app relaunches, For always starts with remote branches shown in the commit list. This is a little disruptive since usually, most local branches are tracking remote branches which means the tags appear twice in the commit list and push the commit message mostly out of the visible area.

On the other hand, many projects use explicit branch names which are referring issue numbers e.g. `1434_improve_activity_filter_in_backend`. Such longer branch names occupy a lot of space in the commit list and mask most of the commit message.

An idea to improve this:

Add "View -> Collapse Branches in Commit List" setting. When selected, the branch name tags in the commit list are collapsed on the first non-alphanumeric (e.g. underscore, dash etc) character, examples:

`1434_improve_activity_filter_in_backend` -> `1434…`
`837-my-great-new-feature` -> `837…`
`userlist-improvements` -> `userlist…`

To unveil the full branch name in the commit list, a tooltip could be shown when hovering a collapsed branch name tag.

**Comment by richellis** [comment]
FWIW the "Hide Remote Branches in Commit List" is persisted between app launches now! 🚀 I came here to submit this as a feature request and was delighted to find it already exists! I only wish it was more discoverable in the UI, I think it's an essential feature for working with large teams and lots of remote branches.

**Comment by DanPristupov** [comment]
I think I can close this.

Since I'm here...

@richellis 
> I only wish it was more discoverable in the UI

It will

> I think it's an essential feature for working with large teams and lots of remote branches.

In Fork 2.6 we will introduce many improvements which must help with such repos 👍
