### ISSUE TITLE
Reorder "push branches" and "delete branches"

### ISSUE THREAD

**Issue by noelforte** [ForkIssues/Tracker#907]
Would like to suggest reordering the options for pushing multiple branches and deleting multiple branches as having options that do 2 very different things next to each other is a dangerous pattern, even with there being confirmation dialogs. I feel like most folks will want to push up their branches more often than deleting them but if there's a specific reason the order is set this way I'd be interested to hear.

<img width="241" alt="Screen Shot 2020-02-12 at 11 52 21 PM" src="https://user-images.githubusercontent.com/2560683/74402665-e9e8e480-4df2-11ea-9aa7-760299ffdd94.png">

**Comment by DanPristupov** [comment]
Done!
<img width="292" alt="Screenshot 2020-02-21 at 16 07 47" src="https://user-images.githubusercontent.com/618115/75045855-4f5c6580-54c4-11ea-83dd-36e42b7f84f2.png">
