### ISSUE TITLE
Symlinked gitconfig doesn't work

### ISSUE THREAD

**Issue by Cyberbeni** [ForkIssues/Tracker#909]
Fork can't get any of the information from gitconfig if it's a symlink, replacing it with the original file solves the problem

**Comment by DanPristupov** [comment]
What 'any' information Fork can't get? If remember correctly, Fork doesn't touch gitconfig at all (however git does).
What is the use case of having gitconfig as a symlink?

**Comment by Cyberbeni** [comment]
I have .gitconfig .gitignore_global and .ssh/config all symlinked into a git repo (with a bunch of other stuff), so if I have to move to a new computer, I can do it fast without losing any changes.
`git config --list` and `ssh-add -l` is working as expected but global (git) user information in Fork's preferences is empty.
And I also noticed after reporting the problem that I get `repository not found` error when I try to open any of my repos with this setup.

**Comment by Cyberbeni** [comment]
Realised that access to Desktop directory was denied for some reason. And the original gitconfig file was inside the Desktop (along with other repositories)
Now that I allowed it, it is working properly.
(It is a new "feature" in Catalina that if you open a file/folder inside Desktop/Downloads/Documents outside of an open panel, you will need permission from the user)

**Comment by DanPristupov** [comment]
> Realised that access to Desktop directory was denied for some reason. 

This is unexpected turn of events :). But it makes sense. Did you see the Permission popup?

**Comment by Cyberbeni** [comment]
Honestly don't remember but probably yes, I just don't allow anything that I don't understand instantly.

We have that problem too. User selects something from open panel, we can work with that without any issue. User closes the app and reopens it later, we want to continue working with the same directory, permission dialog is presented, user doesn't understand what it's about.
