### ISSUE TITLE
[Feature Request] Use the previous location for the project directory

### ISSUE THREAD

**Issue by ElfSundae** [ForkIssues/Tracker#91]
There is a "Default Folder" preference that used in repo adding/creating/cloning. I think it is better to use the previous location as default in most instances. Or giving an option to choose between a default folder and the previous location in the Preferences panel. Thanks.

**Comment by DanPristupov** [comment]
@ElfSundae why cloning to default folder is wrong?
I can add a list of recent clone locations to the dropdown like on the screenshot. Could that be a solution?

<img width="594" alt="2017-09-11 at 09 28" src="https://user-images.githubusercontent.com/618115/30263011-9dc661aa-96d3-11e7-90f0-325cb3902f62.png">

**Comment by ElfSundae** [comment]
The Default Folder is not wrong, but depends.. I have several repo root locations for Websites, C++, iOS, Android, Node, Work Projects, GitHub, when I add a new repo or import a exist repo in Fork GUI, the browser always shows the default folder, I need to select. And I want the browser to show the previous location which I previously selected. 

A list of recent clone locations could be a solution, but only for cloning? Please tell me how to add this list, thanks.

**Comment by DanPristupov** [comment]
There's no such list yet, but I can implement implement it soon.
So, I do can do the following:
- clone will show list of recent paths (like on the screenshot above)
- open and git-init views will use the previous location.

Is that good enough? Can we improve something?

**Comment by ElfSundae** [comment]
I think It will be awesome.

Besides, if the "Choose..." also open the previous location, the Default Folder preference can be removed, or the default folder will be only used for cloning. Am I right?

**Comment by DanPristupov** [comment]
@ElfSundae yes, it seems that default folder preference is going to be useless in this way. I'll keep it for some time to be sure I don't miss something and then get rid of it.

**Comment by ElfSundae** [comment]
👍
