### ISSUE TITLE
Show diff for all selected files

### ISSUE THREAD

**Issue by ZevEisenberg** [ForkIssues/Tracker#912]
I’d love the ability to select multiple files and see the diffs for all of them in a single scrolling view. It would make some kinds of code reviews much easier. I’m thinking specifically of looking at current changes, as well as when looking at a commit in the history. I believe SourceTree has this, for comparison.

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/Tracker/issues/261

**Comment by ZevEisenberg** [comment]
Dupe 😁
