### ISSUE TITLE
Does Fork support on-site GitLab instances?

### ISSUE THREAD

**Issue by lhaeger** [ForkIssues/Tracker#913]
We run GitLab in-house, does Fork support this similar to gitlab.com? If not, is this in the roadmap already?

**Comment by DanPristupov** [comment]
Git protocol doesn't require any special support. As a result Fork supports any git instances, including private GitLab ones.

Just make fetch and Fork will prompt credentials.

**Comment by lhaeger** [comment]
Yes, the basic git stuff work, of course. But how about "View on GitLab" or login via Access tokens?

**Comment by DanPristupov** [comment]
> how about "View on GitLab"

View on GitLab will not be available.

> login via Access 

If I remember correctly you can just use private access token as a password. I.e. no extra support required.

**Comment by unikitty37** [comment]
I would like full support for on-site GitLab, as I'd want notification support to work for my on-site instance. (That said, the website only mentions support for GitHub notifications — do these even work with GitLab?)

**Comment by DanPristupov** [comment]
GitLab API doesn't support notifications.

**Comment by lhaeger** [comment]
> > how about "View on GitLab"
> 
> View on GitLab will not be available.

Would be great if you could add that, though. Should not be too hard to derive the web url from the repo url + branch name:

Clone url: https://gitlab.server.org/group/subgroup/project.git
Web URL for 
- branch "master": https://gitlab.server.org/subgroup/project/-/tree/master
- tag "v3.1.1": https://gitlab.server.org/subgroup/project/-/tags/v3.1.1
- a commit: https://gitlab.server.org/subgroup/project/-/commit/bedb145d7252f36530986ef2bd4d4f3ada05a5aa
