### ISSUE TITLE
Unable to create pull request to gitlab

### ISSUE THREAD

**Issue by tbm98** [ForkIssues/Tracker#914]
my service config
<img width="568" alt="Screen Shot 2020-02-20 at 10 10 02" src="https://user-images.githubusercontent.com/52562340/74897301-3753eb80-53c9-11ea-8af6-09a749c453bb.png">

**Comment by DanPristupov** [comment]
The pull request behavior in Fork will be changed in the next update (1.0.90)

**Comment by tbm98** [comment]
Thanks!
I am waiting for it :D

**Comment by DanPristupov** [comment]
Fork 1.0.90 is out. Please check the new ability to create Pull Requests there.

**Comment by tbm98** [comment]
I just get error 
<img width="459" alt="Screen Shot 2020-02-21 at 22 24 35" src="https://user-images.githubusercontent.com/52562340/75047254-05da3d80-54f9-11ea-8ee0-358e41825d79.png">

**Comment by DanPristupov** [comment]
It happens sometimes. Try to check for updates again. Please let me know if the problem persists, I might need to purge data on CDN in Asia.

**Comment by tbm98** [comment]
still error when retry

**Comment by tbm98** [comment]
I was downloaded the new dmg file install, if error still appear I will refresh install in tomorrow.

**Comment by DanPristupov** [comment]
I just purged the CDN cache. Please try to check for updates again.

You can download the DMG here: https://cdn.fork.dev/mac/Fork-1.0.90.dmg

**Comment by tbm98** [comment]
@DanPristupov still error update
<img width="464" alt="Screen Shot 2020-02-21 at 22 44 59" src="https://user-images.githubusercontent.com/52562340/75048894-d973f080-54fb-11ea-9331-3e0864db9e13.png">

**Comment by DanPristupov** [comment]
Can you download and run the application manually? https://cdn.fork.dev/mac/Fork-1.0.90.dmg

**Comment by tbm98** [comment]
> Can you download and run the application manually? https://cdn.fork.dev/mac/Fork-1.0.90.dmg

Should I remove old and install new or just install new file ?

**Comment by DanPristupov** [comment]
You can run it right from the DMG file. It everything is OK, you can replace the file in the Application folder.

**Comment by tbm98** [comment]
<img width="416" alt="Screen Shot 2020-02-21 at 23 06 05" src="https://user-images.githubusercontent.com/52562340/75050557-c3b3fa80-54fe-11ea-9cf5-b91d7ded6599.png">
:(

**Comment by tbm98** [comment]
after I install file fork.dmg from https://git-fork.com/ and check update again. It show available update and my app is 1.0.89, before install new file version is 1.0.88
<img width="686" alt="Screen Shot 2020-02-21 at 23 08 10" src="https://user-images.githubusercontent.com/52562340/75050686-1097d100-54ff-11ea-9321-dd5e5bb83cd5.png">

**Comment by DanPristupov** [comment]
OK, try to download it again: https://git-fork.com/update/files/Fork.dmg. I just uploaded 1.0.90 there.

**Comment by tbm98** [comment]
ok. still update error when click button 'install updates' on version 1.0.89

**Comment by tbm98** [comment]
> OK, try to download it again: https://git-fork.com/update/files/Fork.dmg. I just uploaded 1.0.90 there.

worked fine! :D

**Comment by tbm98** [comment]
create pull request always merge into default branch, but work fine!
Thank you!
