### ISSUE TITLE
Cannot use Kaleidoscope as external diff tool

### ISSUE THREAD

**Issue by max1mvs** [ForkIssues/Tracker#917]
I have this weird issue where Fork consistently defaults to FileMerge when invoking the External diff (Command-D) tool, even though I have set Kaleidoscope as the Merge and External diff tool under the preferences. I'm relatively new at this, so I'm not capable of understanding what goes on underneath the bonnet, so to speak so any pointers would be helpful.

**Comment by DanPristupov** [comment]
1. Did you install Kaleidoscope CLI tools?
2. Check `~/Library/Logs/Fork.log`

**Comment by max1mvs** [comment]
Oh, of course it is depending on that! I hadn't thought that far. Thank you! 😊 🙏
