### ISSUE TITLE
Fork hangs on checkout of specific branch

### ISSUE THREAD

**Issue by gahms** [ForkIssues/Tracker#920]
For some repositories, for some branches, Fork consistently hangs and never finishes checkout of the branch.

* private github repo
* git currently on "develop"
* remote branch called "feature/something"
* double-click on remotes/origin/feature/something
* Fork asks shows a sheet (asks for name of local branch)
* Press Track
* Sheet stays, cursor turns to spinner, never recovers.
* From the command line I can do `git checkout feature/something` without problems
* Recreated the problem with a clean clone in a different directory
* Recreated the problem on a different machine
* The original clone where the branch feature/something is created works fine - branch were created with Fork.
* The repository uses git-lfs with a few Sketch files tracked by git-lfs.

Attached screenshot, "sample" from Activity Monitor of Fork and of "fork_askpasswd".
<img width="1558" alt="Screenshot 2020-02-28 at 08 26 12" src="https://user-images.githubusercontent.com/5833431/75520820-ba4af680-5a06-11ea-99c5-871a75e8496b.png">
<img width="1038" alt="Screenshot 2020-02-28 at 08 26 24" src="https://user-images.githubusercontent.com/5833431/75520837-be771400-5a06-11ea-9dbd-81d5a3a74b10.png">
[Sample of Fork.txt](https://github.com/ForkIssues/Tracker/files/4265823/Sample.of.Fork.txt)
[Sample of fork_askpasswd.txt](https://github.com/ForkIssues/Tracker/files/4265826/Sample.of.fork_askpasswd.txt)

**Comment by DanPristupov** [comment]
Does LFS Fetch/LFS Pull work properly in Fork?

**Comment by gahms** [comment]
I am not sure what you mean. Normally I can work without problems with Fork and this repository incl. pull and fetch and incl. the LFS controlled files which are pulled and pushed by Fork just by using normal pull and push.

If I do a LFS pull or fetch on develop, no problem, but that branch is already local and up-to-date. I do not see how I can do a LFS pull or fetch from within Fork on a remote branch.

I have worked with Fork with this repos for a long time with lots of commits and lots of branches, incl. LFS controlled files, without problems.

**Comment by DanPristupov** [comment]
I'm just trying to ensure that LFS works in your repository and is authenticated.

Did you try to checkout revision? Does it also hang?

**Comment by gahms** [comment]
I just tried a checkout on a specific commit on the remote branch (detached HEAD as a result). No problem. 

Then I did the same for the newest commit on the branch and now it is no longer a detached HEAD but a normal checked out branch without problems. Weird. Seems like this procedure is at least a work-around.

I just tried checkout of "master" (default branch is develop and thus the master branch is only remote until first checkout), same problem as on the branch. 

Then I tried a fresh clone (in a new dir) from within Fork. No problem. In the fresh clone I checked the LFS files and they have been pulled fine.

Then on the fresh clone I tried to checkout an older commit on develop that definitely had changes to the LFS tracked files. No problem.

When I force quit a hanging Fork a fork_askpassword to seem to survive when I look in the Activity monitor.

**Comment by DanPristupov** [comment]
Please continue noticing the details. Nobody reported such problem yet, so it might be (or not) a problem related to your environment. I will be able to investigate this next week.

> no problem

Can you still reproduce the problem? Didn't it disappear?

**Comment by gahms** [comment]
I will keep an eye on it. I have seen it a couple of times before but shook it off as a fluke. Now I am more certain that something is smelling.

I can reproduce it consistently and make it go away again consistently. A clean clone of the repo and then try to switch branch by double-click in left pane, freeze. 

Switch branch from command line, no problem. Double click a specific commit in history, no problem, double click latest commit in branch, no problem and result is af if I double clicked in the left pane in the first place.

Reach out to me if you think I can help you in any way (attach Xcode debugger or something).
