### ISSUE TITLE
No dark mode available

### ISSUE THREAD

**Issue by pkitslaar** [ForkIssues/Tracker#922]
I just updated Fork on MacOS 10.13.6 to version 1.0.90 but I no longer have the dark mode/theme or can find a way to switch to the application to the dark mode/theme.

**Comment by DanPristupov** [comment]
We removed the dark theme on old MacOS versions. Dark mode is available starting from MacOS 10.14.

You can read more details here: https://github.com/ForkIssues/Tracker/issues/586#issuecomment-477253709. We waited 1 year after that.
