### ISSUE TITLE
Is there any "git fetch -p" equivalent operation?

### ISSUE THREAD

**Issue by tatsuyafujisaki** [ForkIssues/Tracker#924]
Like "git fetch -p", does Fork offer any way to delete all the local branches that no longer exist on the remote?

**Comment by DanPristupov** [comment]
`-p` means 'prune'. It removes **remote**-tracking references that no longer exist on the remote.

<img width="462" alt="Screenshot 2020-03-03 at 07 42 57" src="https://user-images.githubusercontent.com/618115/75749663-9c410700-5d22-11ea-9eeb-31058441a03a.png">

**Comment by tatsuyafujisaki** [comment]
Thank you very much!
