### ISSUE TITLE
rename branch still tracks remote with different name

### ISSUE THREAD

**Issue by matkatmusic** [ForkIssues/Tracker#925]
I was working on `Branch A`.  
I have a `Branch B` which tracks `origin/B`.
I decided to rename `Branch B` to `Branch C`, without switching from `Branch A`. 

`Branch B`(`C`) had not been pushed to the remote yet but was tracking `origin/B`.

I when to check out the branch `origin/B`, and it jumped to my `C` branch. 

I expected a new branch named `B` to be created and checked out, but that did not happen. 

Perhaps we need a menu command to make a branch stop tracking a remote branch if we rename the branch.

**Comment by DanPristupov** [comment]
> Perhaps we need a menu command to make a branch stop tracking a remote branch if we rename the branch.

<img width="551" alt="Screenshot 2020-03-03 at 07 47 34" src="https://user-images.githubusercontent.com/618115/75749923-40c34900-5d23-11ea-917f-663a30abbf26.png">

**Comment by matkatmusic** [comment]
NICE!!  

Can we access that menu by right-clicking on the commits for the branch, though?
