### ISSUE TITLE
Failures when using git flow (either start feature or end feature)

### ISSUE THREAD

**Issue by lksoft** [ForkIssues/Tracker#926]
Could be others as well.

With the current version (1.0.90) I have tried to use git flow twice and both times I have had errors result. Here is the message displayed:

/Applications/Local/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 158: _flags_fatal: command not found
/Applications/Local/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Local/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Local/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 273: [: too many arguments
/Applications/Local/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 1022: [: -ne: unary operator expected
flags:WARN /Applications/Local/Fork.app/Contents/Resources/gitflow-avh/gitflow-shFlags: line 739: /Applications/Local/Sourcetree.app/Contents/Resources/bin/getopt: No such file or directory
flags:FATAL unable to parse provided options with getopt.

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/Tracker/issues/541
https://github.com/ForkIssues/Tracker/issues/557
https://github.com/ForkIssues/Tracker/issues/418
https://github.com/ForkIssues/Tracker/issues/541

**Comment by lksoft** [comment]
Doh! Thanks1
