### ISSUE TITLE
Sidebar: Many operations cause starred branches subtree to collapse

### ISSUE THREAD

**Issue by n8gray** [ForkIssues/Tracker#931]
Various operations cause the starred branch area of the sidebar to collapse.  For example, clicking on the filter icon for a branch in the sidebar will do it, as will fetching from the server.

Here's the state before I filtered to a (non-favorited) branch:
![Screen Shot 2020-03-05 at 4 18 27 PM](https://user-images.githubusercontent.com/82794/76037991-512f1b80-5efd-11ea-8567-c0fb76c9203c.png)

And here's what happened afterwards:
![Screen Shot 2020-03-05 at 4 18 47 PM](https://user-images.githubusercontent.com/82794/76038025-6b68f980-5efd-11ea-8283-adf35de9b136.png)

This is a bit disorienting every time and introduces friction into the "starred" concept, since Fork seems to want to hide starred branches from me whenever I'm actively using it.

Thanks for continuing to develop this app. I'm a big fan.

**Comment by n8gray** [comment]
Any plans to address this? The latest annoyance is that when I un-star a branch the entire "Starred" remote section collapses.  When I have two or three branches to un-star, this gets super irritating.

Before: 
![Screen Shot 2020-06-16 at 11 14 06 AM](https://user-images.githubusercontent.com/82794/84812197-df1da680-afc2-11ea-892c-4f5ed5060039.png)

After:
![Screen Shot 2020-06-16 at 11 14 37 AM](https://user-images.githubusercontent.com/82794/84812210-e644b480-afc2-11ea-9be4-8127f8946636.png)

Adding a new starred branch does the same thing. Basically *anything* that changes the set of starred branches. It's like the feature is actively trying to get me to stop using it!

**Comment by maksimovic** [comment]
In the same manner, searching for a branch (bottom left) always expands all groups: starred, branches, remotes, tags, stashes, submodules. So, you search for something, then cancel the search and you've got everything left expanded. In my case it's really pain in the ass as I've got thousands of tags :D

**Comment by n8gray** [comment]
Much better now, thanks!
