### ISSUE TITLE
Prefix repository display names with folder name

### ISSUE THREAD

**Issue by k-spa** [ForkIssues/Tracker#937]
Fork supports the organization of repositories in folders, which is awesome.

I would love it though if there would be an option to prefix the display name of the repository with the folder name. I have several repositories with the same name in different folders and to tell them apart I have to rename each of them individually.

Let's say, I have the following structure:
- folder 1
  - repo 1
  - repo 2
- folder 2
  - repo 1
  - repo 2

Currently, when opening the repositories, the tab titles are simply "repo 1" or "repo 2" with no information, which repository it actually is.

If there e.g. would be a checkbox when you click the folder in the "new" tab to "Prefix repository names with folder name", the display names when opening could be "folder 1 - repo 1" or "folder 2 - repo 1" and finding the correct tab would be much easier :)

**Comment by DanPristupov** [comment]
Renaming repositories in Fork is the correct solution for this problem.

Adding parent folder to the names will not help in the following (pretty common) case:

- folder 1
   - src
     - repo 1
- folder 2
  - src
    - repo 1
