### ISSUE TITLE
Blame and Show File History don't work for files with 'ä' in their name

### ISSUE THREAD

**Issue by petterikamppuri** [ForkIssues/Tracker#938]
Fork doesn't show Blame and File History for files with a 'ä' in the filename. Probably something to do with file system level stuff.

`> git status` on the command line lists files like this:

```
modified:   "dir/MyFile_\303\244.swift"
```

However, and unfortunately, using that filename doesn't work when asking for log:

`> git log "dir/MyFile_\303\244.swift"`

prints nothing.

Using the 'ä' character in filename works:

`> git log "dir/MyFile_ä.swift"`

prints log as I expect it to.

`ls` prints filename using form `dir/MyFile_ä.swift`.

Would be great to get this fixed, so I don't have to touch the command line. Thanks!

**Comment by DanPristupov** [comment]
Not sure at what point this was fixed, but it works for me now.
