### ISSUE TITLE
Feature request: Support for gitmoji icons

### ISSUE THREAD

**Issue by hans2103** [ForkIssues/Tracker#940]
Using a rigid commit format with emoji means I limit myself to a commit per ‘thing’, it also allows me to parse my commits quickly. 

Fork does not convert `:sparkles:`. to :sparkles:
It just displays `:sparkles:`.
It would be great if Fork embraces emoji and displays :sparkles: and other emoji as well. 

https://gitmoji.carloscuesta.me/
https://github.com/carloscuesta/gitmoji-cli

more words about why to use emoji: https://csi.lk/emoji-use-in-commit-messages/

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/Tracker/issues/296
https://github.com/ForkIssues/Tracker/issues/361

P.S. Just type ✨

**Comment by hans2103** [comment]
@DanPristupov can you explain me how I can type :sparkles: on command line without typing `:sparkles:`
I am committing on both command line as in Fork.

**Comment by DanPristupov** [comment]
Ctrl+Cmd+Space -> Select the emoji

<img width="660" alt="Screenshot 2020-03-23 at 08 49 35" src="https://user-images.githubusercontent.com/618115/77293750-3a513d00-6ce3-11ea-89bb-3ffed9ff7653.png">

**Comment by hans2103** [comment]
just tested and it also works while logged in on a remote server. 
thank you for this workaround
