### ISSUE TITLE
[Feature Request]Login using custom GitHub URL

### ISSUE THREAD

**Issue by matthesoundman** [ForkIssues/Tracker#944]
It would be a nice feature for users that aren't using GitHub.com and have their own instance of GitHub (enterprise or other) running to be able to specify URL to use.

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/52799792/77363328-c24d3c00-6d0f-11ea-8a60-6aad21b28482.png">

- add a field for custom URL
- add field for token 
 
If custom URL is used authenticate using user API token to then show all their remote repos. (The user will have to of course generate token with repo permission.)

GitAhead uses this approach and it works to populate and interact with custom URL.
<img width="255" alt="image" src="https://user-images.githubusercontent.com/52799792/77363657-5b7c5280-6d10-11ea-8e9a-dd581c498bf0.png">

**Comment by ZeldoKavira** [comment]
👍 Please add enterprise support :)

**Comment by Teej42** [comment]
Yeah, this is a must for me.  Do this, and I'll buy.

**Comment by DanPristupov** [comment]
We implemented integration with GitHub Enterprise in Fork 2.6. @Teej42 may be it's time :).

**Comment by Teej42** [comment]
Ooo, perfect timing.  I'm evaluating Git clients again.

**Comment by Teej42** [comment]
Yup, this is the one.  It's actually a bit better than Tower, with a few rough edges that I hope can be smoothed over with experience (i.e., once in a repository, it's not obvious how to go back to the list of repositories outside clicking the + tab.)  Made my purchase.  Thank you for making this product for us.

**Comment by DanPristupov** [comment]
@Teej42 thank you!

>  it's not obvious how to go back to the list of repositories outside clicking the + tab

I'd suggest to use `Cmd+P` to switch repos quickly.
