### ISSUE TITLE
Cannot use latest version of lint-staged due to old version of Node

### ISSUE THREAD

**Issue by kanitw** [ForkIssues/Tracker#947]
Our commit hooks requires lint-stage, but it's requiring at least Node 10.13.0

```
lint-staged requires at least version 10.13.0 of Node, please upgrade
```

It seems like Fork is running 10.6.0.

**Comment by DanPristupov** [comment]
What does `which node` show in command line?

**Comment by kanitw** [comment]
`/Users/kanitw/.nvm/versions/node/v10.16.3/bin/node`

**Comment by kanitw** [comment]
Do I have to update the system's node version?

**Comment by DanPristupov** [comment]
1. Fork only sees what's in `/usr/local/bin` and in ENV. As you said, the 'system' one.
2. You can make it inherit ENV of your terminal if you start it using `open -a Fork .` command.

**Comment by DanPristupov** [comment]
3. I suppose there should be a way to put to /usr/local/bin a symlink which points to the default nmv instance. I'm trying to google this now.
