### ISSUE TITLE
Interactive rebase fails for badly formatted commit messages

### ISSUE THREAD

**Issue by wildmichael** [ForkIssues/Tracker#954]
If a user created commit messages that do not have an empty line between subject and body Fork creates a bad rebase script that contains the commit message body on its own line. E.g. the following commit message:
```
Adds Foo to do Bar
Some more explanation goes here.
```
will result in the following rebase script "line":
```
pick 12ab3ef Adds Foo to do Bar
Some more explanation goes here.
```
The git CLI considers this to be a badly wrapped subject and unwraps it to:
```
pick 12ab3ef Adds Foo to do Bar Some more explanation goes here.
```

**Comment by DanPristupov** [comment]
Good catch, thank you

**Comment by DanPristupov** [comment]
I can't reproduce this (Fork git instance 2.23).

Here are the steps:

1. Create two commits and a commit with multiline subject:
```
ls > aa.txt && git add . && git commit -m "commit1"
ls > bb.txt && git add . && git commit -m "commit2"
ls > cc.txt && git add . && git commit -m "Adds Foo to do Bar
Some more explanation goes here."
```

2. Here's the state
<img width="422" alt="Screenshot 2020-04-06 at 10 27 53" src="https://user-images.githubusercontent.com/618115/78538444-482db480-77f1-11ea-802d-9930f5b697ab.png">

3. Commit details:
<img width="411" alt="Screenshot 2020-04-06 at 10 28 17" src="https://user-images.githubusercontent.com/618115/78538469-567bd080-77f1-11ea-9202-40dd1b4d4665.png">

4. Make IR. I reworded the other commits and reordered them.
<img width="409" alt="Screenshot 2020-04-06 at 10 28 56" src="https://user-images.githubusercontent.com/618115/78538516-6d222780-77f1-11ea-978a-332463f9a16a.png">

5. The todo list seems to be correct

```
$ cat .git/rebase-merge/git-rebase-todo
r dde17176144324e5a78c8c1ca352865c5f7a902b commit11
p 49968c4233c8ee3bbd9b13b39af84cc3d3781a0a Adds Foo to do Bar
r babb798b5fd856621c0a0d52463c973614d32656 commit22
```

6. The graph is correct
<img width="355" alt="Screenshot 2020-04-06 at 10 30 23" src="https://user-images.githubusercontent.com/618115/78538668-a195e380-77f1-11ea-9b1d-a5c8b089120d.png">

7. Commit details are also correct
<img width="373" alt="Screenshot 2020-04-06 at 10 29 39" src="https://user-images.githubusercontent.com/618115/78538593-888d3280-77f1-11ea-89cf-cfda491aad74.png">

Everything is correct. There must be some other reason.
