### ISSUE TITLE
Fetch hangs with beachball in repo with 11k branches

### ISSUE THREAD

**Issue by n8gray** [ForkIssues/Tracker#958]
Version 1.0.91.1

When I try to fetch from my company's massive repo (11k branches, 4.6G in .git folder) Fork becomes unresponsive and beachballs.  I used activity monitor to sample the process a couple of times, and I'll attach those files. Eventually I have to force-quit the app.

[Sample of Fork.txt](https://github.com/ForkIssues/Tracker/files/4411374/Sample.of.Fork.txt)

[Sample of Fork 2.txt](https://github.com/ForkIssues/Tracker/files/4411375/Sample.of.Fork.2.txt)

Running `git fetch --all --prune` from the command line completes in a reasonable amount of time, 15 or 20 seconds.

**Comment by DanPristupov** [comment]
Thank you for the bug report.

**Comment by n8gray** [comment]
Thank you for the excellent app. Another data point: The same thing happens if I bring up the popover to look at the command output from background operations.

[Sample of Fork 3.txt](https://github.com/ForkIssues/Tracker/files/4411699/Sample.of.Fork.3.txt)

![Screen Shot 2020-03-31 at 2 35 02 PM](https://user-images.githubusercontent.com/82794/78077413-35346380-735d-11ea-97ca-ee12eafddc54.png)

**Comment by n8gray** [comment]
Seems to be fixed in 1.0.92. Thanks!

**Comment by DanPristupov** [comment]
😀🎉
