### ISSUE TITLE
[Feature Request] Ability to filter or search the "File Tree"

### ISSUE THREAD

**Issue by morgwn** [ForkIssues/Tracker#959]
It would be great to be able to filter (or search) the File Tree to narrow down on files and then be able to run a "history", etc on them. I'm interested in filenames, and optionally directories.

Similar to:  [[Feature request] Ability to filter branches in the graph #614](https://github.com/ForkIssues/Tracker/issues/614)

**Comment by CodingMarkus** [comment]
Dupe of #428
