### ISSUE TITLE
[Feature Request] Ability to set remote tracking branch from local branch context menu

### ISSUE THREAD

**Issue by initializard** [ForkIssues/Tracker#96]
For local branches that are not tracking a remote branch, add an option to set the remote tracking branch. For branches that already have a remote tracking branch, give an option to change/remove it.

**Comment by romk1n** [comment]
that's something I miss a lot coming from source tree. will vote for that!

**Comment by DanPristupov** [comment]
Finally done. Implemented in 1.0.65: 
![2018-03-16 at 08 50](https://user-images.githubusercontent.com/618115/37509300-1128c3a8-28f7-11e8-9cc7-d8ee89830e97.png)
