### ISSUE TITLE
Incorrect URL of "View on GitHub"

### ISSUE THREAD

**Issue by ElfSundae** [ForkIssues/Tracker#960]
Steps:
```console
$ git clone https://github.com/AFNetworking/AFNetworking
$ cd AFNetworking
$ git remote add fork https://github.com/ElfSundae/AFNetworking
$ fork
```
![image](https://user-images.githubusercontent.com/526008/78468710-f3386280-774c-11ea-9e10-5a27da8a2507.png)

Bug: These two "View on GitHub" buttons open the same remote URL.
Expectation: One opens the `origin` remote URL (https://github.com/AFNetworking/AFNetworking), another opens the `fork` remote URL (https://github.com/ElfSundae/AFNetworking), and so on.

**Comment by DanPristupov** [comment]
Thank you for the bug report.
We'll fix this in the next update.

**Comment by ElfSundae** [comment]
Fixed, thanks.
