### ISSUE TITLE
Can't fetch...

### ISSUE THREAD

**Issue by chewyfrog** [ForkIssues/Tracker#966]
I'm getting the following error when trying to fetch, and I can't figure out how to resolve it:

dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Applications/Fork.app/Contents/Resources/fork_askpasswd
  Reason: image not found
error: /Applications/Fork.app/Contents/Resources/fork_askpasswd died of signal 6
error: unable to read askpass response from '/Applications/Fork.app/Contents/Resources/fork_askpasswd'
fatal: could not read Password for 'https://chewyfrog@bitbucket.org': Device not configured
error: Could not fetch origin

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/Tracker/issues/611
