### ISSUE TITLE
List not updated when staging/unstaging with buttons/keyboard shortcuts on Mac

### ISSUE THREAD

**Issue by lorumic** [ForkIssues/Tracker#968]
After today's update (Version 1.0.92), the "Stage" and "Unstage" buttons in the "Changes" view do stage files, but the view is not updated so as to reflect the action. If I switch to the "Branches" view and then go back to "Changes", I see the files correctly staged/unstaged. Also, if I right click on the file and select "Stage" (or "Unstage") from the menu, I can see the file staged/unstaged immediately (the UI is correctly updated).

Could you please check if you can reproduce the issue? Also, let me know if you need further information (MacOS version, etc., I don't know what could be relevant).

**Comment by DanPristupov** [comment]
Everything works properly on my side.

Does staging by double click work?
Does a single chunk staging work?

Could you reproduce the problem and then send me the log file to support@fork.dev?

The log is located at ~/Library/Logs/Fork.log

**Comment by lorumic** [comment]
Thanks for the quick reply. Staging by double click does not update the view as well. Only right click and selection from the menu does.

I have reproduced the problem and this is the log event that gets generated when I try to stage using one of the 3 methods that do not update the view:

> ⚠️[GitRequest.swift:204] execute(suppressErrorLogging:cancelationToken:) > Git error '--no-optional-locks status --porcelain --renames --untracked-files=all -z -- code_gym.py':
> Unknown option: --no-optional-locks
> usage: git [--version] [--help] [-C <path>] [-c name=value]
>            [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
>            [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
>            [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
>            <command> [<args>]

Looks like there is an unrecognized command line flag "--no-optional-locks", could that be an issue with git version? I remember that the latest Fork update on Windows forced me to update the git instance as well, but if I remember correctly the same didn't happen when I updated it on Mac.

EDIT: Sorry, I just realized that I answered only half of your questions. Staging a single chunk produces the error as well.

**Comment by DanPristupov** [comment]
What git version do you have? The `--no-optional-locks` should be there starting from Git 2.15.2.

Try to switch Fork to the internal git instance. Does this help?

**Comment by lorumic** [comment]
Yes, that was the problem! I thought I was using the internal git instance on Mac just like I do on Windows, but I was wrong. I was using system git which is shamelessly outdated:

> git version 2.14.3 (Apple Git-98)

I have switched to Fork instance and now it works perfectly just as before.

Thanks for helping me troubleshooting the issue!
