### ISSUE TITLE
[Suggestion] Close windows instead of quitting app

### ISSUE THREAD

**Issue by ElfSundae** [ForkIssues/Tracker#97]
![image](https://user-images.githubusercontent.com/526008/30465539-4c6b4380-999d-11e7-8cb3-a19e3a26ab04.png)

I believe the red close button on macOS means "close all windows", not "quit app". The behavior in current Fork confuses me frequently...

**Comment by ElfSundae** [comment]
Yeah, you are right, just close window not quit app. You see, I have been dizzied by this button.

**Comment by DanPristupov** [comment]
Fork is a single-window application (so far). Quitting a single-window app instead of closing window is a common behavior is mac OS: System Preferences, App Store, Photos, FaceTime.

I can keep the application open when user clicks 'close', but should I also remember the open tabs?

**Comment by clounie** [comment]
Personally I prefer windows style (Close actually means Close) anyway - just didn't think about apps using that pattern.

Definitely remember the open tabs - I keep 6-7 open and it'd be reaally annoying to re-open them every time I start Fork back up.

Even if Fork went to multiple windows, I'd expect that if I used Cmd+Q it would remember all my windows and tabs when I started it back up (same as Visual Studio Code, Sublime, IntelliJ IDEA, Postman...etc)

**Comment by ElfSundae** [comment]
@DanPristupov Maybe you are right, but these single-window applications you mentioned have no Tabs or "Documents Views".
The Messages seems be a single-window application, and closing window will not quit Messages. The Dictionary is a multi-windows application, but closing the last window means quitting this application. As well as Maps, Notes.

If an application has tabs or documents, I think that the developer should decide the importance of your application when user click the close button, what is the most users expected behavior? And users do not know whether your application is single-window or multi-windows. 

For instance, In the current Fork, If I open the Preferences window then close the main window, and then how to reopen the main window?

For me, as a developer, I use Fork frequently, so I prefer closing the main window just like hiding it, the opened tabs should be remembered when I re-active Fork. Just like Finder or Xcode does.

If the user quit this application, the opened windows or tabs should be remembered? I think the best solution is let user decide it in the application preferences, like Google Chrome or Safari does. For me, I would like all tabs are remembered if there is no performance issues.

**Comment by clounie** [comment]
There's a minimize button as well as two keyboard shortcuts (Cmd+M / Cmd+H) for hiding a window...don't see why you'd need a fourth way to do the same thing.

**Comment by ElfSundae** [comment]
I know, I am now used to using the minimize button in Fork to close window.

I was talking about the common behavior on macOS.

The difference between closing and minimizing is: closing window will end the lifecycle of this window, clean RAM, and reopening actually recreate a new window. So for single-window applications, closing the only window is even like quitting this application. If closing window but keep application running, there is no need to launch application to recreate window.
Minimizing will only minimize it to the Dock and reopening actually reactivate or redraw it to screen.

Fortunately, Fork costs a very short time to launch, so closing or quitting are both OK. This issue can be closed.
