### ISSUE TITLE
In 1.0.92 double click modified file does not move it between unstaged/stage

### ISSUE THREAD

**Issue by morgwn** [ForkIssues/Tracker#970]
Double-clicking does not move between staged/unstage.

Sometimes the stage button and unstage buttons work, sometimes they don't.

This appears to be a regression in 1.0.92

My machine is running High Sierra.

**Comment by morgwn** [comment]
Just found my original installer for 1.0.90. Double clicking to move between staged/unstaged works correctly. 1.0.92 does not.

**Comment by DanPristupov** [comment]
What git version do you use? 
https://github.com/ForkIssues/Tracker/issues/968

**Comment by morgwn** [comment]
Hi Dan,
it's showing:  2.17.2 (Apple Git-113)
Thx!

**Comment by DanPristupov** [comment]
So, now staging works for you, right?

**Comment by morgwn** [comment]
Actually, no. Just tried it with 1.0.92. Still either very delayed or not working.
1.0.90 works. I'm going to try and grab 1.0.91 which I think is on my other machine to check (if that helps).

**Comment by DanPristupov** [comment]
1.0.91 will work, but we need to understand why 1.0.92 doesn't work for you.

Did you switch Fork to the internal git instance? If not, please try that.

If the problem persists even with the internal git instance, please send me the Fork log file to support@fork.dev. The log is located at ~/Library/Logs/Fork.log

**Comment by morgwn** [comment]
Yes, the internal git instance works. 
High Sierra, System Git 2.17.2 (Apple Git-113) does not work.
Catalina, System Git 2.21.1 Apple Git-122.3) works.

From the other thread it sounded like the command line flags changed starting at "Git 2.15.2", which is why I'm curious.
