### ISSUE TITLE
Context menu quick action for rebase Edit

### ISSUE THREAD

**Issue by carlosefonseca** [ForkIssues/Tracker#972]
Would be great if we could right click on a commit, go to the Interactive Rebase submenu and select "Edit commit…" under the Quick Actions section.

Selecting it would switch the UI to the Changes view with the selected commit in the amend mode, ready to make a change, commit and then continue the rebase.

Thanks

**Comment by DanPristupov** [comment]
This is a good proposal.

**Comment by nsh-ableton** [comment]
+1! I was just coming here to suggest a similar thing. This is actually something that stops me from using Fork in a more integrated fashion as part of my entire rebase workflow. Currently, if I want to edit a particular commit, I always have to right-click on at least one commit prior to that one, and choose "Interactive rebase from here...", and then switch that one to "Edit", and somehow that feels like too many steps for me, so I end up using my terminal and muscle memory. I'd love to be able to do just what Carlos suggests.

**Comment by DanPristupov** [comment]
@nsh-ableton surprisingly this improvement was scheduled for the 1.0.95 update. You can wait for it, or you can download the new version from https://fork.dev/update/files/Fork.dmg right now.

<img width="403" alt="Screen Shot 2020-06-19 at 09 37 47" src="https://user-images.githubusercontent.com/618115/85108756-8ba09800-b210-11ea-8a9e-942acfa35706.png">

**Comment by nsh-ableton** [comment]
Nice! 🎉
