### ISSUE TITLE
Can no longer stage/unstage folders of files via click and drag

### ISSUE THREAD

**Issue by cmcpasserby** [ForkIssues/Tracker#974]
In past versions i was able to grab a folder in the directory tree, and pull it into the staged changes area to stage all files contained in it. This is no longer possible, same problem when unstaging as well.

If i select a folder and hit the stage button things still work, and if i manually select multiple files and drag it still works.
```
Version: Fork 1.0.92
OS: macOS Mojave 10.14.6
```

**Comment by DanPristupov** [comment]
Ouch. This is a regression. I will fix this in the next update. As for now, please use double click. Can you wait?

**Comment by cmcpasserby** [comment]
yeah its not a big deal, since there are multiple other ways to get things done, i just noticed it was a regression that was not in the issue tracker yet. (just sacrifices a bit of muscles memory)

Also you guys are doing a great job, fork feels rock solid compared to all other GUI git clients i have used.

**Comment by DanPristupov** [comment]
This must be fixed in 1.0.95

**Comment by cmcpasserby** [comment]
looks to be working just fine for me and am currently on `1.0.95` on macOS. Thanks!
