### ISSUE TITLE
Can't push to forked repo

### ISSUE THREAD

**Issue by tbm98** [ForkIssues/Tracker#975]
I have forked a private repo.
clone it and take a commit.

When I use fork tool to push it show error
<img width="681" alt="Screen Shot 2020-04-15 at 10 09 02" src="https://user-images.githubusercontent.com/52562340/79294946-aa796a00-7f01-11ea-9e34-1d40aac37065.png">
But when I push by terminal 'git push' then it work well
<img width="635" alt="Screen Shot 2020-04-15 at 10 09 47" src="https://user-images.githubusercontent.com/52562340/79294999-cbda5600-7f01-11ea-8875-652a955c36cf.png">

**Comment by tbm98** [comment]
I just have test on https://gitfiend.com/ tool and it work normal.

**Comment by DanPristupov** [comment]
1. Is that possible that you entered a wrong password and Fork remembered it? Open the KeyChain Access application, remote the entries which looks like 'Fork.github.*' and then fetch again.

2. As an alternative, open Repository Manager (Cmd+T) and login to your GitHub account.

**Comment by tbm98** [comment]
<img width="557" alt="Screen Shot 2020-04-15 at 13 09 55" src="https://user-images.githubusercontent.com/52562340/79303993-7a8a9080-7f1a-11ea-905c-857ad1c2b1a1.png">
I was check and it seem logined

**Comment by tbm98** [comment]
I have logged out and logged back in. When logging in, request access to the source repo. After the admin has approved, it will work normally. :D
