### ISSUE TITLE
"Push 'master' to origin" always asks for repository password

### ISSUE THREAD

**Issue by robertmfuhrer** [ForkIssues/Tracker#982]
I'm running Fork 1.0.92 on MacOS High Sierra 10.13.6.

I've got a local clone of a Git repository, hosted remotely by my Mac Mini. Almost everything seems to be working correctly: I'm able to do almost everything I need, e.g. push/pull, etc. wrt the remote repo.

However, every time I do a master->"Push 'master' to origin...", Fork asks for the password.

I always check the "Remember in Keychain" option, but every time, the push/password dialog comes up with that checkbox unchecked.

I've looked in Keychain Access multiple times (after several push ops), and AFAICT, there's no relevant password recorded. (I've tried searching for anything with "fork" or "Fork" in the name, and all entries for the host name in question, of which there are several, but none related to Fork or Git.)

FWIW, I've browsed similar issues, and all were related to much older Fork versions (e.g. 1.0.56), and all were closed; hence I filed this new issue.

**Comment by DanPristupov** [comment]
> I've looked in Keychain Access multiple times (after several push ops), and AFAICT, there's no relevant password recorded.

First of all, try to restart computer. Keychain Access in macOS has glitches.

**Comment by robertmfuhrer** [comment]
FWIW, I rebooted, and no change. I also tried on another Mac laptop (freshly setup with Catalina 10.15.3), and I get the same behavior, with the exception that I *do* see a single Fork-related entry in Keychain Access, for github.com, which isn't the repo server I'm using for this project.

**Comment by DanPristupov** [comment]
During the last year we have reworked the accounts subsystem and now everything must be working properly. Please let me know if the problem is still actual.
