### ISSUE TITLE
How to access an organization's GitHub repositories that require SAML single sign-on (SSO)?

### ISSUE THREAD

**Issue by tatsuyafujisaki** [ForkIssues/Tracker#983]
Is there any way for Fork to clone/push/pull an organization's GitHub repository that requires SAML single sign-on (SSO)?

I have trouble getting Fork find such a repository.

Reference:
https://help.github.com/en/github/authenticating-to-github/about-authentication-with-saml-single-sign-on

**Comment by w0o** [comment]
I recall SAML did not work for me in the earlier versions but I still use fork to push/pull/etc when I manually add/open repos that were cloned over SSH. 
Anyhow, this should be added/fixed but hope the above helps.

**Comment by tatsuyafujisaki** [comment]
@w0o Thank you for the info! I will use another Git client for the time being.

**Comment by DanPristupov** [comment]
@tatsuyafujisaki as I see in your docs, you need to generate a personal access token and use it as a password.

**Comment by tatsuyafujisaki** [comment]
@DanPristupov Where in Fork do I enter my personal access token as a password?

**Comment by uvw** [comment]
Switching to my default Git installation fixed the issue. Select it in the Fork preferences once you get `git` working with a personal GitHub token in the console:

<img width="551" alt="Screen Shot 2020-05-01 at 2 17 16 PM" src="https://user-images.githubusercontent.com/1078682/80842511-a5c9dc80-8bb6-11ea-82e7-c840fb7f2bbb.png">

Should work similarly on Windows.

I guess the issue is that the Git bundled with Fork ("2.23.0 Fork instance" in the screenshot) uses a separate credentials store.

**Comment by tatsuyafujisaki** [comment]
@uvw Thanks for the help!

<img width="1679" src="https://user-images.githubusercontent.com/1838962/80850366-736fbc00-8c56-11ea-9235-3a6026c6ff7f.png">

However, I failed to get authenticated using a personal access token in Fork though I had succeeded in getting authenticated using it on Terminal. :thinking:

**Comment by uvw** [comment]
@tatsuyafujisaki That is weird. Once I switched to the same Git installation in Fork that I always use in terminal, I never got to this GitHub screen in Fork again.

Interesting, maybe there is a difference between SSO of various identity providers, or your SSO setup has something to do with this. For reference, I used GitHub+Fork with Azure AD and Okta before without this issue. 🤔

**Comment by tatsuyafujisaki** [comment]
@uvw My apologies. Now it worked for me! Earlier I mistakenly used another MacBook where I had not got authenticated using a personal access token on Terminal.

Thanks again for the help! :smiley:
