### ISSUE TITLE
"Nothing to do" error isn't an error.

### ISSUE THREAD

**Issue by matkatmusic** [ForkIssues/Tracker#994]
```
2020-04-26 18:03:46.564 fork_ri[21683:27420384] Start helper for editing git-rebase-todo.
Nothing to do
```
If you cancel an Interactive Rebase, you're greeted with this error popup.   It's not an error, so we shouldn't be told about it.

**Comment by DanPristupov** [comment]
What version of git do you use in Fork?

**Comment by matkatmusic** [comment]
2.17.2 (Apple Git-113)

**Comment by DanPristupov** [comment]
If I remember correctly this is a bug in git 2.17.2 where rebase returned error when there's nothing to do.

Update git or switch Fork to the internal git.
