### ISSUE TITLE
git: 'credential-osxkeychain' is not a git command.

### ISSUE THREAD

**Issue by jochenstu** [ForkIssues/Tracker#995]
`git: 'credential-osxkeychain' is not a git command.`

I have been having this issue when trying to connect to remotes with fork lately, but not when using git through the terminal. From what I gathered it seems to be related to an app using a different executable of credential-osxkeychain, that does not exist where it should. I don't know where it should tho.

Any pointers would be much appreciated. Thanks in advance.

**Comment by DanPristupov** [comment]
What does `git config --get credential.helper` command returns?
What git instance do you use in Fork? Try to switch it.

**Comment by jochenstu** [comment]
Switching the git instance in the Fork options worked for me. Thanks!
