### ISSUE TITLE
Fork doesn't seem to run git pre-commit hooks

### ISSUE THREAD

**Issue by denizdogan** [ForkIssues/Tracker#996]
For some reason Fork doesn't seem to run git pre-commit hooks but only on one specific local repository of mine. Another repostitory works fine.

The content of `.git/hooks/pre-commit` is:

```
#!/bin/sh
# husky

# Created by Husky v4.2.5 (https://github.com/typicode/husky#readme)
#   At: 4/11/2020, 4:43:26 PM
#   From: /Users/deniz/Code/elm/node_modules/husky (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
```

The content of `husky.sh` is pretty long and largely uninteresting. The file has been generated by the [husky npm package](https://www.npmjs.com/package/husky).

Is there any way to debug this in Fork? The hooks are properly executed in the CLI and in PyCharm.

**Comment by DanPristupov** [comment]
1. > Is there any way to debug this in Fork? 

Add `printenv` to your hook, then run `printenv` in CLI and compare PATH values.

2. Quick fix: run fork from CLI using `open -a Fork` command
https://github.com/ForkIssues/Tracker/issues/430#issuecomment-429013890

**Comment by denizdogan** [comment]
Thank you, I managed to solve this problem by adding the following to `~/.huskyrc`:

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```

...as described here:

https://github.com/typicode/husky/#node-version-managers

**Comment by do-adams** [comment]
I solved this by opening Fork with a `open-fork.sh` script:

```zsh
open -a Fork
exit
```

...and updating my `~/.huskyrc` file to:

```zsh
# This loads nvm.sh and sets the correct PATH before running hook

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# This runs nvm use, but if it fails (e.g., because .nvmrc is missing or specifies an invalid version), it will execute nvm use default

[ -f .nvmrc ] && nvm use || nvm use default
```

**Now, Fork, nvm + Node, and Husky are integrated through Git hooks** 😸

<hr>

This also adds automatic support for `.nvmrc` files. 

Note that you must have installed the Node version specified in `.nvmrc` for the Git hooks to run. Sometimes, you must also run `corepack enable` on that Node installation if your Husky hooks use another package manager like Yarn.

**Comment by DanPristupov** [comment]
@do-adams I think now you can simply switch `Fork -> Preferences -> Git -> Env mode` to `System Shell`
