### ISSUE TITLE
[Bug] Skip pre-commit hook while doing amend commit

### ISSUE THREAD

**Issue by carlosefonseca** [ForkIssues/Tracker#997]
Hi,

If I do an amend commit which triggers a pre-commit hook that fails and I click "skip pre-commit hook", the commit succeeds but leaves the changes view with the amend option enabled, leaving the staged changes in place.

Usually, when an amend commit occurs and the pre-commit hook alert doesn't show, the amend option is automatically disabled and the staged changes becomes empty.

Thanks

**Comment by carlosefonseca** [comment]
@DanPristupov Sorry to tag but there was no acknowledgment and this seems like a small-ish bug (but still annoying on the day to day work). Thank you.

**Comment by DanPristupov** [comment]
Thank you for reminding me 👍

**Comment by DanPristupov** [comment]
I fixed the problem in 2.7
