### ISSUE TITLE
fork error when rebasing with conflicts

### ISSUE THREAD

**Issue by boneskull** [ForkIssues/Tracker#998]
![image](https://user-images.githubusercontent.com/924465/80651729-48edeb00-8a2b-11ea-9417-be01f09eb444.png)

This occurred when I initialized a rebase from [here](https://github.com/nicojs/mocha/commit/1e28deafed1ae00953a5840ef2ab58fd99defca8) onto [here](https://github.com/mochajs/mocha/commit/400bf9b9319bdf8f0d9aa05ff8c7a54f6fe65d2a) via the CLI, then worked to resolve the conflicts via Fork & Kaleidoscope.

It seems to happen after I resolve the conflicts for every changeset, and click "Continue Rebase" in fork.

**Comment by DanPristupov** [comment]
I couldn't try your sample because I can't find 1e28deafe in the repo after clone. Did you force-push and removed it from the tree may be?

What git instance do you use?

**Comment by boneskull** [comment]
apologies, branch was deleted. if it comes up again i’ll update this issue.
